### ISSUE TITLE
Use better test data

### ISSUE THREAD

**Issue by shoshber** [poldracklab/fmriprep#100]
- shareable
- more diverse

**Comment by oesteban** [comment]
This will be derived from #105, when we have intermediate results.

**Comment by oesteban** [comment]
Hey team, do you think we could close this one?
- We have the downsampled datasets (I could add one subject of the beast if we wanted to circle)
- We have so many data from openfmri...

I think we opened this one based on the fact that we had to take down the very early datasets we were using and now they are replaced.

So, should we hit "close"?
