### ISSUE TITLE
Uncompressed nifti files are ignored

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#1005]
.nii input files are ignored probably caused by https://github.com/INCF/pybids/issues/133

See https://openneuro.org/datasets/ds001243/versions/00001?app=FMRIPREP&version=53&job=5a937975c7c1fc0001887029

**Comment by effigies** [comment]
As far as I can tell, that ran fine... I don't see any errors. It was run `--anat-only`, and ran the anatomical portion of the workflow.

**Comment by chrisfilo** [comment]
Sorry my bad.
