### ISSUE TITLE
Multi-echo: look at the TE to select first echo

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1009]
Since the BIDS spec does not impose an ordering with the naming (last-to-first or first-to-last), TEs should be looked into to select the "first" (shortest) echo.

Originally derived from #891.

**Comment by emdupre** [comment]
Is there any appetite for bringing this up as a discussion point for the BIDS spec ? I think it's reasonable to enforce a standardize ordering&mdash; it's an issue that's come up already in https://github.com/ME-ICA/me-ica/pull/5.

Regardless, I agree that having a built-in check can only be an additional benefit. I'll address this ASAP, but wanted to see if it was worth expanding the discussion to the BIDS list. cc @chrisfilo

**Comment by chrisfilo** [comment]
I think this would be a relatively small and not controversial change. If
you could send a quick email to the mailing list we could get the ball
rolling. Thanks for your continuing work on ME!

Best,
Chris

**Comment by emdupre** [comment]
Emailed the list, and opened #1018 to hopefully address this for FMRIPREP !

**Comment by oesteban** [comment]
Closed with #1018
