### ISSUE TITLE
Multi-echo and CircleCI: blue contours of BOLD-to-T1w reportlet missing

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1011]
Comes from #891

**Comment by emdupre** [comment]
To clarify, this concern is specific to using multi-echo T2* driven coregistration, not to multi-echo data generally !

It looks like this is an artifact of running our tests with down-sampled data; I imagine the anatomical, particularly. Running locally with 7c2c4f5eb959b48aef48a8b7d721f80bdfe71329 on a non-down-sampled dataset, it seems resolved both with recon-all:

<img width="1173" alt="t2s_w_reconall" src="https://user-images.githubusercontent.com/15017191/36807831-da99628c-1c91-11e8-830b-72776c534f80.png">

and without:

<img width="1174" alt="t2s_wout_reconall" src="https://user-images.githubusercontent.com/15017191/36825628-7f6d500e-1cd6-11e8-8220-0e5130518ca9.png">

Should we use a non-down-sampled anatomical to patch this ? I don't want to increase testing time unnecessarily, but I'd also prefer if tests reflected usage on real data !

**Comment by oesteban** [comment]
I'll check on this if I have some time in a future.

**Comment by oesteban** [comment]
This has been fixed.
