### ISSUE TITLE
Random errors running fmriprep (on OsX?)

### ISSUE THREAD

**Issue by treanus** [poldracklab/fmriprep#1012]
With ‘error’ I mean a failure in python execution - not e.g. the T1w image being misregistrated to MNI space. But an execution error of fmriprep itself. 

I’m running fmriprep on OsX (docker installation) on several datasets (multiple subjects, multiple sessions). 
Some datasets failed to complete workflows (python traceback error in the log). Initially I thought this may be due to datasets itself. 

However, running fmriprep repeatedly - starting from the original BIDS dataset -  on the same dataset/subject/session sometimes runs fine, sometimes fails.

I can replicate the error (or not - runs fine) by running fmriprep again on the same single dataset. 
In each ‘failed case’ the python traceback (or previous workflow) shows a “file not found error”. And when I check in the work/scratch directory: the file exists.

This may not directly be related to fmriprep, but (also) to nipype or docker.

I have:
- Datasets from multiple scanners (Philips/GE). All passed the bids validation. MRIQC runs without errors. mriqc works fine, in all datasets, all reruns!
- OsX 10.13.3. Tested fmriprep on multiple machines.
- Docker latest version (17.12.0-ce), set to run max cpu (8) and max ram (16G) in prefs.

A typical command can be: 
`docker run -it --rm -v /Users/xm52195/Dropbox/MIND_extra/BIDS:/data -v /Users/xm52195/Dropbox/MIND_extra/fmriprep_1:/out -v /Users/xm52195/Dropbox/MIND_extra/fmriprep_work_1:/scratch -v /Users/xm52195/apps/Freesurfer_License/license.txt:/opt/freesurfer/license.txt poldracklab/fmriprep:latest /data /out participant -w /scratch --fs-no-reconall --participant_label pat01`

What I have tried so far:

a) fresh install of docker, fresh dataset. May run fine. Or fail. Reset docker to factory settings (and download fmriprep again): may work or fail. Given docker enough mem and cpu. Unset docker experimental setting. 

b) running fmriprep-docker or fmriprep directly: same errors.

c) specifying --nthreads 1. Tends to run fine on more datasets (and of course takes more time to run), but still may fail.

d) since maybe the failure is due OsX volume mounts (see https://docs.docker.com/docker-for-mac/osxfs-caching/) and the delay in availability of the work (scratch) directory between the host and container:
- created a nipype.cfg with job_finished_timeout = 60 & poll_sleep_duration = 30
- mounted the nipype.cfg by running: 
`docker run -it --rm -v /Users/xm52195/Dropbox/MIND_extra/BIDS:/data -v /Users/xm52195/Dropbox/MIND_extra/fmriprep_1:/out -v /Users/xm52195/Dropbox/MIND_extra/fmriprep_work_1:/scratch -v /Users/xm52195/apps/Freesurfer_License/license.txt:/opt/freesurfer/license.txt -v /Users/xm52195/Dropbox/MIND_extra/nipype.cfg:/root/.nipype/nipype.cfg:ro poldracklab/fmriprep:latest /data /out participant -w /scratch --fs-no-reconall --stop-on-first-crash --nthreads 7 --mem-mb 14000 --participant_label pat01`

Still may fail.

**I guess I'm missing something trivial** and I'm debugging in the wrong direction...

Best regards,

Stefan.

**Comment by effigies** [comment]
I wonder if you're running into issues with your data (or at least your scratch directory) being synced on Dropbox. (I assume that `/users/xm52195/Dropbox` is an actively managed Dropbox directory.)

**Comment by chrisfilo** [comment]
I would also suggest trying not to mount scratch from the host and omitting the `-w` flag.

**Comment by treanus** [comment]
I've run it outside of dropbox as well with same errors... I will try the -w flag. Thank you @effigies and @chrisfilo for your amazing fast response!

**Comment by treanus** [comment]
This is probably a mac/osx only problem and related to docker https://github.com/docker/for-mac/issues/2625.

Upgrading to the new docker-for-mac Version 17.12.0-ce-mac55 (23011) and specifying your mounts as delegated seems to solve this. 

E.g:
`docker run -it --rm -v /Volumes/LaCie/MRIDATA/MIND/BIDS:/data:delegated -v /Volumes/LaCie/MRIDATA/MIND/fmriprep_force_syn:/out:delegated -v /Volumes/LaCie/MRIDATA/MIND/fmriprep_force_syn_work:/scratch:delegated -v /Users/xm52195/apps/Freesurfer_License/license.txt:/opt/freesurfer/license.txt poldracklab/fmriprep:latest /data /out participant -w /scratch --fs-no-reconall --stop-on-first-crash --nthreads 7 --mem-mb 14000 --force-syn --participant_label pat001`

I guess this issue can be closed.

**Comment by chrisfilo** [comment]
Thanks for figuring this out!
