### ISSUE TITLE
Turn SyN-SDC on by default

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#1023]
After looking through many reports last week I got the impression that SyN-SDC is performing very well in various situations. I think we should turn it on by default and let users turn it off with an optional flag. WDYT @oesteban @effigies?

**Comment by effigies** [comment]
Sure.

As to the flag, what would our default be with `--ignore fieldmaps`? Would that mean "Do not do SDC", or "Don't use fieldmaps, run SyN-SDC"? If the former, maybe we could deprecate `--ignore fieldmaps` for a more general `--ignore susceptibility` (or similar). If the latter, then we could just add a `--no-syn-sdc` flag.

I'm not entirely sure what the less surprising option would be.

**Comment by chrisfilo** [comment]
`--ignore` was meant for ignoring a particular part of the dataset when deciding what processing steps to perform. As such I think it should stay the way it is which means `--ignore fieldmaps` **should** run SyN-SDC unless `--no-syn-sdc` flag is provided.

**Comment by effigies** [comment]
Works for me.
