### ISSUE TITLE
Number of voxels in phase-encoding direction is not always equal to number of phase-encoding lines on Philips systems

### ISSUE THREAD

**Issue by Gilles86** [poldracklab/fmriprep#1029]
Heya,

I was looking into the code that calculates the effective echo spacing for Philips scans. This uses the number of voxels in the phase-encoding dimension as a proxy for (EPI train length * acceleration factor). 

https://github.com/poldracklab/fmriprep/blob/260872273a1f4ef02de2cae20dd7d6948b531c4b/fmriprep/interfaces/fmap.py#L327

However, especially on Philips systems, the "Acquisition matrix size" (corresponding to actual number of k-space lines), and the "Reconstruction matrix size" can sometimes be different, because Philips systems automatically select a reconstruction matrix size that is easy to reconstruct using the fast fourier transform (FFT; powers of 2). This is something we also sometimes do deliberately in our data because it might somewhat alleviate partial voluming.

Would it be an idea to first try to use the "epi_factor"-field (standard in Philips parrecs) to calculate the number of k-space lines before using the nifti dimensions?

(this is also reccomended here:
http://dbic.dartmouth.edu/pipermail/mrusers/attachments/20141112/eb1d20e6/attachment.pdf )

**Comment by Gilles86** [comment]
Yeah apparently they do not "trust" this field?
https://github.com/rordenlab/dcm2niix/blob/8fc0c514a7595d4afb8fac09091f5c54ecbf28ee/console/nii_dicom_batch.cpp#L829

In any case, if you have a different reconstruction vs acquisition matrix size, the DICOM will already have a different resolution from what was acquired. This should somehow be encoded in BIDS metadata I would argue.

**Comment by oesteban** [comment]
Hi @Gilles86, would you like to submit a PR from your sketch?

**Comment by oesteban** [comment]
I'll re-up this. @Gilles86, any possibility that you would send us a PR? That'd be really sweet - otherwise, I would try to cherry-pick your commits to maintain your authorship and that is prone to get pretty hairy.

**Comment by Gilles86** [comment]
I made a [pull request](https://github.com/poldracklab/fmriprep/pull/1489).

I was wondering: to what extent have you tested B0-map correction on open datasets? It seems that most of the stuff on openfmri does not provide B0 maps.

To be honest, at the Spinoza Centre in Amsterdam, I head from multiple people that the B0 correction of fmriprep usually over- or undercorrects their data and they switched to topup-procedures for this reason. Whether this is because of "their" confusion about meta-data or fmriprep itself is unclear to me. I myself have this issue as well, even though I'm 99.9% sure that my echo spacing times should be correct and the fieldmaps that Philips outputs are in Hz, fmriprep seems to considerably overcorrect my (7T) data.

In that context, this line:
https://github.com/poldracklab/fmriprep/blob/260872273a1f4ef02de2cae20dd7d6948b531c4b/fmriprep/interfaces/fmap.py#L326

Seems very dangerous to me. I don't think there is much fMRI data out there that does not use any acceleration (ParallelReductionFactorInPlane = 1) but needs B0 correction... What do you think?

**Comment by oesteban** [comment]
Thanks very much!

I can think of two solutions (not mutually exclusive):
- Skip fieldmap correction if the metadata is not set, with a message like "fMRIPrep cowardly skipped fieldmap correction because the MANDATORY metadata field "ParallelReductionFactorInPlane" was not set, please set it in the corresponding sidecar JSON file(s).
- Add a big warning to the output reports when the acc factor is 1.0, indicating that such factor is quite suspicious.

In general, I agree with your suggestion, although I think it is not recommended to use in-plane acceleration with new multiband sequences.

**Comment by oesteban** [comment]
Let's keep discussion on the new issue.
