### ISSUE TITLE
test elegant failure & report on bad/variable BIDS data

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#103]
Create several fake BIDS structures of empty files, with different combinations of subjects, modalities, sessions, tasks, acquisitions, and runs, and exercise #102 against it:
- [ ] Create the fake BIDS structures. Test a matrix of valid cases: `[one bold, several bold, no fieldmap, se-fmap, gre-fmap, se&gre-fmap, no sbref, sbref, no t1, t1, several t1, no t2, t2, several t2] x [one bold, several bold, no fieldmap, se-fmap, gre-fmap, se&gre-fmap, no sbref, sbref, no t1, t1, several t1, no t2, t2, several t2]`
- [ ] Create fake BIDS structures with problems:
  - [ ] there is SBRef but no corresponding bold
  - [ ] there is only one PE direction for SE-fieldmaps
  - [ ] there is only phasediff and no magnitude in fmap/
- [x] Write corresponding unit tests (automated, so that we can flexibly add more fake structures in the future without need of modifying the test code)
- [x] Remove any dependency in real data (https://github.com/shoshber/preprocessing-workflow/blob/nipypedep87/test/utils/test_misc.py#L15)

**Comment by oesteban** [comment]
We're moving this to pybids, is that correct @chrisfilo ?

**Comment by shoshber** [comment]
exactly which module is this supposed to test?

**Comment by shoshber** [comment]
also, I don't think this can be *fully* automated, unless I'm missing something important

**Comment by oesteban** [comment]
Well, the structures of fake files (```touch filename```) can be hard-coded or written in runtime from a tree or dictionary.

Particularly, I'd like this interface (https://github.com/oesteban/preprocessing-workflow/blob/master/fmriprep/interfaces/bids.py#L43) to catch all the problematic cases, discriminating by subjects (meaning, if only one subject is missing the bold image, then we shouldn't break all) and runs (meaning, if one subject has 5 runs whole but 1 is light of the bold then this subject can be processed on the 5 correct runs and we need to notice that one was omitted for having one image missing).

**Comment by shoshber** [comment]
Based on previous discussions, I think we will not worry about handling of datasets with varying subject data for now.

Let's wait on this issue until after it's moved to pybids, since that might change the code organization significantly
