### ISSUE TITLE
fmriprep-docker crashing due to intermittent permissions error

### ISSUE THREAD

**Issue by bbfrederick** [poldracklab/fmriprep#1039]
This occurs when running an analysis in a docker container on a Mac (macOS 10.13.3) using an external work directory.

The analysis stops seemingly at random, due to a permissions error.  Restarting the analysis (without changing anything) proceeds past the point of failure. The work directory is on an external drive with plenty of available space.

For some reason, the error shown below terminated fmriprep, but there are 4 crash logs (which I can also send if you're interested) that show that some processes terminated due to permissions or expected files not existing without stopping the analysis.  This sounds like a race condition writing files to the work directory - does docker do asynchronous writes to external directories?  We had a similar problem on an SGE cluster that mounted the work directories asynchronously...  This seems to be a known issue https://docs.docker.com/docker-for-mac/osxfs-caching/

Thanks,
Blaise

The command I ran was:
```
fmriprep-docker \
    /Volumes/data_external/hliu/bids-controls \
    /Volumes/data_external/hliu/bids-controls/derivatives \
    participant \
    --fs-license-file /Applications/freesurfer/license.txt \
    --n_cpus 4 \
    --verbose \
    --longitudinal \
    --use-syn-sdc \
    --fs-no-reconall \
    -w /Volumes/data_external/hliu/workdir \
    --resource-monitor \
    --nthreads 8 --omp-nthreads 4 --mem-mb 8000
```

The crash that stopped the analysis is here:
```
	 [Node] Setting-up "fmriprep_wf.single_subject_XWSN019PLL_wf.func_preproc_ses_D_task_rest_run_011_wf.bold_reg_wf.fsl_bbr_wf.select_transform" in "/scratch/fmriprep_wf/single_subject_XWSN019PLL_wf/func_preproc_ses_D_task_rest_run_011_wf/bold_reg_wf/fsl_bbr_wf/select_transform".
180404-02:38:02,341 workflow INFO:
	 [Node] Running "select_transform" ("niworkflows.nipype.interfaces.utility.base.Select")
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 339, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 498, in run
    self, report_type='postexec', is_mapnode=isinstance(self, MapNode))
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/utils.py", line 156, in write_report
    result = node.result  # Locally cache result
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 203, in result
    return _load_resultfile(self.output_dir(), self.name)[0]
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/utils.py", line 277, in load_resultfile
    pkl_file = gzip.open(resultsoutputfile, 'rb')
  File "/usr/local/miniconda/lib/python3.6/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/local/miniconda/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
PermissionError: [Errno 13] Permission denied: '/scratch/fmriprep_wf/single_subject_XWSN019PLL_wf/func_preproc_ses_D_task_rest_run_011_wf/bold_reg_wf/fsl_bbr_wf/select_transform/result_select_transform.pklz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.0.8', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 267, in main
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 602, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 190, in run
    self._send_procs_to_workers(updatehash=updatehash, graph=graph)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 347, in _send_procs_to_workers
    'traceback': traceback
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 228, in _clean_queue
    crashfile = self._report_crash(self.procs[jobid], result=result)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 215, in _report_crash
    return report_crash(node, traceback=tb)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/tools.py", line 29, in report_crash
    if node.result and getattr(node.result, 'runtime'):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 203, in result
    return _load_resultfile(self.output_dir(), self.name)[0]
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/utils.py", line 277, in load_resultfile
    pkl_file = gzip.open(resultsoutputfile, 'rb')
  File "/usr/local/miniconda/lib/python3.6/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/local/miniconda/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
PermissionError: [Errno 13] Permission denied: '/scratch/fmriprep_wf/single_subject_XWSN019PLL_wf/func_preproc_ses_D_task_rest_run_011_wf/bold_reg_wf/fsl_bbr_wf/select_transform/result_select_transform.pklz'
fMRIPrep: Please report errors to https://github.com/poldracklab/fmriprep/issues
```

**Comment by chrisfilo** [comment]
A potential workaround would be not to specify -w and thus use Docker
managed filesystem for working directory.

Best,
Chris

PS Apologies for brevity and potential typos. This message was composed on
a phone.

**Comment by effigies** [comment]
Filesystem synchronization issues are difficult for us to do much about, because they're so variable in cause. One option is to update the nipype configuration to use a longer `poll_sleep_duration`, which may give the changes more time to propagate before they need to be read, but it actually looks like this read may be happening within the same process that wrote the file, so I'm not sure that would help. It should, however, reduce the frequency of disk hits, which could help indirectly.

As a rule, though, I would generally recommend using local filesystems for your scratch directory. Local filesystems typically have stronger consistency guarantees than networked filesystems (an external hard drive seems like it should be treated more like a local FS than networked, but I'm unfamiliar with the Mac OS model). Additionally, they're likely to be faster, which also makes them more appropriate for nipype working directories.

And, as @chrisfilo says, you can omit the `-w` flag, but that will mean you start each fmriprep run from scratch, rather than picking up where you left off. I would do that as a last resort.

Finally, one thing worth considering is to update nipype to watch for errors like these, and attempt to wait and retry, to allow for FS synchronization. Since we're in a potentially erroring state, anyway, the performance cost of waiting a few seconds to allow sync issues to resolve themselves seems acceptable. @oesteban Any thoughts here?

**Comment by bbfrederick** [comment]
Yes, since the analysis takes around a day I want to preserve the ability to restart.  This is a locally connected external disk drive, not a network mount, btw.  I suppose I could try to twiddle the fstab to make sure the external disk is synchronously mounted, although that's still not a guarantee that is would stay in sync with the container.

Looking more in depth at the link I sent the implication is that the default is for Docker to use the "consistent" option, which implies synchronous writes, which would seem to indicate that this shouldn't happen.  I would think that the "cached" option would be better anyway - faster, and the container's view of the filesystem is authoritative.  So hard to say why this is happening.

**Comment by treanus** [comment]
Could be related to https://github.com/poldracklab/fmriprep/issues/1012.
I suggest mounting your volumes as "delegated".

**Comment by effigies** [comment]
Would it be useful to have `fmriprep-docker` mount volumes as delegated on OSX? Is there any down-side to doing this automatically, such that it makes sense to add an option, e.g., `--delegated-mounts`?

**Comment by oesteban** [comment]
Hi @bbfrederick, did mounting the volumes as "delegated" work for you?

**Comment by oesteban** [comment]
> Would it be useful to have fmriprep-docker mount volumes as delegated on OSX? Is there any down-side to doing this automatically, such that it makes sense to add an option, e.g., --delegated-mounts?

What about making it the default for OSX?

**Comment by oesteban** [comment]
Opened an issue for the `--delegated-mounts` option.

**Comment by praanja** [comment]
Hello, my fMRIprep crashes just before the HTML file with the report is generated into the folder everytime. How to fix this
