### ISSUE TITLE
save transforms in subject derivatives output directory

### ISSUE THREAD

**Issue by satra** [poldracklab/fmriprep#1042]
@effigies - i was just told that currently fmriprep does not save the transforms in the output. i think it would be good to do so such that we can go back and forth between the spaces (T1, freesurfer, MNI)

people are currently saving the workdir to pull out those files. 

perhaps this can be added as an option?

**Comment by oesteban** [comment]
The T1-to-MNI is written out under `anat/`.

True the BOLD-to-T1 is missing. Maybe worth also writing a "collapsed" BOLD-to-MNI.

**Comment by effigies** [comment]
So we should have T1w-to-MNI (and reverse), orig-to-T1w and T1w-to-fsnative (both affine). As @oesteban notes, we mainly lack BOLD-to-T1w (affine), but that hasn't been considered a problem, as we provide the BOLD series sampled in T1w, MNI and fsnative.

What specific transforms are still needed?

**Comment by chrisfilo** [comment]
@satra could you get us in touch with those users so we could understand better which transformations are needed?

**Comment by satra** [comment]
@chrisfilo - i'm going to close this issue - i just looked at an fmriprep output from a recent version. i see all the pieces i would need to go between spaces.

the person was trying to take this file to mni space: sub-001_task-all_run-1_bold_space-T1w_label-aparcaseg_roi.nii.gz

but i think the only thing it needs is the h5 file. i'll close this for now. if there is some residual issue, i will reopen.
