### ISSUE TITLE
Create a test sample of 10 subjects

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#105]
From the HCP, with the BIDS validator passing :)

**Comment by oesteban** [comment]
Hey @suyashdb , where do we stand with this? Can we close this one?

**Comment by suyashdb** [comment]
Hey @oesteban, I have still curated only and want to write a script first to use it for all dataset now and in future. Might take this week easily as per my understanding..

**Comment by shoshber** [comment]
Do we have an updated ETA on this?

**Comment by suyashdb** [comment]
I have created a sample bids dataset from HCP data without converting task events, physiological events files. 
If you are ok using bids dataset with proper nii and json files that this should work fine. 
dataset location: `/work/04275/suyashdb/lonestar/hcp2Bids_sampleds`
If there are any errors please me know.
