### ISSUE TITLE
KeyError: 'workflow' while reporting an error

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#1054]
I think there is an issue with error reporting. See the second traceback

```
Running poldracklab/fmriprep:1.0.9
_______________________________________________________
^@Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 336, in build_workflow
    bids_dir, participant_label=opts.participant_label)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/utils/bids.py", line 89, in collect_participants
    'may need to adjust your "File sharing" preferences.', bids_dir)
fmriprep.utils.bids.BIDSError: 
---------- BIDS root folder: "/snapshot/data" ----------
           Could not find participants. Please make sure the BIDS data structure is present and correct. Datasets can be validated online using the BIDS Validator (http://incf.github.io/bids-validator/).
If you are using Docker for Mac or Docker for Windows, you may need to adjust your "File sharing" preferences.
--------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.0.9', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 254, in main
    fmriprep_wf = retval['workflow']
  File "<string>", line 2, in __getitem__
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
KeyError: 'workflow'
```

**Comment by chrisfilo** [comment]
https://openneuro.org/datasets/ds000117/versions/00001/logs/FMRIPREP%2Fdefault%2F7ea4284f-c3a7-4dff-8dad-7e599de7666e

**Comment by isukrit** [comment]
sudo fmriprep-docker --fs-license-file /home/sukrit/Freesurfer_license/license.txt  /LMU_test /LMU_test_processed participant 

tree LMU_test
LMU_test
├── dataset_description.json
├── sub-01
│   └── ses-01
│       ├── anat
│       │   └── sub-01_ses-01_T1w.nii.gz
│       └── func
│           ├── sub-01_ses-01_task-rest_run-1_bold.nii.gz
│           ├── sub-01_ses-01_task-rest_run-2_bold.nii.gz
│           ├── sub-01_ses-01_task-rest_run-3_bold.nii.gz
│           └── sub-01_ses-01_task-rest_run-4_bold.nii.gz
└── task-rest_bold.json

4 directories, 7 files

**Comment by effigies** [comment]
You're running this from `/`, and `/LMU_test` passes the [BIDS validator](https://incf.github.io/bids-validator/)?

**Comment by isukrit** [comment]
I am running this from the parent dir of containing LMU_test and LMU_test_processed. /LMU_test passed the BIDS validator. :)
![image](https://user-images.githubusercontent.com/7867948/39461226-d9870068-4d3b-11e8-99e9-5fba27a91840.png)

**Comment by effigies** [comment]
If the parent directory of `LMU_test` and `LMU_test_processed` is not `/`, then you may want to add a `.` before the slashes. And you do not need `sudo`.

**Comment by imawla** [comment]
I just faced a similar issue running the following command:
`singularity run -B ./:$FS_LICENSE ${image} ./ ./output participant --participant-label=${participant}`

Here's what I get:
`Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 383, in build_workflow
    bids_dir, participant_label=opts.participant_label)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/utils/bids.py", line 89, in collect_participants
    'may need to adjust your "File sharing" preferences.', bids_dir)
fmriprep.utils.bids.BIDSError: 
---------- BIDS root folder: "/home/imawla" ----------
           Could not find participants. Please make sure the BIDS data structure is present and correct. Datasets can be validated online using the BIDS Validator (http://incf.github.io/bids-validator/).
If you are using Docker for Mac or Docker for Windows, you may need to adjust your "File sharing" preferences.`

I am using version 1.0.15. Any help appreciated.

**Comment by effigies** [comment]
Please open a new issue, share your command, error, and the listing of your data directory. (Here, `tree ./` from the same directory from which your command was run. Or `ls -r`, if you don't have `tree`.)

I assume you've validated your dataset?
