### ISSUE TITLE
Viewing data with FSLEyes

### ISSUE THREAD

**Issue by annickt** [poldracklab/fmriprep#1067]
Good morning,

I am not sure if this is fmriprep issue per se, but I thought frmiprep users probably encountered this before and found a solution. 
When I try to open the fmriprep preprocessed data in FSLeyes, I get the message : "an error occurred updating the texture data" Details ('Non-contiguous array passed', array ([0.,0.,0.,...,0.,0.,0.], dtype=float32.), (...)

If I do fslhd with the data file, I get: 
sizeof_hdr     348
data_type      FLOAT32
dim0           4
dim1           78
dim2           93
dim3           78
dim4           530
dim5           1
dim6           1
dim7           1
vox_units      mm
time_units     s
datatype       16
nbyper         4
bitpix         32
pixdim0        0.000000
pixdim1        2.500000
pixdim2        2.500000
pixdim3        2.500000
pixdim4        1.200000
pixdim5        0.000000
pixdim6        0.000000
pixdim7        0.000000
vox_offset     352
cal_max        1445.7714
cal_min        -70.9721
scl_slope      1.000000
scl_inter      0.000000
phase_dim      0
freq_dim       0
slice_dim      0
slice_name     Unknown
slice_code     0
slice_start    0
slice_end      0
slice_duration 0.000000
time_offset    0.000000
intent         Unknown
intent_code    0
intent_name    
intent_p1      0.000000
intent_p2      0.000000
intent_p3      0.000000
qform_name     Aligned Anat
qform_code     2
qto_xyz:1      2.500000  0.000000  0.000000  -96.000000
qto_xyz:2      0.000000  2.500000  0.000000  -132.000000
qto_xyz:3      0.000000  0.000000  2.500000  -78.000000
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
qform_xorient  Left-to-Right
qform_yorient  Posterior-to-Anterior
qform_zorient  Inferior-to-Superior
sform_name     Aligned Anat
sform_code     2
sto_xyz:1      2.500000  0.000000  0.000000  -96.000000
sto_xyz:2      0.000000  2.500000  0.000000  -132.000000
sto_xyz:3      0.000000  0.000000  2.500000  -78.000000
sto_xyz:4      0.000000  0.000000  0.000000  1.000000
sform_xorient  Left-to-Right
sform_yorient  Posterior-to-Anterior
sform_zorient  Inferior-to-Superior
file_type      NIFTI-1+
file_code      1
descrip        FSL5.0
aux_file    

Do you have thoughts on this fsleyes issue? Is there anything I can do to fix it? I get the same error on 2 computers (a mac and a ubuntu). On a side note, I believe it worked with fslview, but I can't use that anymore, unfortunately. 

Thanks a lot.

Annick

**Comment by annickt** [comment]
Hi Paul,

On a Mac and on a Ubuntu: 0.22.6 (separate computers, same error).

Did you want to see the image of the error? Here it is:


I hope it will show properly. I also attached it. Or did you want the
preprocessed data? If so, what is the best way to share data like that?

I really appreciate your help with this.

Annick
​

**Comment by chrisfilo** [comment]
Hi @annickt,
I'm afraid the image (?) didn't come through. Could you post it directly on github (instead of email reply). Thanks!

**Comment by annickt** [comment]
<img width="329" alt="screen shot 2018-04-24 at 1 52 00 pm" src="https://user-images.githubusercontent.com/32720853/39412211-e0140a4e-4be6-11e8-8f9e-c60ac268b7a4.png">

Thank you @chrisfilo , that should be better. Although I'm still wondering if "image" refers to preprocessed data. I don't have pilot data preprocessed (just "real" participants), but if that's helpful, I will make it happen!

**Comment by pauldmccarthy** [comment]
Definitely sounds like a bug in FSLeyes. Could you use dropbox or similar to share the image file? i.e. the preprocessed data file that causedLeyes to show the error.

In the meantime I will generate some random data with the same properties to see if I can reproduce the problem.

P.S. As this is obviously a FSLeyes issue, apologies for hijacking the fmriprep tracker!

P.P.S. @effigies - standalone mac builds are available [here](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FSLeyes), and should work - let me know if they don't!

**Comment by effigies** [comment]
@pauldmccarthy That worked. Not sure why last time I tried it didn't. Maybe there's been a fix. Or maybe my Mac has loosened up a little.

**Comment by pauldmccarthy** [comment]
Hey @dangom, unfortunately you need a gitlab account to create an issue. There is a [github mirror](https://github.com/pauldmccarthy/fsleyes) however - please raise an issue there (and perhaps @annickt, you could re-raise the present issue there too, so we can stop hassling the poor fmriprep people! :) )

**Comment by annickt** [comment]
Hello @pauldmccarthy <https://github.com/pauldmccarthy> ! Yes, good idea to
switch to a fsleyes!  I will open the issue there and at the same time, I
will share a problematic image via dropbox soon (probably tomorrow).

Annick Tanguay, B.A. (Spéc./ Hons.)
Candidate au doctorat/ PhD Candidate
Psychologie expérimentale/ Experimental Psychology
Laboratoire de neuropsychologie/ Neuropsychology Lab
Université d'Ottawa/ University of Ottawa

E: atang027@uottawa.ca
B: 613-562-5800 x 8757
RG: https://www.researchgate.net/profile/Annick_Tanguay
