### ISSUE TITLE
Release 1.0.11 did not make it to Zenodo

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1076]
cc @chrisfilo

**Comment by chrisfilo** [comment]
Opened an issue with Zenodo support

**Comment by oesteban** [comment]
Cool, thanks!

**Comment by oesteban** [comment]
Apparently, 1.0.12 worked out (https://zenodo.org/record/1240506#.WuyNHHUvzmE)

This might have been the hiccups.
