### ISSUE TITLE
Calculate regressors and save them in _confounds.tsv table

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#109]
- [x] confounds in native space
  - [x] Frame Displacement regressor (input is HMC movpar)
  - [x] after HMC & unwarping:
    - [x] White Matter, Grey Matter, CSF signal regressors, Global Signal regressor
    - [x] dvars
    - [x] TCompCor
    - [x] ACompCor
- [x] Put outputs in bids-derivatives according to standard
- [ ] integration test
- [ ] headers in confound file/derivative

**Comment by shoshber** [comment]
I have the same concern as in #44

**Comment by oesteban** [comment]
- For CompCor, please see https://github.com/nipy/nipype/issues/1594
- For the Global Signal and the tissue-wise signal regressors we could submit another new interface to nipype.

OR

- Have only one interface for all of this (ComCor, Global Signal, tissue-wise signal regressors).

In both cases, the FD regressor is a bit more complicated and we already have all the building blocks in place to generate it. That's why I would not mix it with the rest of them.

I prefer the two separated interfaces, and let it up to the user to merge all of them in a single file (using AddCSVColumn, for instance)

WDYT @chrisfilo ?

**Comment by shoshber** [comment]
@oesteban At your suggestion, I took a look at AddCSVColumn in nipype.algorithms.misc, and it doesn't match the requirements for this project as written--would you recommend I modify/refactor AddCSVColumn to make it work (may take longer, but perhaps more useful in the future), or write a simple T/CSV manipulation function just for this (less work now, but not as useful to others)?

**Comment by oesteban** [comment]
@shoshber @chrisfilo let's go for a quick and dirt implementation, probably just with something like `numpy.savetxt(delimiter='\t')`

**Comment by chrisfilo** [comment]
Agreed - or a Function Interface that uses pandas.

**Comment by shoshber** [comment]
Cool, time to learn me some pandas!

**Comment by oesteban** [comment]
pandas adds another dependency and it is probably overkill the problem, but as you want. Sooner or later pandas will end up as a dependency.

**Comment by chrisfilo** [comment]
You are right - it's probably an overkill.

**Comment by rwblair** [comment]
Pandas fatalism wins again.

**Comment by chrisfilo** [comment]
That's why they are endangered.

**Comment by shoshber** [comment]
Pandas make a comeback! http://www.cbsnews.com/videos/adorable-baby-pandas-make-their-debut-in-china/

Also I finished writing it before I saw these comments. So ...
