### ISSUE TITLE
Propagate TR from BIDS structure to NIfTI dims

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1093]
We may have forgotten setting the TR in some nodes (e.g. it was missing in both MELODIC and ICA-AROMA). We should set it in the ValidateImage node as a backup.

**Comment by effigies** [comment]
Were these inputs not BIDS validated? Or is it that somewhere in between `fsl.Split`, `MultiApplyTransform` and `nilearn.Merge` we lose the information? Does it make sense to just add it in `nilearn.Merge`?

**Comment by oesteban** [comment]
Related #1190

**Comment by oesteban** [comment]
I think this would be relatively easy to achieve within the `DerivativesDataSink`. We'll need a bit more of control logic, but reasonably easy to check whether there is a `RepetitionTime` metadata and set it in the NIfTI header. Transferring to niworkflows.

**Comment by oesteban** [comment]
Can't transfer across organizations. Closing manually.
