### ISSUE TITLE
Arrange a battery of OpenfMRI datasets (in BIDS)

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#112]
So we run the fmriprep on then easily, these data would live in /corral-repl

**Comment by suyashdb** [comment]
@oesteban dataset battery is under /corral-repl/utexas/poldracklab/openfmri/bids_dataset_battery. Please let me know if you have any question..

**Comment by oesteban** [comment]
All these datasets are passing the BIDS validator?

**Comment by oesteban** [comment]
Hi @suyashdb, can we close this issue? Are all datasets passing the validator?
