### ISSUE TITLE
multiple errors

### ISSUE THREAD

**Issue by danielkimmel** [poldracklab/fmriprep#1126]
Hello,

I'm running fmriprep 1.0.13 on a single subject. The process is completing but it's generating multiple errors that are opaque to me. I've attached the terminal output and the error logs. I'd be most grateful for any advice you have.

(BTW, unlike last time, I'm running on a well-spec'd machine, and so am not running into memory or storage limits).

Thanks so much for your help,
Daniel
[kimmel_errors_sub-18042401_2018_05_13.zip](https://github.com/poldracklab/fmriprep/files/1999100/kimmel_errors_sub-18042401_2018_05_13.zip)

**Comment by chrisfilo** [comment]
Hi,

Thanks for reporting. Nothing obvious stands out. Could you:
1) make sure your input data passes the BIDS validator https://github.com/INCF/bids-validator without error or warnings
2) try running FMRIPREP via Docker or Singularity

**Comment by danielkimmel** [comment]
Hi Chris,

Thanks for the super fast reply.

BIDS validator gives 0 errors, and 4 warnings:
1. slice timing not provided
2. no events.tsv file
3. not all subjects contain the same number of files (this is true, but I’m running in "single participant” mode)
4. not all subjects have same scanning params (this is true across participants, but not in a given participant — and running in single participant mode)

(In the past, these warnings have not caused me problems with fmriprep)

I’m running fmriprep in Docker already.

Any other thoughts?

Thanks again,
Daniel

**Comment by chrisfilo** [comment]
Maybe this is some FS sync issue (see you are using an external hard drive). Could you try without specifying a working directory (no `-w`)? Make sure docker has enough space (see Docker settings and `docker system prune` for cleanup).

**Comment by effigies** [comment]
I agree with @chrisfilo that the `FileNotFoundError`s are likely filesystem synchronization issues. I wonder if we can have nipype force a sync at the end of a node's execution. Otherwise, possibly you can try adding the following to your nipype config (you can pass with `--config`:

```Python
[execution]
job_finished_timeout = 5
```

This should force nipype to make sure that files are readable (but see nipy/nipype#2573 for caveats).

We're also seeing replications of #1127, so that at least is something that can be fixed on our end.

**Comment by effigies** [comment]
Well, to verify that they actually are filesystem sync issues, could you verify that you can find `fmriprep_wf/single_subject_18042401_wf/func_preproc_ses_001_task_context031_run_01_wf/bold_reg_wf/gen_ref/highres001_BrainExtractionBrain_reference.nii.gz` in your scratch directory?

**Comment by effigies** [comment]
Oh, I would also check to make sure that you have space in your working directory. These files may fail to be written for that reason.

Sorry for the multiple comments.

**Comment by danielkimmel** [comment]
Hi Chris-es

Thanks so much. I'll check on whether the file is present this evening (can't access the machine at the moment).

As for space in the working dir, there's plenty. That's why I went to the external disk. For what it's worth, I was having issues with the size of the scratch files (up to 70GB per participant!), and so couldn't keep the scratch on my internal disk. Is this common?

Thanks!
d

**Comment by effigies** [comment]
>  I was having issues with the size of the scratch files (up to 70GB per participant!), and so couldn't keep the scratch on my internal disk. Is this common?

Potentially. Every additional functional file will generate quite a lot of scratch files, and `--low-mem` will cause one or two full copies of the resampled functional series to be saved uncompressed in the scratch directory, if you're using that.

**Comment by oesteban** [comment]
Hi @danielkimmel, did you solve these issues?

**Comment by danielkimmel** [comment]
Hi Oscar

Thanks, I've moved things over to a 2TB share so that the scratch has plenty of room. I never tried the low-mem option.

Cheers,
Daniel
