### ISSUE TITLE
Testing: compare results across runs ?

### ISSUE THREAD

**Issue by emdupre** [poldracklab/fmriprep#1137]
Is there any interest in setting up circle testing so that it compares the results of fmriprep across CI runs ? I could imagine using something like `np.allclose`, which we're doing in [`tedana`](https://github.com/me-ica/tedana). A much lighter weight option could be to use `hashlib`. 

Right now fmriprep is confirming that the same derivatives are generated (i.e., that the derivatives are consistent with a log file), rather than that the derivatives themselves are the same. This alternate set up might be able to head off issues like #1131.

I know there's a lot of rapid development, and breaking changes in results are to be expected with some frequency, but I think there might be value in knowing as those points arise. Would love to know your thoughts !

**Comment by oesteban** [comment]
In MRIQC we check the MD5 hash of the nifti data array. I think this would be an awesome idea (although we already have monster tests so we may want to refine a bit).
