### ISSUE TITLE
DOC Freesurfer Derivative Usage Info

### ISSUE THREAD

**Issue by kastman** [poldracklab/fmriprep#1139]
Hi all,

Since freesurfer is the slowest part of fmriprep, I'm wondering about the best way to use previously-computed runs. It looks like fmriprep smart enough to check the BIDS derivatives folder because cached derivatives are explicitly downloaded in the circleCI config setup, but it might be useful to explicitly state the format and what's checked for as a guide within the fmriprep doc. I'm going to play around with it and write up a paragraph or two on using FS derivatives if I get it to make sense, but wanted to check whether you think that would be helpful as a DOC PR. It also wouldn't hurt to be explicit about using freesurfer runs in the working directory (and what the recommended lifespan of the working directory is, compared to the output directory), if there is a recommendation for provenance.

I also looked for issues where you might have discussed writing the outputs directly to the BIDS derivs folder (vs. keeping the BIDS input read-only and not touching it), but only #1057 discussing longitudinal inputs looks promising and only partly at that. Is that a design choice that was decided against? Again, maybe something to talk about in the doc.

Thanks for any guidance. I'm happy to PR some doc changes, as long as I'm understanding things correctly, but wanted to reach out early.

**Comment by chrisfilo** [comment]
This question comes up a lot so a dedicated easily findable paragraph would be fantastic to have. We would really appreciate such contribution.

As for storing derivatives... Not sure I fully understand the question, but it might be good to mention that you can mount a subfolder of a read-only mounted folder as a read-write folder (with multiple `-v` arguments in Docker).

**Comment by effigies** [comment]
Hi, thanks for the offer of help. I'll respond to some parts of this to hopefully give you some context.

@kastman:
> It looks like fmriprep smart enough to check the BIDS derivatives folder because cached derivatives are explicitly downloaded in the circleCI config setup, but it might be useful to explicitly state the format and what's checked for as a guide within the fmriprep doc.

From [the docs](https://fmriprep.readthedocs.io/en/latest/workflows.html#surface-preprocessing):

> In order to bypass reconstruction in fmriprep, place existing reconstructed subjects in <output dir>/freesurfer prior to the run. fmriprep will perform any missing recon-all steps, but will not perform any steps whose outputs already exist.

@kastman:
>  I'm going to play around with it and write up a paragraph or two on using FS derivatives if I get it to make sense, but wanted to check whether you think that would be helpful as a DOC PR.

Sounds good to me. I tried to convey this idea in the above section, but it's either too buried or insufficiently clear. Your suggestions as a user would be appreciated.

@kastman:
> It also wouldn't hurt to be explicit about using freesurfer runs in the working directory (and what the recommended lifespan of the working directory is, compared to the output directory)

I'm not sure I understand what you mean about using freesurfer runs in the working directory. As the lifespan, I would keep it as long as you feel you might re-run part of your data. For example, if you're still collecting data, on the off chance you find a bug when trying to process new participants, it would be good to be able to run any fixes on your entire dataset. Keeping the working directory around will allow you to only re-run the parts that change.

@kastman:
> I also looked for issues where you might have discussed writing the outputs directly to the BIDS derivs folder (vs. keeping the BIDS input read-only and not touching it), but only #1057 discussing longitudinal inputs looks promising and only partly at that. Is that a design choice that was decided against?

This is mostly a function of the BIDS-App model, which separates input directory from output directory. There's nothing stopping you from running:

```
fmriprep $DATASET $DATASET/derivatives participant
```

We just don't assume that you want that. And personally, I would keep the derivative dataset separate until I'm satisfied that I won't want to change it (e.g. it's publication time so we need a full snapshot), at which point I would move it into the proper `derivatives/` directory.

**Comment by kastman** [comment]
Thanks both, those are helpful for clearing up my misconceptions. 

Sorry, even though it's pretty clear in the docs (both the surface reconstruction bit and the fs derivatives output bit) I had it in my head that fmriprep was leaving the freesurfer output only in the working directory and not copying it out. I think this is because I was only looking in the `fmriprep` directory inside the output directory; even though `freesurfer` was there it wasn't sinking in that this was a direct output of fmriprep. So another way of saying this is to list where fmriprep checks for freesurfer runs: 1. in output/freesurfer, 2. in BIDS/derivatives/freesurfer. Giving a full example path would also be helpful, since even though I'm roughly familiar with the spec and derivatives I have no existing known good examples of a working exact tree path ("a directory named derivatives containing a directory named freesurfer containing a directory named "sub-NNN" which is a freesurfer run...") 

> As for storing derivatives... Not sure I fully understand the question, but it might be good to mention that you can mount a subfolder of a read-only mounted folder as a read-write folder (with multiple -v arguments in Docker).

@chrisfilo The layered mounting sounds tricky but interesting, though I don't think we'd need it. 

@effigies:

> And personally, I would keep the derivative dataset separate until I'm satisfied that I won't want to change it (e.g. it's publication time so we need a full snapshot), at which point I would move it into the proper derivatives/ directory.

Now that I get it it, I think this is actually the only point I would add to the doc, but I would be explicit about both the freesurfer derivatives as well as the fmriprep derivatives. Being explicit about this step helps sign-post examples of exactly where fmriprep itself will look.

I'm going to test that I'm really getting this right, and then maybe play around with adding a few sentences. Thanks for the pointers,

**Comment by effigies** [comment]
> So another way of saying this is to list where fmriprep checks for freesurfer runs: 1. in output/freesurfer, 2. in BIDS/derivatives/freesurfer.

Just FYI, we only check `BIDS/derivatives/freesurfer` if `output == BIDS/derivatives`.

**Comment by kastman** [comment]
Oh, as a user, that’s surprising. Was that a design choice you made on purpose? Seems like knowing “where to look” is the whole purpose of the spec, and not looking in the “right place” is both confusing and removes a lot of the incentive of using a spec in the first place, no?

**Comment by kastman** [comment]
Got it. I think an early fail would be totally acceptable (check for an incomplete reconstruction, e.g. that all required fs inputs exist) and fail with a useful error before processing so the user can remove the bad recon themselves. I'll take a look tomorrow to see if that's an easy enough fix that I can drop in, vs. someone more familiar with the project.

Even if you didn't use them, I'd definitely at least warn the user "hey, freesurfer derivatives exist in the BIDS folder, but since they're not in the derivatives folder we're going to re-run them now".
