### ISSUE TITLE
Suboptimal scaling of some confounds in reports

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#1143]
![image](https://user-images.githubusercontent.com/238759/40269233-e4cd8862-5b40-11e8-8ba4-9c5a79a2913b.png)

It's hard to see variation in WM and CSF with this scaling.

**Comment by oesteban** [comment]
Moved to poldracklab/niworkfows#242, since now these plots are composed in niworkflows proper.
