### ISSUE TITLE
FS license suddenly stopped working

### ISSUE THREAD

**Issue by shirareznik** [poldracklab/fmriprep#1144]
Hi,

I've successfully executed the pipeline once with the command:

`fmriprep-docker --debug  --fs-license-file D:\fmri_processing\toolboxes\license.txt input_path output_path`

and on the last execution
(command:
`fmriprep-docker --debug --cifti-output  --fs-license-file D:\fmri_processing\toolboxes\license.txt input_path output_path`

I got:

\nwriting expanded surface to midthickness...\nStandard error:\n--------------------------------------------------------------------------\nERROR: FreeSurfer license file /opt/freesurfer/license.txt not found.\n If you are outside the NMR-Martinos Center,\n go to http://surfer.nmr.mgh.harvard.edu/registration.html to \n get a valid license file (it\'s free).\n If you are inside the NMR-Martinos Center,\n make sure to source the standard environment.\n A path to an alternative license file can also be\n specified with the FS_LICENSE environmental variable.\n--------------------------------------------------------------------------\nReturn code: 255\n', ' File "bin/fmriprep", line 11, in <module>', ' File "fmriprep/cli/run.py", line 314, in main', ' File "niworkflows/nipype/pipeline/engine/workflows.py", line 595, in run', ' File "niworkflows/nipype/pipeline/plugins/base.py", line 168, in run', ' File "niworkflows/nipype/pipeline/plugins/base.py", line 227, in _clean_queue'] fMRIPrep: Please report errors to https://github.com/poldracklab/fmriprep/issues

Thanks!

BTW- can I somehow execute it from that stage, or I must run all the pipeline again?

**Comment by effigies** [comment]
Can you share the docker command that is generated (should be the first line output by `fmriprep-docker`)? And can you verify that `D:\fmri_processing\toolboxes\license.txt` still exists, is readable and is valid?

> BTW- can I somehow execute it from that stage, or I must run all the pipeline again?

If you use the `-w` flag to use a working directory mounted from your host, yes. On the other hand, this may cause issues in Docker for Windows.

**Comment by shirareznik** [comment]
Of course-
Will send the command in about 9 hours from now.
Thank you for the quick response!

**Comment by shirareznik** [comment]
Hi,

I couldn't get to that line  of the mentioned execution (text exceeded buffer length), and on the last execution I've copied the file to another location (yes- I've checked it's existence. regarding validness- it worked in a former execution without an error, the only difference I can think of between the successful and failed execution was the addition of the --cifti output flag).
 In the last execution I've slightly changed the options (and copied the license to another location), but here it is:
```
RUNNING: docker run --rm -it -v D:\license.txt:/opt/freesurfer/license.txt:ro -v D:\bids\filt:/data:ro -v D:\output3:/out -v C:\Users\shirarez\1mm:/imports/1mm:ro poldracklab/fmriprep:1.0.12 /data /out participant --debug --template-resampling-grid 1mm
180520-19:01:18,561 workflow IMPORTANT:

    Running fMRIPREP version 1.0.12:
      * BIDS dataset path: /data.
      * Participant list: ['005', '006', '007', '008'].
      * Run identifier: 20180520-190118_98d7ef86-9a76-4b80-a232-6be62fdaf83a.

```
Thanks!
Shira

**Comment by effigies** [comment]
Can you try upgrading `fmriprep-docker` to the latest version?

```
pip install --upgrade fmriprep-docker
```

**Comment by shirareznik** [comment]
Hi,

I've upgraded, and now I'm facing the following issue-
last executions end with the following error:
180521-18:55:35,126 workflow INFO:
         [Node] Setting-up "_fix_surfs6" in
"/root/src/fmriprep/work/fmriprep_wf/single_subject_008_wf/anat_preproc_wf/surface_recon_wf/gifti_surface_wf/fix_surfs/mapflow/_fix_surfs6".
180521-18:55:35,126 workflow INFO:
         [Node] Cached "_fix_surfs6" - collecting precomputed outputs
180521-18:55:35,126 workflow INFO:
         [Node] "_fix_surfs6" found cached.
180521-18:55:35,127 workflow INFO:
         [Node] Setting-up "_fix_surfs7" in
"/root/src/fmriprep/work/fmriprep_wf/single_subject_008_wf/anat_preproc_wf/surface_recon_wf/gifti_surface_wf/fix_surfs/mapflow/_fix_surfs7".
180521-18:55:35,128 workflow INFO:
         [Node] Cached "_fix_surfs7" - collecting precomputed outputs
180521-18:55:35,128 workflow INFO:
         [Node] "_fix_surfs7" found cached.
180521-18:55:35,130 workflow INFO:
         [Node] Finished
"fmriprep_wf.single_subject_008_wf.anat_preproc_wf.surface_recon_wf.gifti_surface_wf.fix_surfs".
ERRO[90234] error waiting for container: EOF
fMRIPrep: Please report errors to
https://github.com/poldracklab/fmriprep/issues

would appreciate your help ASAP.

Many thanks!

**Comment by shirareznik** [comment]
Correction- I've checked and this execution was a pre upgrade execution-
when the current execution will end- I'll write an update.
Thanks!

**Comment by shirareznik** [comment]
Update:
after updating-
the pipeline got stuck at:
180524-20:50:16,758 workflow INFO:
         [Node] Setting-up "_update_metadata0" in
"/root/src/fmriprep/work/fmriprep_wf/single_subject_005_wf/func_preproc_task_BAT1_wf/bold_surf_wf/update_metadata/mapflow/_update_metadata0".
180524-20:50:16,759 workflow INFO:
         [Node] Cached "_update_metadata0" - collecting precomputed outputs
180524-20:50:16,760 workflow INFO:
         [Node] "_update_metadata0" found cached.
180524-20:50:16,761 workflow INFO:
         [Node] Setting-up "_update_metadata1" in
"/root/src/fmriprep/work/fmriprep_wf/single_subject_005_wf/func_preproc_task_BAT1_wf/bold_surf_wf/update_metadata/mapflow/_update_metadata1".
180524-20:50:16,762 workflow INFO:
         [Node] Cached "_update_metadata1" - collecting precomputed outputs
180524-20:50:16,762 workflow INFO:
         [Node] "_update_metadata1" found cached.
180524-20:50:16,763 workflow INFO:
         [Node] Finished
"fmriprep_wf.single_subject_005_wf.func_preproc_task_BAT1_wf.bold_surf_wf.update_metadata".


I can find most of the files, but the reports are missing (no line after
this line in the console).
What stages were missed?
How can one figure out why it got stuck?
(BTW- Why is the logging is only to the prompt and not to some file? I've
added a debug flag)

Thanks!

**Comment by chrisfilo** [comment]
Some questions:
- When you say "stuck" how long did you wait for? Do you see any CPU activity?
- Could you try a fresh run with empty contents of the `output_path` folder?
- Could you tell more about your setup (windows? mac? how many cores/memory did you enable in docker settings?

**Comment by shirareznik** [comment]
1. This state lasted 2 days
2. This output directory was empty when I've started this execution
3. Docker for Windows, 6 cores, about 8-9 GB
Though it seems from Windows that the docker doesn't utilize of the
allocated memory, for some reason...

Many thanks for your help!
(Will now connect and check for CPU activity)

**Comment by shirareznik** [comment]
Yes, I will.
Thank you!
I wanted to ask for some hardware requirements- I don't remember seeing any
guidance in the documentation, but it could be that I've missed it.
Something like a table with hardware equipment on one column  and expected
execution time on the other column would have been really helpful.
Thank again!

**Comment by shirareznik** [comment]
BTW- according to the stage mentioned in the log- what files except for the
reports are likely to be missing from this execution?
Thanks again.

**Comment by chrisfilo** [comment]
Could you try with latest version of FMRIPREP and without
specifying/mounting the working directory?

Best,
Chris

PS Apologies for brevity and potential typos. This message was composed on
a phone.

**Comment by shirareznik** [comment]
Hi,

Of course- will try that in few hours from now and update (seems
reasonable, indeed, that this causes the error...)

Thanks!

**Comment by shirareznik** [comment]
Indeed- doesn't reproduce without the w option.

Regarding hardware recommendations- 
recommended memory and cores number  (and any other hardware tip)  would be appreciated.
Thanks

**Comment by oesteban** [comment]
Hi @shirareznik, did you  manage to fix this problem?

**Comment by shirareznik** [comment]
Hi
@oesteban ,

Regarding the original issue- I wasn't able to reproduce it since.

Regarding the working directory specification-
if I don't use the working directory option (which is a useful option, to my opinion)- it works.
 I would be happy to know when this option becomes available for docker for Windows users (I know that it depends on docker too).

Many thanks

**Comment by oesteban** [comment]
Hi @shirareznik, can you try using the `-w` option with a new option in the latest release (1.1.3) to set the user id?.

Something like:

```
fmriprep-docker -u $( id -u ) -w work_directory/ .....
```

Please let me know whether this worked for you.

**Comment by oesteban** [comment]
Hi @shirareznik, did my latest suggestion make any difference?

**Comment by shirareznik** [comment]
Many thanks- will check and update soon!
Sorry for the delay!

**Comment by shirareznik** [comment]
Hi Oscar!
Sorry for the delay in my response- after updating to the current version-
this option works fine!
Many thanks for your help!

**Comment by oesteban** [comment]
Thanks! Great you got it sorted out!
