### ISSUE TITLE
fmriprep-docker is taking too long.

### ISSUE THREAD

**Issue by AzmatUllahKhan** [poldracklab/fmriprep#1147]
I ran fmriprep-docker on 17 subjects data. It is fourth day and still it is running. Is it possible to reduce the time?

**Comment by chrisfilo** [comment]
What hardware are you using? Which operating system is it?

**Comment by effigies** [comment]
Two further questions:

1) What is the size of your dataset? i.e. How many of each type of image does each subject have, and how many BOLD volumes in total?
2) What is the command line you're running? Please post both the `fmriprep-docker` command line and the version of `fmriprep` you're running.

And a couple notes:

1) You can expect FreeSurfer to take somewhere on the order of 6 hours per subject on a reasonably well-spec'd machine. Potentially twice that on a slower system.
2) If your instance is being forced into swap, you're going to spend much more time.
3) If you have access to a cluster, you should be able to get significant speed-ups by running each subject with its own node. If you do not have access to a cluster, you may want to consider running fMRIPrep on [OpenNeuro](https://openneuro.org) (be sure to read the [FAQ](https://openneuro.org/faq)).

**Comment by AzmatUllahKhan** [comment]
The PC i am using is
Processor: Intel® Core™ i7-4770 CPU @ 3.40GHz × 8 
Memory: 24GiB RAM
Disk: 2Tb

Size of dataset is 7Gb. Below is the folder tree of each subject.
sub-1
├── anat
│   ├── sub-1_T1w.json
│   └── sub-1_T1w.nii
└── func
    ├── sub-1_task-rest_bold.json
    └── sub-1_task-rest_bold.nii

Below is the code i am running.
sudo fmriprep-docker /media/azmat/Data/645_ses1/ /media/azmat/Data/645_ses1/Preprocessed/ participant --fs-license-file /usr/local/freesurfer/license.txt

**Comment by effigies** [comment]
Okay. With those specs, Since you're running FreeSurfer and using the MNI output space, I would expect about 7 hours per subject for the anatomical portion of fMRIPrep. While there will be a slight speedup from parallelism, the most time-consuming parts of these will use 7 cores, so let's call that 119 hours or 5 days.

So it's not unreasonable for you to have gotten to five days at this point.

**Comment by AzmatUllahKhan** [comment]
What if i preprocess it on OpenNeuro?

**Comment by chrisfilo** [comment]
It should be faster, but I would convert .nii to .nii.gz to save space and
shorten upload time.

Best,
Chris

PS Apologies for brevity and potential typos. This message was composed on
a phone.

**Comment by oesteban** [comment]
Hi @AzmatUllahKhan, did you overcome your issues?

**Comment by oesteban** [comment]
Hi @AzmatUllahKhan, you could also reduce the run time avoiding FreeSurfer's surface reconstruction with the flag `--fs-no-reconall`. As a consequence, you will not be able to perform any surface-based analysis with the preprocessed results.

Please reopen if you have further questions.

**Comment by AzmatUllahKhan** [comment]
Hi @oesteban, preprocessing of my dataset is done, it took pretty much of my time.
Thankyou for your help.

**Comment by isukrit** [comment]
Hi @oesteban, will the --fs-no-reconall flag affect the quality of functional preprocessing in any way? I am only interested in functional data, so I was wondering if I could use it to save time while preprocessing.

**Comment by effigies** [comment]
@isukrit The quality of BOLD-T1w registration is generally much better with FreeSurfer's `bbregister`, which was the primary reason for including it in the first place. It's a heavy cost, if you have no interest in analyzing your data on the surface, however. You could try with `--fs-no-reconall` and see whether you're happy with the quality of FLIRT's registration.

**Comment by oesteban** [comment]
Totally agreed. FLIRT will be less robust with: a) low resolution EPIs; and b) low quality T1w resulting in noisy segmentations with FSL FAST.

**Comment by isukrit** [comment]
I will check it for different files and update you. But from preliminary analysis the results seem to be fine.
