### ISSUE TITLE
fieldmap

### ISSUE THREAD

**Issue by bidhanlamichhane** [poldracklab/fmriprep#1148]
Hello, I have received following error while running fmriprep-docker: 
as :   "fmriprep-docker --fs-license-file $FREESURFER_HOM  /Users/.../Desktop/BIDS/Test_data/sub-001 /Users/.../Desktop/BIDS/Test_data002/" and my  subject's data folder consists of : anat/fmap/func data collected using CMRR and multi-band factor: 4

Running fMRIPREP version 1.0.15:
      * BIDS dataset path: /data.
      * Participant list: ['sub-002'].
      * Run identifier: 20180527-184833_a0043697-6e85-443e-939d-7794bbf24eab.
    
180527-18:48:34,638 workflow IMPORTANT:
	 Creating bold processing workflow for "/data/sub-001/ses-01/func/sub-001_ses-01_task-reward_......._run-01_bold.nii.gz" (0.26 GB / 368 TRs). Memory resampled/largemem=1.06/2.03 GB.
180527-18:48:35,776 workflow IMPORTANT:
	 Slice-timing correction will be included.
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 510, in build_workflow
    ignore_aroma_err=opts.ignore_aroma_denoising_errors,
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 202, in init_fmriprep_wf
    ignore_aroma_err=ignore_aroma_err)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 458, in init_single_subject_wf
    ignore_aroma_err=ignore_aroma_err)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/bold/base.py", line 401, in init_func_preproc_wf
    debug=debug, fmap_demean=fmap_demean, fmap_bspline=fmap_bspline)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/fieldmap/base.py", line 178, in init_sdc_wf
    name='pepolar_unwarp_wf')
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/fieldmap/pepolar.py", line 97, in init_pepolar_unwarp_wf
    raise Exception("None of the discovered fieldmaps has the right "
Exception: None of the discovered fieldmaps has the right phase encoding direction. Possibly a problem with metadata. If not, rerun with '--ignore fieldmaps' to skip distortion correction step.

**Comment by chrisfilo** [comment]
Could you share the metadata (content of the JSON files) from func and fmap
folders? Does this dataset pass the validator (
https://github.com/INCF/bids-validator) without warnings?

BTW - this is unrelated, but you should increase the amount of memory (RAM)
accessible to Docker. 2gb is not enough. You can change this in Docker
settings.

**Comment by bidhanlamichhane** [comment]
Hello,
Thanks you so much for your quick response:
Please find JSON files ( bold and fmap) for one of my task run attached.




Thanks
Bidhan Lamichhane



On May 27, 2018, at 2:51 PM, Chris Filo Gorgolewski <notifications@github.com<mailto:notifications@github.com>> wrote:

Could you share the metadata (content of the JSON files) from func and fmap
folders? Does this dataset pass the validator (
https://github.com/INCF/bids-validator) without warnings?

BTW - this is unrelated, but you should increase the amount of memory (RAM)
accessible to Docker. 2gb is not enough. You can change this in Docker
settings.

**Comment by chrisfilo** [comment]
Attachments don't work over email when sent to ggithub. Please include the content of your JSON files in the body of the message.

**Comment by bidhanlamichhane** [comment]
No problem, below is the copy-paste of json files .  YES  this data passed validator.
Thanks
Bidhan

BOLD JSON: (*002_ses-01_task-reward_acq-multiband2p4flatAP_run-01_bold.json)

Modality        "MR"
MagneticFieldStrength   3
Manufacturer    "Siemens"
ManufacturersModelName  "Prisma_fit"
InstitutionName "Center_for_Clinical_Imaging_Research"
InstitutionalDepartmentName     "WP-MR30A"
InstitutionAddress      "South_Kingshighway_510_Saint_Louis_MO_US_63110"
DeviceSerialNumber      "167047"
StationName     "CCIRWP-MR30A"
BodyPartExamined        "BRAIN"
PatientPosition "HFS"
ProcedureStepDescription        "CCIR-00900_CCIR-0987_Braver"
SoftwareVersions        "syngo_MR_E11"
MRAcquisitionType       "2D"
SeriesDescription       "CMRR_fMRI_TASK_AP_2.4mm_368meas"
ProtocolName    "CMRR_fMRI_TASK_AP_2.4mm_368meas"
ScanningSequence        "EP"
SequenceVariant "SK_SS"
ScanOptions     "FS_EXT"
SequenceName    "epfid2d1_96"
ImageType
0       "ORIGINAL"
1       "PRIMARY"
2       "M"
3       "MB"
4       "ND"
5       "NORM"
6       "MOSAIC"
SeriesNumber    18
AcquisitionTime "15:29:35.875000"
AcquisitionNumber       1
ImageComments   "Unaliased_MB4_PE3_LB"
SliceThickness  2.4
SpacingBetweenSlices    2.4
SAR     0.044071
EchoTime        0.03
RepetitionTime  1.2
FlipAngle       52
PartialFourier  1
BaseResolution  96
ShimSetting
0       4608
1       7714
2       1602
3       416
4       7
5       95
6       -35
7       -18
TxRefAmp        239.132
PhaseResolution 1
ReceiveCoilName "Head_32"
ReceiveCoilActiveElements       "HEA;HEP"
PulseSequenceDetails    "%CustomerSeq%_cmrr_mbep2d_bold"
ConsistencyInfo "N4_VE11C_LATEST_20160120"
MultibandAccelerationFactor     4
PercentPhaseFOV 100
EchoTrainLength 96
PhaseEncodingSteps      96
AcquisitionMatrixPE     96
ReconMatrixPE   96
BandwidthPerPixelPhaseEncode    21.259
EffectiveEchoSpacing    0.000489989
DerivedVendorReportedEchoSpacing        0.000489989
TotalReadoutTime        0.0465489
PixelBandwidth  2605
DwellTime       0.000002
PhaseEncodingDirection  "j-"
SliceTiming
0       0
1       0.6275
2       0.0775
3       0.7075
4       0.155
5       0.785
6       0.235
7       0.865
8       0.3125
9       0.9425
10      0.3925
11      1.0225
12      0.47
13      1.1
14      0.55
15      0
16      0.6275
17      0.0775
18      0.7075
19      0.155
20      0.785
21      0.235
22      0.865
23      0.3125
24      0.9425
25      0.3925
26      1.0225
27      0.47
28      1.1
29      0.55
30      0
31      0.6275
32      0.0775
33      0.7075
34      0.155
35      0.785
36      0.235
37      0.865
38      0.3125
39      0.9425
40      0.3925
41      1.0225
42      0.47
43      1.1
44      0.55
45      0
46      0.6275
47      0.0775
48      0.7075
49      0.155
50      0.785
51      0.235
52      0.865
53      0.3125
54      0.9425
55      0.3925
56      1.0225
57      0.47
58      1.1
59      0.55
ImageOrientationPatientDICOM
0       0.999268
1       -0.00126896
2       -0.0382435
3       -0.00331375
4       0.992825
5       -0.119529
InPlanePhaseEncodingDirectionDICOM      "COL"
ConversionSoftware      "dcm2niix"
TaskName        "reward"
ConversionSoftwareVersion       "v1.0.20180328 (OpenJPEG build) Clang8.1.0"



FMAP JASON: (*002/ses-01/fmap/sub-MOCCAG002_ses-01_acq-multiband2p4flatAP_run-01_epi.json)

Modality        "MR"
MagneticFieldStrength   3
Manufacturer    "Siemens"
ManufacturersModelName  "Prisma_fit"
InstitutionName "Center_for_Clinical_Imaging_Research"
InstitutionalDepartmentName     "WP-MR30A"
InstitutionAddress      "South_Kingshighway_510_Saint_Louis_MO_US_63110"
DeviceSerialNumber      "167047"
StationName     "CCIRWP-MR30A"
BodyPartExamined        "BRAIN"
PatientPosition "HFS"
ProcedureStepDescription        "CCIR-00900_CCIR-0987_Braver"
SoftwareVersions        "syngo_MR_E11"
MRAcquisitionType       "2D"
SeriesDescription       "SpinEchoFieldMap_AP_2.4mm"
ProtocolName    "SpinEchoFieldMap_AP_2.4mm"
ScanningSequence        "EP"
SequenceVariant "SK"
ScanOptions     "FS"
SequenceName    "epse2d1_96"
ImageType
0       "ORIGINAL"
1       "PRIMARY"
2       "M"
3       "ND"
4       "MOSAIC"
SeriesNumber    9
AcquisitionTime "15:07:1.167500"
AcquisitionNumber       1
SliceThickness  2.4
SpacingBetweenSlices    2.4
SAR     0.126468
EchoTime        0.066
RepetitionTime  8
FlipAngle       90
PartialFourier  1
BaseResolution  96
ShimSetting
0       4608
1       7714
2       1602
3       416
4       7
5       95
6       -35
7       -18
TxRefAmp        239.132
PhaseResolution 1
ReceiveCoilName "Head_32"
ReceiveCoilActiveElements       "HEA;HEP"
PulseSequenceDetails    "%CustomerSeq%_cmrr_mbep2d_se"
ConsistencyInfo "N4_VE11C_LATEST_20160120"
PercentPhaseFOV 100
EchoTrainLength 96
PhaseEncodingSteps      96
AcquisitionMatrixPE     96
ReconMatrixPE   96
BandwidthPerPixelPhaseEncode    21.259
EffectiveEchoSpacing    0.000489989
DerivedVendorReportedEchoSpacing        0.000489989
TotalReadoutTime        0.0465489
PixelBandwidth  2605
DwellTime       0.000002
PhaseEncodingDirection  "j-"
SliceTiming
0       3.99
1       0
2       4.1225
3       0.1325
4       4.255
5       0.265
6       4.3875
7       0.3975
8       4.52
9       0.5325
10      4.655
11      0.665
12      4.7875
13      0.7975
14      4.92
15      0.93
16      5.0525
17      1.0625
18      5.185
19      1.1975
20      5.32
21      1.33
22      5.4525
23      1.4625
24      5.585
25      1.595
26      5.7175
27      1.7275
28      5.85
29      1.86
30      5.985
31      1.995
32      6.1175
33      2.1275
34      6.25
35      2.26
36      6.3825
37      2.3925
38      6.515
39      2.525
40      6.65
41      2.66
42      6.7825
43      2.7925
44      6.915
45      2.925
46      7.0475
47      3.0575
48      7.18
49      3.19
50      7.315
51      3.325
52      7.4475
53      3.4575
54      7.58
55      3.59
56      7.7125
57      3.7225
58      7.845
59      3.855
ImageOrientationPatientDICOM
0       0.999268
1       -0.00144229
2       -0.0382226
3       -0.0031393
4       0.992825
5       -0.119535
InPlanePhaseEncodingDirectionDICOM      "COL"
ConversionSoftware      "dcm2niix"
IntendedFor     "ses-01/func/sub-MOCCAG002_ses-01_task-reward_acq-multiband2p4flatAP_run-01_bold.nii.gz"
ConversionSoftwareVersion       "v1.0.20180328 (OpenJPEG build) Clang8.1.0”





On May 27, 2018, at 3:01 PM, Chris Filo Gorgolewski <notifications@github.com<mailto:notifications@github.com>> wrote:


Attachments don't work over email when sent to ggithub. Please include the content of your JSON files in the body of the message.

**Comment by bidhanlamichhane** [comment]
Thank you Chris,
Again, got following error  almost at the end of preprocessing...

Thanks
Bidhan   

****Terminal output ( error portion only).**

[Node] Running "apply_mask" ("niworkflows.nipype.interfaces.fsl.maths.ApplyMask"), a CommandLine Interface with command:
fslmaths /root/src/fmriprep/work/fmriprep_wf/single_subject_002_wf/func_preproc_ses_01_task_reward_acq_multiband3p0tiltPA_run_08_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/fixhdr_unifize/uni_xform.nii.gz -mas /root/src/fmriprep/work/fmriprep_wf/single_subject_002_wf/func_preproc_ses_01_task_reward_acq_multiband3p0tiltPA_run_08_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/combine_masks/ref_image_corrected_brain_mask_maths.nii.gz /root/src/fmriprep/work/fmriprep_wf/single_subject_002_wf/func_preproc_ses_01_task_reward_acq_multiband3p0tiltPA_run_08_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/apply_mask/uni_xform_masked.nii.gz
180529-03:27:57,192 workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_002_wf.func_preproc_ses_01_task_reward_acq_multiband3p0tiltPA_run_08_wf.bold_bold_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.apply_mask".
180529-03:28:16,994 workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_002_wf.func_preproc_ses_01_task_reward_acq_multiband3p0tiltPA_run_08_wf.bold_confounds_wf.dvars".
180529-03:28:19,139 workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_002_wf.anat_preproc_wf.surface_recon_wf.autorecon1" in "/root/src/fmriprep/work/fmriprep_wf/single_subject_002_wf/anat_preproc_wf/surface_recon_wf/autorecon1".
180529-03:28:19,144 workflow INFO:
	 [Node] Running "autorecon1" ("niworkflows.nipype.interfaces.freesurfer.preprocess.ReconAll"), a CommandLine Interface with command:
recon-all -autorecon1 -i /data/sub-002/ses-01/anat/sub-002_ses-01_T1w.nii.gz -T2 /data/sub-002/ses-01/anat/sub-002_ses-01_T2w.nii.gz -noskullstrip -hires -openmp 1 -subjid sub-002 -sd /out/freesurfer -expert /root/src/fmriprep/work/fmriprep_wf/single_subject_002_wf/anat_preproc_wf/surface_recon_wf/autorecon1/expert.opts
180529-03:28:23,323 workflow WARNING:
	 [Node] Error on "fmriprep_wf.single_subject_002_wf.anat_preproc_wf.surface_recon_wf.autorecon1" (/root/src/fmriprep/work/fmriprep_wf/single_subject_002_wf/anat_preproc_wf/surface_recon_wf/autorecon1)
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.0.15', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 314, in main
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 168, in run
    self._clean_queue(jobid, graph, result=result))
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 227, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 68, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 480, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 644, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 520, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 1020, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 957, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
recon-all -autorecon1 -i /data/sub-002/ses-01/anat/sub-002_ses-01_T1w.nii.gz -T2 /data/sub-002/ses-01/anat/sub-002_ses-01_T2w.nii.gz -noskullstrip -hires -openmp 1 -subjid sub-002 -sd /out/freesurfer -expert /root/src/fmriprep/work/fmriprep_wf/single_subject_002_wf/anat_preproc_wf/surface_recon_wf/autorecon1/expert.opts
Standard output:
INFO: hi-res volumes are conformed to the min voxel size
Subject Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a
Current Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a
INFO: SUBJECTS_DIR is /out/freesurfer
Actual FREESURFER_HOME /opt/freesurfer
Linux 1b2416ff7830 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
'/opt/freesurfer/bin/recon-all' -> '/out/freesurfer/sub-002/scripts/recon-all.local-copy'
/out/freesurfer/sub-002

 mri_convert /data/sub-002/ses-01/anat/sub-002_ses-01_T1w.nii.gz /out/freesurfer/sub-002/mri/orig/001.mgz 

mri_convert.bin /data/sub-002/ses-01/anat/sub-002_ses-01_T1w.nii.gz /out/freesurfer/sub-002/mri/orig/001.mgz 
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from /data/sub-002/ses-01/anat/sub-002_ses-01_T1w.nii.gz...
--------------------------------------------------------------------------
GNU libc version: 2.23
ERROR: Systems running GNU glibc version greater than 2.15
  require a newly formatted license file (it's free). Please
  download a new one from the following page:
  http://surfer.nmr.mgh.harvard.edu/registration.html
--------------------------------------------------------------------------
Linux 1b2416ff7830 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

recon-all -s sub-002 exited with ERRORS at Tue May 29 03:28:22 UTC 2018

For more details, see the log file /out/freesurfer/sub-002/scripts/recon-all.log
To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting

Standard error:

Return code: 1

Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
fMRIPrep: Please report errors to https://github.com/poldracklab/fmriprep/issues

**Comment by chrisfilo** [comment]
Your original post indicated that you used the following command line invocation:

```
fmriprep-docker --fs-license-file $FREESURFER_HOM /Users/.../Desktop/BIDS/Test_data/sub-001 /Users/.../Desktop/BIDS/Test_data002/
```

1. Is the `FREESURFER_HOM` variable set?
2. Does it point to a file (not folder!) with a valid FreeSurfer license?

**Comment by oesteban** [comment]
You are running `fmriprep-docker --fs-license-file $FREESURFER_HOM/license.txt`, however `$FREESURFER_HOM` is not set (please note the typo).

Please make sure you do:
```
fmriprep-docker --fs-license-file /Applications/freesurfer/license.txt
```

**Comment by bidhanlamichhane** [comment]
Thank you so much,  
Yes, I did make that change before running again as: 
fmriprep-docker --fs-license-file /Applications/freesurfer/license.txt  ………
but still similar error ( below); 
Thanks
Bidhan Lamichhane


Terminal output: 
Setting up environment for FreeSurfer/FS-FAST (and FSL)
FREESURFER_HOME   /Applications/freesurfer
FSFAST_HOME       /Applications/freesurfer/fsfast
FSF_OUTPUT_FORMAT nii.gz
SUBJECTS_DIR      /Applications/freesurfer/subjects
MNI_DIR           /Applications/freesurfer/mni
FSL_DIR           /usr/local/fsl

Bidhans-MacBook-Pro:~ bidhan$ fmriprep-docker --fs-license-file /Applications/freesurfer/license.txt  /Users/bidhan/Desktop/BIDS/Test_oppJ_manually_data002/sub-002 /Users/bidhan/Desktop/BIDS/Test_oppJ_manually_data00
Warning: <8GB of RAM is available within your Docker environment.
Some parts of fMRIPrep may fail to complete.
Continue anyway? [y/N]y
RUNNING: docker run --rm -it -v /Applications/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /Users/bidhan/Desktop/BIDS/Test_oppJ_manually_data002/sub-002:/data:ro -v /Users/bidhan/Desktop/BIDS/Test_oppJ_manually_data00:/out poldracklab/fmriprep:1.0.15 /data /out participant
docker: Error response from daemon: Mounts denied: 
The path /Applications/freesurfer/license.txt
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
ERRO[0000] error waiting for container: context canceled 
fMRIPrep: Please report errors to https://github.com/poldracklab/fmriprep/issuesBidhans-

**Comment by oesteban** [comment]
The error is similar at the looks of its symptoms, but has nothing to do with the former error.

You first tried to point `fmriprep-docker` to a path (`/license.txt`) because of the mistake using an environment variable misspelled. 

Now, you are pointing `fmriprep-docker` to a path that exists indeed in the host (`/Applications/freesurfer/license.txt`), but docker is complaining:

```
docker: Error response from daemon: Mounts denied:
The path /Applications/freesurfer/license.txt
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```
Luckily this is a pretty explicit message about what is going on. Basically, you'll need to tweak some configurations on you docker installation to allow that path to be used.

Otherwise (and I would advise to take this road, also for security reasons), copy/move the license file to your home directory and point Docker to that license file:

```
cp /Applications/freesurfer/license.txt $HOME/.freesurfer-license.txt
fmriprep-docker --fs-license-file $HOME/.freesurfer-license.txt
```

Next time you will encounter that fmriprep breaks because of memory issues. I'm looking at this warning:

```
Warning: <8GB of RAM is available within your Docker environment.
Some parts of fMRIPrep may fail to complete.
Continue anyway? [y/N]
```
In order to learn how to increase the RAM available to docker, please read the documentation: https://docs.docker.com/docker-for-mac/#advanced
