### ISSUE TITLE
Coregistration failure - Rotation ?

### ISSUE THREAD

**Issue by emdupre** [poldracklab/fmriprep#1150]
As promised in #999, I'm opening a new issue for rotated coregistration with multi-echo. This is a problem I'm still seeing with the latest release (v. 1.0.15) and the same data set as shared previously on OpenNeuro:

<img width="1125" alt="screen shot 2018-05-28 at 16 38 13" src="https://user-images.githubusercontent.com/15017191/40628870-9ad52664-6295-11e8-8b9e-9163692c685d.png">

The only thing I could think that's differing from my local execution and on OpenNeuro is that I'm using a previously computed FreeSurfer directory, though I'm not sure how it could be causing this issue. 

Any (other) ideas where to start looking would be deeply appreciated !

**Comment by oesteban** [comment]
Can you point me to these data on OpenNeuro?

**Comment by emdupre** [comment]
This subject should be available [here](https://openneuro.org/datasets/ds001239) !
