### ISSUE TITLE
singularity not executing despite using bids validated data

### ISSUE THREAD

**Issue by imawla** [poldracklab/fmriprep#1154]
I just faced an issue similar to #1054 
Ran the following singularity command:
`singularity run -B ./:$FS_LICENSE ${image} ./ ./output participant --participant-label=${participant}`

Here's what I get:

`Process Process-2: Traceback (most recent call last): File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap self.run() File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 93, in run self._target(*self._args, **self._kwargs) File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 383, in build_workflow bids_dir, participant_label=opts.participant_label) File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/utils/bids.py", line 89, in collect_participants 'may need to adjust your "File sharing" preferences.', bids_dir) fmriprep.utils.bids.BIDSError: ---------- BIDS root folder: "/home/imawla" ---------- Could not find participants. Please make sure the BIDS data structure is present and correct. Datasets can be validated online using the BIDS Validator (http://incf.github.io/bids-validator/). If you are using Docker for Mac or Docker for Windows, you may need to adjust your "File sharing" preferences.`

Here's what the directory looks like:

```
 |-derivatives
 |-sub-CBTFM0001pre
 |---anat
 |---func
 |-sub-CBTFM0002pre
 |---anat
 |---func
 |-sub-CBTFM0003pre
 |---anat
 |---func
 |-sub-CBTFM0004pre
 |---anat
 |---func
 |-sub-CBTFM0005pre
 |---anat
 |---func
```

I am using version 1.0.15. 
BIDS validator was used to validate the directory, no issues there.
Not sure what is happening, any help appreciated.

**Comment by imawla** [comment]
Ran the following now:
`singularity run -B /home/imawla/ISHTIAQ/singularity_test:/app/FreeSurfer/v6.0.0/license.txt /home/imawla/ISHTIAQ/singularity/fmriprep-1.0.15.simg /home/imawla/ISHTIAQ/singularity_test/ /home/imawla/ISHTIAQ/singularity/output participant --participant-label=sub-CBTFM0001pre`

Getting the following error now:
```
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 383, in build_workflow
    bids_dir, participant_label=opts.participant_label)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/utils/bids.py", line 79, in collect_participants
    [subdir[4:] for subdir in os.listdir(bids_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/imawla/ISHTIAQ/singularity_test'


```

**Comment by oesteban** [comment]
Singularity can't bind files, so this `-B /home/imawla/ISHTIAQ/singularity_test:/app/FreeSurfer/v6.0.0/license.txt` won't work.

My suggestion would be, assuming you have the root of your BIDS dataset under `/home/imawla/ISHTIAQ` with the name `singularity_test`, the following.

1. make sure you have an existing and valid FS license file at `/home/imawla/ISHTIAQ/license.txt`
2. Run:

```
singularity run /home/imawla/ISHTIAQ/singularity/fmriprep-1.0.15.simg \
                singularity_test/ singularity_test/derivatives/1.0.15 participant \
                --participant-label CBTFM0001pre --fs-license-file license.txt -w work/
```

**Comment by imawla** [comment]
@oesteban thanks, i ran your suggestion
```
singularity run /home/imawla/ISHTIAQ/singularity/fmriprep-1.0.15.simg \
                singularity_test/ singularity_test/derivatives/1.0.15 participant \
                --participant-label CBTFM0001pre --fs-license-file license.txt -w work/
```
and now I am getting a different error:

```
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.0.15', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 246, in main
    'ERROR: a valid license file is required for FreeSurfer to run. '
RuntimeError: ERROR: a valid license file is required for FreeSurfer to run. FMRIPREP looked for an existing license file at several paths, in this order: 1) command line argument ``--fs-license-file``; 2) ``$FS_LICENSE`` environment variable; and 3) the ``$FREESURFER_HOME/license.txt`` path. Get it (for free) by registering at https://surfer.nmr.mgh.harvard.edu/registration.html
```

I placed the license.txt file in the CWD as you have suggested.

The license file is fully functioning and obtained from the installation on our own server.

Not sure what is wrong now.

**Comment by chrisfilo** [comment]
Try putting it in $HOME and providing absolute path to it via
``--fs-license-file``

Best,
Chris

**Comment by imawla** [comment]
thanks @chrisfilo, license issue is now gone when I directly put license.txt under `$HOME`, but new issue popped up...

ran:
`singularity run /home/imawla/ISHTIAQ/singularity/fmriprep-1.0.15.simg /home/imawla/ISHTIAQ/singularity_test /home/imawla/ISHTIAQ/singularity_test/derivatives/1.0.15 participant --participant-label CBTFM0001pre --fs-license-file /home/imawla/license.txt -w /home/imawla/ISHTIAQ/singularity_test/work/`

received this:
```
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 383, in build_workflow
    bids_dir, participant_label=opts.participant_label)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/utils/bids.py", line 79, in collect_participants
    [subdir[4:] for subdir in os.listdir(bids_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/imawla/ISHTIAQ/singularity_test'

```

do I need to `export` anything or put anything under `$PATH`??

**Comment by chrisfilo** [comment]
The plot thickens...

- Does `/home/imawla/ISHTIAQ/singularity_test` exist? 
- Can you see it from inside the container by doing `singularity exec /home/imawla/ISHTIAQ/singularity/fmriprep-1.0.15.simg ls /home/imawla/ISHTIAQ/singularity_test`? 
- Did you try to mount it explicitly with `-B`?

**Comment by oesteban** [comment]
Can you report the output of

```
singularity exec /home/imawla/ISHTIAQ/singularity/fmriprep-1.0.15.simg pwd
```

**Comment by imawla** [comment]
huh interesting
`singularity exec /home/imawla/ISHTIAQ/singularity/fmriprep-1.0.15.simg pwd`
is giving me 
`/home/imawla`
which is my `$HOME`
but I am running this code from `/home/imawla/ISHTIAQ/singularity_test` which is my `pwd`

**Comment by imawla** [comment]
A broken symlink was causing all this trouble...thanks for your help, everyone.

**Comment by brainconnectome** [comment]
I am having the same error and issue here. Could you please post your solution to this?

**Comment by oesteban** [comment]
I'm guessing that @imawla just found and fixed the broken symlink.

**Comment by hcp4715** [comment]
Hi there,

I am having the same error here. Might be because of the upgrade of my Ubuntu 20.04. 
I am not very familiar with Linux, how should I check whether it's the problem of symlink? and how to fix it?

**Comment by effigies** [comment]
@hcp4715 Would you mind opening a new issue? And providing your full command?

**Comment by hcp4715** [comment]
Hi, @effigies, 
Thanks for your response. I tried changing my code a few times and it worked finally. I guess it was some very subtle typo. 
sorry for my later reply.

**Comment by effigies** [comment]
Glad you got it working!
