### ISSUE TITLE
Phasediff fieldmap correction KeyError: 'EffectiveEchoSpacing' fmriprep v0.6.1

### ISSUE THREAD

**Issue by abakkour** [poldracklab/fmriprep#1156]
Hello,
I am having an issue applying phasediff fieldmap correction in fmriprep v0.6.1.
I'm running fmriprep-docker.
It clearly sees the fieldmaps and creates the proper workflow:

180601-19:39:33,705 workflow INFO:
	 Creating bold processing workflow for "/data/sub-101/ses-01/func/sub-101_ses-01_task-dots_run-01_bold.nii.gz".
180601-19:39:33,910 workflow INFO:
	 Fieldmap estimation: type "phasediff" found
180601-19:39:34,995 cli WARNING:
	 Captured warning (<class 'UserWarning'>): This has not been fully tested. Please report any failures.

I see the warning about the feature not being fully tested, so this may be part of the issue.
Attached is the crash log for one run of one task. But I get the same crash log for the others. 
It seems to be running into a KeyError: 'EffectiveEchoSpacing'

[crash-20180601-191131-root-gen_vsm-c20f2a4b-a6ce-4ffb-8ee4-954611935d13.txt](https://github.com/poldracklab/fmriprep/files/2063946/crash-20180601-191131-root-gen_vsm-c20f2a4b-a6ce-4ffb-8ee4-954611935d13.txt)

In the BIDS directory, I follow the guidelines from bids_spec1.0.0.pdf for "8.9.1 Case 1: Phase difference image and at least one magnitude image". I have a phasediff and 2 magnitude  images.
The phasediff json sidecar looks like this:
{
    "EchoTime1":0.00492,
    "EchoTime2":0.00738,
    "IntendedFor": ["func/sub-101_ses-01_task-dots_run-01_bold.nii.gz",
		    "func/sub-101_ses-01_task-dots_run-02_bold.nii.gz",
		    "func/sub-101_ses-01_task-food_run-01_bold.nii.gz",
		    "func/sub-101_ses-01_task-food_run-02_bold.nii.gz"]
}

Thanks!
Akram

**Comment by effigies** [comment]
Hi, can you verify this problem still occurs in fmriprep 1.0.15?

**Comment by abakkour** [comment]
Sorry for the delay. I thought that fmriprep had updated before I posted this. It downloaded, but then it apparently didn't update properly. I also didn't check elsewhere to find out what the latest version was.
In any case, I have managed to properly install fmriprep v1.1.0 and no longer run into the phasediff problem.
Thanks!

**Comment by effigies** [comment]
Great to hear, and thanks for checking back!

We generally recommend using the latest version of fMRIPrep, except if you need to reproduce a specific preprocessing run (e.g. from a published result, or to be consistent with already preprocessed subjects).
