### ISSUE TITLE
fmriprep 1.0.15 module not found error?

### ISSUE THREAD

**Issue by MetaD** [poldracklab/fmriprep#1157]
Hello,
I've been using fmriprep 1.0.8 and just tried to upgrade to 1.0.15, and I got the following error after upgrading:
```
$ fmriprep --version
Traceback (most recent call last):
  File "/Users/mengdu/venv3/bin/fmriprep", line 11, in <module>
    sys.exit(main())
  File "/Users/mengdu/venv3/lib/python3.6/site-packages/fmriprep/cli/run.py", line 231, in main
    from niworkflows.nipype import logging as nlogging
ModuleNotFoundError: No module named 'niworkflows.nipype'
```

I installed everything through pip, and I have niworkflows==0.4.0 and nipype==1.0.4. Could you help with this? Thank you very much!

**Comment by effigies** [comment]
You'll need to downgrade niworkflows to 0.3.13 for the moment (or install fmriprep from GitHub). Apologies. We'll need to put out a new fmriprep version to go with niworkflows 0.4.0.

**Comment by MetaD** [comment]
No problem that sounds good!

**Comment by effigies** [comment]
Hi @MetaD, we're in the process of releasing fmriprep now. In about 2 hours, it should be installable through PyPI.
