### ISSUE TITLE
Tests on the fieldmap estimation and unwarping

### ISSUE THREAD

**Issue by poldrack** [poldracklab/fmriprep#116]
- [ ] [CI unit test] Check that fieldmaps computed with FUGUE and TOPUP are equivalent (using HCP data, which includes both types of images).
- [ ] [On the reports, per subject] Check original polarity and opposite/reverse polarity and see which one results in better final coregistration score (e.g. normalized correlation, mutual information)
  - [ ] For blip up/down images estimation
  - [ ] For GRE pairs (phase-difference images) estimation

(EDITED by @oesteban on 08/29/2016)

**Comment by poldrack** [comment]
do same for blip up/down as well as GRE field maps

**Comment by oesteban** [comment]
Ok, we are in a good position to address this: the BEAST dataset has fieldmaps and "[PEpolar](https://cni.stanford.edu/wiki/Data_Processing#Gradient-reversal_Unwarping_.28.27pepolar.27.29)" (topup). The fieldmaps are in Hz (meaning: they don't have phase wrapping, and that's really awesome to get this issue done).

I'm addressing this in the ```fieldmaps``` branch.

**Comment by oesteban** [comment]
As in #341 our first take on this will be visually assessing the results. We'll reopen if we find the resources to unit-test all the steps in the workflow.
