### ISSUE TITLE
Segmentationu error

### ISSUE THREAD

**Issue by tragus1** [poldracklab/fmriprep#1166]
Standard error:

    Using antsBrainExtraction with the following arguments:
      image dimension         = 3
      anatomical image        = /data/sub-TAURESTMCIm024S4674/anat/sub-TAURESTMCIm024S4674_T1w.nii.gz
      extraction template     = /niworkflows_data/ants_oasis_template_ras/T_template0.nii.gz
      extraction reg. mask    = /niworkflows_data/ants_oasis_template_ras/T_template0_BrainCerebellumRegistrationMask.nii.gz
      extraction prior        = /root/src/fmriprep/work/fmriprep_wf/single_subject_TAURESTMCIm024S4674_wf/anat_preproc_wf/skullstrip_ants_wf/t1_skull_strip/T_template0_BrainCerebellumProbabilityMask.nii.gz
      output prefix           = highres001_
      output image suffix     = nii.gz

    N4 parameters (pre brain extraction):
      convergence             = [50x50x50x50,0.0000001]
      shrink factor           = 4
      B-spline parameters     = [200]

    Atropos parameters (extraction):
       convergence            = [3,0.0]
       likelihood             = Gaussian
       initialization         = kmeans[3]
       mrf                    = [0.1,1x1x1]
       use clock random seed  = 1

/usr/lib/ants/antsBrainExtraction.sh: line 117:   849 Segmentation fault      (core dumped) $cmd
Return code: 1

I. always get this error from different subjects in my study. How can I avoid that?

thank you,
Tragus

**Comment by chrisfilo** [comment]
Looks like a memory error similar to what you reported last time https://github.com/poldracklab/fmriprep/issues/961. Maybe docker limits got reset?

**Comment by oesteban** [comment]
Hi @tragus1, any progress troubleshooting this?

**Comment by oesteban** [comment]
Please reopen if this problem comes back.
