### ISSUE TITLE
Error occurs when using two phase images and two magnitude images as fieldmap inputs

### ISSUE THREAD

**Issue by wangboc** [poldracklab/fmriprep#1169]
Hi, according to BIDS naming convention, I use two magnitude and phase images as the fieldmap inputs. While, fmriprep failed to run at the beginning. The error infos  :

![image](https://user-images.githubusercontent.com/12145052/41398930-8ba57866-6feb-11e8-9290-71c60dcc8b88.png)

And my inputs structure is:
![image](https://user-images.githubusercontent.com/12145052/41398972-a8cd46da-6feb-11e8-9521-41dbe409cac4.png)

**Comment by effigies** [comment]
Hi, what version of fMRIPrep are you running?

**Comment by wangboc** [comment]
should be the newest version: 1.1.1
![image](https://user-images.githubusercontent.com/12145052/41401271-fde686da-6ff1-11e8-84ce-71885826a174.png)

**Comment by chrisfilo** [comment]
@oesteban does FMRIPREP support  phase1/phase2 type of SDC input data? I could not find traces of it in the codebase.

**Comment by wangboc** [comment]
How can I calculate the phase difference image by using the two phase image? I find the fslcomplex is so complex to run...  :)

**Comment by mattcieslak** [comment]
So does this mean that BIDS section 8.9.2 isn't currently supported?

**Comment by effigies** [comment]
@mattcieslak I believe that's correct. We would be happy to review a patch, however.

**Comment by mattcieslak** [comment]
Happy to write a workflow for this. Would make sense to calculate a phasediff image from the two phases and send that as input to the workflow for 8.9.3-style fieldmaps? Or is there something fundamentally different between derived phasediffs and those that come from scanners?

**Comment by effigies** [comment]
I'm not really sure, myself. I have dug into the fieldmap math much less than @oesteban, who might have thoughts here.

**Comment by mattcieslak** [comment]
It looks like there is support for phase1/phase2 in the dipy workflow (https://github.com/nipy/nipype/blob/master/nipype/workflows/dmri/fsl/utils.py#L645).  Would it make sense to check if the `type` is `"phase"` and if so send the two phase images to `pha2rads`? 

Maybe it would be good to change the `type` from `"phase"` to `"phases"` or something more descriptive?

**Comment by oesteban** [comment]
It's been a long way @wangboc, but this has been finally addressed and released with version 1.5.1 (although you should go with the newest 1.5.2).

Could you check whether this is working out for you now? Please reopen if you find any issues.
