### ISSUE TITLE
fmap .json setup question

### ISSUE THREAD

**Issue by imawla** [poldracklab/fmriprep#1172]
Hi, I am setting up the .json for fmap based on specifications listed here:
https://bids.neuroimaging.io/bids_spec1.0.0-rc2.pdf

I have a phase difference image and one magnitude image, and prior to using FMRIPREP, I have used `epidewarp.fsl` function from FSL as follows:

`epidewarp.fsl --mag $dir/$subj/bold/fieldmap/fieldmap1.nii --dph $dir/$subj/bold/fieldmap/fieldmap2.nii --epi bold.nii.gz --tediff 2.46 --esp .69 --sigma 2 --vsm shiftmap.nii.gz --epidw bold_dw.nii.gz`

The flags in the command stand for the following:

```
Inputs
--mag volid     : B0 magnitude volume
--dph volid     : B0 phase difference volume
--tediff tediff : difference in B0 field map TEs
--esp esp       : EPI echo spacing
--sigma sigmamm : 2D spatial gaussing smoothing stddev (def 2mm)
Outputs
--vsm volid   : voxel shift map (required)
--epidw volid : dewarped epi volume
```

My understanding from the example .json in the BIDS Spec document is that I can specify `EchoTime1` and `EchoTime2` as follows:

```
{
"EchoTime1": 0.00600,
"EchoTime2": 0.00746,
"IntendedFor": "func/sub001­task­motor_bold.nii.gz"
}
```

Is the EPI echo spacing (`--esp` from` epidewarp.fsl`) calculated from the difference of these two `EchoTime ` values? How can I specify `--tediff` and `--sigma` in the .json?

I also have some fieldmaps collected in R->L orientation instead of P->A, which results in a different `--esp` value. How do I specify the orientation in the .json?

Thanks so much!
Ishtiaq

**Comment by oesteban** [comment]
> Is the EPI echo spacing (`--esp` from `epidewarp.fsl`) calculated from the difference of these two `EchoTime` values? 

No, the json example above looks like sec. 8.3.5.1 of BIDS, which describes how the field maps can be specified. From those `EchoTime[1,2]` keys, the `--tediff` parameter can be calculated.

Then the question how do you encode the `--esp` parameter. The `--esp` is the EPI echo spacing *of your BOLD data*. Moreover, `--esp` is, in fact, an *effective* EPI echo spacing (meaning that parallel imaging should also be taken into account). Therefore, please make sure that parallel imaging metadata is also written in the sidecar json. You have several ways to encode this in BIDS, but basically you'll use either `EffectiveEchoSpacing` or `TotalReadoutTime`+`ParallelReductionFactorInPlane`. But please recall that these are metadata corresponding to the BOLD images.

> How can I specify `--tediff` and `--sigma` in the .json?

The only parameter left is `--sigma`. FMRIPREP does not need it as it implements a slightly different strategy to reduce the noise in the phase difference map. For `epidewarp.fsl` the parameter is pretty much self-explanatory (and I cannot give any good recommendation, probably you'll find suitable values in the FSL mailing list).

**Comment by imawla** [comment]
Thanks @oesteban, that was helpful.

I am trying to enter `PhaseEncodingDirection` in the `.json` corresponding to `bold.nii.gz`, however, I am not familar with the possible `PhaseEncodingDirection` values of `“i”, “j”, “k”, “i-”, “j-”, “k-”`

The infodump file from the scanner says `PhaseEncDir COL` and the `mri_info` command on `bold.nii.gz` says: 
```
Volume information for bold.nii.gz
          type: nii
    dimensions: 98 x 98 x 75 x 288
   voxel sizes: 2.0000, 2.0000, 2.0000
          type: SHORT (4)
           fov: 196.000
           dof: 0
        xstart: -98.0, xend: 98.0
        ystart: -98.0, yend: 98.0
        zstart: -75.0, zend: 75.0
            TR: 1250.00 msec, TE: 0.00 msec, TI: 0.00 msec, flip angle: 0.00 degrees
       nframes: 288
       PhEncDir: UNKNOWN
ras xform present
    xform info: x_r =  -0.9990, y_r =  -0.0000, z_r =   0.0442, c_r =     1.9476
              : x_a =  -0.0031, y_a =  -0.9976, z_a =  -0.0691, c_a =   -21.2549
              : x_s =   0.0441, y_s =  -0.0692, z_s =   0.9966, c_s =     7.4993
Orientation   : LPS
Primary Slice Direction: axial

voxel to ras transform:
               -1.9980  -0.0000   0.0885    96.5335
               -0.0061  -1.9952  -0.1383    81.9954
                0.0883  -0.1384   1.9933   -64.7910
                0.0000   0.0000   0.0000     1.0000

voxel-to-ras determinant 8

ras to voxel transform:
               -0.4995  -0.0015   0.0221    49.7748
               -0.0000  -0.4988  -0.0346    38.6575
                0.0221  -0.0346   0.4983    32.9852
                0.0000   0.0000   0.0000     1.0000
```
How can I translate this information to BIDS specification?

**Comment by imawla** [comment]
*bump*

I figured out that the data was collected `A>P`, which is on the `y` dimension, and this potentially translates to `j`, am I getting this right?

**Comment by emdupre** [comment]
Hi @imawla ! 

This question seems like a better fit for [neurostars](https://neurostars.org), since it's relevant to BIDS generally, rather than specifically to FMRIPREP. There's a great community there, if you haven't used that forum already !

**Comment by oesteban** [comment]
Hi @imawla, did you finally post this question to neurostars?

> I figured out that the data was collected A>P, which is on the y dimension, and this potentially translates to j, am I getting this right?

Since your images are oriented in LPS (left-to-right, posterior-to-anterior, superior-to-inferior), yes, you can see that the AP axis is the second of the image grid. That corresponds to `j` in BIDS. You could 

However, I cannot tell you with certainty the polarity of your images.

[This link](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/topup/Faq) may help you discern the polarity and double check that the axis is indeed `j`.
