### ISSUE TITLE
pybids performance

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#1174]
Context https://neurostars.org/t/possible-to-skip-bids-validation/1851

Ideas:

- turn off pybids validation (`validation=False`)
- update pybids and grabbits (there were recent performance related improvements)

**Comment by effigies** [comment]
I don't think we do validation, but both of these sound reasonable. There were some API changes, but we might not use those aspects, so it might be as simple as pinning a new version.
