### ISSUE TITLE
Is looking for T1s in places where it shouldn't

### ISSUE THREAD

**Issue by mih** [poldracklab/fmriprep#1177]
The 'life' movie dataset (http://datasets.datalad.org/?dir=/labs/haxby/life) carries non-defaced T1w images in a `sourcedata/` subdirectory. However, their content is not available (due to privacy issues), so those files appear to be dead symlinks. When running fmriprep it picks these files up and then crashed when opening them. I think:

- it should not be looking in `sourcedata/` at all
- it could treat dead symlinks as non-existent files

(of course that dataset has defaced T1w images in the respective BIDS-compliant locations too)

**Comment by chrisfilo** [comment]
Thanks for reporting. We should exclude `sourcedata` folder here: https://github.com/poldracklab/fmriprep/blob/5dd78197a828de566d754b327f0f7d663bfe42f0/fmriprep/utils/bids.py#L154

**Comment by chrisfilo** [comment]
Could you try out this PR? https://github.com/poldracklab/fmriprep/pull/1178

**Comment by mih** [comment]
@chrisfilo Not anyhow quickly. I am still exploring this space and I am using a Docker->Singularity container for now that I did not compose myself. Sorry, and thx for the quick fix.

**Comment by effigies** [comment]
You should be able to override fmriprep installation in Singularity by using, from the repo root:

```Shell
PYTHONPATH="." singularity run ...
```

Failing that, you can bind in:

```Shell
singularity -B $PWD/fmriprep:/usr/local/miniconda/lib/python3.6/site-packages/fmriprep run ...
```

Or similar.

**Comment by chrisfilo** [comment]
Waiting for @mih to report if the issue is indeed resolved.
