### ISSUE TITLE
How can i get  both T1w and template output space ?

### ISSUE THREAD

**Issue by wangboc** [poldracklab/fmriprep#1185]
Hi dear friend, I input the parameter --output-space {T1w, template}, while I got the only MNI152-preproc.nii.gz . How can I get both T1w and template output space?

![image](https://user-images.githubusercontent.com/12145052/42228140-c5bb12f2-7f15-11e8-922e-00c7c53f647c.png)

**Comment by effigies** [comment]
`--output-space T1w template`

**Comment by wangboc** [comment]
Do not need the brackets {} ? I`ll try it. Thank u very much for so rapid a reply!

**Comment by effigies** [comment]
No, the brackets are in the help output to show the options you may select from.
