### ISSUE TITLE
Write out meta-data JSON sidecars

### ISSUE THREAD

**Issue by adelavega** [poldracklab/fmriprep#1190]
Currently, fmriprep does not output `.json` metadata sidecar files. This makes it cumbersome to get such information (e.g. TR).

For example, @effigies is working on a PR to grabbit/pybids to allow a user to get the metadata of the original bold file that matches a preproc file. This is still not ideal though, because it requires the original dataset. For some applications (e.g. `fitlins`) that would require having the original dataset around just to get the TR of preproc file.

If fmriprep were to writeout `.json` sidecar metadata files for its outputs, it would make these datasets much more independent and portable.

**Comment by chrisfilo** [comment]
If the only thing you are after is TR you can get it from nifti headers right now. We made sure those are correct.

**Comment by effigies** [comment]
This might be a good idea also in terms of filtering out the things that can no longer apply after reorientation/resampling, such as `PhaseEncodingDirection`, `SliceTiming`, etc.

**Comment by adelavega** [comment]
Thx @chrisfilo. @effigies we could for now always look in the preproc headers, but I think the issue is that `pybids.Analysis` uses `get_metadata` and I suppose looking in the original bold file headers would not be reliable?
