### ISSUE TITLE
Error on --output-space 

### ISSUE THREAD

**Issue by wangboc** [poldracklab/fmriprep#1191]
Hi, friend:

When I type the following command, error occurs:  

_fmriprep-docker **--output-space T1w template** --use-syn-sdc --fs-license-file /root/projects/freesurfer/license.txt /root/projects/Sample/ADNI3/5.AD/ADNI3_130_S_6072/sub-ADNI3130S6072/fmriprep/input/ /root/projects/Sample/ADNI3/5.AD/ADNI3_130_S_6072/sub-ADNI3130S6072/fmriprep/output/ participant_

Here comes the log:
RUNNING: docker run --rm -it -v /root/projects/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /root/projects/Sample/ADNI3/5.AD/ADNI3_130_S_6072/sub-ADNI3130S6072/ADNI/130_S_6072/Axial_fcMRI__EYES_OPEN_/2017-08-25_14_34_51.0/S601336/T1w:/data:ro -v /root/projects/Sample/ADNI3/5.AD/ADNI3_130_S_6072/sub-ADNI3130S6072/ADNI/130_S_6072/Axial_fcMRI__EYES_OPEN_/2017-08-25_14_34_51.0/S601336/template:/out poldracklab/fmriprep:1.1.1 /data /out participant --output-space --use-syn-sdc /root/projects/Sample/ADNI3/5.AD/ADNI3_130_S_6072/sub-ADNI3130S6072/fmriprep/input/ /root/projects/Sample/ADNI3/5.AD/ADNI3_130_S_6072/sub-ADNI3130S6072/fmriprep/output/ participant

usage: fmriprep [-h] [--version]
                [--participant_label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]]
                [-t TASK_ID] [--debug] [--nthreads NTHREADS]
                [--omp-nthreads OMP_NTHREADS] [--mem_mb MEM_MB] [--low-mem]
                [--use-plugin USE_PLUGIN] [--anat-only]
                [--ignore-aroma-denoising-errors] [-v]
                [--ignore {fieldmaps,slicetiming} [{fieldmaps,slicetiming} ...]]
                [--longitudinal] [--t2s-coreg] [--bold2t1w-dof {6,9,12}]
                [--output-space {T1w,template,fsnative,fsaverage,fsaverage6,fsaverage5} [{T1w,template,fsnative,fsaverage,fsaverage6,fsaverage5} ...]]
                [--force-bbr] [--force-no-bbr]
                [--template {MNI152NLin2009cAsym}]
                [--output-grid-reference OUTPUT_GRID_REFERENCE]
                [--template-resampling-grid TEMPLATE_RESAMPLING_GRID]
                [--medial-surface-nan] [--use-aroma]
                [--aroma-melodic-dimensionality AROMA_MELODIC_DIMENSIONALITY]
                [--skull-strip-template {OASIS,NKI}] [--fmap-bspline]
                [--fmap-no-demean] [--use-syn-sdc] [--force-syn]
                [--fs-license-file PATH] [--no-submm-recon]
                [--cifti-output | --fs-no-reconall] [-w WORK_DIR]
                [--resource-monitor] [--reports-only] [--run-uuid RUN_UUID]
                [--write-graph] [--stop-on-first-crash] [--notrack]
                bids_dir output_dir {participant}
fmriprep: error: argument --output-space: expected at least one argument

**Comment by chrisfilo** [comment]
Ooops - this looks like a bug in the fmriprep-docker wrapper. While we work on fixing it please try using docker directly

```
docker run --rm -it -v /root/projects/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /root/projects/Sample/ADNI3/5.AD/ADNI3_130_S_6072/sub-ADNI3130S6072/ADNI/130_S_6072/Axial_fcMRI__EYES_OPEN_/2017-08-25_14_34_51.0/S601336/T1w:/data:ro -v /root/projects/Sample/ADNI3/5.AD/ADNI3_130_S_6072/sub-ADNI3130S6072/ADNI/130_S_6072/Axial_fcMRI__EYES_OPEN_/2017-08-25_14_34_51.0/S601336/template:/out poldracklab/fmriprep:1.1.1 /data /out participant --output-space T1w template --use-syn-sdc /root/projects/Sample/ADNI3/5.AD/ADNI3_130_S_6072/sub-ADNI3130S6072/fmriprep/input/ /root/projects/Sample/ADNI3/5.AD/ADNI3_130_S_6072/sub-ADNI3130S6072/fmriprep/output/ participant
```

**Comment by effigies** [comment]
I think it's an ordering thing. If you move `--output-space T1w template` to the end, I see the arguments show up.

Not that it isn't a bug, but I think there's a very easy workaround.
