### ISSUE TITLE
Use PNG-based images in documentation

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#1201]
A number of example figures in the documentation do not display correctly for Firefox, as they were generated during the webp era.

**Comment by erramuzpe** [comment]
@effigies I went one by one checking the all the figures in the `/docs/_static` folder (also checked visually the docs in both Chrome and Firefox(v.70) and everything seems to be ok.

**Comment by effigies** [comment]
Thanks for checking. We probably just failed to close this after fixing it.
