### ISSUE TITLE
nipype error: No resources available

### ISSUE THREAD

**Issue by spitschan** [poldracklab/fmriprep#1203]
I'm running fmriprep 1.1.2 in docker with the following command:

```
fmriprep-docker --fs-license-file /Users/spitschan/Data/mrTest/fslicense.txt \
/Users/spitschan/Data/mrTest/bids /Users/spitschan/Data/mrTest/out/ \
--use-syn-sdc --bold2t1w-dof 9 -vvv --low-mem --debug
```

It seems to run fine but after a few minutes, I get the following repeated error messages (repeated every 2 seconds):

```
180712-08:08:00,554 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_L003_wf.func_preproc_ses_afternoon_task_varcon_run_03_wf.bold_reference_wf.validate" in "/root/src/fmriprep/work/fmriprep_wf/single_subject_L003_wf/func_preproc_ses_afternoon_task_varcon_run_03_wf/bold_reference_wf/validate".180712-08:08:00,554 nipype.workflow INFO:
	 [Node] Running "validate" ("fmriprep.interfaces.images.ValidateImage")

180712-08:08:00,559 nipype.workflow INFO:
	 [Node] Running "validate" ("fmriprep.interfaces.images.ValidateImage")
180712-08:08:02,158 nipype.workflow DEBUG:
	 No resources available
180712-08:08:02,452 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_L003_wf.func_preproc_ses_afternoon_task_varcon_run_02_wf.bold_reference_wf.validate" in "/root/src/fmriprep/work/fmriprep_wf/single_subject_L003_wf/func_preproc_ses_afternoon_task_varcon_run_02_wf/bold_reference_wf/validate".
180712-08:08:02,464 nipype.workflow INFO:
	 [Node] Running "validate" ("fmriprep.interfaces.images.ValidateImage")
180712-08:08:04,59 nipype.workflow DEBUG:
	 No resources available
180712-08:08:06,222 nipype.workflow DEBUG:
	 No resources available
180712-08:08:08,99 nipype.workflow DEBUG:
	 No resources available
180712-08:08:10,94 nipype.workflow DEBUG:
	 No resources available
180712-08:08:12,80 nipype.workflow DEBUG:
	 No resources available
180712-08:08:14,89 nipype.workflow DEBUG:
	 No resources available
180712-08:08:16,48 nipype.workflow DEBUG:
	 No resources available
180712-08:08:18,225 nipype.workflow DEBUG:
	 No resources available
180712-08:08:20,304 nipype.workflow DEBUG:
	 No resources available
180712-08:08:22,293 nipype.workflow DEBUG:
	 No resources available
180712-08:08:26,52 nipype.workflow DEBUG:
	 No resources available
```

System specs: iMac running Sierra 10.12.6, 3.4 GHz Intel Core i5, 8 GB RAM. In my docker config, I've allowed maximum use of RAM and CPU. Is this simply a problem of not enough RAM available?

Is there any other debug information that could be extracted to learn about the problem?

Much obliged.

**Comment by spitschan** [comment]
Any suggestions?

**Comment by effigies** [comment]
Hi, sorry about the slow response. `No resources available` is an indicator that new jobs can't be scheduled, because other jobs are using the resources. This is normal, and actually good, as it means that the scheduler isn't over-committing resources.

The reason you're seeing this because you have the verbosity set high enough to hit the DEBUG level of logging.

**Comment by spitschan** [comment]
Thanks. It appears though that the program gets stuck at some point:

```
180727-22:53:04,212 nipype.workflow DEBUG:
         No resources available
180727-22:53:04,361 nipype.workflow DEBUG:
         No resources available
```

This message was <12h ago, with no further information. Is there any way to know if it is stuck?

**Comment by spitschan** [comment]
Thanks, this is helpful, though I am not getting any messages every 2 seconds (the last of the "No resources available" messages is from <12h ago). `top` does not reveal any program using lots of CPU/mem.

**Comment by effigies** [comment]
If you're not getting any messages, then the pipeline is probably not still running, though why they would have stopped is unclear. (Unless you're `tail`ing logs and the log ran out of space.)

I would probably stop and retry. I would also *highly* recommend using `-w` flag to mount a working directory, so you don't have to start from the beginning every time.

**Comment by spitschan** [comment]
Thanks, I suspect this issue arose from using a terminal multiplexer (`screen`) and the log was just full.
