### ISSUE TITLE
 No BOLD images found for participant [...] and task <all>. All workflows require BOLD images.

### ISSUE THREAD

**Issue by relyativist** [poldracklab/fmriprep#1206]
Hello have this problem with fmriprep, the problem is that my data sat don't consist of BOLD images, how to skip this error?

**Comment by mgxd** [comment]
@yarkinvyacheslav there could be a few things here:

- does you dataset pass the [bids validator]?
- are you processing just anatomical images? If so, you'll need to use the `--anat-only` flag

What does your command look like?

**Comment by yarkinvyacheslav** [comment]
@mgxd, "does you dataset pass the [bids validator]?" -  No, it doesn't. "are you processing just anatomical images? If so, you'll need to use the --anat-only flag" - will try this, thanks
@mgxd is there any universal solution for heuristic.py? I have an issue to compose heuristsic.py and BIDS validate every incoming dataset.

**Comment by mgxd** [comment]
The `--anat-only` flag is for if you are just processing structural images, this sounds like your conversion isn't correct. 

Regarding `heurisitic.py` - are you referring to [heudiconv](https://github.com/nipy/heudiconv)? Here is a nice [tutorial](http://reproducibility.stanford.edu/bids-tutorial-series-part-2a/), or a [video](https://www.youtube.com/watch?v=O1kZAuR7E00) if you'd prefer that.

**Comment by effigies** [comment]
`--anat-only` is the correct approach in these cases. Thanks for chiming in, @mgxd!

@relyativist please re-open if you're having further issues.
