### ISSUE TITLE
--debug flag can be confusing

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#1213]
The fact that the `--debug` flag yields poor normalization results (due to using testing configs) can be confusing - see https://neurostars.org/t/fmriprep-1-1-1-anat-only-t1-to-mni-poor-quality-nonlinear-registration/2143/2

I recommend renaming it to `--testing`.

**Comment by jclauneuro** [comment]
It may be reasonable to just leave the flag as is but just make it more obvious to the user that they are running in `DEBUG` mode. This could be beneficial in two different locations:
1. the standard output log
2. the html reports

Also would be helpful to include a warning that the normalization results will be suboptimal when in this mode.

@chrisfilo suggested that I do a pull request. I'll look into this but I'm not yet familiar enough with the code to do this well. For log location (2), I believe that including a conditional statement on the `DEBUG` mode status in `interfaces/reports.py` could be a good solution.

**Comment by chrisfilo** [comment]
Here are some useful instructions for new contributors: https://github.com/poldracklab/fmriprep/blob/master/CONTRIBUTING.md

I still think that just renaming the argument is an easier solution, but if you want to add more info to the reports you will have to modify the reports template: https://github.com/poldracklab/fmriprep/blob/master/fmriprep/viz/report.tpl and pass new variables to it.

**Comment by oesteban** [comment]
Renamed to `--sloppy`
