### ISSUE TITLE
fmriprep fails to find echo time info 

### ISSUE THREAD

**Issue by nblauch** [poldracklab/fmriprep#1219]
I am rerunning FMRIPREP on a dataset to get functional runs in a different space. My FMRIPREP version is the same as when I ran it before successfully (1.0.12). In the first 8/12 subjects, rerunning now fails due to an inability to find the echo time info from the field mapping scans. Oddly, this does not occur for subs 9-12. In the crash log (attached), the echo time info is clearly displayed in printout despite the error at the bottom.

Any ideas? 

[crash-20180723-205845-root-compfmap-4971e2f8-ab7d-4bad-bca6-51b22d1aad87.txt](https://github.com/poldracklab/fmriprep/files/2224572/crash-20180723-205845-root-compfmap-4971e2f8-ab7d-4bad-bca6-51b22d1aad87.txt)

**Comment by chrisfilo** [comment]
Please run the validator on the input data. As per [spec section 8.3.5.1](http://bids.neuroimaging.io/bids_spec.pdf#page=26) phasediff data requires two field EchoTime1 and EchoTime2. We should make the error message more clear.

**Comment by nblauch** [comment]
That fixes it. I now remember going in before to fix these. When I recreated my bids dir (per #1220 ) these edits were lost in translation. 

Clearer error message would be great. Thanks Chris.
