### ISSUE TITLE
Running fmriprep docker image from XNAT with --fs-no-reconall option

### ISSUE THREAD

**Issue by stefanpsz** [poldracklab/fmriprep#1222]
Hi all!!

I am tryinng to run the fmriprep docker image from XNAT 1.7 but I cannot get it to work.

As stated in the [XNAT BIDS apps internal list](https://wiki.xnat.org/display/CS/BIDS+Apps), that there is no straightforward way of mounting the FreeSurfer licence file into the image within XNAT, hence the --fs-no-reconall option should be used. The problem is that even when provided with such option, the image tries to look for the licence file anyway, hence failing to run.

Would it be possible to have a docker image such that when provided with the --fs-no-reconall option it does not look for the licence file?

Thank you very much!

Stefan

**Comment by chrisfilo** [comment]
We still use freesurfer tools for example for creating robust T1w templates. They will require a license even if recon all is not run.

**Comment by effigies** [comment]
Unfortunately, we do at times FreeSurfer tools apart from `recon-all`, and so can't skip the license in general. However, if you only have one T1w image per subject, I think you won't necessarily need it.

It's possible you could use `--fs-license-file /dev/null`, and hope that no FreeSurfer commands are used, but I haven't tried this myself.

**Comment by chrisfilo** [comment]
I think your idea from the wiki of creating a wrapper image for running FMRIPREP with a site freesurfer licence is the most promising.

**Comment by stefanpsz** [comment]
Will try. Thanks!

**Comment by oesteban** [comment]
Please reopen if there is any further development. Thanks!

**Comment by effigies** [comment]
Please open a new issue with what you need. Reading through this and your comment, I can't tell what you want.
