### ISSUE TITLE
[DOC] Add  ME descriptions

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1227]
After merging #1024, we should add a couple of sentences to the `__desc__` of ME workflows. WDYT @emdupre ?

**Comment by tsalo** [comment]
I know that the ME workflows are likely to change given the other `me-epi` issues and the development of `tedana`, but I'd be happy to take a crack at this. I'm fairly naive regarding fmriprep's organization, but it looks like the only workflow that needs to be updated is [init_bold_t2s_wf](https://github.com/poldracklab/fmriprep/blob/18019ea0de7f6523ff81f7475202997225002ecc/fmriprep/workflows/bold/t2s.py#L26).

**Comment by emdupre** [comment]
Thanks @tsalo ! That would be great, I think.
