### ISSUE TITLE
Is carpetplot's xlabel wrong?

### ISSUE THREAD

**Issue by dangom** [poldracklab/fmriprep#1228]
Minor bug, but I believe carpet plots xlabel meant to say Volumes or Time (TR) instead of Time (s). If not then the time scale is not being properly multiplied by TR.

I could PR but I don't know which fix makes more sense. In my opinion Time (TR) is more intuitive.

```bash
$ fmriprep --version
fmriprep v1.1.2
```

**Comment by shirareznik** [comment]
Duplicate of:

https://github.com/poldracklab/niworkflows/issues/260#issuecomment-442277835

Which is closed...

**Comment by oesteban** [comment]
Yes, but @dangom is right that we need to make that change effective in fmriprep (I think). I'll identify where we are at now, and report back.

**Comment by oesteban** [comment]
We are now with niworkflows>0.7.2, so this can be safely closed.
