### ISSUE TITLE
[ENH] Zenodo citation on boilerplate

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1229]
Comes from https://github.com/poldracklab/fmriprep/pull/1024#discussion_r205953098

Depending on whether we consider that using the DOI to latest of zenodo (the solution given in #1024), this issue would be fixed with replacing the appropriate fMRIPrep version on the bibtex file. If we still want to use the DOIs pointing to particular versions, then this issue would include solving also that problem.

**Comment by chrisfilo** [comment]
Thanks for opening this!
