### ISSUE TITLE
fmriprep hanging

### ISSUE THREAD

**Issue by danielkimmel** [poldracklab/fmriprep#1231]
Hello

I'm running into a very similar problem as in https://github.com/poldracklab/fmriprep/issues/671 ... twice. 

The first time was on a low-powered machine that was running out of HDD space for the scratch. I'm now running on a server with 2TB of scratch and 32GB of mem. In general, fmriprep has been running well for single subjects on the high-spec'd box. However, when processing the full dataset (~25 subjects), it got through many of the steps, but is now hanging for about 3 days on one node:
![image](https://user-images.githubusercontent.com/32337686/43526917-4d7213a8-9573-11e8-8a09-d0e603605758.png)

Note that it appears that it actually completed the above node, but no new node has been started (this is the last line in the terminal). So the problem may not be with this node, but with the next step (which may be exporting and wrapping up for all I know!).

Nonetheless, I've looked at the log for this subject, since it was the last node. The log suggests that in a previous attempt to process this subject (within the same call to fmriprep), the process crashed because of space:

```
Node: fmriprep_wf.single_subject_18042401_wf.func_preproc_ses_01_task_resting_run_02_wf.bold_bold_trans_wf.bold_reference_wf.validate
Working directory: /scratch/fmriprep_wf/single_subject_18042401_wf/func_preproc_ses_01_task_resting_run_02_wf/bold_bold_trans_wf/bold_reference_wf/validate

Node inputs:

ignore_exception = False
in_file = /scratch/fmriprep_wf/single_subject_18042401_wf/func_preproc_ses_01_task_resting_run_02_wf/bold_bold_trans_wf/merge/vol0000_xform-00000_merged.nii.gz

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 68, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 480, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 644, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 520, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/images.py", line 468, in _run_interface
    img.to_filename(out_fname)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/filebasedimages.py", line 334, in to_filename
    self.to_file_map()
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/analyze.py", line 1096, in to_file_map
    arr_writer.to_fileobj(imgf)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/arraywriters.py", line 562, in to_fileobj
    nan2zero=self._needs_nan2zero())
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/volumeutils.py", line 766, in array_to_file
    nan_fill=nan_fill if nan2zero else None)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/volumeutils.py", line 833, in _write_data
    fileobj.write(dslice.tostring())
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/openers.py", line 205, in write
    return self.fobj.write(*args, **kwargs)
  File "/usr/local/miniconda/lib/python3.6/gzip.py", line 264, in write
    self.fileobj.write(self.compress.compress(data))
OSError: [Errno 28] No space left on device
```

However, my disk usage on the share with the output and scratch is far below the max (using 1.2 of 2TB). Memory usage is also low (4 of 32GB). CPU has been pegged at 100% for 1 core. (There are 12 cores, most of which were in use during most of the fmriprep job, until the current hang). I've also checked the docker container, which does not have a cap on its disk image. So it's hard to see how fmriprep is running out of space. 

(Note that this crash report was prior to the current ongoing hang, so it could be the hang is unrelated to space).

The job took a long-time to get this far, so I'm loathe to stop it if there's a) some way to rescue it, or b) some debugging info I should get before terminating it.

What do you all recommend?

Thanks very much,
Daniel

**Comment by effigies** [comment]
If you're running out of space, my first guess would be that it's your working directory within the Docker container that's running out of space. Am I right in that you're using Docker, and not mounting a working directory? This would be a reasonable expectation with attempting to run 25 subjects in a single execution of fMRIPrep. (Incidentally, mounting the working directory will make re-running less costly, as we will be able to re-use completed steps from earlier runs.)

As to the initial hang, your screenshot shows the log indicating two nodes that have finished, which doesn't tell us much about what might still be running. Incidentally, what version of fMRIPrep are you running?

Finally, the only thing I can tell you to do to debug a currently-running instance of fMRIPrep is to use `htop` (if you have it; failing that, `top` would work) to identify whether any fMRIPrep-related jobs are consuming CPU or memory.

**Comment by danielkimmel** [comment]
Hi @effigies ,

Thanks for the feedback. 

Yes, I'm using fmriprep-docker.py

Here's the stuff about the docker container:
<img width="640" alt="pastedgraphic-3" src="https://user-images.githubusercontent.com/32337686/43537218-bc56cb92-958c-11e8-87b5-3e36fa0ef637.png">
<img width="640" alt="pastedgraphic-2" src="https://user-images.githubusercontent.com/32337686/43537219-bc6187f8-958c-11e8-98ed-437f1c70908b.png">

Here's the output of top:
<img width="640" alt="pastedgraphic-1" src="https://user-images.githubusercontent.com/32337686/43537227-c149fd18-958c-11e8-8dc3-c1872a28dd25.png">

**Comment by danielkimmel** [comment]
Hi @effigies 
I terminated the hung fmriprep run. FWIW, attached is the final terminal output.

Thanks!
Daniel

[crash-2018_08_01.txt](https://github.com/poldracklab/fmriprep/files/2254636/crash-2018_08_01.txt)

**Comment by effigies** [comment]
So it seems to say that you hit `^C` in the middle of garbage collection, but with the amount of memory you have, I'm going to guess that that was just chance. More likely you were in a busy loop, though it's not obvious what that was.

I'd still recommend not trying to run 25 subjects in a single instance of fMRIPrep.

**Comment by oesteban** [comment]
Hi @danielkimmel, any news on this?

**Comment by danielkimmel** [comment]
Hi Oscar

I've been away and haven't tested again running one fmriprep call per subject. I'll test it out next week and let you know.

Thanks!
Daniel
