### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#1232]
We should create an issue template to avoid us having to ask for commonly-needed information. Things we need for bug reports:

1) Version of fMRIPrep being run.
2) Full command (specific directories could be obscured) including `docker`, `singularity`, or `fmriprep-docker`
3) If still running, are any processes consuming large amounts of memory/CPU, as determined by `top`/`htop`?

Anything else?

And bugs/support aren't the only issues; we should probably include language to prompt good feature requests (e.g. references to papers for new techniques, etc.) or discussion topics.

**Comment by effigies** [comment]
We do have a infrequently-updated [FAQ](https://github.com/poldracklab/fmriprep/wiki/FAQ:-Frequently-asked-questions). We can add that, and have users check off a box saying "I have searched the FAQ for my issue" or similar.

**Comment by PeerHerholz** [comment]
If no one is already working on this, I would give it a try.

**Comment by effigies** [comment]
That's fine with me. Does anybody have experience with issue templates where users don't ignore them? That might be useful for designing one.

**Comment by mgxd** [comment]
One thing I really like is having different types of issues - we implemented something like that in pydra

https://github.com/nipype/pydra/issues/new/choose

**Comment by PeerHerholz** [comment]
Yeah, definitely a big fan of those. This also relates to @effigies comment [here](https://virtualdatalab.github.io/publications/) regarding different issue types. So, `bugs` and `feature request` are safe bets. Any thoughts on other potential types?

**Comment by jdkent** [comment]
[repronim has a section describing what should go into a bug report](http://www.repronim.org/module-reproducible-basics/05-misc/#a-good-bug-report-is-a-reproducible-one) 

We could have a `question` template that could potentially redirect the asker to neurostars if the question is more appropriate for that platform, and try to draw the boundary between what types of questions belong here versus neurostars.

A [recent comment](https://github.com/poldracklab/fmriprep/issues/1799#issuecomment-536302829) by @effigies provides indication of which questions go where.

**Comment by emdupre** [comment]
+1 on bug report, feature request, and question as categories !

I also suggested to @oesteban that we look into adding [Discourse Topic Templates to NeuroStars](https://github.com/poldracklab/fmriprep/issues/1849), so we could have an ideal NeuroStars issue template in mind when writing these, if that helps to distinguish use cases.

**Comment by oesteban** [comment]
@emdupre can I ask you to take ownership of this one and help @PeerHerholz in implementing it?

**Comment by tsalo** [comment]
Should this have been closed by #2012?

**Comment by effigies** [comment]
Yup. Thanks.
