### ISSUE TITLE
futures package being installed in Docker image

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#1240]
Despite nipype indicating that `futures` should only be installed for Python 2.7 (see [nipype/info.py#L151](https://github.com/nipy/nipype/blob/d2abc85cd98ea3a168a53306700312ca50eea87d/nipype/info.py#L151), we see the following in the Docker output:

```
Collecting futures (from nipype>=1.1.0->niworkflows>=0.4.2->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/cc/26/b61e3a4eb50653e8a7339d84eeaa46d1e93b92951978873c220ae64d0733/futures-3.1.1.tar.gz
```

I don't see this simply `pip install`ing nipype in a new conda environment locally, but it does occur within the Docker container. Upgrading `pip` to version 18 doesn't resolve the issue.

While I don't understand why this doesn't seem to cause issues for running fmriprep, it does cause issues for testing in the Docker container. (I also don't understand why it's not causing problems on Circle.)

**Comment by oesteban** [comment]
Good catch

**Comment by effigies** [comment]
This is a nipype wheel-building problem, not a misconfiguration on our end. See nipy/nipype#2678.
