### ISSUE TITLE
does fmriprep use spin echo EPIs for SDC when available

### ISSUE THREAD

**Issue by satra** [poldracklab/fmriprep#1246]
if our dataset has spin echo EPIs with blip up-down will fmriprep use them first before it uses the gradient echo BOLD runs?

for sdc, one can compute the warp from multiple sources, perhaps in a preferential order:
1. Explicit B0 fieldmaps
2. SE EPIs with multiple directions
3. BOLD runs with multiple directions
4. BOLD runs without multiple directions

since SE also has lower dropout, the correction would be better if it used 2 instead of using 3.

**Comment by oesteban** [comment]
I'm coming back to all fieldmaps-related issues.

What do you mean by?:

> 4. BOLD runs without multiple directions

Thanks

**Comment by satra** [comment]
in spm there is an option to estimate unwarping field from the data itself. see: https://www.fil.ion.ucl.ac.uk/spm/toolbox/unwarp/#RealignUnwarp

**Comment by oesteban** [comment]
I'm going to close this one in favor of nipreps/sdcflows#20 and especially nipreps/sdcflows#101. Thanks for posting Satra, we'll follow up in SDCflows proper.
