### ISSUE TITLE
Determining Microtime Resolution

### ISSUE THREAD

**Issue by aroyucsf** [poldracklab/fmriprep#1248]
Hello,

I'm trying to determine the microtime resolution for our data. It is my understanding that since we ran slice time corrections (STC), the microtime resolution should be the same as the number of slices specified during STC. Where can I find this? 

Thanks!

**Comment by oesteban** [comment]
If I understand correctly, the microtime resolution is something you can set in SPM analyses to calculate additional regressors (https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=spm;70bf5c7f.0904).

In principle, fMRIPrep does not modify anything that would change how you determine the microtime resolution.
