### ISSUE TITLE
Input device is not a tty, because of the -it option in docker?

### ISSUE THREAD

**Issue by isukrit** [poldracklab/fmriprep#1252]
Hi, it is not a problem/bug per se but while running a bash script for fmriprep-docker using the nohup command, we get the error "the input device is not a tty". I am trying to run it on a remote Linux machine (as discussed in https://github.com/poldracklab/fmriprep/issues/1199). Is there a way we can remove this? This has to do with the usage of -it option rather than -i option while running docker. Refer: https://serverfault.com/questions/897847/what-does-the-input-device-is-not-a-tty-exactly-mean-in-docker-run-output

**Comment by effigies** [comment]
That sounds plausible, but I don't have any specific experience with `nohup` + Docker. For a little context, the fmriprep-docker command is meant to abstract away the details of Docker, so adding flags to modify Docker flags starts getting into the territory where it requires further Docker knowledge. For users that need different invocations, we provide the `docker` command that we construct, so those users can edit it as needed.

So in this case, I would recommend copying the command that `fmriprep-docker` prints at its start, and then removing  the `-t` flag from that. And without a strong justification, I am disinclined to modify fmriprep-docker to enable or disable the `-t` flag.
