### ISSUE TITLE
rois_plot is missing resources specification

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#1254]
https://github.com/poldracklab/fmriprep/blob/38d6e0492662069de3ad634d51b885ec1f2ded65/fmriprep/workflows/bold/confounds.py#L207

See https://neurostars.org/t/fmriprep-stopped-due-to-memory-error/2275

**Comment by jdkent** [comment]
What would be the appropriate size for the resources specification, the size of the bold file?

**Comment by oesteban** [comment]
I'd say that would be a good approximation.

**Comment by effigies** [comment]
Just a quick note that at least loading the reference image and masks should be ~4x one volume, not the size of the original BOLD series, but not a big deal for now. (Also, creating an SVG is an operation of unknown memory usage.) We can adjust once we get profiling going.
