### ISSUE TITLE
[DOC] Enable text wrap in documentation tables?

### ISSUE THREAD

**Issue by tsalo** [poldracklab/fmriprep#1257]
Tables on the RTD site do not have text wrapping enabled, so there is often a lot of horizontal scrolling involved in reading them, especially for rows with very long descriptions (like the `--template-resampling-grid` parameter on the Usage page). It's easy to enable text wrapping in the tables, per [this set of instructions](https://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html). I can make the changes and open a PR if this is worth implementing.

On a related note, would it be worth it to use `sphinx.ext.linkcode` to link the documentation to GitHub instead of local snapshots of the code?

**Comment by oesteban** [comment]
> Tables on the RTD site do not have text wrapping enabled, so there is often a lot of horizontal scrolling involved in reading them, especially for rows with very long descriptions (like the ``--template-resampling-grid`` parameter on the Usage page). It's easy to enable text wrapping in the tables, per this set of instructions. I can make the changes and open a PR if this is worth implementing.

I think this is a good idea in general. The only issue is that most of the tables susceptible of this improvement are automatically generated by the argparse sphinx extension. I'm not sure it will be easy to play with.

> On a related note, would it be worth it to use sphinx.ext.linkcode to link the documentation to GitHub instead of local snapshots of the code?

Sure, that be great!
