### ISSUE TITLE
How to get BOLD signal for voxels in MNI space after preprocessing with fmriprep?

### ISSUE THREAD

**Issue by isukrit** [poldracklab/fmriprep#1262]
This will seem like a trivial question, but I am confused about what the output space of fmriprep func is. I think it is MNI152NLin2009cAsym for my pipeline, but I wanted confirm the steps that I need to do to get the time series for voxels I have MNI coordinates of. So here is the situation, I have some MNI coordinates and I need to extract the time series of voxels at those MNI coordinates from my data. According to what I understand: 
the coordinates of '*bold_space-<space>_preproc.nii.gz' should be in IJK space by default and I need to use its affine matrix to convert my MNI coordinates (for which I want to extract time series) to IJK space. 
It will be something like: 
```
import nibabel as nib
epi_img = nib.load('downloads/someones_epi.nii.gz')
affine = epi_img.affine
# do I use the affine directly or do I use its inverse?
M = affine[:3, :3]
abc= affine[:3, 3]

mni = M.dot([i, j, k]) + abc  #where i,j,k are some coordinates in MNI format at which I want to get the time series data.
```

Am I right? Thanks for your time!

**Comment by oesteban** [comment]
That is correct.

However, the most straightforward way of extracting your time-series is having your ROIs resampled in the same resolution of the `_preproc` file. Then, you'll be able to use voxel coordinates (ijk). Tools like nilearn are smarter and will use physical coordinates so you will not need to even apply the affine matrix.

This topic has been touched upon several times on neurostars (e.g. https://neurostars.org/t/fmriprep-connectivity-analysis/2290). Please let us know if you finally succeeded in extracting the time-series, and reopen if you need further details.
