### ISSUE TITLE
Preferred usecase for gitter chatroom ?

### ISSUE THREAD

**Issue by emdupre** [poldracklab/fmriprep#1264]
I had a quick question on my WIP PR that I thought might be better answered in a chatroom like [gitter](http://gitter.im). There is a [FMRIPREP gitter chat](https://gitter.im/poldracklab/fmriprep?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge); however, it is relatively inactive so I was unsure if this was an appropriate place to post. I checked the [Contributing guidelines](https://github.com/poldracklab/fmriprep/blob/master/CONTRIBUTING.md) but could find no mention of the gitter room or any other instant messaging platform (e.g., Slack). 

Is there a preferred use case for gitter, or any other chatroom ? If so, would it be possible to document this ?

Thanks !

**Comment by effigies** [comment]
I'll add the fmriprep gitter to my Riot client, but if people aren't logged in, Gitter tends to get slow responses, as it waits a bit to send a notification email.

I think the Brainhack slack tends to be the most responsive for quick questions.

**Comment by emdupre** [comment]
Ok ! It would just be great to document what the preferred workflow is -- for example, right now the readme links to the gitter channel, which could be removed if you want to encourage people to instead use the slack !

**Comment by effigies** [comment]
I'm okay with any channel, really, as long as I know to monitor it. @oesteban @chrisfilo Do you have preferences?

**Comment by chrisfilo** [comment]
I don't feel strongly about it, but in terms of growing a knowledge base I much prefer a system like neurostars. Providing support via instant messaging puts a lot of stress on maintainers and tends to lead to past questions being lost and hard to find. 

In short - I don't oppose the notion, but I would nudge users to use neurostars and keep gitter to dev chatter.

**Comment by emdupre** [comment]
That seems very reasonable to me ! Would it make sense, then, to remove the (gitter) chatroom from the README and instead link to the (slack) chatroom in the [Contributing section of RTD](https://fmriprep.readthedocs.io/en/stable/contributors.html#adding-dependencies) ?

Do you have any suggestions for when devs would want to reach out there vs in issues ? Having [some specific language](https://github.com/ME-ICA/tedana/blob/master/CONTRIBUTING.md#joining-the-conversation) might help with pointing others in the right direction !
