### ISSUE TITLE
Pin grabbits and pybids to specific versions in Dockerfile

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#1279]
These two packages evolve quickly and often break backwards compatibility. We should pin them to be in control when our side needs updating when pybids API changes.

**Comment by oesteban** [comment]
#1281 works for containers. The python distribution requires we also set versions on the setup script (i.e. [here](https://github.com/poldracklab/fmriprep/blob/eb7e4a5644d0d9788e1a51d7c630eae79f212bfb/fmriprep/__about__.py#L97-L98))

**Comment by effigies** [comment]
Are we worried about that?

**Comment by oesteban** [comment]
Oh no, just to note it down

**Comment by chrisfilo** [comment]
I personally wouldn't be.

Best,
Chris

PS Apologies for brevity and potential typos. This message was composed on
a phone.
