### ISSUE TITLE
Pepolar unwarping: QwarpPlusMinus requires a value for input 'in_file'

### ISSUE THREAD

**Issue by lukassnoek** [poldracklab/fmriprep#1287]
Hi!

I'm trying to preprocess a dataset using the 'pepolar' (blip-up, blip-down) technique with fmriprep (using the Docker interface, version 1.1.6). It crashes with the following error message:

`QwarpPlusMinus requires a value for input 'in_file'`

My data passes the `bids-validator` checks, so I don't think the problem is caused by the data itself.
I don't know how relevant it is for solving this issue, but I'm including the meta-data for the functional run and the corresponding "topup" (*_epi.nii.gz) below.

*Functional file .json*:
```json
"PhaseEncodingDirection": "j",
"EffectiveEchoSpacing": 0.00034538,
"ParallelReductionFactorInPlane": 1.51,
"MultibandAccelerationFactor": 4,
"WaterFatShift": 14.388,
"FlipAngle": 55,
"TotalReadoutTime": 0.01347,
"PulseSequenceType": "Multiband gradient echo EPI",
"TaskName": "wm"
```

*Topup .json*:
```json
"PhaseEncodingDirection": "j-",
"EffectiveEchoSpacing": 0.00034538,
"ParallelReductionFactorInPlane": 1.51,
"MultibandAccelerationFactor": 4,
"WaterFatShift": 14.388,
"FlipAngle": 55,
"TotalReadoutTime": 0.01347,
"PulseSequenceType": "Multiband gradient echo EPI",
"IntendedFor": "func/sub-RE01_task-wm_acq-Mb4Mm2Tr1600_bold.nii.gz"
```

If I should post more information about the data, let me know!

**Comment by effigies** [comment]
Ah, I see the problem. Some inputs got renamed in an upstream refactor in nipype (nipy/nipype#2674).

Thanks for the report. I'll submit a fix and we can release today or tomorrow.

**Comment by effigies** [comment]
Hi @lukassnoek, are you able to verify that #1289 fixes the issue for you? The easiest way to check is to use the `fmriprep-docker` wrapper and [patch in the working repository](https://fmriprep.readthedocs.io/en/stable/contributors.html#patching-working-repositories). Please let me know if you need any help.

**Comment by lukassnoek** [comment]
Sure thing! I cloned your repository (https://github.com/effigies/fmriprep) and changed to the fix-branch (`git checkout fix/qwarpplusminus`) and then tried the following command:

```
 fmriprep-docker $proj_dir/bids_topup $proj_dir/preproc_topup --nthreads 10 --omp-nthreads 4 --output-space template --fs-license-file /usr/local/freesurfer/license.txt --participant-label $base_sub -f /home/lsnoek1/spinoza/MB2018/fmriprep
```
...which generated the following docker-command:

```
 docker run --rm -it -v /home/lsnoek1/spinoza/MB2018/fmriprep:/usr/local/miniconda/lib/python3.6/site-packages/fmriprep:ro -v /usr/local/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /home/lsnoek1/spinoza/MB2018/bids_topup:/data:ro -v /home/lsnoek1/spinoza/MB2018/preproc_topup:/out poldracklab/fmriprep:1.1.6 /data /out participant --nthreads 10 --omp-nthreads 4 --output-space template --participant-label sub-RE02
```
... but this gave the following error:

```python
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 7, in <module>
    from fmriprep.cli.run import main
ModuleNotFoundError: No module named 'fmriprep.cli'
```
Maybe I'm using the `-f` flag the wrong way?

**Comment by lukassnoek** [comment]
Ah, yeah, now it works! At least, it starts running, but I get the following error:

```
traits.trait_errors.TraitError: The trait 'in_file' of a CopyHeaderInputSpec instance is an existing file name, but the path  'Qwarp_PLUS_WARP.nii.gz' does not exist.
Error setting node input:
Node: cphdr_warp
input: in_file
results_file: /tmp/work/fmriprep_wf/single_subject_RE02_wf/func_preproc_task_wm_acq_Mb4Mm3Tr550_wf/sdc_wf/pepolar_unwarp_wf/qwarp/result_qwarp.pklz
value: Qwarp_PLUS_WARP.nii.gz
```

**Comment by effigies** [comment]
I think I resolved that issue with nipy/nipype#2705. Could you try patching that in, as well?

**Comment by lukassnoek** [comment]
Yes, seems to work!

Thanks for fixing this!

**Comment by effigies** [comment]
Great! You'll need to keep using this until the release. Given that we're going to need to depend on fixes to nipype, I think we'll put off the release until Monday. If we need it sooner, we can patch the interface here.

**Comment by lukassnoek** [comment]
Thank you so much for the quick fix!
