### ISSUE TITLE
Output aparcaseg in requested output spaces

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#1290]
Right now aparcaseg is being produced only for `bold_space-T1w` even though MNI was specified as an output space. Context: https://neurostars.org/t/segmentation-compartment-files-in-functional-space-resolution-for-after-fmriprep/2486

**Comment by effigies** [comment]
Ah, I see.

**Comment by nirjacoby** [comment]
Hi all, 

I want to create a patch for this issue but want to know if to treat it as bug or enhancement. 

Short summary of the problem:
Currently if freesurfer was used, the FS label files (parcellation and segmentation) are created in the anatomical and functional folders.
In anat - label files are in T1w space (T1w grid).
In func - label files are created for each functional run in T1w space (functional grid) regardless of the requested output space (T1w, MNI or both).

Presumably all the func folder label files are just nearest neighbor resampling of the T1w space anat label files. Therefore, my suggestion is to treat this as a bug and the solution will be to always sample to the requested output spaces in the functional folder. This will give a meaningful label files that correspond to each of the output preprocessed run file that is ready to use (with no additional transformation required).

Does that sound like a reasonable path forward?
