### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by Irisfee** [poldracklab/fmriprep#1291]
Hi,

I am running fmriprep on docker with CPUs:12 and memory:26 GB for a single subject with 1.7iso. 

I run fmriprep with:

 fmriprep-docker /Users/***/Desktop/***/Nifti /Users/***/Desktop/*** participant --output-space T1w template fsaverage6 --fs-license-file /Applications/freesurfer/license.txt -vvv --low-mem --notrack --resource-monitor

I got the error:

> 180919-14:39:07,870 nipype.workflow WARNING:
> 	 [Node] Error on "fmriprep_wf.single_subject_001_wf.func_preproc_ses_1_task_Perception_run_04_wf.bold_mni_trans_wf.bold_to_mni_transform" (/tmp/work/fmriprep_wf/single_subject_001_wf/func_preproc_ses_1_task_Perception_run_04_wf/bold_mni_trans_wf/bold_to_mni_transform)
> 180919-14:39:09,515 nipype.workflow DEBUG:
> 	 Clearing 953 from queue
> Traceback (most recent call last):
>   File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 344, in main
>     fmriprep_wf.run(**plugin_settings)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 595, in run
>     runner.run(execgraph, updatehash=updatehash, config=self.config)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 162, in run
>     self._clean_queue(jobid, graph, result=result))
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 224, in _clean_queue
>     raise RuntimeError("".join(result['traceback']))
> RuntimeError: Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 521, in run
>     runtime = self._run_interface(runtime)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/itk.py", line 143, in _run_interface
>     for i, (in_file, in_xfm) in enumerate(zip(in_files, xfms_list))]
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
>     yield fs.pop().result()
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 432, in result
>     return self.__get_result()
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
>     raise self._exception
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/thread.py", line 56, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/itk.py", line 262, in _applytfms
>     runtime = xfm.run().runtime
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 521, in run
>     runtime = self._run_interface(runtime)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/fixes.py", line 29, in _run_interface
>     self.__class__.__name__, __version__))
>   File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/utils.py", line 179, in _copyxform
>     newimg = resampled.__class__(resampled.get_data(), orig.affine, header)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/dataobj_images.py", line 202, in get_data
>     data = np.asanyarray(self._dataobj)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/numpy/core/numeric.py", line 544, in asanyarray
>     return array(a, dtype, copy=False, order=order, subok=True)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/arrayproxy.py", line 293, in __array__
>     raw_data = self.get_unscaled()
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/arrayproxy.py", line 288, in get_unscaled
>     mmap=self._mmap)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/volumeutils.py", line 535, in array_from_file
>     getattr(infile, 'name', 'object')))
> OSError: Expected 7017840 bytes, got 857524 bytes from object
>  - could the file be damaged?
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
>     result['result'] = node.run(updatehash=updatehash)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
>     result = self._run_interface(execute=True)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
>     return self._run_command(execute)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 639, in _run_command
>     _save_resultfile(result, outdir, self.name)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/utils.py", line 309, in save_resultfile
>     savepkl(resultsfile, result)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/utils/filemanip.py", line 732, in savepkl
>     pkl_file.close()
>   File "/usr/local/miniconda/lib/python3.6/gzip.py", line 319, in close
>     myfileobj.close()
> OSError: [Errno 28] No space left on device

I am wondering why it reported that no space left on device, since there still quite a large amount space there?

thanks!

**Comment by effigies** [comment]
Because you're not passing the `-w` flag to `fmriprep-docker`, the working directory is being constructed inside the Docker image, which may have more constraints than disk space. You can check your Docker settings.

Alternately, you can try passing a `-w <some-scratch-directory>` option. This will also have the advantage that, if something fails, you can pick up where you left off.

**Comment by Irisfee** [comment]
It works then! thank you very much!
