### ISSUE TITLE
Update Confounds

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#1301]
### Filename

| Old | New |
|---|---|
| `func/sub-<sub_id>_task-<task_id>_run-<run_id>_bold_confounds.tsv` | `func/sub-<sub_id>_task-<task_id>_run-<run_id>_desc-confounds_regressors.tsv` |

### Columns

| Old | New |
|---|---|
| non-stdDVARS | DVARS |
| vx-wisestdDVARS | [`<remove>`](https://docs.google.com/document/d/17ebopupQxuRwp7U7TFvS6BH03ALJOgGHufxK8ToAvyI/edit?disco=uiAAAACNeECVM&usp=comment_email_discussion&ts=5bb44c3b)

I will note that RC1 indicated that X, Y, Z were to become TransX, TransY and TransZ as well. This was not generally discussed and made it into RC1 as a function of copy-paste. I think the impact here would be fairly far reaching for little gain, so I'm leaving that off this list until the discussion is resolved.

### Metadata

a/tCompCor columns must have an associated `Method` metadata. We can probably do this with:

`fmriprep/desc-confounds_regressors.json`:
```JSON
{
    "aCompCor00": {"Method": "aCompCor"},
    "aCompCor01": {"Method": "aCompCor"},
    ...
}
```

`GlobalSignal`, `WhiteMatter` and `CSF` should have the following metadata:

```JSON
{
    "GlobalSignal": {"Method": "Mean"},
    "WhiteMatter": {"Method": "Mean"},
    "CSF": {"Method": "Mean"}
}
```

`AROMAaggrCompXX` should indicate `ICA-AROMA` version. Not sure whether `"Method"` can be a dict with "Name" and "Version", or what.

**Comment by effigies** [comment]
Is this one done with #1586?

**Comment by oesteban** [comment]
Done for CompCor only. Added two unitary issues addressing each type of regressor separately.
