### ISSUE TITLE
fmriprep not using field maps

### ISSUE THREAD

**Issue by pvelasco** [poldracklab/fmriprep#1303]
Hi,

I'm trying to run fmriprep on my datasets and it seems like fmriprep doesn't find/read my fmaps.

The command I'm running is:

```
fmriprep \
    /data/staff/Pablo/scratch/hartleylab_test \
    /data/staff/Pablo/scratch/hartleylab_test_2 \
    participant \
    --fs-license-file /bids/etc/FS_license.txt \
    --template-resampling-grid "native"
    --participant_label 05
```

The stdout reads:
```
/usr/local/miniconda/lib/python3.6/site-packages/bids/grabbids/__init__.py:6: FutureWarning: grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8
  warnings.warn("grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8", FutureWarning)
181003-20:00:00,382 nipype.workflow IMPORTANT:
	 
    Running fMRIPREP version 1.1.7:
      * BIDS dataset path: /data/staff/Pablo/scratch/hartleylab_test.
      * Participant list: ['05'].
      * Run identifier: 20181003-200000_b44bb468-a24a-413d-a0bc-c916ca95d22e.
    
181003-20:00:02,318 nipype.workflow IMPORTANT:
	 Creating bold processing workflow for "/data/staff/Pablo/scratch/hartleylab_test/sub-05/func/sub-05_task-TASK_acq-normal_run-01_bold.nii.gz" (0.31 GB / 304 TRs). Memory resampled/largemem=1.25/2.20 GB.
181003-20:00:02,323 nipype.workflow IMPORTANT:
	 Using single-band reference file sub-05_task-TASK_acq-normal_run-01_sbref.nii.gz
181003-20:00:03,559 nipype.workflow IMPORTANT:
	 Slice-timing correction will be included.
181003-20:00:03,574 nipype.workflow WARNING:
	 SDC: no fieldmaps found or they were ignored (/data/staff/Pablo/scratch/hartleylab_test/sub-05/func/sub-05_task-TASK_acq-normal_run-01_bold.nii.gz).
181003-20:00:03,874 nipype.workflow IMPORTANT:
	 Creating BOLD surface-sampling workflow.
```

I tripled-checked that the fmaps json files have the IntendedFor field set:
```
 grep -B 1 -A 10 "IntendedFor" /data/staff/Pablo/scratch/hartleylab_test/sub-05/fmap/sub-05_acq-fMRI_dir-AP_run-01_epi.json 
  "InstitutionalDepartmentName": "Department",
  "IntendedFor": [
    "func/sub-05_task-TASK_acq-normal_run-01_bold.json",
    "func/sub-05_task-TASK_acq-normal_run-01_sbref.json",
    "func/sub-05_task-TASK_acq-normal_run-02_bold.json",
    "func/sub-05_task-TASK_acq-normal_run-02_sbref.json",
    "func/sub-05_task-TASK_acq-normal_run-03_bold.json",
    "func/sub-05_task-TASK_acq-normal_run-03_sbref.json",
    "func/sub-05_task-TASK_acq-normal_run-04_bold.json",
    "func/sub-05_task-TASK_acq-normal_run-04_sbref.json"
  ],
  "MagneticFieldStrength": 3,
```
I'm trying to debug this issue setting a pdb.set_trace() in `/fmriprep/workflows/bold/base.py`, at the line that reads: https://github.com/poldracklab/fmriprep/blob/b7b68d402fad70be9bbba9ce4d6cd6eeda7cada1/fmriprep/workflows/bold/base.py#L290
but when the execution reaches that point, it crashes with a `bdb.BdbQuit` error.

Any ideas of what can be wrong, or how to debug this issue?

Many thanks in advance,

-Pablo

**Comment by pvelasco** [comment]
Hi @effigies,
Thanks for catching that.  It runs fine now.
I did run the BIDS validator and it didn't throw any errors.

Just for the future.  What is the proper way of debugging fmriprep?

**Comment by effigies** [comment]
Generally speaking, I will dig through the working directory, find the failing node, and check the source. There should be a way of using `nipypecli` to debug nodes, but I use it so rarely I can't tell you the exact way to do it.

This is a weird one in that the issue happens before the workflow starts running. If `pdb` doesn't work, I don't really have a good suggestion. But really, the validator should catch this case. Care to open an [issue](https://github.com/bids-standard/bids-validator/issues) over there?
