### ISSUE TITLE
Could not find participants

### ISSUE THREAD

**Issue by hasanasim** [poldracklab/fmriprep#1309]
I am using the command
`"singularity run fmriprep-1.1.4.simg ds00001-0006 . participant --participant-label subjects1.txt"`

subjects1.txt is a text file with contents '01' to correspond to the first participant 'sub-01'.
I get this error.

 `

usr/local/miniconda/lib/python3.6/importlib/_bootstrap.py:219:

 RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 414, in build_workflow
    bids_dir, participant_label=opts.participant_label)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/utils/bids.py", line 106, in collect_participants
    ', '.join(participant_label)), bids_dir)
fmriprep.utils.bids.BIDSError:
---------- BIDS root folder: "/data/aca16mha/ds000001-00006" ----------
           Could not find participants [subjects1.txt]
-----------------------------------------------------------------------
bash-4.2$ 

'

**Comment by effigies** [comment]
For example, `--participant-label 01 02`.

**Comment by hasanasim** [comment]
> For example, `--participant-label 01 02`.

Great, thank you so much! Out of curiosity, if there is a large amount of participants, is it possible to do it through a txt file?

**Comment by effigies** [comment]
@oesteban Newlines become spaces in `$()`. For example,

```
cat > subjects1.txt <<END;
01
02
03
END
echo --participant-label $(cat subjects1.txt)
```

Output:

```
--participant-label 01 02 03
```

**Comment by oesteban** [comment]
hi @hasanasim did our suggestions fix your issue? Please reopen if not.
