### ISSUE TITLE
dead link to bids-validator in the docs

### ISSUE THREAD

**Issue by surchs** [poldracklab/fmriprep#1312]
Hey,

I noticed that the [link to the BIDS-validator in the docs](https://github.com/poldracklab/fmriprep/blame/master/docs/usage.rst#L21) is dead, probably because the underlying repo has moved. The bad link should now point to http://bids-standard.github.io/bids-validator/ . Do you want a PR with the fix?

**Comment by oesteban** [comment]
That'd be great!
