### ISSUE TITLE
Error in generate_report function

### ISSUE THREAD

**Issue by gmrosenb** [poldracklab/fmriprep#1313]
Hi,

I am trying to run a singularity image of fmriprep version 1.1.8 on an HPC, with singularity version 2.6.0. After successfully completing the bold_mni_trans_wf.merge, I get the following error:
```
/usr/local/miniconda/lib/python3.6/site-packages/nipype/algorithms/confounds.py:1022: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are th
e input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  betas = np.linalg.lstsq(X, data.T)[0]
/usr/local/miniconda/lib/python3.6/site-packages/matplotlib/contour.py:1173: UserWarning: No contour levels were found within the data range.
  warnings.warn("No contour levels were found"
```

The last line above is repeated multiple times, before the following error appears:

```
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 351, in main
    errno += generate_reports(subject_list, output_dir, work_dir, run_uuid)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/viz/reports.py", line 312, in generate_reports
    for subject_label in subject_list
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/viz/reports.py", line 312, in <listcomp>
    for subject_label in subject_list
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/viz/reports.py", line 302, in run_reports
    return report.generate_report()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/viz/reports.py", line 173, in generate_report
    text = (logs_path / 'CITATION.html').read_text()
  File "/usr/local/miniconda/lib/python3.6/pathlib.py", line 1195, in read_text
    return f.read()
  File "/usr/local/miniconda/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 6165: ordinal not in range(128)
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit

```

From what I can tell, at line 173 of /fmriprep/viz/reports.py, the script is trying to run the generate_report function which is trying to read CITATION.html. It doesn't seem like there is anything wrong with the citation file but I'm not sure. Here's a pdf version of the citation file: [CITATION.pdf](https://github.com/poldracklab/fmriprep/files/2465924/CITATION.pdf)

Below is the code we used to run the singularity image. The first line (setting SINGULARITYENV_PYTHONIOENCODING=UTF-8 ) was recommended by the people who run our HPC after the first time we encountered the error although it clearly did not fix the issue (plus, I'm assuming the --cleanenv flag might counter the SINGULARITYENV setting anyway).

```
SINGULARITYENV_PYTHONIOENCODING=UTF-8 
singularity exec --cleanenv /beegfs/work/public/singularity/fmriprep-1.1.8.simg fmriprep BIDS_SeqTest Out_SeqTest participant \
                --fs-license-file /beegfs/work/hartley/projects/seqTest/scripts/fsLicense/license.txt \
                --template-resampling-grid "native" \
                --participant_label ${SUBJ_ID} \
```

Do you have any thoughts about what might be going wrong?

Thank you for your help!

**Comment by gmrosenb** [comment]
Update: I tried the command unset PYTHONPATH and am still getting the same error. I also tried adding SINGULARITYENV_PYTHONIOENCODING=UTF-8  after the image name (and after cleanenv), and that still did not work. We would appreciate any other ideas you have!

**Comment by oesteban** [comment]
@alioco could you send us a PR with the fix?
