### ISSUE TITLE
crosstalk between fmriprep processes (v1.1.8)

### ISSUE THREAD

**Issue by toddt** [poldracklab/fmriprep#1314]
So this is a bit of a strange bug, but I'm nearly 100% certain it's not user-error.

I was concurrently processing two 50-60 subject datasets on an HPC, with each subject having their own job in the queue. After completion, some of the freesurfer outputs from dataset1 were found under the derivatives/freesurfer folder of dataset2.

Submitted jobs were executed like this:
singularity exec -B /om:/om -B /om3:/om3 -B /cm:/cm $proj/singularity_images/fmriprep_1_1_8.simg \
fmriprep $bids_dir $out_dir participant --participant_label $subject --nthreads 8 \
--mem_mb 13000 --ignore slicetiming --use-aroma --ignore-aroma-denoising-errors -w $scratch \
--fs-license-file /cm/shared/openmind/freesurfer/6.0.0/.license \
--template-resampling-grid /om/group/saxelab/OpenAutism/scripts/HarvardOxford-cort-maxprob-thr50-2mm.nii.gz

where the two different datasets had independent $bids_dir and $out_dir arguments.

During execution, a subject from the first dataset (EIB) did not find his pre-existing freesurfer outputs in the EIB/BIDS/derivatives/freesurfer directory (although they was there), and instead created a new freesurfer folder in the second dataset's (TASTI2) tree.

Unfortunately I deleted all of the slurm logs before I noticed this issue, but the first lines in the recon-all.log file, below, highlight the issue. Note that the subject is an EIB (dataset1) subject, and the input is coming from the EIB hierarchy, but the SUBJECTS_DIR is being set to TASTI2 (dataset2). All of the rest of that subject's outputs are correctly found in the EIB hierarchy.

[toddt@node014 scripts]$ more recon-all.log
Wed Oct 10 06:53:10 UTC 2018
/om3/group/saxelab/ASD_TOM/data/TASTI2/BIDS/derivatives/freesurfer/sub-SAXEIB69
/opt/freesurfer/bin/recon-all
-autorecon1 -i /om3/group/saxelab/ASD_TOM/data/EIB/BIDS/sub-SAXEIB69/anat/sub-SAXEIB69_T1w.nii.gz -noskullstrip -openmp 
7 -subjid sub-SAXEIB69 -sd /om3/group/saxelab/ASD_TOM/data/TASTI2/BIDS/derivatives/freesurfer
subjid sub-SAXEIB69
setenv SUBJECTS_DIR /om3/group/saxelab/ASD_TOM/data/TASTI2/BIDS/derivatives/freesurfer
F

**Comment by effigies** [comment]
Is `$scratch` dataset-dependent? It may be the case that you're reusing a scratch directory that already had the setup node. Can you try a new `$scratch` directory, just to rule that out?

**Comment by toddt** [comment]
No, scratch is the same workingdir for both datasets.

When I look in that workingdir, I see an fmriprep_wf directory. And under that directory is a child directory for each subject, along with a single fsdir directory, that is currently pointing to dataset2's output directory.

I would think that node would be regenerated every time the "derivatives" input changed, though, and that that input would change whenever the most recent dataset switched. Perhaps there's a race condition where multiple processes are updating it simultaneously and it ends up executing for some of those processes with incorrect inputs?

**Comment by effigies** [comment]
Yeah, if you use the same scratch directory, you could get race conditions.

**Comment by oesteban** [comment]
Hi @toddt, this is definitely a race condition on the shared working directory. The easiest fix is to add a dataset folder to the working directory (i.e. `-w work/dataset1`, `-w work/dataset2`, etc.)
