### ISSUE TITLE
TraitError complaining about irrelevant files?

### ISSUE THREAD

**Issue by MetaD** [poldracklab/fmriprep#1315]
Hello!
I got a TraitError when running with fmriprep v1.1.8. It looks quite weird to me, because seems like it's complaining about files in a completely irrelevant folder, which contains files resulted from previous fmriprep version for the same subject.

My directories are structured like this:

`hierarchy` (the bids directory)
-- `sub-149`
-- `sub-xyz` (other subjects)
-- `fmriprep`
----`c` (the directory where I'm running fmriprep from)
-------`output_118c` (output directory specified in fmriprep command)
-------`work` (working directory specified in fmriprep command)
----`old_output`(contains some old fmriprep output, including those for sub-149; no working directory here)

I was running fmriprep from that `c` folder, and the command is:
```
fmriprep /u/project/cparkins/data/hierarchy/ /u/project/cparkins/data/hierarchy/fmriprep/c/output_118c/ participant -w work/ --output-space T1w fsnative template fsaverage --ignore slicetiming --use-aroma --fs-license-file $FREESURFER_HOME/.license --participant-label 145 146 148 149 154
```

So I'd imagine that things in `old_output` folder really has nothing to do with this fmriprep command, since the none of the input, output or working directory is there. But the TraitError says that a list of files in the `old_output` folder was specified, which makes me very confused... I think I have done the same thing before (i.e. running fmriprep with old output around in some other folder) with an ancient version 1.0.8 and it didn't happen back then. Now this error also only happens with the `t1_2_mni` node and the `lesion_mask` input, and doesn't seem to happen every time I run fmriprep (even I always had the `old_output` there).

I'm trying to run the same command again after deleting the entire `old_output` folder, but still want to ask if this behavior is expected. Should I simply avoid putting old output files around? (How far away should I put them?)

Thank you so much in advance!

The error log:
```
Node: fmriprep_wf.single_subject_149_wf.anat_preproc_wf.t1_2_mni
Working directory: /u/project/cparkins/data/hierarchy/fmriprep/c/work/fmriprep_wf/single_subject_149_wf/anat_preproc_wf/t1_2_mni

Node inputs:

compress_report = auto
explicit_masking = True
flavor = precise
float = True
initial_moving_transform = <undefined>
lesion_mask = <undefined>
moving = T1
moving_image = <undefined>
moving_mask = <undefined>
num_threads = 8
orientation = RAS
out_report = report.svg
reference = T1
reference_image = <undefined>
reference_mask = <undefined>
settings = <undefined>
template = mni_icbm152_nlin_asym_09c
template_resolution = 1

Traceback (most recent call last):
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 408, in run
    cached, updated = self.is_cached()
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 294, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 488, in _get_hashval
    self._get_inputs()
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 531, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 276, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 103, in validate
    validated_value = super(File, self).validate(object, name, value)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/traits/trait_types.py", line 411, in validate
    self.error( object, name, value )
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'lesion_mask' trait of a RobustMNINormalizationInputSpecRPT instance must be an existing file name, but a value of ['/u/project/cparkins/data/hierarchy/fmriprep/old_output/fmriprep/sub-149/anat/sub-149_T1w_label-aparcaseg_roi.nii.gz', '/u/project/cparkins/data/hierarchy/fmriprep/old_output/fmriprep/sub-149/anat/sub-149_T1w_label-aseg_roi.nii.gz'] <class 'list'> was specified.
Error setting node input:
Node: t1_2_mni
input: lesion_mask
results_file: /u/project/cparkins/data/hierarchy/fmriprep/c/work/fmriprep_wf/single_subject_149_wf/bidssrc/result_bidssrc.pklz
value: ['/u/project/cparkins/data/hierarchy/fmriprep/old_output/fmriprep/sub-149/anat/sub-149_T1w_label-aparcaseg_roi.nii.gz', '/u/project/cparkins/data/hierarchy/fmriprep/old_output/fmriprep/sub-149/anat/sub-149_T1w_label-aseg_roi.nii.gz']
```

**Comment by effigies** [comment]
We explicitly ignore `derivatives/`, but most of the directory will be indexed. The solution will be to move old results out of the BIDS data directory (or into, e.g., `<datadir>/derivatives/fmriprep.old`).

Hopefully, as we conform naming to the BIDS Derivatives release candidate spec, some of these issues will go away, but I would still recommend against storing your old derivatives in such a manner. Does the BIDS validator warn you about your dataset?

**Comment by MetaD** [comment]
I think my dataset passed BIDS validator before, but just updated it to the new version and it does give me an error now for including non-BIDS directories. If I include a `.bidsignore` file in the BIDS directory, would fmriprep also ignore folders specified there?

Thanks for the info!

**Comment by effigies** [comment]
I think it should, but I can't be sure. We depend on pybids for parsing BIDS structures, which I believe has implemented that functionality.

**Comment by MetaD** [comment]
Sounds good. Thank you so much!
