### ISSUE TITLE
inconsistent output dimensions

### ISSUE THREAD

**Issue by niclong** [poldracklab/fmriprep#1317]
Hi, I am using fmriprep 1.1.6 via a singularity container on an HPC. My data are BIDS compatible (checked in the validator). My output spaces are {T1w,template,fsaverage5,fsnative}. fmriprep runs without errors and produces preprocessed anatomical and functional files, however, the preprocessed functional files have inconsistent and strange dimensions.

The input T1w: 176 x 256 x 256
The preproc T1w (sub-01_T1w_preproc.nii.gz): 176 x 256 x 256

The input functional: 124 x 124 x 72 x 198
The preproc functional in T1w space (sub-01_task-instruct_run-01_bold_space-T1w_preproc.nii.gz): 85 x 109 x 83

In another instance where I ran the exact same code but only specified {T1w} as the output space, the functional dimensions were 86 x 111 x 84 x 198. 

I found a discussion of this issue on Neurostars (https://neurostars.org/t/dimensions-mismatch-in-preprocessed-fmri-data-fmriprep-0-3-2/362), but could not interpret how to use the proposed fix (https://github.com/poldracklab/fmriprep/pull/513). 

Any help would be appreciated; let me know if I should attach any files.

**Comment by effigies** [comment]
To be clear, for the instance where you used T1w only, was that the same BOLD series or a different one?

**Comment by niclong** [comment]
The same BOLD series.

**Comment by oesteban** [comment]
I think these differences in sizes are too big to represent a regression of #513.

Two questions:
1. What is the exact command line you are running?
2. What are you running in parallel? (in other words, have you run several instances of fmriprep in parallel sharing the working directory?)

**Comment by niclong** [comment]
1. Here's the exact command:

singularity run --bind ${group_dir}:${group_dir} ${image} ${bids_dir} ${derivatives} participant \
--participant_label ${subid} \
--output-space {T1w,template,fsaverage5,fsnative} \
-w ${working_dir} \
-vvv \
--ignore {fieldmaps,slicetiming} \
--fs-license-file ${freesurferlicense}

where the directory structure is:

group_dir/studyName/bids_dir/subid
group_dir/studyName/derivatives/working_dir

image = group_dir/studyName/containers/fmriprep-1.1.6.simg
subid = "sub-01"
freesurferlicense = group_dir/studyName/containers/license.txt

2. Currently I am not running anything in parallel, I've only run one run for one subject.

**Comment by oesteban** [comment]
Could you share that subject privately for us to replicate? This is truly puzzling

**Comment by effigies** [comment]
I'm guessing that there's a slight stochastic difference in either BOLD-EPI registration. Or, if we're cropping to a bounding box (I don't think we are?), there could be a small difference in skull-stripping.

I agree that it doesn't seem related to #513, as that is based on variations in voxel size influencing the resampling grid across different files.

For myself, I would be less concerned about minor variations from run to run than with variations within spaces; if you have multiple BOLD series in the same subject's T1w space with different FoVs, then probably the correct fix is to fix up the bounding boxes across series before saving the derivatives.

**Comment by niclong** [comment]
Because of our IRB, I am not able to share the data. 

What are the units of the preprocessed BOLD data dimensions? I see that part of its creation utilizes the file:

highres001_N4Corrected0_masked_reference.nii.gz

found in:

func_preproc_task_instruct_run_01_wf/bold_reg_wf/gen_ref/

But I'm not clear on how that mask is created with those particular dimension values as it is derived from two masks matching the anatomical dimensions (176 x 256 x256) and one mask matching the original BOLD dimensions (124 x 124 x 72).

**Comment by ilkayisik** [comment]
Hi everyone, 
I realized I am having a very similar issue:
Running fMRIPREP version 1.1.4 via docker container, 
My data are also BIDS compatible [used heudiconv, 
My output spaces are T1w template fsnative fsaverage. 
fmriprep runs without errors [occasionally giving this warning: Note on orientation: qform matrix overwritten. The qform has been copied from sform]

There is no change in the anatomical data matrix
The input T1w: 176 x 256 x 256
The preproc T1w (sub-01_T1w_preproc.nii.gz): 176 x 256 x 256

However the functional output dimensions are different than the original
The input functional [sub-01_task-video_run-05_bold.nii.gz: 64 x 64 x 32 x 180
The preproc functional in T1w space [sub-01_task-video_run-05_bold_space-T1w_preproc.nii.gz]: 49 x 60 x 46 x 180

and also different across participants

The input functional[sub-02_task-video_run-05_bold.nii.gz]: 64 x 64 x 32 x 180
The preproc functional in T1w space [sub-02_task-video_run-05_bold_space-T1w_preproc.nii.gz]: 48 x 63 x 45 x 180

I ran this code: 
```for subj in {01..10}; do

docker run -ti --rm \
      -v /Users/ilkay.isik/localApps/freesurfer/license.txt:/opt/freesurfer/license.txt:ro \
      -v /Users/ilkay.isik/project_folder_temp/fc_content/MRI_data/data_BIDS/Nifti:/data:ro \
      -v /Users/ilkay.isik/project_folder_temp/fc_content/MRI_data/data_BIDS/Nifti:/out \
      poldracklab/fmriprep:latest \
      /data /out/out \
      participant \
      --participant-label sub-$subj \
      --ignore slicetiming \
      --output-space T1w template fsnative fsaverage \
      --use-aroma \
      --write-graph \
      --nthreads 2 --n_cpus 3 --mem_mb 20000 \
      --work-dir /out/out/temp_files/sub-$subj
 done```

**Comment by effigies** [comment]
@niclong Sorry about the delay. The new dimensions are the result of reslicing the BOLD in the same space as the T1w, while keeping the same voxel sizes. So small differences of rotation in the registration might lead to one voxel more or less on each side, so up to a difference of two voxels per dimension.

**Comment by oesteban** [comment]
I think this has been resolved. Please feel free to reopen if that is not the case.
