### ISSUE TITLE
This document format requires a nonempty <title> element. 

### ISSUE THREAD

**Issue by hasanasim** [poldracklab/fmriprep#1319]
I get the error
"This document format requires a nonempty <title> element. Please specify either 'title' or 'pagetitle' in the metadata."

How do I go about specifying a title exactly?

**Comment by oesteban** [comment]
You can dismiss that warning. It is generated by the generator of the new citation boilerplate, in one of the conversion from markdown to html/latex.

I'll see whether we can just not show it.

**Comment by oesteban** [comment]
I should have said ignore it. 👍

**Comment by oesteban** [comment]
https://neurostars.org/t/help-with-fmriprep/2654/2?u=oesteban

**Comment by oesteban** [comment]
Closed via #1464
