### ISSUE TITLE
A nice way to add missing BIDS info

### ISSUE THREAD

**Issue by KevinAquino** [poldracklab/fmriprep#1327]
Hi all,

Our scanner has not been saving some key properties of each protocol in the DICOM header (it is a some unfavourable combo of the CMMR and our PACS system) I thus need to add metadata manually. Are there any nice scripts people use that can add the necessary BIDS tags -- slice timing etc. I thought I'd ask before I go reinventing the wheel (if it exists!) 

Thanks!

**Comment by effigies** [comment]
I don't know of any off the top of my head, but the wider BIDS community has a lot of experience in it. I would recommend asking this question at [Neurostars](https://neurostars.org/) to get a larger audience.

**Comment by KevinAquino** [comment]
Great thanks! I'll keep this issue open in case I find a solution (ill post it on here)

**Comment by effigies** [comment]
Further discussion should happen on Neurostars: https://neurostars.org/t/a-nice-way-to-add-missing-bids-metadata/2668
