### ISSUE TITLE
Remove methods section from CLI output

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#1349]
The copyable methods section in the CLI output makes reading the output even harder than it already is. I don't mind it being part of the derivatives (or logs), but I find it extremely irritating when trying to debug.

Does anybody strongly oppose removal?

**Comment by oesteban** [comment]
I'd be fine with that. It served the purpose, but now I agree it is irritating.

**Comment by oesteban** [comment]
Okay, after #2018, the boilerplate is printed at the very end, and only if fMRIPrep ran successfully. Do we still want to get rid of it or that would solve the concerns?

**Comment by effigies** [comment]
I don't see the value of it in the terminal output.
