### ISSUE TITLE
RC1 derivatives - Update documentation

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1351]
In particular https://github.com/poldracklab/fmriprep/blob/8f734520370c26a82d46935f6f88c8e2e1040cae/docs/outputs.rst#L49-L93

**Comment by oesteban** [comment]
Maybe it would be legitimate to just link to the RC1 google docs?

**Comment by effigies** [comment]
I agree that we should link to the RC1 google doc, but that is much broader than fMRIPrep, so I think it's still valuable to clarify what derivatives we actually generate.

Perhaps we could generate the outputs automatically, and then link to the spec for descriptions? (That might be a bit much for one-time changes, but in case there are new outputs or further spec changes, it could be worth it.)
