### ISSUE TITLE
Inconsistent Preprocessed Functional Output Dimensions

### ISSUE THREAD

**Issue by aureliooo** [poldracklab/fmriprep#1360]
Hello! I am using fmriprep 1.1.4 (I believe) via a singularity container. My data have been BIDS validated, and it is also a very large dataset of resting state from multiple lab sites. I am trying to run comparisons across this data from different sites but the preprocessed functional outputs are inconsistent across site.

For example, across all subjects in one site, the registered preprocessed functional output file (in MNI152NLin2009Asym standard space) is 3.125 x 3.125 x 4 with dimension size 63, 74, 49.

However, from another site, the output (also in MNI152NLin2009Asym standard space) is 3.281 x 3.281 x 4.14 with dimension size 60, 71, 47. 

I am unable to compare these different sites using these outputs because of the inconsistency even though they should all be in standard MNI space. It seems as if the registration is dependent on input sizes. I know there are similar issues on here but I am unsure what the solution is (or if there even is one at the moment). Any help or redirection would be super helpful! Thank you so much!

**Comment by effigies** [comment]
Yes, the size of the input image will affect the size of the image in template space. The template doesn't specify a bounding box, and so we use the smallest bounding box that will contain all data from the source image. That said, they should all be in alignment, so it's just a matter of adjusting the bounding boxes.

You can use [`nilearn.image.resample_to_img`](https://nilearn.github.io/modules/generated/nilearn.image.resample_to_img.html#nilearn.image.resample_to_img) to update the bounding boxes, and get all images so that the same voxel in each image refers to the same location in template space.

**Comment by effigies** [comment]
Oh sorry. I see the voxel sizes are also different. You may want to pass `--template-resampling-grid 3mm` when running fMRIPrep.

**Comment by aureliooo** [comment]
When I use that flag, 3mm is read as a path which says doesn't exist. I will use the 2mm option for now which does seem to work, but should the 3mm also be an available template?

**Comment by effigies** [comment]
It looks like we don't currently have a 3mm-resampled image to target. If you take the first volume of one of your preprocessed BOLD series from your existing outputs (I would choose the one with the highest resolution and largest field of view), you could target that. They should be in the right space. (@oesteban can you verify I'm not typing nonsense?)

**Comment by oesteban** [comment]
Oh, yes, the `--template-resampling-grid 3mm` will not work out. Defining the behaviors of the output gridding is very tricky. For now, I think that templateflow/templateflow#2 would be the easiest way forward until we come up with a better solution (this is highly related to other concerns we need to address in the context of #1334 .

But yes, let's add a new 3mm resampling target.

**Comment by oesteban** [comment]
Is this a duplicate #1317 ?
