### ISSUE TITLE
Plugin-fix for memory issues fails in 1.2.1

### ISSUE THREAD

**Issue by markushs** [poldracklab/fmriprep#1363]
Hi!

We've been running large MB-datasets successfully using fmriprep 1.1.8 and the the "--use-plugin" argument (yaml file configured as in #1259). 

However, when testing out version 1.2.1 we get the following error (on the same data with the same  input parameters as in 1.1.8):

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/44242647/47990567-2013c080-e0e8-11e8-85d3-f3740fec9e57.png">

The error occurs immediately after the citation dump (i.e., before initiation of any workflows)

Here's the command:

<img width="775" alt="image" src="https://user-images.githubusercontent.com/44242647/47991274-fe1b3d80-e0e9-11e8-9480-13c5f75d3bf1.png">

And the content of the yaml-file:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/44242647/47991204-cdd39f00-e0e9-11e8-96f2-25885f7dce98.png">

We do not see the error when running fmriprep without the --use-plugin argument (however other issues arises, see #1365).

Any ideas?

Thanks!
Markus

(sorry about the screenshots - our data is stored in a secure environment that won't even let us copy-paste text)

**Comment by effigies** [comment]
Hmm. It's not obvious what the problem is, here. Is this a clean working directory (passed with `-w`), or, if not, does it still occur if you use a clean working directory?

**Comment by markushs** [comment]
Yes, I used a clean working directory. Replicated the issue with `-vvvv`. Not much more information, however:

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/44242647/48032386-bd5a0d80-e157-11e8-98dc-0260f1869951.png">

**Comment by effigies** [comment]
Oh, I see. This is a nipype issue, related to fixes in nipy/nipype#2754, which was needed for Python 3.7 compatibility.

I'll submit a patch over there.

**Comment by effigies** [comment]
So I cannot for the life of me figure out how you're getting to the point where you're trying to pickle that particular object; I'm unable to write a test for my fix. Are you able to reproduce this problem on a local system where you can use `fmriprep-docker`? If so, then we should be able to test my fix without just releasing and seeing if it resolves your problem.
