### ISSUE TITLE
Fmriprep 1.2.1: ica_aroma_wf.rm_nonsteady: skip_vols argument missing

### ISSUE THREAD

**Issue by markushs** [poldracklab/fmriprep#1365]
Hi!

We're testing out 1.2.1 and get the following errors for all datasets during ICA_AROMA:

<img width="1636" alt="image" src="https://user-images.githubusercontent.com/44242647/47993432-b7c8dd00-e0ef-11e8-88c1-c4f1ce6f01b8.png">

The error log says:
<img width="1609" alt="image" src="https://user-images.githubusercontent.com/44242647/47993467-cb744380-e0ef-11e8-85fb-4a1c1a20f721.png">

I guess this is likely due to the changes following #1335, but looking through the code I couldn't see any obvious problems (my python-skills are limited, however..). For information, we're running the following fmriprep-command on (BIDS-conformed) MB-data with single-band refs:

<img width="725" alt="image" src="https://user-images.githubusercontent.com/44242647/47993767-a3391480-e0f0-11e8-8573-e35f97aa6556.png">

(sorry about the screenshots - our data is stored in a secure environment that won't even let us copy-paste text).

Any ideas?

Thanks!
Markus

**Comment by effigies** [comment]
Hi, thanks for the report. I think the issue is that you have single-band references, which means that we don't attempt to use non-steady-state volumes to create a reference image, so we skip discovery and counting altogether. I'll push a change to fix that.
