### ISSUE TITLE
"template_transforms "-output of init_anat_template_wf seems to be off

### ISSUE THREAD

**Issue by Gilles86** [poldracklab/fmriprep#1371]
Hi there,

I am trying to make a version of fmriprep that can gracefully deal with MP2RAGEs. I seem to fail quite ungracefully.

 I need the `template_transforms`-output of the `init_anat_template_wf` workflow, so that I can get the 2nd inversions into the same template space.

However, when I use those transforms to transform the T1w-template to the original T1ws with FSLeyes, FSL applyXFM or ANTS's ApplyTransforms, the transformation is completely off. The template ends up translated a couple of cms.

I have the suspicion that there is something wrong with the `fmriprep.interfaces.image.Conform`-interface. If I apply the output matrix fo this interface to the input of the interface, I get a very different orientation from what the interface outputs itself.

Anyone a clue what happens here?

**Comment by effigies** [comment]
It's hard to say what might be wrong from your description. It's plausible that the conformation step may be missing a translation component if there are flips. Are you able to provide example images and explain how you're feeding them through template construction?

**Comment by Gilles86** [comment]
Hey @effigies ,

I sent you an email with the two anatomical images.

if I do:
```
t1w = '/data/sub-01/anat/sub-01_T1w.nii.gz'
t1w_im = nb.load(t1w)

# Conform data
conform = Conform()
conform.inputs.in_file = t1w
conform.inputs.target_shape  = t1w_im.header.shape
conform.inputs.target_zoom  = t1w_im.header.get_zooms()

r = conform.run()

# Try to conform using the outputted matrix
applier = fsl.ApplyXFM()
applier.inputs.in_file = t1w
applier.inputs.in_matrix_file = r.outputs.transform
applier.inputs.reference = t1w
r2 = applier.run()
```

Then the conformed image of `Conform` (`r.outputs.out_file`) is very different from the output `ApplyXFM` (r2.outputs.out_file).


I will try to see what happens when I already reorient2std the images before I put them into this workflow.

**Comment by effigies** [comment]
I've reproduced your issue, but I'm having trouble thinking through the transforms at the moment. I also don't fully understand how FLIRT applies transforms. For instance, when you provide the image as the transform reference, what internal adjustments does it apply?

I'll try to think through this as I can. But just note that both images have the same values for the same RAS coordinates.

```
ras = A * ijk
ras = A' * ijk'
ijk' = A'^-1 * A * ijk
```

I've verified that the transform == `A'^-1 * A`, so at least by the internal logic, we're not doing anything obviously wrong. So I need to figure out where the assumptions are being violated.

It's possible that what FLIRT really wants is an RAS-RAS transform (which should be the identity matrix), and the reference should just have a target affine indicating that it should be RAS-oriented, not LAS.

**Comment by effigies** [comment]
Sorry, not trying to say it's FSL's "fault", so much as I think that we aren't speaking the same language, and I'm honestly not sure how FSL represents the same transform. The transform is specifically flipping the first dimension of the data matrix and the translation difference between the RAS origin in the two spaces.

I assume you're converting from FSL format to ANTs with convert3d or similar? If so, they should produce an ITK transform that ANTs will interpret in the same way that FSL interprets this one. So solving one should solve the other.
