### ISSUE TITLE
Upgrade minimum Python to 3.7

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#1390]
As of Python 3.7, [`concurrent.futures.ProcessPoolExecutor`](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor) supports passing a [`multiprocessing.context`](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods) context (as well as passing initialization arguments).

Combined with efforts to reduce the memory overhead of `nipype.interface.CommandLine` spawns, setting the default context to `ForkServerContext` (as we currently do, though it has no effect in `MultiProc`) should help reduce the multiprocessing memory overhead to a bare minimum.

**Comment by effigies** [comment]
Marking external as I expect we'll need to patch Nipype to enable 3.7-only features in `MultiProc`.

**Comment by nirjacoby** [comment]
@effigies can you explain the implication/solution to this?
Is this a reason for fmiprep-docker not to work?
Since starting to use 1.2.2 I have not been able to run through with error traceback to multiproc

**Comment by effigies** [comment]
This should have no effect on `fmriprep-docker`, which will remain compatible with all current Python versions (2.7, 3.4-3.7). This is about memory issues which have been plaguing us for some time now. There are two related errors:

1) Using the `LegacyMultiProc` plugin, processes killed by the OS (usually for excessive memory requests) are not caught, and fMRIPrep will simply hang.
2) Using the `concurrent.futures`-based `MultiProc` plugin does not have that issue, but also does not do as much to keep memory consumption reasonable, causing newly forked processes to be killed.

It appears with a little work, we can use the tools that are available in 3.7+ to get us to the point where `MultiProc` consumes less memory.

I don't understand your comment about an "error traceback to multiproc".
