### ISSUE TITLE
Singularity build seems to fail

### ISSUE THREAD

**Issue by hstojic** [poldracklab/fmriprep#1392]
I'm trying to build the singularity image per instructions on our HPC, with Singularity 2.5.2

When I try to build the image, with the following command:
`singularity build Scratch/fmriprep-1.2.2.simg docker://poldracklab/fmriprep:1.2.2`

I get a lot of errors of following type
ERROR   [U=191821,P=39557] copy_data()                               tar extraction error: Write failed
WARNING [U=191821,P=39557] extract_tar()                             Warning handling tar header: Write failed

I presume this causes improper build of the image and the code doesn't work - if I try to use the image I get an error:
`/.singularity.d/runscript: 3: exec: /usr/local/miniconda/bin/fmriprep: not found`

There is a mention of RAM being the issue at Singularity github repo: https://github.com/sylabs/singularity/issues/1526

Could anyone offer some guidance?

**Comment by effigies** [comment]
Did you try using some other TMP directory, as suggested in that thread? I haven't experienced this, but fMRIPrep is a large image, so exhausting RAM is entirely possible.

**Comment by hstojic** [comment]
It seems like there were two issues:
1. Our HPC doesn't allow building singularity images
2. Default singularity cache/tmp folders were not writable

Solution was to to redefine environment variables, setting them to a writeable location (in my case these were folders in my Scratch space) and pull the image rather than build it:
```
export SINGULARITY_CACHEDIR=/home/ucjttoj/Scratch/.singularity/
export SINGULARITY_TMPDIR=/home/user/Scratch/.singularity/tmp
export SINGULARITY_LOCALCACHEDIR=/home/user/Scratch/.singularity/tmp/
export SINGULARITY_PULLFOLDER=/home/user/Scratch/.singularity/pull
export SINGULARITY_BINDPATH=/scratch/scratch/user
```
Might be good to add few additional lines about this in the documentation?

**Comment by oesteban** [comment]
> Might be good to add few additional lines about this in the documentation?

Sure! Please do send a PR :)

**Comment by hstojic** [comment]
Will do!

**Comment by oesteban** [comment]
Closing and looking forward to the PR with improved documentation :)

**Comment by oesteban** [comment]
Moved to a private email discussion
