### ISSUE TITLE
Some Sentry messages seem to be truncated

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#1400]
Example https://sentry.io/poldracklab/fmriprep/issues/768434032/events/36874332501/

Note that both "message" as well as "traceback" are truncated, but the latter is twice as long as the former.

**Comment by chrisfilo** [comment]
Traceback seems to be truncated at 16384 characters.

**Comment by effigies** [comment]
Maybe the way to go about fixing this is to give nipype a config option to display the final N characters of stdout? It will probably be generally true that the relevant lines will be the final lines.

**Comment by chrisfilo** [comment]
I'm not sure how this looks on the console. For Sentry I was planning to split `traceback` into multiple chunks each at most 16384 characters.
