### ISSUE TITLE
Update CONTRIBUTING guide

### ISSUE THREAD

**Issue by emdupre** [poldracklab/fmriprep#1403]
Several recent questions from new contributors have made me realize we could update the CONTRIBUTING guide to help better orient people to the project ! I'm going to open a PR with some suggested changes, but open questions include:

* Did we decide if we're maintaining the gitter chat room (see #1264) ? It's still listed in the README. 
* Is there a code of conduct for fmriprep ? For some reason I remembered that there was, but I can't find any trace of it, now !

**Comment by effigies** [comment]
I think inertia has decided us on Gitter. I think we should kill it (not sure if there's a way to remove it from gitter altogether) and just suggest using Neurostars for general questions and the issues page for feature requests and bug reports.

BIDS, BrainHack and Nipype all have CoC's, but I don't think we've posted our own. My main hold up to doing it myself is that I haven't had the energy to compare and contrast the various templates out there. @chrisfilo Do we have a lab standard or other preference? @emdupre If you have one(s) you recommend, I'd happily welcome the contribution.

**Comment by chrisfilo** [comment]
+1 for know killing gitter and adding CoC. The covenant (used in bids and
nipype) should be a good template.

**Comment by emdupre** [comment]
Ok ! If there's a consensus around this I can update the PR to address both of these issues as well.

For covenant we need to list a contact point for enforcement -- are there preferences on who it should be ? I'd imagine @oesteban as project lead but won't sign anyone up unless I get a specific ok !

**Comment by oesteban** [comment]
Thanks a lot for this! Thumbs-up!. Yes, you can set me as the contact point.

**Comment by effigies** [comment]
I'd prefer it to be two people, which would make it obvious what to do if either of them is the subject of a claim. I'm happy to be a point of contact, if nobody objects.

**Comment by emdupre** [comment]
Yes, two people is definitely ideal :+1: Ok, I'll list both of you ! Thanks so much :sparkles:
