### ISSUE TITLE
sentry attempting error message with --anat-only

### ISSUE THREAD

**Issue by yidilozdemir** [poldracklab/fmriprep#1423]
Hello,

I run fmriprep with the command with different memory/thread configurations to troubleshoot a possible memory problem
`docker run --rm -it -v /home/vm01/local/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /home/vm01/local/freesurfer/ds002:/data:ro -v /home/vm01/local/freesurfer:/out poldracklab/fmriprep:1.2.3 /data /out participant --anat-only --mem_mb 15000 -vvv --omp-nthreads 4`
 and I have been getting this error message:
`181125-20:48:15,725 nipype.utils DEBUG:
	 Copying File: /out/fmriprep/sub-11/figures/sub-11_reconall.svg->/tmp/work/reportlets/fmriprep/sub-11/anat/sub-11_reconall.svg
Sentry is attempting to send 1 pending error messages
Waiting up to 2.0 seconds
Press Ctrl-C to quit
`

I checked the produced html file and there is no error to report, but I see that the docker sees func files. In the produced freesurfer folder for the subject, I see all the files freesurfer normally creates, and those are all I need.

Can this still be a memory related issue and I am missing some files, or is the sentry attempting to send an error message because it sees func and doesn't know how to handle --anat-only?

FYI I am running this from a VM 
```
$ vmstat
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 0  0   8960 5095276 4190220 4691660    0    0     7    17    1    6  4  0 96  0  0`
```

Thank you for the help
Idil

**Comment by effigies** [comment]
I suspect this is actually a success report... We're trying to get a sense of what proportion of jobs complete successfully, and not merely accumulate errors. @chrisfilo Would a success report appear this way?

**Comment by chrisfilo** [comment]
Yes correct -  the sentry message can be ignored.

To check if FMRIPREP run correctly you can:
1. Look at the exit code - if it's anything else than 0 means that there were errors
2. Check HTML reports for error.

**Comment by yidilozdemir** [comment]
Thank you!
