### ISSUE TITLE
docker install issue on windows 

### ISSUE THREAD

**Issue by f003mrp** [poldracklab/fmriprep#1461]
Trying to get a docker to singularity image made. I get an error that seems to be problematic for docker where tar is unable to function correctly due to overlay. Tried switching to overlay2 with no success. Docker suggests using bsdtar instead of tar but I am unable to get this functioning.

**Comment by oesteban** [comment]
Hi, you can get the latest fmriprep singularity image from here: https://www.dropbox.com/s/mfmzqtpx88bg9o4/poldracklab_fmriprep_1.2.5-2018-12-04-2ef6b23ede2a.img?dl=0

Other than that, we'll need a better description of everything you've tried and settings because it is not clear at all from your post.

**Comment by f003mrp** [comment]
Thanks for sending that over.

So I am using the current version of docker on a windows 10 64-bit machine.

Following the instructions on the fMRIprep webpage I run this code (using my computer's directories):

docker run --privileged -t --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v C:\to\my\output\image:/output \
    singularityware/docker2singularity \
    poldracklab/fmriprep:1.2.5

It appears to download fine and then starts a sandbox (step 1) on step 2 it fails with multiple versions of this error code:

tar: etc: Directory renamed before its status could be extracted

and then says:

 tar: Exiting with failure status due to previous errors


googling these errors led me to this page:

https://github.com/docker/hub-feedback/issues/727

[https://avatars3.githubusercontent.com/u/1364012?s=400&v=4]<https://github.com/docker/hub-feedback/issues/727>

Automated build fails on 'tar' with: "Directory renamed before its status could be extracted" · Issue #727 · docker/hub-feedback · GitHub<https://github.com/docker/hub-feedback/issues/727>
github.com
Join GitHub today. GitHub is home to over 28 million developers working together to host and review code, manage projects, and build software together.


At different points, they suggest trying to use AUFS instead of overlay or overlay2 instead of overlay both options did not work for me. They also suggest using bsdtar instead of tar but I think this must be implemented in the actual code so I was unable to test this.


Please let me know if you need more specific information. It's also quite possible I just messed up something easy along the way!

Thanks again,

Travis

________________________________

**Comment by oesteban** [comment]
I would say this is an issue from running `singularityware/docker2singularity` on a Windows filesystem. But I don't think this is an fMRIPrep's problems itself.

Please force an update of the docker2singularity image and try again. If the problem persists, please report the issue in their repository.
