### ISSUE TITLE
Question: purpose of ubuntu.tar.gz

### ISSUE THREAD

**Issue by jdkent** [poldracklab/fmriprep#1470]
I am using the fmriprep `.circleci/config.yml` as a template for [NiMARE](https://github.com/neurostuff/NiMARE) (e.g. neurostuff/NiMARE#62) (this config has a lot of useful features! :100: ), and I am curious what the purpose of the [ubuntu.tar.gz](https://github.com/poldracklab/fmriprep/blob/dd0f4d4dfc26b107dfd9073760c2d03940051552/.circleci/config.yml#L24) is and whether it is necessary.

**Comment by jdkent** [comment]
I see, thanks! I linked where the image gets loaded from the cache, but where/when did the image get first saved to cache? I couldn't see an obvious command that said to save `ubuntu.tar.gz` in cache.

**Comment by effigies** [comment]
Oh, looks like it's gone. We can probably remove that line, then.

**Comment by emdupre** [comment]
Major :heart_eyes_cat: to that, @jdkent ! I think all we need to do is add the right issue label(s).

**Comment by oesteban** [comment]
Sorry for the educational value of that line, but I forgot of this discussion and removed it in https://github.com/poldracklab/fmriprep/commit/1bf4a21cce62c4330510a9a8ae50db876fbc23b0
