### ISSUE TITLE
Spike detection part of newest version?

### ISSUE THREAD

**Issue by zanderso13** [poldracklab/fmriprep#1471]
Hello!

Someone in my lab came across this link 

https://github.com/poldracklab/fmriprep/issues/699

Which appeared to indicate that spike detection was being applied at the subject level. But when we went through the documentation we didn't see anything indicating this had been implemented. I wanted to check in to see if spike detection is part of the current fmriprep pipeline and if so, is it being applied to raw images or later in the pipeline?

Thanks!

**Comment by effigies** [comment]
Not yet. That's an open issue, so if you're interested in making a contribution, we could help you get going.

**Comment by oesteban** [comment]
Please follow up in the link above.
