### ISSUE TITLE
ImportWarning and no outputs of preprocessing data

### ISSUE THREAD

**Issue by xj2019** [poldracklab/fmriprep#1475]
Dear all,

I am a fresh hand trying to run fmriprep with Singularity  2.6.1-dist. In the parent directory path of subject data, I used command line as bellows:

_singularity run --cleanenv /opt/fmriprep-1.2.5.simg ./subj_data/ ./prep/ participant -w ./work/ --fs-license-file ./license.txt_

However, after bids validation, there are some warnings like:

_/usr/local/miniconda/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
 return f(*args, **kwds)
/usr/local/miniconda/lib/python3.6/site-packages/skimage/__init__.py:80: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/miniconda/lib/python3.6/site-packages/pytest.py' mode='r' encoding='utf-8'>_

At last, an Error was reported in a summary:

_Node Name: fmriprep_wf.single_subject_01_wf.anat_preproc_wf.surface_recon_wf.autorecon1_

 I would appreciate it if someone could let me know what the problem is.

**Comment by xj2019** [comment]
> Those warnings can be ignored. They're Python issues that hopefully will resolve as upstream libraries attend to them, and we upgrade our dependencies.
> 
> Can you provide any more detail from the autorecon1 error, though? There should be a traceback to go with it. Alternately, you can dig through the FreeSurfer directory in your output directory for logs in `sub-01/scripts`.

Thank you for your reply. I read the log file in `sub-01/scripts` and found there is an error as follows:

ERROR! FOV=272.000 > 256
Include the flag -cw256 with recon-all!
Inspect orig.mgz to ensure the head is fully visible.

Maybe it is because we used high resolution T1 data (0.85 mm * 0.85 mm * 0.85 mm).  I searched on the Internet but have no idea about how to resolve this . 

I would appreciate it if you could give me some suggestions.

Thank you for your time :)

**Comment by oesteban** [comment]
We very recently addressed that problem (poldracklab/smriprep#36), however I can't make any promises about when that code will be integrated within fMRIPrep.

For now, the most straightforward solution is to crop your T1w images that have more than 256 voxels along any dimension.

**Comment by effigies** [comment]
Hi @xj2019 would you have any interest in porting that change back over to fMRIPrep? The code bases haven't diverged very far, yet. I'd be happy to walk you through the process, if you need help getting started.

**Comment by oesteban** [comment]
The fix is now released with fMRIPrep.
