### ISSUE TITLE
Malformed nifti header from epi unwarp artifact.

### ISSUE THREAD

**Issue by rwblair** [poldracklab/fmriprep#148]
We should check nifti headers of files we produce to make sure they are in good order.
<img width="476" alt="screen shot 2016-08-30 at 4 42 02 pm" src="https://cloud.githubusercontent.com/assets/14927911/18110999/dee8c992-6ed0-11e6-8d33-15babaafb52c.png">

**Comment by oesteban** [comment]
This is a common problem with several of the FSL outputs. Which file is this?

**Comment by oesteban** [comment]
I guess this is not a problem anymore. Please reopen if we see this again.
