### ISSUE TITLE
filename inside output zipped file differs from name of the zipped file

### ISSUE THREAD

**Issue by Remi-Gau** [poldracklab/fmriprep#1480]
Am working on the NARPS project data that have fMRIprep preprocessed data (V 1.1.6) and it seems that for quite a few output files from fMRIprep: the filename inside the zipped file is different from the zipped file itself. 

For example the file:
`sub-001_task-MGT_run-01_bold_space-MNI152NLin2009cAsym_preproc.nii.gz`
contains the file: 
`vol0000_xform-00000_merged.nii`

And the file:
`sub-001_task-MGT_run-02_bold_space-MNI152NLin2009cAsym_preproc.nii.gz`
contains a file with the same name: 
`vol0000_xform-00000_merged.nii`

Not sure if the issue has been raised before but this might be an "inconvenience" for matlab/SPM users who have to use fMRIprep data. It can of course be fixed on the user side by unzipping and renaming but I am wondering if this is not better fixed on the fMRIprep side.

I don't think there is any requirement about this (matched name for zipped and unzipped files) in the BIDS specs for raw or derivatives but I suspect this could be added as good practice suggestion. Will raise an issue on the BIDS specs repo.

**Comment by effigies** [comment]
I think this did come up before, and for some reason I thought we'd resolved it, but thanks for the heads up.

**Comment by Remi-Gau** [comment]
For reference here is the [issue on the BIDS specs repo](https://github.com/bids-standard/bids-specification/issues/136)

**Comment by oesteban** [comment]
Testing the patch here: https://circleci.com/workflow-run/6835ab5c-689d-4d44-8347-32fd5a2e6b7c

**Comment by oesteban** [comment]
The patch works (tests failed for other reasons, but I checked that running `gunzip -N` now does not recover the old filename)

**Comment by oesteban** [comment]
The fix has been rolled out with https://github.com/poldracklab/niworkflows/releases/tag/0.5.2.post8 and I'll release a patched version of fmriprep soon.
