### ISSUE TITLE
UnboundLocalError: local variable 'ses_uids' referenced before assignment

### ISSUE THREAD

**Issue by pdiazq** [poldracklab/fmriprep#1481]
Hi. Please help me with this. I am using docker and getting the following erros. Thanks

pedro@pedro-HP-Pavilion-Notebook:/usr/src/Python-3.7.0$ fmriprep-docker /home/pedro/Documents/fmriprep/in_data/best_BIDS /home/pedro/Documents/fmriprep/out_data participant 
RUNNING: docker run --rm -it -e DOCKER_VERSION_8395080871=18.09.1 -v /home/pedro/Documents/freesurfer/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /home/pedro/Documents/fmriprep/in_data/best_BIDS:/data:ro -v /home/pedro/Documents/fmriprep/out_data:/out poldracklab/fmriprep:1.2.6 /data /out participant
Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
This dataset appears to be BIDS compatible.
        Summary:                  Available Tasks:        Available Modalities: 
        18 Files, 185.85MB        audiovisual             T1w                   
        1 - Subject                                       meg                   
        1 - Session                                                             

If you have any questions please post on https://neurostars.org/tags/bids

/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/site-packages/nilearn/datasets/neurovault.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Container
/usr/local/miniconda/lib/python3.7/site-packages/skimage/__init__.py:80: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/miniconda/lib/python3.7/site-packages/pytest.py' mode='r' encoding='utf-8'>
  imp.find_module('pytest')
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
190124-16:35:58,837 nipype.workflow IMPORTANT:
	 
    Running fMRIPREP version 1.2.6:
      * BIDS dataset path: /data.
      * Participant list: ['01', 'emptyroom'].
      * Run identifier: 20190124-163558_943fd88c-fd64-41f0-a8c4-47e6bd38713c.
    
/usr/local/miniconda/lib/python3.7/site-packages/networkx/classes/reportviews.py:95: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, Set, Iterable
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/bids_layout.py:121: ResourceWarning: unclosed file <_io.TextIOWrapper name='/data/dataset_description.json' mode='r' encoding='UTF-8'>
  self.description = json.load(open(target, 'r'))
/usr/local/miniconda/lib/python3.7/site-packages/grabbit/core.py:436: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/config/bids.json' mode='r' encoding='UTF-8'>
  domain = json.load(open(domain, 'r'))
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 740, in build_workflow
    ignore_aroma_err=opts.ignore_aroma_denoising_errors,
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 217, in init_fmriprep_wf
    ignore_aroma_err=ignore_aroma_err,
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 383, in init_single_subject_wf
    subject_data, layout = collect_data(bids_dir, subject_id, task_id, echo_idx)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/utils/bids.py", line 181, in collect_data
    subj_data.update({"bold": ses_uids})
UnboundLocalError: local variable 'ses_uids' referenced before assignment
fMRIPrep: Please report errors to https://github.com/poldracklab/fmriprep/issues
pedro@pedro-HP-Pavilion-Notebook:/usr/src/Python-3.7.0$

**Comment by effigies** [comment]
Hi, thanks for the report. A fix was just merged last night, and this should be resolved in the next release.

**Comment by pdiazq** [comment]
thanks @effigies for your quick response. When can we get that new release? thanks again

**Comment by oesteban** [comment]
@pdiazq could you post the tree of the BIDS folder?

**Comment by pdiazq** [comment]
pedro@pedro-HP-Pavilion-Notebook:~/Documents/fmriprep/in_data/best_BIDS$ tree
.
├── acq-epi_T1w.json
├── acq-flipangle05_run-01_MEFLASH.json
├── acq-flipangle30_run-01_MEFLASH.json
├── CHANGES
├── dataset_description.json
├── derivatives
│   ├── audvis.ave
│   ├── ct_sparse_mgh.fif
│   └── sss_cal_mgh.dat
├── sub-01
│   ├── anat
│   │   ├── sub-01_acq-flipangle05_run-01_MEFLASH.nii.gz
│   │   ├── sub-01_acq-flipangle30_run-01_MEFLASH.nii.gz
│   │   └── sub-01_T1w.nii.gz
│   ├── meg
│   │   ├── sub-01_task-audiovisual_meg.json
│   │   ├── sub-01_task-audiovisual_run-01_channels.tsv
│   │   ├── sub-01_task-audiovisual_run-01_events.tsv
│   │   └── sub-01_task-audiovisual_run-01_meg.fif
│   └── sub-01_scans.tsv
└── sub-emptyroom
    └── meg
        └── sub-emptyroom_task-noise_run-01_meg.fif

**Comment by pdiazq** [comment]
Hi @oesteban, this is the tree, Thanks a lot

**Comment by oesteban** [comment]
Are you running with `--anat-only`, because I can't find BOLD runs in your dataset.

A comment about your naming: `acq-epi_T1w.json` will not match any files. Please rename to `T1w.json`.

**Comment by oesteban** [comment]
Hi @pdiazq, we just rolled an experimental version out. Can you test the following command line?:

```
fmriprep-docker -i poldracklab/fmriprep:unstable /home/pedro/Documents/fmriprep/in_data/best_BIDS /home/pedro/Documents/fmriprep/out_data participant
```

**Comment by pdiazq** [comment]
Thanks @oesteban for everything.  I renamed (acq-epi_T1w.json) to (T1w.json) and ran the command you indicated, but seems the same:
Thanks a lot...

pedro@pedro-HP-Pavilion-Notebook:~$ fmriprep-docker -i poldracklab/fmriprep:unstable /home/pedro/Documents/fmriprep/in_data/best_BIDS /home/pedro/Documents/fmriprep/out_data participant
Downloading. This may take a while...
Unable to find image 'poldracklab/fmriprep:unstable' locally
unstable: Pulling from poldracklab/fmriprep
c83208261473: Already exists
6e1a85c1d66a: Already exists
f1320ef45e20: Already exists
5a6ab6e6fbf6: Already exists
6fd240c27767: Already exists
4b9b9707336e: Already exists
3add0dfae14a: Already exists
83e3db7d3f3a: Already exists
d71bac2d9fad: Already exists
5d0ae597aed9: Already exists
98b41d25b055: Already exists
bffb9e4658d2: Already exists
b9e719af6147: Already exists
40344841efd3: Already exists
6c568f65d1a1: Already exists
c9eee2647539: Already exists
02137be2c375: Already exists
c2043c38ab50: Already exists
b082bd58c018: Already exists
e9d4ab5a5ee2: Already exists
38d4f1e41baa: Already exists
b1081868115e: Already exists
fc93e733dff0: Pulling fs layer
dfb7f70103af: Pulling fs layer
fb1d574bee29: Pulling fs layer
3ba3a4f70e95: Pulling fs layer
86f86ebb569e: Pulling fs layer
5f386c83f711: Pulling fs layer
3ba3a4f70e95: Waiting
86f86ebb569e: Waiting
5f386c83f711: Waiting
fc93e733dff0: Download complete
fc93e733dff0: Pull complete
fb1d574bee29: Verifying Checksum
fb1d574bee29: Download complete
86f86ebb569e: Verifying Checksum
86f86ebb569e: Download complete
5f386c83f711: Download complete
dfb7f70103af: Verifying Checksum
dfb7f70103af: Download complete
3ba3a4f70e95: Verifying Checksum
3ba3a4f70e95: Download complete
dfb7f70103af: Pull complete
fb1d574bee29: Pull complete
3ba3a4f70e95: Pull complete
86f86ebb569e: Pull complete
5f386c83f711: Pull complete
Digest: sha256:81c207179397079a510c3e8ba64fe2d41219936ba3b12e26046ed08d69546073
Status: Downloaded newer image for poldracklab/fmriprep:unstable
RUNNING: docker run --rm -it -e DOCKER_VERSION_8395080871=18.09.1 -v /home/pedro/Documents/freesurfer/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /home/pedro/Documents/fmriprep/in_data/best_BIDS:/data:ro -v /home/pedro/Documents/fmriprep/out_data:/out poldracklab/fmriprep:unstable /data /out participant
Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
This dataset appears to be BIDS compatible.
        Summary:                  Available Tasks:        Available Modalities: 
        18 Files, 185.85MB        audiovisual             T1w                   
        1 - Subject                                       meg                   
        1 - Session                                                             

If you have any questions please post on https://neurostars.org/tags/bids

/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/site-packages/nilearn/datasets/neurovault.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Container
/usr/local/miniconda/lib/python3.7/site-packages/skimage/__init__.py:80: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/miniconda/lib/python3.7/site-packages/pytest.py' mode='r' encoding='utf-8'>
  imp.find_module('pytest')
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
190125-19:39:34,903 nipype.workflow IMPORTANT:
	 
    Running fMRIPREP version 1.2.6+14.g9a9e7d72:
      * BIDS dataset path: /data.
      * Participant list: ['01', 'emptyroom'].
      * Run identifier: 20190125-193934_78d40973-41c4-44e7-a227-708482435380.
    
/usr/local/miniconda/lib/python3.7/site-packages/networkx/classes/reportviews.py:95: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, Set, Iterable
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/bids_layout.py:121: ResourceWarning: unclosed file <_io.TextIOWrapper name='/data/dataset_description.json' mode='r' encoding='UTF-8'>
  self.description = json.load(open(target, 'r'))
/usr/local/miniconda/lib/python3.7/site-packages/grabbit/core.py:436: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/config/bids.json' mode='r' encoding='UTF-8'>
  domain = json.load(open(domain, 'r'))
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 749, in build_workflow
    ignore_aroma_err=opts.ignore_aroma_denoising_errors,
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 217, in init_fmriprep_wf
    ignore_aroma_err=ignore_aroma_err,
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 389, in init_single_subject_wf
    subject_id, task_id if task_id else '<all>'))
Exception: No BOLD images found for participant 01 and task <all>. All workflows require BOLD images.
fMRIPrep: Please report errors to https://github.com/poldracklab/fmriprep/issues

**Comment by oesteban** [comment]
Hi @pdiazq it is actually not the same. As I was fearing in the beginning, the workflow now breaks with: `Exception: No BOLD images found for participant 01 and task . All workflows require BOLD images.`.

I think the message is pretty clear. fMRIPrep sought for fMRI within your dataset, but it couldn't find any BOLD run. If you just want to run the anatomical part of the workflow, you can use the ``--anat-only`` flag, and it'll go ahead and process your T1w and T2w images. It should also take FLAIR images into account, but that is currently an open issue we are working on.

I think I can close this issue. Please keep using it if you need further help.

**Comment by pdiazq** [comment]
Thanks for helping me. I would continue looking what would be the problem- Thanks

pedro@pedro-HP-Pavilion-Notebook:~$ fmriprep-docker /home/pedro/Documents/fmriprep/in_data/best_BIDS /home/pedro/Documents/fmriprep/out_data participant --anat-only
RUNNING: docker run --rm -it -e DOCKER_VERSION_8395080871=18.09.1 -v /home/pedro/Documents/freesurfer/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /home/pedro/Documents/fmriprep/in_data/best_BIDS:/data:ro -v /home/pedro/Documents/fmriprep/out_data:/out poldracklab/fmriprep:1.2.6 /data /out participant --anat-only
Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
This dataset appears to be BIDS compatible.
        Summary:                  Available Tasks:        Available Modalities: 
        18 Files, 185.85MB        audiovisual             T1w                   
        1 - Subject                                       meg                   
        1 - Session                                                             

If you have any questions please post on https://neurostars.org/tags/bids

/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/site-packages/nilearn/datasets/neurovault.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Container
/usr/local/miniconda/lib/python3.7/site-packages/skimage/__init__.py:80: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/miniconda/lib/python3.7/site-packages/pytest.py' mode='r' encoding='utf-8'>
  imp.find_module('pytest')
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
190125-21:02:07,965 nipype.workflow IMPORTANT:
	 
    Running fMRIPREP version 1.2.6:
      * BIDS dataset path: /data.
      * Participant list: ['01', 'emptyroom'].
      * Run identifier: 20190125-210207_d3cc32cf-1e6f-4c46-84e7-ed54c67022fe.
    
/usr/local/miniconda/lib/python3.7/site-packages/networkx/classes/reportviews.py:95: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, Set, Iterable
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/bids_layout.py:121: ResourceWarning: unclosed file <_io.TextIOWrapper name='/data/dataset_description.json' mode='r' encoding='UTF-8'>
  self.description = json.load(open(target, 'r'))
/usr/local/miniconda/lib/python3.7/site-packages/grabbit/core.py:436: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/config/bids.json' mode='r' encoding='UTF-8'>
  domain = json.load(open(domain, 'r'))
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 740, in build_workflow
    ignore_aroma_err=opts.ignore_aroma_denoising_errors,
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 217, in init_fmriprep_wf
    ignore_aroma_err=ignore_aroma_err,
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 383, in init_single_subject_wf
    subject_data, layout = collect_data(bids_dir, subject_id, task_id, echo_idx)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/utils/bids.py", line 181, in collect_data
    subj_data.update({"bold": ses_uids})
UnboundLocalError: local variable 'ses_uids' referenced before assignment
fMRIPrep: Please report errors to https://github.com/poldracklab/fmriprep/issues
pedro@pedro-HP-Pavilion-Notebook:~$

**Comment by oesteban** [comment]
In order to use the proposed patch, you'll need to change your command line as stated above (i.e., include the `-i <image>` argument:

```
 fmriprep-docker -i poldracklab/fmriprep:unstable /home/pedro/Documents/fmriprep/in_data/best_BIDS /home/pedro/Documents/fmriprep/out_data participant --anat-only
```

Please let us know if that did it.

**Comment by pdiazq** [comment]
This is the new output:

pedro@pedro-HP-Pavilion-Notebook:~$  fmriprep-docker -i poldracklab/fmriprep:unstable /home/pedro/Documents/fmriprep/in_data/best_BIDS /home/pedro/Documents/fmriprep/out_data participant --anat-only
RUNNING: docker run --rm -it -e DOCKER_VERSION_8395080871=18.09.1 -v /home/pedro/Documents/freesurfer/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /home/pedro/Documents/fmriprep/in_data/best_BIDS:/data:ro -v /home/pedro/Documents/fmriprep/out_data:/out poldracklab/fmriprep:unstable /data /out participant --anat-only
Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
This dataset appears to be BIDS compatible.
        Summary:                  Available Tasks:        Available Modalities: 
        18 Files, 185.85MB        audiovisual             T1w                   
        1 - Subject                                       meg                   
        1 - Session                                                             

If you have any questions please post on https://neurostars.org/tags/bids

/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/site-packages/nilearn/datasets/neurovault.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Container
/usr/local/miniconda/lib/python3.7/site-packages/skimage/__init__.py:80: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/miniconda/lib/python3.7/site-packages/pytest.py' mode='r' encoding='utf-8'>
  imp.find_module('pytest')
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
190125-21:40:17,163 nipype.workflow IMPORTANT:
	 
    Running fMRIPREP version 1.2.6+14.g9a9e7d72:
      * BIDS dataset path: /data.
      * Participant list: ['01', 'emptyroom'].
      * Run identifier: 20190125-214017_25bcc3b1-4849-45b8-82af-7871487ad508.
    
/usr/local/miniconda/lib/python3.7/site-packages/networkx/classes/reportviews.py:95: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, Set, Iterable
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/bids_layout.py:121: ResourceWarning: unclosed file <_io.TextIOWrapper name='/data/dataset_description.json' mode='r' encoding='UTF-8'>
  self.description = json.load(open(target, 'r'))
/usr/local/miniconda/lib/python3.7/site-packages/grabbit/core.py:436: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/config/bids.json' mode='r' encoding='UTF-8'>
  domain = json.load(open(domain, 'r'))
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/bids_layout.py:121: ResourceWarning: unclosed file <_io.TextIOWrapper name='/data/dataset_description.json' mode='r' encoding='UTF-8'>
  self.description = json.load(open(target, 'r'))
/usr/local/miniconda/lib/python3.7/site-packages/grabbit/core.py:436: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/config/bids.json' mode='r' encoding='UTF-8'>
  domain = json.load(open(domain, 'r'))
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 749, in build_workflow
    ignore_aroma_err=opts.ignore_aroma_denoising_errors,
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 217, in init_fmriprep_wf
    ignore_aroma_err=ignore_aroma_err,
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 393, in init_single_subject_wf
    "All workflows require T1w images.".format(subject_id))
Exception: No T1w images found for participant emptyroom. All workflows require T1w images.
fMRIPrep: Please report errors to https://github.com/poldracklab/fmriprep/issues

**Comment by oesteban** [comment]
Okay, this is not an error:

```
Exception: No T1w images found for participant emptyroom. All workflows require T1w images.
```
Basically, there is no workable image under `sub-emptyroom/` within the BIDS structure. A T1w image per subject is necessary for fMRIPrep to run.

You could still run the anatomical workflow on subject 01, with the following command line:
```
 fmriprep-docker -i poldracklab/fmriprep:unstable /home/pedro/Documents/fmriprep/in_data/best_BIDS /home/pedro/Documents/fmriprep/out_data participant --participant-label 01 --anat-only
```

PS. the name "emptyroom" seems a bit suspicious for a subject identifier.

**Comment by emdupre** [comment]
It looks like these are MEG sessions, and the `emptyroom` is the calibration scan. Is that correct ?

If so, fMRIPrep does not handle MEG modality scans, but I'd recommend [MNE Python](https://martinos.org/mne/stable/index.html) !

**Comment by pdiazq** [comment]
Thanks everyone for your big help. Everything is working so far.
