### ISSUE TITLE
Singularity build error downloading

### ISSUE THREAD

**Issue by trh3** [poldracklab/fmriprep#1483]
I have been attempting to build the latest fmriprep (1.2.6) as a Singularity container using Singularity 2.6, and have been running into issues apparently in downloading the various layers:

```
singularity build FMRIPrep-1.2.6.simg docker://poldracklab/fmriprep:1.2.6
Docker image path: index.docker.io/poldracklab/fmriprep:1.2.6
Cache folder set to /pine/scr/t/r/trhenry/.singularity/docker
[1/28] ||----------------------------------|   0.0% ERROR Error downloading https://index.docker.io/v2/poldracklab/fmriprep/blobs/sha256:3add0dfae14aa1c9d695f63dccb63f29640912a45e27ae6b53d496e86dacea11. Do you have permission to write to /pine/scr/t/r/trhenry/.singularity/docker?
ERROR Error downloading https://index.docker.io/v2/poldracklab/fmriprep/blobs/sha256:bffb9e4658d2a307c690468069ca77d0fb7885669f8b930ad524034283afb524. Do you have permission to write to /pine/scr/t/r/trhenry/.singularity/docker?
ERROR Error downloading https://index.docker.io/v2/poldracklab/fmriprep/blobs/sha256:b1081868115e32040e9afeeb1702ab6056f2ac95f7a77232107ea3cc59888afe. Do you have permission to write to /pine/scr/t/r/trhenry/.singularity/docker?
ERROR Error downloading https://index.docker.io/v2/poldracklab/fmriprep/blobs/sha256:c832082614738021cf51d68e84457a45a3f85dbe0ddbb93000c5dc5aae77fe93. Do you have permission to write to /pine/scr/t/r/trhenry/.singularity/docker?
ERROR Error downloading https://index.docker.io/v2/poldracklab/fmriprep/blobs/sha256:4f64328238f2cf9841528bef1b9f8e1537bcb2bf51a0560054784ffb5e596e98. Do you have permission to write to /pine/scr/t/r/trhenry/.singularity/docker?
[2/28] |==|--------------------------------|   7.1% ERROR Error downloading https://index.docker.io/v2/poldracklab/fmriprep/blobs/sha256:83e3db7d3f3af26fd7ab31e87deca6788a1b5fc5ed2d538fd2b4c4000f8ab802. Do you have permission to write to /pine/scr/t/r/trhenry/.singularity/docker?

```

These types of errors occur when I build it on the university cluster (where space is not an issue), or on a local virtual machine ([this virtual machine specifically](https://app.vagrantup.com/sylabs/boxes/singularity-2.6-ubuntu-bionic64)).

They also occur even after deleting the `.singularity` cache directories, disabling singularity caching entirely, and/or setting the cache directories to folders that I definitely have read write permissions, see this [issue ](https://github.com/sylabs/singularity/issues/740) for some related errors.

Finally, I have no issues building other containers from dockerhub, though none have been quite so large as fmriprep. Do you folks have any advice for building the newest version? Thanks!

**Comment by oesteban** [comment]
Hi @trh3, I've been stuck with docker2singularity since pre-2.5 times and it seems to save me quite a bit of trouble. My command line of reference is:

```
docker run --privileged -ti --rm -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/output singularityware/docker2singularity -m "/gpfs /scratch /work /home1 /share /share/PI /local-scratch /oak /opt/freesurfer/license.txt" poldracklab/fmriprep:1.3.0.post1
```

Then I manually upload the image to the cluster.

I have just tried to replicate your problem, but it seems to work for me. I would suggest to post this issue to singularity.
