### ISSUE TITLE
Explain fmriprep-docker wrapper more thoroughly in docs

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#1488]
The motivation and use of fmriprep-docker appears to be underdocumented, as it is not clear that all options to fmriprep are valid fmriprep-docker options, and that it mostly converts paths and environment variables to `-v` mounts.

See discussion in https://neurostars.org/t/fmriprep-docker-call/3363.

Related: #1129

**Comment by oesteban** [comment]
@franklin-feingold do you feel confident to take on this one, after the great work you did with the tutorial? I think this would require some markdown/RST knowledge and the modification of the installation file: https://github.com/poldracklab/fmriprep/blob/master/docs/installation.rst#docker-container

**Comment by franklin-feingold** [comment]
I'll add some documentation to that file (thank you for linking it!) and send over a PR

**Comment by oesteban** [comment]
Closed via #1515
