### ISSUE TITLE
Error using anat-only: local variable 'ses_uids' referenced before assignment

### ISSUE THREAD

**Issue by VriendC** [poldracklab/fmriprep#1495]
Dear fmriprep experts,

when running the fmriprep with the anat-only flag I keep getting the error below while running fmriprep on T1+BOLD data gave me no problems.
I ran the following command on one subject (for now):

fmriprep-docker /path/T1_input /path/T1_output participant --anat-only --fs-license-file=/path/license.txt

any suggestions are highly appreciated!

best wishes, Chris

  Running fMRIPREP version 1.2.6:
      * BIDS dataset path: /data.
      * Participant list: ['735013'].
      * Run identifier: 20190205-160706_0eb472cf-b3a1-434d-b85e-feefeed5b25e.
    
/usr/local/miniconda/lib/python3.7/site-packages/networkx/classes/reportviews.py:95: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, Set, Iterable
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/bids_layout.py:116: UserWarning: 'dataset_description.json' file is missing from project root. You may want to set the root path to a valid BIDS project.
  warnings.warn("'dataset_description.json' file is missing from "
/usr/local/miniconda/lib/python3.7/site-packages/grabbit/core.py:436: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/config/bids.json' mode='r' encoding='UTF-8'>
  domain = json.load(open(domain, 'r'))
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 740, in build_workflow
    ignore_aroma_err=opts.ignore_aroma_denoising_errors,
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 217, in init_fmriprep_wf
    ignore_aroma_err=ignore_aroma_err,
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 383, in init_single_subject_wf
    subject_data, layout = collect_data(bids_dir, subject_id, task_id, echo_idx)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/utils/bids.py", line 181, in collect_data
    subj_data.update({"bold": ses_uids})
UnboundLocalError: local variable 'ses_uids' referenced before assignment

**Comment by effigies** [comment]
Can you try updating to the latest `fmriprep-docker` and re-running?

**Comment by VriendC** [comment]
I'm running fmriprep-docker 1.2.6.post1 (release date Jan 26,2019) which I believe is the most recent update, but no luck.

**Comment by oesteban** [comment]
They should

**Comment by VriendC** [comment]
I’ve checked once again but I’m definitely running version 1.2.6.post1 but with the anat-only flag the script gives this error.

**Comment by effigies** [comment]
And you get this output?

> `Running fMRIPREP version 1.2.6:`

**Comment by effigies** [comment]
I just went ahead and ran `fmriprep-docker` 1.2.6-1, and got:

```
Running fMRIPREP version 1.2.6-1:
```

**Comment by oesteban** [comment]
Hi @VriendC, can you check using the latest release 1.3.0.post2 ?

**Comment by oesteban** [comment]
Important side note: I think both of you are right regarding the version - you may have fmriprep-docker at 1.2.6.post1 and run 1.2.6 if that is the latest tag pulled in your docker cache.

To make sure you run 1.3.0.post2 you don't need to update fmriprep-docker, just make sure you run it including the option `-i poldracklab/fmriprep:1.3.0.post1` right after `fmriprep-docker`.

**Comment by VriendC** [comment]
It took al while but I finally figured it out. Due to some issues with read/write permissions, Docker kept telling me that I was running the latest version of fmriprep but the poldracklab docker file was not actually updated. After correcting this I am able to really update fmriprep to 1.3.0 and run the anat-only without any further issues!

**Comment by oesteban** [comment]
Glad to hear you finally got it going!
