### ISSUE TITLE
Methods section typo

### ISSUE THREAD

**Issue by dcosme** [poldracklab/fmriprep#1509]
Hi there,

Just wanted to alert you to this typo in the version 1.1.4 methods description. Thanks for building this amazing tool! 

<img width="851" alt="fmriprep methods section" src="https://user-images.githubusercontent.com/11858670/52742216-238ed180-2f8c-11e9-9bf8-a92942cf6da8.png">

**Comment by effigies** [comment]
Thanks for the heads up. I updated that in the current master. It will continue to appear in old versions of fMRIPrep.
