### ISSUE TITLE
How to install fmriprep-docker?

### ISSUE THREAD

**Issue by Debby88** [poldracklab/fmriprep#1531]
Dear fmriprep-users,
I have installed a docker and python on my computer however when I run the installation of the docker I get an error that I cannot solve:

debby@debbylp:/usr/local$ pip install fmriprep-docker
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main

Is someone here familiar with this error and can you maybe help me solving the issue?

Best,
Debby

**Comment by effigies** [comment]
There's a possibility that you've got a couple conflicting installations of Python. Try `python -m pip install --upgrade pip`.

**Comment by oesteban** [comment]
Hi @Debby88, did you solve this issue?
