### ISSUE TITLE
nu_correct error

### ISSUE THREAD

**Issue by amlarge** [poldracklab/fmriprep#1532]
I'm running fmriprep in docker, and I see an issue during nu_correct:

> ncopen: filename "./tmp.mri_nu_correct.mni.76747/0/nu1_residue.mnc": No such file or directory
miopen: MINC package entry point
nu_estimate_np_and_em: crashed while running mincmath (termination status=768)
nu_correct: crashed while running nu_estimate_np_and_em (termination status=768)
ERROR: nu_correct

I'm running 

`~/Library/Python/2.7/bin/fmriprep-docker PATH/in PATH/out participant --fs-license-file /Applications/freesurfer/license.txt --output-space T1w template`

But I keep getting that error (log attached). I've seen other places it might have something to do with /tmp. I can set the working directory when I run fmriprep with -w /tmp, but that doesn't seem to help. I also gave Docker access to that directory.

Any help would be appreciated! 

[recon-all.log](https://github.com/poldracklab/fmriprep/files/2946795/recon-all.log)

**Comment by oesteban** [comment]
Hi @amlarge, is this a linux box? Could you attach the full fmriprep output?

(I'd suggest running `fmriprep-docker` with the `-vv` option to increase verbosity).

**Comment by amlarge** [comment]
I'm running from a Mac (either High Sierra or Mojave). I have been running with the -vv option, but it's been taking days to run - is that normal?
[crash-20190308-104007-root-autorecon1-328c2c98-4603-44b1-9405-d03311da3a64.txt](https://github.com/poldracklab/fmriprep/files/2995074/crash-20190308-104007-root-autorecon1-328c2c98-4603-44b1-9405-d03311da3a64.txt)

**Comment by oesteban** [comment]
Hi @amlarge, this seems to me like an internal FreeSurfer error. Can you post this problem in their mailing list and reopen this issue with their feedback? My apologies for the slow response.
