### ISSUE TITLE
Reports (ds005 or ds054)

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#155]
PDF reports must include:
- [x] Skull-strippings (overlay of translucent mask over the designated image)
  - [x] T1
  - [x] SBRef (if available - ds054)
  - [ ] mean EPI
  - [x] fieldmap magnitude image
- [ ] T1 Segmentation plot (see: http://nilearn.github.io/auto_examples/01_plotting/plot_atlas.html#sphx-glr-auto-examples-01-plotting-plot-atlas-py)
- [ ] Image registration outputs:
  - [x] mean EPI-to-SBRef (overlay of SBRef contours over EPI - if SBRef available)
  - [ ] SBRef-to-T1 (overlay of T1 segmentation contours over SBRef, replace SBRef with mean EPI if SBRef is not available)
  - [x] T1-to-MNI (overlay of T1 segmentation contours over MNI template)
- [ ] Unwarping / Fieldmaps
  - [ ] T1 contours over the unwarped mean EPI (if fieldmaps available)
- [ ] Head motion
  - [ ] Frame displacement plot
  - [ ] DVARS plot
  - [ ] "Power" plot (The Plot)
- [ ] Error reporting - stack trace specific for this subject

**Comment by shoshber** [comment]
- [  ] 4D segmentation (label file)

**Comment by chrisfilo** [comment]
I think that should go to output derivatives not reports.

**Comment by oesteban** [comment]
4D segmentation and label file do not get along, they are two different things (?)

**Comment by chrisfilo** [comment]
I'll start splitting remaining items into individual issues.
