### ISSUE TITLE
Incompatible version of smriprep in FMRIPrep 1.3.2?

### ISSUE THREAD

**Issue by bbfrederick** [poldracklab/fmriprep#1557]
Since installing fmriprep 1.3.2 (bare metal install), I get the following error whenever I run an analysis:

Process Process-2:
Traceback (most recent call last):
  File "/home/bdf1/software/anaconda3/envs/fmripreplatest/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/bdf1/software/anaconda3/envs/fmripreplatest/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bdf1/software/anaconda3/envs/fmripreplatest/lib/python3.7/site-packages/fmriprep/cli/run.py", line 775, in build_workflow
    err_on_aroma_warn=opts.error_on_aroma_warnings,
  File "/home/bdf1/software/anaconda3/envs/fmripreplatest/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 218, in init_fmriprep_wf
    err_on_aroma_warn=err_on_aroma_warn,
  File "/home/bdf1/software/anaconda3/envs/fmripreplatest/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 462, in init_single_subject_wf
    template=template,
TypeError: init_anat_preproc_wf() got an unexpected keyword argument 'bids_root'

The line in question is this:
    # Preprocessing of T1w (includes registration to MNI)
    anat_preproc_wf = init_anat_preproc_wf(
        bids_root=layout.root,
        debug=debug,
        freesurfer=freesurfer,
        fs_spaces=output_spaces,
        hires=hires,
        longitudinal=longitudinal,
        name="anat_preproc_wf",
        num_t1w=len(subject_data['t1w']),
        omp_nthreads=omp_nthreads,
        output_dir=output_dir,
        reportlets_dir=reportlets_dir,
        skull_strip_fixed_seed=skull_strip_fixed_seed,
        skull_strip_template=skull_strip_template,
        template=template,
    )

bids_root is the first argument, and is a keyword arg.

init_anat_preproc_wf comes from smriprep:
from smriprep.workflows.anatomical import init_anat_preproc_wf

Where its definition is:
def init_anat_preproc_wf(skull_strip_template, fs_spaces, template, debug,
                         freesurfer, longitudinal, omp_nthreads, hires, reportlets_dir,
                         output_dir, num_t1w,
                         skull_strip_fixed_seed=False, name='anat_preproc_wf'):

Completely different argument order, with many positional arguments.  So it does seem it's not expecting a named argument there....

smriprep was installed automatically by fmriprep as a dependency by pip.  Is there a version skew?

Thanks,
Blaise

**Comment by bbfrederick** [comment]
Ah.  On GitHub, the current version of smriprep.workflows.anatomical has:
def init_anat_preproc_wf(
        bids_root, freesurfer, fs_spaces, hires, longitudinal,
        omp_nthreads, output_dir, num_t1w, reportlets_dir,
        skull_strip_template, template,
        debug=False, name='anat_preproc_wf', skull_strip_fixed_seed=False):
    r"""

That looks compatible.  That's from 7 days ago, the 0.1.0 release (what fMRIPrep pulls) is from 17 days ago.

**Comment by effigies** [comment]
It looks like an oversight that sMRIPrep didn't get released before fMRIPrep. An installation procedure that should always work is (from the repository directory):

```
fmriprep> pip install -r requirements.txt
fmriprep> pip install .
```

**Comment by bbfrederick** [comment]
Good to know!  I'll give that a try.

**Comment by oesteban** [comment]
Same issue here: https://neurostars.org/t/typeerror-init-anat-preproc-wf-got-an-unexpected-keyword-argument-bids-root/3919/2?u=oesteban

@bbfrederick did updating fix the problem for you?

**Comment by effigies** [comment]
I should probably chime in that I did release sMRIPrep, but I forgot to update you, @bbfrederick. Thanks again for the heads up!

**Comment by bbfrederick** [comment]
Yes, @oesteban 's suggestion fixed my problem - thank you!
