### ISSUE TITLE
Support templates other than MNI152NLin2009cAsym

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1558]
Now that TemplateFlow is up and seemingly running okay, it is time to open up the `--template` option and allow additional template keywords.

This is related to poldracklab/smriprep#50 where the CLI interface will be reconsidered and where we will come up with a solution for people who want to run normalization to two or more templates.

**Comment by oesteban** [comment]
cc @satra

**Comment by satra** [comment]
more than other templates, i think i would want to extract individual space data. that being said, custom/other templates would likely be helpful to extend fmriprep to other workflows (e.g., infant mri)

**Comment by oesteban** [comment]
Absolutely. I pinged you because now [`fsLR` can be applied as the target](https://github.com/templateflow/tpl-fsLR/blob/5ce3160db2202b2fbe529fb61af084aa2a16a847/tpl-fsLR_res-01_space-MNI152NLin6Asym_T1w.nii.gz) and generating HCP-compliant CIfTIs will be much easier - at least for the volumetric part.

**Comment by satra** [comment]
this describes the surface mappings. so if the templates are in place, creating the workflows is not that complicated.

https://wiki.humanconnectome.org/download/attachments/63078513/Resampling-FreeSurfer-HCP.pdf?version=1&modificationDate=1472225460934&api=v2&download=true

**Comment by oesteban** [comment]
Necessary surfaces were already there ([L](https://github.com/templateflow/tpl-fsLR/blob/5ce3160db2202b2fbe529fb61af084aa2a16a847/tpl-fsLR_space-fsaverage_hemi-L_den-32k_sphere.surf.gii), [R](https://github.com/templateflow/tpl-fsLR/blob/5ce3160db2202b2fbe529fb61af084aa2a16a847/tpl-fsLR_space-fsaverage_hemi-R_den-32k_sphere.surf.gii)).

Although discouraged (the recommendation is to align the individual's surfaces to fsLR's via MSM), the  files I included into the fsLR template are intented to implement route C of the document.

For the recommended way (or at least more accurate procedures involving surface native spaces), people should use ciftify (wdyt @edickie?).

**Comment by edickie** [comment]
Seems like the best plan for the time being. Sorry I haven't had time to contribute to this lately. I'm pretty swamped till May.

**Comment by edickie** [comment]
Wait aren't you doing route D in the doc?

**Comment by satra** [comment]
if `fsLR` is the target, shouldn't we be going route `B` (`individual` to `fsLR`)?

obviously we will not be able to do single step interpolation, but at least in two steps going from bold to individual surface and then to `fsLR`

**Comment by oesteban** [comment]
I'll be using the `` fs_LR-deformed_to-fsaverage.?.sphere.???k_fs_LR.surf.gii`` files, just for convenience. Then, I'll concatenate all the inverse transforms from BOLD to fsaverage and map all coordinates from fsaverage to BOLD and sample via interpolation. Basically, I'll resample into fsaverage with just 1 step.
