### ISSUE TITLE
Don't rely on google drive for circle builds

### ISSUE THREAD

**Issue by shoshber** [poldracklab/fmriprep#156]
This has become a common failure:

https://circleci.com/gh/shoshber/fmriprep/41

Also, `data/getters.py` has lots of hardcoded google drive things

**Comment by shoshber** [comment]
Uploaded to https://figshare.com/account/home#/projects/16278

I guessed on the license and picked CC-BY. Say something if that's not right.

**Comment by oesteban** [comment]
That link is not public, points to something inside your profile...

**Comment by shoshber** [comment]
Figshare is one of the most confusing sites I've ever used

https://figshare.com/articles/DS005/3978078
https://figshare.com/articles/DS054/3978081

Can you download these?

**Comment by shoshber** [comment]
@oesteban `data/getters.py` has a lot of hardcoded google drive urls. I'm not sure where those urls are pointing or who has access to them. Since you are the author of the file, can you take over? Or give me the information to continue. This problem is blocking all circle builds that don't have these data cached.

**Comment by oesteban** [comment]
Hey @shoshber, I tried to use the links to figshare you had in #157 but one of them did not work. Since there were more data that needed to be uploaded, I have opened a [new OSF project for that](https://osf.io/fvuh8/).
