### ISSUE TITLE
incorrect circleci print statement

### ISSUE THREAD

**Issue by jdkent** [poldracklab/fmriprep#1563]
For the doc build process, if one specifies to skip the docs building process, the readout will say "Skipping pytest job" while it should say something like "Skipping doc building job" in [this line](https://github.com/poldracklab/fmriprep/blob/cb52c0d06530b812cc8b7ee7bbffa4b98c453e07/.circleci/config.yml#L308). 

This would be a great first time contributor/first time github user issue to tackle.

**Comment by ariveradompenciel** [comment]
I would like to take on this issue!

**Comment by effigies** [comment]
@ariveradompenciel Great! Let us know if you need any guidance here.
