### ISSUE TITLE
Suggestions for CONTRIBUTING.md

### ISSUE THREAD

**Issue by ariveradompenciel** [poldracklab/fmriprep#1565]
Just contributed for the first time. The CONTRIBUTING guide was very helpful, thanks! I have a few suggestions for the following steps:

- Step 3: add `git commit` and `git add` commands

- Step 4: 
  - include examples of what falls under each descriptive prefix
  - change link for https://help.github.com/en/articles/creating-a-pull-request to https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by jdkent** [comment]
oops, I already hopped on that, sorry @emdupre !
