### ISSUE TITLE
Revise command line interface of spaces/references/outputs

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1588]
### Currently supported

- [x] Allow the user to change the atlas used in brain extraction (as long as the selected atlas has a binary brain mask, although it would be better to use only templates that have a probabilistic brain mask and Registration/Extraction masks).
- [x] Allow the user to change the Spatial Normalization target with the `--template` argument (although some paths may not be fully implemented, e.g. with `--cifti-outputs` or `--ica-aroma`).
- [x] Allow the user to write preprocessed data, resampled to several alternative spaces (namely `T1w`, `template`, and `fsXXXX`) with the `--output-space` argument.
- [x] Allow the user to specify an output resolution with `--template-resampling-grid`.

### Problems

- The use of templates other than `MNI152NLin2009cAsym` is quite unstable. 
- Inconsistency of methods relying on other templates (ICA-AROMA and CIFTI generation)
- Only support freesurfer's surface spaces, and the extension to other surface spaces is difficult for the poor integration with TemplateFlow of the surface world.
- Spatial normalization restricted to only one template (although for long we've allowed supplying several arguments to `--template` it didn't actually turn out in a different workflow).
- Lack of flexibility to satisfy requests for new outputs resampled in new spaces (e.g. native bold).

### Proposal

- *Templates*: Deprecate `--template`, rename it to `--std-spaces`, allow it to accept a list of template identifiers from TemplateFlow (which can be either surface, volume or both). Volumetric registration will then run for all the volumetric templates in the list. The first template defines the "default" standard space for preprocessing. If `--ica-aroma` is set, and the keyword `MNI152NLin6Asym` is not in the list, an internal nonlinear registration will be added. Same for `--cifti-outputs` with `fsLR`. An special keyword `custom` (or maybe `user-provided`, please mention what you like better) can be used to provide a path with a custom template. In that case, `--custom-template-path` should be provided and pointing to a TemplateFlow-like organized template, and having at least two resolutions (high and low) with indexes res-1 and res-2.
- *Nonstandard spatial references*: a `--nonstd-spaces` flag that allows values like `anat`, `run`, and `sbref` (will need to think this through). We could add `T1w` for backwards compatibility, but that is the same meaning as `anat`. Key `run` indicates the individual, native space of this particular BOLD run, `sbref` is the space of the SBRef used as reference (which may or may not be in the same resolution or even session). That would open the door to, for instance, have other keywords such as `individual` or `participant` that would calculate a reference for all tasks and runs of a participant and similarly, `session`.
- *Resolution/density*: `--template-sampling-grid` is deprecated, and the `--standard-spaces` accepts comma separated values indicating resolutions and or densities for resampling. Special key `orig` is the default, and would generate data with the same resolution as the original volume (in other words, the current default of fMRIPrep). For instance `MNI152NLin2009cAsym,res-2` or `fsLR,den-92k`, `MNI152NLin2009cAsym,orig`. I'd be happy to change the default resolution to `res-2`. Additionally, one can set the special key `dismiss` if the user does not want the data to be resampled into the template space (e.g. `MNI152NLin2009cAsym,dismiss` will prevent the generation of `space-MNI152NLin2009cAsym` derivatives).

### Example

Old:
```
fmriprep ... --output-space T1w template fsnative fsaverage5 --template-resampling-grid 2mm
```
New:
```
fmriprep --std-spaces MNI152NLin2009cAsym,res-2 fsaverage,den-10k --nonstd-spaces anat,orig fsnative
```

WDYT?

Paging @edickie @satra for opinions (as this may interact with the discussions about volspace/reference/etc in BIDS Derivatives).

**Comment by oesteban** [comment]
This proposal enables #1558 to be implemented.

**Comment by oesteban** [comment]
BTW, this would enable other interesting possibilities such as enforcing other details of the template:

```
fmriprep --std-spaces MNIBabyAsym,res-2,cohort-20mo --nonstd-spaces anat
```
would select the template of 20 months old (we are thinking of using the entity `cohort` to specify age of developmental templates, and also allow for other groupings such as control/patients).

**Comment by effigies** [comment]
I find this hard to evaluate. It's certainly flexible, but it feels like it's so flexible that what we're going to end up with is people describing their use cases on Neurostars, which we then translate into the arguments they need. But not fully understanding the range of use cases you're actually trying to accommodate, I don't know that I can suggest anything better.

So just a couple specific thoughts:

> An special keyword `custom` (or maybe `user-provided`, please mention what you like better) can be used to provide a path with a custom template. In that case, --custom-template-path should be provided and pointing to a TemplateFlow-like organized template, and having at least two resolutions (high and low) with indexes res-1 and res-2.

Why not just allow a path instead of `custom` + `--custom-template-path`? Special names that can be overridden with hard paths is a pretty common CLI idiom.

> *Nonstandard spatial references*

Is there no way to specify these with the same option as the templates? There shouldn't be name collisions.

> `--standard-spaces` accepts comma separated values indicating resolutions and or densities for resampling.

Thjs feels surprising from a CLI perspective, as commas often separate different values, rather than connect related values. Perhaps a colon (`:`)?

> `fsaverage,den-10k`

I guess this is `fsaverage5`. I would strongly recommend letting pre-existing names serve as synonyms, if you're going to impose these new conventions.

> Additionally, one can set the special key dismiss if the user does not want the data to be resampled into the template space (e.g. MNI152NLin2009cAsym,dismiss will prevent the generation of space-MNI152NLin2009cAsym derivatives).

Is this to avoid creating volumetric derivatives when what you want is the CIFTI? I'm not really following.

---

Synthesizing the above, I'd replace your suggestion of

```
fmriprep --std-spaces MNI152NLin2009cAsym,res-2 fsaverage,den-10k --nonstd-spaces anat,orig fsnative
```

with

```
fmriprep --output-space MNI152NLin2009cAsym:2mm fsaverage5 anat fsnative
```

The logic should be pretty simple. The "nonstandard" spaces of `anat` and `fsnative` can be quickly matched and removed from the list, and `fsaverage5` translated into `fsaverage:10k`. Then `fsaverage` and `MNI152NLin2009cAsym` can be found in the TemplateFlow set of known templates, so there are no unknown spaces where we need to try to interpret as a path.

The goal here is to maintain as much backwards compatibility as possible while still getting you the flexibility you need.

**Comment by oesteban** [comment]
> Why not just allow a path instead of `custom` + `--custom-template-path`? Special names that can be overridden with hard paths is a pretty common CLI idiom.

I'm totally fine with this solution (I actually think it is better since now you can easily have two custom templates).

> Is there no way to specify these with the same option as the templates? There shouldn't be name collisions.

No, there's no need to split the options. The reason why I think it is a good idea to have them separate is that it enforces some explicitness in terms of spaces. That said, I think your last example is pretty nice.


> Thjs feels surprising from a CLI perspective, as commas often separate different values, rather than connect related values. Perhaps a colon (`:`)?

:+1: 

> I guess this is `fsaverage5`. I would strongly recommend letting pre-existing names serve as synonyms, if you're going to impose these new conventions.

Yes, it is. And yes, I would keep the compatibility with pre-existing names via synonyms.


> Is this to avoid creating volumetric derivatives when what you want is the CIFTI? I'm not really following.

Yes, that would be the use case. Some users are hitting quota problems and might want to get the transforms calculated (and written out as X5) but they are not interested in generating new resamplings. Although I agree this could be very unintuitive and it could be left apart as a future possibility.



> The logic should be pretty simple. The "nonstandard" spaces of `anat` and `fsnative` can be quickly matched and removed from the list, and `fsaverage5` translated into `fsaverage:10k`. Then `fsaverage` and `MNI152NLin2009cAsym` can be found in the TemplateFlow set of known templates, so there are no unknown spaces where we need to try to interpret as a path.

The nonstandard spaces should not accept some modifiers such as pre-defined resolutions (other than the reference's resolution and the original bold's reference). That could be a justification for `--nstd-spaces`

Finally, although the `2mm` key for resolution seems beautiful (or at least nicer than `res-2`), allowing such keyword seeds the confusion (what if a template does not have a 2mm resolution?) and forces us to query the metadata dictionary in search for a 2mm resolution. This can blow up when we start including rodent templates. Forcing a nomenclature somewhat established for TemplateFlow seems easier and less error-prone. It also makes the ordering of modifiers interchangeable:

```
fmriprep --output-space MNIPediatricAsym:cohort-20mo:res-2
```
or
```
fmriprep --output-space MNIPediatricAsym:res-2:cohort-20mo
```
could work out equivalently.

**Comment by effigies** [comment]
Okay, I'm fine with `res-2` instead of `2mm`. So if `T1w` is equivalent to `anat`, and the default `res` option doesn't change, then existing `--output-space` options should remain usable, and I'm happy with this plan.

**Comment by oesteban** [comment]
What about std vs nstd prefix in the argument? Not convinced yet?

**Comment by effigies** [comment]
Not sold on it. I think these are distinctions for us to draw to produce correct outputs and set the branching logic needed to produce valid metadata, but what users are going to care about is "How do I say I want to use this template or keep things in some kind of subject-native space?"

For the parameters, we can match up to the first colon and easily identify known templates, dataset-specific references (nstd-spaces, as you call them), and arguments we should check whether it's a path to a valid template directory.

As to teaching users about where optional parameters can apply, I think we can do that in the docs and/or help text. This is mostly going to be a question for templates, anyway. We could write something like:

```
Output spaces may be templates with optional parameters or dataset-specific references.
Templates take the form <TEMPLATE>[:res-<resolution>][:cohort-<label>][...], with optional,
colon-separated parameters, while dataset-specific references imply a specific orientation
and sampling grid.

[Some language listing the available templates and dataset-specific references that we
know how to target.]
```

**Comment by a3sha2** [comment]
Can you include  warp and affine for transformation between t1w and native space so that users can decide to covert preprocessed bold to native space

**Comment by oesteban** [comment]
@a3sha2, we currently write out all transformations when calculated. In the future, when the X5 transform format is ready (is being developed under the umbrella of BIDS), all the transforms calculated by fMRIPrep will be encapsulated in one single file.

**Comment by oesteban** [comment]
Related #1376

**Comment by edickie** [comment]
I think I get it.. but how are you dealing with the subcortical atlas/parcellation in cifti files? or is that another issue?

**Comment by oesteban** [comment]
If you say ``--output-spaces fsLR:den-91k`` you are explicitly saying the volumetric atlas & parcellation that should be used.

**Comment by oesteban** [comment]
I'm becoming more and more convinced that at this point, the only grayordinates structure that makes sense is the official one.

I agree that in the future some people may want to have other possibilities. That could be encoded on TemplateFlow or with specific modifiers like `--output-spaces fsLR:res-2:nifti` which would output only volumetric derivatives on the Conte space used by fsLR. Similarly: `--output-spaces fsLR:den-10k:gifti` would produce only timeseries for surfaces.

(disclaimer: neither the `nifti` nor the `gifti` modifiers are being proposed at this point - I honestly doubt we need them, I used them just to show that the semantics can be implemented).
