### ISSUE TITLE
OSError: Expected 17060042 bytes, got 8538377 bytes from object

### ISSUE THREAD

**Issue by shaohanyu2017** [poldracklab/fmriprep#1591]
Dear experts,
    I am trying to run fmriprep with the following command: fmriprep ~/Desktop/AgentData ~/Desktop/csv participant -t localizer --run-uuid 01 --no-freesurfer -w ~/Desktop/work --low-mem

I consistently got errors from  three nodes.The errors are the same.OSError: Expected 17060042 bytes, got 8538377 bytes from object. It would be a great help if I could get some information about why does this error comes and how to fix it. With many thanks!

Node Name:fmriprep_wf.single_subject_01_wf.func_preproc_task_localizer_run_02_wf.bold_mni_trans_wf.gen_ref
Node Name: fmriprep_wf.single_subject_01_wf.anat_preproc_wf.t1_2_mni
Node Name: fmriprep_wf.single_subject_01_wf.func_preproc_task_localizer_run_01_wf.bold_mni_trans_wf.gen_ref

**Comment by oesteban** [comment]
Hi @shaohanyu2017,

First I'd say you want to replace `--run-uuid 01` with `--participant-label 01`. That said, it seems to me that it is possible that some of your images have integrity problems.

You may want to run mriqc on this dataset to see whether you get similar errors.

**Comment by shaohanyu2017** [comment]
Thank you! The issue was resolved when running fmriprep on a computer with 32G memory
