### ISSUE TITLE
fmriprep manufacturer/model info use

### ISSUE THREAD

**Issue by sandhitsu** [poldracklab/fmriprep#1592]
Does fmriprep require or actually tried to use the Manufacturer and ManufacturersModelName variables in the .json file in any way ?

**Comment by oesteban** [comment]
It doesn't require them. But they are highly recommendable.

**Comment by sandhitsu** [comment]
Do I take it to mean it does look for it and tries to use this information in an intelligent manner ?

**Comment by oesteban** [comment]
Sorry for the confusion. Not at all, fMRIPrep does not use such information.

**Comment by sandhitsu** [comment]
Sorry I assumed that is the reason for your recommendation. I asked because we were going to "anonymize" those variables, sounds like that won't affect the processing.

**Comment by oesteban** [comment]
It won't
