### ISSUE TITLE
shared libraries error in v1.3.2

### ISSUE THREAD

**Issue by manishsaggar1** [poldracklab/fmriprep#1593]
Hi all,

I am getting the shared libraries error when I run fmriprep (v1.3.2) on the cluster (Sherlock). Not sure how to fix it. Please help.

I built the singularity image using:

`
singularity build /my_images/fmriprep-v1.3.2.simg docker://poldracklab/fmriprep:latest
`

Interestingly, the same image ran perfectly last week on another dataset. However, it keeps crashing with the following error with the current dataset.

`
Standard error:
fslmaths: error while loading shared libraries: libnewimage.so: cannot open shared object file: No such file or directory
Return code: 127
`

**Comment by ds7711** [comment]
One simple thing to check is whether you have the "/my_images/" directory/folder. "/my_images/fmriprep-v1.3.2.simg" should be where you want to store your image and differ between computers/users.

**Comment by manishsaggar1** [comment]
Thanks, yes I do. "/my_images" is only a placeholder in the command I pasted above.

**Comment by ds7711** [comment]
Sorry, I misread what your issue is. What command do you use to run fMRIprep? I encountered similar problems and the cause is that I was not using `srun` before the singularity command. 
Did you try something like
 `srun singularity run --cleanenv /my_images/fmriprep-1.3.2.simg \
    path/to/data/dir path/to/output/dir \
    participant \
    --participant-label lab
    -w path/to/temprory_working_dir`

**Comment by manishsaggar1** [comment]
Thanks. Not sure about srun. But using --cleanenv flag helped.

**Comment by oesteban** [comment]
Yes, this is likely some `LD_*` environment variable leaking into the container.
