### ISSUE TITLE
BUG: Missing `cosineXX` columns for some subjects (ds003)

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1594]
Investigate (and fix if pertinent) the reasons why not all subjects have the same number of cosine regressors.

cc @rciric

**Comment by oesteban** [comment]
Hi @satra, you may have an idea about why this is happening. We are using this code from nipype: https://github.com/nipy/nipype/blob/master/nipype/algorithms/confounds.py#L1383

Any ideas?

**Comment by satra** [comment]
the only thing i can think of is if this returns 1:

https://github.com/nipy/nipype/blob/master/nipype/algorithms/confounds.py#L1408

can you check the inputs to the function for some of those folks?

**Comment by oesteban** [comment]
@rciric can you remind me the conclusions about this?

**Comment by oesteban** [comment]
Okay, only now I realize this is not a bug: https://github.com/poldracklab/fmriprep/issues/1899#issuecomment-561687460

@rciric could you double-check that the irregular subjects have different TR, number of time points or number of nonsteady states?

In any case, let's follow up on #1899.
