### ISSUE TITLE
Running fMRIPREP version 0+unknown

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1619]
Versioneer has stopped working with the revision of the packaging.

**Comment by effigies** [comment]
Gah. Sorry. I'll look at this. I just noticed this with the last version of FitLins as well...

**Comment by oesteban** [comment]
It seems that the cmdclass replaces the `fmriprep/_version.py` file. Since `.git` is in the `.dockerignore`, that file is generated with an incorrect version.

Because of the rewrite, the `VERSION` file is not looked at either.

**Comment by effigies** [comment]
Hmm. I'm confused. How are you reproducing this? I specifically test that the version is correct in brand new environments in `test_deploy_pypi` (e.g. https://circleci.com/gh/poldracklab/fmriprep/8537).

**Comment by effigies** [comment]
Oh, I see. It's in the Docker container... interesting.

**Comment by oesteban** [comment]
Yep, I guess the Pypi packaging is correct.

**Comment by oesteban** [comment]
FYI: https://github.com/warner/python-versioneer/issues/189

**Comment by effigies** [comment]
It looks abandoned at this point. We can edit it ourselves, or just work with it as is.
