### ISSUE TITLE
New packaging workflow does not allow posting to Pypi link dependencies

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1624]
I think we are hitting this - https://github.com/pypa/pip/issues/6301 (see https://circleci.com/gh/poldracklab/fmriprep/8634)

**Comment by effigies** [comment]
I'm not a fan of publishing with those, anyway. Let's just release nipype. I can get a rel/ branch tonight and release in the morning.

**Comment by effigies** [comment]
Fixed in 1a4b64f8853d339c844850198b0f98acb3bbfc13.
