### ISSUE TITLE
Resampling funcs to standard spaces fails in 1.4.0a0 

### ISSUE THREAD

**Issue by markushs** [poldracklab/fmriprep#1626]
Hi, 
You might be aware of this, but resampling of funcs to standard spaces produces strange results in  in 1.4.0.a0. Here's an example (`anat/sub-XX_space-MNI152Nlin2009cAsym_desc-preproc_T1w` in red, overlaid on one `func/*_space-MNI152NLin2009cAsym_boldref`) 

<img width="300" alt="image" src="https://user-images.githubusercontent.com/44242647/57443298-0184b280-724e-11e9-91b7-71d79aa8cc8a.png">

Here's just the `func/*_space-MNI152NLin2009cAsym_boldref`

<img width="300" alt="image" src="https://user-images.githubusercontent.com/44242647/57443523-8b348000-724e-11e9-9744-f81d71121fdf.png">

I see this error in all subjects I've run through 1.4.0.a0 (to get around #1615 after implementing #1603), and for both MNI152NLin2009cAsym and MNI152NLin6Asym. Same data has been processed in previous versions of fmriprep without these issues.

I know that 1.4.0.a0 is a pre-release, so sorry if this an already known issue planned to be fixed for the "official" release.

**Comment by markushs** [comment]
Hi again,
I did some debugging, and it looks like `antsApplyTransforms` in `/bold_std_trans_wf/_key_*/bold_to_std_transform` gets t1_to_mniComposite-inputs (`--transform`) from both standard spaces.

Here's a screenshot from `/bold_std_trans_wf/_key_MNI152NLin6Asym/bold_to_std_transform/command.txt` (note the MNI152NLin2009cAsym-registration in addition to MNI152NLin6Asym)

<img width="1882" alt="image" src="https://user-images.githubusercontent.com/44242647/57454105-5e8d6200-7268-11e9-8e23-209042be7392.png">

Running `antsApplyTransforms` with the correct registration only seems to fix the problems I'm seeing.

Note that my original call to fmriprep didn't ask for MNI152NLin6Asym under `output-spaces` (I used `--output-spaces T1w MNI152NLin2009cAsym` to reproduce fmriprep-behavior from earlier versions). However, due to ICA-AROMA being run NLin6 was automatically added.

**Comment by effigies** [comment]
@markushs Thanks so much for tracking this down! We're lucky to have you trying out the pre-release.

**Comment by oesteban** [comment]
Okay, I can see this happening also on my settings. The `KeySelect` interface seems to work alright:

```
Node: single_subject_01_wf (func_preproc_task_mixedgamblestask_run_01_wf (bold_std_trans_wf (select_std (utility)
=================================================================================================================


 Hierarchy : fmriprep_wf.single_subject_01_wf.func_preproc_task_mixedgamblestask_run_01_wf.bold_std_trans_wf.select_std
 Exec ID : select_std.aI.a1


Original Inputs
---------------


* anat2std_xfm : ['/home/oesteban/tmp/fmriprep-ds005/work/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin2009cAsym/registration/ants_t1_to_mniComp
osite.h5', '/home/oesteban/tmp/fmriprep-ds005/work/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin6Asym/registration/ants_t1_to_mniComposite.h5']
* key : MNI152NLin6Asym
* keys : ['MNI152NLin2009cAsym', 'MNI152NLin6Asym']
* resolution : ['native', 2]

Execution Inputs
----------------


* anat2std_xfm : ['/home/oesteban/tmp/fmriprep-ds005/work/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin2009cAsym/registration/ants_t1_to_mniComp
osite.h5', '/home/oesteban/tmp/fmriprep-ds005/work/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin6Asym/registration/ants_t1_to_mniComposite.h5']
* key : MNI152NLin6Asym
* keys : ['MNI152NLin2009cAsym', 'MNI152NLin6Asym']
* resolution : ['native', 2]


Execution Outputs
-----------------


* anat2std_xfm : /home/oesteban/tmp/fmriprep-ds005/work/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin6Asym/registration/ants_t1_to_mniComposite.
h5
* key : MNI152NLin6Asym
* resolution : 2
```

So I guess I missed some connection to the ApplyTransforms node.

**Comment by oesteban** [comment]
@markushs you are the goalkeeper of this release. Thank you so much.

**Comment by oesteban** [comment]
@markushs pre-release 1.4.0a1 should post within the next couple of hours. Can I ask you to give it a try and confirm this problem has been addressed?

**Comment by markushs** [comment]
Hi @oesteban

**Comment by markushs** [comment]
@oesteban Yes, everything seems to work much better now! One observation though: the funcs in both MNI-spaces come out identical even though different`--transform` inputs are used. While NLin2009 and NLin6 are similar, they are not identical so I was a bit puzzled by this.

**Comment by oesteban** [comment]
Are they identical bitwise or visually?

**Comment by oesteban** [comment]
They should have different resolutions, for instance.

**Comment by markushs** [comment]
So, the preprocessed funcs are both in native resolution (3.027 x 3.027 x 3 mm in both MNI spaces). The preprocessed BOLD time series are identical voxel-by-voxel to the 6th digit at least.

**Comment by markushs** [comment]
<img width="687" alt="image" src="https://user-images.githubusercontent.com/44242647/57559131-bb7c3b80-7380-11e9-86bd-bfe500247f46.png">

**Comment by markushs** [comment]
Sorry for not being of more help here, but I can at least confirm that the inputs to `bold_std_trans_wf/outputnode` are different across MNI output spaces. But they end up identical in `derivatives/fmriprep/sub-XX/ses-XX/func` (as you can see from the fslinfo output)

**Comment by oesteban** [comment]
Thanks for the heads up, again :)
