### ISSUE TITLE
config.yml build step is not installing parallel and gzip

### ISSUE THREAD

**Issue by jdkent** [poldracklab/fmriprep#1628]
A minor inconsistency between the command and the name of the command in [config.yml](https://github.com/poldracklab/fmriprep/blob/1a4b64f8853d339c844850198b0f98acb3bbfc13/.circleci/config.yml#L13)

instead of 
```
name: Install parallel gzip and python3
```
the line should read
```
name: Install pigz and python3
```

Another great issue if someone is looking to open their first pull request.

**Comment by effigies** [comment]
[pigz](https://zlib.net/pigz/) == parallel gzip

**Comment by jdkent** [comment]
gotcha, Thanks! I thought those were three separate packages that got modified to be two somewhere down the line. Sorry for the noise.
