### ISSUE TITLE
Potential pitfall: aparc/aseg outputs in standard space

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1631]
The following section of fMRIPrep is arguably incorrect:

https://github.com/poldracklab/fmriprep/blob/a8ef9a3b1722dd667e6ca0fc0e06a1fd23219eb1/fmriprep/workflows/bold/resampling.py#L356-L388

The reason is that anatomical derivatives are being processed as though they were functional. I guess the rationale is that, when we write outputs on standard space with native grid, we retrieve the resolution information from the functional images.

IMHO, aparc/aseg might be useful to have in standard space, with native resolution if you will, but they should be written out to the anat/ folder, and the native resolution should be the T1w.

I believe these were generated for the CIFTI subworkflow. Since we will be revising that very soon, I'd propose to make this move now.

One additional detail to add is that these images are not correctly aligned at least with 1.4.0a1 (might be another one error from the refactor, or just wrong since the beginning).

WDTY @effigies ?

**Comment by oesteban** [comment]
Any opinions on this, @effigies ?

**Comment by effigies** [comment]
Ah, thanks for the ping...

They are anatomical derivatives, but they are in the BOLD space specifically to make it trivial to select voxels in the BOLD series. I don't see that there's much advantage to moving them to the T1w grid.

**Comment by oesteban** [comment]
What if we just stop writing them?

**Comment by effigies** [comment]
We got #1401 specifically because users needed them in MNI space. IDK. What's the motivation for removing them? Just conceptual clarity?

**Comment by oesteban** [comment]
Okay, given #1401, I've gone through the debugging and fixing of the error.

However, I still don't see an acceptable use for these derivates other than testing whether transforms were correctly chained and applied or not. Using these files to extract time series in standard space should be a strongly discouraged use of these derivatives.
