### ISSUE TITLE
error downloading template 

### ISSUE THREAD

**Issue by a3sha2** [poldracklab/fmriprep#1635]
the following error occur: 

Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin6Sym/tpl-MNI152NLin6Sym_res-01_T1w.nii.gz
  0%|                                                                                                                                                                | 0.00/9.84k [00:00<?, ?B/s]
190514-20:19:00,574 nipype.workflow WARNING:
	 [Node] Error on "fmriprep_wf.single_subject_080557_wf.anat_preproc_wf.anat_norm_wf.fixed_tpl" (/cbica/home/adebimpa/cbica/projects/GURLAB/projects/distortionccorr/fmriper1.4/wkdir/fmriprep_wf/single_subject_080557_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin6Sym/fixed_tpl)
190514-20:19:00,583 nipype.workflow ERROR:
	 Node fixed_tpl.a3 failed to run on host cubic-login2.
190514-20:19:00,588 nipype.workflow ERROR:
	 Saving crash info to /cbica/home/adebimpa/cbica/projects/GURLAB/projects/distortionccorr/fmriper1.4/fmriprep/sub-080557/log/20190514-201817_331ebd4f-00bc-4c9c-a942-91777d9ac16a/crash-20190514-201900-adebimpa-fixed_tpl.a3-b44b230f-f345-4ac4-8aeb-111119dead1c.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/templateflow/api.py", line 144, in _s3_get
    f.write(data)
OSError: [Errno 28] No space left on device

**Comment by effigies** [comment]
It looks like you're running from a custom installation, so the atlases were not pre-cached, and the default cache is in your home directory.

We do the following in the Dockerfile:

https://github.com/poldracklab/fmriprep/blob/b2ac1ac23b8f0ee0dc37b2125e5a18892447f255/Dockerfile#L164-L172

You will probably want to set the `TEMPLATEFLOW_HOME` variable to somewhere with enough space, and may wish to pre-cache as well.

**Comment by a3sha2** [comment]
Thanks @effigies 
I am using the singularity image

**Comment by a3sha2** [comment]
done!

**Comment by NikkiBytes** [comment]
@a3sha2 could you post your singularity correction? I am running into the same error with my image. Thank you!

**Comment by oesteban** [comment]
@NikkiBytes what error are you seeing?

**Comment by NikkiBytes** [comment]
@oesteban Hey Oscar! I am seeing the exact same error he listed above, it's attempting to download the atlas but then runs out of disk space! I too am using a singularity image. Looking at his solution I understand, I am just learning how I'd add this to the singularity build? Thanks!

**Comment by oesteban** [comment]
And are you positive you actually have disk space for new data?

**Comment by NikkiBytes** [comment]
Version: I recently upgraded to the latest version of fmriprep,  fmriprep v1.4.1rc1
Note: fmriprep has run successfully before, am now wanting to use the new command `--output-spaces MNI152Lin ` 

Command: 

`fmriprep /home_dir/Experiments/BreakfastClub/BIDS /home_dir/Experiments/BreakfastClub/fmriprep2 participant --participant-label sub-001 --skip_bids_validation --fs-license-file /home_dir/freesurfer/license.txt --longitudinal --fs-no-reconall --omp-nthreads 16 --n_cpus 16 --bold2t1w-dof 12 --output-spaces MNI152Lin -w /home_dir/Experiments/BreakfastClub/fmriprep2`


Here is the error: 

`Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152Lin/tpl-MNI152Lin_res-01_T1w.nii.gz
  8%|███▊                                            | 835/10.4k [00:00<00:02, 3.86kB/s]
190521-17:58:06,69 nipype.workflow WARNING:
	 [Node] Error on "fmriprep_wf.single_subject_001_wf.anat_preproc_wf.anat_norm_wf.fixed_tpl" (/home_dir/Experiments/BreakfastClub/fmriprep2/fmriprep_wf/single_subject_001_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152Lin/fixed_tpl)
190521-17:58:06,78 nipype.workflow ERROR:
	 Node fixed_tpl.a0 failed to run on host croatan-2-5.cluster.
190521-17:58:06,88 nipype.workflow ERROR:
	 Saving crash info to /home_dir/Experiments/BreakfastClub/fmriprep2/fmriprep/sub-001/log/20190521-175740_3e8c3dae-3aee-43a1-b285-41f90e7dad54/crash-20190521-175806-nbytes-fixed_tpl.a0-30630d8b-7710-49b2-b1a0-665d9106ceba.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/templateflow/api.py", line 144, in _s3_get
    f.write(data)
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 316, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 472, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 563, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 643, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 375, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/utility/wrappers.py", line 144, in _run_interface
    out = function_handle(**args)
  File "<string>", line 5, in _templateflow_ds
  File "/usr/local/miniconda/lib/python3.7/site-packages/templateflow/api.py", line 39, in get
    _s3_get(filepath)
  File "/usr/local/miniconda/lib/python3.7/site-packages/templateflow/api.py", line 144, in _s3_get
    f.write(data)
OSError: [Errno 28] No space left on device`

**Comment by a3sha2** [comment]
@NikkiBytes  I bind the template flow directory like ` .. -B  /mytemplateflowdir:/opt/templateflow` after declaration `TEMPLATEFLOW_HOME="/opt/templateflow" `

**Comment by oesteban** [comment]
I'd say that is the best answer :)

**Comment by NikkiBytes** [comment]
@a3sha2 @effigies ahhh yes that looks like what I am looking for! Thank you guys for your help!
