### ISSUE TITLE
grand mean intensity normalization / global rescaling

### ISSUE THREAD

**Issue by ilyaveer** [poldracklab/fmriprep#1642]
Hi fmriprep developers,

In the docs I couldn't find any reference to grand mean intensity normalization being applied to the BOLD data, which is a necessary step to calculate valid group statistics later on. Perhaps this is something that could be added, or is this already being done under the hood in the current version?

Cheers,
Ilya

**Comment by oesteban** [comment]
Duplicate of #1210. Please follow up there.

Thanks for requesting!
