### ISSUE TITLE
PhaseEncodingDirection caused error

### ISSUE THREAD

**Issue by Xin-cqu** [poldracklab/fmriprep#1663]
I got the json file in rest fMRI data implied that the "PhaseEncodingDirection: y-" which cause the fMRIprep reject to recognize the right PE direction. Data I used is from CamCAN. The whole json file is: `{
	"RepetitionTime": 1.97,
	"EchoTime": 0.03,
	"FlipAngle": 78,
	"SliceTiming": [1.895,1.835,1.7725,1.7125,1.65,1.59,1.5275,1.4675,1.4075,1.345,1.285,1.2225,1.1625,1.1,1.04,0.9775,0.9175,0.855,0.795,0.7325,0.6725,0.61,0.55,0.49,0.4275,0.3675,0.305,0.245,0.1825,0.1225,0.06000000001,0],
	"EffectiveEchoSpacing": 0.0005100042432,
	"PhaseEncodingDirection": "y-",
	"TaskName": "Rest"
}
`
How could I fix it?

**Comment by effigies** [comment]
PhaseEncodingDirection should use i, j, k, rather than x, y, z. It is probable you want j-, but you should verify that. j indicates the second axis in the data block, irrespective of world dimensions.

**Comment by Xin-cqu** [comment]
@effigies Thanks for your explanation. The analogy of x,y,z and i,j,k was very clear and easy to understand. Problem was solved. Again, thanks.
