### ISSUE TITLE
Allow subjects to be run in parallel without causing errors

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/fmriprep#1667]
While running fmriprep (--anat-only) on 13 subjects in parallel, I ran into the following error on 4 of the subjects due to subjects running simultaneously:

FileNotFoundError: [Errno 2] No such file or directory: '/scratch/03201/jbwexler/openneuro_fmriprep/data/ds000003_work/ds000003-download/derivatives/fmriprep-1.4.0/fmriprep/logs/CITATION.md'

I'm attaching the full log here.
[ds003_anatonly.txt](https://github.com/poldracklab/fmriprep/files/3259486/ds003_anatonly.txt)

**Comment by effigies** [comment]
Thanks @jbwexler. I agree we need to handle this better.

**Comment by oesteban** [comment]
This was introduced in #1567.

I've been thinking about this and: i) the boilerplate is generated on a per-subject basis, and it should stay within the subject directory - which would solve this issue immediately; ii) [with the findings of Soichi at neurostars](https://neurostars.org/t/large-virtual-memory-allocations-in-fmriprep-on-pbs-system/4665/10?u=oesteban) I think we should delay markdown to html conversion to the very end of fmriprep (not right at the beginning).

WDYT? I'm going to increase the priority of this.
