### ISSUE TITLE
Dimensions of space-T1w_desc-preproc_bold.nii.gz images

### ISSUE THREAD

**Issue by OlenaInuki** [poldracklab/fmriprep#1672]
Dear fmriprep experts,

I have a question about the space of space-T1w_desc-preproc_bold.nii.gz files. I was under the impression that files with "space-T1w" in the name are in T1w space (i.e., should have the same # of voxels, matrix size, and voxel size as the preprocessed T1w image), but the space-T1w_desc-preproc_bold.nii.gz files I get all seem to be in some weird space that's neither their original functional space, nor the T1w space. Here's the output of fslinfo:

fslinfo ~/fmriprep/sub-A00040573/func/sub-A00040573_task-rest_space-T1w_desc-preproc_bold.nii.gz 
data_type      INT16
dim1           66
dim2           90
dim3           69
dim4           404
datatype       4
pixdim1        2.000000
pixdim2        2.000000
pixdim3        2.000000
pixdim4        1.400000

This is the original BOLD data:

fslinfo ~/sub-A00040573/func/sub-A00040573_task-rest_bold.nii.gz 
data_type      INT16
dim1           112
dim2           112
dim3           64
dim4           404
datatype       4
pixdim1        2.000000
pixdim2        2.000000
pixdim3        2.000000
pixdim4        1.400000

This is the preprocessed T1w image (same as the original one):

fslinfo ~/fmriprep/sub-A00040573/anat/sub-A00040573_desc-preproc_T1w.nii.gz 
data_type      FLOAT32
dim1           176
dim2           256
dim3           256
dim4           1
datatype       16
pixdim1        1.000000
pixdim2        0.976562
pixdim3        0.976562
pixdim4        0.000000

So, what space is space-T1w_desc-preproc_bold.nii.gz in?

In case this is relevant, here's the command I used to preprocess the data:
docker run --rm -it -e DOCKER_VERSION_8395080871=18.09.2 \
 -v /Applications/freesurfer/license.txt:/opt/freesurfer/license.txt:ro \
 -v /Users/neuroteam/Documents/bids/Nifti:/data:ro \
 -v /Users/neuroteam/Documents/bids/Nifti/derivatives:/out poldracklab/fmriprep:latest \
/data /out participant  --participant-label A00040573 --ignore slicetiming \
 --use-syn-sdc --low-mem --output-spaces T1w MNI152NLin2009cAsym fsaverage

I'm also attaching the log file (no errors in the html report). 
[sub-A00040573 log 061019.txt](https://github.com/poldracklab/fmriprep/files/3283318/sub-A00040573.log.061019.txt)

Thanks so much for all your help!
Olena

**Comment by oesteban** [comment]
> the space-T1w_desc-preproc_bold.nii.gz files I get all seem to be in some weird space that's neither their original functional space, nor the T1w space

That weird space is indeed T1w space. The caveat is what you understand for "space". If you understand a continuous cartesian system of physical coordinates, then fMRIPrep is working properly.

If you understand a discrete coordinate of voxels, then of course none of the three images (functional, T1w and preprocessed) are aligned.

fMRIPrep understands space as physical coordinates and thus there is nothing wrong about your outputs.

If you open up the T1w image with a decent visualization tool and then overlay the preprocessed file you'll see how they are aligned. Looking at the visual report for this task would also suffice to ensure both images are properly aligned.

**Comment by OlenaInuki** [comment]
Oh, I see. Thank you for the clarification!
