### ISSUE TITLE
Incomplete implementation of fsLR output space

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1673]
Adding `fsLR` to the `--output-spaces` argument currently leads to crashing in several ways.

Example: https://neurostars.org/t/fmriprep-v1-4-0-error-when-using-fslr-in-output-spaces/4435?u=oesteban

Related: #1611 #1612

**Comment by oesteban** [comment]
@mgxd is this addressed by #1887 ?

**Comment by oesteban** [comment]
@mgxd bumping up the question above

**Comment by mgxd** [comment]
yes, should fix it
