### ISSUE TITLE
assert info_dir, "%s .dist-info directory not found" % req AssertionError: fmriprep-docker .dist-info directory not found

### ISSUE THREAD

**Issue by vittalkorann** [poldracklab/fmriprep#1676]
Hello fmriprep experts,

I am trying to install fmriprep-docker in ubuntu16.04.
I have installed all the dependencies required for fmriprep-docker.

When I did "pip install --user --upgrade fmriprep-docker", I am getting the following error:' WARNING: The directory '/home/naren123/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/naren123/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting fmriprep-docker
Installing collected packages: fmriprep-docker
ERROR: Exception:
Traceback (most recent call last):
  File "/home/naren123/anaconda3/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/home/naren123/anaconda3/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "/home/naren123/anaconda3/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/home/naren123/anaconda3/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 920, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/home/naren123/anaconda3/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 448, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/home/naren123/anaconda3/lib/python3.6/site-packages/pip/_internal/wheel.py", line 428, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: fmriprep-docker .dist-info directory not found'

If any solutions available for the above problem, please post me.

Thank you
-Korann

**Comment by effigies** [comment]
I would try `pip install --upgrade --user pip`.

**Comment by vittalkorann** [comment]
Thank you, Chris, for your response

I tried long back it didn't work though.
Anything else other than the above-mentioned solution.

Thanks
-Korann

**Comment by effigies** [comment]
It looks like this is a problem related to `The directory '/home/naren123/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory.`

Search: [pip ".dist-info directory not found"](https://www.google.com/search?hl=en&q=pip%20%22.dist%2Dinfo%20directory%20not%20found%22)

You'll need to fix your Python/pip installation or install a distribution like [Anaconda](https://www.anaconda.com/distribution/).

**Comment by vittalkorann** [comment]
Hello Chris,

The '.cache' is hidden file and root doesn't have access to it. Any other
way to sort it out? I tried my best to sort out.

Thanks & regards
-Korann

**Comment by vittalkorann** [comment]
Hello Chris,

When executing this command  'sudo -H pip install --user --upgrade
fmriprep-docker', I got following error:

"Collecting fmriprep-docker
  Downloading
https://files.pythonhosted.org/packages/1e/7c/5d873dd3c8c67b9072addba434a2686e3571eabef97304f16c14844ae80c/fmriprep-docker-1.4.0.tar.gz
  WARNING: Generating metadata for package fmriprep-docker produced
metadata for project name unknown. Fix your #egg=fmriprep-docker fragments.
Building wheels for collected packages: unknown, unknown
  Building wheel for unknown (setup.py) ... done
  Stored in directory:
/root/.cache/pip/wheels/ee/1a/04/aa4b02a87dd7bfa3c9684ef3a87f77d557dede6af3143840e7
  Building wheel for unknown (setup.py) ... error
  ERROR: Complete output from command /usr/bin/python3 -u -c 'import
setuptools,
tokenize;__file__='"'"'/tmp/pip-install-qy_ormrx/unknown/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
bdist_wheel -d /tmp/pip-wheel-_1vs0usa --python-tag cp35:
  ERROR: Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.5/tokenize.py", line 454, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory:
'/tmp/pip-install-qy_ormrx/unknown/setup.py'
  ----------------------------------------
  ERROR: Failed building wheel for unknown
  Running setup.py clean for unknown
  ERROR: Complete output from command /usr/bin/python3 -u -c 'import
setuptools,
tokenize;__file__='"'"'/tmp/pip-install-qy_ormrx/unknown/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
clean --all:
  ERROR: Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.5/tokenize.py", line 454, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory:
'/tmp/pip-install-qy_ormrx/unknown/setup.py'
  ----------------------------------------
  ERROR: Failed cleaning build dir for unknown
Successfully built unknown
Failed to build unknown
Installing collected packages: unknown
Successfully installed unknown-0.0.0 "

Though I have access to '.cache' file, I am getting above error. Any help
would mean a lot!!

Thanks & regards
-Korann

**Comment by oesteban** [comment]
I've seen that kind of error before and never looked into the original cause. But they usually go away adding the option `--no-cache` to your command line:

```
sudo -H pip install --user --upgrade --no-cache fmriprep-docker
```

**Comment by vittalkorann** [comment]
Thank you, Chris, for your suggestion.

I have tried "*sudo -H pip install --user --upgrade --no-cache
fmriprep-docker" and below is the error message:*

*" *
sudo -H pip install --user --upgrade --no-cache fmriprep-docker
Collecting fmriprep-docker
  Downloading
https://files.pythonhosted.org/packages/1e/7c/5d873dd3c8c67b9072addba434a2686e3571eabef97304f16c14844ae80c/fmriprep-docker-1.4.0.tar.gz
  WARNING: Generating metadata for package fmriprep-docker produced
metadata for project name unknown. Fix your #egg=fmriprep-docker fragments.
Building wheels for collected packages: unknown, unknown
  Building wheel for unknown (setup.py) ... done
  Stored in directory:
/tmp/pip-ephem-wheel-cache-5b48h2bi/wheels/ee/1a/04/aa4b02a87dd7bfa3c9684ef3a87f77d557dede6af3143840e7
  Building wheel for unknown (setup.py) ... error
  ERROR: Complete output from command /usr/bin/python3 -u -c 'import
setuptools,
tokenize;__file__='"'"'/tmp/pip-install-8yqcru5b/unknown/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
bdist_wheel -d /tmp/pip-wheel-23huay_2 --python-tag cp35:
  ERROR: Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.5/tokenize.py", line 454, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory:
'/tmp/pip-install-8yqcru5b/unknown/setup.py'
  ----------------------------------------
  ERROR: Failed building wheel for unknown
  Running setup.py clean for unknown
  ERROR: Complete output from command /usr/bin/python3 -u -c 'import
setuptools,
tokenize;__file__='"'"'/tmp/pip-install-8yqcru5b/unknown/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
clean --all:
  ERROR: Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.5/tokenize.py", line 454, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory:
'/tmp/pip-install-8yqcru5b/unknown/setup.py'
  ----------------------------------------
  ERROR: Failed cleaning build dir for unknown
Successfully built unknown
Failed to build unknown
Installing collected packages: unknown
  Found existing installation: UNKNOWN 0.0.0
    Uninstalling UNKNOWN-0.0.0:
      Successfully uninstalled UNKNOWN-0.0.0
Successfully installed unknown-0.0.0
"

Are any other solutions available for this? If so please let me know.

Thanks & regards
-Korann

**Comment by oesteban** [comment]
Hi Korann,

Sorry for the confusion. The right argument is `--no-cache-dir`.

```
sudo -H pip install --user --upgrade --no-cache-dir fmriprep-docker
```

(you are missing that last `-dir` bit)

**Comment by vittalkorann** [comment]
Thank you, Esteban, for your help.

But the above-mentioned command also threw an error and the same given
below:

" sudo -H pip install --user --upgrade --no-cache-dir  fmriprep-docker

Collecting fmriprep-docker
  Downloading
https://files.pythonhosted.org/packages/1e/7c/5d873dd3c8c67b9072addba434a2686e3571eabef97304f16c14844ae80c/fmriprep-docker-1.4.0.tar.gz
  WARNING: Generating metadata for package fmriprep-docker produced
metadata for project name unknown. Fix your #egg=fmriprep-docker fragments.
Building wheels for collected packages: unknown, unknown
  Building wheel for unknown (setup.py) ... done
  Stored in directory:
/tmp/pip-ephem-wheel-cache-km0ejqrd/wheels/ee/1a/04/aa4b02a87dd7bfa3c9684ef3a87f77d557dede6af3143840e7
  Building wheel for unknown (setup.py) ... error
  ERROR: Complete output from command /usr/bin/python3 -u -c 'import
setuptools,
tokenize;__file__='"'"'/tmp/pip-install-wcd4nk0v/unknown/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
bdist_wheel -d /tmp/pip-wheel-6au__q3z --python-tag cp35:
  ERROR: Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.5/tokenize.py", line 454, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory:
'/tmp/pip-install-wcd4nk0v/unknown/setup.py'
  ----------------------------------------
  ERROR: Failed building wheel for unknown
  Running setup.py clean for unknown
  ERROR: Complete output from command /usr/bin/python3 -u -c 'import
setuptools,
tokenize;__file__='"'"'/tmp/pip-install-wcd4nk0v/unknown/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
clean --all:
  ERROR: Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.5/tokenize.py", line 454, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory:
'/tmp/pip-install-wcd4nk0v/unknown/setup.py'
  ----------------------------------------
  ERROR: Failed cleaning build dir for unknown
Successfully built unknown
Failed to build unknown
Installing collected packages: unknown
  Found existing installation: UNKNOWN 0.0.0
    Uninstalling UNKNOWN-0.0.0:
      Successfully uninstalled UNKNOWN-0.0.0
Successfully installed unknown-0.0.0 "

Further solution?
Thanks & regards
-Korann

**Comment by effigies** [comment]
This is very strange I'm able to install this package from a variety of virtual environments and have not seen anything like this. Can you also try `pip install --upgrade setuptools`?

**Comment by vittalkorann** [comment]
Thanks, Chris for a timely response. It did work for me.

"sudo -H pip install --upgrade setuptools"

"sudo -H pip install --user --upgrade --no-cache-dir  fmriprep-docker"

The above 2 commands worked for me and here is the terminal output:
"Collecting fmriprep-docker
  Downloading
https://files.pythonhosted.org/packages/1e/7c/5d873dd3c8c67b9072addba434a2686e3571eabef97304f16c14844ae80c/fmriprep-docker-1.4.0.tar.gz
Building wheels for collected packages: fmriprep-docker
  Building wheel for fmriprep-docker (setup.py) ... done
  Stored in directory:
/tmp/pip-ephem-wheel-cache-d2b8288t/wheels/ee/1a/04/aa4b02a87dd7bfa3c9684ef3a87f77d557dede6af3143840e7
Successfully built fmriprep-docker
Installing collected packages: fmriprep-docker
  WARNING: The script fmriprep-docker is installed in '/root/.local/bin'
which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this
warning, use --no-warn-script-location.
Successfully installed fmriprep-docker-1.4.0"

Until I get the first output from the fmriprep pipeline, will keep bugging
you :)

With regards
-Korann

**Comment by vittalkorann** [comment]
Hello Chris,

After installing fmriprep, when trying to execute the command:
 "fmriprep-docker '/home/naren123/Desktop/TO_BIDS/sub-01'
'/home/naren123/Desktop/TO_BIDS/derivatives' participant
--participant-label sub-01 --fs-license-file
'/usr/local/freesurfer/license.txt' --ignore slicetiming"
'fmriprep-docker: command not found'

# whereis docker
docker: /usr/bin/docker /etc/docker /usr/share/man/man1/docker.1.gz

#sudo -H  python -m pip install --upgrade fmriprep-dockerRequirement
already up-to-date: fmriprep-docker in
/root/.local/lib/python3.5/site-packages (1.4.0)

Good if you let me know the solution for the above!

Thanks & regards
-Korann

**Comment by vittalkorann** [comment]
Also Chris,

When type this command: "find ~/.local -name fmriprep-docker"
It does not display it's path for me.

root@Milkyway:~# find ~/.local -name fmriprep-docker
root@Milkyway:~#

Something wrong with installation or the path.I am not able to figure it
out.
Any suggestions?

Thanks & regards
-Korann

**Comment by effigies** [comment]
Yeah, sorry, it looks like you've got your Python environments fairly messed up, with things installed in `/root/.local`, which seems pretty useless. I think we gave you some bad advice. Let's uninstall:

```Shell
pip uninstall fmriprep-docker
sudo -H pip uninstall fmriprep-docker
```

Let's upgrade your installation tools in your base environment, and we can use root to do this. Note the lack of `--user`.

```Shell
sudo -H python -m pip install --upgrade pip setuptools wheel
```

Now, if you want, you can install with `sudo -H`, or you can install with `--user`, but don't do both, or you'll end up back in `/root/.local`. I would suggest:

```Shell
pip install --upgrade --user fmriprep-docker
```

Now that should be installed in your main Python environment, but in a user-controlled directory, probably `$HOME/.local/bin`.

**Comment by vittalkorann** [comment]
Thanks, Chris for the suggestion. But no luck though with the commands.
I uninstalled fmriprep-docker and tried with your commands. Below are the
error messages for both commands: sudo -H and --user

1.
"pip install --upgrade --user fmriprep-docker
WARNING: The directory '/home/naren123/.cache/pip/http' or its parent
directory is not owned by the current user and the cache has been disabled.
Please check the permissions and owner of that directory. If executing pip
with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/naren123/.cache/pip' or its parent directory
is not owned by the current user and caching wheels has been disabled.
check the permissions and owner of that directory. If executing pip with
sudo, you may want sudo's -H flag.
Collecting fmriprep-docker
Installing collected packages: fmriprep-docker
ERROR: Exception:
Traceback (most recent call last):
  File
"/home/naren123/anaconda3/lib/python3.6/site-packages/pip/_internal/cli/base_command.py",
line 178, in main
    status = self.run(options, args)
  File
"/home/naren123/anaconda3/lib/python3.6/site-packages/pip/_internal/commands/install.py",
line 414, in run
    use_user_site=options.use_user_site,
  File
"/home/naren123/anaconda3/lib/python3.6/site-packages/pip/_internal/req/__init__.py",
line 58, in install_given_reqs
    **kwargs
  File
"/home/naren123/anaconda3/lib/python3.6/site-packages/pip/_internal/req/req_install.py",
line 920, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File
"/home/naren123/anaconda3/lib/python3.6/site-packages/pip/_internal/req/req_install.py",
line 448, in move_wheel_files
    warn_script_location=warn_script_location,
  File
"/home/naren123/anaconda3/lib/python3.6/site-packages/pip/_internal/wheel.py",
line 428, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: fmriprep-docker .dist-info directory not found"

2.
"sudo -H pip install --upgrade fmriprep-docker
Collecting fmriprep-docker
Installing collected packages: fmriprep-docker
ERROR: Exception:
Traceback (most recent call last):
  File
"/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/base_command.py",
line 178, in main
    status = self.run(options, args)
  File
"/usr/local/lib/python3.5/dist-packages/pip/_internal/commands/install.py",
line 414, in run
    use_user_site=options.use_user_site,
  File
"/usr/local/lib/python3.5/dist-packages/pip/_internal/req/__init__.py",
line 58, in install_given_reqs
    **kwargs
  File
"/usr/local/lib/python3.5/dist-packages/pip/_internal/req/req_install.py",
line 920, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File
"/usr/local/lib/python3.5/dist-packages/pip/_internal/req/req_install.py",
line 448, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/wheel.py",
line 428, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: fmriprep-docker .dist-info directory not found"

Any more suggestions? Waiting for your comments Chris!

Thanks & regards
-Korann

**Comment by effigies** [comment]
At this point, I would suggest installing a Python distribution like Anaconda.

**Comment by vittalkorann** [comment]
Thanks, Chirs.

I did install anaconda but still, it is throwing an error:

$"whereis anaconda
anaconda: /home/naren123/anaconda3/bin/anaconda"

Thanks & regards
-Korann

**Comment by effigies** [comment]
What is the error?

**Comment by vittalkorann** [comment]
Thanks, Chris,

"sudo -H pip install --upgrade fmriprep-docker
Collecting fmriprep-docker
Installing collected packages: fmriprep-docker
ERROR: Exception:
Traceback (most recent call last):
  File
"/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/base_command.py",
line 178, in main
    status = self.run(options, args)
  File
"/usr/local/lib/python3.5/dist-packages/pip/_internal/commands/install.py",
line 414, in run
    use_user_site=options.use_user_site,
  File
"/usr/local/lib/python3.5/dist-packages/pip/_internal/req/__init__.py",
line 58, in install_given_reqs
    **kwargs
  File
"/usr/local/lib/python3.5/dist-packages/pip/_internal/req/req_install.py",
line 920, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File
"/usr/local/lib/python3.5/dist-packages/pip/_internal/req/req_install.py",
line 448, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/wheel.py",
line 428, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: fmriprep-docker .dist-info directory not found"

Is it because of the pyhton version it is throwing an error? or something
else is affecting the installation.
Need your help, Chris...



Thanks & regards
-Korann

**Comment by effigies** [comment]
Hi, it looks like you're still using the default Python installation, and not Anaconda. Please see the [installation docs](https://docs.anaconda.com/anaconda/install/linux/).
