### ISSUE TITLE
RuntimeError: Data for requested participant(s) label(s) not found. Could not find data for participant(s)

### ISSUE THREAD

**Issue by qcheung33** [poldracklab/fmriprep#1682]
I use docker to run fmriprep, and the testing dataset has passed the BIDS validation (with warnings). 

However, when I run the command, the error message I got is `RuntimeError: Data for requested participant(s) label(s) not found. Could not find data for participant(s): –-use-aroma,–-fs-license-file,/Users/bernice/license.txt,–-fd-spike-threshold,–-low-mem,–-fs-no-reconall. Please verify the requested participant labels.`

My command line is `fmriprep-docker /Users/bernice/Documents/socialContext_BIDS/ /Users/bernice/Documents/socialContext_BIDS/derivatives/ --participant_label 01 -w /Users/bernice/Documents/socialContext_BIDS/derivatives/scratch/ –-fs-license-file /Users/bernice/license.txt –-low-mem –-fs-no-reconall –-use-aroma –-fd-spike-threshold`

It seems like my additional arguments were not recognized. Could anyone help me figure out what should I change with my command? Thank you so much!

**Comment by effigies** [comment]
The first output of `fmriprep-docker` should be a line beginning with `RUNNING:`. Could you paste that line here?

**Comment by qcheung33** [comment]
> The first output of `fmriprep-docker` should be a line beginning with `RUNNING:`. Could you paste that line here?

The first line of output is `RUNNING: docker run --rm -it -e DOCKER_VERSION_8395080871=18.09.2 -v /Users/bernice/Documents/socialContext_BIDS:/data:ro -v /Users/bernice/Documents/socialContext_BIDS/derivatives:/out -v /Users/bernice/Documents/socialContext_BIDS/derivatives/scratch:/scratch poldracklab/fmriprep:1.4.0 /data /out participant --participant_label 01 –-fs-license-file /Users/bernice/license.txt –-low-mem –-fs-no-reconall –-use-aroma –-fd-spike-threshold -w /scratch`

**Comment by effigies** [comment]
Well, something seems wrong, since your `--fs-license-file /Users/bernice/license.txt` should be translated to a volume mount like:

`-v /Users/bernice/license.txt:/opt/freesurfer/license.txt:ro`

Can you try moving `--participant-label 01` to the end of the command?

**Comment by qcheung33** [comment]
> Well, something seems wrong, since your `--fs-license-file /Users/bernice/license.txt` should be translated to a volume mount like:
> 
> `-v /Users/bernice/license.txt:/opt/freesurfer/license.txt:ro`
> 
> Can you try moving `--participant-label 01` to the end of the command?

Thanks for the suggestion! 
I ran the command with the participant argument at the end, but it still gave the same error. 
My updated command line: `fmriprep-docker /Users/bernice/Documents/socialContext_BIDS/ /Users/bernice/Documents/socialContext_BIDS/derivatives/ -w/Users/bernice/Documents/socialContext_BIDS/derivatives/scratch/ –-fs-license-file /Users/bernice/license.txt –-low-mem –-fs-no-reconall –-use-aroma –-fd-spike-threshold --participant-label 01`

The first line of output is : `docker run --rm -it -e DOCKER_VERSION_8395080871=18.09.2 -v /Users/bernice/Documents/socialContext_BIDS:/data:ro -v /Users/bernice/Documents/socialContext_BIDS/derivatives:/out -v /Users/bernice/Documents/socialContext_BIDS/derivatives/scratch:/scratch poldracklab/fmriprep:1.4.0 /data /out participant –-fs-license-file /Users/bernice/license.txt –-low-mem –-fs-no-reconall –-use-aroma –-fd-spike-threshold --participant-label 01 -w /scratch`

Here's my file tree for the BIDS folder: 
── CHANGES
├── README
├── code
│   └── socialContext_config.json
├── dataset_description.json
├── derivatives
│   └── scratch
├── participants.json
├── participants.tsv
├── sourcedata
├── sub-01
│   ├── anat
│   │   ├── sub-01_T1w.json
│   │   └── sub-01_T1w.nii.gz
│   ├── fmap
│   │   ├── sub-01_dir-AP_epi.json
│   │   ├── sub-01_dir-AP_epi.nii.gz
│   │   ├── sub-01_dir-PA_epi.json
│   │   └── sub-01_dir-PA_epi.nii.gz
│   └── func
│       ├── sub-01_task-socialContext_run-1_bold.json
│       ├── sub-01_task-socialContext_run-1_bold.nii.gz
│       ├── sub-01_task-socialContext_run-2_bold.json
│       ├── sub-01_task-socialContext_run-2_bold.nii.gz
│       ├── sub-01_task-socialContext_run-3_bold.json
│       ├── sub-01_task-socialContext_run-3_bold.nii.gz
│       ├── sub-01_task-socialContext_run-4_bold.json
│       └── sub-01_task-socialContext_run-4_bold.nii.gz

**Comment by effigies** [comment]
Thanks. Could you share the error again? It doesn't make sense to have all of the same contents as initially...

**Comment by qcheung33** [comment]
> Thanks. Could you share the error again? It doesn't make sense to have all of the same contents as initially...

If I put the participant argument at the end, the error message I got is 
`fmriprep: error: unrecognized arguments: –-fs-license-file /Users/bernice/license.txt –-low-mem –-fs-no-reconall –-use-aroma –-fd-spike-threshold`

**Comment by effigies** [comment]
I think some of those hyphens might not be ASCII dashes (-), but instead unicode endashes (&ndash;).

**Comment by qcheung33** [comment]
> I think some of those hyphens might not be ASCII dashes (-), but instead unicode endashes (–).

it worked! Thank you so much!!!

**Comment by effigies** [comment]
Glad to hear it!
