### ISSUE TITLE
Not recognizing --output-spaces argument

### ISSUE THREAD

**Issue by rtansey** [poldracklab/fmriprep#1696]
I am trying to run the new version released today, 1.4.1, but I don't think that it is updating and/or being accessed correctly, despite running

`pip install --user --upgrade fmriprep-docker`

and getting a message saying that version 1.4.1 has successfully installed. I keep getting the following error:

> /usr/local/miniconda/lib/python3.6/site-packages/bids/grabbids/__init__.py:6: FutureWarning: grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8
  warnings.warn("grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8", FutureWarning)
usage: fmriprep [-h] [--version]
                [--participant_label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]]
                [-t TASK_ID] [--debug] [--nthreads NTHREADS]
                [--omp-nthreads OMP_NTHREADS] [--mem_mb MEM_MB] [--low-mem]
                [--use-plugin USE_PLUGIN] [--anat-only] [--boilerplate]
                [--ignore-aroma-denoising-errors] [-v]
                [--ignore {fieldmaps,slicetiming} [{fieldmaps,slicetiming} ...]]
                [--longitudinal] [--t2s-coreg] [--bold2t1w-dof {6,9,12}]
                [--output-space {T1w,template,fsnative,fsaverage,fsaverage6,fsaverage5} [{T1w,template,fsnative,fsaverage,fsaverage6,fsaverage5} ...]]
                [--force-bbr] [--force-no-bbr]
                [--template {MNI152NLin2009cAsym}]
                [--output-grid-reference OUTPUT_GRID_REFERENCE]
                [--template-resampling-grid TEMPLATE_RESAMPLING_GRID]
                [--medial-surface-nan] [--use-aroma]
                [--aroma-melodic-dimensionality AROMA_MELODIC_DIMENSIONALITY]
                [--skull-strip-template {OASIS,NKI}]
                [--skull-strip-fixed-seed] [--fmap-bspline] [--fmap-no-demean]
                [--use-syn-sdc] [--force-syn] [--fs-license-file PATH]
                [--no-submm-recon] [--cifti-output | --fs-no-reconall]
                [-w WORK_DIR] [--resource-monitor] [--reports-only]
                [--run-uuid RUN_UUID] [--write-graph] [--stop-on-first-crash]
                [--notrack]
                bids_dir output_dir {participant}
fmriprep: error: unrecognized arguments: --output-spaces MNIPediatricAsym

I have tried running through `fmriprep-docker`, and with `docker` only, but to no avail. Here are the arguments I have tried:

`fmriprep-docker [bids_folder] [output_folder] participant --participant_label [participant_ID] --ignore fieldmaps --fs-no-reconall --use-syn-sdc --output-spaces MNIPediatricAsym --bold2t1w-dof 9`

`docker run -i --rm -v [bids_folder]:/bids_dataset:ro -v [output_folder]:/outputs poldracklab/fmriprep -v /bids_dataset /outputs participant --participant_label [participant_ID] --ignore fieldmaps --fs-no-reconall --use-syn-sdc --output-spaces MNIPediatricAsym --bold2t1w-dof 9`

Thanks!

**Comment by oesteban** [comment]
can you try?:

```
fmriprep-docker -i poldracklab/fmriprep:1.4.1 ...
```

**Comment by rtansey** [comment]
I think that there is something wrong with my fmriprep-docker as I keep getting the error `-bash: fmriprep-docker: command not found`. Is there an equivalent to what you suggested, but in the `docker` format?

Thank you so much for your help!

**Comment by oesteban** [comment]
Okay, let's try this:


First, pull down the latest fmriprep Docker image
```
docker pull poldracklab/fmriprep:1.4.1
```

Next, let's call fmriprep-docker with an absolute path:

```
$HOME/.local/bin/fmriprep-docker -i poldracklab/fmriprep:1.4.1 --version
```

**Comment by rtansey** [comment]
Thank you! It seems to be running now. For anyone accessing this thread later, my final commands were

`$HOME/.local/bin/fmriprep-docker -i poldracklab/fmriprep:1.4.1 [bids_folder] [output_folder] participant --participant_label [participant_ID] --fs-license-file [license_path] --ignore fieldmaps --fs-no-reconall --use-syn-sdc --output-spaces MNIPediatricAsym:res-2 --bold2t1w-dof 9`
