### ISSUE TITLE
Coregistration plots should use animations

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#170]
Like in here: https://simexp.github.io/qc_cobre/registration.html

Avoid generating GIFs - using CSS or JS should generate smaller files.

**Comment by oesteban** [comment]
I've been thinking of this during some off times here and there. Some ideas:
  - SVG + CSS: https://jonsuh.com/blog/animate-svg-with-css/
  - JS: in case the previous is not compatible with the browser, with D3.js this should be fairly easy. After all, for mriqc I am already using D3... so I am starting to climb its learning curve.

**Comment by shoshber** [comment]
This is basically done. However, I just noticed that the animation doesn't work in Safari, which is totally fine for now.

**Comment by oesteban** [comment]
Safari Version 10.0 (11602.1.50.0.10) works perfectly for me.

**Comment by shoshber** [comment]
Yep, I'm still using Safari 9. Shall we close the issue?
