### ISSUE TITLE
Error waiting for container

### ISSUE THREAD

**Issue by qcheung33** [poldracklab/fmriprep#1704]
I ran fmriprep using docker, and I've set the preference to 8 RAM. 

After 10 hours of running 1 subject, an error message pop up: 
```
ERRO[41511] Error waiting for container: container 21c1043c98305ac4712ba85f082ae344267676ffad276fd85525389beaa3d165: driver "overlay2" failed to remove root filesystem: remove /var/lib/docker/overlay2/2fb0d71cbd334a232909ace0e822ed7fd3c8642e57b95ba2ba7b9afda35f6e12/link: read-only file system
```

The command that I used was: 
```
fmriprep-docker /Users/bernice/Documents/socialContext_BIDS/ /Users/bernice/Documents/socialContext_BIDS/derivatives/ --participant_label 06 -w/Users/bernice/Documents/socialContext_BIDS/derivatives/scratch/ --fs-license-file /Users/bernice/license.txt --low-mem --fs-no-reconall --use-aroma --fd-spike-threshold 0.2
```

This error message popped up after `[Node] Finished "fmriprep_wf.single_subject_06_wf.func_preproc_task_school_run_3_wf.bold_std_trans_wf.merge".`

Can anyone help me take a look, and provide some troubleshooting suggestions? 

Thank you so much!

**Comment by oesteban** [comment]
That is a problem with your Docker engine. Maybe this would help https://stackoverflow.com/a/50653728
