### ISSUE TITLE
Attempting to record Sentry events when --notrack is set

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#1705]
Via https://github.com/poldracklab/fmriprep/issues/1681#issuecomment-513325136, it looks like there are cases when `--notrack` is set, but we still try to use `sentry_sdk`.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.3.2', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 440, in main
    sentry_sdk.capture_exception(e)
AttributeError: 'NoneType' object has no attribute 'capture_exception'
```

To be clear, it does not look like information is being sent, just that we aren't checking for whether the event handler should exist before adding information to it.

**Comment by oesteban** [comment]
I think that affected 1.3.x series only:

https://github.com/poldracklab/fmriprep/blob/a8ef9a3b1722dd667e6ca0fc0e06a1fd23219eb1/fmriprep/cli/run.py#L437-L441

Now I believe all sentry calls are protected with a check on the notrack flag.

**Comment by oesteban** [comment]
After the refactor of the config module, it seems very unlikely this is still happening. Close?
