### ISSUE TITLE
fmriprep singularity run failing

### ISSUE THREAD

**Issue by dkp** [poldracklab/fmriprep#1718]
Back in May I tried fmriprep 1.4.1 as a singularity container on our HPC successfully.  I'm trying it again (updated to 1.5.0rc1) and getting failure after failure.
The job submitted was:

export WORKING=/extra/dkp
module load singularity
singularity run --cleanenv --bind ${WORKING}/mydata:/data ${WORKING}/singularity-images/fmriprep.sif /data /data/derivatives participant --participant_label 1012 --fs-license-file ${WORKING}/license.txt -w /data/work --fs-no-reconall --ignore slicetiming

(I gave it 6 cpus, 36 gb of ram 16 hours of walltime and 48 hours of cpu time)

The log is attached. This is singularity/3/3.2.1  
[crash-20190728-090052-dkp-norm-41affd0e-a86f-48c8-84a2-18930d54156a.txt](https://github.com/poldracklab/fmriprep/files/3439352/crash-20190728-090052-dkp-norm-41affd0e-a86f-48c8-84a2-18930d54156a.txt)

Any advice would be greatly appreciated.  

The corresponding docker container for 1.5.0rc1 is running fine on the same dataset on my mac. I will test singularity on a local linux box and see if I encounter the same problem.

Thank you,

Dianne

**Comment by dkp** [comment]
I'm not going to submit this to you unless it is also failing on a local linux box.  I suspect the job submission system is not behaving as expected on the HPC.

**Comment by oesteban** [comment]
Sorry I missed this issue. It looks very much like a memory issue, the kernel killed the process halfway.

**Comment by dkp** [comment]
Umm, you are very kind.  User error ; p
