### ISSUE TITLE
replace comma with point in the confounds_regressors.tsv file?

### ISSUE THREAD

**Issue by vtsogli** [poldracklab/fmriprep#1719]
Hello, 
one of fmriprep derivatives is the "sub-001_..._desc-confounds_regressors.tsv" file. 
I used Gnumeric to open this file in order to export the data in a .txt file and use them in SPM. 
In this file both the comma and the point are used as decimal delimiters.
If I replace all commas with points will it cause any kind of issue? 
The reason is that MATLAB comes up with an error when I try to load files where commas are used as decimal delimiters. 
Thank you for your time.

**Comment by effigies** [comment]
Hi, could you provide more details of which regressors are found to have commas over decimal points?

**Comment by vtsogli** [comment]
Hi Chris, 
Thank you for your response. 
Columns were comma is used as decimal point in the .tsv file:
csf_power2, white_matter_power2 (ex: 297106,35149069515), all t_comp_cor_00 (ex: -0,0196131286) till t_comp_cor_06, all a_comp_cor_01 till a_comp_cor_219, all cosine00 till cosine31 (ex: 0,04311), trans_x, trans_x_power2, trans_y, trans_y_power2, trans_z, trans_z_power2, rot_x, rot_x_power2, rot_y, rot_y_power2, rot_z, rot_z_power2 and all motion_outlier00 till motion_outlier115.

**Comment by effigies** [comment]
Hmm. This is strange. That doesn't seem to be the case in our tests, and I don't see any indication that [`pandas.DataFrame.to_csv`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv) would do any automatic localization (e.g., `decimal='.'` is the default).

That said, it seems likely this is a localization issue hiding somewhere, so figuring out your locale might help us track this down. How are you running fMRIPrep?

**Comment by vtsogli** [comment]
Hi Chris, 
after reading your answer I tried to open the .tsv file within the MATLAB editor and actually there were no commas. I suppose that Gnumeric is not displaying correctly the data in the .tsv file. 
In that case I should find another way to save these data in a .txt file and not with Gnumeric.
Regarding your question "How are you running fMRIPrep?", we used the command:
sudo /home/.../.local/bin/fmriprep-docker ../Data/BIDS ../Data/BIDS/derivatives participant --participant-label 001 --fs-license-file /usr/local/freesurfer/license.txt
and there were no errors reported in the .html.
Thank you very much for your answer!

**Comment by effigies** [comment]
Ah, glad to hear that you found the source of the problem. I'd look into gnumeric settings to see if you can override the default to use a comma as a decimal.

That said, if all you want is to turn the file into a comma-separated value file with a .txt extension, you can use Python:

```Python
import pandas as pd
table = pd.read_csv(fname, delimiter='\t')
table.to_csv(new_fname, delimiter=',')
```

You can also select columns if you want...

```Python
# explicitly list columns
columns = ["column_name1", "column_name2", ...]
# or select by some predicate
columns = [col for col in table.columns if <some predicate>]

# and then

table = table[columns]
```

Best of luck!
