### ISSUE TITLE
Doesn't look for license at $FS_LICENSE

### ISSUE THREAD

**Issue by erikglee** [poldracklab/fmriprep#1720]
Hi,

I just downloaded version 1.0.7, and am using the instructions for a singularity image as specified on the fmriprep user page.

I originally didn't have a freesurfer license file on my path, and promptly got an error because of this. In the error, it says that fmriprep looks for a license file in a variety of places, including at the location specified by the $FS_LICENSE environmental variable. I downloaded a new license file and pointed to it with $FS_LICENSE but fmriprep didn't find the file. 

I then tried "--fs_license_file $FS_LICENSE" which worked fine. I now realize that the reason why "--fs_file $FS_LICENSE" worked but relying on fmriprep to look for the environmental variable $FS_LICENSE doesn't work is that the recommended "--cleanenv" flag prevents fmriprep from having access to environmental variables.

I don't know whether or not you would want to update the error message when a license file isn't found to take this into account, but thought I would let you know of this in case you were unaware.

Thanks,
Erik

**Comment by oesteban** [comment]
Hi @erikglee,

I would strongly recommend you to upgrade to version 1.4.1 as soon as possible since 1.0.7 is very outdated.

Regarding the environment variable, you can set environment variables within the container from outside (including the use of `--cleanenv`), preceding them by the prefix `SINGULARITYENV_`, therefore:

```
export SINGULARITYENV_FS_LICENSE=/some/path
```

**Comment by erikglee** [comment]
Good to know, thanks!
