### ISSUE TITLE
forces users to generate functional data in group spaces (vol and surf)

### ISSUE THREAD

**Issue by nblauch** [poldracklab/fmriprep#1723]
I recently upgraded to FMRIPREP 1.4.1 and am finding some of the new behavior around templates to be annoying and a bit wasteful on disk space. Specifically:
1) it fails if I do not specify one of the template spaces in --output-spaces (see https://neurostars.org/t/error-in-native-epi-space-processing-output-spaces-func/4639), 
```
File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py", line 551, in init_func_preproc_wf
    if 'MNI152NLin2009cAsym' in volume_std_spaces else next(iter(volume_std_spaces))
StopIteration
```

2) if i want recon-all, it assumes i must want functional data projected to the surface
```
Although ``--fs-no-reconall`` was not set (i.e., FreeSurfer is to be run), no FreeSurfer output space (valid values are: fsaverage, fsaverage6, fsnative, fsaverage5) was selected. Adding default "fsaverage5" to the list of output spaces.
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py:62: UserWarning: Accessing entities as attributes is deprecated as of 0.7. Please use the .entities dictionary instead (i.e., .entities['suffix'] instead of .suffix.
```

I don't think it is uncommon for people to want to just generate outputs in native volumetric space, do their analyses, and then manually do the transformation to the surface later for any group analyses. 

Please consider bringing back the ability not to generate functional data in template spaces. For now I can just delete the unwanted files.

Thanks as always for your great work on this project.

**Comment by oesteban** [comment]
> 1. it fails if I do not specify one of the template spaces in --output-spaces (see https://neurostars.org/t/error-in-native-epi-space-processing-output-spaces-func/4639),

That is a bug identified and fixed - should be up as of release 1.5.0rc1.

> 2. if i want recon-all, it assumes i must want functional data projected to the surface

I just opened a specific issue for this. You are invited to run the extra mile and send us a pull request :). Otherwise, we will evaluate the priority and it might take a bit longer to see an implementation.

Thanks very much for the feedback.
