### ISSUE TITLE
Do not generate surface outputs if not explicitly requested

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1724]
Currently, if a user does not set `--fs-no-reconall` and does not write any surface space among `--output-spaces`, then `fsaverage5` is automatically added to `--output-spaces` and corresponding functional data sampled on surface too.

This can be annoying (see #1723), and is a heavily implicit behavior. An explicit behavior where output surfaces must be found in the ``--output-spaces`` would be preferred.

**Comment by oesteban** [comment]
Related #1892

**Comment by mgxd** [comment]
Closing in favor of #1892
