### ISSUE TITLE
Reports layout does not work with wide windows

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#173]
narrow window:
![image](https://cloud.githubusercontent.com/assets/238759/20026447/d3d41f3c-a2b7-11e6-9460-9d6563e55484.png)

wide window:
![image](https://cloud.githubusercontent.com/assets/238759/20026450/e3f591c0-a2b7-11e6-8adc-2495c255db4a.png)

**Comment by rwblair** [comment]
Issue for old style reports, closing.
