### ISSUE TITLE
Resuming after a crash

### ISSUE THREAD

**Issue by Heechberri** [poldracklab/fmriprep#1731]
Hi,

My fMRI-prep crashed because my device ran out of space, is there anyway to resume it from where it stopped after I have fixed the issue with memory?

It takes roughly about 2 weeks to run through all 37 subjects with freesurfer and aroma on, is this normal? Is there anyway to optimise this?

Is there anyway to implement a memory estimation algorithm to calculate the amount of memory needed for the job, and check if the system has enough memory at the start of the job?  This is just a suggestion though, I do not know enough about coding to know if it is feasible. 

Thank you!

Regards,
Vae

**Comment by antotorov** [comment]
I am exactly in this situation too.

The first solution I though of was to use the --participant_label option to specify the rest of my participants to run. However, as far as I understand, this option isn't available when using the Docker wrapper (fmriprep-docker). Using fmriprep without container (with a manually prepared environment) would work, but I'm sure there is a better solution, like writing a custom Docker wrapper that would allow the --participant_label option.

Either ways, it would be great to have an option that would automatically detect subjects for which the analysis is already done and have fmriprep to skip those runs...

**Comment by Heechberri** [comment]
> The first solution I though of was to use the --participant_label option to specify the rest of my participants to run. However, as far as I understand, this option isn't available when using the Docker wrapper (fmriprep-docker). Using fmriprep without container (with a manually prepared environment) would work, but I'm sure there is a better solution, like writing a custom Docker wrapper that would allow the --participant_label option.
> 
I am using the Docker container version, since I had trouble setting up fMRIprep from scratch. I hope will be an option to restart my analysis from where I have left off.

> Either ways, it would be great to have an option that would automatically detect subjects for which the analysis is already done and have fmriprep to skip those runs...
>
Yes exactly I agree with this!!

**Comment by antotorov** [comment]
I think the following workaround should work. First define some variables as follows:

```
BIDS_ROOT="/path/to/your/bids/data"
OUTPUT="/path/to/your/results"
FS_HOME="/path/to/your/freesurfer_home"
```
In my case,

`OUTPUT="$BIDS_ROOT/derivatives"`

and

`FS_HOME="/Applications/freesurfer"`

Next define a list containing the labels (omitting the "sub-" prefix) of the subjects you'd like to run, for instance if fmriprep has crashed for sub-001, sub-042 and sub-666, then you need

`PARTICIPANTS="001 042 666"`

Now run the following 

```
docker "run" -ti --rm \
  -v "$BIDS_ROOT:/data" \
  -v "$OUTPUT:/output" \
  -v "$FS_HOME:/fs_home" \
  "poldracklab/fmriprep" \
  "/data" "/output" "participant" --fs-license-file "/fs_home/license.txt" --participant_label $PARTICIPANTS
```

Of course you should make sure to have the freesurfer license.txt file in the FS home folder, but I guess you already have this set up properly.

As you can see this tells docker to run fmriprep with the --participant_label option enabled.

I hope this will work on you side, let me know if I can help.

Disclaimer: I am really not an expert (neither in Docker or fmriprep) so what is above is only a suggestion. It is currently running on my computer so I haven't checked the final result yet.

**Comment by effigies** [comment]
Hi @Heechberri and @antotorov.

> My fMRI-prep crashed because my device ran out of space, is there anyway to resume it from where it stopped after I have fixed the issue with memory?

If you have specified a working directory with `-w` that is still around, then yes. Just re-run with the same parameters. The pieces that have already run will be found and reused.

> It takes roughly about 2 weeks to run through all 37 subjects with freesurfer and aroma on, is this normal? Is there anyway to optimise this?

If you have access to HPC system, then submitting one job for each subject is a typical parallelization strategy. If you only have your own server, you can run them all in one big fMRIPrep call, but you're very likely to run into disk constraints if you want to preserve all of the intermediate files for each subject.

2 weeks doesn't seem very unreasonable to me on a single system. That's on the order of 2-3 subjects a day, which is about as fast as you can hope if you're running FreeSurfer.

> Is there anyway to implement a memory estimation algorithm to calculate the amount of memory needed for the job, and check if the system has enough memory at the start of the job?

We do try to do this for the individual jobs, and rely on Nipype's scheduler to keep simultaneous jobs from consuming excessive memory. That said, with 37 subjects' workflows all in a single job, the controller thread itself will begin to consume a lot of memory that will be unaccounted for.

> The first solution I though of was to use the --participant_label option to specify the rest of my participants to run. However, as far as I understand, this option isn't available when using the Docker wrapper (fmriprep-docker).

All options available to `fmriprep` are available to `fmriprep-docker`. The options that are listed [here](https://fmriprep.readthedocs.io/en/stable/usage.html#the-docker-wrapper-cli) are ones that are added, modified or validated by the wrapper. This could be clearer in the documentation... It looks like we updated them in the [Installation](https://fmriprep.readthedocs.io/en/stable/installation.html) page, but not usage:

> > `fmriprep-docker` accepts all of the typical options for `fmriprep`, automatically translating directories into Docker mount points.

**Comment by Heechberri** [comment]
@antotorov 
> docker "run" -ti --rm \
  -v "$BIDS_ROOT:/data" \
  -v "$OUTPUT:/output" \
  -v "$FS_HOME:/fs_home" \
  "poldracklab/fmriprep" \
  "/data" "/output" "participant" --fs-license-file "/fs_home/license.txt" --participant_label $PARTICIPANTS

I see, thanks for your help, I will try it. Does this re-run all the selected participants from scratch? I have already finished all the freesurfer steps and got stuck at the very last step of processing some subjects (13/37) for aroma, it will be good if I can pick up the subjects from where they had been left off.

@effigies 
>If you have specified a working directory with -w that is still around, then yes. Just re-run with the same parameters. The pieces that have already run will be found and reused.

May  I ask what is the difference between fmriprep-docker and running from docker? I had problems downloading fmriprep-docker. This is what I have ran currently:

> > docker run -ti --rm 
-v $inputdir:/data:ro 
-v $local_outputdir:/fMRI  
-v /Applications/freesurfer/license.txt:/opt/freesurfer/license.txt poldracklab/fmriprep:latest 
/data /fMRI 
participant
 --error-on-aroma-warnings --use-aroma

And since I did not stipulate the -w the first time round, so probably I would not be able to continue the partially finished subjects?  If this time I added  **-w  $local_outputdir:/fMRI**  and re-ran the partially finished subjects with completed freesurfer files, would it be able to make use the freesurfer files already previously generated? 


Thank you for all your help!!

**Comment by effigies** [comment]
fmriprep-docker is just a wrapper that translates from an fMRIPrep command to a docker command, doing any mounting you need for you.

And no, if you didn't mount a working directory, you won't be able to resume. Using --participant-label to specify incomplete subjects is your best bet.

To mount a working directory use `-v $local_wd:/scratch` and then among the fMRIPrep arguments, add `-w /scratch`. Be careful, because `-w` is also a docker flag.

**Comment by Heechberri** [comment]
I see thank you! 

One last question, just to confirm that I understood the manual

> [Surface processing will be skipped if the outputs already exist. In order to bypass reconstruction in fMRIPrep, place existing reconstructed subjects in <output dir>/freesurfer prior to the run. fMRIPrep will perform any missing recon-all steps, but will not perform any steps whose outputs already exist.]

(https://fmriprep.readthedocs.io/en/stable/workflows.html?highlight=freesurfer#surface-preprocessing)

This means if I re-run the incompleted subjects with the full freesurfer directory and the tag recon-all, it will skip the freesurfer steps but do surface registration for their fmri data?

**Comment by antotorov** [comment]
Hi all,

@effigies,

> All options available to `fmriprep` are available to `fmriprep-docker`. The options that are listed [here](https://fmriprep.readthedocs.io/en/stable/usage.html#the-docker-wrapper-cli) are ones that are added, modified or validated by the wrapper. This could be clearer in the documentation... It looks like we updated them in the [Installation](https://fmriprep.readthedocs.io/en/stable/installation.html) page, but not usage.

Ok I see, I actually saw that but I was really confused because typing `fmriprep-docker -help` returns what's in the Usage section of the documentation.

@Heechberri 

>I see, thanks for your help, I will try it. Does this re-run all the selected participants from scratch? I have already finished all the freesurfer steps and got stuck at the very last step of processing some subjects (13/37) for aroma, it will be good if I can pick up the subjects from where they had been left off.

It re-runs all the remaining participants from scratch. If this suits your needs you could add the --fs-no-reconall option, which will have fmriprep to skip the freesurfer recons.

**Comment by jeroenvanbaar** [comment]
@effigies 
> If you have specified a working directory with `-w` that is still around, then yes. Just re-run with the same parameters. The pieces that have already run will be found and reused.

Hi Chris, quick question about this — what happens if you've updated fMRIprep (in my case by building the new version's singularity container) but there are intermediate files from a previous fMRIprep version left in the working directory? If one of the preprocessing steps has changed with the new version, will the corresponding pieces be discarded automatically, or should I manually clear the working dir / scratch when updating fMRIprep? Thanks!
- Jeroen

**Comment by effigies** [comment]
It's a bit ambiguous, unfortunately. Some times you can reuse, and you should feel free to try, but if it fails, the first thing I would try is with a clean working directory.

**Comment by jeroenvanbaar** [comment]
OK, thanks for the info.

**Comment by oesteban** [comment]
Closed in favor of a new issue requesting better documentation.
