### ISSUE TITLE
Multi-stage restrict deformation issue

### ISSUE THREAD

**Issue by VVanreusel** [poldracklab/fmriprep#1733]
Dear All,

We want do perform a coregistration where we want to restrict the deformation along the z-direction. We try the following code:

```
antsRegistration --dimensionality 3 --float 0 \
--interpolation Linear \
--winsorize-image-intensities [0.005,0.995] \
--use-histogram-matching 1 \
--transform Rigid[0.1] \
--metric MI[$imgs,1,32,Regular,0.25] \
--convergence [1000x500x250x100,1e-6,10] \
--shrink-factors 8x4x2x1 \
--smoothing-sigmas 3x2x1x0vox \
--restrict-deformation 0x0x1x1x1x0 \
--transform Affine[0.1] \
--metric MI[$imgs,1,32,Regular,0.25] \
--convergence [1000x500x250x100,1e-6,10] \
--shrink-factors 8x4x2x1 \
--smoothing-sigmas 3x2x1x0vox \
--restrict-deformation 1x1x1x1x1x1x0x0x0x1x1x0 \
-v \
--output [${nm},${nm}_EPI2T2Warped.nii.gz,${nm}_invEPI2T2Warped.nii.gz]
```

As I read somewhere that one should add the restrict-deformation command to each stage. 
If we run the code like this, no deformations are done in the z-direction, but the size of the brain is a lot larger than the one of the T2 we are coregistering it to:
 
![image](https://user-images.githubusercontent.com/42803559/63333609-07545e80-c33a-11e9-8e6f-2df4e974243a.png)

When we do only the rigid or only the affine (with restrict deformation) however, the deformation is also restricted in the z-direction as we want and the size of the deformed brain is similar as the T2 that we are warping it to.

 ![image](https://user-images.githubusercontent.com/42803559/63333405-b3497a00-c339-11e9-8bb4-0c48d374a124.png) 

Does anyone of you have an idea how to solve this?
Thank you in advance

**Comment by VVanreusel** [comment]
Masking did the trick.

**Comment by oesteban** [comment]
For questions regarding ANTS, I'd recommend posting to ANTsX/ANTs
