### ISSUE TITLE
Include confound plots in the reports

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#174]
To save space lets limit the confounds to the following line plots:
1. X, Y, Z, roll, pitch, yaw on one plot (mm on left axis, degrees on the right)
1. FD
1. Standardized DVARS
1. CompCorr (all components on one plot)
1. Grey, white, CSF, and global signal (all on one plot)

plot horizontal lines with: max, median and min

**Comment by effigies** [comment]
It would be nice to prioritize this for an upcoming release. Looking through some reports, mean EPI images only tell you so much.

And what about a carpet plot for each time series?

**Comment by chrisfilo** [comment]
Yeah - it would be good to get this in (ideally without making the reports much bigger).

The carpetplot would make more sense after we implement optional denoising schemes (so regressing out confounds instead of just estimating them).
