### ISSUE TITLE
How to use fmriprep optimally and efficiently according to the performance of my PC?

### ISSUE THREAD

**Issue by hao1ei** [poldracklab/fmriprep#1742]
Hi, 
I want to use fmriprep-docker on an ubuntu system (16 CPUs & 32G Memory). I have 1200+ participants and each participant have 5 functional task. 

The question I want to ask is: How do I configure the two parameters ‘--nthreads’ and '--omp-nthreads' to make these tasks done as quickly as possible. 

Any help would be greatly appreciated,
Hao

**Comment by effigies** [comment]
> I want to use fmriprep-docker on an ubuntu system (16 CPUs & 32G Memory)

The defaults should actually work pretty well for this configuration. With 16 cores the default `--nthreads` will be 16, and the default `--omp-nthreads` will be 8. You might run into some memory issues, though, as there are some tasks that are not very well annotated for memory. If that happens, you could try `--mem-gb 24` instead, to give yourself some breathing room.

We have set these defaults according to our experience that multithreaded jobs usually see diminishing performance gains at >8 threads. The `--nthreads` is simply there in case you want to use fewer cores than your system has available, which is mostly useful if you're working on an interactive system and don't want your GUIs grinding to a halt. I would strongly recommend against increasing `--nthreads` beyond the number of cores you have, as this is very likely to degrade performance beyond any gains you might get in using cores that are claimed but idle.

> I have 1200+ participants and each participant have 5 functional task.

I think this is a very ambitious task for a 16 core computer. Supposing you get 2-3 subjects a day fully processed (which seems reasonable, depending on the number of volumes of your functional runs), you're still looking at 400+ days of computation. If you don't run FreeSurfer, you might get up to ~10 subjects a day, which would still be 120+ days.

If you have or can obtain access to a cluster, that will be much better able to handle the workload you're looking at. Also, is this a large public dataset? It may be that somebody else has already run fMRIPrep on the data, and it would be a better use of resources to find that.

**Comment by hao1ei** [comment]
Many thanks. 
The advice you gave is very valuable, and made me understand the parallel working principle of fmriprep. Based on your estimated running time, I think I should switch to a high performance computing cluster to process these data. 
About this dataset, It is an unpublished longitudinal database (still in continuous acquisition) of children in China (will be public in the near future). This database mainly contains several task fMRI of basic cognitive assessments (attention, working memory, emotion and risk-taking decision).

**Comment by oesteban** [comment]
Please check #1737 and feel invited to contribute your findings back to fMRIPrep's documentation!

**Comment by oesteban** [comment]
Closing in favor of #1737.
