### ISSUE TITLE
Correlation plots are basically unreadable

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#1746]
The labels are too large to match the rows/columns they are attached to. One approach to consider is breaking it into chunks using black lines, and identifying the clusters, such as a/tCompCor, cosine basis, motion parameters. Then there could be enough room to help identify the order of the handful of gross signals (GS, CSF, WM) and summary confounds (FD, DVARS).

**Comment by effigies** [comment]
Oh, meant to link to a full-size report: http://datasets.datalad.org/labs/poldrack/ds003_fmriprep/sub-01.html

I'm guessing we were mostly looking at the dummy reports produced on Circle with a small TR count?

**Comment by oesteban** [comment]
Closed via #2252
