### ISSUE TITLE
participant_label option error when using fmriprep-docker

### ISSUE THREAD

**Issue by antotorov** [poldracklab/fmriprep#1748]
Running the following command

`fmriprep-docker --participant_label "001" "$BIDSROOT" "$OUTPUT" "participant"`

produces the following error:

`fmriprep: error: argument --participant_label/--participant-label: expected at least one argument`

Note that using using the following works just fine:

```
docker "run" -ti --rm \
  -v "$BIDSROOT:/data" \
  -v "$OUTPUT:/output" \
  -v "$FSHOME:/fs_home" \
  "poldracklab/fmriprep" \
  "/data" "/output" "participant" --fs-license-file "/fs_home/license.txt" --participant_label "001"
```
What am I missing?

**Comment by effigies** [comment]
Trying to put flagged arguments before the positional arguments (data, output and analysis level) can cause problems with the parser. Because `--participant-label` can take multiple arguments, there's inherent ambiguity to that argument string, and it seems that the parser interprets "001" as your data directory.

The following should work:

```
fmriprep-docker "$BIDSROOT" "$OUTPUT" participant --participant_label 001
```

**Comment by antotorov** [comment]
Hello,
Thanks, indeed in that case it works ! But adding multiple participants labels

>  --participant-label="001 002"

gives me the error

> Could not find data for participant(s): "001 002"

Running separately with 002 alone works well.
I tried escaping double quotes, and/or putting the whole list into single quotes, but nothing seems to make it happy. Any ideas?

**Comment by effigies** [comment]
Don't use quotes. Just use `--participant-label 001 002`.

**Comment by antotorov** [comment]
Ok it works, thanks!
