### ISSUE TITLE
Can fMRIPrep continue to run after encounter an error?

### ISSUE THREAD

**Issue by hao1ei** [poldracklab/fmriprep#1756]
Due to the limitation of the cluster storage space, my fMRIPrep exited after reporting an error (Disk quota exceeded). After I applied for more space, can I continue to run it? Because my data is very large, it is too cruel to start again.

**Comment by effigies** [comment]
If you still have the same working directory (specified with the `-w` flag), fMRIPrep will resume where it left off.

**Comment by hao1ei** [comment]
Got it, thank you very much ~
