### ISSUE TITLE
Reporting framework

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#176]
![image](https://cloud.githubusercontent.com/assets/238759/20120656/8b5df634-a5c2-11e6-866f-1d1146a3bebb.png)

Self-contained reports (`reportlets`) - html generation functions built into interfaces (such as AntsRegistration, BET etc.)

InputSpec mixin
`generate_report` - Boolean

OutputSpec mixin
`html_report` - File

Interface mixin
`_generate_report()`

Report aggregator:
- Takes two inputs: list of headers (["T1w preprocessing", "task: N-back, run: 0 preprocessing"]) and a list of lists of reportlets (html files).
- Concatenates all reportlets prefixing each list with a header.
- Outputs a single HTML file.

In the functional workflow:
- aggregate all reportlets from each workflows using a Merge node
- generate section header using the input file

Before feeding to the aggregator:
- aggregate lists of reportlets from all tasks/runs using a [JoinNode](http://nipype.readthedocs.io/en/latest/users/joinnode_and_itersource.html); do the same for section headers; `itersource` should be set tot `epi` (see: https://github.com/poldracklab/fmriprep/blob/78424b0facc2a102e75d87c828574e22fbb5b66e/fmriprep/workflows/base.py#L83)
- combine with the list of reportlets from the anatomical workflow; add a header for it

If this works well we will merge this into Nipype master.

**Comment by rwblair** [comment]
Will need to add the overloaded input/output specs and interfaces to niworkflows and update imports accordingly.

**Comment by oesteban** [comment]
@rwblair - actually, that is potentially the best entry point for us to implement and test this. niworkflows is still very small, we can set very simple smoke tests, etc.

**Comment by shoshber** [comment]
Moved to niworkflows
