### ISSUE TITLE
Raise warning/error if working directory is a subdirectory of BIDS root

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#1760]
This is almost guaranteed to cause problems, so perhaps it should be made an error.

Related #1738, #1758.

**Comment by oesteban** [comment]
We already have this for the output directory:

https://github.com/poldracklab/fmriprep/blob/2ee97230e54fa9e13bd801208a5f8d2c777bf520/fmriprep/cli/run.py#L532-L538

Labeling this as a low hanging fruit

**Comment by dmd** [comment]
Presumably it's ok to have the working directory be a subdirectory of BIDS root if it's excluded in `.bidsignore`?

**Comment by effigies** [comment]
No. `.bidsignore` is specifically a BIDS validator feature that pybids does not parse, although we can pass directories to ignore to pybids. So that would be another option. Although writing data into a source directory feels somewhat sketchy; I personally prefer to keep my source data in a separate, read-only directory, to reduce the chance of software bugs corrupting the data.

**Comment by bbfrederick** [comment]
Should we also prohibit putting “derivatives” in the source directory for the same reason?  IIRC there was some discussion a while back about bids validation hanging as it walked the derivatives tree.

**Comment by effigies** [comment]
If it's in the subdirectory `<bids root>/derivatives/`, then it will not be indexed, because that directory has a meaning in BIDS, and pybids knows not to index it.
