### ISSUE TITLE
Clear indication of completion and status

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#1763]
It's not as obvious as it should be whether fMRIPrep finished successfully or not.

Perhaps a quick summary:

* X subjects successfully run
* Y errors encountered

And some flagging characters, such as `*******[...]`, to make sure people see it.

**Comment by dmd** [comment]
Is there currently *any* way to determine if fmriprep has stopped processing? A file that does or does not exist, perhaps?

**Comment by effigies** [comment]
The HTML reports are written at the end. That's probably the best indicator at the moment.

**Comment by oesteban** [comment]
There is this https://github.com/poldracklab/fmriprep/blob/4cb3385ec8389ff62fbd375385a7c03327f523f3/fmriprep/cli/run.py#L404

**Comment by dmd** [comment]
When might that start appearing?

**Comment by oesteban** [comment]
That's been there for long. Not sure why it doesn't really show up. But it is probably working because we are identifying about 60% of the runs as successful in sentry (and that means this line must be hit at some point).

We'll look into this - it could be that you only see it if you are running with `--notrack`.

**Comment by dmd** [comment]
In the 312 fmriprep jobs we've "successfully' run so far, we've seen it 0 times. 

I'd love to see something even more explicit like I mentioned in #1922 someday.

**Comment by effigies** [comment]
It might need a `-v` or `-vv`.

**Comment by oesteban** [comment]
While working on the config file, it seems that for some reason the level of the `'cli'` log is modified, or the log is shut down at some point.

Long story short, writing that log entry into the `workflows` log made it show up in my tests.

Should be a really easy fix.
