### ISSUE TITLE
How to get information of transformation from structural to functional space in fmriprep?

### ISSUE THREAD

**Issue by xj2019** [poldracklab/fmriprep#1765]
Dear all,
I would like to use FSL FIX on the data preprocessed by fmriprep. However, the information of transformation from structural to functional space is necessary. Therefore, I would like to ask if anyone knows how to get the information.
Any help would be appreciated. Thank you a lot!

**Comment by effigies** [comment]
What do you mean by functional space, in this context?

**Comment by xj2019** [comment]
Sorry for my unclear discription. It needs a file of "FLIRT transfom from structural to functional space".
I understand is as a matrix of Affine transformation that registers T1 image to functional data. 

I found a "registration.lta" file in "work/fmriprep_wf/.../func_preproc)task_wf/bold_reg_wf/bbreg_wf/mri_coreg/". If this is the one includes the information:
1. Shall I inverse the 1st matrix in that file for the information? 
2. Is it the tramsformation into the MNI space?

Please let me know if I do not clearly discribe my question. Thank you for your help.

**Comment by effigies** [comment]
Sorry, I wasn't clear. What image are you trying to put a structural in alignment with? If it's the preprocessed BOLD series in T1w space, they are already in alignment, and you only need an identity matrix:

```
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1
```

If you're trying to get back to the `boldref` file, which will be roughly in alignment with the first couple volumes of the original BOLD series, then we'll need to find that transform in the working directory, as I don't think we currently output it.

**Comment by xj2019** [comment]
Thank you :)
