### ISSUE TITLE
Carpet plots issue

### ISSUE THREAD

**Issue by TMaksym** [poldracklab/fmriprep#1773]
Dear all,

There is a question related to the carpet plots produced by fmriprep. I've run the pipeline for all the subjects together without any errors. However, the carpet plots for several subjects look strange as the number of voxels differs significantly from run to run. When I reran the analyses for these subjects the carpet plots looked more reasonable (i.e., the number of voxels seems similar in all runs for a given subject). What might be a possible reason for this? 

The command which I used:
$ fmriprep-docker   $PWD/data/PROJECT/fMRI_task/   $PWD/data/PROJECT/fMRI_task/derivatives/   --participant_label 01 02 03 04 05 06  --n_cpus 16  -v  --use-aroma   --fs-license-file  $PWD/data/license.txt   --fs-no-reconall   -w  $PWD/data/PROJECT/fmriprep_tmp/

Python version: 2.7.12  
Docker Engine version: 19.03.2

Here, I attached the carpet plots of three runs from one subject. 

![sub-05_task-nback_run-1_desc-carpetplot_bold](https://user-images.githubusercontent.com/27223487/64861636-1678b480-d639-11e9-9489-7186ec7a695b.png)
![sub-05_task-nback_run-2_desc-carpetplot_bold](https://user-images.githubusercontent.com/27223487/64861640-1c6e9580-d639-11e9-9609-bd646b54d549.png)
![sub-05_task-nback_run-3_desc-carpetplot_bold](https://user-images.githubusercontent.com/27223487/64861644-1f698600-d639-11e9-8459-b03165237562.png)

Regards,
Maksym

**Comment by effigies** [comment]
I believe we display all gray-matter voxels, so if there are differences in the size of your gray-matter masks or the size of your voxels, that could produce effects like this.

**Comment by TMaksym** [comment]
Thank you for response. 
I reanalyzed the same subject. However now they plots looked fine

The command which I used:
$ fmriprep-docker $PWD/data/PROJECT/fMRI_task/ $PWD/data/PROJECT/fMRI_task/derivatives/ --participant_label 05  --n_cpus 16 -v --use-aroma --fs-license-file $PWD/data/license.txt --fs-no-reconall -w $PWD/data/PROJECT/fmriprep_tmp/

Here are the carpet pots from a second analysis (the subject is the I same that I posted above):

sub-05_task-nback_run-01_desc-carpetplot_bold](https://user-images.githubusercontent.com/27223487/64865657-7d4e9b80-d642-11e9-8e04-fc31291654e4.png)
![sub-05_task-nback_run-02_desc-carpetplot_bold](https://user-images.githubusercontent.com/27223487/64865666-80e22280-d642-11e9-833d-38fa85381994.png)
![sub-05_task-nback_run-03_desc-carpetplot_bold](https://user-images.githubusercontent.com/27223487/64865679-8475a980-d642-11e9-9581-ebf7d51f9701.png)


I still cannot get why the results are so different between two analyses.

Regards,
Maksym

**Comment by effigies** [comment]
It's possible there was a strange rendering issue related to the graphics library that only happened on the first run. The content of the plots looks similar before and after, just the scaling seems different.

**Comment by oesteban** [comment]
Since it seems to be fixed for now, I'll close this issue. Please do not hesitate to open if the problem regresses.
