### ISSUE TITLE
First level modeling with multiple runs ?

### ISSUE THREAD

**Issue by hao1ei** [poldracklab/fmriprep#1775]
Hello, 

This is my first time using fsl. I understand the first level modeling process of fsl by reading this script: https://github.com/poldrack/fmri-analysis-vm/blob/master/analysis/postFMRIPREPmodelling/First%20and%20Second%20Level%20Modeling%20(FSL).ipynb

However, my experiment has multiple runs. How does that work? 
The notebook above only have 1 run , and there is nothing about dealing with multiple runs. 

Any help would be greatly appreciated,
Lei

**Comment by oesteban** [comment]
Hi Lei, this is not a question about fMRIPrep, please post it in https://neurostars.org where it'll more findable and exposed to more experts. Just to give you a hint of how it works, you'll need to add one subject-level analysis between run-level and group-level analysis. Cheers.
