### ISSUE TITLE
Artefact on processed BOLD series

### ISSUE THREAD

**Issue by antotorov** [poldracklab/fmriprep#1776]
Hello,
After I ran fmriprep on my functional images I got a time-series with some artifact:

![Screenshot 2019-09-16 16 07 31](https://user-images.githubusercontent.com/53940822/64964848-378d0f80-d89c-11e9-9a25-e8486651c49c.png)

This is present only for some volumes (and there's nothing weird on the original time-series). I first suspected an error related to time-slicing, so I launched the pipeline removing the slice-timing data, but the artifact remains.

I suspect something goes wrong with head-motion correction (it seems the subject moved his eyes quite a lot - maybe this has an effect on the correction?) but I'm not sure.

Thanks for your help

Best

**Comment by effigies** [comment]
These could correspond to points of relatively high motion. Have you checked your motion parameters?

**Comment by antotorov** [comment]
Thanks for your answer. It seems indeed that the subject moved quite a lot. At any rate this is definitely not an issue with fmriprep as I get the same artifact when using SPM for motion-correction.
Best
