### ISSUE TITLE
fmriprep : multi echo data processing - numpy version too old?

### ISSUE THREAD

**Issue by sameera2004** [poldracklab/fmriprep#1782]
Hi,

I am getting TypeError: must be real number, not NoneType. Here I am attaching the .html file created by fmriprep pre processing. 
[sub-13023.html.txt](https://github.com/poldracklab/fmriprep/files/3631760/sub-13023.html.txt)

Does anyone seen this error before? Does anyone know how to fix this issue?
Thanks

**Comment by tsalo** [comment]
We saw this error within tedana [here](https://github.com/ME-ICA/tedana/issues/141#issue-370839839). Our solution was to update numpy. Did you run fMRIPrep from a container or as a library?

**Comment by sameera2004** [comment]
Hi @tsalo,
Thank you for the comment.

 I am using our university cluster to run fMRIprep. I requested them to install fMRIprep for our group. They manually installed the libraries and prepared the environment.

So the tedana is creating the issue, that's why I don't get it when I process single-echo data. This analysis taken very long time to run. I got this error after ~10hrs, I see that it finished processing structural data.

 I will ask them to update numpy and let you know about the outcome.

**Comment by sameera2004** [comment]
Sure, I already requested them to update numpy.

**Comment by oesteban** [comment]
I'm going to remove the FSL versioning from the title as it can be confusing.

**Comment by sameera2004** [comment]
Sure, Thanks @oesteban

**Comment by sameera2004** [comment]
Hi @tsalo and @oesteban,

After numpy update, I was able to run fmriprep without any errors and get the outputs. Thank you so much. 
 
Sameera

**Comment by oesteban** [comment]
Thanks @tsalo for the prompt and accurate support, and thanks @sameera2004 for your patience. Glad to hear that.
