### ISSUE TITLE
N4BiasFieldCorrection doesn't work properly for some BOLD brain masks, resulting in T-CompCor errors

### ISSUE THREAD

**Issue by lukassnoek** [poldracklab/fmriprep#1785]
When preprocessing several large MRI datasets using Fmriprep 1.4.2, I noticed that it crashed at the T-CompCor stage for some runs (not all!) for about 5% of the subjects, with the error `IndexError: cannot do a non-empty take from an empty axes.` (this may be related to #1697 and #1409, and perhaps #900). 

After checking the outputs of the pipeline one by one (backtracking from the T-CompCor step), I found out that, at least for my data, things go wrong at the `N4BiasFieldCorrection` of the BOLD reference (in the `enhance_and_skullstrip_bold_wf` workflow). After bias correction of the `ref_bold.nii.gz` file, the output (`ref_bold_corrected.nii.gz`) looks as follows:

![image](https://user-images.githubusercontent.com/6350135/65512264-287c1200-ded9-11e9-93f9-dc760fb048ff.png)

This is not due to issues with the registered brain mask (`tpl-MNI152NLin2009cAsym_res-02_desc-brain_mask_trans_dil_hdr.nii.gz`) or the actual `ref_bold.nii.gz` itself (both look fine). Note that in runs that *do not* crash at this stage, the output of the bias correction step (i.e., `ref_bold_corrected.nii.gz`) looks fine. It seems that this happens somewhat randomly - some scans crash at this stage, others don't (within a particular subject).

I noticed, though, that removing the `--bspline-fitting [ 200 ]` argument fixes this issue, i.e., the `ref_bold_corrected.nii.gz` looks fine.

Would it be an idea to add a flag to Fmriprep to turn this option (bspline-fitting) off?

**Comment by effigies** [comment]
This should be fixed in 1.5.0. Can you try rerunning with that?

Related issues: poldracklab/niworkflows#388 poldracklab/niworkflows#389 #1750 #1752

**Comment by lukassnoek** [comment]
It does! Thanks for the tip.
