### ISSUE TITLE
Docker: consider moving to poldracklab/neuroimaging-core:freesurfer-0.0.2

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#179]
That docker image is better maintained and it is versioned. The current base image oesteban/crn_nipype:freesurfer is kind of stale (and too heavy).

That said, it should still work, although it is making it difficult for CircleCI to build in #178.

For reference, we can use the Dockerfile of niworkflows. On top of poldracklab/neuroimaging-core:freesurfer-0.0.2 we should just install conda.

**Comment by oesteban** [comment]
Note - this is not urgent, we can address it after the BEAST sprint.

**Comment by oesteban** [comment]
For a reference on how the new dockerfile would look like, we have niworkflows https://github.com/oesteban/niworkflows/blob/master/Dockerfile

**Comment by chrisfilo** [comment]
Superseded by #273
