### ISSUE TITLE
ICA-AROMA for the further analysis

### ISSUE THREAD

**Issue by yuan0821** [poldracklab/fmriprep#1799]
I am a newer user for fmriprep . Now I finished the preprocessing using the comm of --use-aroma --use-syn-sdc. And I get the files like 'sub-003_ses-01_task-rest_run-001_space-MNI152NLin2009cAsym_desc-smoothAROMAnonaggr_bold.nii.gz'. 

1. I wonder if this **'smoothAROMAnonaggr**' file has been regressed out the effect of motion, CSF,WM and Global signal. If so, can I use this file to perform bass-pass filter (0.01-0.1 HZ for the resting state) and functional connectivity analysis?  
2. After functional connectivity, If I wan to perform group analysis, should I consider the motion effect and put the meanFD into the EV and regressed out. Is it right? 
Thank you very much for any help.
@chrisgorgo

**Comment by jdkent** [comment]
Hi and thanks for reaching out.

1. `smoothAROMAnonaggr` has only spatial smoothing and the AROMA noise components "non-aggressively" removed.  you can see [this post for more details on potential regressor strategies](https://neurostars.org/t/fmriprep-ica-aroma-filtering-including-wm-csf-etc-confounds-in-fsl-regfilt/3137)

2. If I understand correctly, I do often include the meanFD in my between participant models to account for overall motion differences, but I do not have a paper offhand to justify this behavior.

**Comment by effigies** [comment]
Hi @yuan0821. I would also recommend going to Neurostars for advice on analysis choices. The fMRIPrep issues are generally for bugs and clarifications in fMRIPrep operation.

I believe your first question was part of https://github.com/poldracklab/fmriprep/issues/817#issuecomment-535785256? Do you need further clarification?

**Comment by yuan0821** [comment]
Thank you very much for your advice. I need to confirm now whether it is appropriate for me to do this.
**smoothAROMAnonaggrs** just do spatial smoothing and motion correction, right?
If I use a **smoothAROMAnonaggrs** file for functional connection analysis, it means that I need to regress the CSF/WM components and aroma_motion components(from **confounds_regressors.tsv).** Then perform the bass-pass filter. Finally, when doing a group-level comparison, use the mean FD as a covariable
Thanks again for your kind help. @jdkent @effigies

**Comment by effigies** [comment]
> **smoothAROMAnonaggrs** just do spatial smoothing and motion correction, right?

And AROMA non-aggressive denoising.

> If I use a **smoothAROMAnonaggrs** file for functional connection analysis, it means that I need to regress the CSF/WM components and aroma_motion components(from **confounds_regressors.tsv).**

No, this would be invalid. CSF/WM components are calculated on the non-denoised dataset, and those regressors do not properly apply. And the AROMA components will have already been removed (according to the non-aggressive strategy).

> Then perform the bass-pass filter. Finally, when doing a group-level comparison, use the mean FD as a covariable

I don't have enough experience to give advice here.

---

Note that this is the same as https://neurostars.org/t/ica-aroma-for-the-further-analysis/5144. Please choose one forum or the other to post questions, rather than both.

**Comment by oesteban** [comment]
> Note that this is the same as https://neurostars.org/t/ica-aroma-for-the-further-analysis/5144. Please choose one forum or the other to post questions, rather than both.

Totally agreed, let's follow up there as it will have more visibility :+1:

**Comment by yuan0821** [comment]
Thank you very much!!!
I just read the paper 'ICA-AROMA: A robust ICA-based strategy for removing motion artifacts
from fMRI data'. So as my understanding, **smoothAROMAnonaggrs** is a file that motion noise components have been removed. But WM, CSF... components have not been regressed out but just extract their time series, right?? If so, I should do 
1. nuisance regression for CSF, WM...(using comm fsl_glm -i smoothAROMAnonaggrs.nii.gz -d design_with_nuisance.mat --out_res= nuisance_smoothAROMAnonaggrs.nii.gz);

2. bandpass (using comm:  fslmaths nuisance_smoothAROMAnonaggrs.nii.gz -bptf <hp_sigma> <lp_sigma> filtered_nuisance_smoothAROMAnonaggrs.nii.gz filter)??

I appreciate any suggestions you @effigies give. Thank you very much.

**Comment by effigies** [comment]
The time series of WM CSF have not been calculated from the AROMA-denoised BOLD series. Regressing them out is probably not valid.

Regarding bandpass filtering, I have no experience with that. I would recommend asking about bandpass filtering WRT AROMA on Neurostars, where there are contributors with much more experience.
