### ISSUE TITLE
Bad bold-derived brain mask

### ISSUE THREAD

**Issue by antotorov** [poldracklab/fmriprep#1805]
Running fmriprep 1.5.0rc1 on a cohort of 50 subjects, I got the following problem for only one subject: the mask obtained from the bold images is terribly wrong:

![Screenshot 2019-10-03 13 29 44](https://user-images.githubusercontent.com/53940822/66123360-12a9d380-e5e2-11e9-890c-6ba9f91312c4.png)

The log mentions an error at the node

> fmriprep_wf.single_subject_014_wf.func_preproc_task_gas_wf.bold_confounds_wf.tcompcor

The error contain 

> IndexError: cannot do a non-empty take from an empty axes.

This is similar to #1785, except it should be fixed in 1.5.0.

In the report the images show a very strong inhomogeneity located (partially) on the region covered by the mask:

![Screenshot 2019-10-03 13 16 30](https://user-images.githubusercontent.com/53940822/66124467-beecb980-e5e4-11e9-9020-8926a619c043.png)

I don't understand where those inhomogeneities comes from, in particular there is nothing suspect in the reproc_bold images produced by fmriprep (this is the background image I used in the first screenshot, and moving around through space and volumes doesn't reveal anything).

Any idea?

**Comment by oesteban** [comment]
Hi @antotorov, please note 1.5.0rc1 means "release candidate 1" (which means 1.5.0rc1 is actually prior to 1.5.0). I've checked the change log and 1.5.0rc1 does not contain #1752 (which is the PR where this was addressed).

Could you upgrade to 1.5.0 and check again?

**Comment by antotorov** [comment]
Okay, I launched 1.5.0 as soon as I read your answer. It just finished and the problem disappeared!
Thanks!
