### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'outputs'

### ISSUE THREAD

**Issue by xuyangwen** [poldracklab/fmriprep#1807]
Hello,

I am running one subject through fmriprep 1.5.0.

An error comes again and again for the data of each acquisition:

```
Error while checking node hash, forcing re-run. Although this error may not prevent the workflow from running, it could indicate a major problem. Please report a new issue at https://github.com/nipy/nipype/issues adding the following information:

	Node: fmriprep_wf.single_subject_02_wf.func_preproc_task_intactArgumentative2_wf.bold_bold_trans_wf.bold_transform
	Interface: niworkflows.interfaces.itk.MultiApplyTransforms
	Traceback:
Traceback (most recent call last):

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/base.py", line 337, in _local_hash_check
    cached, updated = self.procs[jobid].is_cached()

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 297, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 494, in _get_hashval
    self._get_inputs()

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 521, in _get_inputs
    outputs = _load_resultfile(results_file)[0].outputs

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 311, in load_resultfile
    if resolve and result.outputs:

AttributeError: 'NoneType' object has no attribute 'outputs'
```

Does anybody know how to solve this?

Thanks!

**Comment by effigies** [comment]
Hi, apologies for this issue. This is related to a bug in one of our upstream dependencies. When it releases (which should be soon), we can make a new release of fMRIPrep, and this should be resolved, then.

**Comment by xuyangwen** [comment]
> 
> 
> Hi, apologies for this issue. This is related to a bug in one of our upstream dependencies. When it releases (which should be soon), we can make a new release of fMRIPrep, and this should be resolved, then.

Thank you! But I guess it will not affect the results if it can continue running till the end of the pipeline? or I need to wait till the new release?

**Comment by effigies** [comment]
I'm going to try to have a release of both by tomorrow. I would [recommend](https://fmriprep.readthedocs.io/en/stable/faq.html#a-new-version-of-fmriprep-has-been-published-when-should-i-upgrade) waiting to run all of your data with a good release.

**Comment by xuyangwen** [comment]
> 
> 
> I'm going to try to have a release of both by tomorrow. I would [recommend](https://fmriprep.readthedocs.io/en/stable/faq.html#a-new-version-of-fmriprep-has-been-published-when-should-i-upgrade) waiting to run all of your data with a good release.

Looking forward to it.

**Comment by oesteban** [comment]
@xuyangwen That is usually a WARNING - although pretty annoying, your preprocessing should've finished successfully. Could you check on that?

There is a variant of this error (which is not what you posted) that does crash fmriprep. You could've experienced those too.

**Comment by xuyangwen** [comment]
> 
> 
> @xuyangwen That is usually a WARNING - although pretty annoying, your preprocessing should've finished successfully. Could you check on that?
> 
> There is a variant of this error (which is not what you posted) that does crash fmriprep. You could've experienced those too.

Yes. It is a warning. It could be finished successfully. My preprocessing crashes because of another error. This error does not occur in the log folder.

**Comment by xuyangwen** [comment]
> @xuyangwen That is usually a WARNING - although pretty annoying, your preprocessing should've finished successfully. Could you check on that?
> 

@oesteban 
I saw this "AttributeError: 'NoneType' object has no attribute 'outputs'" again (maybe not totally the same). But this time, it crashes, and no surface files are generated. See the log information below:

```
Node: fmriprep_wf.single_subject_04_wf.func_preproc_task_scrambledNarrative2_wf.bold_surf_wf.rename_src
Working directory: /scratch/fmriprep_wf/single_subject_04_wf/func_preproc_task_scrambledNarrative2_wf/bold_surf_wf/rename_src

Node inputs:

format_string = %(subject)s
in_file = <undefined>
keep_ext = True
parse_string = <undefined>
subject = ['fsaverage5']
use_fullpath = False

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 269, in _send_procs_to_workers
    num_subnodes = self.procs[jobid].num_subnodes()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 1204, in num_subnodes
    self._get_inputs()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 1219, in _get_inputs
    super(MapNode, self)._get_inputs()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 521, in _get_inputs
    outputs = _load_resultfile(results_file)[0].outputs
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 311, in load_resultfile
    if resolve and result.outputs:
AttributeError: 'NoneType' object has no attribute 'outputs'
```

**Comment by oesteban** [comment]
Two questions:
- Can you replicate? (i.e., if you re-run fMRIPrep, does it crash again at the same point?)
- If you can replicate, does version 1.5.1rc1 (released just yesterday) improve things?

**Comment by xuyangwen** [comment]
> Two questions:
> 
> * Can you replicate? (i.e., if you re-run fMRIPrep, does it crash again at the same point?)
> * If you can replicate, does version 1.5.1rc1 (released just yesterday) improve things?

Sorry for the reply. I tried again just for this participant still using 1.50. It works this time. I think this error might result from the conflict of other computation processes. Thanks!
