### ISSUE TITLE
Update CONTRIBUTING.md from dMRIPrep?

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1808]
Probably of particular interest to @emdupre, @ariveradompenciel and @jdkent who have worked on the contributor guidelines in the past.

We've been doing some work on the [`CONTRIBUTING.md` file of *dMRIPrep*](https://github.com/nipreps/dmriprep/blob/master/CONTRIBUTING.md), which was initially based on the fMRIPrep's one.

But now I believe we could feed in the reversed directions. In particular:
- The Impostor's syndrome disclaimer
- The revised git workflow (includes creating a branch to work on PR)
- The description of the `impact:*` and `effort:*` issue labels.
- Finally, the description of _creators_ and _contributors_ (names match Zenodo's available roles) should probably need more adaptations but could be helpful to define more clearly the role of people who want to be kept in the core and others who prefer to see things happening and chime in for particular topics they are interested in. Anyway, a more explicit statement about how authorship and publications will be handled would be nice to have.

WDYT?

**Comment by emdupre** [comment]
This looks fantastic :heart_eyes: I'm very much :+1: on bringing in some of these changes.

Let me know if there's anything I can do to help !

**Comment by jdkent** [comment]
I'm on the same page as @emdupre, this looks great (going to have to port this to my projects as well).

I like seeing the explicit rules for publications, on first pass they all look reasonable, would posters fall under the same guidelines? (excluding the recommendation to post to a preprint server)

**Comment by ariveradompenciel** [comment]
Also agree, looks good! Let me know how I can help as well.

**Comment by oesteban** [comment]
> I like seeing the explicit rules for publications, on first pass they all look reasonable, would posters fall under the same guidelines? (excluding the recommendation to post to a preprint server)

We've been pretty liberal as regards posters and abstracts because pulling together these many people seems to be a block for actually submitting these kinds of work. It's better to disseminate fMRIPrep although sometimes the author list should've been more inclusive. Happy to chat about this and have something written down to clarify.
