### ISSUE TITLE
Conversions of AROMA-denoised data are generated in spaces other than MNI152NLin6Asym

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1816]
This should not be happening - actually #1255 addresses this feature, but at this moment this is a bug.

**Comment by divyanganar** [comment]
Does this mean files with the name 2009c and AROMAnonaggr should not be used? I used 1.3.2 a while ago and had outputs with this name ```task-rest_space-MNI152NLin2009cAsym_desc-smoothAROMAnonaggr_bold.nii.gz```
