### ISSUE TITLE
How to export IGES/STEP from Surface ?

### ISSUE THREAD

**Issue by selvakarna** [poldracklab/fmriprep#1822]
How to export IGES/STEP from Surface ?

**Comment by oesteban** [comment]
What is IGES/STEP? What is _Surface_ in this context?

I'm guessing you need to convert fMRIPrep output surfaces (in GIFTI format) to some other formats. Unfortunately, I don't think we know anything about IGES/STEP.

If you have a very clear use-case in mind, please reopen this issue including additional details.
