### ISSUE TITLE
Issues creating a 2mm template of the 2009 Asym standard image

### ISSUE THREAD

**Issue by hpfisher3** [poldracklab/fmriprep#1824]
Hello,

I am analyzing fmriprep outputs in fsl Feat, but I need a 2mm template because that's the output image resampling we chose. When I resample the 1mm template that is used by fmriprep, the voxel dimensions do not match (functional images are 91x109x91 and the template is 98x116x94). Why are these different and how do I fix it? I could use 3dresample and set the -master flag to one of my functional images, but that seems biased toward whatever image I choose. 

Best,
- Harris

**Comment by oesteban** [comment]
https://fmriprep.readthedocs.io/en/latest/spaces.html

Please, point out those sections of the documentation that need further clarification

**Comment by oesteban** [comment]
Please reopen if the documentation was not sufficient to achieve your goals. Thanks!
