### ISSUE TITLE
Update connection names from sMRIPrep's ``anat_preproc_wf``

### ISSUE THREAD

**Issue by adelavega** [poldracklab/fmriprep#1825]
A recent PR in `smriprep` breaks connections between the anat and func preproc wfs:
https://github.com/poldracklab/smriprep/pull/108

Here:
https://github.com/poldracklab/fmriprep/blob/2c0a8b39af4fac7416ce5d242c45f86e4a195b91/fmriprep/workflows/base.py#L624

Should be an easy fix, I can submit a PR.

**Comment by oesteban** [comment]
As long as we do not release another patch release of 0.3.x, this should not be a problem. I have updated the title. Thanks for reporting!

**Comment by oesteban** [comment]
PR has been merged. Not an issue anymore! Thanks Alejandro.
