### ISSUE TITLE
Strategies for alignment to T1 for small EPI slabs

### ISSUE THREAD

**Issue by JWinawer** [poldracklab/fmriprep#1842]
Dear All,

We use fMRIprep for a number of our studies.  While it usually works quite well, we have found a problem in one study. This study uses a small FOV for EPIs (in the slice dimension). From the same session, some of the EPIs, all of which are coronal, get correctly aligned to the T1, but many are way off (eg rotated 150 to 200 deg around an R-L axis).

In contrast, our [home-brewed pre-processing tool ](https://github.com/WinawerLab/MRI_tools/blob/master/preprocessing/prisma_preproc.py)(written by @sfavila and @billbrod), which takes a different alignment strategy, works fine. The strategy in that tool is:

In addition to unwarping the EPIs using distortion scans, we also unwarp the distortion scan itself. We then compute the alignment between the distortion scan and the T1, rather than the EPIs and the T1. This works better than aligning the EPIs to the T1 because the distortion scan is spin echo and has  better quality. We then compute the alignment of each EPI to the distortion scan. This works better than aligning the EPI to the T1 because the EPIs and the distortion scans have the identical acquisition volume. (We save out the alignment matrices, and then only apply a single resampling).

So the question is, is there any way to implement this alignment strategy in fMRIprep? Specifically, to align each EPI to the (unwarped) distortion scan, and to then align the (unwarped) distortion scan to  the whole-brain T1? 

Thanks
Jon

**Comment by effigies** [comment]
Hi, thanks a lot for this question. Limited-FoV is definitely an issue that fMRIPrep has not found a good general solution for, so I'm glad to see you've also been thinking about this.

This doesn't sound very far out of line with what we do. We currently find some reference image to use as stand-in for the BOLD series, whether that's an sbref, dummy scans at the start of the BOLD series, or motion-corrected and averaged first 20 (or so) scans. This is the target of HMC, the object of SDC correction, and the SDC-corrected boldref is the object of BOLD-T1w registration. Similarly, every EPI volume is sampled to the target space in a single resampling.

If I'm reading this correctly, you currently replace the boldref with the reverse-PE EPI, post-SDC correction, for both HMC and coregistration. That seems pretty doable. It would result in a bit of reordering some operations, but the overall structure of the workflow would be minimally affected.

One question is whether the reverse-PE EPI is a better (or equivalent) target of motion correction as opposed to the boldref, as we calculate it. My intuition would have been that the original boldref would have been better, as all of the scan parameters are identical, but I can see an argument that the limited FoV would produce a bias toward too-low motion estimates. Curious if you have any data, here.

Anyway, I think this is definitely something worth trying. Would you be interested in contributing code?

**Comment by pvelasco** [comment]
> If I'm reading this correctly, you currently replace the boldref with the reverse-PE EPI, post-SDC correction, for both HMC and coregistration. That seems pretty doable. It would result in a bit of reordering some operations, but the overall structure of the workflow would be minimally affected.

I think @JWinawer uses the Spin-Echo EPI with the same PE polarity as the bold EPIs for boldref.

In my experience, the SE EPIs have better gray/white contrast than the EPIs, so they are better candidates for the EPI-to-T1 registration.  However, since they don't have as much dropout as the bold EPIs, you have to be careful with the boldEPI-to-SEEPI registration.

**Comment by JWinawer** [comment]
Yes we use the SE EPI. We acquire both same- and reverse-polarity
Phase-encode spin-echo EPIs (3 volumes of each). We unwarp these and then
average all 6 images so that we have a single merged and unwarped SE
reference, which we align to the whole-brain t1-weighted anatomy. We then
align the single band reference image from the first BOLD EPI scan (the one
closest in time to the distortion scan) to the merged and unwarped SE.
Finally,  we co-register all the EPI volumes from that scan and subsequent
scans to the SBref from the first BOLD scan.

T1-> Unwarped SE -> unwarped SB ref from 1st BOLD EPI -> all EPI volumes
from all scans

@sfavila: let me know if I got any of this wrong.

Jon

On Fri, Oct 25, 2019 at 15:59 pvelasco <notifications@github.com> wrote:

> If I'm reading this correctly, you currently replace the boldref with the
> reverse-PE EPI, post-SDC correction, for both HMC and coregistration. That
> seems pretty doable. It would result in a bit of reordering some
> operations, but the overall structure of the workflow would be minimally
> affected.
>
> I think @JWinawer
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JWinawer&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=EWkH5YBN_iCbpisdK_0ZyMnwsR8PFQ6pd2FDdGBj0Ks&s=40B8v1pyQwhqgfsuDBmtSzTfxpPWjuOAz3F1dcqI5MM&e=>
> uses the Spin-Echo EPI with the same PE polarity as the bold EPIs for
> boldref.
>
> In my experience, the SE EPIs have better gray/white contrast than the
> EPIs, so they are better candidates for the EPI-to-T1 registration.
> However, since they don't have as much dropout as the bold EPIs, you have
> to be careful with the boldEPI-to-SEEPI registration.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_poldracklab_fmriprep_issues_1842-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAAQFPXWAKHBCLRB2BGLV5ZLQQNFZHA5CNFSM4JFG6Z5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECJM42I-23issuecomment-2D546492009&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=EWkH5YBN_iCbpisdK_0ZyMnwsR8PFQ6pd2FDdGBj0Ks&s=1o5vLmRicVc7jfN5EuKvJ3Y_GJ2Y7XYxVIBjUO9-rJ0&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAQFPXU4CTOFWNOJAOKSTWTQQNFZHANCNFSM4JFG6Z5A&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=EWkH5YBN_iCbpisdK_0ZyMnwsR8PFQ6pd2FDdGBj0Ks&s=IchodAYBqvwfrTDDIyrqOgTJNnTASOLWy9daKnXNgTI&e=>
> .
>
-- 
Sent from Gmail Mobile

**Comment by irisgroen** [comment]
We have done some further testing in @winawerlab lab and think we might have a solution to improve partial volume registration in fmriprep: provide the option to initialize registration using the header info, i.e. passing inputflags '--regheader' to mri_convert, and '--init-header' to bbregister.

As far as I can see the current registration workflows in fmriprep don't use these inputs. Below is one of our "bad" registrations created by running: 

```
bbregister --t2 --6 \
           --lta /Users/winawerlab/Desktop/scratch/work/fmriprep_wf/single_subject_wlsubj102_wf/func_preproc_ses_nyu3t01_task_prf_acq_normal_run_01_wf/bold_reg_wf/bbreg_wf/bbregister/uni_xform_masked_bbreg_sub-wlsubj102.lta \
           --reg /Users/winawerlab/Desktop/scratch/work/fmriprep_wf/single_subject_wlsubj102_wf/func_preproc_ses_nyu3t01_task_prf_acq_normal_run_01_wf/bold_reg_wf/bbreg_wf/bbregister/uni_xform_masked_bbreg_sub-wlsubj102.dat \
           --o /Users/winawerlab/Desktop/scratch/work/fmriprep_wf/single_subject_wlsubj102_wf/func_preproc_ses_nyu3t01_task_prf_acq_normal_run_01_wf/bold_reg_wf/bbreg_wf/bbregister/uni_xform_masked_bbreg.nii.gz \
           --mov /Users/winawerlab/Desktop/scratch/work/fmriprep_wf/single_subject_wlsubj102_wf/func_preproc_ses_nyu3t01_task_prf_acq_normal_run_01_wf/sdc_wf/pepolar_unwarp_wf/enhance_and_skullstrip_bold_wf/apply_mask/uni_xform_masked.nii.gz \
           --s sub-wlsubj102
```

which is the fmriprep command found in the workflow located here: scratch/work/fmriprep_wf/single_subject_wlsubj102_wf/func_preproc_ses_nyu3t01_task_prf_acq_normal_run_01_wf/bold_reg_wf/bbreg_wf/bbregister/command.txt

<img width="2212" alt="Screen Shot 2019-11-08 at 3 11 51 PM" src="https://user-images.githubusercontent.com/33101992/68508730-1c57d400-023d-11ea-9752-13138c374d1f.png">

And here's the same data now registered by adding '--init-header' tot the input

```
bbregister --t2 --6 --init-header \
           --lta /Users/winawerlab/Desktop/scratch/work/fmriprep_wf/single_subject_wlsubj102_wf/func_preproc_ses_nyu3t01_task_prf_acq_normal_run_01_wf/bold_reg_wf/bbreg_wf/bbregister/uni_xform_masked_bbreg_sub-wlsubj102.lta \
           --reg /Users/winawerlab/Desktop/scratch/work/fmriprep_wf/single_subject_wlsubj102_wf/func_preproc_ses_nyu3t01_task_prf_acq_normal_run_01_wf/bold_reg_wf/bbreg_wf/bbregister/uni_xform_masked_bbreg_sub-wlsubj102.dat \
           --o /Users/winawerlab/Desktop/scratch/work/fmriprep_wf/single_subject_wlsubj102_wf/func_preproc_ses_nyu3t01_task_prf_acq_normal_run_01_wf/bold_reg_wf/bbreg_wf/bbregister/uni_xform_masked_bbreg.nii.gz \
           --mov /Users/winawerlab/Desktop/scratch/work/fmriprep_wf/single_subject_wlsubj102_wf/func_preproc_ses_nyu3t01_task_prf_acq_normal_run_01_wf/sdc_wf/pepolar_unwarp_wf/enhance_and_skullstrip_bold_wf/apply_mask/uni_xform_masked.nii.gz \
           --s sub-wlsubj102
```

<img width="2212" alt="Screen Shot 2019-11-08 at 3 20 29 PM" src="https://user-images.githubusercontent.com/33101992/68508928-b9b30800-023d-11ea-8453-ba139241b8b4.png">

The corresponding nifti files can be downloaded here:
https://nyu.box.com/s/a4lra1mmgei66id772zbbkhe5uq1o336

NB In this case the reference volume was the EPI scan, not the sbref, and there were no modifications to the fmriprep pipeline. I get similar results when running mri_coreg with and without the regheader flag (can provide images/files if that's helpful).

In sum, the default initialization in [mri_coreg](https://surfer.nmr.mgh.harvard.edu/fswiki/mri_coreg ) that is passed on to bbregister appears to be bad for partial volume acquisitions (possibly because it centers the two volumes?). As noted [here](https://surfer.nmr.mgh.harvard.edu/fswiki/bbregister), using the header info to initialize registration is only helpful in case the T1 and EPIs were collected within the same session. However, this not uncommon so it could be a valuable option for fmriprep users (it looks like it would be for us!).

**Comment by JWinawer** [comment]
Thanks, Iris.

@Chris: Is it likely that fMRIprep could be modified to accept this
additional flag? (ie an instruction to include the "init-header" flag in
the call to bbregister, which apparently means  "Assume that the geometry
information in the cross-modal and anatomical are sufficient to get a close
voxel-to-voxel registration. This usually is only the case if they were
acquired in the same session.")

If so, it looks like it will fix our problem. If not, I suppose we could
modify the fMRIprep code locally.

Jon




On Fri, Nov 8, 2019 at 4:20 PM Iris Groen <notifications@github.com> wrote:

> We have done some further testing in @WinawerLab
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_WinawerLab&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=vcPHoEUfTylRbra-ssFSIb437ouyP3zxeOcCi0tiUyk&s=2ZqJ50wxLvya2oFSHBdgHlc28kihJgY03yITNLUJ6u0&e=>
> lab and think we might have a solution to improve partial volume
> registration in fmriprep: provide the option to initialize registration
> using the header info, i.e. passing inputflags '--regheader' to
> mri_convert, and '--init-header' to bbregister.
>
> As far as I can see the current registration workflows in fmriprep don't
> use these inputs. Below is one of our "bad" registrations created by
> running:
>
> bbregister --t2 --6 \
>            --lta /Users/winawerlab/Desktop/scratch/work/fmriprep_wf/single_subject_wlsubj102_wf/func_preproc_ses_nyu3t01_task_prf_acq_normal_run_01_wf/bold_reg_wf/bbreg_wf/bbregister/uni_xform_masked_bbreg_sub-wlsubj102.lta \
>            --reg /Users/winawerlab/Desktop/scratch/work/fmriprep_wf/single_subject_wlsubj102_wf/func_preproc_ses_nyu3t01_task_prf_acq_normal_run_01_wf/bold_reg_wf/bbreg_wf/bbregister/uni_xform_masked_bbreg_sub-wlsubj102.dat \
>            --o /Users/winawerlab/Desktop/scratch/work/fmriprep_wf/single_subject_wlsubj102_wf/func_preproc_ses_nyu3t01_task_prf_acq_normal_run_01_wf/bold_reg_wf/bbreg_wf/bbregister/uni_xform_masked_bbreg.nii.gz \
>            --mov /Users/winawerlab/Desktop/scratch/work/fmriprep_wf/single_subject_wlsubj102_wf/func_preproc_ses_nyu3t01_task_prf_acq_normal_run_01_wf/sdc_wf/pepolar_unwarp_wf/enhance_and_skullstrip_bold_wf/apply_mask/uni_xform_masked.nii.gz \
>            --s sub-wlsubj102
>
> which is the fmriprep command found in the workflow located here:
> scratch/work/fmriprep_wf/single_subject_wlsubj102_wf/func_preproc_ses_nyu3t01_task_prf_acq_normal_run_01_wf/bold_reg_wf/bbreg_wf/bbregister/command.txt
>
> [image: Screen Shot 2019-11-08 at 3 11 51 PM]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_33101992_68508730-2D1c57d400-2D023d-2D11ea-2D9752-2D13138c374d1f.png&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=vcPHoEUfTylRbra-ssFSIb437ouyP3zxeOcCi0tiUyk&s=RAgg0RUO47qkabbY-CUWj9-GkPKL3A_jYj_4EzP3dY8&e=>
>
> And here's the same data now registered by adding '--init-header' tot the
> input
>
> bbregister --t2 --6 --init-header \
>            --lta /Users/winawerlab/Desktop/scratch/work/fmriprep_wf/single_subject_wlsubj102_wf/func_preproc_ses_nyu3t01_task_prf_acq_normal_run_01_wf/bold_reg_wf/bbreg_wf/bbregister/uni_xform_masked_bbreg_sub-wlsubj102.lta \
>            --reg /Users/winawerlab/Desktop/scratch/work/fmriprep_wf/single_subject_wlsubj102_wf/func_preproc_ses_nyu3t01_task_prf_acq_normal_run_01_wf/bold_reg_wf/bbreg_wf/bbregister/uni_xform_masked_bbreg_sub-wlsubj102.dat \
>            --o /Users/winawerlab/Desktop/scratch/work/fmriprep_wf/single_subject_wlsubj102_wf/func_preproc_ses_nyu3t01_task_prf_acq_normal_run_01_wf/bold_reg_wf/bbreg_wf/bbregister/uni_xform_masked_bbreg.nii.gz \
>            --mov /Users/winawerlab/Desktop/scratch/work/fmriprep_wf/single_subject_wlsubj102_wf/func_preproc_ses_nyu3t01_task_prf_acq_normal_run_01_wf/sdc_wf/pepolar_unwarp_wf/enhance_and_skullstrip_bold_wf/apply_mask/uni_xform_masked.nii.gz \
>            --s sub-wlsubj102
>
> [image: Screen Shot 2019-11-08 at 3 20 29 PM]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_33101992_68508928-2Db9b30800-2D023d-2D11ea-2D8453-2Dba139241b8b4.png&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=vcPHoEUfTylRbra-ssFSIb437ouyP3zxeOcCi0tiUyk&s=ngmye0_ku2afMn7rpJBEyvSTmeMOcntGUwYf84tAz8I&e=>
>
> The corresponding nifti files can be downloaded here:
> https://nyu.box.com/s/a4lra1mmgei66id772zbbkhe5uq1o336
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__nyu.box.com_s_a4lra1mmgei66id772zbbkhe5uq1o336&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=vcPHoEUfTylRbra-ssFSIb437ouyP3zxeOcCi0tiUyk&s=seQmx6fuHIX0Dt3yqAk7rxhQqvcGd4yrn33KpKmlyyo&e=>
>
> NB In this case the reference volume was the EPI scan, not the sbref, and
> there were no modifications to the fmriprep pipeline. I get similar results
> when running mri_coreg with and without the regheader flag (can provide
> images/files if that's helpful).
>
> In sum, the default initialization in mri_coreg
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__surfer.nmr.mgh.harvard.edu_fswiki_mri-5Fcoreg&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=vcPHoEUfTylRbra-ssFSIb437ouyP3zxeOcCi0tiUyk&s=FG0XK8Q_hFvakL9uLaxm6IVdJsW181abhh85MkkQRaU&e=>
> that is passed on to bbregister appears to be bad for partial volume
> acquisitions (possibly because it centers the two volumes?). As noted here
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__surfer.nmr.mgh.harvard.edu_fswiki_bbregister&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=vcPHoEUfTylRbra-ssFSIb437ouyP3zxeOcCi0tiUyk&s=GcjxRkfuQrXd1rx0a9eLa5iceyBkwMJHbpNoiYVyNLw&e=>,
> using the header info to initialize registration is only helpful in case
> the T1 and EPIs were collected within the same session. However, this not
> uncommon so it could be a valuable option for fmriprep users (it looks like
> it would be for us!).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_poldracklab_fmriprep_issues_1842-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAAQFPXVPVICMXKEQVVZIDMLQSXJ3PA5CNFSM4JFG6Z5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDTMERA-23issuecomment-2D551993924&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=vcPHoEUfTylRbra-ssFSIb437ouyP3zxeOcCi0tiUyk&s=Bd2K6DplW_KqCWRvcTMq748f9gRdFu1MvJGCmM_Ticw&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAQFPXWX35S35JCLTWHBEH3QSXJ3PANCNFSM4JFG6Z5A&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=vcPHoEUfTylRbra-ssFSIb437ouyP3zxeOcCi0tiUyk&s=lQA-ECWkMH4RWPV0DZvPw3TYVfVG5dAWigep4VqHIQw&e=>
> .
>


-- 
Jonathan Winawer
Associate Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/

**Comment by effigies** [comment]
Hi Iris and Jon,

Thanks for looking further into this. I think alternative initial registrations are a good way to think about this, and it certainly seems reasonable to make `--init-header` one of those options.

A couple things to consider:

1) How should we handle this as far as the fMRIPrep command line options go? An `--init-header` (or equivalent; presumably we'd want something a little more descriptive) would be very granular, but perhaps a `--partial-fov` flag, that might expand as other partial-FoV optimizations are found, would make sense? There's of course a danger that not all partial fields of view are created equal, and a common set of parameters is a bad idea.

2) We currently use the difference between the initial registration and the BBR refinement as a test for whether the BBR was useful, and fall back to the rigid `mri_coreg` registration if the difference is too great. `--init-header` would bypass the first. Should we proceed to unconditionally accept the BBR refinement in these cases, or have some error case?

3) Do we want to allow people to include "manual" or otherwise pre-calculated registrations as part of their datasets? This could help in cases where our registration fails even with an `--init-header`-style option.

Anyway, overall I'm supportive of this idea. We should think through the best way to include it. Please let me know your thoughts on the above. (The third question is probably a bit outside the immediate scope, but figured I'd raise it.)

**Comment by irisgroen** [comment]
Thanks for the quick response. Here are my thoughts:

1. Perhaps the fmriprep command line could have an optional flag like `'--reg-init'` which users could use to pass one of the alternative registration inputs that are then converted into the appropriate inputs to `mri_coreg` and `bbregister`? E.g. `--reg-init header` or `--reg-init <path_to_custom_matrix_file>` (see point 3). If you don't specify `--reg-init`, it would just default to the default settings from `mri_coreg`.

2. The examples I showed were from `bbregister` but the same option is available for `mri_coreg`, you can supply `'--regheader'` to `mri_coreg` to tell it to use the header information. So perhaps no modifications to `bbregister` would be necessary if you start `mri_coreg` with a better starting point and `bbregister `then tries to improve from there. I can try that out on our data. This would make sense if there's never a scenario in fmriprep when `bbregister` is used 'on its own', is that true? 

3. I think it would be really great if that were an option: we haven't tested exhaustively but as you say, registration for partial volumes can fail even with the header-based approach, for example when the T1 is actually from a different session. In our lab we also sometimes deal with brains from patients that have resections in which case manual alignment may be necessary. We thought about potentially hacking that solution in (if header-based registration would be included in fmriprep) by overwriting  the header in the to-be-aligned files, to get a precalculated registration in there. But it would be cleaner to supply it as an optional input.

**Comment by JWinawer** [comment]
> Hi Iris and Jon,
> 
> Thanks for looking further into this. I think alternative initial registrations are a good way to think about this, and it certainly seems reasonable to make `--init-header` one of those options.
> 
> A couple things to consider:
> 
> 1. How should we handle this as far as the fMRIPrep command line options go? An `--init-header` (or equivalent; presumably we'd want something a little more descriptive) would be very granular, but perhaps a `--partial-fov` flag, that might expand as other partial-FoV optimizations are found, would make sense? There's of course a danger that not all partial fields of view are created equal, and a common set of parameters is a bad idea.

I am not sure `--partial-fov`  is the best descriptor. First, there might be data with partial fov where the T1 and EPIs come from separate sessions, as Iris indicated. And second, there might be large fov datasets which would nonetheless benefit from the alignment being initialized with the file headers. 

So one option is the granular flag, as you suggested and Iris maybe agreed with (e.g., `--initheader`. If you prefer a more general flag, then perhaps something like `--single-session` to indicate whether all data came from a single session (if so, then assume that the nfiti headers are meaningful for initializing the alignments, and perhaps there will be other optimizers that go along with this). 

Even better would be if it were possible to determine whether the two images are in the same space, either from BIDS fields/files or from the NIFTIs (eg maybe the sform_code in the EPI would be useful?)

Yet another option is to simply change the default to initialize the alignment as though the headers are meaningful. When the images are already aligned, this will be helpful. If they are not already aligned, it will not be helpful but I am not sure whether it will be detrimental. 

> 2. We currently use the difference between the initial registration and the BBR refinement as a test for whether the BBR was useful, and fall back to the rigid `mri_coreg` registration if the difference is too great. `--init-header` would bypass the first. Should we proceed to unconditionally accept the BBR refinement in these cases, or have some error case?
> 3. Do we want to allow people to include "manual" or otherwise pre-calculated registrations as part of their datasets? This could help in cases where our registration fails even with an `--init-header`-style option.
> 

This would be great but I don't think it's essential (at least for our situation, which is solved by initializing mri_coreg or bbregister appropriately).

> Anyway, overall I'm supportive of this idea. We should think through the best way to include it. Please let me know your thoughts on the above. (The third question is probably a bit outside the immediate scope, but figured I'd raise it.)

Agree re last issue.
