### ISSUE TITLE
Unexpected lack of images in html report and incomplete output

### ISSUE THREAD

**Issue by dittothat** [poldracklab/fmriprep#1845]
I have been trying to run fmriprep using fmriprep-docker and I am encountering trouble. I have attached a tree of my bids compliant data set.
[tree_sub-test01_2.txt](https://github.com/poldracklab/fmriprep/files/3789589/tree_sub-test01_2.txt)

Given these inputs I expect the html report to look similar to the example reports in the documentation but it contains no images and no confounds information at all: 
[sub-test01.html.pdf](https://github.com/poldracklab/fmriprep/files/3789576/sub-test01.html.pdf)

Second, the output seems incomplete as there is no confounds information at all, and none of the func/*_spaces-* outputs (eg func/sub-<subject_label>_[specifiers]_space-<space_label>_desc-preproc_bold.nii.gz) that are described in the documentation. See attached derivatives tree.
[tree_derivatives.txt](https://github.com/poldracklab/fmriprep/files/3789645/tree_derivatives.txt)

I do get an early error (crash) while fmriprep is running. It is attached, but I have no idea what it means.
[crash-20191029-223737-root-fsdir_run_20191029_223642_cc6ba41c_9515_4378_af4b_6028846d074f-f9306052-4f67-44a7-908c-01f4826cbf24.txt](https://github.com/poldracklab/fmriprep/files/3789646/crash-20191029-223737-root-fsdir_run_20191029_223642_cc6ba41c_9515_4378_af4b_6028846d074f-f9306052-4f67-44a7-908c-01f4826cbf24.txt)

Any help or suggestions would be deeply appreciated.

**Comment by dittothat** [comment]
Command.
fmriprep-docker /net/rc-fs-nfs/ifs/data/NoSync/FNNDSC-NR/neuro/labs/grantlab/research/SCD /net/rc-fs-nfs/ifs/data/NoSync/FNNDSC-NR/neuro/labs/grantlab/research/SCD/derivatives_2 participant --participant-label test01 --fs-license-file ~/license.txt --output-spaces T1w fsnative func > /net/rc-fs-nfs/ifs/data/NoSync/FNNDSC-NR/neuro/labs/grantlab/research/SCD/fmripreprun_2.txt

Log.
[fmripreprun_2.txt](https://github.com/poldracklab/fmriprep/files/3789973/fmripreprun_2.txt)

The error looked vaguely permissions like, so I made certain the output directory ".../derivatives_2" had complete permissions:
drwxrwxrwx   4 jeff   grantlab_local     54 Oct 29 18:37 derivatives_2

**Comment by effigies** [comment]
There may be strange interactions with NFS policies here. It runs as `root` by default, so that it's being recast to `nobody` makes me think Docker or your filesystem is doing something too clever for its own good. If you add `-u $UID` to your `fmriprep-docker` command, it should write all outputs as as your user.

As an aside, I would generally not recommend nesting your derivatives inside your source dataset at runtime. If you're going to nest derivatives inside the raw dataset, then I would do it after everything is done, when it's time to publish or archive, but that's a bit beside the point here... While `derivatives/` is ignored and thus should not affect execution, any other name will almost always be picked up, so you're seeing things like:

```
                ./fmripreprun_2.txt
			Evidence: fmripreprun_2.txt
		./tree_derivatives.txt
			Evidence: tree_derivatives.txt
		./tree_sub-test01.txt
			Evidence: tree_sub-test01.txt
```

I don't think that's your problem here, but it's generally best to keep things separate, as that gives the opportunity for one error to turn into another when you try to rerun.

**Comment by dittothat** [comment]
Thank you for your help! You were exactly correct about the file system doing something too clever for its own good. I wrote the outputs to my very own home directory and everything is beautiful. I will mark closed, but a slightly more descriptive error message, or a final warning in the report itself, if there is some catastrophic failure in write permissions would be a really great addition.

**Comment by dittothat** [comment]
I add just for someone's future reference, that the -u $UID threw an error that allowed me to diagnose the problem, but did not fix it. Interpreting the error, anything docker writes initially (folder for mount points) are created as root, and if that ownership is subsequently transfer to UID. If ownership gets altered by some file system cleverness (root is squashed), then the permissions transfer doesn't work for the orphaned files. In my case if the initial folders and files were owned by UID to start I don't think I would have had an issue.

**Comment by effigies** [comment]
Thanks for that feedback. I'm glad you were able to resolve the issue. I opened #1846 to track improvements to this reporting. If you have reproducible conditions you can set up on a local system, that would help a lot. Feel free to comment on that issue with any suggestions you may have.
