### ISSUE TITLE
fMRIPrep docusprint - November 6, 2019

### ISSUE THREAD

**Issue by franklin-feingold** [poldracklab/fmriprep#1848]
Hey fMRIPrep Community! 

The fMRIPrep team is proud to announce that we will be hosting an fMRIPrep contributor sprint to enhance the documentation. We hope to gather you around the world on Wednesday, November 6, 2019. This will be an all day sprint. We will be using the [fmriprep mattermost channel](https://mattermost.brainhack.org/brainhack/channels/fmriprep) to facilitate discussions across the sprint.

With the help from many contributors and fMRIPrep users, we have identified some dark areas on our documentation that hopefully will be better covered after the sprint. Please check on the  ["Documentation" project board](https://github.com/orgs/poldracklab/projects/2) to see a list of these issues and feel free to submit additional documentation requests that may be beneficial to address in the sprint! During the sprint we will attempt to write all the documentation pages necessary to resolve those issues. Your contributions are very much appreciated - please follow [these simple steps](https://github.com/poldracklab/fmriprep/wiki/Contributing-documentation-guidelines) to send your contributions.

Please let us know if you have any questions!

Thank you,
fMRIPrep Team

**Comment by oesteban** [comment]
People interested in confounds/regression - please reach out to @kfinc and check out her outline to improve docs on that front!

https://docs.google.com/document/d/14WyhCvEn0G5fbLY-Rk7BQa9ISzYEB2ll3YCjyd-OjB8/edit
