### ISSUE TITLE
mri_robust_template issues with multiple T1s from multiple sessions

### ISSUE THREAD

**Issue by cmpetty** [poldracklab/fmriprep#1865]
i'm running into an issue when trying to process subjects which have multiple sessions, with a T1 per session.

default processing with mri_robust_template does not seem to be aligning the images prior to producing the mean.  maybe in a typical freesurfer pipeline with mutliple T1s they would align them prior to running this step, not completely sure.

But the subject's i've tried have always ended up like the following

This shows the 2 T1s on top of one another ( one grey, one red )
![Screen Shot 2019-11-07 at 10 39 55 AM](https://user-images.githubusercontent.com/2243287/68403723-6496c980-014b-11ea-988c-323a193d40aa.png)
 
The resulting template, which just looks like a straight average of the two:
![Screen Shot 2019-11-07 at 10 40 07 AM](https://user-images.githubusercontent.com/2243287/68403735-695b7d80-014b-11ea-8908-af990c831179.png)

this is the command being run by fmriprep to combine them, i shortened the paths for brevity:
`
mri_robust_template
--satit
--mov
anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct0/sub-7621_ses-rest01_T1w_ras_corrected.nii.gz
anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct1/sub-7621_ses-reward01_T1w_ras_corrected.nii.gz
--inittp
1
--iscale
--template
sub-7621_ses-rest01_T1w_ras_template.nii.gz
--subsample
200
--lta
anat_preproc_wf/anat_template_wf/t1_merge/tp1.lta
anat_preproc_wf/anat_template_wf/t1_merge/tp2.lta
`

looking for suggestions to make this work, other than just excluding the additional T1s. i will add that the original T1s were slightly different resolution, but fmriprep resampled them appropriately before this t1_merge step.

**Comment by effigies** [comment]
Robust template should be aligning them. We use it because it does a very good job within-subject at ignoring gross anatomical structures like a neck (e.g., if the subject was positioned differently in the scanner across sessions) and growing tumors.

Are they both of reasonable quality and you can visually see that they are the same subject (the same folding patterns)?

**Comment by cmpetty** [comment]
they're definitely the same subject.  second session has a bit of noise because they tried to increase the resolution

first session .5mm iso, second .5x.5x.4

![Screen Shot 2019-11-07 at 11 09 07 AM](https://user-images.githubusercontent.com/2243287/68406233-767a6b80-014f-11ea-871f-aae04258e81d.png)

i haven't actually seen one of these process correctly where both sessions were present when fmriprep processing was launched.

**Comment by effigies** [comment]
Could you show the `*T1w_ras_corrected.nii.gz` files listed in the command, as those are the actual inputs? It may be that resampling the first into the second space didn't go well, or the N4 correction may have failed.

**Comment by cmpetty** [comment]
![Screen Shot 2019-11-07 at 11 27 06 AM](https://user-images.githubusercontent.com/2243287/68407441-9448d000-0151-11ea-92f7-cd03cf34bd0f.png)

**Comment by cmpetty** [comment]
> 
tesla:mapflow cmp12$ mrinfo _n4_correct0/sub-7621_ses-rest01_T1w_ras_corrected.nii.gz 
************************************************
Image:               "_n4_correct0/sub-7621_ses-rest01_T1w_ras_corrected.nii.gz"
************************************************
  Dimensions:        512 x 512 x 388
  Voxel size:        0.5 x 0.5 x 0.4
  Data strides:      [ 1 2 3 ]
  Format:            NIfTI-1.1 (GZip compressed)
  Data type:         32 bit float (little endian)
  Intensity scaling: offset = 0, multiplier = 1
  Transform:                    1           0           0      -126.6
                                0           1           0      -113.6
                                0           0           1      -74.12
tesla:mapflow cmp12$ mrinfo _n4_correct1/sub-7621_ses-reward01_T1w_ras_corrected.nii.gz 
************************************************
Image:               "_n4_correct1/sub-7621_ses-reward01_T1w_ras_corrected.nii.gz"
************************************************
  Dimensions:        512 x 512 x 388
  Voxel size:        0.5 x 0.5 x 0.4
  Data strides:      [ 1 2 3 ]
  Format:            NIfTI-1.1 (GZip compressed)
  Data type:         32 bit float (little endian)
  Intensity scaling: offset = 0, multiplier = 1
  Transform:                    1           0           0      -130.7
                                0           1           0      -110.1
                                0           0           1      -30.21
>

**Comment by effigies** [comment]
That inhomogeneity in the right image really didn't get fixed well. It's possible that's driving the failure.

These are also large (>200 voxels) on all axes, so `--subsample 200` comes into play. You could try rerunning manually and removing this, though it will incur a cost in memory and time.

If that fails, I would probably check with the FreeSurfer mailing list to see if they have any suggestions. If there are things we can do to make our usage of this tool more robust, we'd be happy to incorporate those changes. I don't know of a better cross-session registration tool.

**Comment by cmpetty** [comment]
For sanity sake i made a copy of the good image and rotated it 10 degrees to be out of alignment. Then manually ran `mri_robust_template` with the defaults from above.  The end result was a nicely aligned/merged template of the 2 good versions.

I also tried the good image and the noisy image without the `--subsample 200`, which just resulted in a bigger version of the bad looking template from above.

Looking back through these subjects that were processed with 2 visits ... only 1 out of the 6 had a descent looking template, but the failures can probably be attributed to excessive motion/noise as the above image showed.
