### ISSUE TITLE
Carpet plots not appearing in report

### ISSUE THREAD

**Issue by dittothat** [poldracklab/fmriprep#1868]
Should "carpet"-plots like those shown in the documentation be given in every output html report? That information would be useful to me but it is not appearing in my report, and without any crashes or reported errors I wonder why.

**Comment by effigies** [comment]
What is your full command?

**Comment by dittothat** [comment]
This is the command:
fmriprep-docker /net/rc-fs-nfs/ifs/data/NoSync/FNNDSC-NR/neuro/labs/grantlab/research/SCD/data /home/jeff/SCD/derivatives participant --participant-label scd01 --fs-license-file /home/jeff/license.txt --output-spaces T1w fsnative func -w /home/jeff/SCD/work --write-graph

Thanks for your help,
Jeff

**Comment by effigies** [comment]
Carpet plots depend on using the standard template output space, for now. We intend to make them more general in the future.

**Comment by dittothat** [comment]
Thank you. I didn't glean this from the documentation.
