### ISSUE TITLE
fmriprep cifti vs ciftify cifti question

### ISSUE THREAD

**Issue by dkp** [poldracklab/fmriprep#1872]
I'm curious about cifti files generated by fmriprep vs Erin Dickie's ciftify.  

Erin Dickie had this to say: "So the ciftify one's are in a "space" and resolution (and surface-based registration algorithm) as the HCP Pipelines. They are in "fsLR" space with a 32k density. At least earlier - the cifti files that fmriprep was outputting had surfaces in "fsaverage5", a bit of their own thing. But I think Oscar was working on changing that recently."

What is the current state of this...are fmriprep's cifti files comparable to ciftify's cifti files?  Thank you,

Dianne

**Comment by mgxd** [comment]
Currently the CIFTI outputs provided by fmriprep consist of the BOLD timeseries sampled to `fsaverage5` or `fsaverage6` cortices, and `MNI152NLin2009cAsym` for subcortical structures. This is different from the output spaces of the HCP Pipelines and ciftify.

However, we are actively working on generating outputs in the HCP greyordinates space - `fsLR` surface and `MNI152NLin6Asym` volume.

**Comment by dkp** [comment]
Thanks so much!
