### ISSUE TITLE
fMRIprep Susceptibility Distortion correction (SDC) issues

### ISSUE THREAD

**Issue by yishant** [poldracklab/fmriprep#1874]
Hi all,
We’ve been using fMRIprep to preprocess some data that will ultimately be used to run a functional connectivity analysis in resting state scans. I have a few questions regarding the distortion correction, as that is where we believe the problems are stemming from. Any advice/guidance would really help.

1)Our data were collected with 2 opposite phase encoded EPI sequences (AP and PA) so when we ran fMRIprep , the SDC method chosen was the PEPOLAR technique (which uses AFNI’s 3dQwarp). While it ran with no errors, it resulted in less than ideal [outputs](https://drive.google.com/file/d/1R8bTPLQPgvZ8reAvZ8NV3wvllFwKl_Ro/view?usp=sharing).

What’s most noticeable is that when we overlay the BOLD on the T1 image, there is signal dropout at the frontal poles as well as some other regions in particular slices. Is there an explanation as to why this would be happening (and a way to fix it)?

2)To try and work around the issue stated in 1), we tried forcing fMRIprep to run SDC through the direct [B0 mapping sequence](https://fmriprep.readthedocs.io/en/stable/api/index.html#direct-b0-mapping-sequences), so it could be run using TOPUP. We created field maps and magnitude images following instructions from https://lcni.uoregon.edu/kb-articles/kb-0003 . However, this resulted in even worse outputs than before, with the brain being completely distorted and unreadable.

3)We’ve thought of another route, but haven’t tried it yet. We were thinking to run TOPUP for SDC prior to running fMRIprep (with --ignore fieldmaps). But we are unsure of how important the preprocessing order is for fMRIprep, and how this would affect the workflow. Has anyone tried this (or something similar), and if so, what kind of results did you obtain?

If anyone has worked with a similar data set and has experienced these issues, any help would be appreciated! Thanks!

**Comment by markushs** [comment]
Hi @yishant ,
This sounds related to an issue I have posted over at sdcflows (I think fmriprep gets its SDC-workflows from that library now). https://github.com/poldracklab/sdcflows/issues/37
Seems like there's some refactoring going on in sdcflows these days, so maybe @oesteban can comment on whether TOPUP implementation is in the pipeline (or if assistance is needed)? 

However, even after successful SDC its not uncommon to see dropout in inferior temporal regions (depending on your acquisition parameters, of course).

**Comment by oesteban** [comment]
> 1)Our data were collected with 2 opposite phase encoded EPI sequences (AP and PA) so when we ran fMRIprep , the SDC method chosen was the PEPOLAR technique (which uses AFNI’s 3dQwarp). While it ran with no errors, it resulted in less than ideal [outputs](https://drive.google.com/file/d/1R8bTPLQPgvZ8reAvZ8NV3wvllFwKl_Ro/view?usp=sharing).
> 
> What’s most noticeable is that when we overlay the BOLD on the T1 image, there is signal dropout at the frontal poles as well as some other regions in particular slices. Is there an explanation as to why this would be happening (and a way to fix it)?

Depending on your imaging settings, your screen capture seems like a very nice result for SDC on BOLD data. Some regions perturb the B0 field because of the proximity of air and tissue interfaces and provoke the spatial distortions and oftentimes signal dropout. What you are seeing are regions where the signal was completely lost.



> 2)To try and work around the issue stated in 1), we tried forcing fMRIprep to run SDC through the direct [B0 mapping sequence](https://fmriprep.readthedocs.io/en/stable/api/index.html#direct-b0-mapping-sequences), so it could be run using TOPUP. We created field maps and magnitude images following instructions from https://lcni.uoregon.edu/kb-articles/kb-0003 . However, this resulted in even worse outputs than before, with the brain being completely distorted and unreadable.

Feels like an error encoding the EffectiveEchoSpacing of your BOLD. But if you double check and feel fMRIPrep has a problem, please go ahead and report it in https://github.com/poldracklab/sdcflows/issues/new



> 3)We’ve thought of another route, but haven’t tried it yet. We were thinking to run TOPUP for SDC prior to running fMRIprep (with --ignore fieldmaps). But we are unsure of how important the preprocessing order is for fMRIprep, and how this would affect the workflow. Has anyone tried this (or something similar), and if so, what kind of results did you obtain?

fMRIPrep will get pretty bad indigestion with pre-processed results - I definitely discourage this route. As @markushs suggested, please follow up on poldracklab/sdcflows#37 about the progress in the implementation of a pure TOPUP solution.
