### ISSUE TITLE
Outdated cache, while nothing changed

### ISSUE THREAD

**Issue by bpinsard** [poldracklab/fmriprep#1875]
I am running fmriprep in a singularity container, but it crashed during copy to the output folder (because of a datalad lock).
When I relaunch the pipeline with the exact same command and same input, everything is reprocessed, giving for each node.
```[Node] Outdated cache found for ...```

I know this is more a nipype issue, but as anyone experienced it with fmriprep?
Why is the cache outdated?
Is it because the data is in datalad?

The hack I found to avoid reprocessing all the data, is to use `--use-plugin` with `"updatehash": true` added to the [default options](https://github.com/poldracklab/fmriprep/blob/master/fmriprep/cli/run.py#L570) .

When only the reports are needed `--reports-only` works.

I am posting it here as it could help others having the same problem.

**Comment by effigies** [comment]
I've run into similar when a new template needs to be downloaded. If it's not in the container, its timestamp gets updated every time.

**Comment by oesteban** [comment]
@basile would you like to resurrect this one and better define how to replicate the problem?

**Comment by bpinsard** [comment]
I will try again, but it might be because templateflow re-fetches the templates. Prefetching the templates is necessary on the new cluster that we are using, so that should fix it.
I will try with both locally.

**Comment by oesteban** [comment]
Any updates on this one?

**Comment by bpinsard** [comment]
I ran it on docker, if interrupted and relaunched it seems to catch back where it was (minus different execution order of parallel nodes).  Many changes have been made that should have fixed this one since 1.5.x .  I will close it now.

**Comment by SujaCCME** [comment]
rfreg
