### ISSUE TITLE
Do the files in the output directory completed?

### ISSUE THREAD

**Issue by YeYeLab** [poldracklab/fmriprep#1881]
Hi fmriprep gurus,
I have crushes while running fmriprep, but the output directory containing all the files I need.
I wonder if I can use them although the run as a whole is corrupted. Are they valid to use?

I am talking about this kind of output files:
“sub-1_ses-01_task-seker_run-01_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz”
“...space-MNI152NLin2009cAsym_desc-preproc_T1w”

Thank you very much,
Sharon

**Comment by effigies** [comment]
Hi Sharon,

Yes, the files in the output directory have been fully processed. No further changes are made after they are placed there.

Could you describe the crashes you're seeing more?

Best,
Chris

**Comment by YeYeLab** [comment]
Thank you!
I have started a dedicated new issue regarding the crushes.

**Comment by effigies** [comment]
Thanks.
