### ISSUE TITLE
Output of fmriprep not BIDS campatible?

### ISSUE THREAD

**Issue by maalaria** [poldracklab/fmriprep#1888]
Dear all,

I am a new user of fmriprep and first want thank you for this amazing tool. 
I have now completed the preprocessing of some subjects without errors but checking the /fmriprep/ folder with the BIDS validator gives some errors related to  `[Code 1] NOT_INCLUDED` which is apparently because of the sub-[...].html files and some others. What is the best practice here, adding them to a .bidsignore file?
The second error is a bit weird: `[Code 67] NO_VALID_DATA_FOUND_FOR_SUBJECT`
It basically says for all included subjects that there is no BIDS compatible data:
e.g.

```
/sub-02                                           NaN KB |
Location:
/sub-02

Reason:

No BIDS compatible data found for subject 02
```

**Comment by emdupre** [comment]
Hi @maalaria  --

fMRIPrep outputs BIDS Derivatives files, which are not yet considered part of the BIDS specification (see [here](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#source-vs-raw-vs-derived-data) for the distinction in BIDS between source, raw, and derived data). 

There are a few PRs open on the specification to change this (see https://github.com/bids-standard/bids-specification/pull/265 and https://github.com/bids-standard/bids-specification/pull/207), but until they are merged the BIDS Validator won't process derivatives directories, such as those output by fMRIPrep.

If you are just trying to confirm that processing completed correctly, I would check the error log at the bottom of the HTML files !

**Comment by maalaria** [comment]
Thanks, @emdupre !
