### ISSUE TITLE
float64 error

### ISSUE THREAD

**Issue by neurosurd** [poldracklab/fmriprep#1890]
Im using fmriprep 1.5.1 and getting a datatype error. Ive attached the crash report file. Please advise.

[crash-20191127-160156-root-skull_strip_extern-865f7cd5-c9d8-4890-8cc5-cf82ab99b737.txt](https://github.com/poldracklab/fmriprep/files/3897697/crash-20191127-160156-root-skull_strip_extern-865f7cd5-c9d8-4890-8cc5-cf82ab99b737.txt)

**Comment by effigies** [comment]
Thanks for this. I have proposed a fix in https://github.com/poldracklab/niworkflows/pull/430.

**Comment by effigies** [comment]
@oesteban Updated the niworkflows dependency. Any objection to a 1.5.2 release?
