### ISSUE TITLE
JSONDecodeError: Extra Data

### ISSUE THREAD

**Issue by BAshinoff** [poldracklab/fmriprep#1897]
I am trying to run fMRIPrep on my data which is in BIDS format and includes two sessions per subject. However, I am getting a JSONDecodeError: Extra Data almost immediately after the pipeline starts running. I have tried running multiple subjects, running this on only one session at a time, running the code with the longitudinal flag, but I keep getting the same error (see attached image). I also tried running this with the debug flag, but didn't get anything different. I have tried finding the line and column with the error, but I don't know which JSON file is causing the error. Plus, my lab has run this code on similarly structured data before with no problems. I am running fMRIPrep with docker.

![Error](https://user-images.githubusercontent.com/58481618/70071706-bce2af00-15c3-11ea-8ae3-49b39f8ad713.PNG)

Any advice would be appreciated! Also, this is my first time posting here, so if there is a better way or place to post a question like this, please let me know. Thanks!

**Comment by effigies** [comment]
PyBIDS has improved the error message in https://github.com/bids-standard/pybids/pull/495. To identify the failing file, please install `pybids >= 0.9.4`:

```Shell
pip install "pybids>=0.9.4"
```

Then you can open a Python shell:

```Python
>>> from bids import BIDSLayout
>>> BIDSLayout('/path/to/dataset')
```

This should identify the failing file. fMRIPrep has depended on PyBIDS >= 0.9.4 in versions 1.5.1+, but you may not want to change versions if things are generally working for you.

**Comment by BAshinoff** [comment]
Hi, just wanted to follow up and say this helped us find the problem file! If anyone else ends up with this issue, one thing to note is that we ended up having to update to python3 to get this to work. Thanks!

**Comment by effigies** [comment]
Yes, Python 2 is end-of-life in January, so very few projects are even making an effort to maintain support at this point.
