### ISSUE TITLE
Remove deprecated command line arguments

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1898]
We've been keeping some deprecated command-line arguments for some time - it is now the moment to drop them. These are:

- `--ignore-aroma-denoising-errors`
- `--debug`
- `--output-space`
- `--template`
- `--template-resampling-grid`
- `--no-freesurfer`
- `--output-grid-reference` (this is only present on the wrapper).

**Comment by mgxd** [comment]
Looking into this now - one question: is the docker wrapper meant to provide a very high level fmriprep call, while the `fmriprep` callable allows more fine-grain control? Or have we just not been synchronizing the two?

**Comment by effigies** [comment]
The Docker wrapper is meant to turn something that looks like an fMRIPrep invocation into a docker command. Any option that's valid in fMRIPrep should be valid in fMRIPrep docker. But it passes most things through, uninspected, only parsing options that will require it to mount a volume or some other manipulation of Docker.
