### ISSUE TITLE
Brain Mask Issue fmriprep v 1.5.3rc2 and v 1.5.0

### ISSUE THREAD

**Issue by mikojeske** [poldracklab/fmriprep#1914]
After running fmriprep 1.5.3rc2 on a couple of subjects, I noticed a problem with the brain mask as can be seen below. 

<img width="1259" alt="Screenshot 2019-12-13 at 18 44 59" src="https://user-images.githubusercontent.com/58860006/70820608-5d617c00-1dd9-11ea-8650-a49d13cc6431.png">

I was running this using HPC with the following command:
singularity run --cleanenv  ${VSC_DATA}/fmriprep.simg \
--task-id ddt1 --participant-label 10 --use-aroma --fs-license-file ./license.txt --fs-no-reconall \
--work-dir . \
BIDS_Folders fmriprep_out participant

I ran it once before for this subject locally using fmriprep v 1.5.0. There it did work. The only difference is the added --use-aroma argument and a new BIDS-folder. 

Does anybody have any suggestions about what could be going wrong?

**Comment by oesteban** [comment]
Did you reuse the work directory (in other words, did you invoked singularity run from the same path? - since you have ``--work-dir .``).

If you had access to the standard output both processes generated, it would be useful.

**Comment by mikojeske** [comment]
You can look at the output through the following link:
https://drive.google.com/file/d/1-FFAJI5wpbvhJ2Llq4-LFU6yUSoC8KIJ/view?usp=sharing

We think there might be a problem with the bias field correction, after which the top of the brain is not detected for the brain mask.

**Comment by oesteban** [comment]
Hi @mikojeske, there seems to be a problem in the brain extraction workflow - I'll try to dig it up next week.

**Comment by oesteban** [comment]
One question - are you using containers?

If so, are you sure this was not happening with version 1.5.0? or some RC of 1.5.0? These differences would make sense with any version prior to 1.5.0, but not with that particular version which included many changes to the bias correction and the brain extraction.

**Comment by mikojeske** [comment]
Hey @oesteban,

I ran it on the HPC using different singularity containers with different versions of fMRIPrep (1.5, 1.5.7, 1.5.8) with the extra commands --participant-label --fs-no-reconall -use-aroma. 

However, I also ran it locally using a docker container with the same commands and the issue was not present there. I also tried using --use-syn-sdc but that didn't work.

So it seems that there is an issue specifically to the singularity.

**Comment by oesteban** [comment]
Is it possible that you are reusing an existing work directory on the HPC but you aren't locally?

**Comment by mikojeske** [comment]
No, I always deleted the work directories before running fmriprep again.

If you want to see the output, you can view it through the following link:
https://drive.google.com/file/d/181SH3hDFS6dkqGH2nrUIYkNQ_dxiU1O-/view?usp=sharing

**Comment by mikojeske** [comment]
After a lot of searching, I could find that there was a problem in the antsApplyTransform because of a faulty tpl-OASIS30ANTs_res-01_label-brain_probseg.nii.gz template. This was downloaded wrongly to the cache when I first ran fmriprip on the HPC. Removing the cache and redownloading everything fixed the issue.

**Comment by effigies** [comment]
Thanks for updating, @mikojeske.
