### ISSUE TITLE
fMRIprep can't read a file it generated?

### ISSUE THREAD

**Issue by BAshinoff** [poldracklab/fmriprep#1916]
Hi,

I am trying to run fMRIprep on my data and it keeps crashing with the error below.
I can see that the erorr message says it can't read T2.norm.mgz, but I don't know why. The file does exist in the correct folder and I can open that file with other programs (fsl/mricron) and it looks fine -- no obvious problems or distortions. The previous line of code (included below) is the line of code that generates the file that fMRIprep seems to be unable to find. Any suggestions on how to get fix this would be appreciated! Thank you!

```
writing normalized volume to /output/freesurfer/sub-3115/mri/T2.norm.mgz

 mri_mask /output/freesurfer/sub-3115/mri/T2.norm.mgz /output/freesurfer/sub-3115/mri/brainmask.mgz /output/freesurfer/sub-3115/mri/T2.mgz 

mghRead(/output/freesurfer/sub-3115/mri/T2.norm.mgz): could not read 360000 bytes at slice 238
No such file or directory
mri_mask.bin: could not read source volume /output/freesurfer/sub-3115/mri/T2.norm.mgz
No such file or directory
Linux 465716803a77 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

recon-all -s sub-3115 exited with ERRORS at Wed Dec 18 00:41:27 UTC 2019

For more details, see the log file /output/freesurfer/sub-3115/scripts/recon-all.log
To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting

Standard error:

Return code: 1
```

**Comment by oesteban** [comment]
version of fmriprep?

**Comment by BAshinoff** [comment]
fMRIPREP version 1.5.0rc1:

**Comment by oesteban** [comment]
The problem should have been fixed in version 1.5.3. Could you try the latest (1.5.4)?

**Comment by BAshinoff** [comment]
Thanks! Re-running it now and will update once it's done.
I had thought I was using the most recent version. 
Just realized it was just the most recent version on our system (which apparently hadn't been updated in a while).

**Comment by mgxd** [comment]
If this issue persists, please reopen this issue!

**Comment by BAshinoff** [comment]
Hi, Sorry I forgot to update this. The problem was fixed after I updated. Thanks!
