### ISSUE TITLE
Upgrading from 1.5.2 to 1.5.4

### ISSUE THREAD

**Issue by soichih** [poldracklab/fmriprep#1921]
I am trying to upgrade from fmriprep 1.5.2 to 1.5.4. 

If I run fmrprep 1.5.4 with the same command line argument that worked for 1.5.2, the 1.5.4 now complains that I am missing an option.

```
    Running fMRIPREP version 1.5.4:
      * BIDS dataset path: /mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripinput.
      * Participant list: ['TTTEMPSUB'].
      * Run identifier: 20200102-042619_5fdc5d07-5cca-4785-9028-ad271e9d524f.
    
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 687, in build_workflow
    work_dir=str(work_dir),
TypeError: init_fmriprep_wf() missing 1 required positional argument: 'fs_subjects_dir'

```

So I've added the following command line option (fs_subjects_dir) to point to where my freesurfer output is.

>  --fs-subjects-dir="$outdir/freesurfer/$bidsSub" \

However, now fmrprep is complaining that there is no such option.

> fmriprep: error: unrecognized arguments: --fs-subjects-dir=fmripout/freesurfer/sub-TTTEMPSUB

I've tried without "=" and with fs_subjects_dir instead of fs-subjects-dir, but none of that seems to fix the problem. Could you help me troubleshoot?

**Comment by mgxd** [comment]
hi @soichih - can you share the full command?

**Comment by soichih** [comment]
@mgxd 

I was able to find the cause of the fs-subjects-dir issue (I think), but now I am seeing a different error message that I didn't see when I was running 1.5.2 version.

```
200106-17:19:07,412 nipype.workflow WARNING:
	 Storing result file without outputs
200106-17:19:07,413 nipype.workflow WARNING:
	 [Node] Error on "fmriprep_wf.single_subject_TTTEMPSUB_wf.func_preproc_ses_SSSES_task_facerecognition_run_1_wf.func_derivatives_wf.ds_bold_aparc_std" (/mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripworkdir/fmriprep_wf/single_subject_TTTEMPSUB_wf/func_preproc_ses_SSSES_task_facerecognition_run_1_wf/func_derivatives_wf/ds_bold_aparc_std)
200106-17:19:07,414 nipype.workflow ERROR:
	 Node ds_bold_aparc_std failed to run on host dev1.soichi.us.
200106-17:19:07,415 nipype.workflow ERROR:
	 Saving crash info to /mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripout/fmriprep/sub-TTTEMPSUB/log/20200106-171837_3e4cb4e9-ee73-4f26-9172-d087bb31b223/crash-20200106-171907-hayashis-ds_bold_aparc_std-93acf1c8-0b0c-4a73-bcb9-08a12e2675b7.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/legacymultiproc.py", line 381, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 479, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 585, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 678, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 340, in run
    self._check_mandatory_inputs()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 249, in _check_mandatory_inputs
    raise ValueError(msg)
ValueError: DerivativesDataSink requires a value for input 'in_file'. For a list of required inputs, see DerivativesDataSink.help()

```

Sorry for the moving target. Here is the command line I am executing.

> singularity exec docker://poldracklab/fmriprep:1.5.4 /usr/local/miniconda/bin/fmriprep --notrack --resource-monitor --skip-bids-validation --md-only-boilerplate --stop-on-first-crash --use-plugin=multi_proc.yml --output-space T1w --force-bbr --use-syn-sdc --fs-license-file=license.txt --fs-subjects-dir=fmripout/freesurfer/sub-TTTEMPSUB --skull-strip-template=NKI --work-dir=fmripworkdir --participant_label=sub-TTTEMPSUB fmripinput fmripout participant

Here is the file structure inside my fmripinput

```
fmripinput
├── dataset_description.json
└── sub-TTTEMPSUB
    └── ses-SSSES
        ├── anat
        │   ├── sub-TTTEMPSUB_ses-SSSES_acq-mprage_run-1_T1w.json
        │   └── sub-TTTEMPSUB_ses-SSSES_acq-mprage_run-1_T1w.nii.gz
        ├── fmap
        │   ├── sub-TTTEMPSUB_ses-SSSES_acq-_run-_magnitude1.nii.gz
        │   ├── sub-TTTEMPSUB_ses-SSSES_acq-_run-_magnitude2.nii.gz
        │   ├── sub-TTTEMPSUB_ses-SSSES_acq-_run-_phase1.json
        │   ├── sub-TTTEMPSUB_ses-SSSES_acq-_run-_phase1.nii.gz
        │   ├── sub-TTTEMPSUB_ses-SSSES_acq-_run-_phase2.json
        │   └── sub-TTTEMPSUB_ses-SSSES_acq-_run-_phase2.nii.gz
        └── func
            ├── sub-TTTEMPSUB_ses-SSSES_task-facerecognition_run-1_bold.json
            └── sub-TTTEMPSUB_ses-SSSES_task-facerecognition_run-1_bold.nii.gz

5 directories, 11 files

```

**Comment by soichih** [comment]
@mgxd 

singularity exec -e -B /home/hayashis/git/app-fmriprep/run.py:/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py docker://poldracklab/fmriprep:1.5.4 /usr/local/miniconda/bin/fmriprep --notrack --resource-monitor --skip-bids-validation --md-only-boilerplate --stop-on-first-crash --use-plugin=multi_proc.yml --output-space T1w --force-bbr --use-syn-sdc --fs-license-file=license.txt --fs-subjects-dir=fmripout/freesurfer/sub-TTTEMPSUB --skull-strip-template=NKI --work-dir=fmripworkdir --participant_label=sub-TTTEMPSUB fmripinput fmripout participant

**Comment by effigies** [comment]
Can you share `/mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripout/fmriprep/sub-TTTEMPSUB/log/20200106-171837_3e4cb4e9-ee73-4f26-9172-d087bb31b223/crash-20200106-171907-hayashis-ds_bold_aparc_std-93acf1c8-0b0c-4a73-bcb9-08a12e2675b7.txt`?

**Comment by soichih** [comment]
@effigies Here is the content of the log.

```
hayashis@dev1:~/git/app-fmriprep/fmripout/fmriprep/sub-TTTEMPSUB/log/20200106-171837_3e4cb4e9-ee73-4f26-9172-d087bb31b223(master*) $ cat crash-20200106-171907-hayashis-ds_bold_aparc_std-93acf1c8-0b0c-4a73-bcb9-08a12e2675b7.txt 
Node: fmriprep_wf.single_subject_TTTEMPSUB_wf.func_preproc_ses_SSSES_task_facerecognition_run_1_wf.func_derivatives_wf.ds_bold_aparc_std
Working directory: /mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripworkdir/fmriprep_wf/single_subject_TTTEMPSUB_wf/func_preproc_ses_SSSES_task_facerecognition_run_1_wf/func_derivatives_wf/ds_bold_aparc_std

Node inputs:

base_directory = /mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripout
check_hdr = True
compress = <undefined>
desc = aparcaseg
extra_values = <undefined>
in_file = <undefined>
keep_dtype = False
meta_dict = <undefined>
source_file = /mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripinput/sub-TTTEMPSUB/ses-SSSES/func/sub-TTTEMPSUB_ses-SSSES_task-facerecognition_run-1_bold.nii.gz
space = <undefined>
suffix = dseg

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/legacymultiproc.py", line 381, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 479, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 585, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 678, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 340, in run
    self._check_mandatory_inputs()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 249, in _check_mandatory_inputs
    raise ValueError(msg)
ValueError: DerivativesDataSink requires a value for input 'in_file'. For a list of required inputs, see DerivativesDataSink.help()

```

**Comment by effigies** [comment]
Okay. I see the issue, but I haven't quite tracked down the bug.

1) `--output-space T1w` means no standard spaces are being specified. This is fine.
2) Somehow `standard_spaces` is non-empty here:

https://github.com/poldracklab/fmriprep/blob/63a661b20ec68e1aa08949d5dd6fd17381ea1d52/fmriprep/workflows/bold/outputs.py#L152

Leading to this section getting run:

https://github.com/poldracklab/fmriprep/blob/63a661b20ec68e1aa08949d5dd6fd17381ea1d52/fmriprep/workflows/bold/outputs.py#L183-L199

So `ds_bold_aparc_std` shouldn't even be getting created, but it is, with no input file. Note that `space` is also undefined, so the workflow is consistent, in that it doesn't think there's a template to be provided.

So the problem lies somewhere around here:

https://github.com/poldracklab/fmriprep/blob/63a661b20ec68e1aa08949d5dd6fd17381ea1d52/fmriprep/workflows/bold/base.py#L278-L280

https://github.com/poldracklab/fmriprep/blob/63a661b20ec68e1aa08949d5dd6fd17381ea1d52/fmriprep/workflows/bold/base.py#L437-L447

My guess is that `std_spaces` is the internal variable for all spaces that need to be resampled to, and we need to update this to be the intersection with the output spaces.

@mgxd WDYT?

**Comment by oesteban** [comment]
I think @effigies is right - @mgxd we should push priority of #1892 up. IMHO, that issue should resolve this bug.

**Comment by effigies** [comment]
@soichih In the short term, using `--output-space T1w MNI152Nlin2009c` will almost certainly resolve the problem, if you just need to get moving again.

**Comment by soichih** [comment]
@effigies @oesteban @mgxd Thanks for the help!

I tried adding MNI152Nlin2009c / MNI152Nlin2009cAsym to the list of spaces, but I can't seem to get around this error message.

```
  File "/usr/local/miniconda/lib/python3.7/site-packages/smriprep/cli/utils.py", line 53, in output_space
    correctly installed and contains the given template identifiers.""".format(template))
ValueError: Template identifier "MNI152Nlin2009cAsym" not found. Please, make sure TemplateFlow is correctly installed and contains the given template identifiers.
```

I am setting it like this..

```
singularity exec docker://poldracklab/fmriprep:1.5.4 /usr/local/miniconda/bin/fmriprep --notrack --resource-monitor --skip-bids-validation --md-only-boilerplate --stop-on-first-crash --use-plugin=multi_proc.yml --output-spaces T1w MNI152Nlin2009cAsym --force-bbr --use-syn-sdc --fs-license-file=license.txt --fs-subjects-dir=fmripout/freesurfer/sub-TTTEMPSUB --skull-strip-template=NKI --work-dir=fmripworkdir --participant_label=sub-TTTEMPSUB fmripinput fmripout participant
```

I tried both --output-space and --output-spaces but neither one worked.. unfortunately. 

By the way, we've been having to use both --output-space to set T1w/fsaverage and --output-spaces to set other spaces. Is this expected?

**Comment by oesteban** [comment]
MNI152Nlin2009cAsym -> MNI152NLin2009cAsym

**Comment by mgxd** [comment]
@effigies you are right, I encountered this same issue when debugging #1915 

@oesteban and I were just discussing the reworking of output spaces and ensuring the proper "internal" normalizations are included so that the workflow always runs regardless of outputs.

**Comment by effigies** [comment]
> By the way, we've been having to use both --output-space to set T1w/fsaverage and --output-spaces to set other spaces. Is this expected?

I think actually you need `--output-spaces` for everything now. `--output-space` and other deprecated arguments were removed in 476e1b2cbb46342386113d96168a7d19c3406c6c.

**Comment by soichih** [comment]
@effigies I tried --output-spaces for all template and it seems to work now with 1.5.4 container. We were having some problems before. As far as volume output goes, everything seems to work now.

I then tested with surface output (--output-spaces fsaverage:den-10k MNI152NLin2009cAsym) 

> singularity exec docker://poldracklab/fmriprep:1.5.4 /usr/local/miniconda/bin/fmriprep --notrack --resource-monitor --skip-bids-validation --md-only-boilerplate --stop-on-first-crash --use-plugin=multi_proc.yml --output-spaces fsaverage:den-10k MNI152NLin2009cAsym --force-bbr --use-syn-sdc --fs-no-reconall --fs-license-file=license.txt --fs-subjects-dir=fmripout/freesurfer/sub-TTTEMPSUB --skull-strip-template=NKI --work-dir=fmripworkdir --participant_label=sub-TTTEMPSUB fmripinput fmripout participant

After running for a few hours, it eventually crashed with this error message.

```
Node: fmriprep_wf.single_subject_TTTEMPSUB_wf.func_preproc_ses_SSSES_task_rest_run_1_wf.carpetplot_wf.select_std
Working directory: /mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripworkdir/fmriprep_wf/single_subject_TTTEMPSUB_wf/func_preproc_ses_SSSES_task_rest_run_1_wf/carpetplot_wf/select_std

Node inputs:

key = MNI152NLin2009cAsym
keys = ['fsaverage', 'MNI152NLin2009cAsym']
std2anat_xfm = ['/mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripworkdir/fmriprep_wf/single_subject_TTTEMPSUB_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin2009cAsym./registration/ants_t1_to_mniInverseComposite.h5']

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/legacymultiproc.py", line 381, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 479, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 585, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 678, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 384, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
    predicted_outputs = self._list_outputs()  # Predictions from _list_outputs
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/utility.py", line 147, in _list_outputs
    for k in self._fields}
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/utility.py", line 147, in <dictcomp>
    for k in self._fields}
IndexError: list index out of range

```

**Comment by effigies** [comment]
Okay. That's https://github.com/poldracklab/fmriprep/blob/7e5b2f1288f53ed54413d997a615a91a999a3597/fmriprep/workflows/bold/confounds.py#L476-L479

which uses [KeySelect](https://github.com/poldracklab/niworkflows/blob/master/niworkflows/interfaces/utility.py).

It looks like it's expecting `std2anat_xfm` to be a two-element list, with a value for each `fsaverage` and `MNI152NLin2009cAsym`, and it's instead a one-element list.

This looks like a bug where `fsaverage` should have been filtered out.

@mgxd @oesteban Will this be covered in an existing issue/PR or should I open a new one?

**Comment by mgxd** [comment]
this falls under the reworking of output spaces (#1920) and should be covered there.

**Comment by effigies** [comment]
I think that may be a misfired reference. But anyway, let me know if I can help push on that fix.

**Comment by effigies** [comment]
@soichih We determined that the full fix to your issue may take a while, so I'm going to be working on a short-term fix while Mathias works toward the long-term solution in #1915. Working now to replicate on a small dataset. I'll aim to have a fix by Monday.

**Comment by soichih** [comment]
@effigies Thanks for the update, and thank you all for working on this issue.

**Comment by effigies** [comment]
@soichih Proposed #1932. It turned out to be ridiculously easy. If you're able to patch in a branch (not as easy in Singularity), then you can try that branch, to see if anything else comes up.

I am seeing the problem, though, that no fsaverage outputs are being generated.

While I'm here, I'd just note that there's an issue with two of your options:

* `--fs-no-reconall` will not attempt to use FreeSurfer surfaces at all.
* `--fs-subjects-dir=fmripout/freesurfer/sub-TTTEMPSUB` should point to the subjects directory, not the individual subject within the subjects directory.

It seems that there's some ambiguity here and it would be good to figure out the set of behaviors we want to support and an intuitive way to access them with flags. See #1930.

**Comment by soichih** [comment]
I will try overriding base.py with the PR version by ..

```
singularity exec -e \
    docker://poldracklab/fmriprep:1.5.4 \
    -e -B $(pwd)/base.py:/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py \
    /usr/local/miniconda/bin/fmriprep ...
```

I think I had to add --fs-no--reconall to workaround some problem, but maybe it was caused by setting --fs-subjects-dir to a incorrect path? I just removed --fs-no-reconall and updated --fs-subjects path - along with the patched version of base.py. I will test it and report back to you.

**Comment by effigies** [comment]
I think you can just drop the `--fs-subjects-dir`, anyway, as it will default to `<OUTPUT_DIR>/freesurfer`.

**Comment by soichih** [comment]
OK. I've droped both --fs-no-reconall and --fs-subjects-dir options.

I've fed `--output-spaces fsaverage:den-10k` to the container and it's failing with this error message.

```
/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py:547: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  plugin_settings = loadyml(f)
200113-19:35:13,947 nipype.workflow IMPORTANT:
	 
    Running fMRIPREP version 1.5.4:
      * BIDS dataset path: /mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripinput.
      * Participant list: ['TTTEMPSUB'].
      * Run identifier: 20200113-193513_1bfa4140-f059-4c32-b6ea-9163db2f05e5.
    
200113-19:35:14,585 nipype.utils INFO:
	 Running nipype version 1.3.1 (latest: 1.4.0)
200113-19:35:17,32 nipype.workflow IMPORTANT:
	 Creating bold processing workflow for "/mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripinput/sub-TTTEMPSUB/ses-SSSES/func/sub-TTTEMPSUB_ses-SSSES_task-rest_run-1_bold.nii.gz" (0.11 GB / 193 TRs). Memory resampled/largemem=0.44/0.65 GB.
200113-19:35:17,52 nipype.workflow IMPORTANT:
	 No single-band-reference found for sub-TTTEMPSUB_ses-SSSES_task-rest_run-1_bold.nii.gz
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 669, in build_workflow
    work_dir=str(work_dir),
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 265, in init_fmriprep_wf
    use_syn=use_syn,
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 622, in init_single_subject_wf
    use_syn=use_syn,
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py", line 454, in init_func_preproc_wf
    fslr_density=fslr_density,
TypeError: init_func_derivatives_wf() got an unexpected keyword argument 'fslr_density'
```

I will try without specifying density attribute.

**Comment by effigies** [comment]
Try re-fetching the branch. I realized I'd based it off the `master` branch, not `maint/1.5.x`, and this is going to aim to be a bug-fix release.

**Comment by mgxd** [comment]
Yup, support for density labels of the `fsaverage` template are not fully implemented yet - that will change in the output spaces rework.

**Comment by soichih** [comment]
Ok. I 've re-fetched the bold.py from the PR, and updated the space to --output-spaces fsaverage5

Now it's saying `ds_bold_aparc_std failed to run`

```
singularity exec -e -B /home/hayashis/git/app-fmriprep/base.py:/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py docker://poldracklab/fmriprep:1.5.4 /usr/local/miniconda/bin/fmriprep --notrack --resource-monitor --skip-bids-validation --md-only-boilerplate --stop-on-first-crash --use-plugin=multi_proc.yml --output-spaces fsaverage5 --force-bbr --use-syn-sdc --fs-license-file=license.txt --skull-strip-template=NKI --work-dir=fmripworkdir --participant_label=sub-TTTEMPSUB fmripinput fmripout participant
Docker image path: index.docker.io/poldracklab/fmriprep:1.5.4
Cache folder set to /mnt/scratch/hayashis/singularity/cache/docker
...
200113-19:55:20,34 nipype.workflow WARNING:
	 Storing result file without outputs
200113-19:55:20,35 nipype.workflow WARNING:
	 [Node] Error on "fmriprep_wf.single_subject_TTTEMPSUB_wf.func_preproc_ses_SSSES_task_rest_run_1_wf.func_derivatives_wf.ds_bold_aparc_std" (/mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripworkdir/fmriprep_wf/single_subject_TTTEMPSUB_wf/func_preproc_ses_SSSES_task_rest_run_1_wf/func_derivatives_wf/ds_bold_aparc_std)
200113-19:55:20,37 nipype.workflow ERROR:
	 Node ds_bold_aparc_std failed to run on host dev1.soichi.us.
200113-19:55:20,87 nipype.workflow ERROR:
	 Saving crash info to /mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripout/fmriprep/sub-TTTEMPSUB/log/20200113-195451_5d481ed8-f7f5-4a3c-ab13-b1dc4cda1e94/crash-20200113-195520-hayashis-ds_bold_aparc_std-3b2e6e3c-f696-4b1a-b94a-7063de078ae1.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/legacymultiproc.py", line 381, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 479, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 585, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 678, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 340, in run
    self._check_mandatory_inputs()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 249, in _check_mandatory_inputs
    raise ValueError(msg)
ValueError: DerivativesDataSink requires a value for input 'in_file'. For a list of required inputs, see DerivativesDataSink.help()

```

**Comment by effigies** [comment]
It looks like you dropped the MNI output space. Can you re-add it and verify that this works? I'll look into fixing the above crash as well.

```
singularity exec -e \
    -B /home/hayashis/git/app-fmriprep/base.py:/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py \
    docker://poldracklab/fmriprep:1.5.4 /usr/local/miniconda/bin/fmriprep \
    --notrack --resource-monitor --skip-bids-validation --md-only-boilerplate \
    --stop-on-first-crash --use-plugin=multi_proc.yml \
    --output-spaces fsaverage5 MNI152NLin2009cAsym \
    --force-bbr --use-syn-sdc --fs-license-file=license.txt \
    --skull-strip-template=NKI --work-dir=fmripworkdir \
    --participant_label=sub-TTTEMPSUB fmripinput fmripout participant
```

**Comment by soichih** [comment]
Thanks. I've put it back. I am not sure why I removed it. The process seems to be progressing now. I will let you know if it finishes this time.

@mgxd So I should stay away from setting the density modifier? What are the spaces that are currerntly supported other than fsaverage5?

**Comment by effigies** [comment]
@oesteban @mgxd I don't really remember. What happened to auto-inserting MNI into output spaces? Because failing to explicitly list it now has several failures, such as the aparc/aseg outputs (easy to fix) such as SyN-SDC not being able to run (no template from sMRIPrep to query).

**Comment by mgxd** [comment]
I believe the MNI template is auto inserted only if no `--output-spaces` are provided, or CIFTI/ICA flags are provided.

**Comment by effigies** [comment]
@soichih I've pushed 1.5.5. You'll still need to include `MNI152NLin2009c` in your output spaces.

Let's see how that goes, and open a new issue with any bugs you encounter going forward.

**Comment by soichih** [comment]
Thanks. I will switch to container v1.5.5 and test it.
