### ISSUE TITLE
Suggested: ignore anatomical data from sessions without functional sessions

### ISSUE THREAD

**Issue by dorianps** [poldracklab/fmriprep#1925]
My understanding so far is that fmriprep creates a subject anatomical template with all the T1w data found in the bids sessions. However, for studies where fMRI is run only on specific sessions this creates an unnecessary bias. My suggestion would be for fmriprep to ignore sessions with no functional data when creating the anatomical average (aka the subject template).

In our case, we have a study with 7 longitudinal sessions, but only the last 3-4 have fMRI. So the template built with all sessions for a certain subject would be biased towards the first 3 years, when the participants were anatomically more healthy (less atrophy).

Dorian

**Comment by mgxd** [comment]
This sounds reasonable - perhaps could be implemented within #1175

**Comment by oesteban** [comment]
I guess the issue Mathias mentioned above could help address this one, but probably there's also a need for better fine-grained filtering of the BIDS dataset (e.g., @bpinsard's work on #1770)

**Comment by mgxd** [comment]
The addition of `--bids-filter-file` should solve this, as you can now exclude certain files / sessions.
