### ISSUE TITLE
Error while running fmriprep-docker

### ISSUE THREAD

**Issue by Hershkovitz-hub** [poldracklab/fmriprep#1926]
Hi all,
I'm trying to run fmriprep-docker but keep getting an error while initiating it:
![image](https://user-images.githubusercontent.com/52285382/71811723-1ab05e00-307e-11ea-8216-502b508f040d.png)

("docker: Error response from daemon: error while creating mount source path '/usr/local/freesurfer/license.txt': mkdir /usr/local/freesurfer: read-only file system.")
I've tried running it with -u $UID as well and with sudo permissions, but still got the same result.
Would appreciate any help.
Thanks!

**Comment by oesteban** [comment]
Hi @Hershkovitz-hub, you need to tell `fmriprep-docker` where your FreeSurfer license is found in the host, e.g.:
```
fmriprep-docker --fs-license-file $HOME/license.txt ...
```
please check https://fmriprep.readthedocs.io/en/latest/docker.html and https://fmriprep.readthedocs.io/en/latest/usage.html#the-freesurfer-license

**Comment by mgxd** [comment]
Feel free to reopen this if there are still issues
