### ISSUE TITLE
is fmriprep using the latest BIDS validator?

### ISSUE THREAD

**Issue by irisgroen** [poldracklab/fmriprep#1929]
I am processing (fmriprep version 1.5.4)a dataset that has _phase.nii.gz files, which is supported by the latest version of BIDS (see https://github.com/bids-standard/bids-validator/issues/834). When I validate my data with the online BIDS-validator I get no errors, but the BIDS-validator in fmriprep gives an error about _phase.nii.gz images not being included (see below). This makes me think fmriprep is not using the latest BIDS validator version (I think the _phase extension was introduced in BIDS 1.3.4). If not, any thoughts on what may be the problem? Thanks.

```
Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
	1: [ERR] Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)
		./sub-som748/ses-nyu3t01/func/sub-som748_ses-nyu3t01_task-hrfpattern_acq-normal_run-01_phase.json
			Evidence: sub-som748_ses-nyu3t01_task-hrfpattern_acq-normal_run-01_phase.json
		./sub-som748/ses-nyu3t01/func/sub-som748_ses-nyu3t01_task-hrfpattern_acq-normal_run-01_phase.nii.gz
			Evidence: sub-som748_ses-nyu3t01_task-hrfpattern_acq-normal_run-01_phase.nii.gz
		./sub-som748/ses-nyu3t01/func/sub-som748_ses-nyu3t01_task-prf_acq-normal_run-01_phase.json
			Evidence: sub-som748_ses-nyu3t01_task-prf_acq-normal_run-01_phase.json
		./sub-som748/ses-nyu3t01/func/sub-som748_ses-nyu3t01_task-prf_acq-normal_run-01_phase.nii.gz
			Evidence: sub-som748_ses-nyu3t01_task-prf_acq-normal_run-01_phase.nii.gz
		./sub-som748/ses-nyu3t01/func/sub-som748_ses-nyu3t01_task-prf_acq-normal_run-02_phase.json
			Evidence: sub-som748_ses-nyu3t01_task-prf_acq-normal_run-02_phase.json
		./sub-som748/ses-nyu3t01/func/sub-som748_ses-nyu3t01_task-prf_acq-normal_run-02_phase.nii.gz
			Evidence: sub-som748_ses-nyu3t01_task-prf_acq-normal_run-02_phase.nii.gz
		./sub-som748/ses-nyu3t01/func/sub-som748_ses-nyu3t01_task-spatialpattern_acq-normal_run-01_phase.json
			Evidence: sub-som748_ses-nyu3t01_task-spatialpattern_acq-normal_run-01_phase.json
		./sub-som748/ses-nyu3t01/func/sub-som748_ses-nyu3t01_task-spatialpattern_acq-normal_run-01_phase.nii.gz
			Evidence: sub-som748_ses-nyu3t01_task-spatialpattern_acq-normal_run-01_phase.nii.gz
		./sub-som748/ses-nyu3t01/func/sub-som748_ses-nyu3t01_task-spatialpattern_acq-normal_run-02_phase.json
			Evidence: sub-som748_ses-nyu3t01_task-spatialpattern_acq-normal_run-02_phase.json
		./sub-som748/ses-nyu3t01/func/sub-som748_ses-nyu3t01_task-spatialpattern_acq-normal_run-02_phase.nii.gz
			Evidence: sub-som748_ses-nyu3t01_task-spatialpattern_acq-normal_run-02_phase.nii.gz
		... and 12 more files having this issue (Use --verbose to see them all).
```

**Comment by effigies** [comment]
Good catch. We should update the validator version in the Dockerfile. Would you care to make a PR?

In the meantime, you can skip bids validation.

**Comment by irisgroen** [comment]
Thanks for the quick response - I can try to make a PR, but I have no expertise with programming a Docker so I'm worried I might not do it right. Would this be the only relevant part to update (in DockerFile)? Would it be possible (and desirable) to pull the latest version, given that the validator is updated regularly it seems?

```
# Installing bids-validator
RUN npm install -g bids-validator@1.2.3
```

Currently @noahbenson is working on a PR of fmriprep where we introduce the option to initialize registration using the header (to solve https://github.com/poldracklab/fmriprep/issues/1842), he could potentially add it to that one, but perhaps you'd prefer to have PRs address separate issues?

**Comment by effigies** [comment]
I think the reasoning in general is that we pin specific versions in the Dockerfile as a way of documenting the versions of software, improving reproducibility.

I'm not sure that this reasoning has as much validity for the validator, since it doesn't affect the results of processing, though it should be easy to query which one is installed...

**Comment by mgxd** [comment]
@irisgroen yes, I believe it would just be those lines. would you like to open a PR upgrading the validator to the latest version (1.4.0)?

**Comment by irisgroen** [comment]
OK - I just forked and made the change, am now testing if the Docker builds successfully using this new version, if so I'll create the PR.
