### ISSUE TITLE
Fix year in changelog

### ISSUE THREAD

**Issue by dorianps** [poldracklab/fmriprep#1936]
Should be 2020... Happy to make a PR but this should be fairly easy to commit on your side.

![image](https://user-images.githubusercontent.com/9083517/72568606-85d01080-3886-11ea-9d85-bdc0606416a6.png)

In https://github.com/poldracklab/fmriprep/blob/master/CHANGES.rst

**Comment by oesteban** [comment]
I guess we should actually fix the update script

**Comment by effigies** [comment]
I think I did it by hand. I forget about the `.maint` directory.
