### ISSUE TITLE
How to use session labels?

### ISSUE THREAD

**Issue by jbruegge** [poldracklab/fmriprep#1938]
Hi there,

I would like to run fMRIPrep on only one out of several sessions, but I cannot figure out how to define the session that should be run. So far I have tried the flags -s --session-label --session-id, but none of them seem to work. It says “unrecognized arguments: --session-label ses-T1” (for example).

I am trying to run the following command line (which works fine if I don’t use the session flag):
`docker run --rm -e DOCKER_VERSION_8395080871=19.03.2 -v /home/jbruegge/freesurfer_liense_file/license.txt:/opt/freesurfer/license.txt:ro -v /data/TIMES/patients:/data:ro -v /data/TIMES/patients/derivatives/with_freesurfer:/out poldracklab/fmriprep:1.5.4 /data /out participant --participant_label sub-01 --session-label ses-T1 --output-spaces MNI152NLin6Asym fsaverage`

I also tried this version (with all flags I mentioned above), but it also didn’t work. The error is exactly the same.:
`docker run --rm -e DOCKER_VERSION_8395080871=19.03.2 -v /home/jbruegge/freesurfer_liense_file/license.txt:/opt/freesurfer/license.txt:ro -v /data/TIMES/patients:/data:ro -v /data/TIMES/patients/derivatives/with_freesurfer:/out poldracklab/fmriprep:1.5.4 /data /out participant --participant_label sub-01 session --session-label ses-T1 --output-spaces MNI152NLin6Asym fsaverage`

So could you please tell me how to properly specify the session? Thank you!

Cheers,
Julia

PS: I already posted on Neurostars but have not received a reply yet. So since I need the answer quite urgently, I am re-posting here. sorry for the repetition.

**Comment by mgxd** [comment]
At the moment, selective session processing is not implemented - see https://github.com/poldracklab/fmriprep/issues/1175.

**Comment by yongninglei** [comment]
is this issue solved now?
