### ISSUE TITLE
Missing carpet plot in report

### ISSUE THREAD

**Issue by PaulZhutovsky** [poldracklab/fmriprep#1940]
Hi,

I preprocessed my resting-state data with fmriprep 1.5.3 using the singularity container. 

My fmriprep command (from within the container) was:
`fmriprep /mnt/bids_data /mnt/bids_data/derivatives participant \
	--skip_bids_validation --n_cpus 16 --omp-nthreads 16 --force-bbr \
	--ignore fieldmaps slicetiming sbref --output-spaces MNI152NLin6Asym:res-2 \
	--use-aroma --fs-license-file license.txt --fs-no-reconall \
	--work-dir /mnt/code/resting_state/fmriprep_preprocessing/workdir`

(the workdir was empty)

I think everything ran through without problems/errors. However, if I look into the html reports I noticed that the carpet plots for the fMRI data are missing. There are also no corresponding svg files in the subjects' figures folder. 

I don't think I will be able to get the carpet plots without re-running the proprecessing but I wanted to report this anyway just in case that it hasn't been reported/fixed yet in the newer version of fmriprep.

Cheers,
Paul

**Comment by effigies** [comment]
Carpetplots are only generated for the MNI152NLin2009cAsym output space right now.

**Comment by effigies** [comment]
I think it's mostly a question of providing an atlas in template flow, but @oesteban will be able to give a better response.

**Comment by PaulZhutovsky** [comment]
I'm sorry but I'm still a bit confused why the carpet plot can only be made if MNI152NLin2009cAsym is specified as the output space. All the confounds, etc. are calculated regardless of space, and masks for GM/WM/CSF, etc. are available for MNI152NLin6Asym as well. And MNI152NLin6Asym is in [templateflow](https://github.com/templateflow/tpl-MNI152NLin6Asym) if I'm seeing it correctly?

It would be really nice if this issue could be addressed or documentation about the lack of this feature for all spaces but MNI152NLin2009cAsym could be added.

**Comment by mgxd** [comment]
at the moment, the parcellation resamplings are hardcoded for only MNI152NLin2009cAsym

https://github.com/poldracklab/fmriprep/blob/26613de407ab224c5f50fae7dbde8c25153b478c/fmriprep/workflows/bold/confounds.py#L482-L484

Though, I'm not sure why this cannot be extended to include MNI152NLin6Asym as well. Let's see what @oesteban thinks

**Comment by oesteban** [comment]
@PaulZhutovsky the carpetplot uses some kind of Frankenstein segmentation I built off of the Harvard-Oxford atlas and the DK atlas from freesurfer. It is only on the space of MNI152NLin2009cAsym.

I would love to see this more flexibly handled (among many other changes to the carpetplot we have in mind, e.g., poldracklab/niworkflows#254, #1120). If the community agrees this is a priority, we'll push it up in the queue. But for now, we are quite deep in the weeds with other refactors.

In particular, poldracklab/niworkflows#254 would entail a prior-free implementation and probably allowing custom segmentations to be set. I would suggest following up there in regards to this particular issue.

On a related note, #1892 will work out internal/user-required spaces. At this point, by adding ``MNI152NLin2009cAsym`` to ``--output-spaces`` you will get the corresponding outputs. After #1892 is addressed, you'll get carpetplot without having a lot of output files you did not ask for.

Therefore, I'm inclined to close this one as the core integration problem (which is indeed a bug) will be solved nicely within the context of #1892. For improvement to the carpetplot itself, please feel free to open issues suggesting new features on https://github.com/poldracklab/niworkflows

Please feel free to reopen if this response did not address all the issues.
