### ISSUE TITLE
`--use-syn-sdc` no longer respected when `--ignore fieldmaps` is passed

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#1941]
Prior to 1.5.3, `--use-syn-sdc --ignore fieldmaps` would ignore fieldmaps, and use SyN-SDC.

As of 9e2320365467f7c3d35d43de4b1cc8dad3636975 (#1886), access to [any SDC algorithm](https://github.com/poldracklab/fmriprep/commit/9e2320365467f7c3d35d43de4b1cc8dad3636975#diff-e705526667f071ca0c3b04c2bd96272bR351-R354) is restricted by `--ignore fieldmaps`.

This leaves users who would prefer to use SyN over fieldmaps stranded.

Ref: https://neurostars.org/t/syn-sdc-not-working-with-more-recent-fmriprep-version/5824

**Comment by effigies** [comment]
This appears to still occur in 20.1.0rc1.

**Comment by effigies** [comment]
From the reports:

> ## Functional
> ### Reports for: task repeatchange, run 1.
> #### Summary
> * Repetition time (TR): 3.38s
> * Phase-encoding (PE) direction: Anterior-Posterior
> * Slice timing correction: Not applied
> * Susceptibility distortion correction: None

...

> ## About
> fMRIPrep version: 20.1.0rc1
> fMRIPrep command: `/usr/local/miniconda/bin/fmriprep sourcedata/ . participant --participant-label 02 --output-spaces anat fsnative --cifti-output --ignore fieldmaps --use-syn-sdc -vv --fs-license-file /projectnb/bohland/repeat_change/worktrees/02/tokens/freesurfer_license.txt --nthreads 16 --omp-nthreads 8 --mem-mb 48000`
> Date preprocessed: 2020-04-09 21:45:06 -0400

**Comment by effigies** [comment]
@oesteban Could this be because the CLI flag is `--use-syn-sdc`, and the new config variable is `use_syn`?

https://github.com/poldracklab/fmriprep/blob/549e7876c8ffdfd2a2472d22cb3dcf3c0d22fab7/fmriprep/cli/parser.py#L234-L235

https://github.com/poldracklab/fmriprep/blob/549e7876c8ffdfd2a2472d22cb3dcf3c0d22fab7/fmriprep/config.py#L459-L461

Or do we account for this mismatch somewhere?

**Comment by mgxd** [comment]
@effigies that seems like the case - I'll double check the config options to see if there are any other deviations from the parser
