### ISSUE TITLE
"." being replaces by unicode symbo in `anat_norm_wf` node `split_desc.aI.a0`

### ISSUE THREAD

**Issue by htwangtw** [poldracklab/fmriprep#1944]
As title, I have been running into this issue in the version 1.5.5 container version, running on a windows machine.  

The process will always start with outputting this error:
```
Node: fmriprep_wf.single_subject_405627_wf.anat_preproc_wf.anat_norm_wf.split_desc
Working directory: /scratch/fmriprep_wf/single_subject_405627_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin2009cAsym./split_desc

Node inputs:

template = ('MNI152NLin2009cAsym', {})

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 336, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 507, in run
    os.makedirs(outdir, exist_ok=True)
  File "/usr/local/miniconda/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/fmriprep_wf/single_subject_405627_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin2009cAsym./split_desc'


When creating this crashfile, the results file corresponding
to the node could not be found.
```

The weird thing about this error message is, when I check the directory in the error message, I see a unicode dot. 
![image](https://user-images.githubusercontent.com/13743617/72918834-413ced00-3d3e-11ea-9444-51690b7ba110.png)
I am not sure how this happened and have yet resolved the actual problem. 
Does it has to do with the input in output spaces?

Thanks in advance.
Hao-Ting

**Comment by effigies** [comment]
This looks like Windows is refusing the `<dirname>./` format and forcing it to some other code point, forcing the name to be different from the expected one. (It's unclear to me why we're adding a `.` anyway. I can look at that if nobody chimes in.)

Are you able to rename the directory to have `.` instead?

**Comment by mgxd** [comment]
I believe the `.` is added as a result of setting the tuple `(str, {})` as nipype iterables. IIRC, the `.` is meant to separate elements, and since the dict is empty, nipype doesn't use a value

**Comment by htwangtw** [comment]
@effigies yes I can with WSL. That leads to a location not accessible error on the windows file browser.  There's nothing in the directory. 
@mgxd That makes sense.
And after a bit more poking around it seems to be a problem of the default input of `--output-spaces`
It is temporarily solved by specifying the value as `MNI152NLin2009cAsym:res-2`

**Comment by mgxd** [comment]
@htwangtw we have reworked output spaces in the latest release (20.0.0) - please reopen this if the issue persists
