### ISSUE TITLE
Midbrain dropout from overly aggressive masking

### ISSUE THREAD

**Issue by skebaas** [poldracklab/fmriprep#1947]
Hello,

We've been having an issue with a couple of participants where we are experiencing a dropout in the midbrain.  We traced it to be happening at the 2nd pass of the skullstrip_bold.  We wanted to know if there was a way to decrease the intensity of the masking?

Thank you,
Alex

**Comment by oesteban** [comment]
Could you post some figures from your html reports?

**Comment by mgxd** [comment]
Closing this as it's gone stale, please reopen if you are still running into issues
