### ISSUE TITLE
fmriprep going in to an infinite loop

### ISSUE THREAD

**Issue by qasim85** [poldracklab/fmriprep#1954]
Hello
I am running fmriprep 1.4.1, and some of my subjects are taking an infinite amount of time to finish. i have a feeling that some subjects are  going in to a loop and getting stuck. Here is my command call
#!/bin/bash
#SBATCH --time=2-00:00:00
#SBATCH --mem=50GB
#SBATCH --cpus-per-task=4
#SBATCH -J fmriprep

base=$1
args=($@)
subjs=(${args[@]:1})

module add openmind/singularity/3.5.0

# index slurm array to grab subject
subject=${subjs[${SLURM_ARRAY_TASK_ID}]}
#plugin=/nobackup/scratch/Wed/qbukhari/sad/
# assign working directory
scratch=/nobackup/scratch/Wed/qbukhari/fmriprep_scratch_SAD
if [ ! -d $scratch ]; then 
    mkdir -p ${scratch}
fi

IMG=/storage/gablab001/data/singularity-images/fmriprep-v1.4.1.sif 
export FS_LICENSE=$HOME/freesurfer_license.txt

cmd="singularity run -B /om2/user/mathiasg/miniconda/lib/python3.6/site-packages/yaml:/usr/local/miniconda/lib/python3.6/site-packages/yaml -B ${scratch}:/workdir -B ${base}:/mnt -B ${base}:/output -B ${out3}:/output2 -B /tmp:/tmp -e $IMG /mnt /output participant --participant_label $subject --output-spaces MNI152NLin6Asym:res-2 MNI152NLin2009cAsym fsaverage5 --cifti-output --ignore slicetiming --use-aroma -w /workdir --fs-license-file /mnt/freesurfer_license.txt --mem_mb 50000 --use-plugin /mnt/plugin.yml --nthreads 2"

echo Submitted job for: ${subject}
echo $'Command :\n'${cmd}

${cmd}
echo "FINISHED"

The output slurm file is huge. But I am pasting some of the  last parts of it

200126-13:53:04,334 nipype.interface INFO:
	 stderr 2020-01-26T13:53:04.334170:++ 3dvolreg: AFNI version=Debian-16.2.07~dfsg.1-5~nd16.04+1 (Jun 12 2017) [64-bit]
200126-13:53:04,334 nipype.interface INFO:
	 stderr 2020-01-26T13:53:04.334170:++ Authored by: RW Cox
200126-13:53:04,356 nipype.interface INFO:
	 stderr 2020-01-26T13:53:04.356214:*+ WARNING:   If you are performing spatial transformations on an oblique dset, 
200126-13:53:04,356 nipype.interface INFO:
	 stderr 2020-01-26T13:53:04.356214:  such as /workdir/fmriprep_wf/single_subject_SAD037_wf/func_preproc_ses_pre_task_dotprobe_run_1_wf/bold_reference_wf/gen_ref/slice.nii.gz,
200126-13:53:04,356 nipype.interface INFO:
	 stderr 2020-01-26T13:53:04.356214:  or viewing/combining it with volumes of differing obliquity,
200126-13:53:04,356 nipype.interface INFO:
	 stderr 2020-01-26T13:53:04.356214:  you should consider running: 
200126-13:53:04,356 nipype.interface INFO:
	 stderr 2020-01-26T13:53:04.356214:     3dWarp -deoblique 
200126-13:53:04,357 nipype.interface INFO:
	 stderr 2020-01-26T13:53:04.356214:  on this and  other oblique datasets in the same session.
200126-13:53:04,357 nipype.interface INFO:
	 stderr 2020-01-26T13:53:04.356214: See 3dWarp -help for details.
200126-13:53:04,357 nipype.interface INFO:
	 stderr 2020-01-26T13:53:04.356214:++ Oblique dataset:/workdir/fmriprep_wf/single_subject_SAD037_wf/func_preproc_ses_pre_task_dotprobe_run_1_wf/bold_reference_wf/gen_ref/slice.nii.gz is 18.438993 degrees from plumb.
200126-13:53:04,357 nipype.interface INFO:
	 stderr 2020-01-26T13:53:04.357414:++ Coarse del was 10, replaced with 3
200126-13:53:23,798 nipype.interface INFO:
	 stderr 2020-01-26T13:53:23.798462:++ Max displacement in automask = 0.32 (mm) at sub-brick 12
200126-13:53:23,798 nipype.interface INFO:
	 stderr 2020-01-26T13:53:23.798462:++ Max delta displ  in automask = 0.56 (mm) at sub-brick 14
200126-13:53:26,294 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_SAD037_wf.func_preproc_ses_pre_task_dotprobe_run_1_wf.bold_reference_wf.gen_ref".
200126-13:53:27,660 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_SAD037_wf.func_preproc_ses_pre_task_dotprobe_run_1_wf.bold_hmc_wf.mcflirt" in "/workdir/fmriprep_wf/single_subject_SAD037_wf/func_preproc_ses_pre_task_dotprobe_run_1_wf/bold_hmc_wf/mcflirt".
200126-13:53:27,673 nipype.workflow INFO:
	 [Node] Running "mcflirt" ("nipype.interfaces.fsl.preprocess.MCFLIRT"), a CommandLine Interface with command:
mcflirt -in /mnt/sub-SAD037/ses-pre/func/sub-SAD037_ses-pre_task-dotprobe_run-1_bold.nii.gz -out /workdir/fmriprep_wf/single_subject_SAD037_wf/func_preproc_ses_pre_task_dotprobe_run_1_wf/bold_hmc_wf/mcflirt/sub-SAD037_ses-pre_task-dotprobe_run-1_bold_mcf.nii.gz -reffile /workdir/fmriprep_wf/single_subject_SAD037_wf/func_preproc_ses_pre_task_dotprobe_run_1_wf/bold_reference_wf/gen_ref/ref_bold.nii.gz -mats -plots
200126-13:54:21,973 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_SAD037_wf.func_preproc_ses_pre_task_dotprobe_run_1_wf.bold_hmc_wf.mcflirt".
200126-13:54:27,155 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_SAD037_wf.func_preproc_ses_pre_task_dotprobe_run_1_wf.bold_hmc_wf.normalize_motion" in "/workdir/fmriprep_wf/single_subject_SAD037_wf/func_preproc_ses_pre_task_dotprobe_run_1_wf/bold_hmc_wf/normalize_motion".
200126-13:54:27,205 nipype.workflow INFO:
	 [Node] Running "normalize_motion" ("niworkflows.interfaces.utils.NormalizeMotionParams")
200126-13:54:27,232 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_SAD037_wf.func_preproc_ses_pre_task_dotprobe_run_1_wf.bold_hmc_wf.normalize_motion".
200126-13:54:29,961 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_SAD037_wf.func_preproc_ses_pre_task_dotprobe_run_1_wf.bold_confounds_wf.fdisp" in "/workdir/fmriprep_wf/single_subject_SAD037_wf/func_preproc_ses_pre_task_dotprobe_run_1_wf/bold_confounds_wf/fdisp".
200126-13:54:29,972 nipype.workflow INFO:
	 [Node] Running "fdisp" ("nipype.algorithms.confounds.FramewiseDisplacement")
200126-13:54:30,78 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_SAD037_wf.func_preproc_ses_pre_task_dotprobe_run_1_wf.bold_confounds_wf.fdisp".
200126-13:54:35,147 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_SAD037_wf.func_preproc_ses_pre_task_dotprobe_run_1_wf.bold_hmc_wf.fsl2itk" in "/workdir/fmriprep_wf/single_subject_SAD037_wf/func_preproc_ses_pre_task_dotprobe_run_1_wf/bold_hmc_wf/fsl2itk".
200126-13:54:35,176 nipype.workflow INFO:
	 [Node] Running "fsl2itk" ("niworkflows.interfaces.itk.MCFLIRT2ITK")
200126-13:55:21,289 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_SAD037_wf.func_preproc_ses_pre_task_dotprobe_run_1_wf.bold_hmc_wf.fsl2itk".
200126-13:55:27,344 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_SAD037_wf.func_preproc_ses_pre_task_dotprobe_run_1_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.init_aff" in "/workdir/fmriprep_wf/single_subject_SAD037_wf/func_preproc_ses_pre_task_dotprobe_run_1_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/init_aff".
200126-13:55:27,357 nipype.workflow INFO:
	 [Node] Running "init_aff" ("niworkflows.interfaces.ants.AI"), a CommandLine Interface with command:
antsAI -c [10,0.000001,10] -d 3 -x /home/qbukhari/.cache/templateflow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_desc-brain_mask.nii.gz -m Mattes[/home/qbukhari/.cache/templateflow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_desc-fMRIPrep_boldref.nii.gz,/workdir/fmriprep_wf/single_subject_SAD037_wf/func_preproc_ses_pre_task_dotprobe_run_1_wf/bold_reference_wf/gen_ref/ref_bold.nii.gz,32,Regular,0.200000] -o initialization.mat -p 0 -s [20.000000,0.120000] -t Affine[0.100000] -v 1
200126-13:55:43,520 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_SAD037_wf.func_preproc_ses_pre_task_dotprobe_run_1_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.init_aff".
200126-13:55:49,88 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_SAD037_wf.func_preproc_ses_pre_task_dotprobe_run_1_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.norm" in "/workdir/fmriprep_wf/single_subject_SAD037_wf/func_preproc_ses_pre_task_dotprobe_run_1_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/norm".
200126-13:55:49,103 nipype.workflow INFO:
	 [Node] Running "norm" ("niworkflows.interfaces.fixes.FixHeaderRegistration"), a CommandLine Interface with command:
antsRegistration --collapse-output-transforms 1 --dimensionality 3 --float 1 --initial-moving-transform [ /workdir/fmriprep_wf/single_subject_SAD037_wf/func_preproc_ses_pre_task_dotprobe_run_1_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/init_aff/initialization.mat, 0 ] --initialize-transforms-per-stage 0 --interpolation Linear --output transform --transform Affine[ 0.1 ] --metric Mattes[ /home/qbukhari/.cache/templateflow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_desc-fMRIPrep_boldref.nii.gz, /workdir/fmriprep_wf/single_subject_SAD037_wf/func_preproc_ses_pre_task_dotprobe_run_1_wf/bold_reference_wf/gen_ref/ref_bold.nii.gz, 1, 64, Random, 0.2 ] --convergence [ 200, 1e-09, 10 ] --smoothing-sigmas 2.0mm --shrink-factors 2 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 --winsorize-image-intensities [ 0.05, 0.98 ]  --write-composite-transform 0
200126-13:55:54,918 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_SAD037_wf.func_preproc_ses_pre_task_dotprobe_run_1_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.norm".
200126-13:55:59,57 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_SAD037_wf.func_preproc_ses_pre_task_dotprobe_run_1_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.map_brainmask" in "/workdir/fmriprep_wf/single_subject_SAD037_wf/func_preproc_ses_pre_task_dotprobe_run_1_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/map_brainmask".
200126-13:55:59,69 nipype.workflow INFO:
	 [Node] Running "map_brainmask" ("niworkflows.interfaces.fixes.FixHeaderApplyTransforms"), a CommandLine Interface with command:
antsApplyTransforms --default-value 0 --float 1 --input /home/qbukhari/.cache/templateflow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_desc-brain_mask.nii.gz --interpolation MultiLabel --output tpl-MNI152NLin2009cAsym_res-02_desc-brain_mask_trans.nii.gz --reference-image /workdir/fmriprep_wf/single_subject_SAD037_wf/func_preproc_ses_pre_task_dotprobe_run_1_wf/bold_reference_wf/gen_ref/ref_bold.nii.gz --transform [ /workdir/fmriprep_wf/single_subject_SAD037_wf/func_preproc_ses_pre_task_dotprobe_run_1_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/norm/transform0GenericAffine.mat, 1 ]
200126-13:56:01,266 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_SAD037_wf.func_preproc_ses_pre_task_dotprobe_run_1_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.map_brainmask".
200126-13:56:03,754 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_SAD037_wf.func_preproc_ses_pre_task_dotprobe_run_1_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.pre_mask_dilate" in "/workdir/fmriprep_wf/single_subject_SAD037_wf/func_preproc_ses_pre_task_dotprobe_run_1_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/pre_mask_dilate".
200126-13:56:03,766 nipype.workflow INFO:
	 [Node] Running "pre_mask_dilate" ("nipype.interfaces.fsl.maths.DilateImage"), a CommandLine Interface with command:
fslmaths -dt char /workdir/fmriprep_wf/single_subject_SAD037_wf/func_preproc_ses_pre_task_dotprobe_run_1_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/map_brainmask/tpl-MNI152NLin2009cAsym_res-02_desc-brain_mask_trans.nii.gz -kernel sphere 3.0000 -dilF /workdir/fmriprep_wf/single_subject_SAD037_wf/func_preproc_ses_pre_task_dotprobe_run_1_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/pre_mask_dilate/tpl-MNI152NLin2009cAsym_res-02_desc-brain_mask_trans_dil.nii.gz
200126-13:56:03,888 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_SAD037_wf.func_preproc_ses_pre_task_dotprobe_run_1_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.pre_mask_dilate".
200126-13:56:06,255 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_SAD037_wf.func_preproc_ses_pre_task_dotprobe_run_2_wf.func_derivatives_wf.raw_sources" in "/workdir/fmriprep_wf/single_subject_SAD037_wf/func_preproc_ses_pre_task_dotprobe_run_2_wf/func_derivatives_wf/raw_sources".
200126-13:56:06,308 nipype.workflow INFO:
	 [Node] Running "raw_sources" ("nipype.interfaces.utility.wrappers.Function")

**Comment by mgxd** [comment]
nipype shouldn't allow for a workflow to be cyclic.

You mentioned only some subjects are not finishing - how long have you been processing this subject? Is there anything different / missing from their scans? It seems like towards the end of your log, processing switched from `task-dotprobe_run-1` to `run-2

**Comment by qasim85** [comment]
This subject has been ongoing for 4 days now.  It is not the only one going on for this  long. Total are 89 subjects, in one go it started with 17 subjects because of qosgrouplimit, and only 6 subjects finished, the rest are on going for the  last 4 +  days.
Nothing missing or different, these are the SAD data that  you converted in to BIDs format actually.

 It moved  to run-2  because its another scan. Here is  the ls of  the bids  of this particular subkect

sub-SAD037_ses-pre_task-dotprobe_run-1_bold.json      sub-SAD037_ses-pre_task-novelobjects_run-1_bold.json
sub-SAD037_ses-pre_task-dotprobe_run-1_bold.nii.gz    sub-SAD037_ses-pre_task-novelobjects_run-1_bold.nii.gz
sub-SAD037_ses-pre_task-dotprobe_run-1_events.tsv     sub-SAD037_ses-pre_task-novelobjects_run-1_events.tsv
sub-SAD037_ses-pre_task-dotprobe_run-2_bold.json      sub-SAD037_ses-pre_task-overtfaces_run-1_bold.json
sub-SAD037_ses-pre_task-dotprobe_run-2_bold.nii.gz    sub-SAD037_ses-pre_task-overtfaces_run-1_bold.nii.gz
sub-SAD037_ses-pre_task-dotprobe_run-2_events.tsv     sub-SAD037_ses-pre_task-overtfaces_run-1_events.tsv
sub-SAD037_ses-pre_task-dotprobe_run-3_bold.json      sub-SAD037_ses-pre_task-rest_run-1_bold.json
sub-SAD037_ses-pre_task-dotprobe_run-3_bold.nii.gz    sub-SAD037_ses-pre_task-rest_run-1_bold.nii.gz
sub-SAD037_ses-pre_task-dotprobe_run-3_events.tsv     sub-SAD037_ses-pre_task-rest_run-1_events.tsv
sub-SAD037_ses-pre_task-masked_run-1_bold.json        sub-SAD037_ses-pre_task-social_run-1_bold.json
sub-SAD037_ses-pre_task-masked_run-1_bold.nii.gz      sub-SAD037_ses-pre_task-social_run-1_bold.nii.gz
sub-SAD037_ses-pre_task-masked_run-1_events.tsv       sub-SAD037_ses-pre_task-social_run-1_events.tsv
sub-SAD037_ses-pre_task-novelfaces_run-1_bold.json    sub-SAD037_ses-pre_task-surreal_run-1_bold.json
sub-SAD037_ses-pre_task-novelfaces_run-1_bold.nii.gz  sub-SAD037_ses-pre_task-surreal_run-1_bold.nii.gz
sub-SAD037_ses-pre_task-novelfaces_run-1_events.tsv   sub-SAD037_ses-pre_task-surreal_run-1_events.tsv

**Comment by mgxd** [comment]
Have you tried removing the `--use-plugin` flag? I believe that is forcing nipype to use LegacyMultiProc. Also, is it possible these SLURM jobs are being constantly preempted? Lastly, you may want to increase the available cores, 4 is fairly low.

Other than altering the config options, you could try upgrading to a newer release (1.5.7 is the latest) and clearing the working directory.

**Comment by qasim85** [comment]
I had  to use --use-plugin, because  if I remove it, I get tons of others errors. Errors and looping behavior. Here is the post that described this issue, I had the exact same problem
https://github.com/poldracklab/fmriprep/issues/1758
In that  post as well they mention  that  it doesnt generate the error but  it keep going forever. So I dont know what was the final solution ?
No these  jobs are not preempted, I am running under gablab qos..
I could not find  the 1.5.8 sif file anywhere  yet, whats the best way to find that sif file ?

**Comment by qasim85** [comment]
ok I solved it using 1.5.8. No error with the newer version. However another issue when using that, I will make a separate post for that
