### ISSUE TITLE
EchoTime2 meta data problem

### ISSUE THREAD

**Issue by qasim85** [poldracklab/fmriprep#1957]
Hello all,
I am using fmriprep 1.5.8. Some of my subjects are giving the following error. Not all, only a few  subjects are with this error, rest finish correctly. 
Can you please help how I can solve this ?
Thanks

Node: fmriprep_wf.single_subject_SAD019_wf.func_preproc_ses_post_task_masked_run_1_wf.sdc_estimate_wf.phdiff_wf.compfmap
Working directory: /workdir/fmriprep_wf/single_subject_SAD019_wf/func_preproc_ses_post_task_masked_run_1_wf/sdc_estimate_wf/phdiff_wf/compfmap

Node inputs:

in_file = <undefined>
metadata = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sdcflows/interfaces/fmap.py", line 244, in _run_interface
    _delta_te(self.inputs.metadata),
  File "/usr/local/miniconda/lib/python3.7/site-packages/sdcflows/interfaces/fmap.py", line 657, in _delta_te
    'EchoTime2 metadata field not found. Please consult the BIDS specification.')
RuntimeError: EchoTime2 metadata field not found. Please consult the BIDS specification.

The tree of the subject BIDS input shows the following
sub-SAD019/ses-pre/anat
├── sub-SAD019_ses-pre_T1w.json
└── sub-SAD019_ses-pre_T1w.nii.gz
sub-SAD019/ses-pre/asl
├── sub-SAD019_ses-pre_acq-casl_run-01_asl.json
├── sub-SAD019_ses-pre_acq-casl_run-01_asl.nii.gz
├── sub-SAD019_ses-pre_acq-casl_run-02_asl.json
├── sub-SAD019_ses-pre_acq-casl_run-02_asl.nii.gz
├── sub-SAD019_ses-pre_run-01_asl.json
└── sub-SAD019_ses-pre_run-01_asl.nii.gz
sub-SAD019/ses-pre/dwi
├── sub-SAD019_ses-pre_run-01_dwi.bval
├── sub-SAD019_ses-pre_run-01_dwi.bvec
├── sub-SAD019_ses-pre_run-01_dwi.json
└── sub-SAD019_ses-pre_run-01_dwi.nii.gz
sub-SAD019/ses-pre/fmap
├── sub-SAD019_ses-pre_acq-128_run-1_magnitude1.json
├── sub-SAD019_ses-pre_acq-128_run-1_magnitude1.nii.gz
├── sub-SAD019_ses-pre_acq-128_run-1_magnitude.json
├── sub-SAD019_ses-pre_acq-128_run-1_magnitude.nii.gz
├── sub-SAD019_ses-pre_acq-128_run-1_phasediff.json
├── sub-SAD019_ses-pre_acq-128_run-1_phasediff.nii.gz
├── sub-SAD019_ses-pre_acq-3_run-1_magnitude1.json
├── sub-SAD019_ses-pre_acq-3_run-1_magnitude1.nii.gz
├── sub-SAD019_ses-pre_acq-3_run-1_magnitude.json
├── sub-SAD019_ses-pre_acq-3_run-1_magnitude.nii.gz
├── sub-SAD019_ses-pre_acq-3_run-1_phasediff.json
├── sub-SAD019_ses-pre_acq-3_run-1_phasediff.nii.gz
├── sub-SAD019_ses-pre_acq-rest_run-1_magnitude1.json
├── sub-SAD019_ses-pre_acq-rest_run-1_magnitude1.nii.gz
├── sub-SAD019_ses-pre_acq-rest_run-1_magnitude.json
├── sub-SAD019_ses-pre_acq-rest_run-1_magnitude.nii.gz
├── sub-SAD019_ses-pre_acq-rest_run-1_phasediff.json
└── sub-SAD019_ses-pre_acq-rest_run-1_phasediff.nii.gz
sub-SAD019/ses-pre/func
├── sub-SAD019_ses-pre_task-dotprobe_run-1_bold.json
├── sub-SAD019_ses-pre_task-dotprobe_run-1_bold.nii.gz
├── sub-SAD019_ses-pre_task-dotprobe_run-1_events.tsv
├── sub-SAD019_ses-pre_task-dotprobe_run-2_bold.json
├── sub-SAD019_ses-pre_task-dotprobe_run-2_bold.nii.gz
├── sub-SAD019_ses-pre_task-dotprobe_run-2_events.tsv
├── sub-SAD019_ses-pre_task-dotprobe_run-3_bold.json
├── sub-SAD019_ses-pre_task-dotprobe_run-3_bold.nii.gz
├── sub-SAD019_ses-pre_task-dotprobe_run-3_events.tsv
├── sub-SAD019_ses-pre_task-masked_run-1_bold.json
├── sub-SAD019_ses-pre_task-masked_run-1_bold.nii.gz
├── sub-SAD019_ses-pre_task-masked_run-1_events.tsv
├── sub-SAD019_ses-pre_task-novelfaces_run-1_bold.json
├── sub-SAD019_ses-pre_task-novelfaces_run-1_bold.nii.gz
├── sub-SAD019_ses-pre_task-novelfaces_run-1_events.tsv
├── sub-SAD019_ses-pre_task-novelobjects_run-1_bold.json
├── sub-SAD019_ses-pre_task-novelobjects_run-1_bold.nii.gz
├── sub-SAD019_ses-pre_task-novelobjects_run-1_events.tsv
├── sub-SAD019_ses-pre_task-overtfaces_run-1_bold.json
├── sub-SAD019_ses-pre_task-overtfaces_run-1_bold.nii.gz
├── sub-SAD019_ses-pre_task-overtfaces_run-1_events.tsv
├── sub-SAD019_ses-pre_task-rest_run-1_bold.json
├── sub-SAD019_ses-pre_task-rest_run-1_bold.nii.gz
├── sub-SAD019_ses-pre_task-rest_run-1_events.tsv
├── sub-SAD019_ses-pre_task-social_run-1_bold.json
├── sub-SAD019_ses-pre_task-social_run-1_bold.nii.gz
├── sub-SAD019_ses-pre_task-social_run-1_events.tsv
├── sub-SAD019_ses-pre_task-surreal_run-1_bold.json
├── sub-SAD019_ses-pre_task-surreal_run-1_bold.nii.gz
└── sub-SAD019_ses-pre_task-surreal_run-1_events.tsv
sub-SAD019/ses-pre/sub-SAD019_ses-pre_scans.tsv 

It seems like there was a similar problem reported  here, but I am not sure how to solve it
https://github.com/poldracklab/sdcflows/issues/65
Can someone please explain what edits need to be done to phasediff.json ?

Thanks

**Comment by qasim85** [comment]
Any one has  any suggestions on how to solve this issue?
Thanks a lot

**Comment by mgxd** [comment]
Hi @qasim85 

From the issue you linked:
> The EchoTime1/2 are basically stored under magnitude1.json and magnitude2.json respectively, and on phasediff.json, it just has "EchoTime" (from magnitude2). According to BIDS specification, EchoTime1/2 should be stored on phasediff.json, and there should be no magnitude1/2.json.

Can you try editing one subject's `phasediff.json` with the EchoTime(s) found in `magnitude.json` and `magnitude1.json`, and see if that fixes your problem?

**Comment by mgxd** [comment]
@qasim85 did editing the `phasediff.json` solve the problem?

**Comment by mgxd** [comment]
feel free to reopen if still an issue
