### ISSUE TITLE
fmriprep error in running multiple nodes on HPC

### ISSUE THREAD

**Issue by NatashaLTaylor** [poldracklab/fmriprep#1965]
Hi,
I have recently tried to get fmriprep to work on my university's HPC through a singularity container. 
I have checked that the singularity container is working, and fmriprep does run through the HPC. However, when I try to run my automatised bash script for 3 participants with fMRI data I receive an exitstatus=1 termination. 
When reading the error file, it states that there was an error in the following:
200205-17:16:49,495 workflow ERROR:
	 could not run node: fmriprep_wf.single_subject_control0647_wf.func_preproc_task_rest_wf.bold_split
200205-17:16:49,496 workflow ERROR:
	 could not run node: fmriprep_wf.single_subject_control0647_wf.func_preproc_task_rest_wf.bold_reference_wf.gen_ref
200205-17:16:49,496 workflow ERROR:
	 could not run node: fmriprep_wf.single_subject_control0647_wf.anat_preproc_wf.skullstrip_ants_wf.t1_skull_strip
200205-17:16:49,980 cli WARNING:
	 Errors occurred while generating reports for participants: control0647 (3).
[fmriprep_error_exitstatus1.txt](https://github.com/poldracklab/fmriprep/files/4162522/fmriprep_error_exitstatus1.txt)

I have attached the full error file. I have made sure that the error is not relating to cpus, as I have requested 32 cpus per participant, with 64gb of memory space. 
Could someone please help me understand what could be the possible route of this error that keeps occurring? 
I did originally think that it was because I was not requesting enough cpus and ram space, however I am not convinced that that is the issue now because the processes are not reaching full-capacity of cpus or mem space. 

Thank you,
Natasha

**Comment by jdkent** [comment]
[Following up on Neurostars](https://neurostars.org/t/fmriprep-error-in-multiple-workflows/6024?u=jdkent)
