### ISSUE TITLE
nu_correct issue with singularity container on computing cluster

### ISSUE THREAD

**Issue by hpfisher3** [poldracklab/fmriprep#1975]
Hello,

I'm running into an issue with the nu_correct step of freesurfer when I run fmriprep through a singularity container on the cluster. (My system does not support docker). With fmriprep versions 1.1.8 and 1.4.1, I ran into an issue of cached memory:

nu_correct -clobber ./tmp.mri_nu_correct.mni.28290/nu0.mnc ./tmp.mri_nu_correct.mni.28290/nu1.mnc -tmpdir ./tmp.mri_nu_correct.mni.28290/0/ -iterations 1000 -distance 50
[hf949@compute-0-50.nmr.mgh.harvard.edu:/autofs/space/rainier_002/users/harris/CTS/data/BIDS/derivatives/freesurfer/sub-HV01baselineTxE/mri/] [2020-02-07 15:01:01] running:
  /opt/freesurfer/mni/bin/nu_estimate_np_and_em -parzen -log -sharpen 0.15 0.01 -iterations 1000 -stop 0.001 -shrink 4 -auto_mask -nonotify -b_spline 1.0e-7 -distance 50 -quiet -execute -clobber -nokeeptmp -tmpdir ./tmp.mri_nu_correct.mni.28290/0/ ./tmp.mri_nu_correct.mni.28290/nu0.mnc ./tmp.mri_nu_correct.mni.28290/nu1.imp

Assertion failed at line 742 in file templates/CachedArray.cc
nu_estimate_np_and_em: crashed while running volume_stats (termination status=256)
nu_correct: crashed while running nu_estimate_np_and_em (termination status=256)
ERROR: nu_correct

If I run the command that caused the error off the cluster, it works just fine. 

I also build a singularity container for the latest version fmriprep.1.5.8 and I still get issues with nu_correct. Initially it throws an error unless I bind my system's freesurfer path to the command -B /usr/local/freesurfer/dev, and if I do that, it runs into an error of not being able to find MNI/Startup.pm in @INC. But @INC contains /usr/local/freesurfer/dev/mni/share/perl5 and several other directories according to the log file.

And the file is located at /usr/local/freesurfer/dev/mni/share/perl5/MNI/Startup.pm. So it should be accessible. 

I'm not even sure why it should be looking at my system's freesurfer though, as I thought the point of the singularity container was that it is self-contained and doesn't require freesurfer or other software locally installed.

I've been reading through freesurfer and MINC list serves and while similar errors have been reported with nu_correct, no solutions were offered that are applicable to me. 

Any help is appreciated.

Best,
- Harris

**Comment by hpfisher3** [comment]
I should add that this is my singularity command: 

#!/bin/bash
#PBS -l nodes=1:ppn=6,vmem=42gb
#PBS -v ${sub_name}

singularity run -B /autofs/space/rainier_002/users/harris/CTS/data/BIDS -B /autofs/space/rainier_002/users/harris/CTS/data/BIDS_wd -B /scratch:/tmp -B /usr/local/freesurfer /autofs/space/rainier_002/users/harris/CTS/data/singularity/fmriprep-1.5.8.simg --participant_label $sub_name --mem_mb 42000 --nthreads 6 -w /autofs/space/rainier_002/users/harris/CTS/data/BIDS_wd --output-spaces MNI152NLin2009cAsym:2mm --fs-license-file=/autofs/space/rainier_002/users/harris/CTS/data/BIDS/code/license.txt /autofs/space/rainier_002/users/harris/CTS/data/BIDS /autofs/space/rainier_002/users/harris/CTS/data/BIDS/derivatives/ participant

**Comment by jdkent** [comment]
Hi Harris,

I do not know if this will definitely fix your problem, but you can try replacing `singularity run` with `singularity run --cleanenv` and remove the binding to your freesurfer installation. The idea behind `--cleanenv` is to remove any pesky environmental variables you have defined that may cause fmriprep to act up (like having environmental variables that point to your local freesurfer installation and not the one in the container).

**Comment by hpfisher3** [comment]
Hi James, 
That seems to have worked! I'll try that as well with older versions of fmriprep, although I suspect that there's a different reason why nu_correct was running into memory issues.

**Comment by mgxd** [comment]
Closing but feel free to reopen this issue if you encounter any more problems
