### ISSUE TITLE
No default output spaces in 20.0.0rc1

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#1979]
Up to now we've always had MNI152NLin2009cAsym as a default output space. Now I get 
```
UserWarning: fMRIPrep will not generate preprocessed derivatives because none of `--output-spaces`, `--use-aroma`, or `--cifti-output` were set.
```

I would suggest we restore the default behavior.

**Comment by mgxd** [comment]
This is the intended behavior, as the large refactor of output spaces makes it possible to add `MNI152NLin2009cAsym` normalization for the carpetplot generation and keep the workflow from breaking, but not clutter the output directory with (possibly) unwanted files. 

And I believe it will still generate preprocessed anatomical? just not any `func/` outputs.

**Comment by effigies** [comment]
The carpetplot bit was written for MNI152etc because that was the default output space, not the other way around. I'm happy to let users override the default space but having no BOLD outputs by default seems pretty extreme.

**Comment by oesteban** [comment]
There needs to be a mechanism to allow users not to generate any outputs (although I don't really understand why you would do that).

One thing we could do is:
- Roll back to the original behavior (i.e., if no ``--output-spaces`` is given, output MNI152NLin2009cAsym results).
- Allow the user to write ``--output-spaces`` without any value, to indicate no bold conversions are to be generated.

WDYT?

**Comment by effigies** [comment]
That sounds fine.
