### ISSUE TITLE
Error for Node Name: fmriprep_wf.single_subject_02_wf.anat_preproc_wf.brain_extraction_wf.norm

### ISSUE THREAD

**Issue by Tao-ZJU** [poldracklab/fmriprep#1988]
Hi, I had run the workflow for two subjects. The command I used was:  **fmriprep-docker data/ output/ participant --use-syn-sdc --fs-license-file license.txt --fs-no-reconall**. It's killed when using SyN registration. Is this a memory error? The memory in my Mac is: 8 GB 1600 MHz DDR3.
Attached is a log file for one subject. [crash-20200217-094316-root-norm-ea9b3c3a-7e24-4a3c-8fcc-3f157feb0db0.txt](https://github.com/poldracklab/fmriprep/files/4215448/crash-20200217-094316-root-norm-ea9b3c3a-7e24-4a3c-8fcc-3f157feb0db0.txt)

**Comment by mgxd** [comment]
Hi @Tao-ZJU - what version of fmriprep are you using? Not sure this is a memory problem, but have you [expanded your Docker app to use more available memory](https://stackoverflow.com/a/44533437)?

**Comment by Tao-ZJU** [comment]
I expanded the memory of my Docker app to 6GB (default: 2GB), but the work is pending more than 15 hours. I don't know whether it is related to the memory or processor of my laptop.
Attached is the terminal output. Thanks!
[Terminal Saved Output.txt](https://github.com/poldracklab/fmriprep/files/4228373/Terminal.Saved.Output.txt)

**Comment by mgxd** [comment]
You may also need to expand the allocated CPUs. Looking at your output, it seems the registration step you initially crashed on eventually finished.

**Comment by Tao-ZJU** [comment]
> You may also need to expand the allocated CPUs. Looking at your output, it seems the registration step you initially crashed on eventually finished.

Hi, thanks for your suggestion. I expand the CPUs, and now it works.
