### ISSUE TITLE
Should fMRIPrep produce brain-masked BOLD volumes?

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1999]
I'm thinking of ways for minimizing the file size of outputs. The most obvious way would be masking BOLD volumes. For them to have an "anatomically-correct" mask, we could project the brain mask from the T1w into the BOLD space (or use the corresponding mask of standardized templates).

Voxels outside the mask could be set to zero or to a NaN-equivalent number (negative, if the datatype supports it?).

cc / @ericearl

**Comment by effigies** [comment]
No. This could potentially hide artifacts that would be extremely obvious as soon as you start doing statistical analysis. @shotgunosine persuaded me that FitLins shouldn't even mask on the first-level analysis so that issues can be shown in reports.

**Comment by oesteban** [comment]
@Shotgunosine, could you provide us with an example? What kind of artifacts would not be picked up by looking at the reports and would be made obvious in statistical analysis?

In other words, maybe what we are missing a quick statistical test that would make these artifacts obvious before generating reportlets? (i.e., I'm not suggesting to generate outputs for this test, just visual reports)

**Comment by oesteban** [comment]
@wiheto, with es-fMRI in mind, how this would affect the study? Would you rather keep the background in that context? I mention this because es-fMRI is a project where the masking of BOLD could have extreme consequences.

**Comment by effigies** [comment]
Note from yesterday's meeting: We might want to consider a `--mask-bold` option (or similar) to allow users to opt-in to masking their BOLD series, but I strongly feel this **should not** be a default.

**Comment by Shotgunosine** [comment]
@oesteban I don't have any artifact examples handy, but some examples include significant effects outside of the brain, or concentrations of significance along blood vessels. @afni-rickr can you describe any other types of artifacts that are detected by examining first-level analyses and looking at the result outside the brain mask. Do you have any example kicking around?

**Comment by oesteban** [comment]
Okay, I think this is more than enough in support of not masking BOLD images, especially considering that I originally proposed it to save storage space. Thanks for the feedback!
