### ISSUE TITLE
Replace get_metadata_for_nifti() with pybids function

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#200]
https://github.com/poldracklab/fmriprep/blob/78424b0facc2a102e75d87c828574e22fbb5b66e/fmriprep/interfaces/bids.py#L191

vs. 

https://github.com/INCF/pybids/tree/master/bids/grabbids#get-all-metadata-for-a-given-file

**Comment by rwblair** [comment]
Only caveat here is that we need to pass the bids data directory as an argument to the ReadSideCar interface.

**Comment by oesteban** [comment]
Couldn't it be inferred from the file path?

**Comment by oesteban** [comment]
Close this in favor of #457
