### ISSUE TITLE
``dseg`` conversions should have integral data types

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#2001]
Currently have float32

cc/ @ericearl

**Comment by effigies** [comment]
This changes outputs for good runs, meaning if somebody processes two subjects, one runs fine on 20.0.0 and the other needs a fix in 20.0.1, then the outputs will differ based on whether they rerun the good subject.

**Comment by effigies** [comment]
I'm seeing mask files as float32, as well. They should be uint8.
