### ISSUE TITLE
Add `--ignore t2w` and `--ignore flair` options

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#2011]
This is probably most easily implemented by clearing subject data entries in `init_single_subject_wf`, just after:

https://github.com/poldracklab/fmriprep/blob/1641529a685c6c23ce2f98ccce06da56280aed98/fmriprep/workflows/base.py#L485-L493

To be consistent with `--ignore fieldmap`, we could pass `ignore` into sMRIPrep's workflows. It's unclear to me that this would be overall cleaner. We could also consider moving `--ignore fieldmap` into `init_single_subject_wf`, though that would be an additional PR.

This adds a CLI option, so I'm marking 20.1.0, but retains backwards compatibility, so I can see an argument for 20.0.2.

This is based on discussion in [Neurostars #2412](https://neurostars.org/t/fmriprep-t2-images/2412/11).

**Comment by effigies** [comment]
Also marked with smriprep, as a similar update should go there for consistency.

**Comment by mgxd** [comment]
A bit hacky, but we could also leverage the `--bids-filter-file` option and just discard looking for these types.

```JSON
{"t2w": {"suffix": null}, "flair": {"suffix": null}}
```
I guess a deeper question would be how much overlap do we want to have between this option and `--ignore`

**Comment by effigies** [comment]
I think `--ignore` is better UX. It's been around for a long time, and is pretty intuitive in meaning. `--bids-filter-file` is a power-user option for when that's not smart enough. I would try to avoid encouraging people to go toward more complicated options when simpler ones will work.

Though if that `--bids-filter-file` option currently works, then it might be good to alert that user, so they can get moving without waiting on our development process.

**Comment by mgxd** [comment]
I agree, it's a cleaner UX
