### ISSUE TITLE
Distortion correction using Phase Encoding POLARity method 

### ISSUE THREAD

**Issue by xuyangwen** [poldracklab/fmriprep#2016]
Hi,

For your bug report, include this information:
-------------------------
What version of fMRIPrep are you using?
20.0.1

What were you trying to do?
I was trying to do distortion correction using Phase Encoding POLARity method. I have two epi files in the fmap folder - one phase encoding direction is "j-", the other is "j". I converted these two images using dcm2niix, without changing any information in the .json files. I did not specify "--ignore filedmaps" in the command line.

What did you expect will happen?
I expected the fMRIPrep would automatically check the fmap folder and choose the Phase Encoding POLARity method to the distortion.

What actually happened?
It omitted the distortion correction step. When I specify "--use-syn-sdc" in the command line, it uses the fieldmap less method.

Can you replicate the behavior? If yes, how?
Yes, I tried several times.

I am not sure if this is the bug. I am wondering if this is because there are some problems in the epi files and the fmriprep can not recognize them, or if I need to specify something in the command line in order to let the fmriprep correct distortion using Phase Encoding POLARity method.

Best,
Yangwen

**Comment by effigies** [comment]
Hi, thanks for your report.

Do you have the `IntendedFor` metadata set on your fieldmaps?

**Comment by xuyangwen** [comment]
> Hi, thanks for your report.
> 
> Do you have the `IntendedFor` metadata set on your fieldmaps?
No, I do not have it. It should be intended for all the runs. Do I need to manually add it by myself?

**Comment by effigies** [comment]
Yes. fMRIPrep uses `IntendedFor` to determine the associated fieldmaps for a given BOLD series. We don't infer this.

**Comment by xuyangwen** [comment]
> Yes. fMRIPrep uses `IntendedFor` to determine the associated fieldmaps for a given BOLD series. We don't infer this.

Thanks! I will try to do that.

**Comment by xuyangwen** [comment]
> Yes. fMRIPrep uses `IntendedFor` to determine the associated fieldmaps for a given BOLD series. We don't infer this.

It seems to work. Thank you very much!
