### ISSUE TITLE
Use ``BIDSLayout.database_path``

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#2019]
In general, it's the case that we run several subjects (sometimes a lot) all stored within the same BIDS dataset. Using the new pybids feature to store the index to hard-disk seems like an effective way of minimizing indexing times.

Problems that will need to be addressed:
- Parallelism: race conditions in generating the first indexed database (although I'm not sure this would be a real problem).
- Reproducibility: does pybids have any ways of checking whether the index should be updated? (cc/ @effigies)
- Where this index should be stored?:
  - The BIDS dataset root.
  - The output folder (I'm not sure of this one, as one would probably like to index the derivatives downstream).
  - The work directory (in many scenarios, e.g., running on a local scratch, this would defeat the purpose of this utility).

**Comment by effigies** [comment]
In FitLins, users can provide a path for a database file. If it exists, we use it. If not, we create it. If it's not passed, we can create one one time in the nipype working directory for the process to avoid indexing multiple times.

Parallelism is handled by the user. There is no sensible way to detect whether the index should be updated that isn't effectively reindexing.
