### ISSUE TITLE
Keep track of random seeds

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#2024]
With clean execution, generate random seeds and store them to the config module. When reusing some work directory or re-running fMRIPrep, enable a flag to reuse all these seeds (mainly for PYTHON, numpy and ANTs processes).

- It would be desirable that seeds are random themselves, the feature here is to leave a trace back to produce the exact same result in re-runs. This will be rather straightforward once #2018 is finished.

Hopefully, this would contribute ease the reproducibility problems we are seeing (cc/ @poldrack)

**Comment by mgxd** [comment]
implemented in #2086
