### ISSUE TITLE
data arrangement for BIDS

### ISSUE THREAD

**Issue by Tao-ZJU** [poldracklab/fmriprep#2029]
Hi experts,

I am running the fmriprep. My dataset including two scans of resting-state fMRI that within 3 hours and one scan of structural T1 MRI. Can I arrange this data as follow?
<img width="276" alt="20200310200216" src="https://user-images.githubusercontent.com/57374591/76378207-1f0d2780-630a-11ea-994a-59a399f91a50.png">

Thanks a lot!

**Comment by effigies** [comment]
This looks reasonable, but I would suggest `sub-01_task-rest_run-01_bold.nii.gz` (and `run-02`), rather than treating each as a separate task.

**Comment by Tao-ZJU** [comment]
Thanks for you reply.
How about arrange as different sessions? 

![Screen Shot 2020-03-11 at 11 07 38 AM](https://user-images.githubusercontent.com/57374591/76449222-e9f3ea00-6388-11ea-919b-ee2aae750966.png)
only drugoff session contains T1w images.

What's the difference between different sessions and different runs?

Thanks!

**Comment by effigies** [comment]
From an fMRIPrep perspective, there's no real difference between splitting things up by session or run. It will change the outputs to more closely match the changed inputs, but that's it. I would organize things however seems most logical to you. Also, in case I wasn't clear, there's nothing wrong with treating them as different tasks, if you prefer that.

**Comment by Tao-ZJU** [comment]
I wonder if there is a registration between different fmri scans? Or just align different fmri scan and T1 images separately?

**Comment by effigies** [comment]
Each BOLD series is registered to the T1w image.

**Comment by Tao-ZJU** [comment]
So if we do some longitudinal analyses, no registration between different BOLD series?

**Comment by effigies** [comment]
Not directly, no. Each is registered to the T1w image. If you have multiple T1w images per subject, they are combined into a template, and each BOLD series is registered to the T1w template.

**Comment by Tao-ZJU** [comment]
I understand it. I only have one T1w image, so each BOLD series is registered to this T1w image.
And another question, for the preprocessing of fmriprep (do not use ICA-AROMA), only head motion correction, slice timing, and normalization have been done, right? This raises another question of whether we should regress the noise before or after the normalization. Many studies regress the noise before the normalization.  Thanks!

**Comment by oesteban** [comment]
> This raises another question of whether we should regress the noise before or after the normalization.

Noise regression must be done outside fmriprep. Make sure you set ``--output-spaces func`` to generate timeseries in the original run's space.

That said, because you are interpolating anyways to account for head motion and susceptibility distortions I honestly doubt you'll see any difference regressing out after normalization. Generating BOLD in its original space or standard space takes fMRIPrep just one interpolation either way.
