### ISSUE TITLE
Empty Templateflow files

### ISSUE THREAD

**Issue by FidgetteSpinneur** [poldracklab/fmriprep#2030]
Hi!

fMRIPrep 1.5.2, Singularity.

We are hitting this exact issue: https://github.com/poldracklab/smriprep/pull/94#issuecomment-510189997 -- i.e. the template file exists, but has size 0.

When running the SIMG we set the following variable:

```
TEMPLATEFLOW_HOST_HOME=/tmp/templateflow-$(whoami)
```

followed by:

```
mkdir -p ${TEMPLATEFLOW_HOST_HOME}
```

Later down, the SIMG is run like this:

```
singularity run --cleanenv -B $STUDY:/projectFolder -B ${TEMPLATEFLOW_HOST_HOME}:${SINGULARITYENV_TEMPLATEFLOW_HOME} -B $L_SCRATCH:/work $IMAGE_DIR/$IMAGE_NAME
```

Any comments?

Thanks in advance!

**Comment by mgxd** [comment]
Which template file is not being pulled?

One possible workaround would be to pull the template locally with `$TEMPLATEFLOW_HOST_HOME`, and just mount it into the container. This discussed towards the end of this section of the documentation https://fmriprep.readthedocs.io/en/stable/singularity.html#internet-access-problems

**Comment by oesteban** [comment]
Also, how did you set `SINGULARITYENV_TEMPLATEFLOW_HOME`?

**Comment by FidgetteSpinneur** [comment]
> Which template file is not being pulled?

It seems to fail at ```tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz```

> One possible workaround would be to pull the template locally with `$TEMPLATEFLOW_HOST_HOME`, and just mount it into the container. This discussed towards the end of this section of the documentation https://fmriprep.readthedocs.io/en/stable/singularity.html#internet-access-problems

This is for spotty internet connections, though, isn't it? We do have internet access.

> Also, how did you set SINGULARITYENV_TEMPLATEFLOW_HOME?

We're using Slurm along with a slightly modified version of the script provided in the documentation:
https://fmriprep.readthedocs.io/en/stable/singularity.html#running-singularity-on-a-slurm-system

Thanks!

**Comment by mgxd** [comment]
Inside the container, does `$TEMPLATEFLOW_HOME` point to whatever`$TEMPLATEFLOW_HOST_HOME` was bound as? And do you have write permission in that directory?

> This is for spotty internet connections, though, isn't it? We do have internet access.

Primarily yes, though we can apply it to this problem and ensure you have the necessary files prior to running the container

**Comment by FidgetteSpinneur** [comment]
> Inside the container, does `$TEMPLATEFLOW_HOME` point to whatever`$TEMPLATEFLOW_HOST_HOME` was bound as? And do you have write permission in that directory?

No, `$TEMPLATEFLOW_HOME` is never set, only `$SINGULARITYENV_TEMPLATEFLOW_HOME`. We need to set the former one too?

Wasn't this a solved problem as per the smriprep fix above? I'm sorry but I'm slightly out of my element here :)

Thanks!

**Comment by FidgetteSpinneur** [comment]
```
One possible workaround would be to pull the template locally with $TEMPLATEFLOW_HOST_HOME, and just mount it into the container
```

So we tried that -- installing `Templateflow` via `pip`, invoking the `api.get` and fetching `MNI152NLin2009cAsym_res-01_T1w`.

This _still_ results in an empty (size 0) `tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz`. I still don't understand Templateflow (I'm not a researcher, just trying to help one) but this doesn't seem right to me. Do you have any further pointers?

Thanks!

**Comment by mgxd** [comment]
> No, $TEMPLATEFLOW_HOME is never set, only $SINGULARITYENV_TEMPLATEFLOW_HOME. We need to set the former one too?

Variables with the `SINGULARITYENV_` prefix should be visible within the container (so `SINGULARITYENV_TEMPLATEFLOW_HOME=/foo` becomes `TEMPLATEFLOW_HOME=/foo`). 

Can you share the full run script? And what version of singularity are you using?

**Comment by FidgetteSpinneur** [comment]
> Variables with the `SINGULARITYENV_` prefix should be visible within the container (so `SINGULARITYENV_TEMPLATEFLOW_HOME=/foo` becomes `TEMPLATEFLOW_HOME=/foo`).

Ah.

> Can you share the full run script?

Certainly. It's a slightly modified version of the sample Slurm script: [gist](https://gist.github.com/FidgetteSpinneur/4f45af8862074fe0076dcd41faa4f80e)

> And what version of singularity are you using?

3.5.0 (Ubuntu 16.04).

Thanks!

**Comment by mgxd** [comment]
solved in https://gist.github.com/FidgetteSpinneur/4f45af8862074fe0076dcd41faa4f80e#gistcomment-3256933
