### ISSUE TITLE
Use --longitudinal to average anat, but not func

### ISSUE THREAD

**Issue by jawaltz** [poldracklab/fmriprep#2038]
Hi-

I usually have 2 anatomies for each subject, acquired in opposite directions. It might be useful to average them, to create the optimal anatomies. So, I would structure them as separate runs, right?

But then I have 4 runs of task-related data in the func folder, and I DON'T want to average those; I want each of those runs concatenated. 

So how can I make --longitudinal only apply to the anatomy?

Thanks,

Jim Waltz

**Comment by effigies** [comment]
We always merge multiple anatomicals, and never functionals. Using --longitudinal results in an anatomical template that is approximately equidistant from all inputs, as opposed to being aligned to the first time point. It's not clear to me that you need this, but it will not affect functional processing.

**Comment by jawaltz** [comment]
Thanks, so if my anatdir looks like the attached, and my funcdir looks like the attached, fmriprep --longitudinal will merge the anatomies, but not the bold images?
<img width="862" alt="anatdir" src="https://user-images.githubusercontent.com/5703114/76803368-0be9d400-67b0-11ea-9657-076be4646237.png">
<img width="862" alt="funcdir" src="https://user-images.githubusercontent.com/5703114/76803384-1310e200-67b0-11ea-9dcc-142b41c76e05.png">

**Comment by effigies** [comment]
Yes. And so will fmriprep without longitudinal.

**Comment by jawaltz** [comment]
Hi- So I have fmriprep working in Singularity, and it always says it can't find the single-band reference. Recently, I started INCLUDING the single-band reference; for a given BOLD data set

sub-M092002_task-CBT_acq-APMB_run-01_bold.nii

the single-band reference is

sub-M092002_task-CBT_acq-APSBRef_run-01_sbref.nii

fmriprep still says it can't find it. What do I need to do?

Second question: Many of my data sets were converted with dcm2nii, which didn't spit out the accompanying json files. What can I do to reconstruct the accompanying json files? I see that, between subjects, json files differ in the contents of only a few fields ("SAR", "TxRefAmp", "ImageOrientationPatientDICOM"). Is there a way of recovering that info from the nifti or DICOM files, without redoing the entire conversion? What does fmriprep actually NEED from the json files? As far as I could tell, it needed the repetition time, which is the same for every subject. What ELSE does it look for?

Thanks so much,

Jim Waltz

**Comment by effigies** [comment]
> sub-M092002_task-CBT_acq-APMB_run-01_bold.nii
> 
> the single-band reference is
> 
> sub-M092002_task-CBT_acq-APSBRef_run-01_sbref.nii
> 
> fmriprep still says it can't find it. What do I need to do?

Your `acq-*` values don't match.

> Is there a way of recovering that info from the nifti or DICOM files, without redoing the entire conversion? What does fmriprep actually NEED from the json files? As far as I could tell, it needed the repetition time, which is the same for every subject. What ELSE does it look for?

I think the only thing we absolutely need is `RepetitionTime`, but I could be wrong. We will definitely look for `SliceTiming` and `PhaseEncodingDirection`. If you have fieldmaps, things definitely get more complicated.

As for recovering from the NIfTI files, repetition time should be available in the `pixdim[4]` field of BOLD series. Phase/frequency/slice directions may or may not be available in the `dim_info` field. Slice timing information for multiband sequences cannot be encoded in NIfTI headers.

**Comment by jawaltz** [comment]
Hi Chris-

Thanks so much for your quick response. I was using the "acq" entity to describe the scan (multi-band or single-band reference), so I guess that doesn't quite work. The "AP" signifies the DIRECTION of acquisition, so I guess I can keep that.

With regard to giving fmriprep the information it needs, in the form of json files, do you think I can just use the same sets of json files over and over again? Are you sure that fmriprep does not use the Image Orientation info in the json files (which differs among subjects)?

Also, I guess I was just wondering if you knew of a version of the dcm2niix script that spits out json files, without nii files. But I guess I can ask the developers of that, too.

Thanks again,

jw

**Comment by jawaltz** [comment]
Just asking this question again: "With regard to giving fmriprep the information it needs, in the form of json files, do you think I can just use the same sets of json files over and over again? Are you sure that fmriprep does not use the Image Orientation info in the json files (which differs among subjects)?"

I contacted dcm2niix script writers about the question of whether there is a version of the dcm2niix script that spits out json files, without nii files.

Thanks,

jw

**Comment by effigies** [comment]
Apologies for not getting back sooner. As you've re-asked the questions in #2067, I'll close this one.
