### ISSUE TITLE
CIFTI volume preferred orientation #39

### ISSUE THREAD

**Issue by shilpitju** [poldracklab/fmriprep#2047]
Hi @effigies @mgxd ,

What are your suggestions to me now based on the reply in
CIFTI volume preferred orientation #39

Shall I use wb_command -cifti-resample or wait for an update in fmriprep?

Regards,

**Comment by mgxd** [comment]
We have released `20.1.0rc1` which now features CIFTI volume in LAS orientation.

**Comment by shilpitju** [comment]
That's wonderful. I will wait for its official release.

**Comment by mgxd** [comment]
@shilpitju if you wouldn't mind, could you test out your data with `20.1.0rc1`? It would be great to crowdsource some testing prior to the official release 😄

**Comment by shilpitju** [comment]
@mgxd I ran one of my datasets using 20.1.0rc1. Thereafter the MATLAB code to extract parcels using the ColeAnticevic_NetPartition which is in HCP CIfti DIDN'T GAVE ANY ERRORS of LAS-RAS mismatch.

Thanks so much. When is an official release expected?

**Comment by mgxd** [comment]
great to hear! there are some outstanding todos to hit, but sometime in april seems likely

**Comment by shilpitju** [comment]
Alright.

**Comment by shilpitju** [comment]
When is the official release expected? :)

Thanks

**Comment by oesteban** [comment]
Expected: past week.
Actual: ASAP, but we'll run a lot of testing so maybe one or two weeks.

**Comment by shilpitju** [comment]
Thanks.
