### ISSUE TITLE
niworkflows' Pinned version conflict between fmriprep:master and its smriprep pin

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#2053]
https://github.com/poldracklab/fmriprep/commit/2c6141c9a642e6e66f959cd97adf9338f5271c68#r38104468

**Comment by effigies** [comment]
Looks like we just need to bump niworkflows in smriprep before the 0.6.0 release?

**Comment by effigies** [comment]
Opened #2054 and an associated issue on sMRIPrep to help track these things. We should probably also open them on SDCflows and niworkflows, but my battery is about to die and it's Saturday. :-)
