### ISSUE TITLE
Dependency tracking

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#2054]
This issue is intended to allow easy reference for the dependencies within the nipreps family of projects.

| fMRIPrep series | sMRIPrep series | SDCflows series | niworkflows series |
|----|----|----|----|
| 20.1.x | `~= 0.6.0` | `~= 1.3.0` | `~= 1.2.0` |
| 20.0.x | `~= 0.5.2` | `~= 1.2.0` | `~= 1.1.7` |
| 1.5.3+ | `~= 0.4.0` | `~= 1.0.1` | `~= 1.0.2` |

TemplateFlow and PyBIDS might be worth adding to this table.

**Comment by mgxd** [comment]
thinking on this some more, maybe we should consider expanding our calver scheme into downstream projects as well. We are essentially treating them as such already, having the major/minors sync up would surely make this dependency graph easier on the developers

**Comment by effigies** [comment]
I'm fine with moving the other projects to calver, but I'm not positive that they'll always sync up.

**Comment by oesteban** [comment]
The dependency matrix has been moved to https://www.nipreps.org/devs/versions/, to edit/suggest changes, please send a PR against the `mkdocs` branch (default) of https://github.com/nipreps/nipreps.github.io/blob/mkdocs/docs/devs/versions.md

This is part of the general strategy of setting up NiPreps as a community and platform for the development of these preprocessing BIDS-Apps.

**Comment by oesteban** [comment]
BTW, that is the perfect place for the CalVer proposal, please write an issue on https://github.com/nipreps/nipreps.github.io
