### ISSUE TITLE
20.1.0rc1 official release

### ISSUE THREAD

**Issue by shilpitju** [poldracklab/fmriprep#2057]
Hi,

When is the official release expected?

Shilpi Modi

**Comment by mgxd** [comment]
20.1.0rc1 is already available.

There are a few [outstanding enhancements/issues](https://github.com/poldracklab/fmriprep/milestone/38) that we would to address prior to releasing 20.1.0, especially since it will be a long-term release.

**Comment by shilpitju** [comment]
Yeah...I m aware that 20.1.0rc1 is available as a pre-release. 

I used it as well on one of my data-sets as asked by you. 

Awaiting 20.1.0

Thanks and all the best.
