### ISSUE TITLE
dimensions of output image

### ISSUE THREAD

**Issue by amuratore** [poldracklab/fmriprep#2058]
Hello,

I'm trying to use FSL's randomise function on data that were preprocessed using fMRIPrep. I was able to combine each individual subject's cope file into one 4D NIFTI file. However, when I enter the randomise command I get an error that the dimensions of my input file and ROI do not match. The pixdims of the 4D file are 3, 3, 3, 2 while the pixdims of the ROI are 2, 2, 2, 1. I resampled the ROI image to match the 4D file using the flirt command which works for pixdims 1-3 but will not change pixdim4 to 2. Can you explain why pixdim4 is set to 2 and how to create a mask in the same space as this? Thanks in advance.

**Comment by effigies** [comment]
pixdim4 is the repetition time. It is unclear why FSL needs a repetition time for a mask, but presumably FSL has a tool for setting header fields.

**Comment by mgxd** [comment]
Feel free to reopen if this is still an issue
