### ISSUE TITLE
Atlas in MNI152NLin2009cAsym space

### ISSUE THREAD

**Issue by Tao-ZJU** [poldracklab/fmriprep#2064]
Hi all,
I'm now searching for the atlas that can be used in the processed fmri data using fmriPrep (with MNI152NLin2009cAsym template). 
I am trying to download the atlas via template flow (https://github.com/templateflow/tpl-MNI152NLin2009cAsym). I have tried to read the *nii.gz file using Matlab, or open the nifti file (*.nii.gz ) by some visualization software (e.g. ITK-snap). I could not open these files correctly, it seems that these files are empty. Can you tell me how to use this atlas? I just aim to compute the functional connectivity using some atlas in MNI152NLin2009cAsym template. Thanks!

**Comment by mgxd** [comment]
Hi @Tao-ZJU 

You'll have to use templateflow's [python api](http://www.templateflow.org/python-client/api/templateflow.api.html) to fetch the data, or you could download the specific files you need from the [OSF project](https://osf.io/ue5gx/)

**Comment by Tao-ZJU** [comment]
> Hi @Tao-ZJU
> 
> You'll have to use templateflow's [python api](http://www.templateflow.org/python-client/api/templateflow.api.html) to fetch the data, or you could download the specific files you need from the [OSF project](https://osf.io/ue5gx/)

Thanks for your reply. I downloaded these files. But I have another question.  The dimension of the data processed by fmriPrep is 49*53*62 (voxel size=3.75*3.75*4), which is not matching the atlas space (res-01 or res-02). I'd like to extract the ROI signals using this atlas, so do you have any suggestions?

**Comment by mgxd** [comment]
you'll have to downsample the atlas to the BOLD resolution, you could use nilearn's [resample_img](https://nilearn.github.io/modules/generated/nilearn.image.resample_img.html#nilearn-image-resample-img)

**Comment by Tao-ZJU** [comment]
> you'll have to downsample the atlas to the BOLD resolution, you could use nilearn's [resample_img](https://nilearn.github.io/modules/generated/nilearn.image.resample_img.html#nilearn-image-resample-img)

Sure, I can downsample the atlas image to get the same resolution. But the image dimension is still different. It seems that the BOLD images have been cropped, so the x, y, z is smaller than those in the atlas space.

**Comment by mgxd** [comment]
@Tao-ZJU if you'd like to produce your BOLD preproc files in the same space as the template, you can designate this in your fmriprep invocation, i.e.

```
fmriprep ... --output-spaces MNI152NLin2009cAsym:res-1
```

**Comment by Tao-ZJU** [comment]
> @Tao-ZJU if you'd like to produce your BOLD preproc files in the same space as the template, you can designate this in your fmriprep invocation, i.e.
> 
> ```
> fmriprep ... --output-spaces MNI152NLin2009cAsym:res-1
> ```

Thanks very much for your kindly help!

**Comment by oesteban** [comment]
What version of *fMRIPrep* is this?

**Comment by Tao-ZJU** [comment]
> What version of _fMRIPrep_ is this?

I check the version with this command: fmriprep-docker --version, 
and get the output: fMRIPrep v20.0.5

**Comment by oesteban** [comment]
@mgxd isn't this related to #2060?

**Comment by mgxd** [comment]
@oesteban this sounds like the preproc data is being output in native space

@Tao-ZJU did adding the `res-` entity help you with the problem?

**Comment by Tao-ZJU** [comment]
> @oesteban this sounds like the preproc data is being output in native space
> 
> @Tao-ZJU did adding the `res-` entity help you with the problem?

Yes, it works. Thanks!
