### ISSUE TITLE
How to run subjects in parallel using fmriprep-docker wrapper? 

### ISSUE THREAD

**Issue by himaniyadav** [poldracklab/fmriprep#2066]
I’m trying to run a few subjects in parallel, and used the guidelines as laid out in this post (mentioned in the FAQ): https://neurostars.org/t/fmriprep-workaround-for-running-subjects-in-parallel/4449. So I tried a command like this:

sleep 1m && fmriprep-docker [source] [dest] participant --participant-label 01 --anat-only --fs-license-file licenses/freesurfer/license.txt --fs-no-reconall
sleep 2m && fmriprep-docker [source] [dest] participant --participant-label 02 --anat-only --fs-license-file licenses/freesurfer/license.txt --fs-no-reconall
sleep 3m && fmriprep-docker [source] [dest] participant --participant-label 03 --anat-only --fs-license-file licenses/freesurfer/license.txt --fs-no-reconall
sleep 4m && fmriprep-docker [source] [dest] participant --participant-label 04 --anat-only --fs-license-file licenses/freesurfer/license.txt --fs-no-reconall

This didn’t work. It only ran the first subject. I assume you cannot use the same parallel strategy when running fmriprep via docker; or am I missing something obvious?

**Comment by oesteban** [comment]
> This didn’t work. It only ran the first subject. I assume you cannot use the same parallel strategy when running fmriprep via docker; or am I missing something obvious?

We'll need to know what was the result of this and more details about your settings (i.e., the logs generated by fmriprep and where you are exactly running this, docker version, etc.).

Thanks

**Comment by effigies** [comment]
I suspect this is a bash issue. Assuming this is one script, these will run in serial.

**Comment by himaniyadav** [comment]
Yes you're right, I tried it as a bash script so it made sense that they ran serially. I ended up being able to run subjects in parallel just by opening up several terminal windows. I think I misunderstood the FAQ post then?

**Comment by effigies** [comment]
Yeah... I'm not sure I understand that post, either. I would not suggest doing that.

**Comment by mgxd** [comment]
task delegated to #2082, closing this
