### ISSUE TITLE
Info extracted from json files for func images

### ISSUE THREAD

**Issue by jawaltz** [poldracklab/fmriprep#2067]
Hi-

With regard to giving fmriprep the information it needs, in the form of json files: what does fmriprep actually NEED?

About half of my data sets had json files created automatically, with dcm2niix; about half of them had only nii files created, with dcm2nii. 

I am still trying to figure out a way to reconstruct json files and/or give fmriprep the info it needs. Would it be possible for me to just use the same sets of json files over and over again? Or does fmriprep also use the Image Orientation info in the json files (which differs among subjects)?"

Thanks,

Jim Waltz

**Comment by effigies** [comment]
We accept valid BIDS datasets, and BIDS only requires RepetitionTime for BOLD series. We will take advantage of EchoTime, SliceTiming and PhaseEncodingDirection, if available.

The image orientation information should be in the NIfTI header, and that's where fMRIPrep will expect to find it. If dcm2niix produces it in JSON, that's fine, but we won't use it.

I don't know of any issues with dcm2nii or dcm2niix converting files, but as a best practice, I'd suggest converting all files with the same version of the same software.

You generally will not need to copy metadata. BIDS has the inheritance principle, which allows common metadata to be defined for multiple files at a higher level. Please see the [BIDS specification](bids-specification.rtfd.io/) for more.

**Comment by jawaltz** [comment]
@effigies Thanks so much. You've been so helpful, but I thought you could have been sick, or overloaded, so I didn't want to hound you, personally. I also didn't want to violate protocol by going straight to you.

**Comment by effigies** [comment]
No worries. My capacity is pretty limited at the moment (and my GitHub notifications are basically impossible to get through), so this was a reasonable thing to do.
