### ISSUE TITLE
error using clean-workdir using docker

### ISSUE THREAD

**Issue by amyh101** [poldracklab/fmriprep#2074]
Hi all...

I am using docker desktop for mac to run fmriprep v20.1.0 and interested in using the '--clean-workdir' option to remove all intermediate files at the conclusion of each fmriprep command. The code is correctly running, but when I include the clean-workdir argument, I receive the following error. Here is an example of my docker command...

```
 <docker run -it --rm -v /path/to/inputs:/data:ro -v  /path/to/outputs:/out -v  /path/to/freesurfer/license.txt:/opt/freesurfer/license.txt -v  /path/to/scratch:/scratch poldracklab/fmriprep /data /out participant --participant-label 0001 --output-spaces MNI152NLin6Asym:res-2 --fs-license-file /opt/freesurfer/license.txt --work-dir /scratch --clean-workdir>
```

And resulting error...
```
<Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 16, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/parser.py", line 382, in parse_args
    work_dir)
  File "/usr/local/miniconda/lib/python3.7/logging/__init__.py", line 1445, in log
    raise TypeError("level must be an integer")
TypeError: level must be an integer>
```

**Comment by mgxd** [comment]
thanks for the report - i've submitted a fix.

by the way, the `--clean-workdir` argument is meant to clear working directories at the beginning of your fmriprep run, not at the end.

**Comment by amyh101** [comment]
Ah thanks so much for the clarification on the --clean-workdir argument. will this argument also work to clean a working directory if the --work-dir argument is not specified (i.e. default working directory is used)?

**Comment by mgxd** [comment]
until the fix is in, I would recommend manually clearing the working directory either before or after each `fmriprep` invocation. once the fix is in, it will ensure (or warn that it couldn't) a clean working directory at the start of every invocation.
