### ISSUE TITLE
FSLeyes does not recognize fmriprep melodic directory

### ISSUE THREAD

**Issue by dmd** [poldracklab/fmriprep#2077]
fmriprep creates a "melodic" directory. However, FSLeyes's melodic mode (for displaying spatial patterns, timeseries, and power spectrum for each component) seems to require that that directory be specifically named `melodic.ica` in order for this to work correctly. 

I'm not sure whether fmriprep should name that directory with an `.ica` extension or whether FSLeyes should not require that extension. (Or whether I and the researchers I support have misunderstood something!)

**Comment by effigies** [comment]
cc @pauldmccarthy for advice

**Comment by pauldmccarthy** [comment]
The FSLeyes expectations are outlined here:  https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/userdoc/latest/ic_classification.html

although as mentioned in pauldmccarthy/fsleyes#48, I don't see any problem in allowing melodic directories with any suffix..

**Comment by effigies** [comment]
Oh, I'm sorry, I'm on an app that apparently doesn't show cross links.

**Comment by pauldmccarthy** [comment]
No worries; I have vague aims to get a new version of FSLeyes out within the next week or two, but am continually interrupted with other work; but I'll add this to the list.

**Comment by effigies** [comment]
I'm going to close this in favor of FSLeyes being more flexible, since BIDS derivatives is going to constrain which naming conventions we can support. Please reopen if there's more to discuss, though.
