### ISSUE TITLE
Update FAQ link to neurostars regarding running fmriprep in parallel

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/fmriprep#2082]
The updated page is here: https://neurostars.org/t/updated-fmriprep-workaround-for-running-subjects-in-parallel/6677 Or the text from the neurostars page could be pasted into the FAQ.

The relevant section in the FAQ is here: https://github.com/poldracklab/fmriprep/blob/master/docs/faq.rst#running-subjects-in-parallel

**Comment by mgxd** [comment]
@jbwexler do you want to open a PR for this?

**Comment by jbwexler** [comment]
Sure, I'll send one in a bit
