### ISSUE TITLE
Latest version release

### ISSUE THREAD

**Issue by shilpitju** [poldracklab/fmriprep#2096]
Hi,

Is the latest version released 20.0.6 the first release candidate of the fMRIPrep 20.1.x series (official release of 20.1.0rc1? 

I suppose it is not. Please correct me if I am wrong.

**Comment by mgxd** [comment]
The first release candidate of the fMRIPrep 20.1.x series is `20.1.0rc1`.
`20.0.6` is a backport to the 20.0.x series
