### ISSUE TITLE
adding -u $UID does not solve permission issues

### ISSUE THREAD

**Issue by geowk** [poldracklab/fmriprep#2098]
Trying to run the following command with the -u option to avoid root issues

fmriprep-docker DIR/ DIR/derivatives -u $UID

However, I get the following error  message:

Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/pathlib.py", line 1241, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/out/fmriprep/logs'

During handling of the above exception, another exception occurred:
`
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 609, in build_workflow
    log_dir.mkdir(exist_ok=True, parents=True)
  File "/usr/local/miniconda/lib/python3.7/pathlib.py", line 1245, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/miniconda/lib/python3.7/pathlib.py", line 1241, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/out/fmriprep'   `

The command only runs if I DO NOT include the -u $UID option. I've tried $USER and get the following output:

`docker: Error response from daemon: unable to find user xxxxx: no matching entries in passwd file.
fMRIPrep: Please report errors to https://github.com/poldracklab/fmriprep/issues `

Essentially, we'd like the derivatives folder and newly created/files to have the same user and group permissions as the user running the camp, not the root.

Any input would be appreciated.

Thanks

geowk

**Comment by mgxd** [comment]
This line of the error:

```
PermissionError: [Errno 13] Permission denied: '/out/fmriprep'
```

make me think the user you are running as doesn't have write access to the output directory.

**Comment by geowk** [comment]
`PermissionError: [Errno 13] Permission denied: '/out/fmriprep'`

> make me think the user you are running as doesn't have write access to the output directory.

mxgd, that is correct.

This was my command:
`fmriprep-docker DIR/ DIR/derivatives -u $UID`

1. I did create the DIR directory, but not the DIR/derivatives. After executing the command, the DIR/derivatives directory is created with root user and root as group . I then created the DIR/derivatives before using fmriprep. Since I had user ownership and group privileges the derivatives folder, fmriprep-docker worked. However, my primary group was not applied to the newly created fmriprep, log,etc. folders. My user ID was also applied to group (GID).

2. Additionally, if other users follow step 1, the new subfolders created under the DIR/derivatives subfolder have user-specific ownership but the files/folders belong to the root group.  Is there way for the newly created files to not only maintain user-specific ownership but also the specified-user's primary group (GID).

Thanks.

**Comment by mgxd** [comment]
> Is there way for the newly created files to not only maintain user-specific ownership but also the specified-user's primary group (GID).

this should be possible by passing in both users / group ids to the `--user` flag, i.e.

```
fmriprep-docker --user $(id -u):$(id -g) ...
```

**Comment by geowk** [comment]
Thanks mgxd. Your solution worked. As long as the DIR/derivatives directory exists prior to running fmriprep-docker, the appropriate username and group ownership is maintained. No root user or root group ownership of newly created files or folders from the fmriprep-docker output.

If one does not create DIR/derivatives directory before executing the fmriprep-docker command, then the DIR/derivatives folder is created by the fmriprep-docker, but with root owner and root group applied and the fmriprep-docker script fails due to permission issues.

Thanks again mgxd.
