### ISSUE TITLE
RuntimeError: Data for requested participant(s) label(s) not found. Could not find data for participant(s): 01

### ISSUE THREAD

**Issue by acsouza** [poldracklab/fmriprep#2100]
Hi there! 
I'm new in using fmriprep and I'm having some issues when trying to run it. Dataset passed the BIDS validator but it can't find subject data. I appreciate any comment on this. 

fmriprep-docker /Users/souza/Documents/postdoc/test_database/ds000116 /Users/souza/Documents/postdoc/test_database/ds000116/derivatives participant --participant-label 01 --fs-license-file /Users/souza/Documents/postdoc/freesurfer-license.txt --ignore slicetiming

RuntimeError: Data for requested participant(s) label(s) not found. Could not find data for participant(s): 01

RUNNING: docker run --rm -it -e DOCKER_VERSION_8395080871=19.03.8 -v /Users/anasouza/Documents/ucsf_postdoc/freesurfer-license.txt:/opt/freesurfer/license.txt:ro -v /Users/anasouza/Documents/ucsf_postdoc/test_database/ds000116:/data:ro -v /Users/anasouza/Documents/ucsf_postdoc/test_database/ds000116/derivatives:/out poldracklab/fmriprep:20.0.6 /data /out participant --participant-label 01 --ignore slicetiming

**Comment by mgxd** [comment]
can you run a `tree` on `/Users/souza/Documents/postdoc/test_database/ds000116` and paste the output?

there have been a few identical issues to this in the past, posting a link to them here (https://github.com/poldracklab/fmriprep/issues/1682, https://github.com/poldracklab/fmriprep/issues/1840).

**Comment by acsouza** [comment]
I have checked the old threads but still couldn't figure out what the problem was. 
However I just found it here. There was an error in one of the folder's name. 
Thank you for your response.
