### ISSUE TITLE
fmriprep-docker  & /var/lib/docker full, no space left

### ISSUE THREAD

**Issue by geowk** [poldracklab/fmriprep#2105]
Hello, we are running fmriprep-docker on Ubuntu 18.04 LTS.

While running fmriprep-docker on a few participants, we noticed the /var partition is closely reaching 100%. This a small partition ~ 60GB, that rarely hits even 20% of its full capacity over the past few years. That has changed since we started running fmriprep-docker. It is now close to 80% by just running a few participants.

Using the command:

> df -h

You can see the source of the increase is the following directory:

` /var/lib/docker/aufs/mnt/

1. Is there way to change the docker root directory to another partition with more space allocated?
2. Is there an option within the fmriprep-docker command to place this /var/lib/docker/aufs/mnt in another directory?

Thanks in advance.

**Comment by oesteban** [comment]
I would assume that the docker daemon is binding `/tmp` inside the container to that host's `/var/lib/docker/aufs/mnt/` folder.

You can just bind mount some other folder (potentially, your host's /tmp should be a candidate), and make sure that is where fmriprep is run:
```
docker run -v /tmp/fmriprep:/tmp -w /tmp/
```
or
```
docker run -v /tmp/fmriprep:/tmp <docker args> poldracklab/fmriprep:<version> <fmriprep args> -w /tmp/work
```

**Comment by geowk** [comment]
osteban,

Thanks. I tried your suggestion. It did place working files in the new designated directory. 

Thanks  again.
