### ISSUE TITLE
no html file created when running fmriprep 

### ISSUE THREAD

**Issue by acsouza** [poldracklab/fmriprep#2110]
Hi!
I’m new with fmriprep and in order to understand the tool I’m running it in a public dataset. It passed BIDS validator and terminal seems to freeze at:

**resume recon-all : recon-all -autorecon-hemi lh -noparcstats -noparcstats2 -noparcstats3 -nohyporelabel -nobalabels -openmp 1 -subjid sub-01 -sd /out/freesurfer **
200427-22:17:01,353 nipype.workflow INFO:
**	[Node] Running “_autorecon_surfs0” (“smriprep.interfaces.freesurfer.ReconAll”), a CommandLine Interface with command:
recon-all -autorecon-hemi lh -noparcstats -noparcstats2 -noparcstats3 -nohyporelabel -nobalabels -openmp 1 -subjid sub-01 -sd /out/freesurfer **
200427-22:17:01,388 nipype.interface INFO:
**	resume recon-all : recon-all -autorecon-hemi lh -noparcstats -noparcstats2 -noparcstats3 -nohyporelabel -nobalabels -openmp 1 -subjid sub-01 -sd /out/freesurfer**

Recon-all finishes without errors (recon-all.log):
**recon-all -s sub-01 finished without error at Mon Apr 27 22:16:54 UTC 2020**

However, no report html file is created neither sub-01/func

Here is the original data directory tree:
ds000116/
├── CHANGES
├── README
├── dataset_description.json
├── participants.tsv
├── sub-01
│ ├── anat
│ │ ├── sub-01_T1w.nii
│ │ └── sub-01_inplaneT2.nii
│ └── func
│ ├── sub-01_task-auditoryoddballwithbuttonresponsetotargetstimuli_run-01_bold.nii
│ ├── sub-01_task-auditoryoddballwithbuttonresponsetotargetstimuli_run-01_events.tsv
│ ├── sub-01_task-auditoryoddballwithbuttonresponsetotargetstimuli_run-02_bold.nii
│ ├── sub-01_task-auditoryoddballwithbuttonresponsetotargetstimuli_run-02_events.tsv
│ ├── sub-01_task-auditoryoddballwithbuttonresponsetotargetstimuli_run-03_bold.nii
│ ├── sub-01_task-auditoryoddballwithbuttonresponsetotargetstimuli_run-03_events.tsv
│ ├── sub-01_task-visualoddballwithbuttonresponsetotargetstimuli_run-01_bold.nii
│ ├── sub-01_task-visualoddballwithbuttonresponsetotargetstimuli_run-01_events.tsv
│ ├── sub-01_task-visualoddballwithbuttonresponsetotargetstimuli_run-02_bold.nii
│ ├── sub-01_task-visualoddballwithbuttonresponsetotargetstimuli_run-02_events.tsv
│ ├── sub-01_task-visualoddballwithbuttonresponsetotargetstimuli_run-03_bold.nii
│ └── sub-01_task-visualoddballwithbuttonresponsetotargetstimuli_run-03_events.tsv

and that’s how I’m running the script:
**fmriprep_docker /Users/souza/Documents/postdoc\ /test-database\ /external/ds000116/ /Users/souza/Documents/postdoc\ /test-database\ /external/derivatives/ participant --participant-label 01 --fs-license-file /Users/souza/Documents/postdoc\ /freesurfer-license.txt --ignore slicetiming**

I appreciate any help.
Ana

**Comment by mgxd** [comment]
how long have you been processing? the recon-all step can take up a large chunk of time.

**Comment by acsouza** [comment]
I left it for 3 days. And recon-all.log gives this message (although the terminal was not released yet): 
recon-all -s sub-01 finished without error at Mon Apr 27 22:16:54 UTC 2020 
I'm running on MacBook Pro 2,3 GHz Intel Core i5. 8 GB 2133 MHz LPDDR3.

**Comment by effigies** [comment]
Can you try adding `-vv` to the `fmriprep-docker` command? The increased verbosity should make it clearer what fMRIPrep thinks is happening.

**Comment by acsouza** [comment]
Sure. I will do that and post the results here. Thanks.

**Comment by acsouza** [comment]
Hi,
These are the last updates on the terminal. The last line is like this for 16 hours. 

200430-23:14:53,945 nipype.workflow INFO:
	 [Job 386] Completed (fmriprep_wf.single_subject_01_wf.anat_preproc_wf.surface_recon_wf.skull_strip_extern).
200430-23:14:53,954 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 1 jobs ready. Free memory (GB): 7.00/7.00, Free processors: 2/2.
200430-23:14:54,589 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_01_wf.anat_preproc_wf.surface_recon_wf.autorecon_resume_wf.autorecon2_vol" in "/tmp/work/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/surface_recon_wf/autorecon_resume_wf/autorecon2_vol".
200430-23:14:54,623 nipype.interface INFO:
	 resume recon-all : recon-all -autorecon2-volonly -openmp 1 -subjid sub-01 -sd /out/freesurfer 
200430-23:14:54,624 nipype.workflow INFO:
	 [Node] Running "autorecon2_vol" ("smriprep.interfaces.freesurfer.ReconAll"), a CommandLine Interface with command:
recon-all -autorecon2-volonly -openmp 1 -subjid sub-01 -sd /out/freesurfer 
200430-23:14:54,628 nipype.interface INFO:
	 resume recon-all : recon-all -autorecon2-volonly -openmp 1 -subjid sub-01 -sd /out/freesurfer 
200430-23:14:55,956 nipype.workflow INFO:
	 [MultiProc] Running 1 tasks, and 0 jobs ready. Free memory (GB): 2.00/7.00, Free processors: 1/2.
                     Currently running:
                       *fmriprep_wf.single_subject_01_wf.anat_preproc_wf.surface_recon_wf.autorecon_resume_wf.autorecon2_vol

**Comment by mgxd** [comment]
@acsouza sorry for the delay - it looks like freesurfer is hanging. can you paste the contents of `<freesurfer-directory>/sub-01/scripts/recon-all.log`? That should hopefully help narrow down the problem.

**Comment by acsouza** [comment]
Hi Mathias, 
Thank you for your reply. I was able to solve the issue. 
Best regards, Ana 
    Em terça-feira, 25 de agosto de 2020 14:13:32 GMT-7, Mathias Goncalves <notifications@github.com> escreveu:  
 
 


@acsouza sorry for the delay - it looks like freesurfer is hanging. can you paste the contents of <freesurfer-directory>/sub-01/scripts/recon-all.log? That should hopefully help narrow down the problem.
