### ISSUE TITLE
running 1 subject per container? 

### ISSUE THREAD

**Issue by geowk** [poldracklab/fmriprep#2112]
Had a question about the recommendation of running 1 subject per container.

1. If we have 10 subjects to preprocess, this means we should run 10 instances of the command fmriprep-docker? Why not run all 10 subjects at once?

This also relates how fmriprep-docker uses available cores  on a system. There is a --nthreads option in the command.  

2. if the --nthreads option is not used, the fmriprep-docker command will use all threads available on the computer system, no? For example, if a computer has a max 10 threads, then fmriprep-docker will use all 10 threads to process 1 subject?

3. What if fmriprep-docker thread is run with multiple subjects, say 4 subjects? How does it allocate computer resources across the 10 threads and 4 subjects?

Thanks in advance

**Comment by effigies** [comment]
The advantages to running one subject per container:

1) Independent failures. If something goes wrong with one subject's run, the error won't be buried in logs for the other subjects, and picking up where you left off is a little cheaper.
1) Each job will take less time to get running. The startup cost is probably basically linear and the controller process memory usage will probably be basically linear.
1) Distributible to multiple machines.

That said, if you only have one computer to throw at your dataset, the simplicity of a single controller process might be worth it.

To answer your other questions:

2. Correct.
3. We use the Nipype [MultiProc](https://nipype.readthedocs.io/en/latest/api/generated/nipype.pipeline.plugins.multiproc.html) scheduler. The basics are that each job is assigned an ID when the workflow is created. Available jobs are jobs whose inputs are all ready (a job that accepts as input the output of another job has to wait on that other job). So when X cores are free (up to the max that you set with `--nthreads`), then the available job with the lowest ID that uses X or fewer cores is started. When a job finishes, the cores are freed up, and available jobs are recalculated. This extends to memory in the same way. It's not very complicated, and there is room for heuristics that order the jobs more intelligently.

**Comment by geowk** [comment]
Thanks for the breakdown, effigies. Much appreciated. Your explanation helped.
