### ISSUE TITLE
CIFTI space output RPI orientation

### ISSUE THREAD

**Issue by saigerutherford** [poldracklab/fmriprep#2118]
The HCP task analysis scripts require the subcortical volumetric data to have RPI orientation, but the fMRIPrep (version 20.0.4) CIFTI output has LPI orientation for the subcortical volumetric data which creates an error when merging the task contrast maps back into CIFTI space (the script splits the CIFTI file into surface & volume, runs task analysis, then merges back together). If anyone would like to run HCP task analysis on this data they need to flip the subcortical data to be RPI orientation in order for the HCP task scripts to work.

**Comment by mgxd** [comment]
@saigerutherford the CIFTI subcortical orientation has been changed to be compatible with HCP analysis in the upcoming 20.1.0 LTS release. The latest release candidate `20.1.0rc2` includes this change, if you would like to pilot one of your participants.

**Comment by mgxd** [comment]
@saigerutherford now that 20.1.0 has been released, could you try running one participant and see if the orientation is fixed?

**Comment by oesteban** [comment]
@saigerutherford could you reopen this issue if you see we really didn't fix it? Also confirming this worked for you would be great, but I'll close this issue for now.
