### ISSUE TITLE
Preprocessing did not finish successfully. Return code: 137

### ISSUE THREAD

**Issue by levchenkoegor** [poldracklab/fmriprep#2126]
[sub-01.zip](https://github.com/poldracklab/fmriprep/files/4625309/sub-01.zip)

Hello, everyone!

I tried to run fMRIPrep to preprocess one subject, but an error occurred after ~1hour of calculations.  I have searched similar issues and probably it is a memory problem, but I am not sure. At some point the next message appeared in my command line:

```
Standard error:
 file NULL does not exist .
 file NULL does not exist .
 file NULL does not exist .
Killed
Return code: 137
```

And in the end:
```
Preprocessing did not finish successfully. Errors occurred while processing data from participants: 01 (1). Check the HTML reports for details.
fMRIPrep: Please report errors to https://github.com/poldracklab/fmriprep/issues
```

I have attached the HTML file with the report (sorry, it is in zip format, because HTML isn't appropriate for GitHub. Can you help me please with that?

My PC/system characteristics:
Processor: Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz 3.91GHz
RAM: 8.00 GB
System type: 64-bit, x64-based processor
Operating system: Windows 10 Pro

**Comment by levchenkoegor** [comment]
Tried to run the same subject on a powerful cluster computer, but I have an error. Now it is missing some libraries. I used the Singularity tool.

I have attached the archive with a log file with errors.

Any information will be so helpful!
[sub-01.zip](https://github.com/poldracklab/fmriprep/files/4679132/sub-01.zip)

**Comment by oesteban** [comment]
Hi @levchenkoegor,

Your first error on the windows machine with docker looks like you run out of space on the temporal folder.

In your second attempt with Singularity, it seems that some libraries/paths in the host are traversing into the container. Please try to run singularity with the ``--cleanenv`` flag.

For both cases, I think a thorough read of the documentation will give you the background you need: [Docker](https://fmriprep.readthedocs.io/en/latest/docker.html) & [Singularity](https://fmriprep.readthedocs.io/en/latest/singularity.html). The FAQ and other sections could also have some useful tips.

Please reopen if you keep encountering issues.
