### ISSUE TITLE
Figure naming incorrect when t2s-coreg option used in v20.0.7 

### ISSUE THREAD

**Issue by mnarayan** [poldracklab/fmriprep#2127]
This report pertains to a bug that appeared between 20.0.0 and 20.0.7. It seems the figures are incorrectly named when processing multi-echo datasets. 

- I expected figures to contain only the combined multi-echo data since `t2s-coreg` option was used. In version 20.0.0 this is how the files were named. 
```
 3.0M May 15 15:59 sub-CCxxxx_task-movie_run-1_desc-bbregister_bold.svg
159K May 15 17:05 sub-CCxxxx_task-movie_run-1_desc-carpetplot_bold.svg
 100K May 15 16:02 sub-CCxxxx_task-movie_run-1_desc-compcorvar_bold.svg
 438K May 15 16:03 sub-CCxxxx_task-movie_run-1_desc-confoundcorr_bold.svg
 495K May 15 16:03 sub-CCxxx_task-movie_run-1_desc-rois_bold.svg
```
- Instead now in version 20.0.7, I see the following, labeled echo-1. 
```
May 18 11:32 sub-CCxxx_task-movie_run-1_echo-1_desc-aroma_bold.svg
May 18 00:55 sub-CCxxx_task-movie_run-1_echo-1_desc-bbregister_bold.svg
May 18 01:59 sub-CCxxx_task-movie_run-1_echo-1_desc-carpetplot_bold.svg
May 18 00:55 sub-CCxxx_task-movie_run-1_echo-1_desc-compcorvar_bold.svg
May 18 00:55 sub-CCxxx_task-movie_run-1_echo-1_desc-confoundcorr_bold.svg
May 18 00:55 sub-CCxxx_task-movie_run-1_echo-1_desc-rois_bold.svg
```
My suspicion is this has to do with naming conventions for the fmriprep working directory. This uses the naming convention of `task-xxxx_run-1_echo-1` regardless of whether an echo-specific option is used `--echo-id 1` or whether the joint echo processing option is being done `--t2s-coreg` is used.

**Comment by oesteban** [comment]
Thanks much - this is a use case I didn't capture while I was at #2114. The new `dismiss_entities` feature (https://github.com/nipreps/niworkflows/commit/73f54c1285ff275c8c09e6bd9f59ce79ae0bc4fc) will come handy here to drop the echo tag.
