### ISSUE TITLE
Improper outputs generated for ME-EPI

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#2134]
While at #2133, I've noticed that we are generating single `desc-preproc_bold.nii.gz` files, however, AFAIK, we are not producing the BOLD signal corresponding to the combination of echoes.

In other words, we should be generating one `preproc` file per echo (please correct me if I'm wrong @emdupre, @tsalo), or else actually compute the final combination. Given the current state of things, I would incline for generating the different echoes.

This also stands for surface and CIFTI-2 outputs.

/cc @mnarayan @shotgunosine

**Comment by emdupre** [comment]
We should in fact be generating the optimal combination ! Unless something has changed to remove the T2* map interface.

The echo-idx flag allows users to avoid this and instead return individual echoes.

**Comment by oesteban** [comment]
> We should in fact be generating the optimal combination !

Is this a fact or an indication? If we are generating the optimal combination this issue can be closed. In that case, sorry for my ignorance.

**Comment by emdupre** [comment]
I can confirm that we previously generated the optimal combination. As to whether we are still generating it with the latest code base, I'll be able to look at the workflows later tonight. From my recollection of #2109, we were still generating the optimal combination when that was merged.

**Comment by oesteban** [comment]
Awesome, thanks for calling out this false alarm so quickly. I'll let you close the issue whenever you can confirm the implementation :)

**Comment by mnarayan** [comment]
On a related note, I tried to use the following command `--t2s-coreg` **and** `--echo-idx $no` and I am not sure exactly how the individual echoes are processed in this case. Ideally I am looking for individual echoes processed using the same transforms as the optimal combination image when `--t2s-coreg` alone is performed. 

If these two options cannot be used together that would be good to know.

**Comment by emdupre** [comment]
The connections all seem to be there, @oesteban , so I think this can be resolved:

https://github.com/poldracklab/fmriprep/blob/3701780e73a0cb7c32ef203dea176e1426555e04/fmriprep/workflows/bold/base.py#L505

@mnarayan you're right that these two can't be used together ! The way that we implement echo-idx is that we subselect the relevant echo from the original MEEPI list:

https://github.com/nipreps/niworkflows/blob/9b0f64659017f869530d9a33cf2a7b5c87b1e8c4/niworkflows/utils/bids.py#L184

I'd say that we should update the documentation but we've now removed the t2s-coreg option from master (see the discussion around #2109 ). Which release are you using, @mnarayan ?

**Comment by oesteban** [comment]
Thanks much!

Do you think @emdupre and @mnarayan this deserves discussion on a new issue, at least noting the documentation misses?

**Comment by emdupre** [comment]
I suppose that's my question 😄 I'm not entirely familiar with the new release cycle, so I'm wondering if there's a way in which we could still release documentation updates for an older version. I'm happy to follow your suggestion here, @oesteban !

**Comment by mnarayan** [comment]
@emdupre I've been using the v20.0.1/v20.0.7, so I wasn't aware of the change. 
@oesteban I will open a new issue about this, as I have more questions anyway.
