### ISSUE TITLE
.surf.gii for flsr 32k

### ISSUE THREAD

**Issue by JacobLuceno** [poldracklab/fmriprep#2136]
Hello,

My group and I need the left and right hemisphere *.surf.gii geometry files for the cifti.dtseries files output by fMRIprep, and for the .func.gii's we've generated utilizing the wb_command cifti-separate function, in flsr 32k, for each subject.

So far I've tried to use the corresponding midthickness.surf.gii's output in the anat folder but I believe they're in a different space.  

Is there a way to set fMRIprep to output the files we need?

Thanks!

**Comment by effigies** [comment]
Ah, hope you found them. https://github.com/Washington-University/HCPpipelines/tree/master/global/templates/standard_mesh_atlases
