### ISSUE TITLE
Reuse of same work directory between subjects with 20.1.0

### ISSUE THREAD

**Issue by ariekahn** [poldracklab/fmriprep#2137]
I'm testing fmriprep 20.1.0 via singularity (`20.1.0rc2+177.ge3d3bc51`).

I was running my subjects in parallel jobs on an SGE cluster, and noticed that they started failing quickly with missing outputs, and appeared to be searching for the wrong subject IDs.

For instance, once instance that was started with the following argments:
```
singularity run -B $SBIA_TMPDIR:/tmp --cleanenv $SIMG \
    $PROJECT_DIR/data/ \
    $PROJECT_DIR/derived/ \
    participant \
    --nprocs 9 \
    --mem_mb 65536 \
    --fs-license-file $PROJECT_DIR/extra/license.txt \
    --fs-subjects-dir $PROJECT_DIR/derived/freesurfer \
    --participant-label GLS006 \
    -w $PROJECT_DIR/work \
    --skull-strip-fixed-seed \
    --bold2t1w-dof 9 \
    --dummy-scans 10 \
    --output-spaces MNI152NLin2009cAsym:res-native MNI152NLin6Asym:res-2
```

produced the following run:
```
    Running fMRIPREP version 20.1.0rc2+177.ge3d3bc51:
      * BIDS dataset path: /cbica/projects/GraphLearning/project/data.
      * Participant list: ['GLS020'].
      * Run identifier: 20200522-234318_57e47270-f002-4929-8b35-d51e400b07b6.
      * Output spaces: MNI152NLin2009cAsym:res-native MNI152NLin6Asym:res-2.
```

which in turn led to the multiple runs clobbering each other.

It looks like this was due to how the current build writes `.fmriprep.toml` to the root of the work directory, which gets overwritten if I have multiple instances running in parallel.

 With previous versions, fmriprep would create subdirectories for `fsdir_run_<runid>` and `single_subject_<subjectid>` for each instance, but it looks like the root of the work directory is being used now for both `bids.db` and `.fmriprep.toml`.

I'm not sure what correct behavior should be here, which is why I'm opening this issue. I can't find any information in the documentation, and the one parallel example I see for SLURM appears to re-use the same work directory. So I'm not sure if this is incorrect usage on my part, or the documentation needs to be updated.

**Comment by mgxd** [comment]
@ariekahn this certainly sounds like a bug likely introduced during the migration to the config file, I'll take a look - thanks for piloting before the release!

**Comment by oesteban** [comment]
Ha I guess we are not releasing on Monday :(
