### ISSUE TITLE
Ping Nipype's eTelemetry just once on ``config`` load - then disable.

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#2140]
fMRIPrep should ping Nipype's eTelemetry just once. We should do it (silently) when the config module is loaded first and then set the env variable to disable it going forward:

1. Read the environment and determine whether the user has not explicitly disabled the eTelemetry ping.
2. Before setting up the loggers, ping eTelemetry if the user has not disabled it, making sure we do not write anything to screen.
3. Set enviornment variable to disable eTelemetry pings.

**Comment by mgxd** [comment]
this should probably be done in:

https://github.com/poldracklab/fmriprep/blob/e77d77ff0b650c55ec9ee6938e5130036d510f34/fmriprep/config.py#L281-L307

**Comment by oesteban** [comment]
If that is the first import of nipype, yes.

**Comment by oesteban** [comment]
If nipype has an API call to ping eTelemetry, the easiest would be to:

1. Check if user has disabled it themselves previously and keep this info
2. Set the flag as early as possible to disable the ping
3. Use the API call whenever we think it is most appropriate, for instance, just before `.run()`.

**Comment by effigies** [comment]
Nipype worked on this. I think our separate process constructing the workflow is preventing its duplication prevention.

What if we just instantiate an interface, and let nipype do its thing?
