### ISSUE TITLE
RuntimeError: Data for requested participant(s) label(s) not found. Could not find data for participant(s)

### ISSUE THREAD

**Issue by tanya-wen** [poldracklab/fmriprep#2141]
I'm new to fmriprep and I am trying to run the following command:
fmriprep-docker "/Users/Tanya Wen/BoxSync/Extra_Space_for_Tanya/fMRI/decodCC.01_BIDS/Nifti" "/Users/Tanya Wen/BoxSync/Extra_Space_for_Tanya/fMRI/decodCC.01_BIDS/Preprocessed" participant --participant-label 03 --fs-license-file "/Users/Tanya Wen/Box Sync/Extra_Space_for_Tanya/fMRI/freesurfer.txt"

I've validated my data set using the BIDS validator and is has passed (with warnings of no events.tsv files and readme file). 

Here is the dataset tree for sub-03
C:\Users\Tanya Wen\Box Sync\Extra_Space_for_Tanya\fMRI\decodCC.01_BIDS\Nifti>tree /f

│   dataset_description.json
│   participants.tsv
│
├───sub-03
│   ├───anat
│   │       sub-03_T1w.json
│   │       sub-03_T1w.nii.gz
│   │
│   └───func
│           sub-03_task-mem_run-01_bold.json
│           sub-03_task-mem_run-01_bold.nii.gz
│           sub-03_task-mem_run-02_bold.json
│           sub-03_task-mem_run-02_bold.nii.gz
│           sub-03_task-stroop_run-01_bold.json
│           sub-03_task-stroop_run-01_bold.nii.gz
│           sub-03_task-stroop_run-02_bold.json
│           sub-03_task-stroop_run-02_bold.nii.gz
│           sub-03_task-stroop_run-03_bold.json
│           sub-03_task-stroop_run-03_bold.nii.gz
│           sub-03_task-stroop_run-04_bold.json
│           sub-03_task-stroop_run-04_bold.nii.gz
│

And I get this output after running the command:
RUNNING: docker run --rm -it -e DOCKER_VERSION_8395080871=19.03.8 -v C:\Users\Tanya Wen\Box Sync\Extra_Space_for_Tanya\fMRI\freesurfer.txt:/opt/freesurfer/license.txt:ro -v C:\Users\Tanya Wen\BoxSync\Extra_Space_for_Tanya\fMRI\decodCC.01_BIDS\Nifti:/data:ro -v C:\Users\Tanya Wen\BoxSync\Extra_Space_for_Tanya\fMRI\decodCC.01_BIDS\Preprocessed:/out poldracklab/fmriprep:20.0.7 /data /out participant --participant-label 03
Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 319, in main
    validate_input_dir(exec_env, opts.bids_dir, opts.participant_label)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/utils/bids.py", line 136, in validate_input_dir
    raise RuntimeError(error_msg % ','.join(bad_labels))
RuntimeError: Data for requested participant(s) label(s) not found. Could not find data for participant(s): 03. Please verify the requested participant labels.
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
fMRIPrep: Please report errors to https://github.com/poldracklab/fmriprep/issues

It seems like it can't find the participant label. I read some similar issues, and there have been suggestions to move the --participant-label 03 to the end of the command, but it made no difference in my case. I also checked that the hyphens are dashes and not endashes. Any suggestions would be much appreciated.

**Comment by mgxd** [comment]
Command-wise, everything looks good. I think this may have to do with your Docker configuration - is your C drive added to shared drives?
https://stackoverflow.com/questions/51121070/docker-v-bind-mount-is-not-working-any-more-on-windows-10

**Comment by tanya-wen** [comment]
Hi mgxd, thanks so much for your reply. Yeah, I had all the relevant C drive directories added in the Docker the File Sharing. I actually just got an email from my department's IT team, and they just figured out the issue for me. It turned out that Docker file sharing is not working for Box Drive or Box Sync folders. After copying the data to a local directory, everything worked perfectly. I really appreciate you taking the time to help.

**Comment by effigies** [comment]
:+1:
