### ISSUE TITLE
fmriprep error - functional scans have brain tissue cropped out

### ISSUE THREAD

**Issue by NatashaLTaylor** [poldracklab/fmriprep#2144]
Hi,
I have recently come across an issue with running fmriprep (version 1.5.8) on a large dataset, roughly half of the files have pre-processed functional scans that have part of the brain cropped out (specifically the posterior aspect of the cerebellum).
Looking back through the .html file, I found that during the alignment of functional and structural MRI data, the transformation of the EPI-space to T1w, appears to be outlining regions of the brain that are then cut out from the functional data (see photo). Even looking at the generated brain mask, outlines the same cropped brain, it appears as if the pipeline in fmriprep is misidentifying tissue, and removing it.
<img width="1274" alt="Screen Shot 2020-05-26 at 4 20 17 pm" src="https://user-images.githubusercontent.com/57138555/82957698-018d5700-9ff7-11ea-8c09-05aa17012cd7.png">
<img width="1278" alt="Screen Shot 2020-05-26 at 4 20 29 pm" src="https://user-images.githubusercontent.com/57138555/82957707-06520b00-9ff7-11ea-80ef-6b35b296c712.png">

This has resulted in pre-processed functional data that has part of the cerebellum missing. Is there a way to prevent this from occurring in fmriprep?

Only possible explanation that I could consider causing this issue is because in some of these MRI scans, patient’s head was relatively titled and the entire brain for fmri sequence just fitted into the frame, not sure if this is why fmriprep is cropping out the lower aspect of the brain.

Appreciate anyone’s feedback or advice.
Natasha

**Comment by effigies** [comment]
Could you share a screenshot of an example volume in the input data?

**Comment by NatashaLTaylor** [comment]
Sure, I've just attached screenshots of the anatomical T1w and corresponding fMRI. 
<img width="394" alt="Screen Shot 2020-05-27 at 12 23 48 pm" src="https://user-images.githubusercontent.com/57138555/82971111-4627eb00-a015-11ea-98ee-982a815946b6.png">
<img width="395" alt="Screen Shot 2020-05-27 at 12 24 30 pm" src="https://user-images.githubusercontent.com/57138555/82971118-49bb7200-a015-11ea-8306-181e81d368a1.png">

**Comment by effigies** [comment]
Thanks!

It looks to me like your images were not acquired with intact cerebella. Note that it's even dropping out in the larger field of view T1w image. Sorry to say, there's nothing fmriprep can do to recover that.

**Comment by NatashaLTaylor** [comment]
Thank you! 
Would you recommend still using the fmriprep pre-processed data if we are not using the cerebellum as a region of interest in our analysis? 
Or would you suggest using an alternative platform for preprocessing?

**Comment by effigies** [comment]
The alignment looks reasonable to me, so I would be comfortable using fmriprep on these data.

**Comment by oesteban** [comment]
Perhaps unclear in @effigies' answer, but it looks like these images were prescribed a field-of-view not including the cerebellum. Regardless of the software you use, the images just don't have the information.

**Comment by NatashaLTaylor** [comment]
Thank you so much! That does make sense. 
Unfortunately I did not collect this dataset myself, so was not aware that a field-of-view was not including cerebellum.
