### ISSUE TITLE
BOLD dtypes are larger than necessary

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#2157]
fMRIPrep version: 20.1.0

```Python
In [1]: import nibabel as nb

In [2]: nb.load('sourcedata/sub-02/func/sub-02_task-repeatchange_run-5_bold.nii.gz').get_data_dtype()
Out[2]: dtype('<i2')

In [3]: nb.load('fmriprep/sub-02/func/sub-02_task-repeatchange_run-5_space-T1w_desc-preproc_bold.nii.gz').get_data_dtype()
Out[3]: dtype('<f4')

In [4]: nb.load('fmriprep/sub-02/func/sub-02_task-repeatchange_run-5_space-fsLR_den-91k_bold.dtseries.nii').get_data_dtype()
Out[4]: dtype('<f8')
```

I feel like I remember BOLD series being saved to the original precision, but I'm not hugely concerned about that. The CIFTI series should definitely not be float64.

**Comment by mgxd** [comment]
- The BOLD dtype is coerced to float32 when converted to GIFTI here
https://github.com/poldracklab/fmriprep/blob/eb3a40b827d277ce661e31c27f6ace40ef3c2be6/fmriprep/workflows/bold/resampling.py#L106-L115
- I've submitted a fix for the CIFTI file @ https://github.com/nipreps/niworkflows/pull/532, would love to get your feedback to ensure I'm not causing a substantial change in the actual data

**Comment by oesteban** [comment]
Now that the niworkflows PR is merged, can we just close this one?

**Comment by mgxd** [comment]
we might want to fix the `_preproc` files first

**Comment by mgxd** [comment]
i believe this is fixed now, closing
