### ISSUE TITLE
ROIs reportlet showing intermediate result for ME-EPI

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#2162]
We introduced a regression with #2117, affecting all +20.x series.

Before:
<img src="https://13873-53175327-gh.circle-artifacts.com/0/tmp/ds210/derivatives/fmriprep/sub-02/figures/sub-02_task-cuedSGT_run-1_echo-1_desc-rois_bold.svg" />

After:
<img src="https://13880-53175327-gh.circle-artifacts.com/0/tmp/ds210/derivatives/fmriprep/sub-02/figures/sub-02_task-cuedSGT_run-1_echo-1_desc-rois_bold.svg" />

**Comment by oesteban** [comment]
Just to be clear: for this to be fixed we need to roll back the plotting to the whole brain, unmasked.

**Comment by effigies** [comment]
@oesteban is this resolved? Latest run: https://15342-53175327-gh.circle-artifacts.com/0/tmp/ds210/derivatives/fmriprep/sub-02.html

**Comment by oesteban** [comment]
Yes, I'm finding myself in the same situation. But I believe that the CI run you posted seems to be using the echo combination.
