### ISSUE TITLE
singularity not writing finished without errors message to stderr in 20.1.0

### ISSUE THREAD

**Issue by dmd** [poldracklab/fmriprep#2167]
Every successful job we've run (which is all of them except those mentioned in https://github.com/poldracklab/fmriprep/issues/2161 )  using singularity container 20.1.0 has written nothing at all to stderr.

That means we don't get the "fMRIPrep finished without errors" message written anywhere.

**Comment by dmd** [comment]
Aha! You changed the output stream *and* the wording! I was grepping for (and my code was expecting) `fMRIPrep finished without errors`.

**Comment by dmd** [comment]
(Oh, ugh. This means my code has to handle both phrases and both possible files, since some people pin their fmriprep version at older versions.)

**Comment by oesteban** [comment]
Sorry about this. Maybe worth documenting this kind of details in our draft for how fmriprep uses version numbers (www.nipreps.org/devs/releases/). Something to mention that important signals in the log file and changes to where (std out/err) things are logged may grant a minor version bump. What do you think?

**Comment by dmd** [comment]
Yeah. If people (like me) are building tooling around fmriprep, it's important to at least know when stuff like that changes.
