### ISSUE TITLE
no 20.1.1 on docker hub

### ISSUE THREAD

**Issue by yarikoptic** [poldracklab/fmriprep#2171]
Since I was pestered, pestering in turn: It has been entire 7 hours!!! as 20.1.1 was released, but it seems not  to be present on https://hub.docker.com/r/poldracklab/fmriprep/tags . *What is going on?* ;)

**Comment by oesteban** [comment]
hahaha we are backing up a little - the fs license issue wasn't fully solved, Mathias will cut a fresh tag soon with the fix. Sorry for the fuss.

**Comment by mgxd** [comment]
this should be all set

**Comment by oesteban** [comment]
Just posted https://hub.docker.com/layers/poldracklab/fmriprep/20.1.1/images/sha256-f558e35fa7a41a5e7008c73ae94f9bdfb2a64750ca2c93e733646804633e0cc4?context=explore

**Comment by yarikoptic** [comment]
Awesome, save now singularity container part of https://github.com/ReproNim/containers/tree/master/images/bids
