### ISSUE TITLE
n/a for few of the confound regressors in 1st row

### ISSUE THREAD

**Issue by shilpitju** [poldracklab/fmriprep#2172]
Hi,

After preprocessing a fMRI data set using fmriprep 20.1.0, I am trying to use Friston 24-parameter model for my GLM analysis using SPM. In the first row of the regressors generated by fmriprep, few of the regressor values are n/a (such as, trans_x_derivative1, trans_x_derivative1_power2, trans_y_derivative1, trans_y_derivative1_power2, trans_z_derivative1, trans_z_derivative1_power2 ,rot_x_derivative1, rot_x_derivative1_power2, rot_y_derivative1, rot_y_derivative1_power2, ,rot_z_derivative1,rot_z_derivative1_power2)

While specifying the design matrix using these regressors, SPM is giving error because of the n/a values in the first row. How can I resolve this issue?

Thanks

**Comment by effigies** [comment]
These are undefined values, so you'll need to appropriately impute something. My impression is that for derivatives, 0 is probably a reasonable value, but I might check the paper to see how Friston dealt with it.

**Comment by shilpitju** [comment]
Alright. Thanks
