### ISSUE TITLE
Smarter test of multiecho datasets

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#2179]
Instead of:

https://github.com/poldracklab/fmriprep/blob/4c54ca4f855d4f560c7c4abdbbbcb4fb3a60bae6/fmriprep/workflows/bold/base.py#L147

we may want to do something like:

```Python
entities = layout.parse_file_entities(ensure_list(ref_file)[0])
multiecho = "echo" in entities
```

May I suggest to address this in the context of #1803 ?

**Comment by tsalo** [comment]
Sorry for the delay on responding to this. Is `echo` prohibited for single-echo data? The specification is unclear:

>Multi-echo data MUST be split into one file per echo. Each file shares the same name with the exception of the `_echo-<index>` key/value.

If we assume that single-echo data cannot include `echo`, then I think the proposed check is good.

**Comment by oesteban** [comment]
Perhaps this is easier than I thought in the beginning. What about testing:

```Python
multiecho = len(entities.pop("echo", [])) > 2
```

**Comment by oesteban** [comment]
I believe that covers one of the edge cases of #2182 too.
