### ISSUE TITLE
Implement movement parameters for ApplyTOPUP from mcflirt

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#218]
Per conversation with Jesper Andersson

> Date:    Mon, 12 Sep 2016 12:45:40 +0000
> From:    Jesper Andersson <jesper.andersson@NDCN.OX.AC.UK>
> Subject: Re: Convert FUGUE fieldmaps to TOPUP fieldcoef
> 
> Dear Oscar,
> 
> I'd like to raise this question again, hoping that Jesper could jump in and enlighten me with some leads. This was the problem:
> 
> 1. I am building a workflow that can estimate fieldmaps using TOPUP when the input dataset is appropriate for that estimation and FUGUE when it comes with a phase difference map.
> 
> 2. I want to plug the estimated fieldmap (regardless the tool used for generation) into ApplyTOPUP for all cases. I don't want to use FUGUE at all for this.
> 
> 3. I have successfully created the workflow that estimates the fieldmap with FUGUE, converts it to Hz units, and with several tricks, I generate the corresponding fieldcoeff map. I also manipulate the headers so that they reproduce the headers you get for the fieldcoeff nifti you get with TOPUP.
> 
> 4. I use a fake movpar file with all zeros.
> 
> 5. All this is apparently working fine.
> 
> 6. Now, I want to use a real movpar file, generated with MCFLIRT but rotations are apparently exaggerated, translations do not look that bad.
> 
> These are my questions:
> 
> Q1. Do steps 1-5 look right? Am I missing something even though ApplyTOPUP seems to work fine?
> 
> This all looks good, though I can of course not say anything with certainty about for example your generation of the fieldcoeff map (which sounds like hard work). Why is it you want to use Applytopup instead of FUGUE? Would it not make sense to have these cases (dual-echotime fieldmap vs opposing PE volumes) as separate threads through the process (given that they have anyway diverged in how to estimate the field)?
> 
> Also, if these are diffusion data, why not use EDDY and skip the applytopup/fugue step altogether? The latest patch of eddy allows the input of a dual-echotime fieldmap instead of a topup-field.
> 
> Q2. Is the movpar file in the same format and conventions (order of columns, units, center of rotation) as the par file generated by MCFLIRT with save plots?
> 
> No, unfortunately they are different in every aspect. If you have the transformation matrices from flirt you can convert these to topup/eddy movement-parameters using the TOPUP::Matrix2MovePar global function that you can find in topup_file_io.h in the TOPUP project.
> 
> Jesper

The particular piece of code to use or reimplement is:
```
NEWMAT::ColumnVector Matrix2MovePar(const NEWMAT::Matrix&           M,
				    const NEWIMAGE::volume<float>&  vol)
{
  NEWMAT::ColumnVector mp(6); mp = 0.0;
  NEWMAT::ColumnVector rot(3);

  MISCMATHS::rotmat2euler(rot,M);
  mp.Rows(4,6) = rot;

  NEWMAT::Matrix MM = MovePar2Matrix(mp,vol);
  mp.Rows(1,3) = M.SubMatrix(1,3,4,4) - MM.SubMatrix(1,3,4,4);

  return(mp);  
}
```

MovPar2Matrix:
```
NEWMAT::Matrix MovePar2Matrix(const NEWMAT::ColumnVector&     mp,
                              const NEWIMAGE::volume<float>&  vol) 
{
  if (mp.Nrows() != 6) throw TopupFileIOException("MovePar2Matrix: mp must have 6 elements");

  NEWMAT::ColumnVector tmp(6);
  tmp(1) = mp(4); tmp(2) = mp(5); tmp(3) = mp(6);
  tmp(4) = mp(1); tmp(5) = mp(2); tmp(6) = mp(3);
  
  NEWMAT::ColumnVector cntr(3);
  cntr(1) = ((vol.xsize()-1)*vol.xdim())/2.0;
  cntr(2) = ((vol.ysize()-1)*vol.ydim())/2.0;
  cntr(3) = ((vol.zsize()-1)*vol.zdim())/2.0;

  NEWMAT::Matrix mat(4,4);
  MISCMATHS::construct_rotmat_euler(tmp,6,mat,cntr);

  return(mat);
}
```

rotmat2euler:
```

  int rotmat2euler(ColumnVector& angles, const Matrix& rotmat)
    {
      // uses the convention that R = Rx.Ry.Rz
      Tracer tr("rotmat2euler");
      float cz, sz, cy, sy, cx, sx;
      cy = std::sqrt(Sqr(rotmat(1,1)) + Sqr(rotmat(1,2)));
      if (cy < 1e-4) {
	//cerr << "Cos y is too small - Gimbal lock condition..." << endl;
	cx = rotmat(2,2);
	sx = -rotmat(3,2);
	sy = -rotmat(1,3);
	angles(1) = atan2(sx,cx);
	angles(2) = atan2(sy,(float)0.0);
	angles(3) = 0.0;
      } else {
	// choose by convention that cy > 0
	// get the same rotation if: sy stays same & all other values swap sign
	cz = rotmat(1,1)/cy;
	sz = rotmat(1,2)/cy;
	cx = rotmat(3,3)/cy;
	sx = rotmat(2,3)/cy;
	sy = -rotmat(1,3);
	//atan2(sin,cos)  (defined as atan2(y,x))
	angles(1) = atan2(sx,cx);
	angles(2) = atan2(sy,cy);
	angles(3) = atan2(sz,cz);
      }
      return 0;
    }
```

construct_rotmat_euler:
```
  int construct_rotmat_euler(const ColumnVector& params, int n, Matrix& aff,
			     const ColumnVector& centre)
    {
      Tracer tr("construct_rotmat_euler");
      ColumnVector angl(3);
      Matrix newaff(4,4);
      aff=IdentityMatrix(4);

      if (n<=0) return 0;
      // order of parameters is 3 rotation + 3 translation
      // angles are in radians 
      //  order of parameters is (Rx,Ry,Rz) and R = Rx.Ry.Rz
      angl=0.0;
      angl(1)=params(1);
      make_rot(angl,centre,newaff);
      aff = aff * newaff;
      if (n==1) return 0;

      angl=0.0;
      angl(2)=params(2);
      make_rot(angl,centre,newaff);
      aff = aff * newaff; 
      if (n==2) return 0;

      angl=0.0;
      angl(3)=params(3);
      make_rot(angl,centre,newaff);
      aff = aff * newaff;
      if (n==3) return 0;

      aff(1,4)+=params(4);
      if (n==4) return 0;
      aff(2,4)+=params(5);
      if (n==5) return 0;
      aff(3,4)+=params(6);
      if (n==6) return 0;

      return 1;
    } 
```

**Comment by amirrezas** [comment]
To question 6:
The difference between the mcflirt .par file and topup _movpar.txt file is that the rotations and translations are switched. You can create that dummy file and give it to applytopup or eddy.
