### ISSUE TITLE
List the templates required by fmriprep in the faq

### ISSUE THREAD

**Issue by bpinsard** [poldracklab/fmriprep#2195]
In the faq, we could list the templates that are required by the pipeline, that need to be prefetched in the absence of internet connection on cluster node. Unless I haven't seen it in the doc, it is pretty much a trial and error, you have to wait for the pipeline to crash with a missing template to know. 

It seems that the pipeline requires: `'MNI152NLin2009cAsym', 'MNI152NLin6Asym', 'OASIS30ANTs'`
Can anyone confirm?

**Comment by oesteban** [comment]
@bpinsard this is a great idea - would you be willing to send a PR?

> It seems that the pipeline requires: `'MNI152NLin2009cAsym', 'MNI152NLin6Asym', 'OASIS30ANTs'`
> Can anyone confirm?

- `OASIS30ANTs` -> Default brain extraction. Except for users setting some other `--skull-stripping-template`, yes, this needs to be fetched (including T1w template and two masks)
- `MNI152NLin2009cAsym` -> Default standard space - always used. It requires the T1w template and a bunch of other masks and probseg files.
- `MNI152NLin6Asym` -> Necessary with `--use-aroma` or `--cifti-output` - although it is not strictly necessary, it's a good one to have prefetched.
