### ISSUE TITLE
Is T1w necessary when precomputed anat is given?

### ISSUE THREAD

**Issue by bpinsard** [poldracklab/fmriprep#2197]
When using precomputed anat, I am getting this message:

```
Exception: No T1w images found for participant 01. All workflows require T1w images.
```

It is because in our project, we have separate sub-datasets, one for anatomical and multiple functional.

Is the raw T1w used in the functional part of the pipeline, or this check could be skipped if smriprep output is given? 

Thanks!

**Comment by mgxd** [comment]
The T1w is required for transforming the functional data. We query the dataset to ensure there is at least one T1w available here:
https://github.com/poldracklab/fmriprep/blob/171ac24453397367bcaa30dafa009a7e0df7aa15/fmriprep/workflows/base.py#L150-L152

How does your dataset structure look?

**Comment by bpinsard** [comment]
From smriprep code, it seems that if precomputed smriprep ouputs are given with `--anat-derivatives`, the raw T1w image is not needed. 
https://github.com/nipreps/smriprep/blob/8c27ee49fe11ffa7bffcd4421affb8d3336268f6/smriprep/workflows/anatomical.py#L216
I will run some tests when skipping that check.


The structure of our dataset is a collection of BIDS folder (datalad)  in a super-dataset (datalad), one is anat (contains all the anatomical sessions), the other BIDS folders are functional only (each sub-dataset is a different set of stimuli), but for the exact same participants with matching IDs. Other folders are documentation and code.

$ tree -L 1 .
.
├── anat
│   ├── sub-01
│   ├── sub-02
│   ├── .........
├── code
├── dataset_description.json
├── docs
├── friends
│   ├── sub-01
│   ├── sub-02
│   ├── .........
├── hcptrt
│   ├── sub-01
│   ├── sub-02
│   ├── .........
├── movie10
│   ├── sub-01
│   ├── sub-02
│   ├── .........
└── README.md

**Comment by mgxd** [comment]
Does that top level directory pass BIDS validation?

In any case, the code snippet I linked above is hit even if `--anat-derivatives` is used. We *might* want to consider skipping it if the flag is used, with the assumption that users selecting that flag know what they're doing.

**Comment by bpinsard** [comment]
No, the top-level directory does not pass BIDS validation.
We run fmriprep with `--anat-only` on `/anat` then feed the smriprep results to runs of fmriprep on each functional sub-dataset.
