### ISSUE TITLE
precomputed anat. missing inputs

### ISSUE THREAD

**Issue by bpinsard** [poldracklab/fmriprep#2198]
I am getting the following warning::

`Attempted to access pre-existing anatomical derivatives at </anat>, however not all expectations of fMRIPrep were met (for participant <01>, spaces <MNI152NLin2009cAsym, MNI152NLin6Asym>, reconall <True>).`

I tried to use `smriprep.utils.bids.predict_derivatives()` to see which file were missing.

```
>>> drv=smriprep.utils.bids.predict_derivatives('01',['MNI152NLin2009cAsym','fsLR'],True)
>>> for f in drv:
...     if not os.path.exists(os.path.join('/anat/fmriprep/',f)):
...         print(f)
... 
sub-01/anat/sub-01_from-T1w_to-fsLR_mode-image_xfm.h5
sub-01/anat/sub-01_from-fsLR_to-T1w_mode-image_xfm.h5
sub-01/anat/sub-01_space-fsLR_desc-brain_mask.nii.gz
sub-01/anat/sub-01_space-fsLR_desc-preproc_T1w.nii.gz
sub-01/anat/sub-01_space-fsLR_dseg.nii.gz
sub-01/anat/sub-01_space-fsLR_label-CSF_probseg.nii.gz
sub-01/anat/sub-01_space-fsLR_label-GM_probseg.nii.gz
sub-01/anat/sub-01_space-fsLR_label-WM_probseg.nii.gz
```

Correct me if I am wrong but it seems to be expecting volumetric outputs for a surface-based templates.

However, I also tried :

```
>>> smriprep.utils.bids.collect_derivatives('/anat/','01',['MNI152NLin2009cAsym'],True)
>>> smriprep.utils.bids.collect_derivatives('/anat/','01',[],True)
>>> smriprep.utils.bids.collect_derivatives('/anat/','01',[],False)
```

All three return None.
There is no debug option to that command, so I am not sure what prevents me from loading the precomputed anat outputs.

Thanks for your help.

### What version of fMRIPrep are you using?

20.1.1

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?

Singularity

### What is the exact command-line you used?
```
<place your command line here>
```

### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```
<please copy&paste all the information you can gather about errors>
```

### fMRIPrep log
If you have access to the output logged by fMRIPrep, please make sure to attach it as a text file to this issue.

**Comment by oesteban** [comment]
Duplicate: nipreps/smriprep#211.

**Comment by bpinsard** [comment]
Sorry for the duplicate and thanks for the pointer, will close that one and follow on nipreps.

**Comment by oesteban** [comment]
Are you using the `--cifti-output` flag?

**Comment by bpinsard** [comment]
Yes, but the tests above are independent of the options provided to fmriprep. 
There are anatomical cifti outputs in that folder.

**Comment by bpinsard** [comment]
My bad, I was doing it wrong. I thought that I needed to provide the directory that contains `fmriprep` and `freesurfer` directories, so that it also load freesurfer, in fact it is the `fmriprep` subfolder that is needed.

I still have the problem for cifti, but at least it works for MNI.

I think I will do a PR to specify in the docs/usage which folder `--anat-derivatives` needs to point to. For now missing inputs and providing the wrong path results in the same warning, so it would at least rule-out the latter.
