### ISSUE TITLE
fmriprep docker error: concurrent.futures.process.BrokenProcessPool

### ISSUE THREAD

**Issue by MasonTWells** [poldracklab/fmriprep#2199]
Hi all,

I am running fmriprep in the docker using the following command:

fmriprep-docker /home/masontwells/Documents/BIDS/Nifti/ /home/masontwells/Documents/BIDS/derivatives/ participant --participant-label 0001 

The data is in BIDS format, and I have validated this before running the docker command. However, after several hours of running, I have the error below displayed in the terminal. I am not sure if this is a memory issue or not, or whether I should kill the process and start again (i.e. is fmri prep still running despite this message?).

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

Thanks in advance,
Mason

**Comment by mgxd** [comment]
More than likely, you are running into a memory issue - depending on your OS, you may need to allocate more memory/cores to Docker. Additionally, see an excerpt from a related issue (https://github.com/poldracklab/fmriprep/issues/1260) below:

> How much memory was available on your system? By default Nipype (and thus fMRIPrep) will assume that it can use up to about 90% of your system memory. You may want to consider restricting it using --mem-mb to more accurately reflect your available resources, or to artificially restrict it so that poor estimates of memory usage on our part don't cause crashes.

> Please be aware that larger BOLD series can consume large amounts of memory, and there's not much we can do about it but try to improve our memory estimates to avoid conflicts. (See #857.)

**Comment by MasonTWells** [comment]
Hi,

Thanks for the reply. I am using a Linux machine. Is there any documentation on how to allocate more memory to the docker, I have very little experience with this. Also, am I right in thinking that the error in the original post will result in fmriprep being killed, as such no further processing steps will be undertaken after the error?

**Comment by mgxd** [comment]
Docker on Linux isn't capped by default like on Mac/Windows, so you probably don't have to worry about that then.  Yes, this error will not allow fMRIPrep to finish successfully, though you can try restarting the job. Memory issues can be a bit difficult to track down without profiling, but here are some ideas:

- What version of fMRIPrep are you running?
- How much RAM is available on your system? We generally recommend 16GB, especially if you are working with high-res data.
- If you do have sufficient RAM, you can try capping the memory with the `--mem` and `--nprocs` flags, or try using the `--low-mem` flag.
- Additionally, there's this suggestion https://github.com/poldracklab/fmriprep/issues/1448#issuecomment-447564994 which avoids using `concurrent.futures`. Some users have found success with this.

Hope that helps!

**Comment by effigies** [comment]
Just a note that the `--low-mem` flag is not likely to do much anymore. It was used to permit memory mapping for some very specifically memory-intensive processes that we've re-written to be be more memory efficient.

**Comment by MasonTWells** [comment]
I am running fMRIPrep v20.1.1.

My memory available when running less /proc/meminfo is:

MemTotal:        8056664 kB
MemFree:         3699756 kB
MemAvailable:    4662872 kB

As a side note, can I ask if the docker version of fmriprep allows the same flags as are available when running through the manually prepared environment?

**Comment by mgxd** [comment]
> As a side note, can I ask if the docker version of fmriprep allows the same flags as are available when running through the manually prepared environment?
Yup, and any local paths you pass in are automatically mounted in the container for you

**Comment by oesteban** [comment]
@MasonTWells did you finally work around the problem?

**Comment by mgxd** [comment]
Closing this as it's gone stale, please reopen if you are still running into issues
