### ISSUE TITLE
No 6Asym_desc-preproc_bold.nii.gz file created

### ISSUE THREAD

**Issue by shanaahall** [poldracklab/fmriprep#2200]
The only 6Asym file that is created is the smoothAROMAnonaggr file. In contrast, all of the 2009cAsym files are created except the AROMA-ed file. 

Also, the CSF columns in the confounds file are just nans and the CSF anatomical file contains much less CSF matter than the CSF files for other participants. The other participants were run using an older version of fmriprep so this may be a function of the fmirprep update.

### What version of fMRIPrep are you using?
20.1.0
### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
Singularity
### What is the exact command-line you used?
```
qsub -l h_vmem=50G,vf=50G -N sub-00727fmriprep -o /mnt/BIAC/munin2.dhe.duke.edu/Meade/ConnNeuro.01/Analysis/BIDS/logs/FMRIprep_logs/Output-sub-00727fmriprep-jobid-%j.out -M shana.a.hall@duke.edu -b y "unset PYTHONPATH;  singularity run -B /mnt -e /usr/local/packages/singularity/images/fmriprep-v20.1.0_biac.simg /mnt/BIAC/munin2.dhe.duke.edu/Meade/ConnNeuro.01/Analysis/BIDS/data_BIDS /mnt/BIAC/munin2.dhe.duke.edu/Meade/ConnNeuro.01/Analysis/BIDS/data_fmriprep participant --participant-label 00727 -w /mnt/BIAC/munin2.dhe.duke.edu/Meade/ConnNeuro.01/Analysis/BIDS/fmriprep_workingdir --fs-license-file /mnt/BIAC/munin2.dhe.duke.edu/Meade/ConnNeuro.01/Scripts/license.txt  --use-syn-sdc --use-aroma --error-on-aroma-warnings"
```

### Have you checked that your inputs are BIDS valid?
Yes
### Did fMRIPrep generate the visual report for this particular subject? If yes, could you share it?

Will email link.
### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?

From fmriprep/sub-00727/log/fmriprep.toml
```
[environment]
cpu_count = 48
exec_env = "singularity"
free_mem = 63.3
overcommit_policy = "heuristic"
overcommit_limit = "50%"
nipype_version = "1.4.2"
templateflow_version = "0.6.2"
version = "20.1.0"

[execution]
bids_dir = "/mnt/BIAC/munin2.dhe.duke.edu/Meade/ConnNeuro.01/Analysis/BIDS/data_BIDS"
bids_description_hash = "184957f5258fbfe96f305a2b44ac93da829d86258395377a16af2573e32b61f8"
boilerplate_only = false
debug = false
fs_license_file = "/mnt/BIAC/munin2.dhe.duke.edu/Meade/ConnNeuro.01/Scripts/license.txt"
fs_subjects_dir = "/mnt/BIAC/munin2.dhe.duke.edu/Meade/ConnNeuro.01/Analysis/BIDS/data_fmriprep/freesurfer"
layout = "BIDS Layout: ...uro.01/Analysis/BIDS/data_BIDS | Subjects: 2 | Sessions: 2 | Runs: 4"
log_dir = "/mnt/BIAC/munin2.dhe.duke.edu/Meade/ConnNeuro.01/Analysis/BIDS/data_fmriprep/fmriprep/logs"
log_level = 25
low_mem = false
md_only_boilerplate = false
notrack = false
output_dir = "/mnt/BIAC/munin2.dhe.duke.edu/Meade/ConnNeuro.01/Analysis/BIDS/data_fmriprep"
output_spaces = "MNI152NLin2009cAsym:res-native"
reports_only = false
run_uuid = "20200608-160527_4e17ad30-e2fc-4891-bad1-93c2747ee55a"
participant_label = [ "00727",]
templateflow_home = "/home/fmriprep/.cache/templateflow"
work_dir = "/mnt/BIAC/munin2.dhe.duke.edu/Meade/ConnNeuro.01/Analysis/BIDS/fmriprep_workingdir"
write_graph = false

[workflow]
anat_only = false
aroma_err_on_warn = true
aroma_melodic_dim = -200
bold2t1w_dof = 6
bold2t1w_init = "register"
cifti_output = false
fmap_bspline = false
force_syn = false
hires = true
ignore = []
longitudinal = false
medial_surface_nan = false
regressors_all_comps = false
regressors_dvars_th = 1.5
regressors_fd_th = 0.5
run_reconall = true
skull_strip_fixed_seed = false
skull_strip_template = "OASIS30ANTs"
skull_strip_t1w = "force"
spaces = "MNI152NLin2009cAsym:res-native MNI152NLin6Asym:res-2"
use_aroma = true
use_syn_sdc = true

[nipype]
crashfile_format = "txt"
get_linked_libs = false
nprocs = 48
omp_nthreads = 8
plugin = "MultiProc"
resource_monitor = false
stop_on_first_crash = false

[seeds]
master = 35438
ants = 23657

[nipype.plugin_args]
maxtasksperchild = 1
raise_insufficient = false

```

Snippit from the output file. The full output file is attached here.
```
200610-02:12:35,447 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_00727_wf.func_preproc_ses_baseline_task_rest_acq_ppgresp_run_02_wf.bold_confounds_wf.tcc_metadata_fmt" in "/mnt/munin/Meade/ConnNeuro.01/Analysis/BIDS/fmriprep_workingdir/fmriprep_wf/single_subject_00727_wf/func_preproc_ses_baseline_task_rest_acq_ppgresp_run_02_wf/bold_confounds_wf/tcc_metadata_fmt".

Intel MKL ERROR: Parameter 11 was incorrect on entry to SGESVD.
200610-02:12:36,694 nipype.workflow INFO:
	 [Node] Running "tcc_metadata_fmt" ("niworkflows.interfaces.utils.TSV2JSON")
200610-02:12:37,269 nipype.workflow INFO:
	 [Node] Finished 
```
### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?
No

### fMRIPrep log
If you have access to the output logged by fMRIPrep, please make sure to attach it as a text file to this issue.
[Output-sub-00727fmriprep.txt](https://github.com/poldracklab/fmriprep/files/4819779/Output-sub-00727fmriprep.txt)

**Comment by mgxd** [comment]
fMRIPrep uses the `--output-spaces` flag to specify which `_preproc` outputs it produces. If the flag is not used in your command, only `MNI152NLin2009cAsym` will be used. If you want both outputs generated, you'll have to use the flag and specify both templates (`MNI152NLin2009cAsym` and `MNI152NLin6Asym`)

**Comment by shanaahall** [comment]
Ah ok great. I'll try that. Will that fix the CSF issue as well?

**Comment by oesteban** [comment]
> Will that fix the CSF issue as well?

You mean that:

```
Intel MKL ERROR: Parameter 11 was incorrect on entry to SGESVD.
```

?

That seems like a conflict between the singularity container and the hardware.

**Comment by shanaahall** [comment]
Well I just meant that the CSF columns in the confound file are all nans.

**Comment by shanaahall** [comment]
Hello,

I just wanted to follow-up with this and the n/as in the CSF columns in the confound file. Should I open a new issue for this question?

Thanks!

**Comment by mgxd** [comment]
yes, please open a separate issue. I'll close this one and we can follow up there
