### ISSUE TITLE
CIFTI ``dim`` field should be ``[6 1 1 1 1 X Y 1]``

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#2205]
From the [CIFTI-2 spec](https://www.nitrc.org/forum/attachment.php?attachid=341&group_id=454&forum_id=1955):

> Because the first four dimensions in NIfTIare reserved for space and time, the CIFTI dimensions are stored in the NIfTIheader in dim[5] and up, where dim[5] is the length of the first CIFTI dimension(number of valuesin a row), dim[6] is the length of the second CIFTI dimension, and dim[7] is the length ofthe third CIFTI dimension, if applicable.  The fields dim[1] through dim[4] will be 1; dim[0] will be 6 or 7, depending on whether a third matrix dimension exists.

**Comment by mgxd** [comment]
we can address this in niworkflows, but this sounds like something worth adding to the nibabel cifti module. I'm envisioning a helper method to set the intent code, as well as alter the NIfTI header accordingly. WDYT?

**Comment by effigies** [comment]
Yup, I'm okay doing this in nibabel.

**Comment by effigies** [comment]
@mgxd I checked out outputs again. It looks like this actually was being done, but for some reason the `Nifti2Image.header` was not the same as `Cifti2Image.nifti_header`.

```
>>> img = nb.Nifti2Image.from_filename('/data/out/qnl/repeat_change/fmriprep/sub-02/func/sub-02_task-repeatchange_run-5_space-fsLR_den-91k_bold.dtseries.nii')
>>> print(img.header)                                                                           
<class 'nibabel.nifti2.Nifti2Header'> object, endian='<'
sizeof_hdr      : 540
magic           : b'n+2'
eol_check       : [13 10 26 10]
datatype        : float64
bitpix          : 64
dim             : [    6     1     1     1     1   172 91282     1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
pixdim          : [1. 1. 1. 1. 1. 1. 1. 1.]
vox_offset      : 0
scl_slope       : nan
scl_inter       : nan
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
slice_start     : 0
slice_end       : 0
descrip         : b''
aux_file        : b''
qform_code      : unknown
sform_code      : unknown
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 0.0
qoffset_x       : 0.0
qoffset_y       : 0.0
qoffset_z       : 0.0
srow_x          : [0. 0. 0. 0.]
srow_y          : [0. 0. 0. 0.]
srow_z          : [0. 0. 0. 0.]
slice_code      : unknown
xyzt_units      : 0
intent_code     : ConnDenseSeries
intent_name     : b''
dim_info        : 0
unused_str      : b''
```

This is just to say that I don't think fMRIPrep needs to depend on our recent changes to nibabel in the near future.
