### ISSUE TITLE
Surface projections and surface spaces

### ISSUE THREAD

**Issue by MasonTWells** [poldracklab/fmriprep#2212]
Hi Experts,

I am running the following command.

fmriprep-docker /home/masontwells/Documents/BIDS/Nifti/ /home/masontwells/Documents/BIDS/derivatives/ participant --participant-label 0001 --cifti-output 91k --output-spaces fsnative

I just wanted to double check some logic with respect to the output surfaces and the functional projection. I am using wb_view to visualize the outputs of fmriprep. Am I correct in thinking that fs-native_hemi[LR]_bold.func.gii can be overlaid on the mid thickness surface output in the subjects anat folder? Does this surface match the functional data space? Likewise, which surface can be used to overlay the fsLR_den-91k_bold.dtseries.nii? I know this is a CIFTI file, but I can't seem to find the surface that matches this space in the output folders. Would I need to get this from the HCP repository? 

Best wishes,
Mason

**Comment by effigies** [comment]
Hi, thanks for your questions!

> Am I correct in thinking that fs-native_hemi[LR]_bold.func.gii can be overlaid on the mid thickness surface output in the subjects anat folder?

Correct. It can actually be overlaid on any of the surfaces of the same hemisphere.

> Does this surface match the functional data space?

I'm not sure I understand this question. The surface and functional data are both aligned to the `desc-preproc_T1w.nii.gz` file in your `anat/` folder, if that's what you mean.

> Likewise, which surface can be used to overlay the fsLR_den-91k_bold.dtseries.nii? I know this is a CIFTI file, but I can't seem to find the surface that matches this space in the output folders. Would I need to get this from the HCP repository?

Yes. You can find them [here](https://github.com/Washington-University/HCPpipelines/tree/master/global/templates/standard_mesh_atlases).

There are also the Conte69 surfaces that can be used for visualization: https://github.com/mgxd/brainplot/tree/master/brainplot/Conte69_Atlas

**Comment by MasonTWells** [comment]
Thanks for the reply!

With my first question, I assume you mean it can be overlaid on the hemi-[RL]_smoothwm/pial/midthickness/inflated.surf.gii.?
 
What I meant by second questions was that I assume during the surface projection stage, the data is projected to a specific surface. I just wanted to make sure that the functional data is overlaid onto the correct surface. For example, if the functional data is project to the fsnative surface, overlaying it onto the fsaverage would be incorrect? Likewise, overlaying the output of the --cifti-output flag (fsLR_den-91k_bold.dtseries.nii) onto the midthickness surface would be incorrect? (Hope that makes sense...)

With respect to the 91k surface, in the directory you linked here, there are 59k and 32k surfaces, not 91k surfaces as is specified in fmriprep. Does this matter or is this just the resolution of the surface?

**Comment by effigies** [comment]
> With my first question, I assume you mean it can be overlaid on the hemi-[RL]_smoothwm/pial/midthickness/inflated.surf.gii.?

Yes. All of these have the same mesh, but different coordinates. By the time you have functional data sampled onto the mesh, the choice of coordinates is only significant for distance-based smoothing or visualization. Inflated, for instance, is only useful for visualization.

It is important to note that the same vertex on the gray/white and pial surfaces are connected by a vector normal to the smoothed white matter surface. Thus if a point is at the bottom of a sulcus on one, it is also on the other.
 
> What I meant by second questions was that I assume during the surface projection stage, the data is projected to a specific surface.

The data is sampled at five points between the gray-white boundary and the pial surface and averaged. You can think of it as being projected onto these two surfaces as well as three that are (pointwise) evenly spaced between the two surfaces. Because these vertices are aligned on the surface normal, you are effectively sampling the cortical layers.

> I just wanted to make sure that the functional data is overlaid onto the correct surface. For example, if the functional data is project to the fsnative surface, overlaying it onto the fsaverage would be incorrect?

Correct. The surfaces provided in `anat/` are `fsnative` spaces. To get them in fsaverage, you can use `mri_surf2surf`, but getting that right can be a little tricky. If you did want data in fsaverage, I would recommend making it an explicit output space of fMRIPrep.

> Likewise, overlaying the output of the --cifti-output flag (fsLR_den-91k_bold.dtseries.nii) onto the midthickness surface would be incorrect? (Hope that makes sense...)

Correct again.

> With respect to the 91k surface, in the directory you linked here, there are 59k and 32k surfaces, not 91k surfaces as is specified in fmriprep. Does this matter or is this just the resolution of the surface?

The 91k resolution CIFTI is actually 2x (left and right) 32k vertices surfaces and ~23k subcortical voxels.

**Comment by effigies** [comment]
To view the CIFTIs in `wb_view`, you can use this `wb.spec` file:

```XML
<?xml version="1.0" encoding="UTF-8"?>
<CaretSpecFile Version="1.0">
   <MetaData>
   </MetaData>
   <DataFile Structure="CortexLeft"
             DataFileType="SURFACE"
             Selected="true">
      https://raw.githubusercontent.com/mgxd/brainplot/master/brainplot/Conte69_Atlas/Conte69.L.midthickness.32k_fs_LR.surf.gii
   </DataFile>
   <DataFile Structure="CortexRight"
             DataFileType="SURFACE"
             Selected="true">
      https://raw.githubusercontent.com/mgxd/brainplot/master/brainplot/Conte69_Atlas/Conte69.R.midthickness.32k_fs_LR.surf.gii
   </DataFile>
   <DataFile Structure="Invalid"
             DataFileType="VOLUME"
             Selected="true">
      https://templateflow.s3.amazonaws.com/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-02_T1w.nii.gz
   </DataFile>
</CaretSpecFile>
```

**Comment by MasonTWells** [comment]
Hi,

Thanks for your detailed replies. I used fmriprep to get my function data on a surface (sub-0001_ses-1_task-rest_acq-TR2000_space-fsLR_den-91k_bold.dtseries.nii). I then put this CIFTI through Melodic. I wonder if you can offer any advice on how to display this on the correct surface using wb_view? I see your wb.spec file above, but I am unsure on how to create this correctly and display the component map on the surface. Any tips would be great!

Thanks.

**Comment by effigies** [comment]
Hi, I'm not very familiar with MELODIC. What kind of files do you get? If it's in the same space, then it should load in wb_view the same as the dtseries.

**Comment by MasonTWells** [comment]
I get a CIFTI file output. When I try to open this: wb_view > File > Open file. I get this gui error:

NAME OF FILE: melodic_IC.nii
PATH TO FILE: /home/masontwells/Documents/Data/ICA/sub-0001/ses-1/surface_ICA/first_run

Cifti files cannot be used as volume files

**Comment by MasonTWells** [comment]
I have now convefted this CIFTI into a GIFTI file using wb_command. However, this too can't be loaded in wb_view.

**Comment by oesteban** [comment]
I think this is more of a question to the workbench developers. Please reopen if there's something fMRIPrep is not doing correctly (and please post the answer if you manage to visualize these files)
