### ISSUE TITLE
Co-registration of fMRI data with subjects own structural space

### ISSUE THREAD

**Issue by shilpitju** [poldracklab/fmriprep#2213]
Hi,

While doing clinical fMRI we need to have fMRI data of a subject coregistered with subject's own structural space. 

In fmriprep documentation it is mentioned that using --output-spaces T1w or anat identifier, data are resampled into the individual’s anatomical reference generated with the T1w and T2w images available within he BIDS structure.

That means using this identifier for output space serves my purpose? Am I understanding it correctly?

Thanks,

Regards,

Shilpi Modi

**Comment by effigies** [comment]
Yes, that is correct.

**Comment by shilpitju** [comment]
Oh! That's fantastic.

Thanks
