### ISSUE TITLE
Out of date function reference in workflows.rst

### ISSUE THREAD

**Issue by emdupre** [poldracklab/fmriprep#2214]
Currently, the workflows section on [refinement of the brain mask](https://github.com/poldracklab/fmriprep/blob/e5f067ddd67790f25e1ecb51c4ad1d6265a6a31d/docs/workflows.rst#refinement-of-the-brain-mask) points to an older fMRIPrep freesurfer interface. I believe this functionality has since been moved to niworkflows in the freesurfer [RefineBrainMask](https://github.com/nipreps/niworkflows/blob/b7f01bb403d26aa3ab22a286d389b6ae3e99819c/niworkflows/interfaces/freesurfer.py#L289) interface.

I'm happy to update the reference, but I wanted to make sure my mapping was correct, first !

**Comment by mgxd** [comment]
Yeah, that looks right to me - nice catch!
