### ISSUE TITLE
normalizing an ROI after fmriprep

### ISSUE THREAD

**Issue by s2334** [poldracklab/fmriprep#2217]
Hi experts,
I have run fmriprep with --output-spaces T1w. This created a *_space-T1w_desc-preproc_bold.nii.gz file as expected.
I also have an ROI which is in the same space as the file above (ie, T1w space and in native resolution).
How can I bring this ROI to MNI space, so that it matches *_space-MNI152NLin6Asym_desc-preproc_bold.nii.gz?
Thank you in advance for your help!

**Comment by mgxd** [comment]
If you had `MNI152NLin6Asym` in your `--output-spaces`, fmriprep will include the `...from-T1w_to-MNI152NLin6Asym_mode-image_xfm.h5` transform in your anatomical outputs. 

You then should be able to apply that transform to the ROI to get it in MNI space. (i.e. `antsApplyTransform`, or https://github.com/poldracklab/nitransforms)

**Comment by s2334** [comment]
Thank you @mgxd. That was what I thought, but somehow antsApplyTransforms is not giving the expected output.

Let's say I'd like to transform *space-T1w_desc-aparcaseg_dseg.nii.gz to MNI152NLin6 space. I know the output  should look exactly like the file *space-MNI152NLin6Asym_desc-aparcaseg_dseg.nii.gz stored in the func folder.

I ran this command:
antsApplyTransforms -d 3 -n MultiLabel -i sub023_task-VIS_space-T1w_desc-aparcaseg_dseg.nii.gz -r MNI152_T1_1mm.nii.gz -t sub023_from-T1w_to-MNI152NLin6Asym_mode-image_xfm.h5 -o T1w2mni.nii.gz 

Although close, the output T1w2mni.nii.gz is not exactly the same as the file *space-MNI152NLin6Asym_desc-aparcaseg_dseg.nii.gz in the func folder. But the two files should be identical, shouldn't they?

**Comment by effigies** [comment]
Can you try replacing the reference image with the image you want to compare to?

```
antsApplyTransforms -d 3 -n MultiLabel -i sub023_task-VIS_space-T1w_desc-aparcaseg_dseg.nii.gz -r *space-MNI152NLin6Asym_desc-aparcaseg_dseg.nii.gz -t sub023_from-T1w_to-MNI152NLin6Asym_mode-image_xfm.h5 -o T1w2mni.nii.gz
```

If that gets you the correct output, then the problem is most likely that your particular `MNI152_T1_1mm.nii.gz` has a mismatched affine or field-of-view relative to the template we're using. Assuming that turns out to be the case, what's your source for that file?

**Comment by mgxd** [comment]
Just to add to @effigies's response - `fmriprep` leverages the [templates provided by templateflow](https://www.templateflow.org/usage/archive/#templateflows-data-structure), so you'll want to make sure you are using `tpl-MNI152NLin6Asym_res-01_T1w.nii.gz` template as a reference.

**Comment by mgxd** [comment]
Closing this as it's gone stale, please reopen if you are still running into issues
