### ISSUE TITLE
Distortion correction using reverse phase encoding direction image

### ISSUE THREAD

**Issue by MasonTWells** [poldracklab/fmriprep#2218]
Hi Experts,

I am using fmriprep to pre-process a series of resting-state data. I have acquired a reverse phase encoding direction image to aid with distortion correction. In previous analysis pipelines, I have created a field map using [this technique](https://lcni.uoregon.edu/kb-articles/kb-0003), and then used it as an input in Feat. I wonder how this works in fmriprep? I have the DICOM for this image, but I am not sure where this fits within the bids directory needed to run fmriprep. I assume it belongs in the func folder, once it's been converted to NIFTI? Do I need to continue with my currently pipeline, in that I need to create the distortion correction map using the technique above. If so, where should I place the resulting map, and is there a flag I need to add in order to point fmriprep to this map? Or, does fmriprep conduct distortion corrections without such a map being needed?

Best wishes,
Mason

**Comment by MasonTWells** [comment]
Hi Experts,

I wondered if anyone has any thoughts about my comment above? I essentially want to know if fmriprep allows distortion  correction maps to be applied, and if so, at which stage would they be included?

Thanks,
Mason

**Comment by oesteban** [comment]
> I am not sure where this fits within the bids directory needed to run fmriprep

Yes, it does fit - https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-1-phase-difference-image-and-at-least-one-magnitude-image

> I assume it belongs in the func folder, once it's been converted to NIFTI?

Please, don't assume this. It goes into the `fmap/` folder. 👍 

> there a flag I need to add in order to point fmriprep to this map?

No, but if you want susceptibility distortion estimation and correction to happen, they make sure that the `IntendedFor` metadata (the sidecar json file of the `_phasediff.nii.gz` file) is defined and pointing to the rsfMRI data you want to apply them on.

> Or, does fmriprep conduct distortion corrections without such a map being needed?

fMRIPrep *can* run distortion corrections without fieldmaps, but I definitely don't recommend you to do this if you don't have a very clear picture of what you are doing. Considering your questions, I invite you to do a deep read of fmriprep's documentation (esp. sections about SDC) - https://fmriprep.org. The response to your question is there. Sorry for this kind-of-RTM, but I believe you'll need to first understand the processing before you make these decisions.



> I essentially want to know if fmriprep allows distortion correction maps to be applied, and if so, at which stage would they be included?

This is certainly found at https://fmriprep.org.

**Comment by oesteban** [comment]
BTW, the link you posted above is definitely not the "_reverse phase encoding direction image_" technique.

**Comment by oesteban** [comment]
I'm going to close this to clear up a bit our tracker. Please feel free to reopen if needed.
