### ISSUE TITLE
Example buttons from MRIqc for annotation form in fmriprep

### ISSUE THREAD

**Issue by dorianps** [poldracklab/fmriprep#2220]
@oesteban following our discussion last week, can you paste an example of the mriqc widget form so I can point the developers to that example to extract the colorful buttons used in mriqc. I think you mentioned they become available from bootstrap.js.

Thank you.
Dorian

**Comment by mgxd** [comment]
@dorianps perhaps this is what you were looking for?

https://github.com/poldracklab/mriqc/pull/743

**Comment by dorianps** [comment]
Will have a look at that code to see if we can implement the buttons. For now I am investing on other dataset and image filtering options while using regular form features.

Thank you.

**Comment by mgxd** [comment]
Closing this as it's gone stale, please reopen if you are still running into issues
