### ISSUE TITLE
spike regressors

### ISSUE THREAD

**Issue by shilpitju** [poldracklab/fmriprep#2221]
Hi,

In the documentation it is mentioned that:
Spike regressors for outlier censoring can also be generated from within fMRIPrep using the command line options --fd-spike-threshold and --dvars-spike-threshold (default: FD > 0.5 mm or DVARS > 1.5). Spike regressors are stored in separate motion_outlier_XX columns.

While preprocessing my dataset, I didn't used the flags --fd-spike-threshold and --dvars-spike-threshold. However, my confound tsv files generated have motion_outlier_xx columns. 

Do these motion_outlier_xx columns correspond to outliers in FD and DVARS?

Thanks,

Shilpi Modi

**Comment by mgxd** [comment]
Yes, those columns correspond to the default thresholds.

**Comment by shilpitju** [comment]
Thanks
