### ISSUE TITLE
FMRIPrep-docker issue - running for first time

### ISSUE THREAD

**Issue by mbichin** [poldracklab/fmriprep#2224]
Hello I am running FMRIPrep for the first time useing the following command line:

```
fmriprep-docker /mnt/DATA/Trajectories_Data/Brain/rs_data_fmriprep_input/ /mnt/DATA/Trajectories_Data/Brain/rs_data_fmriprep_output/ participant --participant-label regtrj040 --task-id rest --fs-license-file /usr/local/freesurfer/license.txt --skull-strip-t1w force --output-space MNI152NLin6Asym --use-aroma --fs-no-reconall --fd-spike-threshold 2 --force-bbr --dummy-scans 0 --n-cpus 6 --mem 30_GB -v --notrack
``` 
The first time i tried running the program, it stopped midway as I ran out of room on the drive. I dealt with the issue and removed and reinstalled the program. I tried running it the second time, I noticed that it didnt download a bunch of files as it did the first time and I received improper syntax errors. I installed a newer version of python and that seemed to fix that problem with the syntax errors, though it still did not download the files as it had the first time. 

Now when I run it I get the following errors:
RUNNING: docker run --rm -it -e DOCKER_VERSION_8395080871=19.03.12 -v /usr/local/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /mnt/DATA/Trajectories_Data/Brain/rs_data_fmriprep_input:/data:ro -v /mnt/DATA/Trajectories_Data/Brain/rs_data_fmriprep_output:/out poldracklab/fmriprep:20.1.1 /data /out participant --participant-label regtrj040 --task-id rest --skull-strip-t1w force --use-aroma --fs-no-reconall --fd-spike-threshold 2 --force-bbr --dummy-scans 0 --n-cpus 6 --mem 30_GB -v --notrack --output-spaces MNI152NLin6Asym
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 17, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/parser.py", line 566, in parse_args
    opts = parser.parse_args(args, namespace)
  File "/usr/local/miniconda/lib/python3.7/argparse.py", line 1749, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/local/miniconda/lib/python3.7/argparse.py", line 1781, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/miniconda/lib/python3.7/argparse.py", line 1987, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/local/miniconda/lib/python3.7/argparse.py", line 1927, in consume_optional
    take_action(action, args, option_string)
  File "/usr/local/miniconda/lib/python3.7/argparse.py", line 1839, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/local/miniconda/lib/python3.7/argparse.py", line 2369, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/local/miniconda/lib/python3.7/argparse.py", line 2402, in _get_value
    result = type_func(arg_string)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/parser.py", line 44, in _to_gb
    return int(digits) * scale[units[0]]
KeyError: '_'
fMRIPrep: Please report errors to https://github.com/poldracklab/fmriprep/issues

I can really use some help. Thanks in advance for the effort.

**Comment by effigies** [comment]
`--mem-gb 30`

**Comment by effigies** [comment]
Sent the last response from my phone. Looks like I got it wrong. Here's the issue:

```Diff
 fmriprep-docker /mnt/DATA/Trajectories_Data/Brain/rs_data_fmriprep_input/ \
     /mnt/DATA/Trajectories_Data/Brain/rs_data_fmriprep_output/ \
     participant --participant-label regtrj040 --task-id rest \
     --fs-license-file /usr/local/freesurfer/license.txt --skull-strip-t1w force \
     --output-space MNI152NLin6Asym --use-aroma --fs-no-reconall \
-    --fd-spike-threshold 2 --force-bbr --dummy-scans 0 --n-cpus 6 --mem 30_GB -v --notrack
+    --fd-spike-threshold 2 --force-bbr --dummy-scans 0 --n-cpus 6 --mem-mb 30000 -v --notrack
```

**Comment by mbichin** [comment]
Excellent! I tried that and the error changed  to :
```
Traceback (most recent call last):
  File "/home/mbichin/.local/bin/fmriprep-docker", line 11, in <module>
    sys.exit(main())
  File "/home/mbichin/.local/lib/python2.7/site-packages/fmriprep_docker.py", line 497, in main
    print("RUNNING: " + ' '.join(command))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
```
Any words of wisdom?

**Comment by effigies** [comment]
Looks like you've got some weird character in there somehow. I'd try retyping to make sure you didn't grab something weird with copy-paste.

**Comment by mbichin** [comment]
Thanks, thats exacly what it was. Running correctly now... just have to deal with the errors and warnings. I can handle that. 
Thanks for all your help.
