### ISSUE TITLE
Estimated fieldmap and alignment to the corresponding EPI reference

### ISSUE THREAD

**Issue by MasonTWells** [poldracklab/fmriprep#2225]
Hi Experts, 

I have question about the HTML report generated by fmriprep. I have run the following command for 3 subjects, all of whom have an opposite phase encoding image in the fmap folder and corresponding json file.

fmriprep-docker /home/masontwells/Documents/BIDS/Nifti/ /home/masontwells/Documents/BIDS/derivatives/ participant --participant-label 0004 --output-spaces fsnative T1w

I wonder why for only 1 subject there is an image showing the estimated field map and alignment to the corresponding EPI reference, but not the other two subjects? See below.

Cheers,
Mason

![2](https://user-images.githubusercontent.com/67323940/88560176-b65ae900-d025-11ea-878d-120acb8b2b37.jpg)
![1](https://user-images.githubusercontent.com/67323940/88560177-b6f37f80-d025-11ea-8f57-41c9aa25fe5f.jpg)

**Comment by oesteban** [comment]
Almost certainly, that is your setting of the `IntendedFor` metadata - see https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-1-phase-difference-image-and-at-least-one-magnitude-image

**Comment by oesteban** [comment]
I'm going to close this to clear up a bit our tracker. Please feel free to reopen if needed.
