### ISSUE TITLE
Transformed, but not resampled, anat images

### ISSUE THREAD

**Issue by mathias-sm** [poldracklab/fmriprep#2226]
For a given set of subjects, my anat files are at resolution `0.65x0.65x0.65`. It looks like when computing the transformation to a reference space, in my case `MNI152NLin6Asym`, `fmriprep` resamples the images to `1x1x1`. I can't find a way to avoid this [in the doc](https://fmriprep.org/en/stable/spaces.html)? Here's an excerpt of what's under the `derivatives/fmriprep/sub-01/anat` folder at the end of the run:

```bash
$ nib-ls sub-01_desc-preproc_T1w.nii.gz sub-01_space-MNI152NLin6Asym_*.nii*
sub-01_desc-preproc_T1w.nii.gz                         int16  [240, 320, 320] 0.65x0.65x0.65   sform
sub-01_space-MNI152NLin6Asym_desc-brain_mask.nii.gz    uint8  [182, 218, 182] 1.00x1.00x1.00
sub-01_space-MNI152NLin6Asym_desc-preproc_T1w.nii.gz  float32 [182, 218, 182] 1.00x1.00x1.00
sub-01_space-MNI152NLin6Asym_dseg.nii.gz               int16  [182, 218, 182] 1.00x1.00x1.00
sub-01_space-MNI152NLin6Asym_label-CSF_probseg.nii.gz float32 [182, 218, 182] 1.00x1.00x1.00
sub-01_space-MNI152NLin6Asym_label-GM_probseg.nii.gz  float32 [182, 218, 182] 1.00x1.00x1.00
sub-01_space-MNI152NLin6Asym_label-WM_probseg.nii.gz  float32 [182, 218, 182] 1.00x1.00x1.00
```

`fmriprep` was invoked with the following command:

```bash
singularity run --cleanenv fmriprep-sing bids_data/bids_dataset output participant --fs-license-file license.txt --output-spaces anat func MNI152NLin6Asym:res-native
```

Thanks,

**Comment by mgxd** [comment]
Hi @mathias-sm, thanks for the report! This is indeed a bug, where we are not respecting the native resolution during the transform. We will have a fix out for the next release
