### ISSUE TITLE
How fmriprep deals with multiple T1 ?

### ISSUE THREAD

**Issue by tib-sim** [poldracklab/fmriprep#2227]
Hi, 
I am wondering how fmriprep deals with mutliple T1 ?
In my case we did only one T1 acquisition but we applied a "retro-reconstruction" on this image by removing the "pre-scan normalization filter". This resulted in a second T1, that we aim to use enventually for structural analysis. Once I converted my data in BIDS, I tried to keep all images, thus the first T1 was defined with the suffix "run-001" and the second with the suffix "run-002". 
I am wondering if this can caused issue during the preprocessing done by fmriprep ?
Best,
Simon

**Comment by bpinsard** [comment]
Hi Simon,
The default behavior of fmriprep is to average all T1, with freesurfer `mri_robust_template`.
In your case I would say that it is not optimal to average the same acquisition with 2 reconstruction options.
You can use the option `--bids-filter-file` to have more specific way to select which file you want to use.
Here is the doc on how to use it.
https://fmriprep.org/en/latest/faq.html#how-do-i-select-only-certain-files-to-be-input-to-fmriprep

Best.

**Comment by emdupre** [comment]
Just to +1 @bpinsard's suggestion !

One other note: `run` is probably not the way I would distinguish these two files in BIDS. You might want to look instead at the `rec` entitiy: https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#the-rec-entity

**Comment by tib-sim** [comment]
Thank you for your replies and help !
Even if I use the ```rec``` entity, I guess I will have to use in any case the ```--bids-filter-file``` option by specifying which T1 to select in the JSON file. I guess ```rec``` does not allow to avoid the averaging of all T1 by fmriprep ?
Best,
Simon

**Comment by mgxd** [comment]
Nope, fmriprep does not make any inclusion / exclusion assumptions based on the `rec` entity.

**Comment by shawnyoung23** [comment]
hi, i used fmriprep to average two T1Ws. The only difference between these two is the NORM tag under IMAGETYPE in the json file:

"ImageType":[
"original","PRIMARY","M","ND","NORM"]

i am just wondering if that would be a problem in subsequent processing or quality of data?
