### ISSUE TITLE
fmriprep version upgrade error

### ISSUE THREAD

**Issue by Tao-ZJU** [poldracklab/fmriprep#2228]
Hi fmriprep experts,

I've installed the fmriprep via docker. The current fmriprep version is 20.0.5. I  am trying to upgrade the fmriprep version to the newest version with the following command: pip install --user --upgrade fmriprep-docker. But I got the error:
![error](https://user-images.githubusercontent.com/57374591/88617297-1ca63280-d04b-11ea-84ce-9fd76db311a5.jpg)

Can you tell me how to upgrade the fmriprep version?

Thanks!

**Comment by effigies** [comment]
It looks like a network error. Nothing to do but wait a bit and retry.

**Comment by Tao-ZJU** [comment]
> It looks like a network error. Nothing to do but wait a bit and retry.

Sure, it is a network error. I have successfully upgraded the version. Thanks.
