### ISSUE TITLE
MNI composite transformation on optimally combine multi-echo data 

### ISSUE THREAD

**Issue by JulioAPeraza** [poldracklab/fmriprep#2236]
Hello,

I am running fMRIPrep on a multi-echo dataset using `20.1.1`. I am doing SDC as part of the workflow of fMRIPrep. I was looking the composite transformation (`mat2itk.txt`, `_warpfieldQwarp_PLUS_WARP_fixhdr.nii.gz`, `out_fwd.tfm`, `ants_t1_tomniComposite`) to the MNI, and I realized the transformation is performed to `split_opt_comb/vol*` 

Tracking down the image from `split_opt_comb`, I ended up with `bold_bold_trans_wf/_bold_file_..data..sub-<>..func..sub-<>_task-<>_run-<>_echo-1_bold.nii.gz/merge/vol0000_xform-00000_merged.nii.gz` which seems to be motion and distortion corrected. If that is the case, fmriprep might be applying motion correction and the fieldwarp two times (thanks @tsalo ).

I only read the command.txt files saved in the working directory, so I may be missing something. Could you help me find the origin of split_opt_comb/vol*, if different from the one I found?

Thanks!

**Comment by tsalo** [comment]
Here are some relevant sections of the code:

1) `bold_split` is data without any transforms (no HMC, SDC, or coregistration to T1w)

https://github.com/poldracklab/fmriprep/blob/c717c6b216886be5de75627c067018700f0efd75/fmriprep/workflows/bold/base.py#L429-L430

2) `bold_std_trans_wf` takes in `bold_split` for non-multi-echo, but it takes in `split_opt_comb` (optimally combined after STC, HMC, and SDC) for multi-echo.

https://github.com/poldracklab/fmriprep/blob/c717c6b216886be5de75627c067018700f0efd75/fmriprep/workflows/bold/base.py#L664-L677

3) `bold_std_trans_wf` expects data that hasn't been motion corrected, but can be slice timing corrected.

https://github.com/poldracklab/fmriprep/blob/c717c6b216886be5de75627c067018700f0efd75/fmriprep/workflows/bold/resampling.py#L234-L235

4)

The ME-EPI workflow here seems to go `meepi_echos` --> `bold_stc_wf` --> `boldbuffer`  --> `bold_bold_trans_wf` --> `skullstrip_bold_wf` --> `join_echos` --> `bold_t2s_wf` --> `split_opt_comb` --> `bold_std_trans_wf`.

The SE-EPI workflow here goes `bold_reference_wf` --> `bold_stc_wf` --> `boldbuffer` --> `bold_split` --> `bold_std_trans_wf`.

**Comment by tsalo** [comment]
I think there are three solutions (assuming there isn’t a secret workaround that we haven't noticed yet):
1. Undo HMC and SDC xforms on optimally combined multi-echo data before feeding it into `bold_std_trans_wf`.
2. Add new workflow just for the reference to standard xform (`ref_std_trans_wf`).
3. Drop the HMC xform and SDC warp connections to `bold_std_trans_wf` for ME data specifically. 
    - This assumes that `bold_std_trans_wf` can handle empty xform inputs, which is reasonable, but I haven't checked it yet.

**Comment by emdupre** [comment]
For maintainability, I'd prefer to avoid (2). 

I think (3) is possible, we'd just need to validate whether the xforms exist and update the [`merge_xform` connections](https://github.com/poldracklab/fmriprep/blob/c717c6b216886be5de75627c067018700f0efd75/fmriprep/workflows/bold/resampling.py#L338-L341) appropriately. I'd prefer (3) over (1) in that it'd be a more readable solution, which should also help with maintenance over time !

**Comment by JulioAPeraza** [comment]
One question: Does (3) imply dropping split_opt_comb from ME-EPI workflow?

**Comment by tsalo** [comment]
I don't think so. It should just involve disconnecting the following connections in an if statement for ME data:

https://github.com/poldracklab/fmriprep/blob/c717c6b216886be5de75627c067018700f0efd75/fmriprep/workflows/bold/base.py#L640-L641

https://github.com/poldracklab/fmriprep/blob/c717c6b216886be5de75627c067018700f0efd75/fmriprep/workflows/bold/base.py#L646-L647

Plus ensuring that `bold_std_trans_wf` can handle missing xforms in the manner @emdupre proposed.

**Comment by effigies** [comment]
I agree that (3) is the best of those three options. I see two implementation options:

1) Condition the construction of the transform lists on whether we have multiecho.
2) Pass in an identity transform for anything that doesn't need to be applied. (antsApplyTransforms will just take the string `"identity"`, so we don't even need to create identity files.)

That latter might simplify a bit of the conditional logic for SDC as well, since we currently determine the length of the transform list based on whether SDC is to be applied

**Comment by effigies** [comment]
@JulioAPeraza please try `poldracklab/fmriprep:unstable`.
