### ISSUE TITLE
T2w seemingly never used

### ISSUE THREAD

**Issue by cmpetty** [poldracklab/fmriprep#2237]
using fmriprep v1.5.9 on about 170 subjects we noticed that nowhere in our logs the T2w image was used.  We'd assumed based on the anatomical preprocessing documentation that it would get picked up for use in freesurfer, but is this not the case?

i've searched all the logs and outputs, but it was never used
[sub-7775.2283122.out.txt](https://github.com/poldracklab/fmriprep/files/5059400/sub-7775.2283122.out.txt)

output of one bids-validator
`
        Summary:                   Available Tasks:        Available Modalities: 
        2085 Files, 83.99GB        reward                  T1w                   
        121 - Subjects                   rest                       T2w                   
        1 - Session                                                      bold                  
                                                                                events                
                                                                                fieldmap              

`

Our call to the singularity build:
`
singularity run --cleanenv -B ${SINGULARITYENV_TEMPLATEFLOW_HOME}:/opt/templateflow /usr/local/packages/singularity/images/fmriprep-v1.5.9_biac.simg ${DSNUM}  ${SESS} participant \
 --participant-label ${SUBJ} \
 --nthreads 12 --omp-nthreads 12 --skip_bids_validation \
 --work-dir /mnt/munin5/Gaffrey/NTREC.01/Analysis/output/${SESS}/work \
 --use-aroma --aroma-melodic-dimensionality 30 \
 --ignore fieldmaps \
 --skull-strip-template MNIPediatricAsym:cohort-2 \
 --output-spaces MNIPediatricAsym:cohort-2:res-2 MNI152NLin2009cAsym \
 --use-syn-sdc --force-syn \
`

Attaching an output log.

**Comment by effigies** [comment]
We do use the T2w image in FreeSurfer, but only if it has voxels 1.2mm isotropic or smaller. This is the criterion given on the FreeSurfer mailing list for whether T2w provides any benefit, so we've followed that.

This might be the issue?

**Comment by cmpetty** [comment]
I see, that would definitely clear things up.

In our larger dataset of 120 subjects the T2 isn’t isotropic, its 1x1x2.6, so it was never used.   In the much smaller dataset it does appear to get used in recon-all since its .9mm isotropic.  Thanks for clearing that up.

-Chris

**Comment by effigies** [comment]
Glad (sorry?) to have found the issue. Just to be clear, we don't require them to be isotropic, but have a largest dimension of 1.2mm.

You are welcome to try to insert the T2w images. FreeSurfer will gladly take it after the initial run and reprocess. If it does turn out to have helped, you can rerun fmriprep, and the improvements will be picked up. If you still have the working directory, it will be as efficient as possible.
