### ISSUE TITLE
bold_t1_trans_wf connection for ME-EPI inputs

### ISSUE THREAD

**Issue by emdupre** [poldracklab/fmriprep#2238]
In reviewing the ME connections for #2236, I noticed that the `bold_t1_trans_wf` connection for ME-EPI data seems to need an update. Specifically, for single-echo EPI, we pass the 4D bold time series as a list of 3D files to the workflow's `inputnode.bold_split`:

https://github.com/poldracklab/fmriprep/blob/c717c6b216886be5de75627c067018700f0efd75/fmriprep/workflows/bold/base.py#L517-L518

For ME-EPI data, however, we pass the whole 4D optimal combination time series:

https://github.com/poldracklab/fmriprep/blob/c717c6b216886be5de75627c067018700f0efd75/fmriprep/workflows/bold/base.py#L529-L530

We should patch this by passing the optimal combination to a `bold_splitter` node, as we do for the `bold_std_trans_wf` here:

https://github.com/poldracklab/fmriprep/blob/c717c6b216886be5de75627c067018700f0efd75/fmriprep/workflows/bold/base.py#L670-L677

Happy to contribute a patch if folks agrees with this !

**Comment by effigies** [comment]
That seems correct. I think we may also want to review the HMC transforms that are getting passed to the different resampling workflows. From a quick overview, it looks like we pass them in unconditionally, as if the workflows know not to HMC multi-echo data, but I don't see evidence of that in the resampling workflows.

**Comment by emdupre** [comment]
>  I think we may also want to review the HMC transforms that are getting passed to the different resampling workflows. 

Yes, absolutely ! @tsalo and I discussed the best way forward for that briefly, with proposals in https://github.com/poldracklab/fmriprep/issues/2236#issuecomment-672162176.

For now, I can issue a quick-fix to patch this.

**Comment by effigies** [comment]
Ah, sorry. I've been meaning to read that issue thoroughly...
