### ISSUE TITLE
Write out "sanity" derivatives / introspection mode

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#2245]
In trying to extract the signal for each of the CompCor ROIs to then check their correlation with the global signal (as @rciric suggested in order to finalize #2130) I have realized that I will need to keep the working directory somewhere and then manually select the ROI masks.

I propose to add a new ``--introspect-mode`` flag that runs the workflow in some sort of "debug mode" and writes out to the derivatives folder additional information such as the compcor masks.

In addition, and independently of the ``--introspect-mode``, we could also internally keep some "sanity features", such as the timeseries from CompCor ROIs and use those to make decisions (i.e., very much like the fallback for bold-t1 registration). When in ``--introspect-mode``, these signals/features would be written out to the derivatives folder.

WDYT? @effigies @mgxd 

Note: this is also related in a way to @satra's longstanding request for more quantitative quality metrics, he referred to freesurfers when proposed, but I think it goes to the same point.

**Comment by oesteban** [comment]
@rciric, do you think there would be some value in adding the correlation of the signals from CompCor ROIs in the bar plot you created?
![Screen Shot 2020-08-28 at 4 23 32 PM](https://user-images.githubusercontent.com/598470/91578879-13aac880-e94b-11ea-82bf-1827a580ae24.png)

(also, what about removing the compcor components completely? - if we add the time series, see #1746)

**Comment by effigies** [comment]
As opposed to `--introspect-mode`, we can think about repurposing the `--debug` flag, which I believe is still just warning people that it does nothing. `--debug compcor` (or `--debug masks`) could output CompCor masks. Other useful things to output could be given their own names as we encounter them, and we could have a `--debug all` to just enable all debug outputs.

**Comment by effigies** [comment]
If this can be put into a bug-fix release, then it should not hold up the LTS.

**Comment by oesteban** [comment]
Agree. The only thing I wish we do have before the LTS is the correlation. If @rciric confirms that it'd be useful to add them to the confounds plot (and remove the components), we can have the best of both

**Comment by satra** [comment]
here is one more sanity metric: "correlation of mean roi timeseries in native and normalized space"
