### ISSUE TITLE
Drop CI docs build?

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#2246]
The original purpose of the CI docs build was to ensure that ReadTheDocs would be able to build. I've enabled ReadTheDocs PR builds.

Okay to remove the Circle CI jobs? Or is there a good reason to keep them?

**Comment by oesteban** [comment]
I guess that's fine. 👍

**Comment by mgxd** [comment]
Offloading whatever we can from Circle is fine by me
