### ISSUE TITLE
New fMRIPrep Release?

### ISSUE THREAD

**Issue by BrigiMala** [poldracklab/fmriprep#2249]
Dear devs,

We are planning to use fMRIPrep to preprocess a large data set. 
Before we start, I was just wondering if there is going to be a new version of fMRIPrep coming out soon?

**Comment by effigies** [comment]
Yes, we're hoping to finalize a new release in the very near future.

**Comment by oesteban** [comment]
> preprocess a large data set

As Chris mentioned, we are hoping to release very soon - and it will be [an LTS release](https://www.nipreps.org/devs/releases/#long-term-support-series)!
