### ISSUE TITLE
Revise memory constraints throughout workflow, add missing

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#225]
...for bottleneck nodes that are expected to use a lot of memory (see #223)

**Comment by oesteban** [comment]
I take this one. And make it broader, I'll do a full code-review.

**Comment by oesteban** [comment]
Please check out https://github.com/poldracklab/fmriprep/pull/629#issuecomment-319528238

We should probably set the memory limits to all nodes.
