### ISSUE TITLE
Path does not exist

### ISSUE THREAD

**Issue by alienx-zero** [poldracklab/fmriprep#2257]
Hi, I am new to start fmriprep and also first time using docker. Anyone could tell me what is the problem. I think the path is right...
C:\Users\99488>docker run poldracklab/fmriprep E:\OPT\research\fMRI\2475376 E:\OPT\research\fMRI\output {participant} --participant-label 2475376 --fs-license-file E:\OPT\research\fMRI\license.txt
You are using fMRIPrep-20.1.1, and a newer version of fMRIPrep is available: 20.1.2.
Please check out our documentation about how and when to upgrade:
https://fmriprep.readthedocs.io/en/latest/faq.html#upgrading
usage: fmriprep [-h] [--version] [--skip_bids_validation]
                [--participant-label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]]
                [-t TASK_ID] [--echo-idx ECHO_IDX] [--bids-filter-file FILE]
                [--anat-derivatives PATH] [--nprocs NPROCS]
                [--omp-nthreads OMP_NTHREADS] [--mem MEMORY_GB] [--low-mem]
                [--use-plugin FILE] [--anat-only] [--boilerplate_only]
                [--md-only-boilerplate] [--error-on-aroma-warnings] [-v]
                [--ignore {fieldmaps,slicetiming,sbref} [{fieldmaps,slicetiming,sbref} ...]]
                [--longitudinal]
                [--output-spaces [OUTPUT_SPACES [OUTPUT_SPACES ...]]]
                [--bold2t1w-init {register,header}] [--bold2t1w-dof {6,9,12}]
                [--force-bbr] [--force-no-bbr] [--medial-surface-nan]
                [--dummy-scans DUMMY_SCANS] [--random-seed RANDOM_SEED]
                [--use-aroma]
                [--aroma-melodic-dimensionality AROMA_MELODIC_DIM]
                [--return-all-components]
                [--fd-spike-threshold REGRESSORS_FD_TH]
                [--dvars-spike-threshold REGRESSORS_DVARS_TH]
                [--skull-strip-template SKULL_STRIP_TEMPLATE]
                [--skull-strip-fixed-seed]
                [--skull-strip-t1w {auto,skip,force}] [--fmap-bspline]
                [--fmap-no-demean] [--use-syn-sdc] [--force-syn]
                [--fs-license-file FILE] [--fs-subjects-dir PATH]
                [--no-submm-recon] [--cifti-output [{91k,170k}] |
                --fs-no-reconall] [-w WORK_DIR] [--clean-workdir]
                [--resource-monitor] [--reports-only] [--run-uuid RUN_UUID]
                [--write-graph] [--stop-on-first-crash] [--notrack] [--sloppy]
                bids_dir output_dir {participant}
fmriprep: error: Path does not exist: <E:\OPT\research\fMRI\2475376>.

**Comment by alienx-zero** [comment]
![1599256856(1)](https://user-images.githubusercontent.com/55502834/92287725-9a761d00-eed8-11ea-890b-c303b25903e3.png)

**Comment by alienx-zero** [comment]
![image](https://user-images.githubusercontent.com/55502834/92290888-ea0e1600-eee3-11ea-948b-373376387515.png)
Sorry, it still does not work with -v. And I have read the linkage before openning this issue. And I also read http://reproducibility.stanford.edu/fmriprep-tutorial-running-the-docker-image/. But, all the command line are based on linux. I am using win10.

**Comment by effigies** [comment]
To be clear, it looks like what you want is:

```
fmriprep-docker E:\OPT\research\fMRI\2475376 E:\OPT\research\fMRI\output participant --participnat-label 2475376 --fs-license-file E:\OPT\research\fMRI\license.txt
```

You will almost certainly want to add a `-w` argument to use a work directory outside the container.

**Comment by alienx-zero** [comment]
![1599266160(1)](https://user-images.githubusercontent.com/55502834/92293010-41b17f00-eeee-11ea-8027-7ffa3a67cf10.png)
Sorry, I try either -v or -w, the license.txt path could not be recognized

**Comment by effigies** [comment]
Is the fmriprep-docker command not working for you? It was written to help avoid spending a lot of time debugging docker invocations. I see there was something that got at least to the validation stage above...

**Comment by alienx-zero** [comment]
validation stage error is that after I remove the line --fs-license-file E:\OPT\research\fMRI\license.txt, it would report such error~
If I direclty run fmriprep-docker(F-D) in cmd, theywill say that F-D is not recognized as command as following:

C:\Users\99488>fmriprep-docker -w E:\OPT\research\fMRI\2475376 -w E:\OPT\research\fMRI\output participant --participnat-label 2475376 --fs-license-file E:\OPT\research\fMRI\license.txt
'fmriprep-docker' is not recognized as an internal or external command,
operable program or batch file.

Should I add some file paths into enviroment variables? I do not know whether it work for docker

**Comment by alienx-zero** [comment]
If I run it by docker run poldracklab/fmriprep instead of run --rm -it, it will report other error... 
C:\Users\99488>docker run poldracklab/fmriprep -w E:\OPT\research\fMRI\2475376 -w E:\OPT\research\fMRI\output participant --participnat-label 2475376 --fs-license-file E:\OPT\research\fMRI\license.txt
You are using fMRIPrep-20.1.1, and a newer version of fMRIPrep is available: 20.1.2.
Please check out our documentation about how and when to upgrade:
https://fmriprep.readthedocs.io/en/latest/faq.html#upgrading
usage: fmriprep [-h] [--version] [--skip_bids_validation]
                [--participant-label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]]
                [-t TASK_ID] [--echo-idx ECHO_IDX] [--bids-filter-file FILE]
                [--anat-derivatives PATH] [--nprocs NPROCS]
                [--omp-nthreads OMP_NTHREADS] [--mem MEMORY_GB] [--low-mem]
                [--use-plugin FILE] [--anat-only] [--boilerplate_only]
                [--md-only-boilerplate] [--error-on-aroma-warnings] [-v]
                [--ignore {fieldmaps,slicetiming,sbref} [{fieldmaps,slicetiming,sbref} ...]]
                [--longitudinal]
                [--output-spaces [OUTPUT_SPACES [OUTPUT_SPACES ...]]]
                [--bold2t1w-init {register,header}] [--bold2t1w-dof {6,9,12}]
                [--force-bbr] [--force-no-bbr] [--medial-surface-nan]
                [--dummy-scans DUMMY_SCANS] [--random-seed RANDOM_SEED]
                [--use-aroma]
                [--aroma-melodic-dimensionality AROMA_MELODIC_DIM]
                [--return-all-components]
                [--fd-spike-threshold REGRESSORS_FD_TH]
                [--dvars-spike-threshold REGRESSORS_DVARS_TH]
                [--skull-strip-template SKULL_STRIP_TEMPLATE]
                [--skull-strip-fixed-seed]
                [--skull-strip-t1w {auto,skip,force}] [--fmap-bspline]
                [--fmap-no-demean] [--use-syn-sdc] [--force-syn]
                [--fs-license-file FILE] [--fs-subjects-dir PATH]
                [--no-submm-recon] [--cifti-output [{91k,170k}] |
                --fs-no-reconall] [-w WORK_DIR] [--clean-workdir]
                [--resource-monitor] [--reports-only] [--run-uuid RUN_UUID]
                [--write-graph] [--stop-on-first-crash] [--notrack] [--sloppy]
                bids_dir output_dir {participant}
fmriprep: error: Path does not exist: <participant>.

**Comment by alienx-zero** [comment]
Sorry, I miss the next word on last commnet.
fmriprep: error: Path does not exist: <participant>.

**Comment by alienx-zero** [comment]
Sorry, the text miss the next word on last commnet. I show it in this figure
![1599269199(1)](https://user-images.githubusercontent.com/55502834/92293938-56454580-eef5-11ea-8bc4-31b2e4d1df63.png)
.

**Comment by effigies** [comment]
Do you have Python installed? If so, `python -m pip install fmriprep-docker`.

The issue is that you need to mount any paths, and all Docker options go before the image.

`docker run -v E:\OPT\research\fMRI\2475376:/data -v E:\OPT\research\fMRI\output:/out -v E:\OPT\research\fMRI\license.txt:/opt/freesurfer/license.txt poldracklab/fmriprep:latest /data /out participant --participant-label 2475376`

**Comment by alienx-zero** [comment]
omg, it is fixed~ Thx very much. Like u

**Comment by alienx-zero** [comment]
Sorry to take your time again... Here is a new problem..
![1599271631(1)](https://user-images.githubusercontent.com/55502834/92294858-fea9d880-eefa-11ea-8b95-6b959d1efd11.png)
And the data structure is shown as following:
![image](https://user-images.githubusercontent.com/55502834/92295098-387adf00-eefb-11ea-8017-bea48674bf40.png)
These data are dowloaded from http://fcon_1000.projects.nitrc.org/indi/pro/eNKI_RS_TRT/NKI_Rockland_nifti_dl.html shown in the tutorials. Is it completed? Or lack the labels info

**Comment by effigies** [comment]
That's not a [BIDS](https://bids.neuroimaging.io/) dataset, so fMRIPrep won't know what to do with it. You will either need to reorganize it into BIDS or find someone who has already done that. I might check on [Neurostars](https://neurostars.org/).

**Comment by alienx-zero** [comment]
Get~Thanks for your patient explanation~

**Comment by ZhyGao** [comment]
> Do you have Python installed? If so, `python -m pip install fmriprep-docker`.
> 
> The issue is that you need to mount any paths, and all Docker options go before the image.
> 
> `docker run -v E:\OPT\research\fMRI\2475376:/data -v E:\OPT\research\fMRI\output:/out -v E:\OPT\research\fMRI\license.txt:/opt/freesurfer/license.txt poldracklab/fmriprep:latest /data /out participant --participant-label 2475376`

I have the same question but I don't know why. Can you help me?

docker run -v /home/gzy/tvb-collab-master/input:/data -v /home/gzy/tvb-collab-master/output:/out -v /data/freesurfer/license.txt:/opt/freesurfer/license.txt  nipreps/fmriprep:latest /data /out participant --participant-label CON03

there's an error ERROR: a valid license file is required for FreeSurfer to run. fMRIPrep looked for an existing license file at several paths, in this order: 1) command line argument ``--fs-license-file``; 2) ``$FS_LICENSE`` environment variable; and 3) the ``$FREESURFER_HOME/license.txt`` path. Get it (for free) by registering at https://surfer.nmr.mgh.harvard.edu/registration.html
Thanks for your reply
