### ISSUE TITLE
--ignore t2w/flair options missing

### ISSUE THREAD

**Issue by fliem** [poldracklab/fmriprep#2259]
It seems that the changes in #2015 got lost in refactoring. 
Ignoring t2w and flair is implemented in [fmriprep/workflows/base.py](https://github.com/poldracklab/fmriprep/blob/637fc1f6c2d9ddc615cbd539469aed7d819fb897/fmriprep/workflows/base.py#L135) but the options are missing from [fmriprep/cli/parser.py](https://github.com/poldracklab/fmriprep/blob/637fc1f6c2d9ddc615cbd539469aed7d819fb897/fmriprep/cli/parser.py#L245) and are not documented on the website

**Comment by effigies** [comment]
Good catch. Care to give #2260 a review?
