### ISSUE TITLE
Correlations among regressors plots have no clear ordering

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#2277]
### What version of fMRIPrep are you using?

20.2.0rc0

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?

TACC run

### Did fMRIPrep generate the visual report for this particular subject? If yes, could you share it?

<img width="1792" alt="Screen Shot 2020-09-23 at 13 15 40" src="https://user-images.githubusercontent.com/83442/94046623-f11b9c00-fd9e-11ea-87a4-5a93d633b820.png">

**Comment by oesteban** [comment]
Duplicate (or part of): nipreps/niworkflows#564

**Comment by effigies** [comment]
Closing, then.
