### ISSUE TITLE
Tracking issue for OpenNeuro sample run review

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#2278]
* [ ] default
  * [x] ds000001_sample
    * [x] sub-10
    * [x] sub-11
    * [x] sub-13
    * [x] sub-16
  * [x] ds000157_sample
    * [x] sub-06
    * [x] sub-10
    * [x] sub-12
    * [x] sub-30
  * [x] ds000172_sample
    * [x] sub-control03
    * [x] sub-control04
    * [x] sub-control05
    * [x] sub-control09
  * [x] ds000203_sample
    * [x] sub-16
    * [x] sub-17
    * [x] sub-19
    * [x] sub-20
  * [x] ds000218_sample
    * [x] sub-05
    * [x] sub-13
    * [x] sub-19
    * [x] sub-20
  * [x] ds000219_sample
    * [x] sub-04
    * [x] sub-19
    * [x] sub-20
    * [x] sub-22
  * [x] ds000224_sample
    * [x] sub-MSC02
    * [x] sub-MSC03
    * [x] sub-MSC05
    * [x] sub-MSC06
  * [x] ds000229_sample
    * [x] sub-04
    * [x] sub-07
    * [x] sub-10
    * [x] sub-12
  * [x] ds000231_sample
    * [x] sub-01
    * [x] sub-04
    * [x] sub-05
    * [x] sub-08
  * [x] ds000233_sample
    * [x] sub-rid000012
    * [x] sub-rid000033
    * [x] sub-rid000036
    * [x] sub-rid000037
  * [x] ds000256_sample
    * [x] sub-CTS201
    * [x] sub-CTS213
    * [x] sub-CTS238
    * [x] sub-CTS241
  * [x] ds001019_sample
    * [x] sub-04
    * [x] sub-17
    * [x] sub-23
    * [x] sub-24
  * [x] ds001021_sample
    * [x] sub-A00008326
  * [ ] ds001105_sample
    * [ ] sub-004
    * [ ] sub-006
    * [ ] sub-011
    * [ ] sub-028
  * [x] ds001219_sample
    * [x] sub-05
    * [x] sub-15
    * [x] sub-19
    * [x] sub-20
  * [x] ds001226_sample
    * [x] sub-CON10
    * [x] sub-PAT02
    * [x] sub-PAT05
    * [ ] sub-PAT23
  * [x] ds001242_sample
    * [x] sub-07
    * [x] sub-26
    * [x] sub-32
    * [x] sub-45
  * [x] ds001357_sample
    * [x] sub-003
    * [x] sub-008
    * [x] sub-011
    * [x] sub-016
  * [x] ds001399_sample
    * [x] sub-MOCCAG001
    * [x] sub-MOCCAG002
    * [x] sub-MOCCAG003
  * [x] ds001408_sample
    * [x] sub-NF06
    * [x] sub-NF16
    * [x] sub-control11
    * [x] sub-control18
  * [x] ds001419_sample
    * [x] sub-01
  * [x] ds001439_sample
    * [x] sub-06
    * [x] sub-11
    * [x] sub-13
    * [x] sub-17
  * [x] ds001634_sample
    * [x] sub-01
    * [x] sub-03
    * [x] sub-17
    * [x] sub-18
  * [x] ds001635_sample
    * [x] sub-04
    * [x] sub-06
    * [x] sub-07
    * [x] sub-09
  * [x] ds001722_sample
    * [x] sub-02
    * [x] sub-03
    * [x] sub-11
    * [x] sub-13
  * [ ] ds001761_sample
    * [ ] sub-01
    * [ ] sub-02
    * [ ] sub-03
    * [ ] sub-04
  * [ ] ds001818_sample
    * [ ] sub-012
    * [ ] sub-018
    * [ ] sub-036
    * [ ] sub-049
  * [ ] ds001840_sample
    * [ ] sub-08
    * [ ] sub-15
    * [ ] sub-24
    * [ ] sub-31
  * [ ] ds001927_sample
    * [ ] sub-s005
    * [ ] sub-s012
    * [ ] sub-s017
    * [ ] sub-s023
  * [ ] ds002013_sample
    * [ ] sub-AAA02
    * [ ] sub-AAA03
    * [ ] sub-AAX01
    * [ ] sub-AAX02
  * [ ] ds002033_sample
    * [ ] sub-15
    * [ ] sub-17
    * [ ] sub-22
    * [ ] sub-41
* [ ] fs-no-reconall
  * [x] ds000001_sample
    * [x] sub-04
    * [x] sub-06
    * [x] sub-12
    * [x] sub-13
  * [x] ds000172_sample
    * [x] sub-control03
    * [x] sub-control04
    * [x] sub-control05
    * [x] sub-control09
  * [ ] ds000203_sample
    * [ ] sub-10
    * [ ] sub-12
    * [ ] sub-13
    * [ ] sub-17
  * [ ] ds000218_sample
    * [ ] sub-02
    * [ ] sub-04
    * [ ] sub-10
    * [ ] sub-21
  * [ ] ds000219_sample
    * [ ] sub-01
    * [ ] sub-08
    * [ ] sub-15
    * [ ] sub-20
  * [ ] ds000229_sample
    * [ ] sub-01
    * [ ] sub-02
    * [ ] sub-03
    * [ ] sub-15
  * [ ] ds000231_sample
    * [ ] sub-05
    * [ ] sub-06
    * [ ] sub-07
    * [ ] sub-09
  * [ ] ds000233_sample
    * [ ] sub-rid000001
    * [ ] sub-rid000027
    * [ ] sub-rid000036
    * [ ] sub-rid000041
  * [ ] ds001299_sample
    * [ ] sub-02004
    * [ ] sub-02007
    * [ ] sub-02010
    * [ ] sub-02017
  * [ ] ds001302_sample
    * [ ] sub-06
    * [ ] sub-07
    * [ ] sub-10
    * [ ] sub-14
  * [ ] ds001510_sample
    * [ ] sub-09
    * [ ] sub-18
    * [ ] sub-21
    * [ ] sub-30
  * [ ] ds001511_sample
    * [ ] sub-sid000001
    * [ ] sub-sid000004
    * [ ] sub-sid000009
    * [ ] sub-sid000012
  * [ ] ds001534_sample
    * [ ] sub-07
    * [ ] sub-14
    * [ ] sub-26
    * [ ] sub-31
  * [ ] ds001634_sample
    * [ ] sub-08
    * [ ] sub-11
    * [ ] sub-13
    * [ ] sub-17
  * [ ] ds001635_sample
    * [ ] sub-06
    * [ ] sub-08
    * [ ] sub-10
    * [ ] sub-12
  * [ ] ds001722_sample
    * [ ] sub-01
    * [ ] sub-09
    * [ ] sub-15
    * [ ] sub-16
  * [ ] ds001907_sample
    * [ ] sub-RC4107
    * [ ] sub-RC4119
    * [ ] sub-RC4120
    * [ ] sub-RC4130
  * [ ] ds002006_sample
    * [ ] sub-03
    * [ ] sub-19
    * [ ] sub-23
    * [ ] sub-29
  * [ ] ds002306_sample
    * [ ] sub-01
    * [ ] sub-03
    * [ ] sub-04
    * [ ] sub-06

**Comment by oesteban** [comment]
Something weird that I don't know how to interpret (I believe this is a problem of the original x-form headers):

ds001439/sub-17
<img width="1268" alt="Screen Shot 2020-09-24 at 5 08 02 PM" src="https://user-images.githubusercontent.com/598470/94163900-abd39900-fe88-11ea-9b5a-793cb3af29d7.png">

**Comment by effigies** [comment]
If I'm understanding, you're wondering why it's pitched ~45deg back instead of forward? I suspect it's just that it's so close to the 45degree mark that calling the axis anterior or inferior was a coin flip on the scanner.

**Comment by oesteban** [comment]
> If I'm understanding, you're wondering why it's pitched ~45deg back instead of forward? I suspect it's just that it's so close to the 45degree mark that calling the axis anterior or inferior was a coin flip on the scanner.

You refer to the inclination of the head w.r.t. the prescribed bounding-box? I think there is really an axis swap on the header because if you look at the distortion it seems to go up-down/superior-inferior (which is technically not possible in humans on a closed bore).

**Comment by effigies** [comment]
Sorry, the problem isn't clear to me.
