### ISSUE TITLE
Catch nipype RuntimeError Exceptions

### ISSUE THREAD

**Issue by rwblair** [poldracklab/fmriprep#23]
In run_workflow.py might be able to output a more meaningful error/set of information rather than "check log for details"

**Comment by oesteban** [comment]
We could talk briefly about this very soon with @chrisfilo . I'm having somewhat similar issues in mriqc, and we should understand all that nipype can do for us in this matter. Possible more than we expect, so lets see this next Monday/Tuesday.

**Comment by shoshber** [comment]
Did you meet/come up with any thoughts on this?

**Comment by chrisfilo** [comment]
Closing in favour of #66
