### ISSUE TITLE
Use output log out/log/run_workflow

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#240]
We are writing a small log in ```out/log/run_workflow```.

Currently, the content of that file after running is just a list of subjects processed.

I would love to have a file like that with all the output from processing (preferably with .txt extension so that it is convenient to open with the browser from, i.e. circle's artifacts).

**Comment by shoshber** [comment]
We should log an explicit INFO log of which workflow is being run (ds005 or ds054).
