### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#246]
- [x] Landing page describing the goals of the project
- [x] How to install and run the pipeline (pip, docker, singularity)
   - [x] Installation
   - [x] Usage
   - [x] More detail on command-line args
- [x] Describe the all of the steps in the two workflows (also implement #111)
   - [x] ds005
   - [x] implement #111
- [x] Provide examples of reports generated by the pipeline (use full resolution data)
- [x] Describe the meaning of all outputs produced by the pipelines
   - [x] derivatives
   - [x] log
   - [x] images

**Comment by shoshber** [comment]
re: "Landing page describing the goals of the project". We already have a README.rst which contains that information. Can you describe what, if anything, needs to be changed?

**Comment by chrisfilo** [comment]
The content of the README file is fine, but if we are to move to a platform such as Read The Docs (using github might be too limited) we have to make sure it is displayed as the landing page.

**Comment by shoshber** [comment]
Like this? http://fmriprep.readthedocs.io/.

**Comment by chrisfilo** [comment]
Yes. We need to update the link in the README.md.

As for the description of the workflows please stick to ds005 since ds054 is still in flux. Try to keep it high level (for example "removal of the skull and other non-brain tissues using ANTs" rather than "running ants --default-value 0 ...").
