### ISSUE TITLE
`latest` tag on dockerhub should be stable release

### ISSUE THREAD

**Issue by shoshber** [poldracklab/fmriprep#250]
preferably with a tag like "stable" or something

**Comment by chrisfilo** [comment]
What's wrong with the current tag"latest" https://hub.docker.com/r/poldracklab/fmriprep/tags/ ? It's the usual convention in Docker.

**Comment by rwblair** [comment]
latest and stable can have two different meanings like in debian releases. Latest is working, not bleeding edge, but will still have errors. Stable will mean we know this release to be as good or better than any we have put out before.

**Comment by chrisfilo** [comment]
I see. I would recommend turning off the rolling release then and only push
to docker hub upon new release/tag. latest will equal to stable then.
Frankly speaking I don't think the rolling docker release was too helpful
during this sprint.

**Comment by shoshber** [comment]
Changed the title
