### ISSUE TITLE
BET skulls tripping cuts into the cerebellum

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#252]
![image](https://cloud.githubusercontent.com/assets/238759/20999641/ea4e37e8-bcca-11e6-8894-4f86ebfb1cae.png)

We should investigate BET parameters or other skull stripping options.

**Comment by chrisfilo** [comment]
It also sometimes cut too deeply in the prefrontal cortex:
![image](https://cloud.githubusercontent.com/assets/238759/20999698/5c8e211a-bccb-11e6-83a3-ad2ebe7220e4.png)

**Comment by chrisfilo** [comment]
Another problematic case:
![image](https://cloud.githubusercontent.com/assets/238759/21000107/c7b03fda-bccd-11e6-82a1-0dace34c1915.png)

**Comment by chrisfilo** [comment]
![image](https://cloud.githubusercontent.com/assets/238759/21000850/d8729472-bcd1-11e6-9cf1-b9da7a7c7a11.png)

**Comment by chrisfilo** [comment]
Here's a bad case (prefrontal cortex) despite small distortions:
![image](https://cloud.githubusercontent.com/assets/238759/21002341/179bc5e4-bcda-11e6-92cb-47d263ea00be.png)

**Comment by oesteban** [comment]
We can play around the ```frac``` value.
