### ISSUE TITLE
EPI T1 coregistration errors in ds005

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#258]
![image](https://cloud.githubusercontent.com/assets/238759/21040972/12bd430e-bd9d-11e6-9c07-553e9b2824fb.png)
Probably widening the search parameters of the initial search will solve the issue. This dataset is known for having weird built in affines.

**Comment by chrisfilo** [comment]
Before we get into modifying FMRIPREP @suyashdb could you make sure that ds000005 R2.0.1 has the correct files? I know that @AlexBowring was contributing files with corrected affines. Maybe something went wrong with the update.

**Comment by shoshber** [comment]
Maybe we should double-check that the overlay and the base images are displaying the same slices

**Comment by rwblair** [comment]
Appears to be resolved when running ds000005_R2.0.1 through current version of fmriprep:

<img width="1349" alt="screen shot 2017-02-23 at 3 45 50 pm" src="https://cloud.githubusercontent.com/assets/14927911/23284278/7b539da4-f9df-11e6-997c-d5d7b9995e95.png">
