### ISSUE TITLE
GM/WM outline is yellow instead of red for some ds005 subjects

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#259]
![image](https://cloud.githubusercontent.com/assets/238759/21041115/e1e70b88-bd9d-11e6-899d-6f3a41bd8c46.png)
Definitely a minor issue. Mysterious non-the-less

**Comment by chrisfilo** [comment]
Another example note that the middle row has a different color than the rest:
![image](https://cloud.githubusercontent.com/assets/238759/21414362/b9ed84ac-c7cc-11e6-8ea9-c7c0c525b259.png)

**Comment by oesteban** [comment]
This issue should be in niworkflows :)

**Comment by chrisfilo** [comment]
It might be an intersection between the two packages - we need to make sure
the mask fed to the interface is correct.
