### ISSUE TITLE
T1 -> MNI normalization failure

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#266]
![image](https://cloud.githubusercontent.com/assets/238759/21077049/3b74648e-bef2-11e6-8145-276ac1f0090d.png)

That's subject 100003 from ds054

**Comment by oesteban** [comment]
How did BrainExtraction go?

**Comment by chrisfilo** [comment]
No issues:
![image](https://cloud.githubusercontent.com/assets/238759/21082242/617423a0-bf8c-11e6-9ecb-a22b1a5acc0b.png)

**Comment by oesteban** [comment]
Nice! Looks like a plausible intermediate step

**Comment by oesteban** [comment]
Where to check this worked:
- ds102, sub-26
- ds107, sub-45. In ds107 there are other cases which can use an improvement of normalization: 24, 38, 44, 46.
- ds109, sub-[07, 11, 30, 38, 46]. Also sub-48 could improve.
