### ISSUE TITLE
MCFLIRT is introducing slow frequency confound

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#267]
![image](https://cloud.githubusercontent.com/assets/238759/21079197/afde9fb4-bf3e-11e6-9f5c-a82065340488.png)

https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/MCFLIRT
> As part of the initial 8mm search, an identity transformation is assumed between the middle volume and the adjacent volume. The transformation found in this first search is then used as the estimate for the transformation between the middle volume and the volume beyond the adjacent one. This scheme should lead to much faster optimization and greater accuracy for the majority of studies where subject motion is minimal. In the pathalogical cases, this scheme does not penalise the quality of the final correction. 
> 
> If mean registration is used, the curent motion correction parameters are applied to the time-series, the volumes are averaged to create a new template image and the same 3-stage correction is carried out using this new mean image as a template.

**Comment by chrisfilo** [comment]
MCFLIRT also induces some weird interpolation artefacts:

1a) raw before motion spike
![2016-12-11 09_02_27-sub-100003_task-machinega 168 of 216](https://cloud.githubusercontent.com/assets/238759/21081772/512142bc-bf82-11e6-91e9-862117d645be.png)
1b) raw data after motion spike
![2016-12-11 09_12_25-sub-100003_task-machinega 178 of 216](https://cloud.githubusercontent.com/assets/238759/21081776/677758b2-bf82-11e6-8107-cb48a7ed7730.png)
2a) realigned data before motion spike (interpolation applied by MCFLIRT)
![2016-12-11 09_01_39-sub-100003_task-machinega 168 of 216](https://cloud.githubusercontent.com/assets/238759/21081783/9fb1028c-bf82-11e6-9267-18f3f59bda43.png)
2b) realigned data after motion spike (interpolation applied by MCFLIRT)
![2016-12-11 09_12_48-sub-100003_task-machinega 178 of 216](https://cloud.githubusercontent.com/assets/238759/21081784/b63a21c8-bf82-11e6-822a-9bb221dfccaa.png)

This is sub 100003 from ds054 run 1 (it's easier to spot it in a movie). CompCor is picking up on those as well.

**Comment by chrisfilo** [comment]
Switching to ants might be a solution: http://stnava.github.io/fMRIANTs/

**Comment by oesteban** [comment]
+1 to ants. Additionally, transforms will be compatible across the pipeline

**Comment by chrisfilo** [comment]
For completeness: this slow trend has been reported in DVARS in MRIQC https://github.com/poldracklab/mriqc/issues/221

**Comment by chrisfilo** [comment]
One challenge of switching to ANTs would be to calculate FD. There is some code here: https://github.com/stnava/ANTsR/blob/master/R/preprocessfMRI.R#L78 but I would be very careful when porting.

**Comment by oesteban** [comment]
What about using c3d to convert matrices to FSL?

**Comment by chrisfilo** [comment]
Not the most clean solution, but it would be easy to verify correctness and
we can reuse FD calculation code we already have.

**Comment by chrisfilo** [comment]
https://github.com/poldracklab/mriqc/issues/221

**Comment by chrisfilo** [comment]
I thought about this a little more and I am less confident this confound comes from the way we calculate DVARS (although we should still review and revise it for other reasons). This is why:
- the binomial trend was picked up by PCA run in CompCorr - independently of DVARS calculation
- when we used the same DVARS calculation code on data before motion correction (this is what we switched to in mriqc) we don't see the binomial trend

**Comment by rwblair** [comment]
Gotcha. I'll go ahead and try afni motion correction and see if we similar things.

**Comment by chrisfilo** [comment]
I did some more comparisons and this is what I found:
- The trend is visible even in manually calculated differentials (simple `np.diff`) - not only in DVARS traces from nipype codebase.
- The trend is not visible in data before applying MCFLIRT.
- The trend is not visible in data after applying AFNI 3dvolreg (with Fourier interpolation and twopass).
- DVARS values for data outputted by MCFLIRT are consistently smaller than for those outputted by AFNI.
- Tried one very still (little motion) subject from ABIDE and I could not find the same binomial trend as in beast data, but DVARS values were consistently lower than those produced by AFNI.

My current working theory is that this has something to do with interpolation and shows only in data with short TR and many samples (would be worth running a test on HCP data). Another thing I did not have time to test was the 

```
-u, --useFixedReferenceImage
          use a fixed reference image instead of the neighor in the time series.
```

**Comment by chrisfilo** [comment]
Latest discoveries:

- `-u` produces the same results (trend is still there)
- The trend is not visible in the volumes in the MNI space
![image](https://cloud.githubusercontent.com/assets/238759/23194101/09d8cfc0-f861-11e6-9784-e0755da085d5.png)
This suggests that this is an interpolation issue and we can get rid of it by splitting the input data and applying individual affine transforms and merging it again (same as we do for producing the MNI data, but this time only with the affine transform).
