### ISSUE TITLE
README in `derivatives` folder

### ISSUE THREAD

**Issue by shoshber** [poldracklab/fmriprep#268]
According to BIDS spec: http://bids.neuroimaging.io/bids_spec1.0.0-rc4.pdf

**Comment by rwblair** [comment]
A ​README​file should be found at the root of the “s​ourcedata”​or the “​derivatives”​folder (or both). This file should describe the nature of the raw data or the derived data. In the case of the existence of a “​derivatives”​folder, we recommend to include details about the software stack and settings used to generate the results. Non-imaging objects to improve reproducibility are encouraged (scripts, setting files, etc.).

Wonder what the best way of dumping all our software used and versions to a file should be? Maybe we should just have a link to the commit that is used on github.

**Comment by oesteban** [comment]
Superseded by latest BEP advances.
