### ISSUE TITLE
Slice timing correction

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#27]
- only when metadata are available
- consider using http://nipype.readthedocs.io/en/latest/interfaces/generated/nipype.interfaces.nipy.preprocess.html#spacetimerealigner (simultaneous realignment and slice time correction)

**Comment by oesteban** [comment]
Should this go before or after the fieldmap correction?

**Comment by chrisfilo** [comment]
I would say before.

**Comment by oesteban** [comment]
After our meeting, the slice timing correction will sit after fieldmap correction and before HMC.

**Comment by chrisfilo** [comment]
We should consider using 4dfmrirealign from nipy for simultaneous slice timing and motion correction.

**Comment by chrisfilo** [comment]
Relevant discussion about extracting motion parameters from 4dfmrirealign:
https://neurostars.org/t/spacetimerealigner-output-rotation-in-radians-or-degree/241

User call for adding slice time correction:
https://neurostars.org/t/fmriprep-smoothing-option/259

**Comment by chrisfilo** [comment]
Just heard from another user for whom lack of slice time correction is a deal breaker.

**Comment by chrisfilo** [comment]
Another alternative: https://github.com/dpark6060/FilterShift_C
