### ISSUE TITLE
Dockerfiles

### ISSUE THREAD

**Issue by shoshber** [poldracklab/fmriprep#273]
Perhaps
-> dependency Dockerfile with big binaries, to be cached

-> light weight Dockerfile to be rebuilt each time on circle

More transparent Dockerfiles with all versions and stuff (readable)

(from live conversation)

**Comment by oesteban** [comment]
Some of what we talked today was touched in #179

**Comment by shoshber** [comment]
Slack: On git+ requirements

they could be kept in a requirements.txt file and read from it in the Dockerfile - we should just avoid having them listed in multiple places

[2:49 PM]  
berleant +1 to having Dockerfile read requirements.txt

new messages
[2:53 PM]  
oesteban that's one of the paramount use cases of a requirements.txt file, so I'm also +1

**Comment by chrisfilo** [comment]
Nice breakdown of all the layers: https://microbadger.com/images/poldracklab/fmriprep

**Comment by shoshber** [comment]
That is amazing
