### ISSUE TITLE
[BUG] IntramodalMerge fails when input dimensions are not consistent

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#286]
This happens, for instance, with ds114/sub-02. The T1w images of the two sessions are merged, but it fails for a potential misorientation problem:

```
$ nib-ls /scratch/03843/crn_plab/fmriprep-ohbm-2/ds000114_R2.0.1/sub-02/ses-retest/anat/sub-02_ses-retest_T1w.nii.gz /scratch/03843/crn_plab/fmriprep-ohbm-2/ds000114_R2.0.1/sub-02/ses-test/anat/sub-02_ses-test_T1w.nii.gz 
/scratch/03843/crn_plab/fmriprep-ohbm-2/ds000114_R2.0.1/sub-02/ses-retest/anat/sub-02_ses-retest_T1w.nii.gz float32 [256, 156, 256] 1.00x1.30x1.00   sform
/scratch/03843/crn_plab/fmriprep-ohbm-2/ds000114_R2.0.1/sub-02/ses-test/anat/sub-02_ses-test_T1w.nii.gz     float32 [156, 256, 256] 1.30x1.00x1.00   sform
```

Solving this issue involves:
  - [ ] Checking that input dimensions are consistent
  - [ ] Checking that input orientations are correct and consistent.

WDYT @chrisfilo ?

/ref #285 - for the multiple T1w problem.

**Comment by chrisfilo** [comment]
ds114 is a longitudianl dataset with a separate T1w for each session. In such cases to avoid bias I would treat each session like a separate subject (don't combine T1ws across sessions, coregister EPIs to their respective T1ws).

**Comment by oesteban** [comment]
Ok, that behavior is definitely not implemented.

**Comment by chrisfilo** [comment]
Superseded by #310.
