### ISSUE TITLE
aCompCor white matter mask too conservative

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#290]
![image](https://cloud.githubusercontent.com/assets/238759/21413354/930de82a-c7c4-11e6-9c07-7a30808371b7.png)

segmentation was correct:

![image](https://cloud.githubusercontent.com/assets/238759/21413383/cf216daa-c7c4-11e6-8ccc-4ce50c713c53.png)

In this subject the WM outline on the BBR animation was yellow instead of red (see #259) I wonder if this is related.

**Comment by oesteban** [comment]
Was this fixed in #263? I don't think so, since the PR is posterior to this issue. However I think we are not having issues anymore with aCompCor, is that correct? @effigies .

**Comment by chrisfilo** [comment]
I don't think this was fixed - we should watch out for this when testing. One way to improve things is to use FreeSurfer segmentation.

**Comment by effigies** [comment]
I haven't looked at the aCompCor results with an eye toward anything except there not being obvious distortions. I don't think we generally see large swaths of white matter being outlined in red, if that's how those reports are supposed to look.
