### ISSUE TITLE
dtype conversion issue or corrupt image?

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#291]
![image](https://cloud.githubusercontent.com/assets/238759/21413837/487087a6-c7c8-11e6-8feb-17e88b8970b7.png)

@suyashdb could you validate that this run is not corrupted?

**Comment by suyashdb** [comment]
run doesn't seems to be corrupted. Attached is a gif of the run.
![ds116_sub-04_run02](https://cloud.githubusercontent.com/assets/11152799/21875477/39fe2864-d8a2-11e6-84e3-0cdfc95966de.gif)

**Comment by oesteban** [comment]
Do you think we can close this one @effigies ?

**Comment by effigies** [comment]
I was looking at this one. I don't think we've seen it lately, but I don't understand how it happened in the first place, so I'm not positive it was fixed. I'll check that subject out specifically when we run after this next release.

**Comment by oesteban** [comment]
I was fearing this. Let's leave it open, it'll will pop up when we run the
tests

**Comment by effigies** [comment]
Have a look at the MRIQC report for this BOLD series: https://s3.amazonaws.com/openneuro.outputs/8a9d3f8f8ef48d7eec95bcb4ae06b70c/d8c8ea1e-715a-4238-97b0-d1a94620d23c/reports/sub-04_task-auditoryoddballwithbuttonresponsetotargetstimuli_run-02_bold.html

**Comment by oesteban** [comment]
What kind of astronomical data is that run?

**Comment by effigies** [comment]
https://en.wikipedia.org/wiki/Globular_cluster

**Comment by oesteban** [comment]
Right. Looks to me like Messier 53 :D

**Comment by effigies** [comment]
@chrisfilo I looked at this data. There's a huge shift starting partway through volume 11 of `sub-04/func/sub-04_task-auditoryoddballwithbuttonresponsetotargetstimuli_run-02_bold.nii.gz`:

![ds116_snapshot](https://user-images.githubusercontent.com/83442/28805217-5a1f7c7e-7636-11e7-8497-27c92368bc55.png)

This looks pretty conclusively like a damaged file, not an FMRIPREP problem.

**Comment by chrisfilo** [comment]
@suyashdb could you create a new revision on openfmri and remove this file?

**Comment by suyashdb** [comment]
@effigies Can you share which dataset it is?

**Comment by chrisfilo** [comment]
It's ds000116
