### ISSUE TITLE
EPI -> T1 coregistration failure

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#292]
![image](https://cloud.githubusercontent.com/assets/238759/21414238/a5b796a4-c7cb-11e6-9a4c-439af099dffe.png)

![image](https://cloud.githubusercontent.com/assets/238759/21414265/d527f6ea-c7cb-11e6-8225-97a41e5ff852.png)

**Comment by oesteban** [comment]
I have the impression that the main problem here is initialization. I'll have a deeper look when I'm back after holidays.
