### ISSUE TITLE
Improve robustness of the aCompCor mask

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#296]
The mask used in aCompCor is derived from two tissue classes: white matter (WM) and corticospinal fluid (CSF). Currently implemented procedure works well on the Beast, but for other datasets sometimes provides very small masks (just a few voxels) which can lead to more noisy estimates and even crashes (see #276). The ideal procedure would:

- avoid contamination from gray matter voxels that could be caused by partial voluming, coregistration quality, and field distortions
- provide robust results for input data of different resolution, FOV, the size of ventricles and head size

**Comment by chrisfilo** [comment]
The key to making a CompCor mask in a robust fashion would be to restrict the range of the percentage of the whole brain volume to a prescribed ranged. This way we can ensure that the mask will not be too small nor too big independently of  the head size and/or resolution.

**Comment by oesteban** [comment]
Is this fixed? @chrisfilo

**Comment by oesteban** [comment]
Seems related to #290

**Comment by effigies** [comment]
I am not sure that this is still a problem. Do we have examples of datasets where it's too small?

* The only subject I've seen cited as bad is ds116/sub-01 (#290), which does not exhibit this problem in 0.6.0

**Comment by chrisfilo** [comment]
Thanks great to hear. Let's assume it's fixed until we see this again.
