### ISSUE TITLE
HTML reports can get big

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#306]
Some of the reports for the Beast can get as big as 30Mb. They also can take several seconds to fully render (especially the animations). The size and speed of rendering seem to be related. Smaller reports (from ds000102 for example) load faster.

I explored different ways to reduce the size of the reports:
- I've tried minification, but that only shaves a few kb of the size of the file (the bulk of the size is due to the base64 encoded images)
- I've tried gzipping which reduces the size by 50%, but is only supported when files are served by a server with appropriate header fields. Local files (with .html or .html.gz extensions) are not recognized correctly.
- I've looked at [MHTML](https://www.wikiwand.com/en/MHTML) briefly. It looks promising, but I did not see and obvious way to enable compression there. There is not that much software built around it. More research needs to be done.

**Comment by rwblair** [comment]
Might be possible to store gzipped SVGs in the file and then have javascript decompress them on page load. Would have the benefit that we could load the images one at a time instead of all the SVGs trying to animate at once.

**Comment by chrisfilo** [comment]
By far the biggest chunk of the SVG are the base64 encoded embedded bitmaps. We should explore options for taking those bitmaps, compressing them (possibly in lossless way, for example by limiting colorspace in black and white images) and sticking them back into the SVG. This could be implemented on the level of ReportCapableInterface object.

**Comment by chrisfilo** [comment]
The SVG themselves can be reduced in size using https://github.com/svg/svgo (this will not affect the base64 encoded bitmaps included in the SVGs).

**Comment by chrisfilo** [comment]
A couple of tools for optimizing PNGs:

- http://optipng.sourceforge.net/
- https://pngquant.org/

It's also worth considering WebP.
