### ISSUE TITLE
Support for multisession data with multiple T1s

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#310]
In case the dataset includes multiple sessions **and** each session includes at least one T1w image the pipeline should default to coregistering EPI to the T1w image from the corresponding session.

Alternatively an **unbiased** subject specific template (combination of all T1w images from a given subject) should be created and set as the coregistration target.

Currently the pipeline defaults to combining all T1w images (even across sessions) by coregistering all of them to the first T1 found. This is acceptable for combining multiple T1w images from a single session, but results in a bias towards the first T1w and thus is suboptimal in context of longitudinal studies.

Creating unbiased structural templates is necessary for both the volume as well as surface analysis. Former can be achieved using ANTs or AFNI - latter is supported by the FreeSurfer longitudinal stream.

**Comment by fliem** [comment]
I am planning to implement an [unbiased template approach](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3389460/).
Roughly this means:
- creating an unbiased template from the T1w images
- registering from template-T1w to MNI space
- within each session: registering from session-EPI to session-T1w, from session-T1w to template-T1, and combining with base-T1w-to-MNI-T1w-transformation

The template could be create with 
- the longitudinal freesurfer stream (e.g., [Tracula](https://surfer.nmr.mgh.harvard.edu/fswiki/Tracula) uses that for longitudinal registration of DWI data)
and/or
- ANTs

@chrisfilo and others: do you have experience with either of those approaches?

**Comment by chrisfilo** [comment]
This sounds good to me. I only have small amount of experience with
freesurfer longitudinal processing. Since there are more users in volume
based processing I would prefer at least starting with ants. Thanks!

**Comment by fliem** [comment]
I’m not 100 percent sure, but I think Tracula only uses volumes as templates and basing the fmri workflow on the dmri workflow probably would be straightforward.

As far as ATNs goes, it seems there is 
- [buildtemplateparallel.sh](https://github.com/stnava/ANTs/blob/master/Scripts/buildtemplateparallel.sh) which has a (legacy) [nipype interface](http://nipy.org/nipype/interfaces/generated/nipype.interfaces.ants.legacy.html#buildtemplateparallel) and
- more recently: [antsMultivariateTemplateConstruction2.sh](https://github.com/stnava/ANTs/blob/master/Scripts/antsMultivariateTemplateConstruction2.sh) which has no nipype interface

Also there are two nipype workflows
- [antsRegistrationBuildTemplate](http://nipype.readthedocs.io/en/latest/interfaces/generated/nipype.workflows.smri.ants.antsRegistrationBuildTemplate.html) and 
- [ANTSBuildTemplate](http://nipype.readthedocs.io/en/latest/interfaces/generated/nipype.workflows.smri.ants.ANTSBuildTemplate.html)

@chrisfilo: do you now an ANTs expert from the nipype community who could give recommendations regarding the different options? Thanks

**Comment by chrisfilo** [comment]
Yup - @hjmjohnson is the man!

**Comment by fliem** [comment]
Great.
Hi @hjmjohnson. Do you have any recommendations regarding which ANTs tool to use for unbiased template creation?
Thanks

**Comment by fliem** [comment]
Hi @jfrenchjr. Do you have any recommendations regarding using AFNI for building intra-subject templates (similarly to study-specific templates in #330)? Thanks.

**Comment by jfrenchjr** [comment]
Hello @fliem. Depending on your needs, the tools mentioned in #330 could work. [3dWarpDrive](https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dWarpDrive.html) may also be of use.

**Comment by oesteban** [comment]
Closed here https://github.com/poldracklab/fmriprep/pull/481#issuecomment-297136612

**Comment by effigies** [comment]
#481 did not close this. We don't use an unbiased template (see https://github.com/poldracklab/fmriprep/pull/481#issuecomment-297141567), yet.

**Comment by oesteban** [comment]
Oh, sorry!
