### ISSUE TITLE
[IDEA] Rename workflows

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#311]
The current workflow names (ds005 and ds054) have historical justification, but they confuse new users.

I propose new naming scheme:
`ds005` -> `basic`
`ds054` -> `basic_sbref_fmap`

This way we can add `basic_sbref` in the future (when there are sbrefs but fieldmaps are not available or should not be used). WDYT?

**Comment by mrahim** [comment]
Hi,
BTW what do the names of other workflows mean ? (HPC, spiral)

**Comment by chrisfilo** [comment]
Which other workflows are you referring to? Outside of fmriprep?

**Comment by mrahim** [comment]
I'm referring to these workflows when I type `fmriprep -h`

```
  -t {ds005,ds054,HPC,spiral}, --workflow-type {ds005,ds054,HPC,spiral}
                        workflow type, a monkeypatch while it is not 
                                                 automatically identified
```

**Comment by chrisfilo** [comment]
Oh I see. Those were removed (actually never implemented as workflows). `ds054` aka `basic_sbref_fmap` will support spiral and TOPUP fieldmaps.

**Comment by chrisfilo** [comment]
Alternatively, we can completely scrap the concept of multiple workflows and deal with this with flags. This way there would be "one" workflow that adapts to the data (this is what already happens when the `-t` option is not specified), but certain features could be disabled with flags. For example:

`--ignore_fieldmaps`

`--ignore_sbrefs`

If we chose this option we will have to go do a little documentation rewriting. Basically, we would describe workflows not based on their names, but based on the input data available. This might be more intuitive for users.

**Comment by oesteban** [comment]
I like that

**Comment by chrisfilo** [comment]
Or even better --ignore {sbref, fieldmaps}. by @oesteban
