### ISSUE TITLE
Idea: Simple wrapper script

### ISSUE THREAD

**Issue by shoshber** [poldracklab/fmriprep#316]
As proposed by @effigies

**Comment by effigies** [comment]
This was a big :+1: from at least two focus group participants. They were decidedly unexcited about the docker syntax, though, once explained, they liked the container concept.

**Comment by chrisfilo** [comment]
I'm yet to find someone excited about docker syntax :) We should think how can we make installation of this wrapper easy. Options:

1) `wget` from github
2) put it on pypi as a lightweight package `pip install fmripreprunner` or sth

**Comment by oesteban** [comment]
+1 to ```wget``` a github gist or similar
