### ISSUE TITLE
Solicit data where non-BBR registrations outperform BBR

### ISSUE THREAD

**Issue by rwblair** [poldracklab/fmriprep#333]
There was a question asker today who showed interest in other methods than BBR for EPI registration. If we can find data where BBR fails or under performs we can better tune our registration or include offer other types.

**Comment by oesteban** [comment]
Definitely worth tracking this person and see where BBR fails. I'm under the impression that, once we finish with #101 (adding FreeSurfer to the stack), we'll quickly adopt ```bbregister``` which is basically BBR with some improvements.

**Comment by oesteban** [comment]
Done with #694
