### ISSUE TITLE
[BUG] No error raised if no subjects found in the input directory

### ISSUE THREAD

**Issue by sz144** [poldracklab/fmriprep#348]
The terminal shows "/usr/local/miniconda/lib/python3.5/site-packages/nipype/workflows/dmri/mrtrix/group_connectivity.py:16: UserWarning: cmp not installed
  warnings.warn('cmp not installed')" when I using fmriprep in the docker container. I think cmp is optional for nipype, is this package requested in fmriprep. I trid to install the cmp package (https://github.com/LTS5/cmp), but the outcome is the same. By the way, nipype is not installed at "/usr/local/miniconda/lib/python3.5/site-packages/" on my computer. Is there any mistake I made in running fmriprep?

**Comment by effigies** [comment]
So that's a warning, not an error. I wouldn't worry about it, as FMRIPREP doesn't use those features of nipype.

Apart from this warning, are things running as expected?

**Comment by sz144** [comment]
Only create two empty folders (derivatives and log) in the out folder

**Comment by chrisfilo** [comment]
Did it report any errors? Could you post the full log?

**Comment by sz144** [comment]
It seems run well when given the pramater of participant_label 
But according to the instruction on https://github.com/BIDS-Apps/fmriprep, when I removed the argument --participant_label <ids-list> for getting all subjects processed, only two empty folders derivatives and log created in the out folder.
the full log is attached
![2](https://cloud.githubusercontent.com/assets/14858650/22400742/51f5445a-e5b5-11e6-805e-b4c7d66430d3.PNG)

**Comment by chrisfilo** [comment]
Thanks for reporting. We'll investigate.

**Comment by sz144** [comment]
I just found the datasets I applied now (the initial relaese of openfmri project) are not in the format of BIDs. I tried to process the revision dataset I used previously without the --participant_label argument and it runs well. But no errors or warnings other than cmp warning report when processing all subjects of the datasets in other format.

**Comment by chrisfilo** [comment]
This has been recently fixed in MRIQC, but I think we still need to add it to FMRIPREP.

**Comment by effigies** [comment]
Closed in #558.
