### ISSUE TITLE
Interface BrainExtractionRPT failed to run

### ISSUE THREAD

**Issue by sz144** [poldracklab/fmriprep#351]
Errors reported in log
<img width="1280" alt="2017-01-31 12 41 34" src="https://cloud.githubusercontent.com/assets/14858650/22448484/bbd5915c-e751-11e6-8726-2561cf374df3.png">

**Comment by chrisfilo** [comment]
Since the process was killed I wonder if this is a memory issue. Could you
elaborate on the system you are running this on?

**Comment by sz144** [comment]
I tried to run it on both Mac (10.12.3) and a VirtualBox VM with Ubuntu 14.04 LTS (running on a Windows 7 pc). The above log is a screen shot of Mac terminal. The result is the same on Ubuntu.
![default](https://cloud.githubusercontent.com/assets/14858650/22451759/f15ee2b2-e768-11e6-9cb1-1a1a6995ed74.PNG)

**Comment by chrisfilo** [comment]
How much memory was allocated to your virtual machine?

**Comment by sz144** [comment]
The virtual machine has 1.5GB memory. MacBook has 8 GB memory.

**Comment by chrisfilo** [comment]
Could you try again, but this time allocate more memory to the VM? 4-6 Gb?

**Comment by sz144** [comment]
I allocate 5.5Gb to the virtual machine, and tried to process the data of different subjects and tasks. Sometime result is the same as before, sometime the workflow stoped as the screenshot below
![1234](https://cloud.githubusercontent.com/assets/14858650/22569684/63348526-e990-11e6-85df-babc6da95b56.PNG)

**Comment by chrisfilo** [comment]
When you say "stopped" - how long did you wait? This steps can take over an
hour.

**Comment by sz144** [comment]
I waited longer this time and processed one participant's data (sub-01 of ds005) successfully. But the process was still killed when processing the sub-01 of ds001 openfMRI data (Revision2.0.5).

**Comment by chrisfilo** [comment]
It's most likely a memory issue (we have run fmriprep on this dataset). I
would recommend trying a machine with more RAM.

**Comment by chrisfilo** [comment]
I'm closing this assuming it was a memory issue. Please reopen if you are still having issues.
