### ISSUE TITLE
T1w skull stripping report missing in current master (ds005)

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#352]
https://circleci.com/gh/poldracklab/fmriprep/tree/master

**Comment by rwblair** [comment]
We don't currently have a report capable afni skull strip interface. Looks like ds054 does not have the  --no-skull-strip-ants flag set in the test thats being run for it on circle, so it is getting a report from the ants version of the skull strip workflow.

Originally afni was used to save time, I'm going to switch ds005 over to use the ants workflow and see  how much longer the tests take.
