### ISSUE TITLE
Surface-mapped functional time series

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#355]
Following on #347, we're going to map functional time series onto surfaces. In FreeSurfer, the standard way to do this is through `preproc-sess`, which is kind of like `recon-all` for the functional bits. This is just starting some notes before there's any code to comment on.

I've initiated nipy/nipype#1805 to get this going. This will make sampling to the subject-native and template spaces (or any subject in the subjects directroy) straightforward.

On this end, we'll need to populate an FSFAST directory structure (unless this should be in Nipype?). Since images are already motion-corrected, we can probably skip that step. BBR is part of the preproc-sess pipeline, so we can use that, unless we don't want to force people to go through the FSFAST process for that. Are we going to want to do any slice-time correction or smoothing?

**Comment by chrisfilo** [comment]
I don't think we need to run preproc-sess: motion correction, and EPI-T1 coregistration is already performed in another pipeline (although epi-T1 should be replaced by bbregister).

All we need is mapping to the surface mapping which should be achieved by `mri_vol2surf` followed by `mri_surf2surf` (for fsaverage). Am I missing something?

**Comment by effigies** [comment]
You may be right. I've always gone through the FSFAST pipeline, but it's probably doable without preproc-sess.
