### ISSUE TITLE
Add steady state detector

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#360]
Preliminary code can be found in MRIQC (https://github.com/poldracklab/mriqc/blob/9667137e42dbb1c4c70172d4e18ba358c5761c86/mriqc/utils/misc.py#L46). Each non-steady state volume should be result in an "outlier regressor" ("1" for the volume and "0" everywhere else) in the _confounds file.  New columns could be names "NonSteadyStateOutlier0", "NonSteadyStateOutlier1 etc."

**Comment by oesteban** [comment]
Possibly to include in niworkflows, so that MRIQC also in sync?

**Comment by chrisfilo** [comment]
+1 conditional on optimizations concerning handling of large 4D files.

**Comment by oesteban** [comment]
Sorry for coming back to the same question with a different opinion, but now I realized that this could be a lot more useful under ```nipype.algorithms.confounds```, DYT?

**Comment by chrisfilo** [comment]
Yup! I was thinking about the same thing :)

**Comment by chrisfilo** [comment]
https://github.com/nipy/nipype/blob/master/nipype/algorithms/confounds.py#L592

**Comment by effigies** [comment]
Note that this is done (#603), but instead of `NonSteadyStateOutlier{:d}` the default headers are `SteadyState{:02d}`. Can update this in nipype or modify the headers over here.

**Comment by chrisfilo** [comment]
I must've missed that in review. Apologies. I feel that it is less
confusing if we call it NonSteadyStateOutlier (since it indicates
non-steady state outliers with "1").

**Comment by effigies** [comment]
Yeah. Update in nipype makes more sense than hacking around it here, I think. I'll fix over there.

**Comment by effigies** [comment]
@chrisfilo nipy/nipype#2136

Should be a pretty quick review. :-)
