### ISSUE TITLE
Perform simple denoising before estimating CompCor

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#361]
CompCor can pick on trivial noise patterns that would be removed through other means. To avoid this and let CompCor focus on the non-trivial noise the following simple denoising steps should be performed prior to signal extraction:

- Regressing out non-steady state outliers (see #360)
- High-pass filter with 0.008 Hz (remove signals with slower frequencies than 0.008 Hz)

**Comment by chrisfilo** [comment]
High pass filtering could be implemented in the same regression step via Discrete Cosine Transform basis set (which could also be included in the confounds).

![image](https://cloud.githubusercontent.com/assets/238759/23048393/56b9f4cc-f46a-11e6-9809-60d76696d0b5.png)
Source: https://books.google.com/books?id=AoWD2S8759kC&pg=PA756&lpg=PA756&dq=highpass+DCT+basis+functions+filter&source=bl&ots=EWAvbB8X26&sig=YbOnaVf4Bq8nWNB9v6UK03SjjeY&hl=en&sa=X&ved=0ahUKEwjb4u_B95XSAhUH-mMKHQudCLgQ6AEIRDAJ#v=onepage&q=highpass%20DCT%20basis%20functions%20filter&f=true

**Comment by chrisfilo** [comment]
There should be so code for this in nistats https://github.com/nistats/nistats

**Comment by chrisfilo** [comment]
Is non steady state also included in denoising?

**Comment by effigies** [comment]
Nope.
