### ISSUE TITLE
Doc building in CircleCI doesn't replicate ReadTheDocs build

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#386]
See: https://readthedocs.org/projects/fmriprep/builds/5111314/

I'm honestly not sure what the issue is, here. I'm guessing for some reason it's reverting to the wrong version of nipype, but according to output, it's installing the correct commit.

```
Requirement already satisfied: nipype from git+https://github.com/nipy/nipype.git@07a75a64ae917b4ed0839d3b5a79bd63ebed9964#egg=nipype in /home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/lib/python2.7/site-packages (from -r docs/../requirements.txt (line 1))
```

This shows up later:

```
Installed /home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/lib/python2.7/site-packages/fmriprep-99.99.99-py2.7.egg
Processing dependencies for fmriprep==99.99.99
Searching for nipype===0.13.0-gcfca7cc.dev
Best match: nipype 0.13.0-gcfca7cc.dev
Adding nipype 0.13.0-gcfca7cc.dev to easy-install.pth file
Installing nipypecli script to /home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/bin
```

But I can't find a commit `gcfca7cc` in nipype's git history, so not really sure if this is the issue. And if it is, I don't know where to fix it.

**Comment by oesteban** [comment]
Maybe pulling some of their docker images?

**Comment by chrisfilo** [comment]
Have you tried removing their build cache?

**Comment by effigies** [comment]
@chrisfilo I'm not sure what you mean by removing their build cache.

**Comment by chrisfilo** [comment]
![image](https://cloud.githubusercontent.com/assets/238759/23638452/9c0d44e0-0296-11e7-8172-1a2da979abee.png)

**Comment by effigies** [comment]
Fixed it. Not clear that using their Docker images would help with catching this, if it's a cache issue. Closing for now.
