### ISSUE TITLE
Solid head-motion-correction pipeline

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#387]
In the fieldmaps branch, I'm working on this placeholder (https://github.com/poldracklab/fmriprep/blob/fieldmaps/fmriprep/interfaces/hmc.py#L48) for the head motion correction.

It is based on antsMotionCorr called with nipype's ```CommandLine``` interfaces. When https://github.com/nipy/nipype/pull/1812 is merged we probably want to convert it into a pipeline. At that point, I suggest collecting all the knowledge Ross is generating about head motion correction and try to make it as robust as we can.

For now, the placeholder runs as follows:

1. A first-pass motion correction with Affine transformations (12 parameters) is done, using the first volume as reference (or an external image provided in the ```reference_image``` input, e.g. the SBRef to motion correction of EPIs).
2. The average image out off the first-pass correction is used in a second pass correction, using only rigid registration (6 parameters). The motion parameters from this second step are the only ones we expose out.

We probably also want to look at:

- Is antsMotionCorrection the best option?
- Is this two-step scheme adequate? Can we tune up parameters?

EDIT: One thing I have forgotten, we want to use the ```-w``` option of ```antsMotionCorr``` to merge the head motion correction into the epi unwarping displacements field.

**Comment by oesteban** [comment]
One of the conversations I wanted to open here is about the API of this workflow. I propose the following:

- Inputs:
  - ```in_file```: this is one 4D file or a list of 3D files (to support the case of EPI that have been already split)
  - ```reference_image```: this is one 3D file to be used as reference (to support the case of EPI correction with an SBRef as reference).
  - ```ref_vol```: this is a float to calculate the position of the reference image (xors with ```reference_image```): 0.0 is first, 1.0 is last and therefore 0.5 would be the timepoint in the middle.

- Outputs:
  - ```out_files```: a list of 3D files after correction (therefore, the file is not merged back)
  - ```out_avg```: the average file of the timeseries after correction
  - ```out_movpar```: the output motion parameters as written by antsMotionCorr
  - ```out_confounds```: same as above, but without the two first columns (metric before and after), and in tsv format
  - ```out_tfm```: all ITK matrices in one ITK's tfm file

WDYT? @effigies @chrisfilo @rwblair

**Comment by oesteban** [comment]
The second conversation I would like to start is about we want to implement HMC. My proposal here is as follows:

1. Run a preliminar HMC on the original data
2. Co-register the fieldmap to the average image of 1).
3. Map the estimated fieldmap to each timepoint: concatenating the transform from 1) after the transform from 2).
4. Apply the fieldmap: at this point we have the timeseries corrected for susceptibility distortion -> should ease registration of HMC.
5. Run a second HMC, now with the corrected images from 4). If this is EPI and there is an SBRef (previously corrected for distortion), here it is when we use it as reference.

If there are no fielmaps for running SDC (susceptibility distortion correction), then we jump straight to 5.

**Comment by effigies** [comment]
API: Seems reasonable. Not sure what the advantage is to a ton of image files and just one transform file, though. Should `out_tfm` and `out_files` not have the same dimensionality?

Implementation: Also sounds reasonable, but I have 0 experience with field maps, so I can't give a super-informed opinion about the appropriateness of 1-4.

**Comment by oesteban** [comment]
Thanks a lot for the feedback:

- API: well, the rationale behind using the split EPI is to narrow down the memory issues. However, a text file is really easy to parse, and it is nice to have only one file in derivatives for this, if possible. 
On the other hand, it is also true that once you write a confounds file and since we are going to provide a combined file for the HMC+SDC corrections, then this unique file of transforms is not really necessary. We can go with split files for the transforms as well, I'm fine with that.

**Comment by chrisfilo** [comment]
Few thoughts:

- antsMotionCorrection does not seem to be faster and was not included in existing motion correction algorithm comparisons - not sure why we should go with it (now that we fixed the interpolation error #267)
- I don't see why the HMC workflow should output corrected 3d volumes. Since #370 we are not outputting the _bold files in their original space but in the T1w space.
- I would scratch the ref_vol input and allow reference_image input to take `auto` as a value (in such case some heuristic - for example averaging - would be used to define the reference). `reference_image` should also be an output that could be used later on in epi -> T1w registration
- as for HMC with fieldmaps - is there any evidence that we need to apply unwarping to individual volumes **prior** to doing second pass of coregistration. Seem cumbersome and it might be just splitting hairs.

**Comment by oesteban** [comment]
Nice to see the conversation growing :). I'll try to address your points.

> - antsMotionCorrection does not seem to be faster and was not included in existing motion correction algorithm comparisons - not sure why we should go with it (now that we fixed the interpolation error #267)

I wasn't aware of the fact that we are generating ITK compatible matrices already. I have only these three (weak and barely tested) reasons to suggest antsMotionCorr here:
  1. I have the impression that antsMotionCorr worked better for me with the SBRefs, and
  2. I think antsMotionCorr is more flexible to change settings
  3. antsMotionCorr has the ```-w``` flag to produce a deformation field that can be combined with the epi unwarping field -- I think this is doable with antsApplyTransforms though.

> - I don't see why the HMC workflow should output corrected 3d volumes. Since #370 we are not outputting the _bold files in their original space but in the T1w space.

Got it, I'll modify the outputs. Instead of corrected 3D volumes what we really need is to provide with the transforms you need to append to generate T1w-referenced images. Thanks for the suggestion.

If the EPI does not have SBRefs, it would make sense to write the corrected EPI in their native space to use the average as target for the T1w co-registration.

For now, I am writing out the corrected images as an early checkpoint. I agree we can skip that in "production".

> - I would scratch the ref_vol input and allow reference_image input to take `auto` as a value (in such case some heuristic - for example averaging - would be used to define the reference). `reference_image` should also be an output that could be used later on in epi -> T1w registration

As regards "```reference_image``` should also be an output that could be used later on epi -> T1w registration": I'd say it is the other way around, if you set a ```reference_image``` then you should use that ```reference_image``` in the EPI -> T1w. But yes, I totally agree with this.

Right now, if neither ```reference_image``` nor ```ref_vol``` are set then the default is ```ref_vol=0``` meaning: HMC will use the first volume as reference in a first pass and the average volume after this first registration in a second pass. It would make sense setting the default ```ref_vol=0.5``` to use the middle timepoint. Isn't this, in essence, the same functionality of ```auto```? or am I missing something?.

> - as for HMC with fieldmaps - is there any evidence that we need to apply unwarping to individual volumes **prior** to doing second pass of coregistration. Seem cumbersome and it might be just splitting hairs.

About fieldmaps there's no evidence for anything, but the theory suggests so. Very small rotations change the plane in which the fieldmap warps the image, especially far from the center of masses of the brain. So it makes sense to apply different fieldmaps to each volume. Since the images are corrected, in theory (again) we might expect increased accuracy of the second level of HMC (with corrected images). If I had to choose between the two points of improvement for a bet, all my money would go for the second (the improved HMC with corrected images).

Additionally, this is something that AFAIK very few (or none) people are doing. And I suspect it is exactly for the reason you mentioned: seems too convoluted for little advantages. When you divert from the KISS principle, you are more likely to make mistakes. However, we reached to a point where we can easily play around transforms and fieldmaps without making mistakes. So this could be a great plus for FMRIPREP, and definitely a difference to other software. Since there are some `competitors`, anything we do differently with a good justification is something we need to compare and report evidence.

**Comment by chrisfilo** [comment]
On Mon, Mar 6, 2017 at 3:07 PM, Oscar Esteban <notifications@github.com>
wrote:

> Nice to see the conversation growing :). I'll try to address your points.
>
>
>    - antsMotionCorrection does not seem to be faster and was not included
>    in existing motion correction algorithm comparisons - not sure why we
>    should go with it (now that we fixed the interpolation error #267
>    <https://github.com/poldracklab/fmriprep/issues/267>)
>
> I wasn't aware of the fact that we are generating ITK compatible matrices
> already. I have only these three (weak and barely tested) reasons to
> suggest antsMotionCorr here:
>
>    1. I have the impression that antsMotionCorr worked better for me with
>    the SBRefs, and
>    2. I think antsMotionCorr is more flexible to change settings
>    3. antsMotionCorr has the -w flag to produce a deformation field that
>    can be combined with the epi unwarping field -- I think this is doable with
>    antsApplyTransforms though.
>
> What's the advantage of combining deformation field with the unwarping
field?

>
>
>
>    - I don't see why the HMC workflow should output corrected 3d volumes.
>    Since #370 <https://github.com/poldracklab/fmriprep/pull/370> we are
>    not outputting the _bold files in their original space but in the T1w space.
>
> Got it, I'll modify the outputs. Instead of corrected 3D volumes what we
> really need is to provide with the transforms you need to append to
> generate T1w-referenced images. Thanks for the suggestion.
>
> If the EPI does not have SBRefs, it would make sense to write the
> corrected EPI in their native space to use the average as target for the
> T1w co-registration.
>
Why not just output the reference image used in the final pass of the
motion correction?

> For now, I am writing out the corrected images as an early checkpoint. I
> agree we can skip that in "production".
>
>
>    - I would scratch the ref_vol input and allow reference_image input to
>    take auto as a value (in such case some heuristic - for example
>    averaging - would be used to define the reference). reference_image
>    should also be an output that could be used later on in epi -> T1w
>    registration
>
> As regards "reference_image should also be an output that could be used
> later on epi -> T1w registration": I'd say it is the other way around, if
> you set a reference_image then you should use that reference_image in the
> EPI -> T1w. But yes, I totally agree with this.
>
> Right now, if neither reference_image nor ref_vol are set then the
> default is ref_vol=0 meaning: HMC will use the first volume as reference
> in a first pass and the average volume after this first registration in a
> second pass. It would make sense setting the default ref_vol=0.5 to use
> the middle timepoint. Isn't this, in essence, the same functionality of
> auto? or am I missing something?.
>
There are different heuristics to choose the reference volume in absence of
SBRef. For example HCP pipelines take a short fragment of the original 4D
file to avoid averaging over a long period of time.

>
>    - as for HMC with fieldmaps - is there any evidence that we need to
>    apply unwarping to individual volumes *prior* to doing second pass of
>    coregistration. Seem cumbersome and it might be just splitting hairs.
>
> About fieldmaps there's no evidence for anything, but the theory suggests
> so. Very small rotations change the plane in which the fieldmap warps the
> image, especially far from the center of masses of the brain. So it makes
> sense to apply different fieldmaps to each volume. Since the images are
> corrected, in theory (again) we might expect increased accuracy of the
> second level of HMC (with corrected images). If I had to choose between the
> two points of improvement for a bet, all my money would go for the second
> (the improved HMC with corrected images).
>
> Additionally, this is something that AFAIK very few (or none) people are
> doing. And I suspect it is exactly for the reason you mentioned: seems too
> convoluted for little advantages. When you divert from the KISS principle,
> you are more likely to make mistakes. However, we reached to a point where
> we can easily play around transforms and fieldmaps without making mistakes.
> So this could be a great plus for FMRIPREP, and definitely a difference to
> other software. Since there are some competitors, anything we do
> differently with a good justification is something we need to compare and
> report evidence.
>
True - it could be potentially beneficial, but I feel that we should firt
get a robust tested implementation of vanilla fieldmap unwarping before
getting into such details. I would also say that working on "non-linear
coregisgistration in absence of fieldmaps" feature would have potential for
much bigger impact than this. Imagine being able to correct all these
datasets without fieldmaps!

**Comment by oesteban** [comment]
> field?

Yes - antsMotionCorr -w will generate a displacements map that is compatible with nonlinear warpings from ANTS. It is indeed a field, since you get the actual affine transformation that point would undergo if you were to apply an affine matrix to the image.

> Why not just output the reference image used in the final pass of the motion correction?

That's right. I'll keep writing out these images only for debugging.

> There are different heuristics to choose the reference volume in absence of SBRef. For example HCP pipelines take a short fragment of the original 4D file to avoid averaging over a long period of time.

Oh, true. Let's think of what heuristics we want to implement and which would be the default. Thanks for bringing this up.

> True - it could be potentially beneficial, but I feel that we should firt get a robust tested implementation of vanilla fieldmap unwarping before getting into such details. I would also say that working on "non-linear coregisgistration in absence of fieldmaps" feature would have potential for much bigger impact than this. Imagine being able to correct all these datasets without fieldmaps!

That'd be awesome. However, in the short-term, I think we can see a larger surplus if we come out with fieldmap correction done right (for first time ever).

**Comment by oesteban** [comment]
For now it seems we don't need this.
