### ISSUE TITLE
exceptions during docker start

### ISSUE THREAD

**Issue by NeuroFreakZH** [poldracklab/fmriprep#393]
![fmriprep_exception](https://cloud.githubusercontent.com/assets/26483364/24041914/dbad20c6-0b0f-11e7-8385-5a9e8f194cce.JPG)

occurs after "docker run -i --rm -v /sub-01:/bids_dataset:ro -v /preproc/sub-01:/outputs bids/fmriprep /bids_dataset /outputs participant --participant_label 01" command

many thanks for your help, michael

**Comment by effigies** [comment]
This should almost certainly have a better error message, but the big issue looks like your `/bids_dataset` mount point.

Recall the example command:
```
docker run -i --rm \
	-v /Users/filo/data/ds005:/bids_dataset:ro \
	-v /Users/filo/outputs:/outputs \
	bids/fmriprep \
	/bids_dataset /outputs participant --participant_label 01
```

Here, `/Users/filo/data/ds005` is the BIDS *root*, which means it contains `sub-01` (or whatever the subjects are called. What is the full path of `sub-01`? (I'm assuming it's not actually on your root filesystem.) If, for example it's `/data/bids/sub-01`, then you would use `-v /data/bids:/bids_dataset:ro`.

Similarly, you probably don't want to specify `sub-01` in your `outputs` mount. There's nothing wrong as far as the program will be concerned, but the general idea is that the `outputs` should contain reports for all participants, possibly across multiple runs of the command.

**Comment by NeuroFreakZH** [comment]
rather trivial...and right! Many thanks. 
However, now I receive the error message: "No T1w images found for participant 01." I've checked the folder and the filenames of the T1w images several times. Should be ok. 
Perhaps the problem has its root here: 
The BIDS validator gives an error regarding the T1w files:  : 'PhaseEncodingDirection' needs to be one of 'i', 'i-, 'j', 'j-', 'k', or k-'" . 
Could this be the reason ? 

thanks for your efforts!

**Comment by NeuroFreakZH** [comment]
problem solved. PAR REC files shoud be exported to nifti using the new MRIcroGL with integrated dcmniix

**Comment by oesteban** [comment]
Glad to hear that, Michael. Thanks!

**Comment by chrisfilo** [comment]
We might wan to add the bids validator to the container and run it before
attempting to run mriqc...

**Comment by oesteban** [comment]
In the mriqc docker image we have it installed but never use it :D
