### ISSUE TITLE
Save white, pial, inflated and midthickness surface gifti files

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#394]
Make sure they overlap with the _preproc volume when loaded in Freeview and Connectome Workbench. Use .R.surf.gii suffix/extension.

**Comment by chrisfilo** [comment]
If the volumes do not overlap we might need to output the conformed FS T1 as the T1w_preproc (and adjust FAST to use it instead of the original T1).

**Comment by effigies** [comment]
For the white-matter boundary, do we want `white` or `smoothwm`? It's a pretty minor difference, so I'm okay with going either way.

**Comment by chrisfilo** [comment]
I'm not sure what's the difference, so I'll leave it up to you. We can
always change it if someone complains.
