### ISSUE TITLE
Node object and label consistency

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#417]
We should make sure all node objects have the same names as their labels.

For example:

Instead of
```
t1wmrg = pe.Node(IntraModalMerge(), name='MergeT1s')
```

we should do:
```
t1wmrg = pe.Node(IntraModalMerge(), name='t1wmrg')
```

It will make debugging easier.

**Comment by oesteban** [comment]
I wish I could hit the thumbs up icon 100 times more. We should probably start a style guide in nipype for writing workflows. Not only for us.
