### ISSUE TITLE
Explicit arguments instead of dictionaries

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#418]
Often we are passing `settings` dictionaries to workflow creation functions. This makes debugging hard, because it's not clear which fields of this dictionary are mandatory. I propose we use explicit names.

For example instead of:

```
wf = t1w_preprocessing(settings={'ants_nthreads': 1, 'nthreads': 1, 'freesurfer': True, 'reportlets_dir': '.', 'output_dir': '.'})
```

```
wf = t1w_preprocessing(ants_nthreads=1, nthreads=1, freesurfer=True, reportlets_dir='.', output_dir='.'})
```

In addition, this will make coding easier because IDEs understand local variables but do not understand dictionary keys.

**Comment by effigies** [comment]
The main downside here is that the dictionary allows us to pass an opaque set of key-value pairs that only the workflows that need them will read. Meta-workflows will need to have explicit arguments for variables to be passed to sub-workflows.

That might be good... it makes workflows more self-documenting. But another thing we could do is something like:

```Python
def metaworkflow(arg1, arg2, arg3=default3, arg4=default4, **kwargs):
    kwargs.update({'arg1': arg1, 'arg2': arg2, 'arg3': arg3, 'arg4': arg4})

    ...

    wf = t1w_preprocessing(**kwargs)
```

Then each workflow documents what it needs (if not its descendants), but can still pass an opaque value through.

But really I could go either way.

**Comment by chrisfilo** [comment]
`**kwargs` is another form of an arbitrary dictionary of arguments. It makes it harder to figure out which arguments does this function take and does not play well with IDEs - both can lead to mistakes. I still would prefer explicit arguments. It will make the code easier to read.

**Comment by effigies** [comment]
Right. It was meant to be a sort of half-measure. I'm okay with going fully-explicit args.
