### ISSUE TITLE
[bug] --reports-only argument fails to run

### ISSUE THREAD

**Issue by erramuzpe** [poldracklab/fmriprep#426]
```
DATA_DIR="/home/asier/Desktop/fmriprep/ds000030"
OUTPUT_DIR="/home/asier/Desktop/fmriprep/output"
WORK_DIR="/home/asier/Desktop/fmriprep/scratch"

docker run -ti  \
	-v $DATA_DIR:/data:ro \
	-v $OUTPUT_DIR:/output \
	-v $WORK_DIR:/work \
	-w /work \
	poldracklab/fmriprep:latest \
	/data /output participant  \
	-w /work --no-freesurfer --skip-native --no-skull-strip-ants
```
This works great! :+1: 
```
docker run -ti --rm  \
	-v $DATA_DIR:/data:ro \
	-v $OUTPUT_DIR:/output \
	-w $WORK_DIR:/work \
	poldracklab/fmriprep:latest \
	/data /output participant \
	-w /work --reports-only 
```
`
TypeError: run_reports() missing 3 required positional arguments: 'out_dir', 'subject_label', and 'run_uuid'`

[1 argument](https://github.com/poldracklab/fmriprep/blob/master/fmriprep/cli/run.py#L150-L152) is given to run_reports but [run_reports](https://github.com/poldracklab/fmriprep/blob/master/fmriprep/viz/reports.py#L169) takes 4 arguments. 

I can try to solve this

**Comment by effigies** [comment]
Thanks for the bug report. I've had this on my to do list for a couple weeks. I'll check out your PR and see what I can do to help.


-------- Original message --------
