### ISSUE TITLE
Refine ANTs brain mask with FreeSurfer

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#431]
Sometimes ANTs brainmasks fails
![image](https://cloud.githubusercontent.com/assets/238759/24636174/349e69c6-188d-11e7-9f81-6bfe0f3f51d9.png) 
ds114 subject 01

However we can use the refined brainmask obtained from the FreeSurfer reconstruction (like here: https://github.com/BIDS-Apps/nipypelines/blob/master/run.py#L401)

**Comment by effigies** [comment]
We inject the ANTs brainmask before aparc occurs.

**Comment by effigies** [comment]
Well, I suppose as long as it only ever fails by including too much and never too little, we can use it.

**Comment by chrisfilo** [comment]
Yes - it would only help in cases where ANTs includes parts of dura/skull.

**Comment by effigies** [comment]
So the idea is to continue to inject ANTs as a prior, and then let a binarized `aparc` be the final mask we use?

That should be pretty easy. I assume we don't want to turn around and use the updated mask to fix `recon-all`.

**Comment by chrisfilo** [comment]
Yes that's the idea (without rerunning recon-all). The refined mask
could be used to improve MNI coregistration and FAST tissue segmentation
(although wether we should use FAST if we have freesurfer segmentation is a
nother issues...)

**Comment by chrisfilo** [comment]
So I've tried this last night and the problem I run into is that the aparc based mask is too tight and needs to be dilated. However, when you dilate it (even when using one voxel) the result is worse (includes more non-brain) than the initial ANTs mask.

**Comment by effigies** [comment]
What about setting the mask to `sum(dilated_aparc + ANTs) == 2`?

**Comment by oesteban** [comment]
I'd bet @binarybottle's opinion on this will be very valuable to make a decision here. Arno, can we ask you what do you think about FreeSurfer's and ANTS' brain masks? And how to combine them?

**Comment by binarybottle** [comment]
Thanks for asking!  Because I have also found FreeSurfer and ANTs to under- and over-segment as mentioned above, I wrote the following function to try and reconcile the two:
https://github.com/nipy/mindboggle/blob/master/mindboggle/guts/segment.py#L1660

The docstring says::

    Combine the voxels of one label from two files and overlay them
    on the second label combined from the two files.

    An example application is to combine two segmentation volumes,
    such as from FreeSurfer and ANTs, to obtain a single cortex=2
    and noncortex=3 segmentation file, by taking the union of cortex voxels
    from the segmentations, the union of the noncortex voxels from the
    segmentations, and overwriting intersecting cortex and noncortex voxels
    with noncortex (3) labels.

    ANTs tends to include more cortical gray matter at the periphery of
    the brain than Freesurfer, and FreeSurfer tends to include more white
    matter that extends deep into gyral folds than ANTs, so this function
    attempts to remedy their differences by overlaying ANTs cortical gray
    with FreeSurfer white matter.

    Example preprocessing steps ::

       1. Run Freesurfer and antsCorticalThickness.sh on T1-weighted image.
       2. Convert FreeSurfer volume labels (e.g., wmparc.mgz or aparc+aseg.mgz)
           to cortex (2) and noncortex (3) segments using relabel_volume()
           function [refer to labels.rst or FreeSurferColorLUT labels file].
      3. Convert ANTs Atropos-segmented volume (tmpBrainSegmentation.nii.gz)
           to cortex and noncortex segments, by converting 1-labels to 0 and
           4-labels to 3 with the relabel_volume() function
           (the latter is to include deep-gray matter with noncortical tissues).

**Comment by chrisfilo** [comment]
Here's another example where freesurfer mask could be used to refine the ANTs one

ANTs
![image](https://user-images.githubusercontent.com/238759/34182216-28d896fc-e4ca-11e7-9a60-dee9f221e4a3.png)

FreeSurfer
![image](https://user-images.githubusercontent.com/238759/34182194-1482e6da-e4ca-11e7-93bf-7315ac005564.png)

It's subject 010125 from ds000221 (MP2RAGE acqusition).

**Comment by chrisfilo** [comment]
Another case
![image](https://user-images.githubusercontent.com/238759/34183235-976d67ec-e4ce-11e7-8e63-37e4e6466a12.png)

ds000017/sub-2

**Comment by oesteban** [comment]
Well, I would not include MP2RAGE here. We could try to generate a template for MP2RAGE adding noise around the head.

**Comment by oesteban** [comment]
Alright, I think we are getting to something functional on #912. There is a combination of Arno's ideas and some new.

The problem I could not think a solution for is when ANTs cuts out the outermost bend of some gyri. That happens from time to time.

**Comment by chrisfilo** [comment]
For the MP2RAGE case it might be worth trying one of the inversion images instead of the T1w image. See https://github.com/poldracklab/pydeface/pull/15 for more insights.
