### ISSUE TITLE
Normalize set the origin point of the output T1w volume to AC

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#433]
> For the volume to display correctly in wb_view, the volume needs to be in an orthogonal orientation with the origin (coordinate 0, 0, 0) at the anterior commissure. Essentially, some variation of Talairach Space.

https://github.com/poldracklab/fmriprep/pull/398#issuecomment-291981213

This seems to be related to https://github.com/nipy/nipype/pull/1868

**Comment by effigies** [comment]
Just to make a quick note. From my reading, what FreeSurfer does is a normalization to MNI, and then identifies the reverse mapping of MNI152's (0, 0, 0) to the subject native (0, 0, 0).
