### ISSUE TITLE
T1 merge is failing on s497

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#439]

**Comment by chrisfilo** [comment]
This can be resolved by creating an unbiased subject specific T1w template using affine (not just rigid) transformation. This template should replace multiple inputs to FreeSurfer.

**Comment by effigies** [comment]
If we're going to use the output of `MergeT1s` as the T1 input to `recon-all`, might as well just go with `Reorient`, since we also bring that in for the `FreeSurferTransform` step.

Pushed [`ref/unbiased_t1`](https://github.com/poldracklab/fmriprep/compare/ref/unbiased_t1) to poldracklab/fmriprep as a base. Whoever fixes this issue can work off of that if they want.

**Comment by chrisfilo** [comment]
This actually might be easier to fix than I though. All you need to do is enable 9 degrees of freedom in here https://github.com/poldracklab/fmriprep/blob/cecf99dd25a25a840673c900b3f905616bd35666/fmriprep/interfaces/images.py#L125

**Comment by chrisfilo** [comment]
another subject s499

**Comment by effigies** [comment]
## s497

I'm not actually seeing a scaling issue, just a rigid-transform failure. Here's the same merge performed with our default FLIRT (6 DOF) and FreeSurfer's mri_robust_template (6 DOF):

### FLIRT
![t1_merge](https://cloud.githubusercontent.com/assets/83442/25395526/53059550-29af-11e7-97ad-4dafae66a3ea.png)

### mri_robust_template
![robust_template](https://cloud.githubusercontent.com/assets/83442/25395525/53036d5c-29af-11e7-8dbd-ee3503c01b51.png)

mri_robust_template can do add a 7th DOF for intensity scaling. And FLIRT also takes that. I'm going to try that with `sub-497` to see if that's the issue, not affine scaling.

## s499

I'm only finding one T1 (sherlock:$PI_SCRATCH/data/uh2/sub-s499), and that looks like either it was a bad acquisition or it was already averaged from two misaligned T1s.

**Comment by chrisfilo** [comment]
I see - interesting. 

@IanEisenberg could you look into what is going on with the source data?

**Comment by effigies** [comment]
7-DOF MCFLIRT doesn't do the job. It maybe looks slightly better, but the misalignment is still obvious in the mean image.

**Comment by IanEisenberg** [comment]
Only one T1 was collected. It's just a bad acquisition.
