### ISSUE TITLE
Missing output nodes

### ISSUE THREAD

**Issue by rwblair** [poldracklab/fmriprep#44]
Nodes to be hooked up for datasink.

epi skull striped mask
t1 skull strip
t1 transformations to mni (forward and inverse)
motion corrected unwarped epi in sbref space
affine sbref to t1 transformation
estimated motion parameters (a text file containing translations and rotations)
bias field corrected t1
segmentation of t1

**Comment by chrisfilo** [comment]
Minimum:
- [ ] motion corrected (and unwarped if possible) 4D EPI files trasformed to MNI (but keeping their original resolution)
- [ ] mask of the mean EPI in MNI space (binary)
- [ ] estimated motion parameters

Full:
- [ ] motion corrected (and unwarped if possible) 4D EPI files in their original space (coregistered to SBRef if available)
- [ ] affine transform from EPI to T1 (forward and inverse)
- [ ] affine transform + non-linear transform from T1 to MNI (forward and inverse)
- [ ] mask of the EPI in native space (binary)
- [ ] mask of the T1 in native space (binary)
- [ ] bias field corrected T1
- [ ] segmentation of the T1
- [ ] CompCorr regressors
- [ ] Global Signal regressor
- [ ] Frame Displacement regressor
- [ ] White Matter, Grey Matter, CSF signal regressors
- [ ] FreeSurfer folder

See https://docs.google.com/document/d/1Wwc4A6Mow4ZPPszDIWfCUCRNstn7d_zzaWPcfcHmgI4/edit#heading=h.89uwob8yetyv for file naming and formatting (still work in progress).

**Comment by oesteban** [comment]
bonus: T1w in MNI space to check registration result.

**Comment by chrisfilo** [comment]
- [ ] probabilistic segmentation (in T1 and MNI space)
- [ ] T1 brain mask in MNI space

**Comment by oesteban** [comment]
[ ] Motion parameters in tsv file with format ```Tx  Ty  Tz Rx Ry Rz```

**Comment by oesteban** [comment]
Now, this issue would be closed when we write:

*the motion corrected 4D EPI in original space -motion corrected, coregistered to SBRef (if possible) and unwarped (if possible)-*

**Comment by shoshber** [comment]
Unless I am misunderstanding this, I don't understand how we can (properly) close this issue without first fixing up preprocessing-workflow to understand multiple BIDS inputs. Work done now would likely be wasted effort.

**Comment by oesteban** [comment]
What you mean by multiple BIDS inputs?

**Comment by shoshber** [comment]
multiple BIDS inputs: with/without fieldmaps, with/without sbrefs, etc.

**Comment by oesteban** [comment]
After the latest merged changes, closing this one should be easy. These would be the steps:

1. Changes should be done inside the ```epi_unwarp``` workflow ([here](https://github.com/oesteban/preprocessing-workflow/blob/master/fmriprep/workflows/epi.py#L304))
2. Create a ```DerivativesDataSink``` node ([example](https://github.com/oesteban/preprocessing-workflow/blob/master/fmriprep/workflows/epi.py#L141)).
3. Connect the appropriate output of the node ```unwarp``` (```'outputnode.out_file'```) to the datasink (it can be done [here](https://github.com/oesteban/preprocessing-workflow/blob/master/fmriprep/workflows/epi.py#L331))
