### ISSUE TITLE
Use pypreprocess.realign for motion estimation

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#444]
pypreprocess.realign is a pure python implementation of motion estimation algorithm from SPM. It has the following advantages over other solutions:

- it has unit tests evaluating motion parameter accuracy estimation
- few dependencies
- outputs a series of 3D files with no resampling (just adjusted affine matrices)

A couple of features would have to be added to it before integrating with FMRIPREP:

- [ ] ability to use external reference volume (assuming the same space/orientation)
- [x] parallelization of this loop https://github.com/neurospin/pypreprocess/blob/master/pypreprocess/realign.py#L303

This way we could fully parallelize each motion estimation of each run and combine motion correction with the  4d->3D split step. Having affines in nifti headers will also make the pipeline more straightforward.

**Comment by chrisfilo** [comment]
https://github.com/neurospin/pypreprocess/pull/274

**Comment by oesteban** [comment]
I see the PR to pypreprocess is merged. What is the status of this?

**Comment by chrisfilo** [comment]
It's up to us if we want to switch to using this method. There could be speed ups and working directory space savings that make it worth while.

**Comment by oesteban** [comment]
Should I assign future or 1.0.0 ?. I guess we don't want to add new features, rather than just bugfixes right?

**Comment by chrisfilo** [comment]
Up to you.

**Comment by oesteban** [comment]
Let's make it future, and if we eat up all in 1.0.0 quickly, we reconsider the decision.

**Comment by oesteban** [comment]
Superseded by #1283 . Please reopen if this is still desirable/necessary
