### ISSUE TITLE
Add support for SBRef images

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#449]
All it takes is that the optimal reference estimation procedure to return the SBRef image.

**Comment by effigies** [comment]
Just noticed this was in here. If this is still a goal, this is almost entirely done. All that's needed is to hook up the [`sbref_file`](https://github.com/poldracklab/niworkflows/blob/f3ebdf5479ed8e03143677017d5d084f5a81ae90/niworkflows/interfaces/registration.py#L367-L369) input to `EstimateReferenceImage`.

**Comment by chrisfilo** [comment]
This potentially fixes https://neurostars.org/t/fmriprep-coregistration-and-unwarping-error/2377 which comes with test data.
