### ISSUE TITLE
Rewrite ReadSidecarJSON using pybids

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#457]
https://github.com/poldracklab/fmriprep/blob/master/fmriprep/interfaces/bids.py#L175

**Comment by oesteban** [comment]
We should consider moving this interface to niworkflows or even nipype.

**Comment by oesteban** [comment]
Moving this issue to niworkflows: https://github.com/poldracklab/niworkflows/issues/185
