### ISSUE TITLE
Coregister T2w images

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#474]
#439 raises the issue of cross-session scaling differences between T1w images, which introduces the possibility that T2w images may also need to be scaled, and not merely realigned to the T1w images.

Reading the `recon-all` log for uh2/sub-s483, the T2 image is aligned using `bbregister`, which is 6-dof by default.

It seems reasonable to do a 9-dof registration of T2w images, which would then be saved to `derivatives/fmriprep/<subject>/anat/<subject>_T2w_preproc.nii.gz` (or should it be `<subject>_T2w_space-T1w_preproc.nii.gz`?). This re-aligned T2 would also be passed to FreeSurfer.

Questions:

Does FLIRT work well with T2w->T1w coregistrations? `bbregister` has a `--t2` flag to indicate the expected contrast in the moving image; it's not clear from the docs how that should be done with FLIRT. Or should we go ahead and do `bbregister --9`? Which would mean we need to wait until after the first `white` surfaces are created (`autorecon2`) to load the T2.

I'm inclined toward using FLIRT to align all of the structurals at the very beginning, because we run the risk of getting too complicated with the `recon-all` pipeline.

**Comment by chrisfilo** [comment]
Yes - let's try FLIRT or ANTs for this first.

**Comment by oesteban** [comment]
For inter-modality registration I'd try ANTs first. I can take this one if you want :+1:

**Comment by effigies** [comment]
If you like. It's a little moot at the moment, simply because we were wrong that we needed non-rigid transformations between structurals. But sure, if you want to do this.
