### ISSUE TITLE
Clarify in documentation: Running same dataset with new parameters

### ISSUE THREAD

**Issue by feilong** [poldracklab/fmriprep#483]
If I preprocess the same dataset again with some new parameters (but still in the same directories), would some part of the current outputs be automatically reused and save some time?

More specifically, if I just want to use a different output space this time, would things like FreeSurfer reconstruction be re-run again?

**Comment by chrisfilo** [comment]
Yes.

1. If you only use the save output directory freesurfer outputs will be reused.
2. If you also use the same working directory `-w` other outputs will also be reused (such as skullstriping and normalization).

**Comment by feilong** [comment]
@chrisfilo Thank you very much!

**Comment by effigies** [comment]
When we write these docs, we should note the possibility for the working directory structure to change between versions, which means that some computations may be redone. If the refactoring was significant enough, there may even be errors that must be resolved by removing some or all of the working directory.

I wonder if it would be too much work to version-stamp the working directory, and mark nodes with a "rerun if crossing this version boundary" tag. I think this would need to be a nipype feature in the `Node` itself.

**Comment by chrisfilo** [comment]
That sounds potentially rather complex. Other idea would be to reuse brain
masks and mni transformations from the output directory if they are
present. Those would save a lot of compute time, and would work even if the
working directory is not available.

**Comment by effigies** [comment]
That sounds pretty complex, itself. It'd be turning the entire upstream of each output into a conditional branch, which is already pretty hacky on the single-node level.

**Comment by chrisfilo** [comment]
We could also try an "all-or-nothing" approach and skip running the whole
anat subworkflow if all of its outputs are present. Just an idea though.
low priority.

**Comment by effigies** [comment]
Related to this idea: What about an `FmriprepSource` (or grabber) a la `FreeSurferSource`? At the end of its run, `ReconAll` loads a `FreeSurferSource` of the output directory and gives all of its outputs so they can be grabbed by something else. We could do the same, and in the process set people up with an interface for running analyses on fmriprep outputs.

**Comment by chrisfilo** [comment]
Great idea, but this could even be a `BIDSDerivativesSource`.
