### ISSUE TITLE
Issues using docker container

### ISSUE THREAD

**Issue by yavuzacikalin** [poldracklab/fmriprep#485]
I just installed the docker container on Ubuntu 16.04LTS on VirtualBox and I get the following two errors:

Issue 1:
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.27/images/json?filters=%7B%22reference%22%3A%7B%22poldracklab%2Ffmriprep%3A0.4.1%22%3Atrue%7D%7D: dial unix /var/run/docker.sock: connect: permission denied

Issue 2:
Image 'poldracklab/fmriprep:0.4.1' is missing
Would you like to download? [Y/n] Y
Traceback (most recent call last):
  File "/home/vooz/.local/bin/fmriprep-docker", line 11, in <module>
    sys.exit(main())
  File "/home/vooz/.local/lib/python2.7/site-packages/fmriprep_docker.py", line 282, in main
    mem_total = check_memory(opts.image)
  File "/home/vooz/.local/lib/python2.7/site-packages/fmriprep_docker.py", line 122, in check_memory
    if line.startswith(b'Mem:')][0]
IndexError: list index out of range

**Comment by effigies** [comment]
Have you added your user to the docker group? See: [Manage Docker as a non-root user](https://docs.docker.com/engine/installation/linux/linux-postinstall/)

The second issue is just a failure to catch the first exception. I'll fix that for the next release.

**Comment by yavuzacikalin** [comment]
Ok with the permissions enabled it doesn't give any errors but gets stuck after the "Y" response to the download command:

vooz@vooz-VirtualBox:~$ fmriprep-docker
usage: fmriprep-docker [-h] [-v] [-i IMG] [-w WORK_DIR] [-f PATH] [-n PATH]
                       [-p PATH] [--shell] [--config PATH]
                       [bids_dir] [output_dir] [{participant}]

fMRI Preprocessing workflow

positional arguments:
  bids_dir
  output_dir
  {participant}

optional arguments:
  -h, --help            show this help message and exit (default: False)
  -v, --version         show program's version number and exit (default:
                        False)
  -i IMG, --image IMG   image name (default: poldracklab/fmriprep:0.4.1)

Wrapper options:
  Standard options that require mapping files into the container

  -w WORK_DIR, --work-dir WORK_DIR
                        path where intermediate results should be stored
                        (default: None)

Developer options:
  Tools for testing and debugging FMRIPREP

  -f PATH, --patch-fmriprep PATH
                        working fmriprep repository (default: None)
  -n PATH, --patch-niworkflows PATH
                        working niworkflows repository (default: None)
  -p PATH, --patch-nipype PATH
                        working nipype repository (default: None)
  --shell               open shell in image instead of running FMRIPREP
                        (default: False)
  --config PATH         Use custom nipype.cfg file (default: None)

Image 'poldracklab/fmriprep:0.4.1' is missing
Would you like to download? [Y/n] Y


^CTraceback (most recent call last):
  File "/home/vooz/.local/bin/fmriprep-docker", line 11, in <module>
    sys.exit(main())
  File "/home/vooz/.local/lib/python2.7/site-packages/fmriprep_docker.py", line 282, in main
    mem_total = check_memory(opts.image)
  File "/home/vooz/.local/lib/python2.7/site-packages/fmriprep_docker.py", line 119, in check_memory
    stderr=subprocess.DEVNULL)
  File "/home/vooz/.local/lib/python2.7/site-packages/fmriprep_docker.py", line 74, in _run
    stdout, stderr = proc.communicate()
  File "/home/vooz/anaconda2/lib/python2.7/subprocess.py", line 471, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/home/vooz/anaconda2/lib/python2.7/subprocess.py", line 121, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

**Comment by effigies** [comment]
Ah. I'd guess that it's just taking a bit of time to download and prepare the 4GB image. We should be a little more verbose to let users know that it's working.

**Comment by yavuzacikalin** [comment]
Oh, gotcha, thanks!
