### ISSUE TITLE
Output EPI voxel size slightly different from input

### ISSUE THREAD

**Issue by feilong** [poldracklab/fmriprep#497]
It happened to me occasionally in some runs of some subjects.  The input voxel size was always `(3.0, 3.0, 3.0)` (as shown by `nib.load(filename).header.get_zooms()[:3]`), but the output voxel size became `(2.9999998, 3.0, 3.0)`.  An annoying side effect of this discrepancy is the output grid of that run became `(66, 77, 65)` instead of `(65, 77, 65)`, and the two grids were half a voxel apart and I couldn't simply delete a slice to make them match.

As I tracked down this issue, the voxel size of the generated reference image was already different, and influenced all following steps.  It seems related to [`EstimateReferenceImage`](https://github.com/poldracklab/niworkflows/blob/master/niworkflows/interfaces/registration.py#L261).

The filename of my singularity image was `poldracklab_fmriprep_latest-2017-04-08-0600a0f79358.img`.

**Comment by chrisfilo** [comment]
Ah indeed I have heard about this issue here https://neurostars.org/t/dimensions-mismatch-in-preprocessed-fmri-data-fmriprep-0-3-2/362. 

It would be great to solve it. Is there an example dataset where this is happening that you could share with us?

**Comment by chrisfilo** [comment]
Alternatively you can try changing [this line](https://github.com/poldracklab/fmriprep/blob/46ce936bb2f19dbcb72487fc13765dde5b3bc18e/fmriprep/workflows/epi.py#L290) to 

`gen_ref = pe.Node(EstimateReferenceImage(mc_method = "FSL"), name="gen_ref")`

**Comment by feilong** [comment]
Let me ask my collaborators who collected the data to see if they consent to share.

Probably the problem is because some motion correction step messed up with the header (numeric precision issue with motion parameters and/or affine matrix?).  I guess it could simply be solved by changing the `moving_image` of `GenerateSamplingReference()` to the original EPI, as we only need accurate voxel size information to generate sampling reference.

**Comment by effigies** [comment]
If it makes a difference to their willingness to share, the first 40 volumes of the relevant series should be enough for us to replicate the issue.
