### ISSUE TITLE
Mysterious recon-all failure

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#511]
Moving from #425, since this seems to be a legitimately different issue.

* [FMRIPREP log](https://gist.github.com/mike21499/ebe7ef6910f8948bad6130b50657d59f)
* [recon-all log](https://gist.github.com/mike21499/a760c4629a06a1d8b8421fbd108833bd)

cc @mike21499

**Comment by mike21499** [comment]
Hi

Thanks for your comments: 
Given that the entire pipeline ran (AFAICT), there are two possibilities I can see:

1 ) Our use of an external skull-stripping pipeline produced a mask that FreeSurfer could not use.
2 )There's some issue with your data that FreeSurfer is unable to automatically correct for.

To check for (1), if it isn't evident in the report, you can overlay the brainmask (<outdir>/fmriprep/anat/sub-01_T1w_brainmask.nii.gz) on the preprocessed T1 (.../sub-01_T1w_preproc.nii.gz) in mricron or Freeview, and verify that gray matter hasn't been removed.
![recon_all_failure_overlay](https://cloud.githubusercontent.com/assets/26599314/26098043/c15631ae-3a26-11e7-92b6-0748d3ba7bc1.JPG)

I've tried your approach 1). Attached is the result. It seems that grey matter has been removed..... 

thanks for your efforts, michael

**Comment by effigies** [comment]
Hi @mike21499. It's difficult to be sure from two slices and an opaque overlay, but that looks like a pretty reasonable mask. If anything, it seems to have included a bit too much near the occipital lobe.

I think at this point I'd recommend going ahead and trying recon-all in a fresh directory without going through fmriprep.

If you're able to provide a defaced copy of your T1w image, I can try running the anatomical pipeline and see if I can reproduce your issue.

**Comment by mike21499** [comment]
@effigies . That would be great. Attached is a copy of the anat-folder (no wirries, it's my brain :)
[anat.zip](https://github.com/poldracklab/fmriprep/files/1004371/anat.zip)

**Comment by effigies** [comment]
@mike21499 I'm not able to download from that link. You can email me at this username @ gmail.com.

**Comment by effigies** [comment]
I cannot reproduce this bug. fmriprep ran without error, including recon-all. Have you tried running on fmriprep 0.4.3?

**Comment by effigies** [comment]
@mike21499 Just checking in.

A few questions:

 * How are you running this? Our recommended approach is the `fmriprep-docker` wrapper script, or Singularity, if you're running on a cluster environment.
* Do you have enough memory and disk space?
* Can you try re-running with the most recent release?

**Comment by mike21499** [comment]
Hi effigies

Problem solved. It was a memory issue. We assigned 16GB of RAM to one subject and it ran smootly! 

thanks for your efforts, michael

**Comment by effigies** [comment]
Great! Thanks for checking back in.
