### ISSUE TITLE
Update ANTs to 2.2.0

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#516]
Relevant changes:
- different masking in N4BiasFieldCorrection: https://github.com/stnava/ANTs/commit/6816c5a7ece6090febf90496dd5bd95cd48bb46e
- different metric in brain extraction: https://github.com/stnava/ANTs/commit/98644cd2caa1d30f0ef7cc804098111ee680bc39
- different registration init in brain extraction: https://github.com/stnava/ANTs/commit/10d8c4ccecc80ed2f90a6512e4984ec8e713e2e8

**Comment by effigies** [comment]
This would be good for #544, since I was testing based on 2.2.0. That said, the way we're using `antsRegistration` shouldn't be massively different between the two versions. The main thing is we'll need to switch from the old style of specifying masks to new.

Related: nipy/nipype#2078

**Comment by chrisfilo** [comment]
I think there are binaries available now (from a third party but still) - no objections to upgrade from me.

**Comment by effigies** [comment]
Yeah, I've been working with [this one](https://github.com/kaczmarj/neurodocker/blob/master/neurodocker/interfaces/ants.py#L61).

**Comment by effigies** [comment]
Looking at these changes, it looks like what we want to do is to make sure the outputs are reasonable; there aren't really interface changes to make. Possibly we could generate a mask before N4BiasFieldCorrection (e.g., with BET using a very liberal threshold), but with brain extraction, as long as it  continues to work well, there doesn't seem to be anything to do there...
