### ISSUE TITLE
Circle builds failing due to old AFNI

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#521]
Looks like Sphinx has a [new release out today](https://pypi.python.org/pypi/Sphinx/1.6.1), so we're getting nipype warnings raised to Sphinx warnings, which are treated as errors.

```
AFNI is outdated, detected version Debian-16.2.07~dfsg.1-2~nd16.04+1 and AFNI_17.1.05 is available.
```

**Comment by chrisfilo** [comment]
It seems like a good motivation to suppress the irrelevant nipype warnings!
