### ISSUE TITLE
cannot run fmriprep-docker 0.4.4

### ISSUE THREAD

**Issue by rschmaelzle** [poldracklab/fmriprep#531]
HI,
this may be totally user ignorance on my side, but I am stuck getting fmriprep to run and was encouraged by the output to report this issue ...

I installed fmriprep-docker using pip andchecking gives me 

>  fmriprep-docker -v
Continue anyway? [y/N]y
fmriprep v0.4.4

, so it seems to be successfully installed. I have a bids structure that is compatible according to the validator. now I try to get a basic prepro done via>

> Ralf$ fmriprep-docker /Users/Ralf/My_Cloud/03_PROJEKTE/ins/data/source /Users/Ralf/My_Cloud/03_PROJEKTE/ins/data/fmriprep -participant sub-01
Warning: <8GB of RAM is available within your Docker environment.
Some parts of fMRIprep may fail to complete.
Continue anyway? [y/N]y
RUNNING: docker run --rm -it -v /Users/Ralf/articipant:/usr/local/miniconda/lib/python3.6/site-packages/nipype:ro -v /Users/Ralf/My_Cloud/03_PROJEKTE/ins/data/source:/data:ro -v /Users/Ralf/My_Cloud/03_PROJEKTE/ins/data/fmriprep:/out poldracklab/fmriprep:0.4.4 /data /out participant sub-01
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==0.4.4', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2258, in load
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/__init__.py", line 33, in <module>
    from nipype.interfaces.afni import Info
ModuleNotFoundError: No module named 'nipype.interfaces'

Seems that the installations requires more re: nipype, which I have on my system, but that is all outside of docker... As said, I am just chekcing out things and may make errors - but thought I'd report to help improve documentation/fixing errors. 

Best, r

**Comment by effigies** [comment]
I'll have a look at the nipype import issue, but a couple points to start with:

1) I think you'll want something more along the lines of:

```Shell
fmriprep-docker /Users/Ralf/My_Cloud/03_PROJEKTE/ins/data/source \
    /Users/Ralf/My_Cloud/03_PROJEKTE/ins/data/fmriprep participant --participant_label 01
```

2) You may want to increase the memory available to Docker. While fmriprep will attempt to run with <8GB, some pieces may fail.

**Comment by chrisfilo** [comment]
It's the `-` in `-participant` what caused the problem. If you replace it with `participant` (without the dash) it should work.

**Comment by rschmaelzle** [comment]
yes! Running now with the following command got it start :

> fmriprep-docker /Users/Ralf/My_Cloud/03_PROJEKTE/ins/data/source     /Users/Ralf/My_Cloud/03_PROJEKTE/ins/data/fmriprep participant --participant 01

sorry, I was a bit confused about i) the --participant vs. --participant label and about the bids-naming of sub-01 vs. 01. Thanks for the quick and helpful reply - awesome project.
Best, r
