### ISSUE TITLE
Copy fsaverage instead of symlinking

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#535]
```
[chrisgor@sherlock-ln04 login_node /oak/stanford/groups/russpold/data/ds000030_R1.0.3_preprocessed_0.4.4/freesurfer]$ ls -al
total 1088
drwxr-s---+ 268 chrisgor russpold 20480 May  9 13:07 .
drwxr-s---+   5 chrisgor russpold  4096 May  5 13:27 ..
lrwxrwxrwx    1 chrisgor russpold    34 May  5 18:07 fsaverage -> /opt/freesurfer/subjects/fsaverage
drwxr-s---+   8 chrisgor russpold  4096 May 31  2011 fsaverage5
drwxrws---+  10 chrisgor russpold  4096 May  9 19:11 sub-10159
drwxrws---+  10 chrisgor russpold  4096 May  9 02:29 sub-10171
drwxrws---+  10 chrisgor russpold  4096 May  7 08:44 sub-10189
drwxrws---+  10 chrisgor russpold  4096 May  9 01:32 sub-10193
```

See https://github.com/BIDS-Apps/freesurfer/blob/master/run.py#L142

**Comment by effigies** [comment]
Oh, this is a consequence of [this change](https://github.com/poldracklab/fmriprep/commit/f07d45953db28c98d18e05261556cf978255d124#diff-7bf7d3ca48aa501c95ee753280fb3ee1L237), which doesn't copy fsaverage unless it's a target space. `recon-all` [symlinks](https://github.com/freesurfer/freesurfer/blob/master/scripts/recon-all#L4894-L4902) if it doesn't exist. I'll make sure `fsaverage` is always copied.
