### ISSUE TITLE
Dependency versioning

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#541]
Now that nipype 0.13.1 is out, it might be time to revisit our dependency pinning pattern. We've been simply pinning commits, which obviously is fine for development, but we saw in #540 that this strategy can cause issues for users running natively because pip doesn't install the versions pinned in `requirements.txt`.

Since we can release niworkflows as often as we like, I think we should plan to make a release prior to any fmriprep/mriqc release, so that we can depend on that in the app releases.

Nipype is more complicated. We're already starting to depend on post-0.13.1 PRs, so we can't simply pin to 0.13.1 and compensate for any changes in niworkflows and fmriprep until another nipype release. (My understanding is Satra doesn't intend to push another release until 1.0.) We could try to persuade Satra to have a short (e.g. 2-week or 1-month) release cycle just to get the ENH/FIX PRs into something we can depend on with pip.

Or perhaps we could push to move nipype to [`versioneer`](https://github.com/warner/python-versioneer)-like strings which allow us to say "more recent than this version". We'd still need to be able to persuade pip to automatically install something if the current version doesn't satisfy...

Any thoughts?

**Comment by oesteban** [comment]
+1 . For mriqc 0.9.5 I waited for the release of niworkflows and didn't want to include anything beyond nipype 0.13.1.

For next 0.9.6 (due by the end of this week) I was planning not to stay with the latest release of niworkflows and start a submodule with nipype-specific stuff until those items get included in an official release of nipype.

This is a short-term solution that might work for small iterations like mriqc-0.9.6 but doubtfully sustainable in the long term.

On the other hand, it seems that trying to release nipype more often did not work in the past. So a `versioneer`-like scheme might be a good compromise solution.

Overall you are right, this is currently an outstanding problem. And I can't think of solutions other than those you enumerated.

**Comment by chrisfilo** [comment]
Let's revisit our goals:
1) Keep as much as we can in nipype master so others can benefit.
2) Make installation possible for the few that cannot use Docker/singularity.

I wonder if we shouldn't just ship a pinned version of nipype master with niworkflows (`import niworkflows.nipype as nipype`). This might be easy to achieve using git submodules. WDYT?

**Comment by effigies** [comment]
That sounds reasonable to me on first read. Can we foresee any downsides?
