### ISSUE TITLE
epi_ref_wf_transformer crash - typo?

### ISSUE THREAD

**Issue by mfalkiewicz** [poldracklab/fmriprep#546]
Hello guys,
  I got an crash which looks like a typo regarding the string formatting. Could you please check it?

mfalkiewicz@medusa:~/experiments/SDT1/derivatives/fmriprep/sub-01/log/20170602-072506_a20a50c9-14f6-459b-a422-386035837f11$ nipype_display_crash crash-20170603-004945-mfalkiewicz-transformer-bc7c8ae3-1a8f-4e1a-815e-80d32a474bd7.pklz 

File: crash-20170603-004945-mfalkiewicz-transformer-bc7c8ae3-1a8f-4e1a-815e-80d32a474bd7.pklz
Node: fmriprep_wf.single_subject_01_wf.func_preproc_task_speedating_wf.epi_reg_wf.transformer
Working directory: /home/mfalkiewicz/scratch/MF_SDT1_fmriprep/fmriprep_wf/single_subject_01_wf/func_preproc_task_speedating_wf/epi_reg_wf/transformer

Node inputs:

bbreg_transform = /home/data/scratch/MF_SDT1_fmriprep/fmriprep_wf/single_subject_01_wf/func_preproc_task_speedating_wf/epi_reg_wf/bbregister/uni_masked_bbreg_sub-01.mat
fs_2_t1_transform = /home/data/scratch/MF_SDT1_fmriprep/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/surface_recon_wf/fs_transform/freesurfer2subT1.mat
function_str = def apply_fs_transform(fs_2_t1_transform, bbreg_transform):
    import os
    import numpy as np
    out_file = os.path.abspath('transform.mat')
    fs_xfm = np.loadtxt(fs_2_t1_transform)
    bbrxfm = np.loadtxt(bbreg_transform)
    out_xfm = fs_xfm.dot(bbrxfm)
    assert np.allclose(out_xfm[3], [0, 0, 0, 1])
    out_xfm[3] = [0, 0, 0, 1]
    np.savetxt(out_file, out_xfm, fmt='%.12g')
    return out_file

ignore_exception = False

Traceback: 
Traceback (most recent call last):
  File "/home/mfalkiewicz/scratch/MF_SDT1_fmriprep/fmriprep_wf/batch/pyscript_20170602_073945_fmriprep_wf.single_subject_01_wf.func_preproc_task_speedating_wf.epi_reg_wf_transformer.py", line 32, in <module>
    result = info['node'].run(updatehash=info['updatehash'])
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 372, in run
    self._run_interface()
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 482, in _run_interface
    self._result = self._run_command(execute)
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 613, in _run_command
    result = self._interface.run()
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1083, in run
    runtime = self._run_wrapper(runtime)
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1031, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/nipype/interfaces/utility/wrappers.py", line 194, in _run_interface
    out = function_handle(**args)
  File "<string>", line 10, in apply_fs_transform
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1200, in savetxt
    raise ValueError('invalid fmt: %r' % (fmt,))
ValueError: invalid fmt: u'%.12g'
Interface Function failed to run.

**Comment by effigies** [comment]
I believe this is a Python 2 issue with Unicode strings, rather than a typo (`%g` is a valid format). Are you able to run with Python 3?

We don't actively support Python 2 in fmriprep, though we'd consider simple fixes that allow running on both.

**Comment by mfalkiewicz** [comment]
This was indeed probably run on python2. I simply ran the command-line, without going into the details regarding the interpreter. Maybe the choice of python3 should be handled under the hood, assuming that both python2 and python3 are available on the system?

**Comment by effigies** [comment]
I submitted #547. However, I'm not sure this will actually work; if someone installs with `pip2`, the Python2 executable may still be called by the installed script, since an installed script looks something like:

```Python
#!/path/to/installation/python

# -*- coding: utf-8 -*-
import re
import sys

from <module> import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

I think you may need to install with `pip3`.

However, feel free to `pip install --upgrade git+https://github.com/effigies/fmriprep.git@run_py3#egg=fmriprep`, and let me know if that fixes your issue.

**Comment by mfalkiewicz** [comment]
Indded, #547 does not help. However, #548 does. 

Cheers,
  Marcel
