### ISSUE TITLE
crash in anat_prepro

### ISSUE THREAD

**Issue by rschmaelzle** [poldracklab/fmriprep#571]
Hi,
I am running again into issues with anatomy. Last time you helped me pointing out that there was an issue with the .nii extension (sorry about that) - but this time it seems to be a real crash.
Attached  is the extensive diagnostics from the html-section "errors". 
Thanks & best, r 

[output.txt](https://github.com/poldracklab/fmriprep/files/1099367/output.txt)

My command for running was
`fmriprep-docker /Users/Ralf/My_Cloud/03_PROJEKTE/ins/data/source /Users/Ralf/My_Cloud/03_PROJEKTE/ins/data/fmriprep participant --participant 08 --no-freesurfer`

**Comment by effigies** [comment]
Thanks for the report. It looks like the process is being killed, probably due to exceeding memory bounds. We recommend running with at least 8GB of memory available to your container. Do you know what the constraints of your system or docker configuration are?

**Comment by rschmaelzle** [comment]
thanks again. that was it. i had to increase docker memory (in Docker - preferences) to 11gb which by default was set too low. Curiously it had worked previously, but  i had installed some additonal things which seem to have taken away power. Best r
