### ISSUE TITLE
Add MELODIC/AROMA figures to reports

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#575]
Tabled in #539.

**Comment by chrisfilo** [comment]
I made this on the plane last night:

![image](https://user-images.githubusercontent.com/238759/27921134-a1cb3384-622b-11e7-9ad7-ff47fbd3c41f.png)

What do you think @jdkent?

**Comment by chrisfilo** [comment]
The assignments are random - just for the visualization purposes.

**Comment by jdkent** [comment]
This looks nice, the red/green classification makes it visually easy to distinguish noise and signal (if they were classified as such). Since this is such a large report, would it be given it's own page for visualization?

**Comment by chrisfilo** [comment]
I would make it full scale to full width, but since the reports are HTML (not PDF) there are no "pages" per se.

**Comment by effigies** [comment]
Just as an aesthetic comment, I'd consider keeping the text in black, maybe coloring the "C<N>". Definitely not a big deal, and I might be wrong, but I think that'd be a little easier to read.

**Comment by jdkent** [comment]
Sorry, I'm having trouble with words today. One issue I ran into when I was just trying to print the unaltered melodic report was the space allotted to the report was too small. fmriprep appeared to give each QC report the same amount of space, but the aroma report would need a variable amount of space depending on how many components were derived from melodic. I don't know if the space allotment is handled in [reports.tpl](https://github.com/poldracklab/fmriprep/blob/master/fmriprep/viz/report.tpl) or in [reports.py](https://github.com/poldracklab/fmriprep/blob/master/fmriprep/viz/reports.py), but that is separate issue from the aesthetic in the visualization.

**Comment by effigies** [comment]
I can try to find some time to look at how that works. If you want to start a quick feature branch that re-adds the reports, that would be a useful first step. I think what we may end up wanting to do is to generate an SVG that tiles the inputs, and then save that as a single reportlet to be included in the output.

**Comment by chrisfilo** [comment]
I think we got it figured out in the mriqc reports. I'll try to get it
working in FMRIPREP over the weekend.

**Comment by oesteban** [comment]
We haven't talked much about ICA outputs in the testing plan. How are things in this front? Should we remove this issue from the 1.0.0-rc1?

**Comment by chrisfilo** [comment]
I'm working on it. A PR should come in soon.
