### ISSUE TITLE
Stochastic ICA-AROMA bug

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#578]
- https://circleci.com/gh/effigies/fmriprep/589#tests/containers/1
- https://circleci.com/gh/poldracklab/fmriprep/929#tests/containers/1

I suspect this is related to either the low resolution or the small number of time points. It's the ICA-AROMA interface failing to run, so the solution might need to be in nipype.

**Comment by jdkent** [comment]
The problem file is here in [feature_scores.txt](https://929-53175327-gh.circle-artifacts.com/1/home/ubuntu/ds005/scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_mixedgamblestask_run_01_wf/discover_wf/ica_aroma_wf/ica_aroma/feature_scores.txt)
```
nan 6.564704524321367529e-01 2.187500000000000000e-01 3.239780910722724755e-02
nan 5.158288285626534408e-01 8.854166666666665741e-02 2.391670704351533949e-02
nan 4.715828885449906416e-01 8.854166666666665741e-02 4.360936751167206887e-02
nan 6.033063945444272491e-01 2.187500000000000000e-01 1.898491122542641033e-02
nan 5.930657172866073967e-01 8.697916666666666297e-01 3.077832062697738458e-02
```
The first column corresponds to [maxRPcorr](https://github.com/rhr-pruim/ICA-AROMA/blob/master/ICA_AROMA_functions.py#L482). I'll keep looking to see what going wrong.

**Comment by effigies** [comment]
I wonder if [this line](https://github.com/rhr-pruim/ICA-AROMA/blob/master/ICA_AROMA_functions.py#L273) should be using [`np.nanmean`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.nanmean.html) instead.

**Comment by jdkent** [comment]
I made a [python notebook](https://drive.google.com/drive/folders/0B9eMc5Q-tEdSbU9xQUdjMFRCUWs?usp=sharing) for the function in question and used the melodic_mix and motion parameters from the failing subject. The number of NaNs is small so I believe your intuition is correct, we can just ignore the iterations that didn't work and average over the correct ones. I'll submit a pull request to ICA-AROMA.
