### ISSUE TITLE
Links to "about" and "erros" are repeated

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#594]
![image](https://user-images.githubusercontent.com/238759/28394493-2f591c40-6ca2-11e7-8ddb-b8911528adfd.png)

https://s3.amazonaws.com/openneuro.outputs/b2b76d1b40fe1196eb7db904aaf4bdf1/d7d6f355-ca15-4dc4-97bf-544085dc5188/fmriprep/sub-2.html

**Comment by effigies** [comment]
Fixed in #584. That's why I wanted to merge and push a quick release.
