### ISSUE TITLE
Duecredit integration

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#600]
Generate a "literate" description of the steps, including references to methods.

**Comment by chrisfilo** [comment]
Inclusion into 1.0.0 milestone conditional on help from @yarikoptic help.

**Comment by yarikoptic** [comment]
Simple integration / support should be ready to do but the literate description - not sure if I would be able to try to tackle it any time soon :-/

**Comment by chrisfilo** [comment]
This has been implemented by the citation boilerplate.
