### ISSUE TITLE
Number of files written to working directory

### ISSUE THREAD

**Issue by jokedurnez** [poldracklab/fmriprep#623]
Running fmriprep on MyConnectome generated at least 1,794,910 files in the working directory.  My job stopped because I exceeded the maximum number of files on my system (sherlock:oak - 8 mil).  Something to keep in mind :-)

**Comment by effigies** [comment]
Wow. Good to know. I'm guessing this is because of the large number of EPI volumes?

I think there was discussion about re-jigging HMC to avoid the explosion of files, but if anything ever came of that, it sure wasn't code.

**Comment by effigies** [comment]
Assuming that that is the source of the problem, I think your best bet for now is to specify `--task-id` for separate tasks, and delete the corresponding `func_preproc_task_<task-label>_run_<run-label>_wf` directories from the working directory, once it's completed.

**Comment by oesteban** [comment]
@jokedurnez I think you should also use a local scratch mount point for the work directory. It'll be faster and I don't think there'll be any limitations on size and numbers of files.

**Comment by chrisfilo** [comment]
I doubt local scratch would be big enough for this dataset.

@effigies Indeed switching to pypreprocess (https://github.com/poldracklab/fmriprep/issues/444) would avoid the need to convert MCFLIRT affine matrices to ITK and thus decrease the number of intermediate files.

**Comment by jokedurnez** [comment]
@oesteban I can't run on a local scratch, because I'm hitting the maxtime, so I need to be able to restart freesurfer...
(I can  - of course - still move to TACC ;-) )

**Comment by effigies** [comment]
My recommendation in that case would be to *first* run with `--anat-only --output-space T1w`, so that almost all of the time is devoted to FreeSurfer, until it's finished. Once that's done (and FreeSurfer is in the output directory), you could run the rest on local scratch.

Also, is somebody already building a 0.6.0 singularity image? That will resolve your issues with the ses-001 T1w images. I can get it building if nobody else is. Will take about 45 minutes to build and transfer to Sherlock.

**Comment by oesteban** [comment]
@jokedurnez Gotcha. The only alternative I can think of is running FreeSurfer first, move the results to the appropriate location in OAK and then run fmriprep.

@chrisfilo ITK accepts writing all the transforms in only one file. We could remove that MapNode (number of ITK transforms times num. of files per node generated by nipype and the c3d interface). We could replace all of that with just one node. WDYT?, that'd be probably faster than moving to pypreprocess

PS. @effigies just posted while I was writing, so probably his opinion is much better informed than mine.

**Comment by effigies** [comment]
Having issues with my build machine, if somebody else wants to push a new Singularity image...a
