### ISSUE TITLE
ImportError: No module named 'niworkflows'

### ISSUE THREAD

**Issue by mick-d** [poldracklab/fmriprep#625]
I installed `fmriprep  (wrapper 0.5.4)` in a `conda` environment with `pip`, and run fmriprep on a dataset:
```
source activate fmri
pip install fmriprep-docker
fmriprep-docker --nthreads 10 --output-space fsnative --use-aroma --work-dir /tmp_data --write-graph /raw_data /preproc participant
```
While the pipeline is still running, I noticed two crash files per subject for all subjects:  `/preproc/fmriprep/sub-controlXX/log/*/crash-*-root-calc_epi_mean-*.pklz` and `/preproc/fmriprep/sub-controlXX/log/*/crash-*-root-calc_median_val-*.pklz`.

Using `nipype_display_crash` revealed that in all cases this was due to:
```ImportError: No module named 'niworkflows'```

I am not sure what would be the impact of these crashes on the whole preprocessing pipeline (which is still running), and what to do to correct for this error (if necessary). 

PS: I have `nipype` installed in the same `conda` environment as `fmriprep`

**Comment by effigies** [comment]
FMRIPREP uses a copy of nipype that's bundled in niworkflows. (See #541, poldracklab/niworkflows#174, poldracklab/niworkflows#183 for justification and discussion.) The short story is: We need new nipype features on a faster time scale than nipype releases, and this strategy avoids breaking the environments of users who install fmriprep locally instead of through Docker. It has the side effect of making niworkflows and nipype interfaces mutually incompatible; you have to use `niworkflows.nipype` if you use `niworkflows`.

As a rule, nipype crash files are not portable, so you would be unlikely to be able to use `nipype_display_crash` on crash files created in a Docker container, even if we weren't bundling an incompatible version of nipype. The release coming out later today should be moving to generating text files, but for debugging, you can use the `--config` option, and pass a [nipype configuration file](https://nipype.readthedocs.io/en/latest/users/config_file.html) that includes `crashfile_format = 'txt'`. It may also be useful to use `stop_on_first_crash = true`.

**Comment by mick-d** [comment]
Thanks @effigies. I may have misunderstood but I do not think the first part of your answer apply to my case. I used an extremely straightforward process:

1. I install fmriprep through Docker (in my `conda` environment with `pip install fmriprep-docker`)
2. I run a `fmriprer-docker` command on raw data (as described in my previous post)

So how is it that crash files are generated? I understand I shouldn't use `nipype_display_crash` as it is from a different version of nipype but still, it means crashes occurred for all my subjects in a vanilla installation of fmriprep, so I would think that something is wrong. 

Further, I am not sure what you mean by:
> It has the side effect of making niworkflows and nipype interfaces mutually incompatible; you have to use niworkflows.nipype if you use niworkflows.

Do you mean that if I were to use FMRIPREP and nipype together in custom code, I would need to ignore my local nipype package by only using the FMRIPREP-embed nipype modules by importing them exclusively through `niworkflows.nipype`?

**Comment by mick-d** [comment]
Maybe you were simply telling me that you can't comment on this issue as the error I reported was obtained from `nipype_display_crash`? And that I should only report issues from `txt` crash files generated by an fmriprep pipeline running with the appropriate nipype `crashfile_format`?

**Comment by effigies** [comment]
Yes, there's not enough to go on here to assess the underlying problem. Using an updated configuration file may help you get the debug information you were looking for, which we may then be able to help you with.

You're welcome to report issues at whatever level of information you have. We'll do our best to help you come up with the information you need to get useful feedback from us. If you have tracebacks (which will show up in the reports, as well as in the terminal output, after the workflow has completed as much as it can) it may be obvious what's going wrong.

-----

To address your first comment:

The first part was merely explaining why you're seeing complaints about `niworkflows` when trying to run `nipype_display_crash`. Sorry, if that was extraneous.

> So how is it that crash files are generated?

Failures in the pipeline can produce crash files. Unfortunately, bugs crop up.

> I understand I shouldn't use nipype_display_crash as it is from a different version of nipype but still, it means crashes occurred for all my subjects in a vanilla installation of fmriprep, so I would think that something is wrong.

Agreed. It's hard to say more without knowing more about your data and the specific failures.

> Do you mean that if I were to use FMRIPREP and nipype together in custom code (this is not my case, as I only run a fmriprer-docker command), I would need to ignore my local nipype package by only using the FMRIPREP-embed nipype modules by importing them exclusively through niworkflows.nipype?

Yes. However, our goal is to move as much of the useful functionality (that isn't just to make fmriprep run) into nipype. While this is motivated more by the view that we should be good members of the nipype community, it should also avoid putting users in a position where they're forced to do that. We see fmriprep as an application, not a library, and niworkflows as a place to contain common application code for MRIQC and fmriprep, as well as stage interfaces and workflows that we want to move into nipype.

----

Hopefully some of this was helpful.

**Comment by mick-d** [comment]
Excellent, thanks a lot for that @effigies.

Since the pipeline has been running for some time, I may just wait for it to finish and rerun it with the option you suggested. Hopefully FMRIPREP will just start from where it stopped last (as NiPype is able to).

I totally understand about catching up with NiPype, and I was faced with the same problem. I ended up developing a parallel version and submitting PRs at the same time for the functionalities in "base NiPype" to match the ones of my own project. Luckily the NiPype developers were amazingly fast to integrate everything but that was also because my PRs were pretty simple...

Thanks again for all the help, that was very useful. If i can't debug myself what these crashes are all about (from the proper `txt` files), I will create a separate issue.

**Comment by effigies** [comment]
Just so you know, if you didn't put a pre-computed FreeSurfer subject directory in the output folder (see [Surface preprocessing](https://fmriprep.readthedocs.io/en/0.6.0/workflows.html#surface-preprocessing)), it will be running `recon-all` for several hours.

From the names of your crash files, it looks like the failure was in the functional pipeline. If you want to get a jump on it while FreeSurfer is running, you could make new output and scratch directories, and run with `--no-freesurfer --output-space T1w`.

**Comment by mick-d** [comment]
Fantastic tip, many thanks for this!

**Comment by effigies** [comment]
Oh, I see the issue. You're using `--use-aroma` and `--output-space fsnative`. You need to add "template" to the `output-space` list, because AROMA requires its inputs in MNI template space.

This should have produced an error and told you the problem. I'll check the logic and make sure it does this for the next release. Please leave the issue open, and I'll close it when it's fixed.

**Comment by mick-d** [comment]
Thanks a lot. So the argument to `output-space` can be a list? Simply indicating `--output-space fsnative,template` should work then?

**Comment by effigies** [comment]
Use spaces rather than commas, but yes.


-------- Original message --------

**Comment by mick-d** [comment]
Ok will do (with also `--template MNI152NLin2009cAsym` from what I understand) and get back to you. Thank you!

**Comment by effigies** [comment]
You don't need to specify `--template`, as that's the default. (At present, there are no alternatives, but we put in that option preemptively, because we've had at least one user interested in alternative templates.)

**Comment by mick-d** [comment]
A belated confirmation that your suggestions indeed solved the issue. Thanks again.
