### ISSUE TITLE
Show subject ID and some other details in report summary

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#639]
Report the subject ID and number of tasks, and runs per task on the summary.

**Comment by effigies** [comment]
Right now we have (e.g.):

-----

# Anatomical
## Summary
* Structural images: 2
* FreeSurfer reconstruction: Not run
* Output spaces: MNI152NLin2009cAsym
## Anatomical Conformation
* Input T1w images: 2
* Output orientation: RAS
* Output dimensions: 256x256x256
* Output voxel size: 1mm x 1mm x 1mm
* Discarded images: 0

-----

Adding subject ID would be no problem, but adding number of tasks/runs would require functional information, and no longer fit under the **Anatomical** heading. How about the following:

-----

# Summary
* Subject ID: sub-02
* Structural images: 2 T1-weighted + 1 T2-weighted
* FreeSurfer reconstruction: Not run
* BOLD series
  * Task: fingerfootlips (1 run)
  * Task: covertverbgeneration (1 run)
* Output spaces: MNI152NLin2009cAsym, T1w

# Anatomical
## Conformation
* Input T1w images: 2
* Output orientation: RAS
* Output dimensions: 256x256x256
* Output voxel size: 1mm x 1mm x 1mm
* Discarded images: 0

----

Or should some of it be kept under anatomical? I just don't want to clutter up with too many headings.

**Comment by oesteban** [comment]
+1 to stripping the summary from anatomical and moving it over to the top.
