### ISSUE TITLE
script on sleep mode

### ISSUE THREAD

**Issue by yidilozdemir** [poldracklab/fmriprep#644]
Hello everyone,

When I am trying to run the script fmriprep-docker the terminal does not show anything. When I do ps -au I see that the script is sort of in a sleep mode*? This probably is a problem pertaining to my computer but I was hoping someone would help me understand it.

When I tried to kill the script previously, the system did not recognize its ID. I tried to do debug but couldn't figure it out. 

*lab      21067  0.0  0.1  22680  5240 pts/18   Ss   12:17   0:00 bash
root     21089  0.0  0.1  55032  4056 pts/18   S+   12:18   0:00 sudo fmriprep-d
root     21090  1.9  0.5  58252 22672 pts/18   S+   12:18   0:00 /usr/bin/python
root     21102  0.1  0.4 528616 17000 pts/18   Sl+  12:18   0:00 docker run --rm
lab      21224  0.0  0.0  37368  3372 pts/0    R+   12:18   0:00 ps -au

 Whenever I stop the script by ctrl C, the same "traceback" shows as below so I guess this is where the problem is?

    lab@lab-ThinkStation-E31:~/Desktop/freesurfer$ sudo fmriprep-docker --anat-only /home/lab/Desktop/freesurfer/ds001 /home/lab/Desktop/freesurfer/ds001 participant bash -x ./fmriprep-docker
    [sudo] password for lab:
    ^CTraceback (most recent call last):
      File "/usr/local/bin/fmriprep-docker", line 11, in <module>
        load_entry_point('fmriprep-docker==0.6.0', 'console_scripts', 'fmriprep-docker')()
      File "/usr/local/lib/python2.7/dist-packages/fmriprep_docker.py", line 292, in main
        mem_total = check_memory(opts.image)
      File "/usr/local/lib/python2.7/dist-packages/fmriprep_docker.py", line 118, in check_memory
        stdout=subprocess.PIPE)
      File "/usr/local/lib/python2.7/dist-packages/fmriprep_docker.py", line 74, in _run
        stdout, stderr = proc.communicate()
      File "/usr/lib/python2.7/subprocess.py", line 792, in communicate
        stdout = _eintr_retry_call(self.stdout.read)
      File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
        return func(*args)
    KeyboardInterrupt

Thank you for the help!

**Comment by chrisfilo** [comment]
There are some steps in the pipeline that take a long time with not output
on the terminal (for example 1-2h for skullstripping and normalization).
Are you sure this is not the case?

**Comment by yidilozdemir** [comment]
I ran the script multiple times and it would immediately ask me something like if I am willing to use my docker memory space, then the terminal window would always show what job it's currently doing along with some other stuff.

**Comment by yidilozdemir** [comment]
(I am just doing this to show how unresponsive the script is with sudo-which I need because I have some access issues)
lab@lab-ThinkStation-E31:~/Desktop/freesurfer/ds001$ fmriprep-docker
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.30/images/json?filters=%7B%22reference%22%3A%7B%22poldracklab%2Ffmriprep%3A0.6.0%22%3Atrue%7D%7D: dial unix /var/run/docker.sock: connect: permission denied
usage: fmriprep-docker [-h] [-v] [-i IMG] [-w WORK_DIR]
                       [--output-grid-reference OUTPUT_GRID_REFERENCE]
                       [-f PATH] [-n PATH] [-p PATH] [--shell] [--config PATH]
                       [bids_dir] [output_dir] [{participant}]
(...)
Image 'poldracklab/fmriprep:0.6.0' is missing
Would you like to download? [Y/n] Y
Downloading. This may take a while...
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.30/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
Could not detect memory capacity of Docker container.
Do you have permission to run docker?
lab@lab-ThinkStation-E31:~/Desktop/freesurfer/ds001$ sudo fmriprep-docker


and this does not show anything

**Comment by chrisfilo** [comment]
Maybe you can avoid using sudo by adding your user to docker group?

**Comment by effigies** [comment]
Can you check top (or better, htop), and see if AntsRegistration.sh or some freesurfer tool is running? Your command will run recon-all, unless you have a fully run subject in /home/lab/Desktop/freesurfer/ds001/freesurfer.

**Comment by effigies** [comment]
What version are you running? (Sorry, didn't see last comments when I posted.)

**Comment by yidilozdemir** [comment]
I don't have a fully run subject; my previous recon-all using the script gave some errors in auto segmentation and exited, and I cannot delete that folder because of restrictions.

**Comment by effigies** [comment]
Regarding `sudo fmriprep-docker` not showing anything, it can take a few seconds (~5-20s) to display the help. The reason is that it starts up the docker container to get the original help (this keeps us from having to keep the help for the wrapper and the underlying program in sync). How much time are you giving it?

If you are able to get any output at all, can you add `--nthreads 1 --debug` to your `fmriprep-docker` call? If something runs, it should tell you the name of the node being executed...

**Comment by yidilozdemir** [comment]
It has been 10 minutes and it still is not showing anything. I will add the debug to my command line but I wasn't able to get anything output. I waited for the script for like half an hour, and usually it would give a good amount of output by that time. I am restarting my system again, maybe this will kill any process related to the previous unfinished subject.

Thank you all for the help

**Comment by yidilozdemir** [comment]
Sorry for keeping this thread busy, I restarted the computer to refresh the environments, and it shows the error now:
docker: Error response from daemon: create 1: volume name is too short, names should be at least two alphanumeric characters.
I think it is about my DICOM conversion. 
Thank you!
