### ISSUE TITLE
Update reports to have more flexible name spaces

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#649]
In #647, two new basic reporting derivatives (summarizing data, environment and run parameters) are introduced that are more appropriately associated with the subject than a particular modality.

`DerivativesDataSink` currently [selects the subdirectory](https://github.com/poldracklab/fmriprep/blob/dc99e2493691d413ac810562f2fd5b491bd9e97d/fmriprep/interfaces/bids.py#L172-L180) based on the modality.

Just to make organization match function, we may want to reconsider how to organize derivatives.

**Comment by effigies** [comment]
See https://github.com/poldracklab/fmriprep/pull/647/files#r131662496

**Comment by oesteban** [comment]
I think this has been addressed with the latest refactor of the reports. Please reopen if I'm wrong.
