### ISSUE TITLE
getting "tar: Unexpected EOF in archive" error

### ISSUE THREAD

**Issue by manishsaggar** [poldracklab/fmriprep#653]
Hi all, I am getting the following error when I try to create a Singularity image using the following command. Any ideas why I am getting this error. I tried creating images for other apps (like CPAC) which were made without this or any error. Thanks for any help!

```
$ docker run --privileged -t --rm -v /var/run/docker.sock:/var/run/docker.sock -v /Users/saggar/Singularity:/output singularityware/docker2singularity bids/fmriprep:latest
Size: 15318 MB for the singularity container
(1/9) Creating an empty image...
Creating a sparse image with a maximum size of 15318MiB...
Using given image size of 15318
Formatting image (/sbin/mkfs.ext3)
Done. Image can be found at: /tmp/bids_fmriprep_latest-2017-06-13-7a3a119f98c2.img
(2/9) Importing filesystem...
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

**Comment by chrisfilo** [comment]
It seems that this bug belongs more to https://github.com/singularityware/docker2singularity than here.

Nonetheless - have you tried resetting Docker and trying again?

**Comment by manishsaggar** [comment]
Oops sorry. Thanks complete reset (factory reset) worked. Thanks!
