### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by satra** [poldracklab/fmriprep#658]
- non-visual qa, i.e. automatic flagging
- saving to cifti
- generating conversions with (when available) and without fieldmap correction
- multi-depth sampling of cortical ribbon (so multiple gifti files)
- image similarity metrics (coregistration histogram separability), exposing bbregister mincost as a basic cut-off, distribution variance of ratio of group intersection epi mask to individual epi mask
   - mostly metrics around coregistration, normalization, and artifactual components.

**Comment by effigies** [comment]
@satra, thanks for the input. Below are notes/questions. 

> - non-visual qa
> [...]
> - image similarity metrics (coregistration histogram separability), exposing bbregister mincost as a basic cut-off, distribution variance of ratio of group intersection epi mask to individual epi mask
>   - mostly metrics around coregistration, normalization, and artifactual components.

These two seem related. While mincost is straightforwardly parsed from bbregister, do you have references for the metrics you'd like to use? And to the extent that you have experience with them, do you have thresholds you'd set for flagging, or would you expect to form a distribution across subjects/runs and look for outliers?

We've also been discussing collecting mask volumes (for skull stripping, CSF/WM ROIs, etc.).

Basically, this is something we're actively discussing, and the more concrete the proposal, the more likely we'll implement it or something close to it.

> * saving to CIFTI

This seems reasonable, but out of my experience so far. If you have example code that converts the type of data you'd be interested in, that would be useful. (I assume CIFTI can handle either structural or functional data, as standard NIfTI can...)

> * generating conversions with (when available) and without fieldmap correction

This seems doable and reasonable. We'll need to figure out a naming scheme to indicate fieldmap correction strategy in the filename to avoid collisions, but that seems like a good idea, anyway.

> * multi-depth sampling of cortical ribbon (so multiple gifti files)

This sounds like the trickiest one to implement cleanly, as it basically means somehow exposing fine-tuning of `mri_vol2surf` at the command line or in a configuration file. `mri_vol2surf --reg-header` will get you the GIFTI files, but re-centering them requires a variation on [normalize_surfs](https://github.com/poldracklab/fmriprep/blob/cff630e5f997f510d4e024b13f8e9cb344caa589/fmriprep/interfaces/surf.py#L93-L134).

**Comment by oesteban** [comment]
Hi all, I've dissected this issue in individual feature requests that can be addressed separately. Please feel free of keeping conversation on them (and sorry for the buzzing mentions, I ended up holding off mentioning you).
