### ISSUE TITLE
version not updating

### ISSUE THREAD

**Issue by amhowell2** [poldracklab/fmriprep#673]
I'm trying to run fmriprep on docker. 
The command I'm using is:

docker run -i --rm -v [bidsFolder]/:/bids_dataset:ro -v [outputfolder]:/outputs bids/fmriprep --v /bids_dataset /outputs participant --participant_label [participant ID]

It states that the version I'm using is v0.4.5. I upgraded fmriprep (pip install --user --upgrade fmriprep-docker), and I can see in the location that this creates an up-to-date version of fmriprep in my anaconda folder. However, when I run the docker command it is still using this older version. 

I would like to insert the --use-aroma command, which is not available in v.0.4.5, any recommendation on how I can make the docker version grab the latest version of bids/fmriprep?

**Comment by oesteban** [comment]
Hi @amhowell2, I think you are using the wrong image. Your command should be:

```
docker run -i --rm -v [bidsFolder]/:/bids_dataset:ro -v [outputfolder]:/outputs poldracklab/fmriprep --v /bids_dataset /outputs participant --participant_label [participant ID]
```

please not that I changed `bids/fmriprep` with `poldracklab/fmriprep`. That should download the latest fmriprep release.

**Comment by effigies** [comment]
If you've installed `fmriprep-docker`, use:

```Shell
fmriprep-docker [bidsFolder] [outputFolder] participant --participant_label [participant ID]
```

I believe the source of the confusion is what `pip install --upgrade fmriprep-docker` does. `fmriprep-docker` is a Python wrapper that generates the correct Docker command for you. Installing from pip does not fetch the image; running `fmriprep-docker` will fetch the image, if needed.

**Comment by effigies** [comment]
@amhowell2 was your issue resolved?

**Comment by amhowell2** [comment]
Hiya! Sorry, it was resolved. I used the solution that swaps bids/fmriprep with poldracklab/fmriprep. An alternate solution is you can add :latest to the image name for latest version. For example 

`docker run -i --rm -v [bidsFolder]/:/bids_dataset:ro -v [outputfolder]:/outputs bids/fmriprep:latest --v /bids_dataset /outputs participant --participant_label [participant ID]`
