### ISSUE TITLE
Re-enable AFNI skull-strip flag

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#676]
When https://github.com/poldracklab/niworkflows/issues/194 is fixed.

**Comment by effigies** [comment]
Has anybody actually complained about not having AFNI skull-stripping? My impression was we were only using it to speed up test runs, and we stopped doing that a while ago.

**Comment by oesteban** [comment]
I think we can dismiss AFNI's skullstripping at all.

**Comment by chrisfilo** [comment]
+1
