### ISSUE TITLE
Fall-back registration for BBR failures

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#681]
Original report: https://neurostars.org/t/strange-epi-to-t1w-registration-result/696

Summary: In cases of low gray/white tissue contrast in BOLD series, the default, 9-dof boundary-based registration (BBR) to T1w space can result in noticeable failures. Using the initial transform (vanilla FLIRT for FSL, mri_coreg for bbregister) can reduce the distortion.

cc @chrisfilo @oesteban @jdkent

**Comment by effigies** [comment]
@chrisfilo [wrote](https://neurostars.org/t/strange-epi-to-t1w-registration-result/696/8):

> do you think there would be a reliable way to automatically decided based on the input data whether or not to use BBR on a case by case basis?

If we operate on the assumption that the first pass will be pretty good, and BBR should only induce minor tweaks, we could set a number of thresholds on things like:

1) Difference in translation from initial transform to BBR transform
2) Difference in scale factors from init to BBR
3) Max BBR cost

If the threshold is passed, we could simply grab the initial transform.

**Comment by chrisfilo** [comment]
Another option is to look at the difference in overlap of T1w and BOLD
masks before and after BBR.

**Comment by effigies** [comment]
I'm assuming this is something we're trying to get in for 1.0.0?

**Comment by chrisfilo** [comment]
I think it would be worthwhile. Even though this is the first time we are
seeing such problems, I have a sense it will happen more often (especially
with legacy data).

**Comment by effigies** [comment]
This issue has been replicated in ds000108, as well.

**Comment by oesteban** [comment]
Waiting for #743 to get in since there'll be conflicts.
