### ISSUE TITLE
getting "too many levels of symbolic links" error

### ISSUE THREAD

**Issue by manishsaggar** [poldracklab/fmriprep#682]
Trying to run fmriprep using Singularity on Sherlock and getting the "Too many levels of symbolic links" error. Not sure why? any help!

Version of the poldracklab/fmriprep image [made today] - poldracklab_fmriprep_latest-2017-08-12-b143b2240628.img

Running BIDS format data in Scratch space at Sherlock, using the following command,
`singularity run -B /scratch/PI/saggar/BIDS-bidskit:/data:ro -B /scratch/PI/saggar/BIDS-bidskit-output:/out poldracklab_fmriprep_latest-2017-08-12-b143b2240628.img /data /out/out participant --participant-label 10s1 --use-aroma --skull-strip-ants --no-freesurfer --no-submm-recon
`
Error:
ERROR  : There was an error binding the path /share/PI: Too many levels of symbolic links
ABORT  : Retval = 255

**Comment by effigies** [comment]
Repeatedly submitting until it works is how I've dealt with that. It seems to be a Sherlock error. I don't know if it's stochastic or if some nodes can't handle singularity.

**Comment by vsoch** [comment]
also reported here: https://github.com/singularityware/singularity/issues/890 I think it has to do with https://github.com/singularityware/singularity/issues/757 so workarounds would involve disabling the automatic mounting, possibly by way of mounting the location somewhere else. I would also want to check `LD_LIBRARY_PATH` and `PYTHONPATH` to make sure they aren't being changed and appended with some repeated link each time (although this probably would be a different error)

**Comment by cclerget** [comment]
A fix has been merged in dev branch.

A configuration directive "autofs bug path" has been added where you can specify autofs mount point generating "too many levels of symbolic links" errors.

Example for your case, add to singularity.conf to fix error :
autofs bug path = /scratch/PI

**Comment by effigies** [comment]
Closing here, as this seems to be a singularity issue. Please reopen if it turns out we need to fix something on our end.

**Comment by manishsaggar** [comment]
Thanks, all. Quick update - I was able to run the job successfully using Sherlock 2.0 (instead of originally failing to run on Sherlock 1.0).
I will try the updated (autofs bug path) version as well.
