### ISSUE TITLE
Minor nit with documentation on creating Singularity container

### ISSUE THREAD

**Issue by crhamilt** [poldracklab/fmriprep#685]
In the docs for creating a Singularity container on readthedocs.io, the docker run command  has an argument "-v D:\host\path\where\to\output\singularity\image:/output" that really threw me for a while.  It took me a while to realize a Windows path was being used as an example (I'm a Unix guy and I bet many users are.)  I suggest changing it to "-v host_path_to_write_image:/output".  I kept trying to keep the D: in there, thinking it was necessary.

Very minor nit, but it cost this dunce a lot of time....

Thanks

**Comment by oesteban** [comment]
We'll take this into account and provide with the Unix counterpart.
