### ISSUE TITLE
How to optimize EPI to T1 registration in fmriprep when no fieldmaps are available?

### ISSUE THREAD

**Issue by mick-d** [poldracklab/fmriprep#689]
What parameters should be chosen to obtain the best T1 <-> EPI registration performance when no field maps are available? 

When running `fmriprep` with the parameters below, the registration was poor in frontal and temporal areas in all subjects, as expected from the lack of field maps for susceptibility distortion correction (cf subsequent image). I assume this would then lead to less than adequate estimation of connectivity matrices, as some grey-matter regions would then be outside the brain. Would there be any tip on using `fmriprep` to mitigate this effect and obtain usable connectivity matrices?
```
Functional
Reports for Task: rest
Summary
Slice timing correction: Applied
Susceptibility distortion correction: None
Registration: FreeSurfer boundary-based registration (bbregister)
Functional series resampled to spaces: fsnative, template
Confounds collected: Global signals, DVARS, Framewise displacement, tCompCor, aCompCor, Motion parameters, ICA-AROMA
```

![subj09](https://user-images.githubusercontent.com/4580257/30065302-a0b891a4-9254-11e7-9c52-3935d055311e.png)

**Comment by effigies** [comment]
@mick-d We do have an experimental feature that uses a fieldmap template and non-linear registration along the phase-encoding direction to approximate fieldmap correction. This can be activated with `--use-syn-sdc`.

If the phase-encoding direction is not encoded in the JSON metadata, then it will be estimated for both L-R and A-P directions, and the result that reduces the registration cost will be chosen.

**Comment by mick-d** [comment]
Thank you @effigies. From reading the documentation, the fastest way, would then be to use both the `--use-syn-sdc` and `--no-freesurfer` flags to avoid recomputing the Freesurfer output, is that right?

Furthermore, when looking at the [example](http://fmriprep.readthedocs.io/en/stable/_images/EPIT1Normalization.svg) of EPI to T1 registration results in the `fmriprep` documentation, similar problems can be seen (e.g. y=12 and z=0/13). Does that mean that even if temporal and frontal pole regions have low/no signal, it is acceptable to calculate the connectivity matrices from this kind of preprocessed data?

**Comment by effigies** [comment]
If you've already computed the FreeSurfer outputs, you can make sure there is a `freesurfer/` directory in your output directory, and fmriprep will reuse it. But yes, to avoid using FreeSurfer, you can use `--no-freesurfer`.

As to acceptability, that's going to depend on your reviewers and what are considered standard steps in your particular subfield. In my experience, failing to perform SDC is fairly common, and nonlinear registration of EPI to T1 is not considered mandatory, but the understanding is then that you do have essentially no signal at the temporal and frontal poles. It's worth distinguishing between distortion and signal drop-off, though, as distortion can be partially corrected with spatial warping, while drop-off means any signal "restoration" is simply interpolation from mostly-unrelated data. So, in any event, I would be very cautious when reporting results in these areas, under any correction scheme.

**Comment by mick-d** [comment]
Excellent, thank you @effigies for the useful feedback.
