### ISSUE TITLE
Question: run.py __name__ == '__main__'

### ISSUE THREAD

**Issue by jdkent** [poldracklab/fmriprep#691]
This is a non-consequential question, but what is the purpose of adding __name__ == '__main__' in the [run.py](https://github.com/poldracklab/fmriprep/blob/master/fmriprep/cli/run.py#L336). When calling run.py as an executable it doesn't know if it's contained within a package making it incompatible with the [relative import used](https://github.com/poldracklab/fmriprep/blob/master/fmriprep/cli/run.py#L19).  This was only an issue for me when I was trying to test my own run.py and thought it could be run as an executable, but (eventually) realized that it could not be. 

Is there another reason run.py has the ```__name__ == '__main__'```?

**Comment by oesteban** [comment]
You are right, we probably want to raise an exception there so that the script is not called directly and forcing the users to use the `fmriprep` script installed at setup time.
