### ISSUE TITLE
3dTshift error: ignore value 0 is too large

### ISSUE THREAD

**Issue by jokedurnez** [poldracklab/fmriprep#696]
Ran into [this issue](https://github.com/preprocessed-connectomes-project/quality-assessment-protocol/issues/58) that was also reported for QAP:
```
RuntimeError: Command:
3dTshift -ignore 0 -prefix sub-A00035699_ses-DS2_task-rest_acq-1400_bold_tshift.nii.gz -tpattern @/scratch/users/jdurnez/NKI/fmriprep_wf/single_subject_A00035699_wf/func_preproc_ses_DS2_task_rest_acq_1400_wf/epi_hmc_wf/create_custom_slice_timing_file/timings.1D -TR 1.4s /scratch/users/jdurnez/NKI/fmriprep_wf/s
ingle_subject_A00035699_wf/func_preproc_ses_DS2_task_rest_acq_1400_wf/epi_hmc_wf/slice_timing_correction/sub-A00035699_ses-DS2_task-rest_acq-1400_bold.nii.gz
Standard output:

Standard error:
++ 3dTshift: AFNI version=Debian-16.2.07~dfsg.1-5~nd16.04+1 (Jun 12 2017) [64-bit]
** FATAL ERROR: -ignore value 0 is too large
** Program compile date = Jun 12 2017

Return code: 1
Interface TShift failed to run.
```
Seems to be an issue with AFNI (value 0 is the default).  I'll re-run and see if the error reproduces.

**Comment by chrisfilo** [comment]
Thanks for reporting.

We should set this property only if it's different from 0.

**Comment by effigies** [comment]
Can you run `nib-ls /scratch/users/jdurnez/NKI/fmriprep_wf/single_subject_A00035699_wf/func_preproc_ses_DS2_task_rest_acq_1400_wf/epi_hmc_wf/slice_timing_correction/sub-A00035699_ses-DS2_task-rest_acq-1400_bold.nii.gz`? It looks like it has < 5 time points, judging by the [code that issues this error](https://github.com/afni/afni/blob/0fc35c882ea7a5f2c7900d72d9534f6248a36dd5/src/3dTshift.c#L362).

**Comment by jokedurnez** [comment]
Oh yeah, you're right :-)  Thanks !

```
[jdurnez@sh-0-31 /oak/stanford/groups/russpold/data/NKI_preprocessed_0.5.3/fmriprep/fmriprep]$ nib-ls /scratch/users/jdurnez/NKI/fmriprep_wf/single_subject_A00035699_wf/func_preproc_ses_DS2_task_rest_acq_1400_wf/epi_hmc_wf/slice_timing_correction/sub-A00035699_ses-DS2_task-rest_acq-1400_bold.nii.gz
/scratch/users/jdurnez/NKI/fmriprep_wf/single_subject_A00035699_wf/func_preproc_ses_DS2_task_rest_acq_1400_wf/epi_hmc_wf/slice_timing_correction/sub-A00035699_ses-DS2_task-rest_acq-1400_bold.nii.gz int16 [112, 112,  64,   3] 2.00x2.00x2.00x1.40  #exts: 1
```

**Comment by effigies** [comment]
@chrisfilo It may be worth disabling Tshift on time series with < 5 time points, since that's a hard limit set by AFNI.

**Comment by chrisfilo** [comment]
+1
