### ISSUE TITLE
Misaligned contours in SyN-SDC reports

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#708]
SyN-SDC reports sometimes do not align with the BOLD image:

![sdc_contours](https://user-images.githubusercontent.com/83442/30550461-7f1c5920-9c65-11e7-97cb-0c6151bf8d19.png)

Observed in:

* ds000006
* ds000101 (sub-06)
* ds000102

In some cases, only some runs are affected.

**Comment by oesteban** [comment]
This is very likely to be related to #710.

I'll check it on those datasets and report back here.

**Comment by oesteban** [comment]
In principle, closed via #743. I'll reopen if this persists after running on ds006 and ds102.

**Comment by oesteban** [comment]
Confirmed this is not happening anymore on ds101 or ds102 either.
