### ISSUE TITLE
Handle missing magnitude2.nii(.gz) files

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#709]
See https://neurostars.org/t/fmriprep-fieldmap-phasediff-error-file-magnitude2-not-found/712

If we can support distortion correction without `magnitude2.nii`, we should. If it's the case that we might get `magnitude1.nii` files with two volumes, we should handle that case, as well. And if we don't have enough data to perform distortion correction, we should note that in the summary and not crash.

**Comment by chrisfilo** [comment]
There is one more report on NeuroStars https://neurostars.org/t/fmriprep-field-mapping-data/755/5

**Comment by roniiw** [comment]
I have encountered the same issue,
I tried duplicating the magnitude file as suggested here- https://neurostars.org/t/fmriprep-fieldmap-phasediff-error-file-magnitude2-not-found/712/3, but that didn't work.

The output of nib-ls  is - int16 [106, 106,  33,   2] 2.00x2.00x4.80x0.40   sform

I'm also attaching the error log
[59f1dfe38b4b240001c5a661.txt](https://github.com/poldracklab/fmriprep/files/1419994/59f1dfe38b4b240001c5a661.txt)
