### ISSUE TITLE
Add excerpts of how to cite fmriprep *AND* dependencies

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#713]
Meanwhile we can't implement this in a dynamic fashion with duecredit, we need to credit the authors of the huge amounts of software that fmriprep uses.

Update the documentation with these literate descriptions of references.

**Comment by effigies** [comment]
If there isn't already such a list, we can use this comment to build a running list of tools and citations, when available.

| Tool | Link to code | Citation(s) |
|-----|-----|-----|
| recon-all | | https://doi.org/10.1006/nimg.1998.0395 |
| bbregister | | |
| mri_robust_template | | |

**Comment by oesteban** [comment]
Great idea. I escalated it to a wiki entry: https://github.com/poldracklab/fmriprep/wiki/Software-references

**Comment by chrisfilo** [comment]
Great move turning this into a wiki!

**Comment by effigies** [comment]
Okay, I think the wiki page is complete.

**Comment by oesteban** [comment]
WOW

**Comment by oesteban** [comment]
I was thinking about this:

1. Move the table to an rst file in `/REFERENCES.rst` in the repo.
2. Replace the wiki with a call to include this file (I'm guessing this is possible, but haven't tried though).
3. When fmriprep finishes, print the excerpt selecting the appropriate rows from the table in the `/REFERENCES.rst` file.

WDYT?

**Comment by effigies** [comment]
I think that could be reasonable... I'm not sure how non-trivial it will be to grab the table rows you want.

**Comment by effigies** [comment]
But we could annotate it as "This tool is only used if you use phdiff fieldmaps", etc. Because most tools will be hit by anatomical and bold. ICA-AROMA has a flag, so that's easy. And there are a couple things that will get excluded/included if STC or FreeSurfer get turned off, or fieldmaps on.

**Comment by chrisfilo** [comment]
We need something that is a) well exposed (so part of the website) b) easy to include in the paper (so a whole paragraph that someone can copy, paste and optionally adjust. I'm afraid that if we just provide a list of papers to cite most people will not use it.

**Comment by chrisfilo** [comment]
https://github.com/ANTsX/ANTs#boilerplate-ants
