### ISSUE TITLE
SyN-SDC guessed phase encoding incorrectly

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#714]
ds000243 sub-042 task-rest_run-2

Correction was attempted in L/R but should've been in A/P.

**Comment by chrisfilo** [comment]
Same with sub-032_task-rest_run-1

**Comment by effigies** [comment]
In case it occurs to anybody else to check, the tissue contrast looks fine, so it's not just bad BBR.

**Comment by effigies** [comment]
Following discussion, the fix to this issue cropping up for users will almost always be "label the data with the correct PE direction".

That said, we may be able to get a better heuristic. Two possibilities:

1) LR phase encoding will produce higher LR asymmetry, so we may be able to use an asymmetry measure to decide PE before running SyN-SDC.
2) There is a fairly strong AP prior probability, so we may want to require LR to out-perform AP by some threshold to reject the AP assumption.

**Comment by oesteban** [comment]
> LR phase encoding will produce higher LR asymmetry
I'm not sure of this. If the head has some tilt to the left or right, it will be pretty asymmetric.

> There is a fairly strong AP prior probability
This is true, specially because guessing the PE direction would (ideally) only be needed for legacy datasets which lost that info along the way.

Having said that, maybe worth just spitting a WARNING with the one we have of the EXPERIMENTAL and ask the user to define the PE direction. Otherwise, we assume AP and save a lot of computing.

WDYT?

**Comment by effigies** [comment]
> > LR phase encoding will produce higher LR asymmetry
> I'm not sure of this. If the head has some tilt to the left or right, it will be pretty asymmetric.

I think the idea is that we would need to find the midline anyway, and then test for asymmetry across that.

As to the rest, warning on undefined and assuming AP sounds like a pretty reasonable to build the prior in. Certainly low-cost. :-)

**Comment by oesteban** [comment]
> I think the idea is that we would need to find the midline anyway, and then test for asymmetry across that.

Right, and on that basis I don't see why AP would be more symmetric than LR, unless the interhemispheric plane was perfectly aligned with the sagittal plane of the scanner.
