### ISSUE TITLE
ICA AROMA misclassifications 

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#715]
ICA AROMA sometimes classifies components in a way that one might argue is incorrect (judging from their spatial distribution). This could be intrinsic to ICA AROMA itself (imperfection of the classifier), but it might be worth checking if there is no funny business with the orientation of input files and templates used by ICA AROMA.

From ds000243/reportlets/fmriprep/sub-032/func/sub-032_task-rest_run-1_bold_ica_aroma.svg
![image](https://user-images.githubusercontent.com/238759/30618571-ee84d478-9d4f-11e7-94a3-50de3de7a230.png)
![image](https://user-images.githubusercontent.com/238759/30618590-fbb68a42-9d4f-11e7-9d6a-4ffa50118b89.png)

From ds000243/reportlets/fmriprep/sub-042/func/sub-042_task-rest_run-2_bold_ica_aroma.svg:
![image](https://user-images.githubusercontent.com/238759/30618619-191149ba-9d50-11e7-9857-fb5fe1157fb4.png)

**Comment by oesteban** [comment]
From your expert point of view, what could be the fix for this?

**Comment by chrisfilo** [comment]
This could be intrinsic to ICA AROMA itself (imperfection of the classifier), but it might be worth checking if there are no issues with the orientation of input files and templates used by ICA AROMA.

**Comment by chrisfilo** [comment]
I discussed this with @maartenmennes:

- The first two examples (classified as noise) is something that you would expect from ICA AROMA since the spatial pattern is close to the edge of the brain.
- The third example (classified as signal) is also something that should be expected since ICA AROMA was trained to deal with motion related noise - not the physiological artefacts.
- It would be good to add another ICA step (with visualization) - run on the nonaggressive outputs of ICA AROMA. This would help to show if the denoising preserved mayor brain networks.

I would still double check if the brain edge and tissue class maps included in ICA AROMA still overlap well with data we feed into it (and there is no funny business going on with headers).

**Comment by maartenmennes** [comment]
Just to clarify: the first two examples are not necessarily misclassifications by ICA-AROMA. Obviously, there are going to be components where everybody agrees (including the classifier) that they are noise. On the other side you will have components that will cast a bit more doubt regarding their nature. The first two could be examples of that.

Yes, the look like motor components, but their spatial pattern is very edge-related (or cortex specific depending on your point of view). My guess is that AROMA classified these based on the combination of correlation with the motion parameters and the edge fraction. See the LDA feature, the left graph in Figure 2 of the AROMA paper. In fact, that figure actually illustrates a couple of potential 'misclassifications'.

**Comment by oesteban** [comment]
I think it is safe to close the question after a long time inactive. Please feel free to reopen if appropriate.
