### ISSUE TITLE
SyN-SDC sometimes performs much worse than you would expect from fieldmaps

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#718]
ds000237/reportlets/fmriprep/sub-03/func/sub-03_task-MemorySpan_acq-multiband_run-02

![image](https://user-images.githubusercontent.com/238759/30619367-d96e7efa-9d53-11e7-8323-1294da73b18e.png)

**Comment by oesteban** [comment]
The contrast of this image is pretty poor, it reminds me of #735. Even though SyN should be more robust against this problem, I would also assign this to "Future". Feel free to revert this decision (maybe place it within a Phase II milestone) but I think this should not hold us up anymore.
