### ISSUE TITLE
request for output-space option of functional data in T1w coordinates with original scanning resolution

### ISSUE THREAD

**Issue by psadil** [poldracklab/fmriprep#722]
This came from a question [asked on neurostars](https://neurostars.org/t/why-are-functional-data-files-output-by-fmriprep-in-t1w-space-so-much-larger/796/2). I'm running some participant-specific analyses. An extra output-space option at the resolution of the original BOLD image would be helpful, partially because of their reduced filesize but mainly because I'm trying out a participant-level analysis that would require that resolution.

thanks

**Comment by effigies** [comment]
This seems reasonable to me. By the [derivatives specification proposal](https://docs.google.com/document/d/1Wwc4A6Mow4ZPPszDIWfCUCRNstn7d_zzaWPcfcHmgI4/edit#), I believe T1w would still be the correct space, but we might need to add resolution information.

It's not clear to me why anybody would want to upsample BOLD to T1w resolution, and not simply resample to be aligned. Perhaps the correct move would be just change the default target resolution.

cc @chrisfilo @oesteban

**Comment by effigies** [comment]
Looking into this, we find that we are outputting at the original scanning resolution (at least in our tests), but we are saving as 32-bit floats. Your original inputs may be 16-bit integers. You can check the resolution and data types on your inputs and derivatives with `nib-ls`.

I believe we made a decision to use `float32` for uniformity of outputs, but if file size is a major issue, we may be able to add an `--orig-dtype` flag (or similar) to ensure that derivatives have the same datatype as their corresponding inputs, as well.

**Comment by effigies** [comment]
Would you be willing to share your preprocessed anatomical (defaced, naturally) and a subsequence of your preprocessed BOLD series in MNI and T1w space? (e.g. `fslroi <in> <out> 0 20`) I'd just like to have a look to see if I can figure out what's causing this.

In datasets I'm looking at, I see nothing like the ratios you're describing (5:2 T1w:MNI). The biggest difference I'm seeing is actually in the opposite direction (2:3 T1w:MNI).

**Comment by chrisfilo** [comment]
The latest comment on NeuroStars suggest it is indeed a field of view issue. One suggestion solution I can think of is the following modification of the T1w reg workflow

1. Take native bold space brain mask and fill it all with ones.
2. Apply transformations to T1w space as usual, but use NN interpolation.
3. Use nilearn cropping function on the output of that operation.
4. This becomes the new reference image with voxels size and field of view preserved.

**Comment by psadil** [comment]
Would you still want the images?

**Comment by effigies** [comment]
Yeah, I am curious to have a look at these.

**Comment by psadil** [comment]
Okay, I just sent you an email with links to download them.
