### ISSUE TITLE
Remove afni_vcheck from container?

### ISSUE THREAD

**Issue by feilong** [poldracklab/fmriprep#724]
It seems `afni_vcheck` will run at least once somehow during creating a single subject pipeline, which can be really annoying when `https://afni.nimh.nih.gov/pub/dist/AFNI.version` doesn't response.  In my case, the whole computing cluster waited for hours before any real job started running.  This version check is unnecessary for containers, because the AFNI version is already specified in the Dockerfile, and we don't expect to upgrade AFNI during running `fmriprep` even if a newer version is available.

I removed `/usr/lib/afni/bin/afni_vcheck` in my image and that fixed this problem (with an additional warning though).

**Comment by effigies** [comment]
This is being resolved in nipy/nipype#2196 and #723.

**Comment by feilong** [comment]
Great!
