### ISSUE TITLE
ds000232 registration issues

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#734]
sub-02/ses-01/func/sub-02_ses-01_task-localizer_run-01

![image](https://user-images.githubusercontent.com/238759/31092600-d06c173a-a763-11e7-82a4-5799c648b38a.png)

Could be related to #681

**Comment by oesteban** [comment]
This is fixed via #694.

Now, the report says:

"mri_coreg (FreeSurfer) was used to generate transformations from EPI space to T1 Space - bbregister refinement rejected"

And the registration looks a lot better.
