### ISSUE TITLE
Proposal: Move to FreeSurfer to generate T1w space

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#736]
The issues with moving between FMRIPREP-conformed space and FreeSurfer-conformed space have surfaced a number of times, so it's worth revisiting whether we simply want to permit FreeSurfer to generate our T1w space. In this case, we would begin by running `recon-all -autorecon1 -noskullstrip` (or accept a pre-run FreeSurfer directory), and pick up the rest of our workflow at skull-stripping.

Pros:
- Very little change for FMRIPREP-run FreeSurfer
- Will dramatically reduce friction when moving between FMRIPREP derivatives and FreeSurfer tools when using a previously run FreeSurfer directory

Cons:
- C_RAS coordinate translation throws off non-FreeSurfer utils
- Reslices to isotropic voxels
- Requires all input T1w images to have the same dimensions (performs reslicing after merging)
- Lower reproducibility - FMRIPREP T1w space depends on whether FreeSurfer was pre-run
- Incompatible with previously run FMRIPREP derivatives?

The coordinate translation may be addressable; we've run a C_RAS update step on the surfaces to make them work with HCP and FreeSurfer equally well. The same may be possible with volumes.

Pre-conforming inputs is something we already do -- it just means that we have a layer between the initial T1w images and FreeSurfer, which may reduce some of the appeal of trying to use FreeSurfer as our first pass.

I think the last two are probably the most serious concerns I have. What do people think? And any other arguments for/against?

**Comment by oesteban** [comment]
How stale is this proposal after all the many changes we have merged lately?

**Comment by effigies** [comment]
Stale in the sense that there's a fair bit of work we've recently done that we'd end up throwing away going in this direction, and that the work we've done recently was judged (in advance) to be less work than reorienting around FreeSurfer. But it is still an open question of philosophy.

**Comment by oesteban** [comment]
Okay, let's have it open to remind us to think about this.
