### ISSUE TITLE
Average field maps across tasks and runs

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#747]
A way to make field maps more robust would be averaging (or better calculating the mode) of all fieldmaps, regardless the estimation procedure.

**Comment by oesteban** [comment]
Related to #718

**Comment by chrisfilo** [comment]
> A mean field map was generated based on the field maps collected in each subject (Laumann et al., 2015). This mean field map was then applied to all sessions for distortion correction. To generate the mean field map the following procedure was used: (1) Field map magnitude images were mutually co-registered. (2) Transforms between all sessions were resolved. Transform resolution reconstructs the n-1 transforms between all images using the n,(n-1)/2 computed transform pairs. (3) The resolved transforms were applied to generate a mean magnitude image. (4) The mean magnitude image was registered to an atlas representative template. (5) Individual session magnitude image to atlas space transforms were computed by composing the session-to-mean and meanto-atlas transforms. (6) Phase images were then transformed to atlas space using the composed transforms, and a mean phase image in atlas space was computed.

http://www.cell.com/neuron/pdfExtended/S0896-6273(17)30613-X
