### ISSUE TITLE
Make sure ComputeDVARS get the appropriate mask

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#751]
After merging #743 we have:
https://320-53608443-gh.circle-artifacts.com/0/home/ubuntu/ds054/out/fmriprep/sub-100185.html

**Comment by oesteban** [comment]
Oh wait, is that the fake error we introduced to check that errors are actually included in the report?

**Comment by effigies** [comment]
Yup. Check the timestamp in the filename:

/out/fmriprep/sub-100185/log/20171011-011937_b1e41dbc-a9df-45a8-b541-e0b7897ca010/crash-**20170905**-182839-root-dvars-b78e9ea8-e295-48a1-af71-2d36afd9cebf.txt
