### ISSUE TITLE
Contours in report missing for BBR fallback

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#758]
When BBR is rejected, the message "mri_coreg (FreeSurfer) was used to generate transformations from EPI space to T1 Space - bbregister refinement rejected" is correctly printed, but the surfaces in the report are missing.

**Comment by effigies** [comment]
So they should be there? That's no problem. Quick fix in niworkflows is to add a line like this:

https://github.com/poldracklab/niworkflows/blob/a216dbab443c57ec9f19d633e782c84b8271270a/niworkflows/interfaces/registration.py#L207

To `MRICoregRPT._post_run_hook()`.

**Comment by oesteban** [comment]
I think so, they are very useful to guide your eye, and particularly important on images with reduced FoV where you have little to no reference without them

**Comment by danlurie** [comment]
I am still seeing this issue when running via fmriprep 1.0.8 via Singularity. I've attached an example.
![sub-a00028995_ses-ds2_task-rest_acq-645_bold_flirt_svg](https://user-images.githubusercontent.com/1873103/37925277-fdedea76-30e8-11e8-9162-b5f6f6326287.jpg)

**Comment by effigies** [comment]
This is a FLIRT reportlet, which at the moment doesn't have access to the white matter segmentation unless it's run in BBR mode.

I agree we probably should include these, if we are doing so for `mri_coreg`.
