### ISSUE TITLE
No final output report and no obvious crash/warning/error

### ISSUE THREAD

**Issue by doritdorit** [poldracklab/fmriprep#760]
Hi,
when running fmriprep in a singularity container on a SGE-cluster the final output html report sub-<subject_label>.html in <out_dir>/fmriprep/ is missing.  There is no log folder in outdir/fmriprep/sub-{subject}  and the log folder in <out_dir>/ is empty too.

Cluster-output doesn't show anything obviously funny in terms of errors or warning.

Same data (subject) created an report html on a bare metal installation of fmriprep on a mac os x. Only obvious difference was that it created acomp and tcomp outputs, which are missing for the problematic case described above.

Checked a bunch of files and reports in the work directory but couldn't find something hinting towards a crash/error (but new to fmriprep so possibly not looking in the right places). 

Any ideas or suggestions for pointers where to look for hidden/silent error messages?

Let me know if I miss some crucial information here that would be helpful to understand/solve the issue.

Thanks!

_singularity container used:_
poldracklab_fmriprep_latest-2017-08-28-12cf5348d2f5.img

_command used to run fmriprep:_
singularity exec ${fmriprep_img} fmriprep --participant_label  ${sid} --debug --no-freesurfer --ignore-aroma-denoising-errors ${src_dir} ${out_dir} --ignore slicetiming --output-space T1w -w ${work_dir} participant"

**Comment by doritdorit** [comment]
OK - found the issue. Not at all fmriprep related. 
It produced the report just fine when running same subject with --ignore fieldmaps. However when calling fmriprep _without_ ignoring fieldmaps it produced some of the fieldmap files (and respective sub-reports). 
Turns out the SGE-cluster needed more threads to finish the job. Et voila, final output report produced :)

**Comment by chrisfilo** [comment]
Glad to hear all ended well. Thanks for reporting the solution.

**Comment by doritdorit** [comment]
sure thing!
