### ISSUE TITLE
OSError: Duplicate node name "func_preproc_task_mag_run_01_wf" found.

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#769]
This weird error happened twice, one for ds000223 and another for ds000237. It is a bit surprising that both times happened for run-01 and the other parameterizations do not seem to avoid the naming conflict (particularly, the subject id).

The error does not generate crashfile.

```
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.0.0rc6', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 216, in main
    create_workflow(opts)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 326, in create_workflow
    ignore_aroma_err=opts.ignore_aroma_denoising_errors,
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 194, in init_fmriprep_wf
    ignore_aroma_err=ignore_aroma_err)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 450, in init_single_subject_wf
    ('outputnode.t1_2_mni_reverse_transform', 'inputnode.t1_2_mni_reverse_transform')])
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 176, in connect
    self._check_nodes(newnodes)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 712, in _check_nodes
    raise IOError('Duplicate node name "%s" found.' % node.name)
OSError: Duplicate node name "func_preproc_task_mag_run_01_wf" found.
```

**Comment by effigies** [comment]
Did it happen every time the same command was run? Do you have the command?

**Comment by oesteban** [comment]
Command lines:

```
singularity run /work/03843/crn_plab/singularity/poldracklab_fmriprep_1.0.0-rc6-2017-10-11-b62eaef1811b.img /work/03843/crn_plab/stampede2/fmriprep-phase2/data/openfmri/ds000223 out/ds000223 participant -w wor
k/ds000223 --participant_label 01 19 04 15 --mem-mb 64000 --nthreads 24 --omp-nthreads 8 --force-syn
```

```
singularity run /work/03843/crn_plab/singularity/poldracklab_fmriprep_1.0.0-rc6-2017-10-11-b62eaef1811b.img /work/03843/crn_plab/stampede2/fmriprep-phase2/data/openfmri/ds000237 out/ds000237 participant -w wor
k/ds000237 --participant_label 12 03 08 11 --mem-mb 64000 --nthreads 24 --omp-nthreads 8 --force-syn
```

**Comment by effigies** [comment]
This is on ls5?

**Comment by oesteban** [comment]
yup

**Comment by oesteban** [comment]
When it enters the workflow, it correctly prints out:

```
Creating bold processing workflow for "/work/03843/crn_plab/stampede2/fmriprep-phase2/data/openfmri/ds000223/.git/datalad/tmp/archives/77706772eb/ds000223_R1.0.0/sub-01/func/sub-01_task-mag_run-01_bold.nii.gz".
```

BUT, the name generated for this workflow is `func_preproc_task_mag_run_01_wf` (the subject id goes away).

**Comment by effigies** [comment]
Sure. That's how it's supposed to work, because the containing workflow has the subject ID in it.

https://github.com/poldracklab/fmriprep/blob/b7ffa00a627330e184598885ae44a635ad17ee0e/fmriprep/workflows/bold.py#L231-L233

**Comment by oesteban** [comment]
Yes, I was exactly looking at that. So why the containing workflow does not have subject ID here?. I'll keep you updated

**Comment by effigies** [comment]
I guess I'm not following the bit about the containing workflow. Each individual workflow can have whatever node names it wants. So my suspicion is that the issue isn't interference between subjects, but creating multiple workflows for the functional run. Can you verify [`subject_data['bold']`](https://github.com/poldracklab/fmriprep/blob/master/fmriprep/workflows/base.py#L409) doesn't have duplicates?

**Comment by oesteban** [comment]
I can't replicate locally :(

**Comment by oesteban** [comment]
Got it. So this is the thing, apparently datalad has a temporal copy of this file. It seems to happen that pybids is going down the `.git/` folder, so fmriprep starts workflows for:
```
/work/03843/crn_plab/stampede2/fmriprep-phase2/data/openfmri/ds000223/sub-01/func/sub-01_task-mag_run-01_bold.nii.gz
```

AND
```
/work/03843/crn_plab/stampede2/fmriprep-phase2/data/openfmri/ds000223/.git/datalad/tmp/archives/77706772eb/ds000223_R1.0.0/sub-01/func/sub-01_task-mag_run-01_bold.nii.gz
```

**Comment by oesteban** [comment]
Removing the temporal archive of datalad worked. I opened #773 that would be robust against this.
