### ISSUE TITLE
FreeSurfer reconall failures processing Talairach

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#790]
**Is talairach processing really necessary?**

This error persists after cleaning up the work and out dirs.

DS000221/sub-010251

```
#--------------------------------------------
#@# Talairach Failure Detection Sat Nov  4 14:52:51 UTC 2017
/work/03843/crn_plab/stampede2/fmriprep-phase2/derivatives/ds000221/freesurfer/sub-010251/mri

 talairach_afd -T 0.005 -xfm transforms/talairach.xfm

ERROR: talairach_afd: Talairach Transform: transforms/talairach.xfm ***FAILED*** (p=0.0293, pval=0.0034 < threshold=0.0050)

Manual Talairach alignment may be necessary, or
include the -notal-check flag to skip this test,
making sure the -notal-check flag follows -all
or -autorecon1 in the command string.
See:

http://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/Talairach
```

## Before that, I had reported this.

[recon-all.log.gz](https://github.com/poldracklab/fmriprep/files/1415698/recon-all.log.gz)
[talairach_avi.log.gz](https://github.com/poldracklab/fmriprep/files/1415702/talairach_avi.log.gz)

## And also, this subject failed as reported in #789 .

**Comment by oesteban** [comment]
@effigies would you predict some very disastrous outcome from including the `-notal-check` flag in this autorecon node?

**Comment by effigies** [comment]
@oesteban Has this been resolved?

**Comment by oesteban** [comment]
Seems so, hasn't bitten back in the last round. I presume that handling xforms is the change that fixed this issue.

**Comment by hajerkr** [comment]
@oesteban I am having the same issues with a handful of my subjects. I know it's been years but wondering if you can elaborate on how you resolved the issue? I want to avoid using the -notal-check flag only for those which this failed. Thanks and looking forward to your response.

**Comment by mgxd** [comment]
@hajerkr how do the T1w images look? This issue has poked up from time to time (see https://github.com/nipreps/fmriprep/issues/2404)
