### ISSUE TITLE
Generate CIFTI derivatives

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#794]
@satra said (#658)
> * saving to CIFTI

@effigies:
> This seems reasonable, but out of my experience so far. If you have example code that converts the type of data you'd be interested in, that would be useful. (I assume CIFTI can handle either structural or functional data, as standard NIfTI can...)

This issue propose storing derivatives to CIFTI format.

**Comment by effigies** [comment]
Just a bump on this, at @satra's request. This is pretty high priority for their group.

We have a couple options:

- Include either finding somebody using nibabel's CIFTI support to generate images
- Wrap `connectome_wb`

Satra says his group can contribute some effort, so just as a guess, ccing @mgxd.

**Comment by mgxd** [comment]
Quick question - is there a labels atlas for the MNI template fmriprep uses - `MNI152NLin2009cAsym`, similar to mindboggle's [OASIS-TRT-20 joint fusion atlas](https://osf.io/d2cmy/?action=download&version=1)?

**Comment by oesteban** [comment]
We could map that one into MNI if you'd need it

**Comment by chrisfilo** [comment]
What's the role of such labels in context of CIFTI files?

**Comment by mgxd** [comment]
@oesteban @chrisfilo we could use the labels to generate the [corresponding brain structure label](https://github.com/nipy/nibabel/blob/master/nibabel/cifti2/tests/test_cifti2io.py#L218-L238) and ijk coordinates

**Comment by chrisfilo** [comment]
I see - thanks for clarifying. It might be worth splitting this task to cover different CIFTI outputs in separate PRs.

**Comment by mgxd** [comment]
we should always have the output CIFTI's subcortical structures in the same space as the template - as more are added (#487) we'll have to generate new labels for that template, so I agree this should be broken up in separate PRs. I'm hoping to add support for common space (fsaverage5 surf, MNI152NLin2009cAsym vols) and hopefully subject space (piggybacking once #957 is merged)

@oesteban how would we go about doing this mapping?

**Comment by oesteban** [comment]
The first I'd do is running a registration using: [`niworkflows.interfaces.mni.RobustMNINormalization`](https://github.com/poldracklab/niworkflows/blob/f3ebdf5479ed8e03143677017d5d084f5a81ae90/niworkflows/interfaces/mni.py#L66). Default settings should be pretty good. I assume the template comes with a good brain mask, so everything should be pretty straightforward.

Then we would resample the template, and keep the transform somewhere (maybe in niworkflows?). It'll be extremely useful :)

**Comment by oesteban** [comment]
Closed via #1001
