### ISSUE TITLE
ANTs brain mask misaligned with FreeSurfer-conformed structurals

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#819]
Resampling the ANTs-extracted brain mask into the FreeSurfer directory can fail pretty spectacularly. I believe this is happening because the input T1w has mismatched sform/qform affines, so ANTs skull-stripping produces outputs in the qform space, and FreeSurfer uses the sform space.

### `derivatives/fmriprep/sub-01/anat/sub-01_T1w_preproc.nii.gz`

![preproc](https://user-images.githubusercontent.com/83442/32561092-3b1506f0-c460-11e7-9483-f18feaf3345b.png)

### `derivatives/fmriprep/sub-01/anat/sub-01_T1w_brainmask.nii.gz`

![brainmask](https://user-images.githubusercontent.com/83442/32561093-3b2b86f0-c460-11e7-9fd3-65c2a4ee84bb.png)

### `derivatives/freesurfer/sub-01/mri/T1.mgz`

![t1](https://user-images.githubusercontent.com/83442/32561091-3afe9442-c460-11e7-840f-0f3d4e3e4c18.png)

### `derivatives/freesurfer/sub-01/mri/brainmask.mgz`

![brainmask2](https://user-images.githubusercontent.com/83442/32561090-3ae71a1a-c460-11e7-8418-36ada219a9a9.png)

**Comment by oesteban** [comment]
This is with a T1 where you manually mismatched s/q forms?
