### ISSUE TITLE
Affines Do not Match

### ISSUE THREAD

**Issue by sadevp** [poldracklab/fmriprep#840]
Hello, 

I'm seeing this set of error after running fmriprep on this dataset on openneuro: https://openneuro.org/datasets/ds001033/versions/00001?app=FMRIPREP&version=32&job=f0e26bac-f9ec-4c3c-a176-358d9ef4bbef

There seems to be a change in 'affine_transform' as indicated in the error logs. 

<img width="901" alt="screen shot 2017-11-20 at 8 22 25 am" src="https://user-images.githubusercontent.com/26071772/33029046-5dce3b6a-cdcc-11e7-934a-07f797ca5955.png">

**Comment by effigies** [comment]
This warning is probably not a problem. We’ve recently made changes that make the warning more likely to occur, but less likely than ever to indicate anything is actually amiss.

If there is an actual problem, it will most likely appear in the reports as contours that don’t align with the images they overlay, or possibly a “pulsing” image where the before and after images are very clearly misaligned.

The next release should reduce the frequency of this warning (#837).

**Comment by chrisfilo** [comment]
This issue does not seem to be related to the warning. It's hard to debug due to: https://github.com/OpenNeuroOrg/openneuro/issues/222 but probably related to https://github.com/OpenNeuroOrg/openneuro/issues/151#issuecomment-345753651
