### ISSUE TITLE
FMRIPREP takes more than 48h to finish

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#848]
Potentially frozen 10 runs, 4 cores, 7Gb

https://openneuro.org/datasets/ds001161/versions/00001?app=FMRIPREP&version=32&job=5a12b82a921b110001c24505

**Comment by chrisfilo** [comment]
I'm actually seeing this with more datasets now. Could be related to the memory issue.

**Comment by oesteban** [comment]
I'm very inclined to think this is the memory issue. Please check with `--n_threads 1` that this is the case.

The logs have traces for only 1h, so it is very likely that a process was killed and MultiProc never heard back.

**Comment by oesteban** [comment]
Make sure we also check this on DS148/sub-20

**Comment by oesteban** [comment]
Duplicate #852
