### ISSUE TITLE
Poor EPI-T1w coregistration

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#853]
![screenshot_23](https://user-images.githubusercontent.com/238759/33336656-83a2ac9a-d425-11e7-86d1-79f1a7c67a5b.png)

https://openneuro.org/datasets/ds000148/versions/00001?app=FMRIPREP&version=36&job=5980542c-d3c3-4cf6-87a1-e1f13a929215

**Comment by oesteban** [comment]
I couldn't find which subject is this one. However, one of the reasons for this is the poor T1w reference calculation (there was a FLAIR-like image disguised as a T1w). That precluded valid contours (see the white contour in the figure.

However, looking at e.g. sub-15:

1. We see the xforms warning:
  > **Note on orientation: sform matrix set**
  > The sform has been copied from qform.

2. The BOLD data show a clear X-flip

**Comment by oesteban** [comment]
As the objective of this issue is not a problem anymore, but I've seen potential flips in other datasets I opened #988.
