### ISSUE TITLE
license files stopped working in rc12

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#866]
```
ERROR: FreeSurfer license file /opt/freesurfer/license.txt not found.
  If you are outside the NMR-Martinos Center,
  go to http://surfer.nmr.mgh.harvard.edu/registration.html to 
  get a valid license file (it's free).
  If you are inside the NMR-Martinos Center,
  make sure to source the standard environment.
  A path to an alternative license file can also be
  specified with the FS_LICENSE environmental variable.
```
rc11 worked: https://openneuro.org/datasets/ds001158/versions/00001?app=FMRIPREP&version=36&job=adeacbbb-4c78-4149-8d95-460098a2fa32

rc12 failed: https://openneuro.org/datasets/ds001158/versions/00001?app=FMRIPREP&version=37&job=bf813b2f-9484-4036-8468-556bb2a360bb

**Comment by chrisfilo** [comment]
This problem does not occur when running FreeSurfer app with the same license, so it's unlikely this is an OpenNeuro issue.

**Comment by shirareznik** [comment]
Hi,
I've noticed the issue now-
In an execution a week ago- the license worked well, and now- I've faced this issue- all of a sudden- the license isn't found.

**Comment by effigies** [comment]
Hi, can you please open a new issue with the full command you used as well as the error? Having a conversation on closed issues makes it hard to see that your problem is outstanding.

**Comment by shirareznik** [comment]
np.
Thanks!
