### ISSUE TITLE
Move anatomical workflow out into niworkflows

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#881]
The anatomical workflow is mature enough to be detached from fmriprep's base code.

This would make the anatomical workflow more visible and will allow:
  1) Move the anatomical workflow tests to niworkflows.
  2) Cache all the anatomical workflow between circle builds (speed up build time of fmriprep).

WDYT?

(option 2 could happen before 1, that would also be okay)

**Comment by effigies** [comment]
I guess my question is whether it makes sense outside of fmriprep. As it is, we pipe a lot of options in through workflow arguments, which, on a first glance would seem to make it difficult to abstract to usability in another program.

**Comment by oesteban** [comment]
Let's start with 2 for now. I personally would have interest in seeing the anatomical workflows in niworkflows, but it is true that I know how to use them too well. Other users might be clueless.

**Comment by oesteban** [comment]
As we are considering to branch a dMRIPrep out, I guess this makes more sense now.

**Comment by oesteban** [comment]
See https://github.com/poldracklab/smriprep
