### ISSUE TITLE
/usr/lib/ants/antsBrainExtraction.sh: line 117:  8754 Killed  

### ISSUE THREAD

**Issue by tragus1** [poldracklab/fmriprep#888]
ainCerebellumProbabilityMask.nii.gz
      output prefix           = highres001_
      output image suffix     = nii.gz

    N4 parameters (pre brain extraction):
      convergence             = [50x50x50x50,0.0000001]
      shrink factor           = 4
      B-spline parameters     = [200]

    Atropos parameters (extraction):
       convergence            = [3,0.0]
       likelihood             = Gaussian
       initialization         = kmeans[3]
       mrf                    = [0.1,1x1x1]
       use clock random seed  = 1

/usr/lib/ants/antsBrainExtraction.sh: line 117:  8754 Killed                  $cmd
Return code: 1

**Comment by chrisfilo** [comment]
How much memory is available on the system? Are you running via Docker?

**Comment by tragus1** [comment]
Hi Chris. 16 GB Ram are available. And I'm running via Docker. Do you have any ideas what's the reason for killing my process?
Thanks!

**Comment by effigies** [comment]
Can you provide your full fmriprep command and version?

**Comment by jdkent** [comment]
Bouncing off of @chrisfilo's question, as far as I'm aware, Docker defaults to giving 2GB towards running containers (like fmriprep), so while your system has 16GB, docker may only have access to 2GB. See [here](https://docs.docker.com/docker-for-windows/#advanced) for windows and [here](https://docs.docker.com/docker-for-mac/#advanced) for mac.

**Comment by tragus1** [comment]
Thank you problem solved. It was because of the default 2GB RAM Docker gives to containers.
