### ISSUE TITLE
Unusable BOLD-T1w coregistration in ds000232

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#896]
![image](https://user-images.githubusercontent.com/238759/34181586-aa0a3b98-e4c7-11e7-9b23-e1c5be3fc76e.png)

sub-02 ses-03_task-main_run-01

Could be related to #895

**Comment by oesteban** [comment]
I can confirm that this is not one of the worst cases. Limited FoV is a hard problem. Do you recall if this dataset has fieldmaps?

**Comment by chrisfilo** [comment]
It does not have fieldmaps. I did a bit of digging and found that people recommend acquiring a full brain BOLD scan and using it as an intermediate coregistration target. This dataset did not have such extra scan.

I also read that BBR should be pretty robust to such partial FOV acquisitions - unless the initialization screwed things up. Might be worth looking at the initialization.

**Comment by oesteban** [comment]
That all seems completely reasonable. Agree on the probable initialization problem :+1:
