### ISSUE TITLE
Poor BOLD-T1w coregistration in ds000224 (Midnight Scan Club)

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#898]
![image](https://user-images.githubusercontent.com/238759/34181900-e1c8468c-e4c8-11e7-9297-a681cc227c25.png)

Visible to some extent in all runs. Could be related to SyN-SDC (which was applied).

**Comment by oesteban** [comment]
SyN-SDC has been calculated, but it is not used. Those co-registration problems are precisely revealing the susceptibility distortion.

I don't think we can do much about this, just check if BBR/bbregister fell back to the 6 parameters version.

**Comment by chrisfilo** [comment]
Update - this dataset had fieldmaps, but they were not used due to missing IntendedFor fields. #783

**Comment by oesteban** [comment]
Seems like the `IntendedFor` field was the root of this issue:

https://s3.amazonaws.com/fmriprep/ds000224/fmriprep/sub-MSC05.html
https://s3.amazonaws.com/fmriprep/ds000224/fmriprep/sub-MSC08.html
https://s3.amazonaws.com/fmriprep/ds000224/fmriprep/sub-MSC09.html
https://s3.amazonaws.com/fmriprep/ds000224/fmriprep/sub-MSC10.html

I'll close it for now, please reopen if you feel this should be further investigated. Opened #1085 to follow up on fieldmap SDC, as the fieldmap correction seems improvable.
