### ISSUE TITLE
FreeSurfer brain mask issue in ds000148

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#903]
ANTs worked well
![image](https://user-images.githubusercontent.com/238759/34182803-a28d8762-e4cc-11e7-834e-bb9ed7980004.png)

But Freesurfer applied the mas with an offset
![image](https://user-images.githubusercontent.com/238759/34182831-b480173c-e4cc-11e7-8058-615c6529b9f7.png)

sub-28

**Comment by oesteban** [comment]
Seems like `t1_merge` did not perform very well. The ANTs mask also includes part of the eyeball so I would say it is not perfect either.

**Comment by oesteban** [comment]
Look at the raw data first

**Comment by oesteban** [comment]
This is a duplicate #841.
