### ISSUE TITLE
Too conservative BOLD brain mask in ds000140

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#904]
![image](https://user-images.githubusercontent.com/238759/34182901-f2085812-e4cc-11e7-8cd2-d9ddd44fe67c.png)

sub-32_task-heatpainwithregulationandratings_run-02

Could be related to #902

**Comment by oesteban** [comment]
Ugh. I've seen like this in my reports, but not as bad as #902.

**Comment by oesteban** [comment]
This is fixed
