### ISSUE TITLE
BIDS format error

### ISSUE THREAD

**Issue by tragus1** [poldracklab/fmriprep#909]
Dear fmriprep commuity, I got the following error when I started to run fmri prep. My data is in validated BIDS format.

Do you have any idea what caused that problem?

thanks!
```
docker run -ti --rm \
>     -v $HOME/Desktop/TAUREST_BIDS:/data:ro \
>     -v $HOME/Desktop/taurest_out:/out \
>     -v $HOME/Desktop/fs_file/license.txt:/opt/freesurfer/license.txt \
>     poldracklab/fmriprep:latest \
>     /data /out/out \
>     participant \
>     --ignore fieldmaps
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 321, in build_workflow
    bids_dir, participant_label=opts.participant_label)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/utils/bids.py", line 87, in collect_participants
    'may need to adjust your "File sharing" preferences.', bids_dir)
fmriprep.utils.bids.BIDSError:
---------- BIDS root folder: "/data" ----------
           Could not find participants. Please make sure the BIDS data structure is present and correct. Datasets can be validated online using the BIDS Validator (http://incf.github.io/bids-validator/).
If you are using Docker for Mac or Docker for Windows, you may need to adjust your "File sharing" preferences.
-----------------------------------------------
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.0.0', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 242, in main
    fmriprep_wf = retval['workflow']
  File "<string>", line 2, in __getitem__
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
KeyError: 'workflow'
```

**Comment by effigies** [comment]
Can you show the contents of `$HOME/Desktop/TAUREST_BIDS`?

**Comment by tragus1** [comment]
~/Desktop/TAUREST_BIDS$ ls
dataset_description.json  sub-control01  sub-control02  task-rest_bold.json

**Comment by effigies** [comment]
That looks reasonable... Is your dataset defaced? Is there any chance you could make it available to us to debug?

Failing that, if you can use [tree](https://www.computerhope.com/unix/tree.htm), there might be something else causing the issue.

**Comment by tragus1** [comment]
TAUREST_BIDS
├── dataset_description.json
├── sub-control01
│   ├── anat
│   │   └── sub-control01_T1w.nii.gz
│   └── func
│       └── sub-control01_task-rest_bold.nii.gz
├── sub-control02
│   ├── anat
│   │   └── sub-control02_T1w.nii.gz
│   └── func
│       └── sub-control02_task-rest_bold.nii.gz
└── task-rest_bold.json

6 directories, 6 files

**Comment by tragus1** [comment]
you can find my test dataset here: https://databox.med.uni-muenchen.de  PW: CYQ2-NUMN-Z3RU
the data is not defaced

**Comment by effigies** [comment]
I think the issue is that you don't have functional data. Try using the `--anat-only` flag.

**Comment by tragus1** [comment]
thank you, but I have resting state data in the func folders. Also fmriprep was working with that dataset on a mac, now I moved to a linux machinge because it has more processing power. Can something else cause this error?

**Comment by effigies** [comment]
I wonder if it's a permissions issue. That would also explain why `tree` didn't see the functional images. (Incidentally, I can't download that without a box number.)

**Comment by tragus1** [comment]
Sorry, here is the box number: F8WH 
Permission is given rwx to the TAUREST_BIDS folder and all subfolders

**Comment by effigies** [comment]
I also redacted the box number, to keep this issue from providing public access to subject data.

**Comment by effigies** [comment]
You may need to update your `PATH` environment variable to include the install location for pip-installed programs. For example:

```Shell
$ which fmriprep-docker
/home/cjmarkie/.anaconda3/bin/fmriprep-docker
$ echo $PATH           
/home/cjmarkie/.anaconda3/bin:/opt/freesurfer/bin:/opt/freesurfer/fsfast/bin:/opt/freesurfer/tktools:/usr/share/fsl/5.0/bin:/usr/lib/fsl/5.0:/opt/freesurfer/mni/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/afni/bin
```

To find out where it is, try:

```Shell
$ yes n | pip uninstall fmriprep-docker | grep bin
  /home/cjmarkie/.anaconda3/bin/fmriprep-docker
```

(The `yes n` ensures that you don't actually remove the program.)

**Comment by tragus1** [comment]
Hi,

when I type in: which fmriprep-docker 
it gives me nothing back
so I set in my .profile a path to export PATH=$PATH: /home/boris/.local/bin/fmriprep-docker

but i only get comand not found when I restart the terminal.

**Comment by effigies** [comment]
So you get the following?

```Shell
$ yes n | pip uninstall fmriprep-docker | grep bin
  /home/boris/.local/bin/fmriprep-docker
```

Can you try `chmod +x /home/boris/.local/bin/fmriprep-docker`?

**Comment by tragus1** [comment]
I get: /home/boris/.local/bin/fmriprep-docker thats right. 
Unfortunately chmod +x /home/boris/.local/bin/fmriprep-docker makes no difference.
I have really no idea whats the problem here.

**Comment by effigies** [comment]
Oh, your `PATH` line should be:

```Shell
export PATH=$PATH:/home/boris/.local/bin
```

You want the containing folder, not the full paths of the individual programs. Sorry, didn't catch that the first time I read.

**Comment by tragus1** [comment]
thats true but it looks like there must be another problem. It still gives me comand not found when I start the terminal

**Comment by effigies** [comment]
How about before your `export` command you add:

```Shell
echo Setting PATH...
```

And make sure you see that when you start your terminal. Then you can verify that the `.profile` is being loaded. If it is, could you `echo $PATH` and post the results here? I'm having trouble seeing what the issue could be.

**Comment by tragus1** [comment]
It seems that my .profile is not really loding because I still got only: comand not found but not the echo.
When I echo $PATH i get: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files/MATLAB/R2017a/bin:/mnt/c/Program Files/MATLAB/R2011b/bin:/mnt/c/Users/Boris Rauchmann/AppData/Local/Microsoft/WindowsApps:/snap/bin

**Comment by effigies** [comment]
If your shell is bash (`echo $SHELL` to verify), you can add the line to `.bashrc`. I assume most other shells have something similar (e.g. `.cshrc` for csh, `.zshrc` for zsh, etc.).

**Comment by tragus1** [comment]
I added these two lines in my .bashrc:

echo Setting PATH=$PATH:/home/boris/.local/bin
export PATH=$PATH:/home/boris/.local/bin

but without success, I´m sorry for bothering you with this. Can the problem be that I´m running ubuntu on a windows 10 system?

**Comment by effigies** [comment]
I suppose it's possible. I have no idea how that works. You might make better progress getting your shell properly set up on the Ubuntu forums.

However, in the meantime, you can always directly run:

```
/home/boris/.local/bin/fmriprep-docker ...
```

**Comment by tragus1** [comment]
Thank you for your patience and for your help. Maybe I can get my shell set with ubuntu forums help.

**Comment by tragus1** [comment]
I still got this problem:

boris@Rechenknecht:~$ /home/boris/.local/bin/fmriprep-docker /home/Desktop/TAUREST_BIDS /home/Desktop/taurest_out \
>      --fs-license-file /home/Desktop/fs_file/license.txt
RUNNING: docker run --rm -it -v /home/Desktop/fs_file/license.txt:/opt/freesurfer/license.txt:ro -v /home/Desktop/TAUREST_BIDS:/data:ro -v /home/Desktop/taurest_out:/out poldracklab/fmriprep:1.0.0 /data /out participant
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 321, in build_workflow
    bids_dir, participant_label=opts.participant_label)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/utils/bids.py", line 87, in collect_participants
    'may need to adjust your "File sharing" preferences.', bids_dir)
fmriprep.utils.bids.BIDSError:
---------- BIDS root folder: "/data" ----------
           Could not find participants. Please make sure the BIDS data structure is present and correct. Datasets can be validated online using the BIDS Validator (http://incf.github.io/bids-validator/).
If you are using Docker for Mac or Docker for Windows, you may need to adjust your "File sharing" preferences.
-----------------------------------------------
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.0.0', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 242, in main
    fmriprep_wf = retval['workflow']
  File "<string>", line 2, in __getitem__
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
KeyError: 'workflow'
fmriprep: Please report errors to https://github.com/poldracklab/fmriprep/issues

**Comment by effigies** [comment]
Okay. Glad you got back to this point. :-) I wonder if this is just some other weird consequence of using Ubuntu on Windows. Can you just use Docker for Windows directly?

**Comment by tragus1** [comment]
Yeah probably. I'll try Docker for windows next :)

**Comment by effigies** [comment]
Sounds good. Thanks for sticking with this.

**Comment by oesteban** [comment]
Hi @tragus1, did you finally find out the problem. Anything we can do to help?

**Comment by oesteban** [comment]
Hi @tragus1, did you finally find out the problem. Anything we can do to help?

**Comment by tragus1** [comment]
I changed to another system without a solution on this system

**Comment by oesteban** [comment]
Please reopen if this happens again.
