### ISSUE TITLE
Grouping multi-echo runs

### ISSUE THREAD

**Issue by emdupre** [poldracklab/fmriprep#921]
As discussed in #914, the previous implementation of grouping multi-echo scans together introduced unintended bugs. I've [created a new function, and tested it over some sample files](https://gist.github.com/emdupre/78c34b91669f22b1144e640d0e7a4166), which seems to perform as expected.

Is there other testing data that should be considered at this point?

**Comment by emdupre** [comment]
Ha, sorry I had missed this! But great timing 😄 
I just opened a PR (#956) that adds a circle test on one subsampled subject from ds000210, but I'm happy to update it to only trigger for specific branches. Do you think it's going to an issue to make sure that branches always includes a set key word? Assuming at some point someone other than me might make a multi-echo related commit.

**Comment by oesteban** [comment]
Closed with #891
