### ISSUE TITLE
Linking readthedocs tips for contributing in CONTRIBUTING.md

### ISSUE THREAD

**Issue by emdupre** [poldracklab/fmriprep#922]
Would it make sense to link to the [readthedocs description of Contributing to FMRIPREP](http://fmriprep.readthedocs.io/en/latest/contributors.html) in the CONTRIBUTING.md? That way all information for new contributors is in one place, including how to set up their development environment. I'm happy to submit a PR for this, if desired!

**Comment by effigies** [comment]
That seems like a good idea to me.
