### ISSUE TITLE
slicetiming in bids versus nifti header?

### ISSUE THREAD

**Issue by jlhanson5** [poldracklab/fmriprep#932]
Hello fmriprep folks,

I had some (public-access) datasets where the json files omitted the slice timing info, but that info was included in the relevant NIFTI files. Will 3dTshift in fmriprep catch it because it's in the NIFTI files? 

Thanks for the info!
Jamie.

**Comment by chrisfilo** [comment]
SliceTiming needs to be defined in a BIDS compatible JSON file for the correction to be attempted. See: https://github.com/poldracklab/fmriprep/blob/af2973ae00741ba8b7d1dd023c9362baa6ebc647/fmriprep/workflows/bold/base.py#L259

**Comment by effigies** [comment]
Does it make sense to calculate SliceTiming from a NIfTI header if it's present and there's no JSON entry?

Failing that, it shouldn't be too hard to make a little tool that would read a NIfTI header and create a JSON snippet with `SliceTiming` (and `PhaseEncoding`, if defined) that can be easily inserted into the JSON sidecar.

This could be implemented in the validator as a warning, e.g. "SliceTiming is specified in the NIfTI header, but not in the JSON sidecar. Add the following line ..."
