### ISSUE TITLE
adding multi-echo data to circleci tests

### ISSUE THREAD

**Issue by emdupre** [poldracklab/fmriprep#934]
I'd like to add mutli-echo data to [circleci integration testing](https://github.com/poldracklab/fmriprep/blob/master/circle.yml). However, it seems that all of the used data is hosted on an OSF project that I don't have access to. 

Is there a preferred method for adding new tests to FMRIPREP?

**Comment by oesteban** [comment]
OSF is the preferred way of adding data for testing. Please send me an email with your OSF login and I will give you access :)

**Comment by oesteban** [comment]
Closed with #891
