### ISSUE TITLE
[BUG] fmriprep-docker 1.0.4 did not deploy to Pypi

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#935]
https://circleci.com/gh/poldracklab/fmriprep/1369

```
Writing fmriprep-1.0.4/setup.cfg
creating dist
Creating tar archive
removing 'fmriprep-1.0.4' (and everything under it)
running upload
Submitting dist/fmriprep-1.0.4.tar.gz to https://upload.pypi.org/legacy/
Upload failed (503): Service Unavailable
error: Upload failed (503): Service Unavailable
```

Surprisingly, fmriprep-1.0.4 seems to be the latest version available in PyPi

**Comment by chrisfilo** [comment]
The solution might be as simple as rerunning the job on CircleCI

**Comment by oesteban** [comment]
It's going to fail because apparently fmriprep-1.0.4 was successfully
uplodaded :(

**Comment by oesteban** [comment]
Closing since 1.0.5 deployed correctly without further actions.
