### ISSUE TITLE
aparc+aseg outputs

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#937]
@satra requested FreeSurfer aparc+aseg parcellations sampled into the output spaces, BOLD resolution.

It probably makes the most sense to treat these comparably to brain masks, i.e. one for each preprocessed BOLD series, even though these should be identical, assuming that all BOLD series have the same voxel size.

This may be very easy thanks to #431.

**Comment by oesteban** [comment]
I totally second this idea

**Comment by oesteban** [comment]
(and have some code under the hood)
