### ISSUE TITLE
[DOC] Add a FAQ

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#947]

**Comment by effigies** [comment]
Feel free to reject this, but maybe it would be good to start the FAQ as a wiki page, so it can be updated without lengthy review. Then at release time, we can update the FAQ in the docs (including a link to the wiki page for recent changes).

If I get stuck on something, I might go through old issues and try to tag things that have come up more than once as FAQ fodder.

**Comment by oesteban** [comment]
I think it is a good idea indeed

**Comment by oesteban** [comment]
@effigies https://github.com/poldracklab/fmriprep/wiki/FAQ:-Frequently-asked-questions
