### ISSUE TITLE
Save bold reference images 

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#960]
See https://neurostars.org/t/location-of-bold-reference-image-in-fmriprep-1-0-6/1284

**Comment by oesteban** [comment]
`variant-reference` ?

**Comment by effigies** [comment]
What about just type `_ref.nii.gz`? Similar to `sbref`, but it will end up being `*_bold_ref.nii.gz`, so I think it will be fairly easy to read.

**Comment by chrisfilo** [comment]
+1 for ref.

Best,
Chris
