### ISSUE TITLE
6157 Segmentation fault

### ISSUE THREAD

**Issue by tragus1** [poldracklab/fmriprep#961]
Dear fmriprep community,

I get the following error when running fmriprep_docker-1.0.6.post2 on my unbuntu 16.

/usr/lib/ants/antsBrainExtraction.sh: line 117:  6157 Segmentation fault      (core dumped) $cmd
Return code: 1

Can anyone help me with that issue?

Thank you,
Boris

**Comment by chrisfilo** [comment]
Most likely memory issue, have a look here https://github.com/poldracklab/fmriprep/issues/756#issuecomment-335968692

**Comment by oesteban** [comment]
Hi @tragus1, could you confirm that this is a memory issue?

**Comment by tragus1** [comment]
Yes problem solved it is a memory issue

**Comment by oesteban** [comment]
Thanks for the feedback!
