### ISSUE TITLE
 BOLD brain mask depicted in the ROIs reportlet does not correspond to the mask produced in the outputs

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#963]
Background: https://neurostars.org/t/fmriprep-1-0-6-2-issues-semi-random-brain-mask-failure-and-super-bright-areas-in-epi/1303/8

EDIT OE: (moved to new issue #982)

reportlet:
![image](https://user-images.githubusercontent.com/238759/35985579-d029b5ea-0cab-11e8-9f5e-4776a03e1d70.png)

output mask:
![image](https://user-images.githubusercontent.com/238759/35985603-dcb4c9bc-0cab-11e8-8eff-63a746708e48.png)

**Comment by chrisfilo** [comment]
![image](https://user-images.githubusercontent.com/238759/35994571-a674a6aa-0cc5-11e8-8bec-f0c506c79c33.png)
Seems like a 3dUnifize issue.

**Comment by chrisfilo** [comment]
Similar problem is also visible in: https://openneuro.org/datasets/ds001216/versions/00002?app=FMRIPREP&version=48&job=5a7b6fd4831753000151c620 

https://s3.amazonaws.com/openneuro.outputs/89832c01e43fee4b165e81a351af7b26/37c908e6-f88d-46e3-a0e3-d9c7e2dab4ac/fmriprep/sub-30009.html

**Comment by oesteban** [comment]
I can confirm that this is also happening on our Phase 2 test base. I'm seeing this on ds000237/sub-0[3,6] and some edge case on sub-01.

**Comment by oesteban** [comment]
Identified the source - this mask calculation is failing horribly:

https://github.com/poldracklab/fmriprep/blob/3e7d830e0322435532e875ec8c51213f9f6fec3f/fmriprep/workflows/bold/util.py#L176

**Comment by chrisfilo** [comment]
This might explain #964, but why this mask calculation fail is not visible in the ROIs reportlet?

**Comment by chrisfilo** [comment]
I don't understand why you renamed this issue. I believe the original problem is still unresolved - the mask plotted in the report comes from a different estimation process than the one (two?) leading to _brainmask file in the outputs.

**Comment by oesteban** [comment]
Sorry for the name change

**Comment by oesteban** [comment]
Sorry for the name change. I didn't understand the issue.

I've opened and closed #982, which is the issue that has been really addressed, restored the name and reopened this issue.

Also, I hope this message triggers a notification that makes all aware of these changes.

**Comment by chrisfilo** [comment]
No worries. Thanks for clarifying.

**Comment by chrisfilo** [comment]
@oesteban #1002 mentioned that the fix was only for the MNI part - if the T1w requires fixing maybe we should reopen?

**Comment by oesteban** [comment]
T1 was also fixed (a726ac4)

**Comment by chrisfilo** [comment]
Great - thanks!

Best,
Chris
