### ISSUE TITLE
Overzelous BOLD skullstripping

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#964]
Background: https://neurostars.org/t/fmriprep-1-0-6-2-issues-semi-random-brain-mask-failure-and-super-bright-areas-in-epi/1303/8

![image](https://user-images.githubusercontent.com/238759/35985654-fbe80cf4-0cab-11e8-8290-0a4cefb03784.png)

related to #963

**Comment by oesteban** [comment]
Fixed through #966+#978
