### ISSUE TITLE
Signed integer datatype of inputs

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#968]
Oftentimes, input datasets show signed integer data types in their headers while reconstructed MR data is, intrinsically unsigned (except for particular acquisitions like complex-type phase difference maps).

Unless you hold me back, @effigies and @chrisfilo, I'll quickly add to the input validation an additional check that converts niftis with signed integer types into the corresponding unsigned type.

A new warning will be issued in the reports when this is done.

**Comment by chrisfilo** [comment]
Couple of questions:
- what if input data is unsigned and includes values below zero?
- will this increase space requirements for working dir?

**Comment by oesteban** [comment]
> Couple of questions:
> - what if input data is unsigned and includes values below zero?
If input data is unsigned the proposed solution would not change anything. That said, if input data is unsigned but includes values meant to be below zero I don't think any software would understand that.

Only the signed data types are problematic because most of the software assume that data are unsigned anyways and everything works.

> - will this increase space requirements for working dir?
No, as the equivalent unsigned types will be assigned (i.e. int16 takes as much space as uint16).

**Comment by effigies** [comment]
Is there any reason to think having a signed data type is a problem? Or is the issue a lost bit of precision?

Not sure what the trade-offs are here.

**Comment by oesteban** [comment]
Signed integer data types are problematic. Many scans in OpenfMRI have that. Most software tools (ants, FSL, AFNI, etc.) will use them as if they were unsigned. However, our custom code don't, except for visualization since nilearn automatically adjusts the colormaps to the image limits.

I would turn around the argument. Is there any reason not to normalize the data type when we know that they cannot not be signed?

There is no loss of precision as types would be replaced with their unsigned equivalents.

**Comment by effigies** [comment]
Supposing you have a signed type and a negative value, what's the proposed fix for that file?

**Comment by oesteban** [comment]
How that could happen? Except for particular types of fieldmaps, all other images should strictly be non-negative.

**Comment by effigies** [comment]
So it would be an error condition? I'm okay with making that decision, but I'm just a little uncomfortable saying "This can never happen, so we don't need to worry about it."

**Comment by oesteban** [comment]
FMRIPREP would write a WARNING on the report, noticing the user that their headers contain potentially problematic data.

Right now we are saying (in this respect only): "I better don't look into the headers, everything seems to be working fine".

What about this? We look into the headers AND also check the `scl_inter` header. If it is not zero, it is clear that there is an intention of setting a signed data type. Otherwise, we assume that the datatype is wrong.

**Comment by effigies** [comment]
I understand the warning bit. I'm just saying if we then find an `int16` value that can't be coerced into the `uint16` range (i.e. negative), then it should be an error, or at least a bigger warning. It sounds like you're convinced that it would be pretty rare for that to be an issue, in any event.

I don't think using `scl_inter` in the way you suggest is valid. It doesn't seem to follow that having a floating point interpretation of the data signals an intention to use signed values.

But to be clear, I'm fine with the warnings. I just wanted to understand the issue here. And make sure that we actually cover edge cases that *should* never happen.

**Comment by oesteban** [comment]
I am reconsidering this idea. While I liked the correctness in the beginning, it is true that after some resamplings (and depending on the interpolation kernel, but Lanczos and BSplines will do this) we may have negative values. Then using unsigned reference would introduce truncation errors.

Since it is not clear if this actually solves a problem (as @effigies said), I'll put this on hold and close for now. If I can come up with a more developed idea of the issue and solution, I'll reopen then.

Thanks for the comments @effigies :)
