### ISSUE TITLE
QUESTION: unclosed `<div>`?

### ISSUE THREAD

**Issue by kaczmarj** [poldracklab/fmriprep#971]
Hello,

I was wondering whether this `<div>` should actually be `</div>`. It renders properly, but I was just curious.

https://github.com/poldracklab/fmriprep/blob/ce01c27e1fd26d7550468e0180ae65fbb2b3b8ed/fmriprep/viz/report.tpl#L58

**Comment by effigies** [comment]
Looks like it. Probably renders properly because the `</nav>` implicitly closes both `<div>`s. Mind submitting a quick fix?
