### ISSUE TITLE
Sphinx 1.7.0 (released today) breaks documentation

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#973]
Builds have started to break. IMHO this is the change that originates the problem sphinx-doc/sphinx#2557

**Comment by effigies** [comment]
Not sure if this is the same issue (on my phone, so checking is a pain), but I did run into a failure in nipy/nipype#2437 this morning. Just a thing to check, in case it turns out we were also using the numpydoc extension.
