### ISSUE TITLE
CRITICAL: X-flip of BOLD data.

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#988]
Example DS000148/sub-15:

![ds148-sub-15-flipx-bold](https://user-images.githubusercontent.com/598470/36287073-832ac114-1267-11e8-8566-583b28b6d916.png)
![ds148-sub-15-flipx-t1](https://user-images.githubusercontent.com/598470/36287072-83184b88-1267-11e8-8279-2a2147c4746e.png)

This run had the xforms warning:
  > **Note on orientation: sform matrix set**
  > The sform has been copied from qform.

**Comment by chrisfilo** [comment]
Might be worth painting a virtual vitamin fiducial on the raw data and reprocessing it to verify it is indeed a flip.

**Comment by oesteban** [comment]
If the problem is derived from xforms, we can't be sure that we placed the fiducial in the correct side. I'd try finding very asymmetric brains in the two datasets. Possibly the one failing in #989 is a good candidate.

**Comment by effigies** [comment]
I interpreted @chrisfilo's comment as testing for whether FMRIPREP flips the image. As long as it's in the right side in both the raw data and preprocessed, then we're okay (though perhaps the dataset has a problem).

**Comment by chrisfilo** [comment]
Is this ds000108 or ds000148? 

As a side note: I would not put too much effort in trying to fix issues that come from data with corrupted or missing xforms (like those listed in https://openfmri.org/dataset-orientation-issues/).

**Comment by oesteban** [comment]
I originally posted this for DS000148. I added the DS000108 label after finding that #989 is likely a flip as well due to wrong headers.

That said, DS148's have an apparently valid qform matrix.

**Comment by oesteban** [comment]
I'm currently re-running these two with X-flipped qforms. After confirming they look good this way, we'll have to figure out if it is a dataset problem or an FMRIPREP problem. For DS108 seems like this is a dataset problem. With DS148 this will be harder to assess.

**Comment by oesteban** [comment]
Okay, after running DS148 with the artificial flip now it is clear for some subjects (particularly the asymmetry of ventricles of sub-33 was very helpful) that the original images are correctly oriented.

I'll rerun DS148 with the original qform and post here sub-15.

**Comment by oesteban** [comment]
After all, the first picture I posted is not from ds148, I must have confused accession numbers. I've opened #997 for the particular features of DS148. However, this issue can be closed as it is a duplicate of #989.
