### ISSUE TITLE
Coregistration failure - 90 degree rotation (FLIRT)

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#999]
https://openneuro.org/datasets/ds001236/versions/00002?app=FMRIPREP&version=53&job=7415ba16-d476-4d62-ad64-fae9da437943

![reg_failure](https://user-images.githubusercontent.com/238759/36469704-ffd1a244-169c-11e8-8dd7-b3faf2499e39.gif)

Context https://neurostars.org/t/distortion-correction-errors/1279

**Comment by chrisfilo** [comment]
Using the new SanitizeImage interface might be a good place to start.

**Comment by chrisfilo** [comment]
The problem is still present even if no susceptibiliyt distortion correction is performed. 
https://openneuro.org/datasets/ds001236/versions/00002?app=FMRIPREP&version=53&job=3734dfcf-c09a-41aa-9db6-e32a4bb3115f

**Comment by chrisfilo** [comment]
I previously thought this had something to do with PhaseEncodingDirection of the _bold file, but no I see it is happening whether it is set to "j" or "j-". It seems the problem happens when FLIRT is used to coregister vs bbregister.

**Comment by emdupre** [comment]
Just to +1 this, I'm seeing something similar with the generated aCompCor mask.

<img width="1291" alt="screen shot 2018-02-21 at 13 50 16" src="https://user-images.githubusercontent.com/15017191/36499120-49b63534-170e-11e8-9dd1-93a3c3015288.png">

**Comment by chrisfilo** [comment]
huh - that was with bbregister? Could be a slightly different issue. Could you upload the data to OpenNeuro.org so I could try to debug it?

**Comment by emdupre** [comment]
It says the bbregister refinement was rejected so I'm assuming that's not what it used. Happy to upload, though !

**Comment by effigies** [comment]
It's at least using the bbregister path. The FreeSurfer path uses mri_coreg and bbregister, and falls back to mri_coreg if the bbregister refinement is too different from a basic rigid registration. The FLIRT path follows the same principle, but it uses FLIRT and FLIRT+BBR.

**Comment by chrisfilo** [comment]
I found a solution for the FLIRT related issue, but I could not replicate the issue reported by @emdupre using FMRIPREP 1.0.7 (with or without freesurfer) on the sample data provided. Maybe it's something different or related to dev code you've been currently working on?

![image](https://user-images.githubusercontent.com/238759/36553249-b0517df6-17b0-11e8-851d-78a32a4ccdc0.png)

**Comment by emdupre** [comment]
I'll look into it and open another issue if necessary !

**Comment by chrisfilo** [comment]
Thanks!

Best,
Chris
